### ISSUE TITLE
`kapacitor show` does not properly escape regexes

### ISSUE THREAD

**Issue by phemmer** [influxdata/kapacitor#1002]
If you have a task with a regex in it, when you run `kapacitor show` on the task, slashes in the regex are not properly escaped.

```
stream | from().measurement('diskio') | where(lambda: "path" =~ /\/a\/b\/c/)
```

will output from `kapacitor show` as:
```
stream
    |from()
        .measurement('diskio')
    |where(lambda: "path" =~ //a/b/c/)
```

**Comment by nathanielc** [comment]
@phemmer What version are you using? This has been fixed in https://github.com/influxdata/kapacitor/commit/4604e64808f9cefff0b7f785c0bc9e01fccd05ba
