### ISSUE TITLE
Kapacitor crashes during /replay/query 

### ISSUE THREAD

**Issue by dbienapfl** [influxdata/kapacitor#1004]
If you submit a job to "/replay/query" and there is a 'group by' clause in your query, kapacitor 1.0.2 (deb package) will crash quite reliably:

{
   "task":"Generic_disk_watch_52756c6d46379338",
   "id":"Generic_disk_watch_52756c6d46379338",
   "recording-time":true,
   "clock":"fast",
   "query":"SELECT \"value\",host,cluster FROM graphite.\"default\".\"disk_free_percent_rootfs\" WHERE time > 1476943200s and time < 1476946800s **_GROUP BY host,cluster_**;"
}

I can provide more color if you would like but simply cleaning up my 'GROUP BY' clause allows things to run smoothly.

**Comment by rossmcdonald** [comment]
@dbienapfl Does the Kapacitor service panic? If so, can you provide the logs from the time of the crash?

**Comment by dbienapfl** [comment]
The log file stops entirely - no further entries.  All requests to kapacitor just time out - nothing returns from the http api - all connections just time out.

The docker container stays alive and can be logged into and appears normal.

The AWS vm shows un-remarkable load (<2 on 4cpu, while running influxdb @ 8-10k pts/min, and the now frozen kapacitor)

At the time of the last failure there was about 800MB of available ram and no swap was in use.

The process remains alive and continues to eat CPU but its memory consumption stops changing.

TOP snapshot:

root@influxdb-stage-1:~# top
top - 19:11:09 up 7 days,  7:51,  3 users,  load average: 1.85, 1.98, 1.99
Tasks: 195 total,   1 running, 194 sleeping,   0 stopped,   0 zombie
%Cpu(s): 36.2 us,  2.0 sy,  0.0 ni, 59.8 id,  0.6 wa,  0.0 hi,  0.7 si,  0.7 st
KiB Mem:   7659516 total,  6623664 used,  1035852 free,   159356 buffers
KiB Swap:        0 total,        0 used,        0 free.  2506324 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
29413 root      20   0  433788 198120   8820 S 106.1  2.6   1:07.40 kapacitord

[kapacitor_logs.out.gz](https://github.com/influxdata/kapacitor/files/557257/kapacitor_logs.out.gz)
[strace_kapacitor.out.gz](https://github.com/influxdata/kapacitor/files/557258/strace_kapacitor.out.gz)

I was not able to get the '[stats]' function to work properly - as I suspect this thing may just be thrashing on memory/GC but this is what I have for now.  Let me know if you could use anything else.

**Comment by nathanielc** [comment]
@dbienapfl Were there any logs sent to stderr probably found in `/var/log/kapacitor/kapacitor.err`

**Comment by dbienapfl** [comment]
[logging]
  file = "STDERR"
  level = "DEBUG"

All of the output will be found in the previously attached kapacitor_logs.out file - this is 2/3 of the mystery - there is no useable output that I am able to find.

During my testing I did see one trend - the window of time asked for in the query had an effect on the crash - extremely short time periods < 1min could flush properly following a restart of the container.  Longer windows caused crashes within a few seconds.  This is the behavior that lead me to my statements about memory/GC.

Let me try and recreate this failure outside of a docker where I can not interrupt our staging environment.  I will post any finding here as soon as I can.

**Comment by nathanielc** [comment]
@dbienapfl Yeah it sounds like Kapacitor might be OOMing, because of the amount of data being queried. Which is why I asked about  stderr logs since I expected to see a gloang panic stack trace.

**Comment by docmerlin** [comment]
As there haven't been any replies since 2016, I am closing this issue.
