### ISSUE TITLE
InfluxDB 0.13.1 not delivering points to any subscription.

### ISSUE THREAD

**Issue by politician** [influxdata/kapacitor#1006]
I'm trying to troubleshoot a kapacitor installation, but I cannot prove that `influxdb` is correctly sending points to a subscription regardless of whether it's UDP, TCP, or HTTP.

We're starting from a setup that is working correctly:
- standard influxdb 0.13.1 install
- standard telegraf 0.13.1 install listening on UDP port 8092
- `echo "test n=1" > /dev/udp/127.0.0.1/8092` from Bash writes points to telegraf
- `select * from test` returns expected results proving that point entry is working correctly

However, the subscriptions functionality seems to be non-operational and/or disabled.

**Is there a special `influxdb.conf` flag that I need to enable in order to activate subscriptions? Is/was this a known bug in 0.13.1?  Does my test of listening on a port configured to receive subscriptions traffic constitute a valid test?**

### UDP
1. (bash 1) `nc -ulp 8100`  listen on UDP 8100
2. (bash 2) `echo "testing" > /dev/udp/127.0.0.1/8100` proves `nc` working correctly
3. (influx) `create subscription "pol-udp" ON "telegraf"."default" DESTINATIONS ALL "udp://127.0.0.1:8100"`
4. (bash 2) `echo "test,mode=\"udp\" n=1" > /dev/udp/127.0.0.1/8092` (points arrive in influx)
5. Observe that nothing arrives on the `nc` listener.

### TCP
1. (bash 1) `nc -lp 8101`  listen on UDP 8101
2. (bash 2) `echo "testing" > /dev/tcp/127.0.0.1/8101` proves `nc` working correctly
3. (influx) `create subscription "pol-tcp" ON "telegraf"."default" DESTINATIONS ALL "tcp://127.0.0.1:8101"`
4. (bash 2) `echo "test,mode=\"tcp\" n=1" > /dev/udp/127.0.0.1/8092` (points arrive in influx)
5. Observe that nothing arrives on the `nc` listener.

### HTTP
1. (bash 1) `nc -lp 8102`  listen on UDP 8102
2. (bash 2) `echo "testing" > /dev/tcp/127.0.0.1/8102` proves `nc` working correctly
3. (influx) `create subscription "pol-http" ON "telegraf"."default" DESTINATIONS ALL "http://127.0.0.1:8102"`
4. (bash 2) `echo "test,mode=\"http\" n=1" > /dev/udp/127.0.0.1/8092` (points arrive in influx)
5. Observe that nothing arrives on the `nc` listener.

#### `influxdb.conf`

```
reporting-disabled = true

[meta]
  # Where the metadata/raft database is stored
  dir = "/mnt/data0/influxdb/meta"

  retention-autocreate = true

  # If log messages are printed for the meta service
  logging-enabled = true
  pprof-enabled = false

  # The default duration for leases.
  lease-duration = "1m0s"

[data]
  # Controls if this node holds time series data shards in the cluster
  enabled = true

  dir = "/mnt/data0/influxdb/data"

  # These are the WAL settings for the storage engine >= 0.9.3
  wal-dir = "/mnt/data1/influxdb/wal"
  wal-logging-enabled = true
  data-logging-enabled = true

[cluster]
  shard-writer-timeout = "5s" # The time within which a remote shard must respond to a write request.
  write-timeout = "10s" # The time within which a write request must complete on the cluster.
  max-concurrent-queries = 0 # The maximum number of concurrent queries that can run. 0 to disable.
  query-timeout = "0s" # The time within a query must complete before being killed automatically. 0s to disable.
  max-select-point = 0 # The maximum number of points to scan in a query. 0 to disable.
  max-select-series = 0 # The maximum number of series to select in a query. 0 to disable.
  max-select-buckets = 0 # The maximum number of buckets to select in an aggregate query. 0 to disable.

[retention]
  enabled = true
  check-interval = "30m"

[shard-precreation]
  enabled = true
  check-interval = "10m"
  advance-period = "30m"

[monitor]
  store-enabled = true # Whether to record statistics internally.
  store-database = "_internal" # The destination database for recorded statistics
  store-interval = "10s" # The interval at which to record statistics

[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  max-row-limit = 10000

[subsciber]
  enabled = true
  http-timeout = "30s"

[[graphite]]
  enabled = false

[[collectd]]
  enabled = false

[[opentsdb]]
  enabled = false

[[udp]]
  enabled = false

[continuous_queries]
  log-enabled = true
  enabled = true
```

**Comment by phemmer** [comment]
Just fyi, I think you have the wrong repo. If you suspect this is an InfluxDB issue, the issue tracker for InfluxDB is here: https://github.com/influxdata/influxdb/issues

**Comment by politician** [comment]
Honestly, I think it's a configuration issue.  Since this subscriptions feature was added specifically for Kapacitor, I figured that you guys would be the experts on setting up the InfluxDB configuration correctly.  That's why I've posted this issue to this repo.

**Comment by nathanielc** [comment]
@politician What version of Kapacitor are you using? InfluxDB and Kapacitor need to be the same major version in order to work. In other works you need to be using Kapacitor 0.13 with InfluxDB 0.13

**Comment by politician** [comment]
```
$ kapacitor version
Kapacitor 1.0.2 (git: master 1011dba109bf3d83366c87873ec285c7f9140d34)
$ influxd version
InfluxDB v0.13.0 (git: 0.13 e57fb88a051ee40fd9277094345fbd47bb4783ce)
```

Thanks! That looks like it might be the problem.

**Comment by politician** [comment]
However, that doesn't really explain why my test above didn't receive any traffic.  Those test steps don't involve Kapacitor, just the subscriptions capability.  Ideas?

**Comment by nathanielc** [comment]
@politician TCP is not supported in any version of InfluxDB and HTTP support was added in 1.0. As for the UDP try the test without step 2. Some versions of nc try to implement connection based udp, meaning they will drop subsequent packets from sources that are not the first source.

**Comment by politician** [comment]
Well, it looks like we were able to upgrade InfluxDB to 1.0 and it successfully began streaming points to subscriptions using the same configuration.  I assume that the capability just didn't actually ever work in 0.13.   Thanks a lot for the help and that nc/UDP tip @nathanielc.
