### ISSUE TITLE
Kapacitor to generate alerts based on existing data in Influx

### ISSUE THREAD

**Issue by manojgour** [influxdata/kapacitor#1007]
I worked with getting started tutorial on Kapacitor and it worked smooth. I guess I understood the flow and its working at the high level. When I try to generate alerts without Telegraf ON and try to generate alerts based on existing data in Influx, it won't work. The recording will hang and nothing happens and the moment I bring up Telegraf again then Kapacitor recordings starts to work.

Use case: Tick script checks on certain measurements if we have received data on certain time (hour) period and if data is missing based on that it should generate alerts in certain time in a day

Kapacitor: Alert tick script -

```
$ kapacitor show cpu_alert
ID: cpu_alert
Error: 
Template: 
Type: stream
Status: enabled
Executing: true
Created: 01 Nov 16 09:26 EDT
Modified: 01 Nov 16 09:40 EDT
LastEnabled: 01 Nov 16 09:40 EDT
Databases Retention Policies: ["kapacitor_example"."autogen"]
TICKscript:
var data = stream
    |from()
        .database('kapacitor_example')
        .measurement('cpu')
        .where(lambda: hour("time") >= 5 AND hour("time") <= 6)

data
    |deadman(0.0, 1m, lambda: hour("time") >= 9 AND hour("time") <= 9)
        .log('/path/to/logfile/alerts.log')

DOT:
digraph cpu_alert {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0s" ];
stream0 -> from1 [processed="1"];

from1 [avg_exec_time_ns="0s" ];
from1 -> noop3 [processed="0"];

noop3 [avg_exec_time_ns="0s" ];

stats2 [avg_exec_time_ns="0s" ];
stats2 -> derivative4 [processed="0"];

derivative4 [avg_exec_time_ns="0s" ];
derivative4 -> alert5 [processed="0"];

alert5 [alerts_triggered="0" avg_exec_time_ns="0s" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}
```

```
$ kapacitor list tasks
ID                            Type      Status    Executing Databases and Retention Policies
cpu_alert                     stream    enabled   true      ["kapacitor_example"."autogen"]

kapacitor_example
retention_policy	name	mode	destinations
autogen	"kapacitor-815bbaed-ed47-4312-a97f-3f0640dc5349"	"ANY"	http://localhost:9092
```

```
$ kapacitor stats ingress
Database                      Retention Policy              Measurement                   Points Received     
_internal                     monitor                       queryExecutor                 4                   
_internal                     monitor                       shard                         16                  
_internal                     monitor                       tsm1_engine                   16                  
_internal                     monitor                       httpd                         4                   
_kapacitor                    autogen                       runtime                       1                   
_kapacitor                    autogen                       ingress                       12                  
_internal                     monitor                       subscriber                    16                  
_internal                     monitor                       database                      8                   
_internal                     monitor                       runtime                       4                   
_internal                     monitor                       tsm1_cache                    16                  
_internal                     monitor                       tsm1_wal                      16                  
_internal                     monitor                       cq                            4                   
_kapacitor                    autogen                       kapacitor                     1                   
_kapacitor                    autogen                       edges                         7                   
_internal                     monitor                       tsm1_filestore                16                  
_internal                     monitor                       write                         4                   
_kapacitor                    autogen                       nodes                         6   
```

**Comment by nathanielc** [comment]
@manojgour If you want to use existing data in InfluxDB you need to use a batch task and write a query to get the data. A stream task only work for current data being stream into Kapacitor.

Also using deadman plus recordings has a few issues, seehttps://github.com/influxdata/kapacitor/issues/691 so its a little difficult at the moment to test deadman switch tasks :(.

**Comment by manojgour** [comment]
So I created a batch alert based on the example given in getting started guide. Seems like recording works fine but when I enable actual alert, doesn't work this time.

$ kapacitor list recordings
ID                                      Type    Status    Size      Date                   
c84d799a-1850-4b43-9028-b90a3108c744    batch   finished  121 B     06 Nov 16 11:16 EST 

$ kapacitor show batch-test-alert
ID: batch-test-alert
Error: 
Template: 
Type: batch
Status: disabled
Executing: false
Created: 01 Nov 16 14:54 EDT
Modified: 06 Nov 16 11:15 EST
LastEnabled: 06 Nov 16 10:48 EST
Databases Retention Policies: ["kapacitor_example"."autogen"]
TICKscript:
batch
    |query('''
        SELECT mean(usage_idle)
        FROM "kapacitor_example"."autogen"."cpu"
    ''')
        .period(5m)
        .every(5m)
        .groupBy(time(1m))
    |alert()
        .crit(lambda: "mean" < 100)
        .log('/path/to/logfile/alerts.log')

DOT:
digraph batch-test-alert {
query1 -> alert2;
}

$ kapacitor stats ingress
Database                      Retention Policy              Measurement                   Points Received     
_kapacitor                    autogen                       nodes                         6819                
_kapacitor                    autogen                       runtime                       729                 
_kapacitor                    autogen                       ingress                       12388               
_internal                     monitor                       cq                            1458                
_internal                     monitor                       tsm1_engine                   8748                
_internal                     monitor                       tsm1_cache                    8748                
_internal                     monitor                       queryExecutor                 1458                
_internal                     monitor                       runtime                       1458                
_internal                     monitor                       tsm1_filestore                8748                
_internal                     monitor                       shard                         8748                
_kapacitor                    autogen                       edges                         3884                
_internal                     monitor                       database                      2916                
_internal                     monitor                       httpd                         1458                
_internal                     monitor                       subscriber                    5832                
_internal                     monitor                       tsm1_wal                      8748                
_kapacitor                    autogen                       kapacitor                     729                 
_internal                     monitor                       write                         1458

**Comment by nathanielc** [comment]
@manojgour I am not sure what issue you are having, the pasted output shows the alert is still disabled.

**Comment by manojgour** [comment]
@nathanielc- Appreciate your help and patience.
I was referring to issue with batch tasks are not working as expected; whereas batch record seems to work fine by returning ids. I've created another batch tasks.

Batch recording-
# kapacitor record batch -task platform_batch -past 20m
2157d4bb-0ab4-437b-8512-f6792e01bba6

# kapacitor show platform_batch
ID: platform_batch
Error: 
Template: 
Type: batch
Status: enabled
Executing: true
Created: 07 Nov 16 22:39 UTC
Modified: 07 Nov 16 22:40 UTC
LastEnabled: 07 Nov 16 22:40 UTC
Databases Retention Policies: ["eapimetricsdaily"."default"]
TICKscript:
var data = batch
    |query('''
        SELECT mean(Platformfaults)
        FROM "eapimetricsdaily"."default"."platformcalls"
    ''')
        .period(5m)
        .every(5m)
        .groupBy(time(1m))

data
    |stats(10s)
        .align()
    |derivative('emitted')
        .unit(10s)
        .nonNegative()
    |alert()
        .crit(lambda: "emitted" >= 100.0)
        .log('/path/to/logfile/alerts.log')

DOT:
digraph platform_batch {
graph [throughput="0.00 batches/s"];

query1 [avg_exec_time_ns="0" batches_queried="0" connect_errors="0" points_queried="0" query_errors="0" ];
query1 -> noop3 [processed="0"];

noop3 [avg_exec_time_ns="0" ];

stats2 [avg_exec_time_ns="0" ];
stats2 -> derivative4 [processed="7"];

derivative4 [avg_exec_time_ns="9.723µs" ];
derivative4 -> alert5 [processed="6"];

alert5 [alerts_triggered="0" avg_exec_time_ns="11.454µs" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}

InfluxDB shell version: 1.0.2
> show retention policies on eapimetricsdaily
name	duration	shardGroupDuration	replicaN	default
default	0		168h0m0s		1		true


Above tasks description i guess shows that data is not flowing through query:
query1 -> noop3 [processed="0"];

Verified query results:

Below is my kapacitor config file:

hostname = "localhost"
data_dir = "/root/.kapacitor"

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"
  shutdown-timeout = "10s"
  shared-secret = ""

[replay]
  dir = "/root/.kapacitor/replay"

[storage]
  boltdb = "/root/.kapacitor/kapacitor.db"

[task]
  dir = "/root/.kapacitor/tasks"
  snapshot-interval = "1m0s"

[[influxdb]]
  enabled = true
  name = "default"
  default = false
  urls = ["http://ipaddress-hardcoded:8086"]
  username = ""
  password = ""
  ssl-ca = ""
  ssl-cert = ""
  ssl-key = ""
  insecure-skip-verify = false
  timeout = "0"
  disable-subscriptions = false
  subscription-protocol = "http"
  kapacitor-hostname = ""
  http-port = 0
  udp-bind = ""
  udp-buffer = 1000
  udp-read-buffer = 0
  startup-timeout = "5m0s"
  subscriptions-sync-interval = "1m0s"
  [influxdb.subscriptions]
  [influxdb.excluded-subscriptions]
    _kapacitor = ["autogen"]

[logging]
  file = "STDERR"
  level = "INFO"

[collectd]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "10s"
  read-buffer = 0
  typesdb = "/usr/share/collectd/types.db"

[opentsdb]
  enabled = false
  bind-address = ":4242"
  database = "opentsdb"
  retention-policy = ""
  consistency-level = "one"
  tls-enabled = false
  certificate = "/etc/ssl/influxdb.pem"
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"
  log-point-errors = true

[smtp]
  enabled = false
  host = "localhost"
  port = 25
  username = ""
  password = ""
  no-verify = false
  global = false
  state-changes-only = false
  from = ""
  idle-timeout = "30s"

[opsgenie]
  enabled = false
  api-key = ""
  url = "https://api.opsgenie.com/v1/json/alert"
  recovery_url = "https://api.opsgenie.com/v1/json/alert/note"
  global = false

[victorops]
  enabled = false
  api-key = ""
  routing-key = ""
  url = "https://alert.victorops.com/integrations/generic/20131114/alert"
  global = false

[pagerduty]
  enabled = false
  url = "https://events.pagerduty.com/generic/2010-04-15/create_event.json"
  service-key = ""
  global = false

[sensu]
  enabled = false
  addr = ""
  source = "Kapacitor"

[slack]
  enabled = true
  url = "https://hooks.slack.com/services/#######/#######"
  channel = "#channelname"
  global = false
  state-changes-only = false

[telegram]
  enabled = false
  url = "https://api.telegram.org/bot"
  token = ""
  chat-id = ""
  parse-mode = ""
  disable-web-page-preview = false
  disable-notification = false
  global = false
  state-changes-only = false

[hipchat]
  enabled = false
  url = ""
  token = ""
  room = ""
  global = false
  state-changes-only = false

[alerta]
  enabled = false
  url = ""
  token = ""
  environment = ""
  origin = ""

[reporting]
  enabled = true
  url = "https://usage.influxdata.com"

[stats]
  enabled = true
  stats-interval = "10s"
  database = "_kapacitor"
  retention-policy = "autogen"
  timing-sample-rate = 0.1
  timing-movavg-size = 1000

[udf]

[deadman]
  interval = "10s"
  threshold = 0.0
  id = "{{ .Group }}:NODE_NAME for task '{{ .TaskName }}'"
  message = "{{ .ID }} is {{ if eq .Level \"OK\" }}alive{{ else }}dead{{ end }}: {{ index .Fields \"emitted\" | printf \"%0.3f\" }} points/INTERVAL."
  global = false

[talk]
  enabled = false
  url = ""
  author_name = ""

Although, I don't see my database table listed:
# kapacitor stats ingress
Database                      Retention Policy              Measurement                   Points Received     
telegraf                      autogen                       cpu                           6378                
telegraf                      autogen                       diskio                        4252                
telegraf                      autogen                       system                        2126                
kapacitor_example             autogen                       cpu                           23080               
_internal                     monitor                       queryExecutor                 306                 
_internal                     monitor                       tsm1_cache                    99142               
_kapacitor                    autogen                       edges                         1194                
_kapacitor                    autogen                       runtime                       154                 
_internal                     monitor                       shard                         99142               
telegraf                      autogen                       disk                          2126                
_internal                     monitor                       write                         306                 
telegraf                      autogen                       kernel                        2126                
_internal                     monitor                       tsm1_engine                   99142               
_internal                     monitor                       database                      4284                
_internal                     monitor                       httpd                         306                 
telegraf                      autogen                       swap                          2126                
telegraf                      autogen                       processes                     2128                
_internal                     monitor                       subscriber                    8874                
_internal                     monitor                       tsm1_wal                      99142               
_kapacitor                    autogen                       nodes                         1464                
telegraf                      autogen                       mem                           2126                
_kapacitor                    autogen                       ingress                       3987                
_kapacitor                    autogen                       kapacitor                     154                 
_internal                     monitor                       cq                            306                 
_internal                     monitor                       runtime                       306                 
_internal                     monitor                       tsm1_filestore                99142

**Comment by manojgour** [comment]
@nathanielc Below batch TICK script works fine:
var data = batch
    |query('''
        SELECT sum(sev3c) AS stat
        FROM "eapimetricsdaily"."default"."incidentsdata"
        WHERE "time" > now() - 30d
    ''')
        .period(5m)
        .every(5m)
        .groupBy(time(1m))
data
    |deadman(2.0, 1m)
    .log('/home/ubuntu/kapacitor/alerts/incidentsdata-alerts.log')

Deadman doesn't solve my use case, as I want to trigger alert the moment metric/value reaches 2,so I tried to solve using below script:
var data = batch
    |query('''
        SELECT sum(sev3c) AS stat
        FROM "eapimetricsdaily"."default"."incidentsdata"
        WHERE "time" > now() - 30d
    ''')
data
   |stats(10s)
     .align()
   |derivative('emitted')
     .unit(10s)
     .nonNegative()
   |alert()
     .crit(lambda: "emitted" >= 2.0)
     .log('/home/ubuntu/kapacitor/alerts/incidentsdata-alerts.log')

Above script doesn't work but deadman switch is working fine. Please help with the TICK script.

**Comment by nathanielc** [comment]
@manojgour Can you post your question to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list?

Since it looks like you just need help figuring out the right TICKscript for your use case. You will find more people are able to help there since more people will see your question. Please add a complete example of what your are trying to accomplish with example data etc. I'll take a look at it too when I see your post. Thanks
