### ISSUE TITLE
Alert based on last N values

### ISSUE THREAD

**Issue by m4ce** [influxdata/kapacitor#1009]
Hi,

I woud like to know what you guys recommend as the best way of achieving the following:

1) crit if the last value received == 0
2) critReset only if ALL of the last N values > 0 (where N can be 3 for instance)

I know how to accomplish the first, but not both together :(

Thanks for any help.

**Comment by nathanielc** [comment]
@m4ce That second part can be accomplished using a `min` over the window.

Something like this should work

```go
var data = stream
    |from()
        .measurement('m')
    |window()
        .period(10s)
        .every(1s)

var min = data
    |min('value')
        .as('value')

var last = data
    |last('value')
        .as('value')

min
    |join(last)
       .as('min', 'last')
    |alert()
        .crit(lambda: "last.value" == 0)
        .critReset(lambda: "min.value" > 0)
```

**Comment by m4ce** [comment]
thanks @nathanielc. That's very helpful indeed, didn't know about join.

I'd like to understand more about this kind of scenarios.

What if I were dealing with strings here and wanted to check that the last N values are == "up". Would I have to create another stream counting how many metrics have value == "up"?

**Comment by nathanielc** [comment]
@m4ce yes, you can do essentially the same thing by counting the values and then comparing counts.

```go
var data = stream
    |from()
        .measurement('m')
    |window()
        .period(10s)
        .every(1s)

var up = data
    |where(lambda: "value" == 'up')
    |count('value')
        .as('count')

var all = data
    |count('value')
        .as('count')

var last = data
    |last('value')
        .as('value')

up
    |join(last, all)
       .as('up', 'last', 'all')
    |alert()
        .crit(lambda: "last.value" == 0)
        .critReset(lambda: "up.count" == "all.count")
```

**Comment by m4ce** [comment]
@nathanielc, thanks for the extra tip there. I love the DSL, it's starting to sink in.

I will close the "issue".
