### ISSUE TITLE
Unable to get the alerts from remote influxdb

### ISSUE THREAD

**Issue by gkpraveen1988** [influxdata/kapacitor#1013]
Hi, 
Need your help.. 
Have a scenario. 
1. Installed influxdb and kapacitor on the same machine and created the tick scripts to monitor the points. Alert the same in slack channel- however, this works absolutely fine. 
2. Pushing the data to influxdb (same measurement) from another machine. The data is getting uploaded to the influxdb. But it is not getting monitored by kapacitor and not alerted in slack channel. 

Check the logs for the both scenario. Can see a critical msg that been alerted in to slack channel when the data point is added from the local kapacitor server. 

But there is no entry in the kapaictor logs when the data is pushed from remote. 
Please help in resolving the issue. Thanks

Regards
Praveen

**Comment by TomerAmirV** [comment]
I had the same issue, and I think what solved it is that I changed the `host` field in `kapacitor.conf`
If what I did is correct, it should be the hostname where the influxDB can reach the Kapacitor DB, since they do not keep an active connection, and Kapacitor does not seem to poll the DB.

If this does not work, wait for someone that knows more than me 😄

**Comment by octalthorpe** [comment]
I also ran into a few issues with not getting data when I first started to use kapacitor.
Thinks things I did/learned.

1) Check that your subscriptions look correct on the influxDB host.  i.e. "SHOW subscriptions". Make certain that the interface the metrics will be pushed to is what kapacitor is listening on. i.e. localhost or 127.0.0.1 etc. Also that the host can connect and talk to kapacitor on that address/port combination.  ```netcat -z <host> <port>``` and see if you can connect ie. $?==0.
2) Make certain that you have the proper dbrp options added when you create the task.  If you do not add the DB/retention policies that are referenced in your TICK script then you will not get data. From below add ```--dbrp<database>.<retention_policy>``` where in my case database and retention_policy are variables, but would be something like "stats.default"
3) Add the log() node just after your measurement collection just to be certain you are getting any metrics
```
var data = stream
    |from()
        .database(database)
        .retentionPolicy(retention_policy)
        .measurement(measurement)
    |log() //Uncomment to debug
```

**Comment by rossmcdonald** [comment]
In addition to what others have mentioned, a good way to verify data is being forwarded from InfluxDB is to run the command (on the Kapacitor instance):

```
kapacitor stats ingress
```

Which will display metrics for the DB/RP's that the instance is receiving.

**Comment by rossmcdonald** [comment]
@gkpraveen1988 Are you still not getting points forwarded to the remote instance?

**Comment by gkpraveen1988** [comment]
Hi ross, finally found the issues. 
on to my influxdb there were bunch of datapoints added simultaneously.  Hence for a stream mood hold good only if the one data points are pushed at one time. Changed it to batch mode and then started working. Thanks for you help. 
@tomer I changed the host in kapacitor.conf.
