### ISSUE TITLE
Spread batch query in time interval to reduce load in influxdb

### ISSUE THREAD

**Issue by usdin** [influxdata/kapacitor#1023]
If hundred batch tasks are defined to run every minute. Kapacitor does all hundred queries at once, which creates load on Influxdb. Is there any way to distribute queries on time interval so Kapacitor does not burst Influxdb. Like telegraf have configurable jitter in flush interval.

**Comment by nathanielc** [comment]
Agreed we have an open issue, see https://github.com/influxdata/kapacitor/issues/712

**Comment by usdin** [comment]
Can we limit number of simultaneous query on InfluxDB?

**Comment by nathanielc** [comment]
@usdin No. While not the same you can put limits on your InfluxDB server, in which case if Kapacitor was too aggressive it would get errors back instead of overloading the InfluxDB server.
