### ISSUE TITLE
Why kapacitor throws already subscribed error? 

### ISSUE THREAD

**Issue by jayannah** [influxdata/kapacitor#1028]
When I start the kapacitor for the 1st time, It is successful and I do see the subscriptions added in influxdb with same kapacitor cluster id as in /var/log/kapacitor/cluster.id file.

When stop the kapacitor and restart again, it fails saying the subscription <cluster-id> already exists..

If the subscription already exists, it should continue with default setting, why start of kapacitor fails?

Error:
run: open server: open service *influxdb.Service: creating sub kapacitor-9f6114e6-d3fe-463f-9f86-89bc99f84a60 for db "dbname" and rp "default":  subscription already exists

Kapacitor version: 1.1
Influxdb version: 1.0

**Comment by rossmcdonald** [comment]
@jayannah What version of Kapacitor are you running?

**Comment by jayannah** [comment]
Just updated the versions used.. thank you.

Kapacitor version: 1.1
Influxdb version: 1.0

**Comment by nathanielc** [comment]
@jayannah Can you share the output of `show subscriptions`?

**Comment by jayannah** [comment]
In the show subscription I do see kapacitor is subscribed to all the databases. Only problem is , when I stop the kapacitor with control C and rerun again with or without any configuration change, I see kapacitor fails to run again.

I do the following steps as work around to make the kapacitor registers successfully again and start
1. remove cluster.id from /var/lib/kapacitor/
2. remove server.id from /var/lib/kapacitor/
3. start the kapacitor again

**Comment by nathanielc** [comment]
@jayannah I haven't been able to reproduce this issue. Can you maybe provide more details? Specifically the relevant influxdb config in kapacitor.conf and the output of show subscriptions, along with the output of `kapacitor stats general`. That should help us narrow down what is going on. Thanks

**Comment by fdhex** [comment]
I have the same symptoms actually. @nathanielc should I open a new ticket? 

I got around it by disabling subscriptions altogether, or removing the cluster.id and server.id as described above but that doesn't seem like the proper way to fix this.

**Comment by nathanielc** [comment]
@fdhex No need to open a new issue, can you provide the startup log and relevant information I asked for above?

**Comment by fdhex** [comment]
@nathanielc 

I have a 3 influxdb setup behind relay, which I setup in Kapacitor:

`[[influxdb]]
  # Connect to an InfluxDB cluster
  # Kapacitor can subscribe, query and write to this cluster.
  # Using InfluxDB is not required and can be disabled.
  enabled = true
  default = true
  name = "influxdb"
  urls = ["http://10.19.5.137:8086","http://10.19.5.138:8086","http://10.19.5.139:8086",]
  username = ""
  password = ""`

I use http protocol sub.

`# Which protocol to use for subscriptions
  # one of 'udp', 'http', or 'https'.
  subscription-protocol = "http"`

Somehow, it seems to only create the DB  in one of my Influx, not all.

> show subscriptions
name: influxdb
retention_policy	name						mode	destinations
----------------	----						----	------------
default			kapacitor-6ebd9d1c-de76-4d13-90ad-ac4cede0f2f3	ANY	[http://kapacitor-influxdb.service.consul:9092]

appears on my second influxdb, this on the third:

`> show subscriptions
name: influxdb
retention_policy	name						mode	destinations
----------------	----						----	------------
default			kapacitor-11eb260e-286c-4ce5-b118-35cf4e078309	ANY	[http://kapacitor-influxdb.service.consul:9092]
`

And nothing at all on the first.

If I restart Kapacitor, here's what appears:

`2017/01/26 13:26:07 Using configuration at: /var/vcap/jobs/kapacitor/config/kapacitor.conf
run: open server: open service *influxdb.Service: creating sub kapacitor-6ebd9d1c-de76-4d13-90ad-ac4cede0f2f3 for db "influxdb" and rp "default": subscription already exists`

**Comment by nathanielc** [comment]
@fdhex When you configure Kapacitor to connect to InfluxDB with multiple URLs it assumes that those InfluxDB instances are clustered, not independtly behind a relay. As a result it only issues queries to one url for any given action (i.e. create subscription ...). This is why it is not working. If you are using the relay to get HA then do not use subscriptions as you will duplicate data and have issues like you are currently experiencing. See [this](https://groups.google.com/forum/#!searchin/influxdb/relay$20subscriptions$20kapacitor|sort:relevance/influxdb/yImf4Uok2T4/xvKdvIC2BgAJ) discussion for more details.

**Comment by fdhex** [comment]
Very useful pointer, thank you!

**Comment by lvqian** [comment]
Currently, I am facing this issue but I can't open the google discussion group, it shows "no influxdb group there", can anyone share me some thought on how to "Simply add Kapacitor as a backend in the relay. "
