### ISSUE TITLE
Kapacitor not subscribing to all database

### ISSUE THREAD

**Issue by jayannah** [influxdata/kapacitor#1029]
When I start the kapacitor, it is successfully started.

When I login to InfluxDB and verify, the kapacitor is subscribed to most of the databases, but not ALL.

I  have given admin user name & password in the kapacitor.conf and as the "admin" user of Influxdb has all grants for every database by default, why kapacitor is not subscribing to all database.

We have around 30 database created and kapacitor subscribed to 26, but not for 4.

Also, this is not consistent, it may failed to subscript to different databases. 

If I delete /var/lib/kapacitor/cluster.id and server.id file and restart, it may or may not subscibe to all or few DBs. It is not consistant that the kapacitor failed to subscribed to a fix set of databases. Its just random.

Kapacitor version : 1.1
Influx db : 1.0

[[influxdb]]
  enabled = true
  name = "emmo_influxdb"
  default = true
  urls = ["http://url:8086"]
  username = "admin"
  password = "password"
  ssl-ca = ""
  ssl-cert = ""
  ssl-key = ""
  insecure-skip-verify = false
  timeout = "0s"
  disable-subscriptions = false
  subscription-protocol = "http"
  kapacitor-hostname = ""
  http-port = 0
  udp-bind = ""
  udp-buffer = 1000
  udp-read-buffer = 0
  startup-timeout = "5m0s"
  subscriptions-sync-interval = "1m0s"
  [influxdb.subscriptions]
  [influxdb.excluded-subscriptions]
    _kapacitor = ["autogen"]

**Comment by nathanielc** [comment]
@jayannah Are there any errors in either the kapacitor or influxdb logs? I have tested Kapacitor subscribing to 100+ subscriptions and it is working without issue. 

Are there any more details you can share?

**Comment by jayannah** [comment]
I dont see any errors in kapacitor logs

[run] 2016/11/10 10:48:53 I! Kapacitor starting, version 1.1.0, branch master, commit 939fdf670b028c142944977dcfcb045cac2343ed
[run] 2016/11/10 10:48:53 I! Go version go1.7.3
[srv] 2016/11/10 10:48:53 I! Kapacitor hostname: kapacitor_1aqa
[srv] 2016/11/10 10:48:53 I! ClusterID: 2317c7c5-7a99-4f98-8219-09b938851995 ServerID: c34c673a-3797-4837-a75b-3fb97c469364
[task_master:main] 2016/11/10 10:48:53 I! opened
[task_store] 2016/11/10 10:48:54 W! could not open old boltd for task_store. Not performing migration. Remove the `task_store.dir` configuration to disable migration.
[smtp] 2016/11/10 10:48:54 I! Starting SMTP service
[stats] 2016/11/10 10:48:54 I! opened service
[httpd] 2016/11/10 10:48:54 I! Starting HTTP service
[httpd] 2016/11/10 10:48:54 I! Authentication enabled: false
[httpd] 2016/11/10 10:48:54 I! Listening on HTTP: 0.0.0.0:9092
[run] 2016/11/10 10:48:54 I! Listening for signals
