### ISSUE TITLE
Consistent log time formatting

### ISSUE THREAD

**Issue by phemmer** [influxdata/kapacitor#1033]
The `log()` node emits different time formats based on different chaining methods.

For example, with:
```
data|elapsed('active',1s)|log()
data|count('active').as('count')|log()
```
produces:
```
[test:log10] 2016/11/11 11:13:39 I!  {"Name":"postgresql_replication_slots","Database":"","RetentionPolicy":"","Group":"host=fll2gdbs10stg,slot_name=fll2gbar01stg","Dimensions":{"ByName":false,"TagNames":["host","slot_name"]},"Tags":{"host":"fll2gdbs10stg","slot_name":"fll2gbar01stg"},"Fields":{"count":2},"Time":"2016-11-11T11:13:29.785557848-05:00"}
[test:log8] 2016/11/11 11:13:39 I!  {"Name":"postgresql_replication_slots","Database":"","RetentionPolicy":"","Group":"host=fll2gdbs10stg,slot_name=fll2gbar01stg","Dimensions":{"ByName":false,"TagNames":["host","slot_name"]},"Tags":{"host":"fll2gdbs10stg","slot_name":"fll2gbar01stg"},"Fields":{"elapsed":10},"Time":"2016-11-11T16:13:39.785561457Z"}
```

Notice the different time formats at the end, `2016-11-11T11:13:29.785557848-05:00` vs `2016-11-11T16:13:39.785561457Z`. This makes debugging a bit of a pain.

**Comment by nathanielc** [comment]
Thanks for the report, this should be an easy fix.

**Comment by nathanielc** [comment]
@phemmer Can you share your complete TICKscript that had the inconsistent time behavior? I can't seem to reproduce it. Thanks

**Comment by phemmer** [comment]
Just updating that I haven't forgotten about this. Just been busy. Will try and get some time to come up with a minimal reproducible test case.

**Comment by nathanielc** [comment]
@phemmer Thanks!

**Comment by phemmer** [comment]
Closing as I'm unable to reproduce this any more.
