### ISSUE TITLE
Update Kapacitor HTTPD TLS config to match InfluxDB

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#1034]
InfluxDB has introduced a new config option called `http-private-key`. We should add an equivalent config option to Kapacitor.

**Comment by dalu** [comment]
I'm getting
`run: open server: open service *httpd.Service: tls: failed to find PEM block with type ending in "PRIVATE KEY" in key input after skipping PEM blocks of the following types: [CERTIFICATE CERTIFICATE]`
Is this related?
Because currently is see no option for a private key

**Comment by udf2457** [comment]
@dalu @nathanielc I'm getting this bug too (Kapacitor 1.4.0 (git: HEAD fcce3ee9e6abcee5595fd61066bfc904edb1e113) `kapacitord: run: open server: open service *httpd.Service: tls: failed to find PEM block with type ending in "PRIVATE KEY" in key input after skipping PEM blocks of the following types: [CERTIFICATE CERTIFICATE CERTIFICATE]`.  

I have added `https-private-key` to my config and the associated private key is correct.

**Comment by nathanielc** [comment]
@dalu @udf2457 Once this issue is resolved there will be a new option `http-private-key` that allows you to place the private key in its own file. Until then #1820 config entry `http-certificate` needs to point to a file with 2both cert and private key.

**Comment by gunnaraasen** [comment]
https://github.com/influxdata/kapacitor/pull/1820 introduced the optional `https-private-key` config parameter to Kapacitor.
