### ISSUE TITLE
Kapacitor: Alert conditions are ingored

### ISSUE THREAD

**Issue by jayannah** [influxdata/kapacitor#1036]
Hi

I have written the TICK script to query the data from InfluxDB, calculate tablespace_used and I want to write back to InfluxDB if the tablespace_used is > 0.6 in this example.

The below TICK is able to query the data and write the data back to InfluxDB successfully.

However, it is writing the entry into Database (Oracle_Intellix_TableSpace_Alerts meansurement) and to /tmp/batch_alerts.log even if the value of tablespace used is less than 0.6. I do see the entries in the DB and also in File /tmp/batch_alerts.log with tablespace_used value as 0.02, 0.5, 0.8, 0.9..etc.

Why the script is writing the entries for the tablespace_used values less than 0.6???
How to pass USED_MB, TOTAL_MB and other parameters of Oracle_Intellix_TableSpace measurement like serverName back into InfluxDB measurement created for alert (i.e Oracle_Intellix_TableSpace_Alerts)?
var tablespace_errors = batch
|query('''
SELECT * FROM "comm_qa"."default"."Oracle_Intellix_TableSpace"
''')
.period(15m)
.every(10m)

tablespace_errors
|eval(lambda: "USED_MB" / "TOTAL_MB")
.as('tablespace_used')
|alert()
.crit(lambda: "tablespace_used" > 0.6)
// Whenever we get an alert write it to a file.
.log('/tmp/batch_alerts.log')
|influxDBOut()
.cluster('emmo_relays')
.database('comm_qa')
.measurement('Oracle_Intellix_TableSpace_Alerts')

====

Kapacitor 1.1
InfluxDB 1.0

**Comment by nathanielc** [comment]
@jayannah I believe I just answered this question on the mailing list. https://groups.google.com/forum/?pli=1#!topic/influxdb/MO0db46k_cY 

Closing the issue.
