### ISSUE TITLE
After adding .keep(value field names), alert stopped working

### ISSUE THREAD

**Issue by jayannah** [influxdata/kapacitor#1037]
Kapacitor: 1.1
InfluxDB 1.0

Hi

Below is my TICK script and it was working fine before I add the .keep fields. 
          .keep('USED_MB')
          .keep('TOTAL_MB')
1. After adding the above 2 lines in eval node, the script is not writing anything to the file and also to the InfluxDB.
2. Even before adding these 2 fields, the script was writing only time & value of tablespace_used into the log file & to influxDB, but not the tag names of the measurement Oracle_Intellix_TableSpace which has Tag key such as hostname, instancename & tablespacename

TICK script:

var tablespace_errors = batch
    |query('''
       SELECT *  FROM "comm_qa"."default"."Oracle_Intellix_TableSpace"
    ''')
      .period(20m)
      .every(10m)

tablespace_errors
   |eval(lambda: "USED_MB" / "TOTAL_MB")
          .as('tablespace_used')
          .keep('USED_MB')
          .keep('TOTAL_MB')
   |alert()
        //.warn(lambda: "tablespace_used" >  0.3)
        .crit(lambda: "tablespace_used" >  0.6)
        // Whenever we get an alert write it to a file.
        .log('/tmp/batch_alerts.log')
   |influxDBOut()
        .cluster('emmo_relays')
        .database('comm_qa')
        .measurement('Oracle_Intellix_TableSpace_Alerts')

Oracle_Intellix_TableSpace measurement has following columns:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
time	HOST_NAME	INSTANCE_NAME	TABLESPACE_NAME	TOTAL_MB	USED_MB
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"ADMIN"	20480	1779
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"WEBSYS"	81920	78680
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"WEBSERIES_INDEX"	20480	2
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"USER_TS"	100	1
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"UNDO_TS"	2048	2027
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"TOOLS_TS"	50	1
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"SYSTEM"	1000	715
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"SYSAUX"	2548	1551
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"QA1_INTLX_PRVSN_DATA_TS"	10240	5
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"KEYSTORE"	4096	7
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"DCON_INDEX_TS"	8192	12
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"DCON_DATA_TS"	25600	33
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"CRYSTAL"	4096	199
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"ARCHIVE"	20480	3228
2016-11-14T18:35:23.253Z	"mormont"	"D0006SX"	"APPDBA_TS"	50	1




[root@horizgrafana-qa kapacitor-1.1]# kapacitor show  batch_oracle_intellix_tablespace_usage_alert
ID: batch_oracle_intellix_tablespace_usage_alert
Error:
Template:
Type: batch
Status: enabled
Executing: true
Created: 10 Nov 16 15:13 EST
Modified: 14 Nov 16 13:22 EST
LastEnabled: 14 Nov 16 13:22 EST
Databases Retention Policies: ["comm_qa"."default"]
TICKscript:
var tablespace_errors = batch
    |query('''
       SELECT *  FROM "comm_qa"."default"."Oracle_Intellix_TableSpace"
    ''')
        .period(20m)
        .every(10m)

tablespace_errors
    |eval(lambda: "USED_MB" / "TOTAL_MB")
        .as('tablespace_used')
        .keep('USED_MB')
        .keep('TOTAL_MB')
    |alert()
        // .warn(lambda: "tablespace_used" >  0.3)
        .crit(lambda: "tablespace_used" > 0.6)
        // Whenever we get an alert write it to a file.
        .log('/tmp/batch_alerts.log')
    |influxDBOut()
        .cluster('emmo_relays')
        .database('comm_qa')
        .measurement('Oracle_Intellix_TableSpace_Alerts')

DOT:
digraph batch_oracle_intellix_tablespace_usage_alert {
graph [throughput="0.00 batches/s"];

query1 [avg_exec_time_ns="0s" batches_queried="2" points_queried="45" query_errors="0" ];
query1 -> eval2 [processed="2"];

eval2 [avg_exec_time_ns="0s" eval_errors="0" ];
eval2 -> alert3 [processed="2"];

alert3 [alerts_triggered="0" avg_exec_time_ns="0s" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
alert3 -> influxdb_out4 [processed="0"];

influxdb_out4 [avg_exec_time_ns="0s" points_written="0" write_errors="0" ];
}
[root@horizgrafana-qa kapacitor-1.1]#

**Comment by nathanielc** [comment]
You should use `.keep('TOTAL_MB', 'USED_MD', 'tablespace_used')` to keep the specified list or `.keep()` to keep all fields.

**Comment by jayannah** [comment]
thanks. It worked. Not sure why adding .keep() multiple times didn't work. It will be great if these details added to documentation.  

Please let me know how I can contribute to the documentation from mylearnings and help our community.

**Comment by jayannah** [comment]
Also, when I use .keep() all the tags and fields are written along with new fields. But as per the documentation,"Tags are always preserved regardless how keep is used", but the tags didn't written to the database without .keep() used. Do you think it is a bug or mistake in documentation?

**Comment by nathanielc** [comment]
@jayannah The tag, weren't actually tags, this is a subtle issue. In InfluxQL if you do `select * from ...` then all field and tags are returned as fields. If you want tags to be returned as tags you must group by those tags. i.e. 

```
var tablespace_errors = batch
    |query('''
       SELECT *  FROM "comm_qa"."default"."Oracle_Intellix_TableSpace"
    ''')
        .period(20m)
        .every(10m)
         // Group by all tags
        .groupBy(*)
```

Then tags will be correctly set and the eval keep won't effect them.
