### ISSUE TITLE
What is the correct process for removing a service alerting?

### ISSUE THREAD

**Issue by ws816** [influxdata/kapacitor#1042]
I have a server that runs nginx service. I want to remove nginx from the server, but the kapacitor still alert. I tried to delete series from influxdb, but it didn't work. What is the correct process for removing a service alerting?

**Comment by nathanielc** [comment]
@ws816 Can you share your TICKscript?

**Comment by ws816** [comment]
I use template to define a task, the template as follow:
```
var measurement string
var where = lambda: TRUE

var data = stream
  | from()
    .measurement(measurement)
    .where(where)
    .groupBy('host')

var alert = data
  | deadman(0.0, 30s)
    .id('{{ .TaskName }}|{{ index .Tags "host" }}')

alert
  .log('/tmp/deadman.log')

```
The vars as follow:
```
{
  "measurement": {"type" : "string", "value" : "procstat" },
  "where": {"type": "lambda", "value": "\"process_name\" == 'nginx'"}
}
```

**Comment by ws816** [comment]
What is the correct process for removing a service alerting? remove series from influxdb?

**Comment by nathanielc** [comment]
@ws816 Currently the only way to do this is to disable/enable the task. This is because the deadman node doesn't forget any services. There is an open PR https://github.com/influxdata/kapacitor/pull/610 to fix this but it has some challenges and we are working on a fix.

**Comment by ws816** [comment]
@nathanielc Is there another way to monitor process without using deadman? I think the process monitoring is basic requirement.
