### ISSUE TITLE
logrotate.d ignores kapacitor configuration due to bad file mode

### ISSUE THREAD

**Issue by winem** [influxdata/kapacitor#1043]
By default, kapacitor creates the logrotate configuration in /etc/logrotate.d with 664 as permission. 

logrotate has the following requirements: 
- configuration file owner must be root
- configuration file mode must be 664 

Otherwise, you'll get this error when running logrotate -f /etc/logrotate.conf
root@host-1:/etc/logrotate.d# logrotate -v  -f /etc/logrotate.conf 
reading config file /etc/logrotate.conf
including /etc/logrotate.d
reading config file apport
reading config file apt
Ignoring couchdb because the file owner is wrong (should be root).
reading config file dpkg
reading config file influxdb
Ignoring kapacitor because of bad file mode.
reading config file rsyslog
reading config file telegraf
reading config file ufw
reading config file unattended-upgrades

Successfully reproduced the issue on Debian 8, CentOS 7 and Ubuntu 16.04. 

Already have a fix for that and forked the repository. Will create the pull request soon.

**Comment by rossmcdonald** [comment]
Fixed with https://github.com/influxdata/kapacitor/pull/1044. To anyone who encounters this, run:

```
sudo chmod 644 /etc/logrotate.d/kapacitor
```
