### ISSUE TITLE
Ignore certificate / security while sending notifications to Hipchat

### ISSUE THREAD

**Issue by bharathrajbk** [influxdata/kapacitor#1050]
@nathanielc ,

I am trying to send notifications to our organization's hipchat server which is on SSL layer.

I would like to ignore the security option (something that `curl -k` does).

I looked around the hipchat service.go and this can be done by inserting the following lines of code - 

```
import (
    "crypto/tls" # in addition to the existing imports
)

#In the function -> func (s *Service) Alert(room, token, message string,*
#Add the below lines;

tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }
    cl := &http.Client{Transport: tr}

# And then use cl to Post the request with

resp, err := cl.Post(url, "application/json", post) # Instead of the current http.Post
```
This can be set based on a flag in the configuration such as - 
`Ignore Security for Hipchat = boolean`

I am unable to get this compiled and hence struggling to make the change.

Can you please here here?

Thanks,
Bharath

**Comment by bharathrajbk** [comment]
@nathanielc ,

Never mind... I got the hipchat server working without security. :)

However, this feature would be nice.

Thanks,
Bharath

**Comment by nathanielc** [comment]
@bharathrajbk Thanks for the code snippet and detailed write up. I am hesitant to add config options that expose insecure behaviors, and since you are working I'll close this issue for now.

In general there are a few ways to work around this issue that don't require ignoring TLS certs.

**Comment by bharathrajbk** [comment]
Thanks @nathanielc !
