### ISSUE TITLE
Add metrics unit in alert message.

### ISSUE THREAD

**Issue by usdin** [influxdata/kapacitor#1061]
In kapacitor alert message values are passed directly. Which make message ugly like

If template is 

`Approximate Data Size is  {{ index .Fields "stat" }} kb`

which gives

`Approximate Data Size is  1.223241e+06 kb`

Here value is less readable. How about adding function in go-template which can format value, it should convert _1.223241e+06 kb_ to _1.2 gb_. 
It can be called in template
`Approximate Data Size is  {{ formatValue (index .Fields "stat") "kb" }} `
_formatValue_ should convert values in kb to more readable value-unit. It can be done for other measurements like throughput, time.

**Comment by nathanielc** [comment]
@usdin  Have a look at this https://docs.influxdata.com/kapacitor/v1.1/tick/expr/#human-string-functions
