### ISSUE TITLE
Alert transition handling

### ISSUE THREAD

**Issue by tnkdev** [influxdata/kapacitor#1063]
Hi everyone,
i am new to Kapacitor. I have a question, we can use Kapacitor to generate an alert. So how we can generate an action handler when the the alert is ceased. The TICK script is as following:
cpu
    |alert()
        .warn(lambda: "usage_idle" < 95)
        .exec('/tmp/raise_handler.py','Raise Alarm')
        .warn(lambda: "usage_idle" > 95)
        .exec('/tmp/clear_handler.py','Clear Alarm')
Something goes wrong? 
Thanks in advance.

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
