### ISSUE TITLE
kapacitor outputs strange data

### ISSUE THREAD

**Issue by liurenjie1024** [influxdata/kapacitor#1065]
I have a database and a measurement which get two data points every minute, and my test tick is the following:
```
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('com.mediav.rtut.parser.CookieEventParserBolt.qps')
        .groupBy('hostname', 'port')
    |alert()
        .crit(lambda: "sum" > 1000)
        // Whenever we get an alert write it to a file.
        .log('/tmp/qps.log')
```
and I define my task as following:
```
kapacitor define qps_alert -type stream -tick qps.tick -dbrp rtut.autogen
```

I created a record with the following code:
```
kapacitor record stream -task qps_alert -duration 1m
```

When I replay the record with the task, I expect only two messages in the log file. However, a lot of strange data appears in log, some of them even have timestamp in the future.

**Comment by nathanielc** [comment]
@liurenjie1024 By default a recording replays the data relative to the current time. If you want the recording to use the timestamps on the original data use the `-rec-time` flag, when replaying the recording.

**Comment by liurenjie1024** [comment]
@nathanielc Thanks for the reply. I used the flag but the output is still weird to me.  When 
```
kapacitor record stream -task qps_alert -duration 1m
```
begins to execute, kapacitor is supposed to record data from now. However it seems that kapacitor tries to poll data as much as possible, and even data several days has been recorded. Isn't this a problem?

**Comment by liurenjie1024** [comment]
I've checked the logs and the following confuses me:
1. The same record appears several times in the log, but with different duration. I have no idea the meaning of duration in the log.
2. Records show up in the log is not in the order of event time. Records of several days ago may event appear.

[qps.txt](https://github.com/influxdata/kapacitor/files/622075/qps.txt) is part of my log file. The time when I enable the tick is 2016-11-30T14:30:00Z, but as you can see kapacitor pulls data several days ago and the records are out of order.

**Comment by nathanielc** [comment]
@liurenjie1024 Can you confirm that the measurement `com.mediav.rtut.parser.CookieEventParserBolt.qps` isn't receiving writes for old timestamps? You may be running into this https://github.com/influxdata/kapacitor/issues/1058
