### ISSUE TITLE
What's the best way to learn tickscript

### ISSUE THREAD

**Issue by simonvc** [influxdata/kapacitor#1066]
I'm finding the learning curve quite steep for tickscripts. What's the best way to experiment with them? 

Is there a way to set up some kind of REPL or live feedback type system so you can see data being filtered?

**Comment by nathanielc** [comment]
@simonvc Have you played with the record/replay features? They provide a way to run a task repeatedly with a static set of data. While not quite like a REPL its similar.

**Comment by forestjohnsonpeoplenet** [comment]
I created this to help solve that problem https://github.com/sequentialread/tickscript-studio
disclaimer, this is my 3rd party thing, not from influxdata
