### ISSUE TITLE
Kapacitor in AWS QA Env

### ISSUE THREAD

**Issue by nikhilagrl** [influxdata/kapacitor#1070]
Hi,

I have InfluxDb and kapacitor installed in my AWS QA environment.
What are the changes required in Kapacitor.conf , I am trying to send email notification's.

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
