### ISSUE TITLE
process udf function fail with batch but works with stream [solved]

### ISSUE THREAD

**Issue by IvanTheFirst** [influxdata/kapacitor#1083]
Hello.
I wrote udf function and it's fails with batch in .tick file.  Can you help me with these issue?

kapacitor.log:

> [httpd] ::1 - - [08/Dec/2016:15:31:14 +0000] "PATCH /kapacitor/v1/tasks/forecast_disk_capacity 
> HTTP/1.1" 200 719 "-" "KapacitorClient" 5ac6afaf-bd5b-11e6-8034-000000000
> 000 17726
> [task_master:main] 2016/12/08 15:31:14 D! Starting task: forecast_disk_capacity
> [task_master:main] 2016/12/08 15:31:14 I! Started task: forecast_disk_capacity
> [task_master:main] 2016/12/08 15:31:14 D! digraph forecast_disk_capacity {
> query1 -> Forecast2;
> Forecast2 -> alert3;
> alert3 -> log4;
> }
> [httpd] ::1 - - [08/Dec/2016:15:31:14 +0000] "PATCH /kapacitor/v1/tasks/forecast_disk_capacity HTTP/1.1" 200 834 "-" "KapacitorClient" 5ac972b5-bd5b-11e6-8035-000000000000 13147
> [httpd] ::1 - - [08/Dec/2016:15:31:14 +0000] "GET /kapacitor/v1/tasks?dot-view=attributes&fields=link&limit=100&offset=0&pattern=forecast_disk_capacity&replay-id=&script-format=formatted HTTP/1.1" 200 43 "-" "KapacitorClient" 5acdfb00-bd5b-11e6-8036-000000000000 521
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:31:14 I!P Starting agent for Forecast
> [influxdb] 2016/12/08 15:31:16 D! linking subscriptions for cluster localhost
> [forecast_disk_capacity:query1] 2016/12/08 15:32:14 D! starting next batch query: SELECT min(mount_point_free_kb) / 1024 / 1024 FROM monitoring."default".disk_capacity WHERE host = 'dwhfrn03' AND time >= '2016-12-03T15:32:14.433781029Z' AND time < '2016-12-08T15:32:14.433781029Z' GROUP BY time(1h, 0s), mount_point
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P mount_point_free_kb
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P Traceback (most recent call last):
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P   File "/usr/lib/python2.7/dist-packages/agent.py", line 122, in _read_loop
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P     self.handler.point(request.point)
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P   File "/kapacitor_rules/udf/forecast.py", line 117, in point
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P     value = point.fieldsDouble[self._field]
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P   File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/containers.py", line 462, in __getitem__
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P     val = self._value_checker.DefaultValue()
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P AttributeError: 'TypeChecker' object has no attribute 'DefaultValue'
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P 2016-12-08 15:32:14,463 ERROR:root: error processing request of type point: 'TypeChecker' object has no attribute 'DefaultValue'
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 I!P Agent finished
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 E! error processing request of type point: 'TypeChecker' object has no attribute 'DefaultValue'
> [edge:forecast_disk_capacity|Forecast2->alert3] 2016/12/08 15:32:14 D! closing c: 0 e: 0
> [edge:forecast_disk_capacity|query1->Forecast2] 2016/12/08 15:32:14 I! aborting c: 13 e: 10
> [forecast_disk_capacity:Forecast2] 2016/12/08 15:32:14 E! error processing request of type point: 'TypeChecker' object has no attribute 'DefaultValue'
> [edge:forecast_disk_capacity|alert3->log4] 2016/12/08 15:32:14 D! closing c: 0 e: 0
> [task_store] 2016/12/08 15:32:14 D! task forecast_disk_capacity finished
> [edge:forecast_disk_capacity|batch->batch0] 2016/12/08 15:32:14 D! closing c: 13 e: 13
> [edge:forecast_disk_capacity|query1->Forecast2] 2016/12/08 15:32:14 D! closing c: 13 e: 10
> [task_master:main] 2016/12/08 15:32:14 E! Stopped task: forecast_disk_capacity Forecast2: error processing request of type point: 'TypeChecker' object has no attribute 'DefaultValue'
> [task_store] 2016/12/08 15:32:14 E! task forecast_disk_capacity finished with error: Forecast2: error processing request of type point: 'TypeChecker' object has no attribute 'DefaultValue'

code of function:

```
from agent import Agent, Handler
#from scipy import stats
#import math
import numpy
import udf_pb2
import sys
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)s:%(name)s: %(message)s')
logger = logging.getLogger()


class Forecast(Handler):

    class state(object):
        def __init__(self):
            self._entries = []

        def reset(self):
            self._entries = []

        #def update(self, value, point):
        #    self._entries.append((value, point))
        def update(self, value):
            # tranform to gigabytes
            self._entries.append((value/1024/1024))

        def calc(self):
            print >> sys.stderr, self._entries
            y = numpy.array(self._entries)
            X = numpy.array([ numpy.ones(len(y)), list(range(1,len(y)+1)) ]).transpose()
            #print(X)
            #thetaMulti = ((X'*X)^-1)*X'*y
            X_trans = X.transpose()

            thetaMulti = numpy.linalg.matrix_power(X_trans.dot(X),-1).dot(X_trans).dot(y)

            temp = numpy.power(X_trans.dot(X),-1).dot(X_trans).dot(y)

            iter_count = -thetaMulti[0]/thetaMulti[1] - len(y);

            return iter_count

        #def length(self):
        #    return len(self._entries)

    def __init__(self, agent):
        self._agent = agent

        self._field = None

        self._begin_response = None

        self._state = Forecast.state()

        """
        Keep a rolling window of historically normal data
        When a new window arrives use a two-sided t-test to determine
        if the new window is statistically significantly different.
        """
    def info(self):
        """
        Respond with which type of edges we want/provide and any options we have.
        """
        response = udf_pb2.Response()
        # We will consume batch edges aka windows of data.
        response.info.wants = udf_pb2.BATCH
        # We will produce single points of data aka stream.
        response.info.provides = udf_pb2.STREAM

        # Here we can define options for the UDF.
        # Define which field we should process
        response.info.options['field'].valueTypes.append(udf_pb2.STRING)

        logger.info("info")
        return response

    def init(self, init_req):
        """
        Given a list of options initialize this instance of the handler
        """
        success = True
        msg = ''
        size = 0
        for opt in init_req.options:
            if opt.name == 'field':
                self._field = opt.values[0].stringValue
    
        if self._field is None:
            success = False
            msg += ' must supply a field name'
        
        response = udf_pb2.Response()
        response.init.success = success
        response.init.error = msg[1:]
        return response

    def snapshot(self):
        response = udf_pb2.Response()
        response.snapshot.snapshot = ''
        return response

    def restore(self, restore_req):
        response = udf_pb2.Response()
        response.restore.success = False
        response.restore.error = 'not implemented'
        return response


    def begin_batch(self, begin_req):
        #print >> sys.stderr, "START!!!!"
        self._state.reset()
        # Keep copy of begin_batch
        response = udf_pb2.Response()
        response.begin.CopyFrom(begin_req)
        self._begin_response = response

    def point(self, point):
        print >> sys.stderr, self._field
        value = point.fieldsDouble[self._field]
        #self._state.update(value, point)
        self._state.update(value)

    def end_batch(self, end_req):
        interval_count = self._state.calc()
        #msg = "LENGTH "
        #msg += str(length)
        #print >> sys.stderr, msg
        response = udf_pb2.Response()
        response = udf_pb2.Response()
        response.point.time = end_req.tmax
        response.point.name = end_req.name
        response.point.group = end_req.group
        response.point.tags.update(end_req.tags)
        response.point.fieldsDouble["interval_value"] = interval_count
        self._agent.write_response(response)


if __name__ == '__main__':
    # Create an agent
    agent = Agent()

    # Create a handler and pass it an agent so it can write points
    h = Forecast(agent)

    # Set the handler on the agent
    agent.handler = h

    # Anything printed to STDERR from a UDF process gets captured into the Kapacitor logs.
    print >> sys.stderr, "Starting agent for Forecast"
    agent.start()
    agent.wait()
    print >> sys.stderr, "Agent finished"


```

tick file:

```
var data = batch
     |query('''
         SELECT min("mount_point_free_kb")/1024/1024
         FROM "monitoring"."default".disk_capacity
         WHERE "host" = 'dwhfrn03'
     ''')
        .period(5d)
        .every(1m)
        .groupBy( time(1h), 'mount_point')

data
    //Run our tTest UDF on the hotend temperature
    @Forecast()
    .field('mount_point_free_kb')
    |alert()
        .crit(lambda: "interval_value" > 0)
        .log('/var/log/kapacitor/alerts_free_disk_space.log')
    |log()
```

function in kapacitor.conf:

```
[udf]
  [udf.functions]
    [udf.functions.tTest]
        # Run python
        prog = "/usr/bin/python2"
        # Pass args to python
        # -u for unbuffered STDIN and STDOUT
        # and the path to the script
        args = ["-u", "/kapacitor_rules/udf/ttest.py"]
        # If the python process is unresponsive for 10s kill it
        timeout = "10s"
        # Define env vars for the process, in this case the PYTHONPATH
        [udf.functions.tTest.env]
            PYTHONPATH = "/kapacitor_rules/udf/agent/py"
    [udf.functions.Forecast]
        # Run python
        prog = "/usr/bin/python2"
        # Pass args to python
        # -u for unbuffered STDIN and STDOUT
        # and the path to the script
        args = ["-u", "/kapacitor_rules/udf/forecast.py"]
        # If the python process is unresponsive for 10s kill it
        timeout = "10s"
        # Define env vars for the process, in this case the PYTHONPATH
        [udf.functions.Forecast.env]
            PYTHONPATH = "/kapacitor_rules/udf/agent/py"
```

The same function works with stream tick:
```
var data = stream
    |from()
    .measurement('disk_capacity')
    .groupBy('mount_point')
    .where(lambda: "host" == 'dwhfrn03')
    .groupBy('mount_point')
    |window()
        .period(1m)
        .every(1m)

data
    //Run our tTest UDF on the hotend temperature
    @Forecast()
    .field('mount_point_free_kb')
    |alert()
        .crit(lambda: "interval_value" > 0)
        .log('/var/log/kapacitor/alerts_free_disk_space.log')
    |log()
```

**Comment by IvanTheFirst** [comment]
There is difference from stream and batch. When I start my batch I get this message in **ponit**:
```
time: 1481335200000000000
group: "mount_point=/var/adm/ras/livedump"
tags {
   key: "mount_point"
   value: "/var/adm/ras/livedump"
 }
 fieldsDouble {
   key: "minimum"
   value: 0.247661590576
 }
```

but from tick script waiting 'mount_point_free_kb' tag inside. I just simply fix batch tick:
```
var data = batch
     |query('''
         SELECT min("mount_point_free_kb")/1024/1024 as minimum
         FROM "monitoring"."default".disk_capacity
         WHERE "host" = 'dwhfrn03'
     ''')
        .period(5d)
        .every(1m)
        .groupBy( time(1h), 'mount_point')

data
    //Run our tTest UDF on the hotend temperature
    @Forecast()
    .field('minimum')
    |alert()
        .crit(lambda: "interval_value" > 0)
        .log('/var/log/kapacitor/alerts_free_disk_space.log')
    |log(
```

**Comment by hasanashik** [comment]
Thank you.
