### ISSUE TITLE
GraphQL endpoint

### ISSUE THREAD

**Issue by mytototo** [influxdata/kapacitor#1084]
Hey,

Do you have plans about a GraphQL endpoint admin so we can consume it instead of the REST API ? Way much easier for a dashboard.

Thanks.

**Comment by nathanielc** [comment]
@mytototo No plans currently. Is there a specific API endpoint that isn't easy to use or are you looking more generally?

**Comment by mytototo** [comment]
@nathanielc It's for a general use. Out of curiosity. Thanks for the answer.
