### ISSUE TITLE
Query connect_errors disappeared.

### ISSUE THREAD

**Issue by AAbouZaid** [influxdata/kapacitor#1086]
Hello,
After upgrade to Kapacitor v1.1.1 ... `connect_errors` disappeared from query node in DOT.

How to reproduce:
```
kapacitor show TASK_NAME | grep -P "^query\d"
query1 [avg_exec_time_ns="81.72859ms" batches_queried="8210" points_queried="49260" query_errors="0" ];
...
```
`connect_errors` not exists anymore.

Info:
Kapacitor v1.1.1
Ubuntu 14.04.5

**Comment by nathanielc** [comment]
@AAbouZaid This is because an underlying change to the client was made that doesn't distinguish between connect_errors and query_errors. You can still track the errors via the `query_errors` stat.

**Comment by AAbouZaid** [comment]
@nathanielc Cool then! Thanks a lot Nathaniel.
But is that mentioned anywhere? e.g. change log.
Just to make sure no one else will wonder why it gone.

**Comment by nathanielc** [comment]
@AAbouZaid Good point I'll update the change log.
