### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by flcaza** [influxdata/kapacitor#1091]
I try to trigger an alert. What i do and what i have:
- all on same server
- influx --version InfluxDB shell version: 1.1.1
- telegraf --version Telegraf v1.1.2 (git: release-1.1.0 3da3a2279108d02c2158782794532de7cd7deacd)
- kapacitor Kapacitor starting, version 1.1.1, branch master, commit d1e0173df2b9f44c64b7bbf1a120a1bdb3ef683e

file:
- influxdb.conf
[meta]
  dir = "/var/lib/influxdb/meta"
[data]
  dir = "/var/lib/influxdb/data"
  wal-dir = "/var/lib/influxdb/wal"

- telegraf.conf
[global_tags]
    server = "dev-tools"
[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "dev_tools"
  omit_hostname = false
[[outputs.influxdb]]
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.apache]]
   urls = ["http://localhost/server-status?auto"]
[[inputs.net]]
    interfaces = ["eth0"]

- kapacitor.conf
hostname = "localhost"
data_dir = "/var/lib/kapacitor"
skip-config-overrides = false
default-retention-policy = ""

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"

[config-override]
  enabled = true

[logging]
    file = "/var/log/kapacitor/kapacitor.log"
    level = "INFO"

[replay]
  dir = "/var/lib/kapacitor/replay"

[task]
  dir = "/var/lib/kapacitor/tasks"
  snapshot-interval = "60s"

[storage]
  boltdb = "/var/lib/kapacitor/kapacitor.db"

[deadman]
  global = false
  threshold = 0.0
  interval = "10s"
  id = "node 'NODE_NAME' in task '{{ .TaskName }}'"
  message = "{{ .ID }} is {{ if eq .Level \"OK\" }}alive{{ else }}dead{{ end }}: {{ index .Fields \"collected\" | printf \"%0.3f\" }} points/INTERVAL."

[[influxdb]]
  enabled = true
  default = true
  name = "localhost"
  urls = ["http://localhost:8086"]
  username = ""
  password = ""
  timeout = 0
  insecure-skip-verify = false
  startup-timeout = "5m"
  disable-subscriptions = false
  subscription-protocol = "http"
  subscriptions-sync-interval = "1m0s"
  kapacitor-hostname = ""
  http-port = 0
  udp-bind = ""
  udp-buffer = 1000
  udp-read-buffer = 0

  [influxdb.subscriptions]
  [influxdb.excluded-subscriptions]

- cpu_alert.tick
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_system" > 0.1)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

commands:
kapacitor show cpu_alert
ID: cpu_alert
Error:
Template:
Type: stream
Status: enabled
Executing: true
Created: 16 Dec 16 12:38 UTC
Modified: 16 Dec 16 14:30 UTC
LastEnabled: 16 Dec 16 14:28 UTC
Databases Retention Policies: ["telegraf"."default"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_system" > 0.1)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')
        // Send alert to hander of choice.

DOT:
digraph cpu_alert {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0s" ];
stream0 -> from1 [processed="0"];

from1 [avg_exec_time_ns="0s" ];
from1 -> alert2 [processed="0"];

alert2 [alerts_triggered="0" avg_exec_time_ns="0s" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];

influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 1.1.1
InfluxDB shell version: 1.1.1
> show databases
name: databases
name
----
_internal
telegraf

> use telegraf
Using database telegraf
> select * from cpu limit 10
name: cpu
time                    cpu             host            server          usage_guest     usage_guest_nice        usage_idle      usage_iowait    usage_irq       usage_nice      usage_softirq   usage_steal     usage_system            usage_user
----                    ---             ----            ------          -----------     ----------------        ----------      ------------    ---------       ----------      -------------   -----------     ------------            ----------
1481894470000000000     cpu-total       dev_tools       dev-tools       0               0                       0               0               0      00               0               0.1999000499723049      99.80009994751875
1481894470000000000     cpu1            dev_tools       dev-tools       0               0                       0               0               0      00               0               0.199999999977299       99.80000000446104
1481894470000000000     cpu0            dev_tools       dev-tools       0               0                       0               0               0      00               0               0.20000000000436557     99.79999999981374
1481894480000000000     cpu1            dev_tools       dev-tools       0               0                       0               0               0      00               0               0.20000000000436557     99.79999999981374
1481894480000000000     cpu0            dev_tools       dev-tools       0               0                       0               0               0      00               0               0.20000000000436557     99.79999999981374
1481894480000000000     cpu-total       dev_tools       dev-tools       0               0                       0               0               0      00               0               0.2001000500364654      99.79989995211102
1481894490000000000     cpu0            dev_tools       dev-tools       0               0                       0               0               0      00               0               0.30030030029592597     99.69969970174338
1481894490000000000     cpu-total       dev_tools       dev-tools       0               0                       0               0               0      00               0               0.3999999999901047      99.5999999973178
1481894490000000000     cpu1            dev_tools       dev-tools       0               0                       0               0               0      00               0               0.5000000000058208      99.49999999722931
1481894500000000000     cpu-total       dev_tools       dev-tools       0               0                       0               0               0      00               0               0.3001500750364991      99.6998499270018

show subscriptions
name: _internal
retention_policy        name                                            mode    destinations
----------------        ----                                            ----    ------------
monitor                 kapacitor-0f8a8292-7c11-40f4-be8a-df0a848ccef3  ANY     [http://localhost:9092]

name: telegraf
retention_policy        name                                            mode    destinations
----------------        ----                                            ----    ------------
autogen                 kapacitor-0f8a8292-7c11-40f4-be8a-df0a848ccef3  ANY     [http://localhost:9092]

what i try:
delete all and start from begining
delete all database; restart all services

root@ip-192-168-2-110 ~# kapacitor stats ingress
Database   Retention Policy Measurement    Points Received
_internal  monitor          cq                           9
_internal  monitor          database                    18
_internal  monitor          httpd                        9
_internal  monitor          queryExecutor                9
_internal  monitor          runtime                      9
_internal  monitor          shard                       18
_internal  monitor          subscriber                  27
_internal  monitor          tsm1_cache                  18
_internal  monitor          tsm1_engine                 18
_internal  monitor          tsm1_filestore              18
_internal  monitor          tsm1_wal                    18
_internal  monitor          write                        9
_kapacitor autogen          edges                       45
_kapacitor autogen          ingress                    238
_kapacitor autogen          kapacitor                    9
_kapacitor autogen          nodes                       27
_kapacitor autogen          runtime                      9
telegraf   autogen          apache                      90
telegraf   autogen          cpu                        270
telegraf   autogen          disk                       180
telegraf   autogen          diskio                     180
telegraf   autogen          kernel                      90
telegraf   autogen          mem                         90
telegraf   autogen          net                        180
telegraf   autogen          processes                   90
telegraf   autogen          swap                       180
telegraf   autogen          system                     180
root@ip-192-168-2-110 ~#
root@ip-192-168-2-110 ~#
root@ip-192-168-2-110 ~#
root@ip-192-168-2-110 ~#
root@ip-192-168-2-110 ~# kapacitor stats ingress
Database   Retention Policy Measurement    Points Received
_internal  monitor          cq                          10
_internal  monitor          database                    20
_internal  monitor          httpd                       10
_internal  monitor          queryExecutor               10
_internal  monitor          runtime                     10
_internal  monitor          shard                       20
_internal  monitor          subscriber                  30
_internal  monitor          tsm1_cache                  20
_internal  monitor          tsm1_engine                 20
_internal  monitor          tsm1_filestore              20
_internal  monitor          tsm1_wal                    20
_internal  monitor          write                       10
_kapacitor autogen          edges                       50
_kapacitor autogen          ingress                    265
_kapacitor autogen          kapacitor                   10
_kapacitor autogen          nodes                       30
_kapacitor autogen          runtime                     10
telegraf   autogen          apache                     100
telegraf   autogen          cpu                        300
telegraf   autogen          disk                       200
telegraf   autogen          diskio                     200
telegraf   autogen          kernel                     100
telegraf   autogen          mem                        100
telegraf   autogen          net                        200
telegraf   autogen          processes                  100
telegraf   autogen          swap                       200
telegraf   autogen          system                     200

I do not have any idea why is not trigger any alert. Database are all the same "telegraf", i have data on measurement, i try to change to all i imagine and i do not trigger anything; i try even with kapacitor_example (database) but is the same.

Can you help me please ?

Thank you !
Florin

**Comment by flcaza** [comment]
Ok, somehow i fix this, break 15 min dink 1 coffee and delete all.

Now is working ( i have data). 

Next problem:
i record 1 second of alerts and i want to export/sent to Victorops. 

 kapacitor show cpu_alert
ID: cpu_alert
Error:
Template:
Type: stream
Status: disabled
Executing: false
Created: 16 Dec 16 14:58 UTC
Modified: 16 Dec 16 15:13 UTC
LastEnabled: 16 Dec 16 15:07 UTC
Databases Retention Policies: ["telegraf"."autogen"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" > 10)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')
        // Send alert to hander of choice.

        // Slack
        // .slack()
        // .channel('#alerts')

        // VictorOps
        .victorOps()

DOT:
digraph cpu_alert {
stream0 -> from1;
from1 -> alert2;
}

kapacitor.conf
[victorops]
  # Configure VictorOps with your API key and default routing key.
  enabled = true
  # Your VictorOps API Key.
  api-key = "my keyf"
  # Default VictorOps routing key, can be overridden per alert.
  routing-key = ""
  # The VictorOps API URL should not need to be changed.
  url = "https://alert.victorops.com/integrations/generic/20131114/alert"
  # If true the all alerts will be sent to VictorOps
  # without explicitly marking them in the TICKscript.
  # The routing key can still be overridden.
  global = false

kapacitor replay -recording 4e00e5be-1aed-4f0b-bbdf-555c9b27d887 -task cpu_alert
f8f1b3dc-b353-48ae-9b9b-6ddcef591b59

Error from kapacitor log is:
tail -f kapacitor.log
[task_master:f8f1b3dc-b353-48ae-9b9b-6ddcef591b59] 2016/12/16 15:14:47 I! Started task: cpu_alert
[cpu_alert:alert2] 2016/12/16 15:14:47 E! failed to send alert data to VictorOps: URL or API key not found: 404
[cpu_alert:alert2] 2016/12/16 15:14:48 E! failed to send alert data to VictorOps: URL or API key not found: 404
[cpu_alert:alert2] 2016/12/16 15:14:48 E! failed to send alert data to VictorOps: URL or API key not found: 404
[cpu_alert:alert2] 2016/12/16 15:14:48 E! failed to send alert data to VictorOps: URL or API key not found: 404
[cpu_alert:alert2] 2016/12/16 15:14:48 E! failed to send alert data to VictorOps: URL or API key not found: 404
[cpu_alert:alert2] 2016/12/16 15:14:48 E! failed to send alert data to VictorOps: URL or API key not found: 404
[task_master:f8f1b3dc-b353-48ae-9b9b-6ddcef591b59] 2016/12/16 15:14:48 I! Stopped task: cpu_alert
[task_master:f8f1b3dc-b353-48ae-9b9b-6ddcef591b59] 2016/12/16 15:14:48 I! closed

But url and api key are in kapacitor.conf.

Where is the error ? :)

Thank  you and have a great weekend !
Florin

**Comment by nathanielc** [comment]
@flcaza Did you set a routing key?

**Comment by flcaza** [comment]
Fixed, was from Api key.

Thank you !
