### ISSUE TITLE
Check the last record for a specific host

### ISSUE THREAD

**Issue by folly3** [influxdata/kapacitor#1093]
I want to create batch task, he checks if for a specific host the last time record is lower than the last 5 minutes.

My batch tick :

batch
    |query('''
        SELECT *
        FROM "telegraf"."autogen"."cpu"
        WHERE host = 'monitor2'
        LIMIT 1
    ''')
        .period(5m)
        .every(5m)
    |alert()
        .crit(lambda: "time" < now() - 5m )
        .log('/tmp/alerts.log')

but no result in the log file.

Any suggestions?
My request it is possible  ?

**Comment by flcaza** [comment]
hi folly3,

try to go in influx database and see if you have any result for query, i try on my db and is working

SELECT * FROM "telegraf"."autogen"."cpu" WHERE host = 'dev_tools' limit 1
name: cpu
time                    cpu     device  host            pct_pct_idle    pct_pct_iowait  pct_pct_nice    pct_pct_steal   pct_pct_system  pct_pct_user    server          usage_guest     usage_guest_nice      usage_idle       usage_iowait    usage_irq       usage_nice      usage_softirq   usage_steal     usage_system    usage_user
----                    ---     ------  ----            ------------    --------------  ------------    -------------   --------------  ------------    ------          -----------     ----------------      ----------       ------------    ---------       ----------      -------------   -----------     ------------    ----------
1482243394000000000             all     dev_tools       97.99           0               0               0               1.51            0.5             dev-tools

post if you have a result for query

**Comment by folly3** [comment]
Hi flcaza,

Yes i have a result :

SELECT * FROM "telegraf"."autogen"."cpu" WHERE host = 'monitor2' LIMIT 1
name: cpu
time                    cpu             env     host                    usage_guest     usage_guest_nice        usage_idle              usage_iowait            usage_irq       usage_nice      usage_softirq   usage_steal     usage_system            usage_user
----                    ---             ---     ----                    -----------     ----------------        ----------              ------------            ---------       ----------      -------------   -----------     ------------            ----------
1479463860000000000     cpu-total               monitor2    0               0                       98.98947719986437       0.03340571237646387     0               0               0               0               0.26724569901171097     0.7098713880008067

then i don't understand why my batch tick doesn't works, because when i exec this : 

SELECT * FROM "telegraf"."autogen"."cpu" WHERE host = 'monitor2.localdomain' and time > now() - 5m LIMIT 1

i have 0 result, and my batch throws 0 alert in my log file ...

**Comment by flcaza** [comment]
Folly3, in past i have some similar problem, if you can stop influxdb, stop, telegraf, stop kapacitor, delete influxdb databases (i prefer to delete dir from /var/lib/influxdb), delete kapacitor database (again delete dir from /var/lib/kapacitor) 
start influxdb (check if it is working, login from bash) 
start telegraf (see if you have some data in influxdb)
start kapacitor - again initialize cpu.tick (not batch, just normal one), check if it is working, if it is working start another cpu in batch mode, 

this is my batch

// metric: usage_user
// available_fields: "usage_guest","usage_guest_nice","usage_idle","usage_iowait", "usage_irq","usage_nice","usage_softirq","usage_steal","usage_system"

// Parameters
var info = 70
var warn = 80
var crit = 90
var infoSig = 2.5
var warnSig = 3
var critSig = 3.5
var period = 10s
var every = 10s

// Dataframe
var data = batch
  |query('''SELECT mean(usage_user) AS stat FROM "telegraf"."autogen"."cpu" WHERE cpu = 'cpu-total' ''')
    .period(period)
    .every(every)
    .groupBy('host')

// Thresholds
var alert = data
  |eval(lambda: sigma("stat"))
    .as('sigma')
    .keep()
  |alert()
    .id('batch/{{ index .Tags "host"}}/cpu_used')
    .message('{{ .ID }}:{{ index .Fields "stat" }}')
    .info(lambda: "stat" > info OR "sigma" > infoSig)
    .warn(lambda: "stat" > warn OR "sigma" > warnSig)
    .crit(lambda: "stat" > crit OR "sigma" > critSig)
    .stateChangesOnly()

        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

**Comment by folly3** [comment]
Ok thanks flcaza,

i have an other question :  how i can check if the batch query return a empty result ?
