### ISSUE TITLE
kapacitor id

### ISSUE THREAD

**Issue by flcaza** [influxdata/kapacitor#1096]
Hi,

Small problem :) All working well but i want to customize my id. What i want:
{"id":"cpu/hostnr1","message":"CRITICAL: blablabla

i try with different id:
    |alert()
        .id('{{ index .Tags "host" }}/{{ index .Tags "cpu" }}')
//        .id('{{ .Name }}-{{ index .Tags "service" }}')
//        .id('{{ index .Tags "host" }}')
//        .id('{{ index .Tags "host"}}/disk_used')

but what i get is only 
{"id":"cpu/","message":"CRITICAL: blablabla

without hostname. Of course after every try modification i did a "kapacitor define cpu_alert -tick cpu_alert.tick"

kapacitor show cpu_alert
ID: cpu_alert
Error:
Template:
Type: stream
Status: enabled
Executing: true
Created: 16 Dec 16 14:58 UTC
Modified: 20 Dec 16 06:47 UTC
LastEnabled: 20 Dec 16 06:47 UTC
Databases Retention Policies: ["telegraf"."autogen"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |window()
        .period(5s)
        .every(2s)
    |alert()
        .id('{{ index .Tags "host" }}/{{ index .Tags "cpu" }}')
        //        .id('{{ .Name }}-{{ index .Tags "service" }}')
        //        .id('{{ index .Tags "host" }}')
        //        .id('{{ index .Tags "host"}}/disk_used')
        .message('{{ .Level}}: {{ .Name }}/{{ index .Tags "host" }} has high cpu usage: {{ index .Fields "used" }}')
        .warn(lambda: "usage_user" > 70.0)
        .crit(lambda: "usage_user" > 85.0)
        // Whenever we get an alert write it to a file.

        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

from what i understand from documentation:
 .id('{{ .Name }} - is the name - in my case cpu 
 .id('{{ index .Tags "host" }}') is from measurement cpu with tag host - in my case dev_tools but is not working .....

select * from cpu limit 1
name: cpu
time                    cpu             host            server          usage_guest     usage_guest_nice        usage_idle      usage_iowait     usage_irq       usage_nice      usage_softirq   usage_steal     usage_system            usage_user
----                    ---             ----            ------          -----------     ----------------        ----------      ------------     ---------       ----------      -------------   -----------     ------------            ----------
1482149098000000000     cpu-total       dev_tools       dev-tools       0               0                       45.853658538025840               0               0               0               0               2.439024390607484       51.70731708059472

What i did wrong ?

Thank you for your time and help !

Florin

**Comment by flcaza** [comment]
all .tick

stream
    |from()
        .measurement('cpu')
    // create a new field called 'used' which inverts the idle cpu.
    |eval(lambda: 100.0 - "usage_idle")
        .as('used')
    // |groupBy('service', 'datacenter')
    |window()
        .period(10s)
        .every(10s)
    // calculate the 95th percentile of the used cpu.
    |percentile('used', 95.0)
    |eval(lambda: sigma("percentile"))
        .as('sigma')
        .keep('percentile', 'sigma')
   |alert()
        .id('{{ index .Tags "host" }}/{{ index .Tags "cpu" }}')
// .id('{{ .Name }}-{{ index .Tags "service" }}')
// .id('{{ index .Tags "host" }}')
// .id('{{ index .Tags "host"}}/disk_used')

**Comment by nathanielc** [comment]
@flcaza You need to group by the tags you want in order to preserve them through aggregation operations like `percentile`. So add both `host` and `cpu` to the groupBy list. That should get you started.

**Comment by flcaza** [comment]
Great, all worked well.

Thank you Nathaniel
