### ISSUE TITLE
Feature Request - The formatting of "kapacitor list tasks" should handle long Task ID names.

### ISSUE THREAD

**Issue by darrenmillin** [influxdata/kapacitor#1098]
If the command "kapacitor list tasks" is run, and there are Task IDs in the system with over 30 characters, the space between the Task ID and Type columns disappears. The table formatting
also becomes skewed:

root@influx:~# kapacitor list tasks
ID                            Type      Status    Executing Databases and Retention Policies

aaaaaaa_bbbbbb_ccccc_alert  batch     enabled   true      ["a"."seven_days"]
aaaaaa_bbbbbb_ccc_ddd_eeeee_alertbatch     enabled   true      ["b"."autogen"]

**Comment by nathanielc** [comment]
@darrenmillin What version are you running? I believe this was fixed in 1.1

**Comment by darrenmillin** [comment]
We are running 1.0.0-1 in production. I'll upgrade to 1.1 in test.

**Comment by rossmcdonald** [comment]
@darrenmillin Have you been able to verify that upgrading to v1.1 fixes the issue?

**Comment by darrenmillin** [comment]
Thank you @rossmcdonald. The issue has been resolved with v1.1

**Comment by darrenmillin** [comment]
Thank you @rossmcdonald. The issue has been resolved with v1.1

**Comment by darrenmillin** [comment]
Thank you @rossmcdonald. The issue has been resolved with v1.1
