### ISSUE TITLE
Feature Request - From node support cluster propertiy

### ISSUE THREAD

**Issue by oiooj** [influxdata/kapacitor#1099]
Can `from` node support `cluster` propertiy, just like `query.cluster` in `batch`?

```
// The name of a configured InfluxDB cluster. If empty the default cluster will be used.

node.cluster(value string)
```

**Comment by rossmcdonald** [comment]
@oiooj When receiving points over a stream, Kapacitor doesn't have any notion of which cluster/host is sending the data to it, only the target database and retention policy. Please see https://github.com/influxdata/kapacitor/issues/489 for more information and workaround.
