### ISSUE TITLE
Delete Node doesn't Delete Tags

### ISSUE THREAD

**Issue by rbinnun** [influxdata/kapacitor#1113]
Kapacitor: 1.1.1 
InfluxDB shell: 1.1.1
Installation Source: Pre-built package
OS: Linux Mint 18 Sarah 64-bit | Kernel Linux 4.4.0-57-generic x86_64

In the example below the fields get deleted but the tags don't. 
Am I missing something or is this a bug?

    var raw_event = stream
        |from()
            .measurement('raw_event')
        |delete()
            .tag('glocation')
            .field('rcount')
            ...
    raw_event
        |influxDBOut()
            .database('test1')
            .measurement('test1')

Stats show....

    "node-stats": {
        "delete2": {
            "avg_exec_time_ns": 11857,
            "collected": 1378,
            "emitted": 1378,
            "fields_deleted": 5512,
            "tags_deleted": 0
            }...

**Comment by nathanielc** [comment]
@rbinnun The stat counter only increments if a tag existed to be deleted. Can you confirm that the `glocation` tag exists on the raw data and has been deleted after the `|delete()`? Using `|log()` is a quick way to debug it.

**Comment by rbinnun** [comment]
@nathanielc The `|delete()` is working just fine. I was showing a fragment of the code above. Once I added the `|log()` it helped me spot the issue pretty quickly - thanks!
