### ISSUE TITLE
stateChangeOnly across kapacitor restarts

### ISSUE THREAD

**Issue by m4ce** [influxdata/kapacitor#1115]
Hi,

I noticed that when restarting kapacitor, alerts that were already already in CRITICAL state get re-evaluated and alerts trigger again, flooding the recipients.

Is there any way to prevent the above?

Thanks,
Matteo

**Comment by rossmcdonald** [comment]
@m4ce This is caused by alert state not being persisted across reboots. You can find more information in https://github.com/influxdata/kapacitor/issues/744.
