### ISSUE TITLE
Unusefull to redefined the kapacitor listen port from 9092 to 19092

### ISSUE THREAD

**Issue by zh4af** [influxdata/kapacitor#1119]
## 1.update the kapacitor.conf
17 [http]
18   # HTTP API Server for Kapacitor
19   # This server is always on,
20   # it servers both as a write endpoint
21   # and as the API endpoint for all other
22   # Kapacitor calls.
23   bind-address = ":19092"
24   auth-enabled = false
25   log-enabled = true
26   write-tracing = false
27   pprof-enabled = false
28   https-enabled = false
29   https-certificate = "/etc/ssl/kapacitor.pem"

## 2.restart service
#service kapacitor restart

## 3.view the port
#netstat -nltupa |grep kapacitor
tcp        0      0 :::19092                    :::*                        LISTEN      18533/kapacitord

## 4. define a task with kapacitor
#kapacitor define mem_alert -type stream -tick mem_alert.tick -dbrp telegraf.autogen
Post http://localhost:9092/kapacitor/v1/tasks: EOF

The kapacitor cmd is also post data to port 9092, it seems to unupdatable.

Now the port 9092 is used by my service, how can I work with kapacitor?

**Comment by zh4af** [comment]
kapacitor -url http://localhost:19092

**Comment by nathanielc** [comment]
@zh4af Also

```
export KAPACITOR_URL=http://localhost:19092
kapacitor list tasks
```
