### ISSUE TITLE
kapacitor.db inside kapacitor-docker-container

### ISSUE THREAD

**Issue by sfwn** [influxdata/kapacitor#1125]
kapacitor docker image version: **1.0-alpine**
I run kapacitor through docker, volume `/var/lib/kapacitor/:/var/lib/kapacitor/` for data persistence.
But after I stop & remove kapacitor-docker-container, recreate & run this container again, I lost all my tasks by typing `# kapacitor list tasks` inside container.

Inside container, I found default config file `/etc/kapacitor/kapacitor.conf` with content below:
```
data_dir = "/var/lib/kapacitor"

[replay]
  dir = "/var/lib/kapacitor/replay"

[storage]
  dir = "/var/lib/kapacitor/kapacitor.db"
```
But I found the real **kapacitor.db** is under the root dir: `/kapacitor.db` and when I run docker container with `-v /var/lib/kapacitor/kapacitor.db:/kapacitor.db`, the tasks persist.

I am confused with `/kapacitor.conf` and `[storage]` config in `/etc/kapacitor/kapacitor.conf`.

**Comment by nathanielc** [comment]
See https://github.com/influxdata/influxdata-docker/issues/56
