### ISSUE TITLE
Logging: provide an option to separate the logs

### ISSUE THREAD

**Issue by sadhen** [influxdata/kapacitor#1129]
Currently, kapacitor logs the task debug info into the same log file. I suggest that it should log the task debug in to different log file. For example, task1.log task2.log task3.log . Or provide an config option to enable this feature.

It would be beneficial for integrating these task debug infos into a "tickscript studo".

For example, https://github.com/sequentialread/tickscript-studio take use of the log file. But there are too many noises.

**Comment by nathanielc** [comment]
@sadhen Agreed, I had a discussion with the author of tickscript-studio around the same issue. I proposed that we create an HTTP endpoint that would stream the logs and you could specify the desired task logs via the query string etc.

Does that sound like it would also work for your use case?

**Comment by sadhen** [comment]
Yes
