### ISSUE TITLE
Telegram parseMode option Markdown should be case-insensitive

### ISSUE THREAD

**Issue by Appeltabak** [influxdata/kapacitor#1133]
Kapacitor is unable to send alerts to Telegram when the option `parseMode` is set e.g. to `markdown` instead of `Markdown`:

```
[mbo_deadman:alert6] 2017/01/17 09:04:59 E! failed to send alert data to Telegram: parseMode markdown is not valid, please use 'Markdown' or 'HTML'
```

This occurred to me when using a template alert and template variables.

##### System info
Kapacitor 1.1.1 Official Docker image

**Comment by rossmcdonald** [comment]
Looking at the Telegram API reference [here](https://core.telegram.org/bots/api#sendmessage), it seems like Telegram expects the exact text `Markdown` or `HTML` (case-sensitive). If that's not the case, it should be a very quick fix to update the check to be case in-sensitive:

https://github.com/influxdata/kapacitor/blob/master/services/telegram/service.go#L146

We would accept a PR if someone wants to verify that the parse_mode text is not case-sensitive.

**Comment by Appeltabak** [comment]
I've tested this for both HTML and Markdown using random cased letters: the API is not case-sensitive:
![selection_014](https://cloud.githubusercontent.com/assets/6260588/22548277/046f8198-e946-11e6-872f-6ae04d18f65d.png)

**Comment by rossmcdonald** [comment]
@Appeltabak That's great. Would you like to submit a PR for that change? I can do it, if not.

**Comment by Appeltabak** [comment]
@rossmcdonald  Yes, I'll try to submit one today

**Comment by dgellow** [comment]
I can see that The PR #1168 has been approved. Is there a reason it hasn't been merged?
