### ISSUE TITLE
How to get "com.docker.service.name" in Tags section

### ISSUE THREAD

**Issue by adityacs** [influxdata/kapacitor#1139]
How to write custom message with tag value of "com.docker.swarm.service.name"?. Below is my script. However, tag value is displayed as null in the alert. I even tried this way ".message('{{ .Level}}: { {index.Tags "[[com.docker.swarm.service.name]]" }} has high cpu usage: {{ index .Fields "cpu_usage" }}')".

 batch
    |query('''
         select sum(usage_percent) as cpu_usage from "telegraf"."default"."service_cpu_usage" where "com.docker.swarm.service.name"='jenkins' order by time desc
    ''')
       .period(15m)
       .every(1m)
       .groupBy(time(10s), 'com.docker.swarm.service.name')

    |alert()
        .message('{{ .Level}}: { {index .Tags "com.docker.swarm.service.name" }} has high cpu usage: {{ index .Fields "cpu_usage" }}')
        .crit(lambda: "cpu_usage" > 80)
        .log('/opt/kap/container_cpu_alerts.log')
        .exec('/opt/kap/container_cpu_alert.py')

Thanks

**Comment by nathanielc** [comment]
That should read:

`.message('{{ .Level}}: {{index .Tags "com.docker.swarm.service.name" }} has high cpu usage: {{ index .Fields "cpu_usage" }}')`

**Comment by adityacs** [comment]
Thanks. It works now. I am not sure why I was getting null value. 

However, Thank you so much.
