### ISSUE TITLE
Kapacitor memory leak in 1.1 and 1.2

### ISSUE THREAD

**Issue by joshuajoh** [influxdata/kapacitor#1153]
Issue:  Memory consumption with batch tick script:  in 16 hours memory usage grows from 30MB to 922MB.

Redhat 6.8
Kapacitor 1.2.0, pre-built

Tick script:  

- Grab 30 minute time slices from now and also every week for 5 weeks
- Compute STDDEV/AVG 
- Write the results back InfluxDB

Source Data:  

- Field values are stored in API_TRX or API_CNT tags
- Not all of the monitors have data going back 5 weeks
- 83 monitors have 5 weeks of data
- 212 have < 5 weeks
- This discrepancy is seen in the output of TICK DOT

Other items:  

- This is only TICK script running 
- See the issue in 1.1 and 1.2 versions 
- Disabled subscriptions, kapacitor is only operating in batch mode

Guess:  Seems the discarded join points are still consuming memory.

Please let me know if any other debugging output is needed.

```
var current = batch
    |query('''
                SELECT
                        STDDEV("value"),
                        MEAN("value")
                FROM "API_TRANSACTIONS"."autogen"."API"
                WHERE "metric" = 'API_TRX' OR "metric" = 'API_CNT'
        ''')
        .period(30m)
        .every(60s)
        .groupBy('monitor')

var week1 = batch
    |query('''
                SELECT
                        STDDEV("value"),
                        MEAN("value")
                FROM "API_TRANSACTIONS"."autogen"."API"
                WHERE "metric" = 'API_TRX' OR "metric" = 'API_CNT'
        ''')
        .every(60s)
        .period(30m)
        .offset(7d)
        .groupBy('monitor')
    |shift(7d)

<snip>

    |query('''
                SELECT
                        STDDEV("value"),
                        MEAN("value")
                FROM "API_TRANSACTIONS"."autogen"."API"
                WHERE "metric" = 'API_TRX' OR "metric" = 'API_CNT'
        ''')
        .every(60s)
        .period(30m)
        .offset(35d)
        .groupBy('monitor')
    |shift(35d)

current
    |join(week1, week2, week3, week4, week5)
        .as('current', 'week1', 'week2', 'week3', 'week4', 'week5')
        .tolerance(10s)
    |shift(30m)
    |eval(
        lambda: "week1.stddev" + "week2.stddev" + "week3.stddev" + "week4.stddev" + "week5.stddev",
        lambda: "total_dev" / 5.0,
        lambda: "week1.mean" + "week2.mean" + "week3.mean" + "week4.mean" + "week5.mean",
        lambda: "total_mean" / 5.0
    )
        .as('total_dev', 'historical_stddev', 'total_mean', 'historical_mean')
        .keep('historical_stddev', 'historical_mean')
    |influxDBOut()
        .database('API_TRANSACTIONS')
        .measurement('Historical')
        .tag('message', 'all api test')
        .tag('version', '0.01')


DOT:
digraph mea_week_stddev_calc {
graph [throughput="0.00 batches/s"];

query10 [avg_exec_time_ns="107.133682ms" batches_queried="86578" points_queried="85772" query_errors="0" ];
query10 -> shift11 [processed="86578"];

shift11 [avg_exec_time_ns="189ns" ];
shift11 -> join17 [processed="86578"];

query8 [avg_exec_time_ns="78.072853ms" batches_queried="98853" points_queried="98853" query_errors="0" ];
query8 -> shift9 [processed="98853"];

shift9 [avg_exec_time_ns="216ns" ];
shift9 -> join17 [processed="98853"];

query6 [avg_exec_time_ns="145.399237ms" batches_queried="351345" points_queried="351345" query_errors="0" ];
query6 -> shift7 [processed="351345"];

shift7 [avg_exec_time_ns="150ns" ];
shift7 -> join17 [processed="351345"];

query4 [avg_exec_time_ns="138.89073ms" batches_queried="351345" points_queried="351345" query_errors="0" ];
query4 -> shift5 [processed="351345"];

shift5 [avg_exec_time_ns="278ns" ];
shift5 -> join17 [processed="351345"];

query2 [avg_exec_time_ns="160.625741ms" batches_queried="351345" points_queried="351345" query_errors="0" ];
query2 -> shift3 [processed="351345"];

shift3 [avg_exec_time_ns="131ns" ];
shift3 -> join17 [processed="351345"];

query1 [avg_exec_time_ns="92.655603ms" batches_queried="351345" points_queried="351345" query_errors="0" ];
query1 -> join17 [processed="351345"];

join17 [avg_exec_time_ns="50.417µs" ];
join17 -> shift18 [processed="98853"];

shift18 [avg_exec_time_ns="137ns" ];
shift18 -> eval19 [processed="98853"];

eval19 [avg_exec_time_ns="106.44µs" eval_errors="0" ];
eval19 -> influxdb_out20 [processed="98853"];

influxdb_out20 [avg_exec_time_ns="7.925µs" points_written="85772" write_errors="0" ];
}
```

**Comment by nathanielc** [comment]
@joshuajoh Thanks! I'll look into reproducing locally.

**Comment by nathanielc** [comment]
I have a hypothesis as to what is going on. Testing locally the processed counts on each of the shift nodes for each week counts up in step with the processed count for the join nodes. In other words the join is working as expected creating one point per one point from each parent. However, if data was missing for that week, then the query node would not output any data, and then the point would be missing. In turn the join would block and buffer those points till data arrived. Internally the join is buffering points for each group (i.e. monitor tag value). 

Looking at you output there is a similar pattern. query10 has only processed 86578 and query8  has only processed 98853 points. The join node has processed 98853, the same as query8. Where as most other  query nodes have processed 351345 points. The `351345 - 98853 = 252492` points are buffered in the join node, clearly consuming lots of ram.

 The query node should be emitting an empty batch if the query returned zero results so that this doesn't happen. I'll look into it. If you don't query weeks 4 and 5 or backfill data for weeks 4 and 5 with 0 or something then you can probably get around this issue for now.

**Comment by joshuajoh** [comment]
@nathanielc Thank-you for the workaround ideas.

Does this buffering in join also occur in union? 

I was thinking of using union to calculate the entire stddev/mean of the time slices instead of using the average of each 30 min period.

**Comment by nathanielc** [comment]
@joshuajoh Yes, union also buffers, but not as much as the join node since it is easier to satisfy the conditions needed to emit each point.

**Comment by nhaugo** [comment]
See #1173
