### ISSUE TITLE
Kapacitor mail alert data format JSON to plain text

### ISSUE THREAD

**Issue by partheshzeotap** [influxdata/kapacitor#1155]
I configured TICK stack and it's working fine. Now I need to send mail alerts using kapacitor. kapacitor connected with chronograf and influxdb . kapacitor sending mail alerts in JSON format. I need alert data in plain text format. How can I change data format?

![rsz_screen_shot_2017-01-31_at_51024_pm](https://cloud.githubusercontent.com/assets/23651572/22463703/0f8ed7fe-e7d9-11e6-8244-2a49a8bc35ac.png)

**Comment by nathanielc** [comment]
@partheshzeotap Are the Kapacitor tasks you are using created with Chronograf? 

Kapacitor has the ability to send emails with plain text content via the [details](https://docs.influxdata.com/kapacitor/v1.2/nodes/alert_node/#details) property of the alert node.

Chronograf does not expose that property yet.

**Comment by goller** [comment]
@partheshzeotap I've added chronograf PR https://github.com/influxdata/chronograf/pull/835 to handle this issue.  Once it is merged you'll need to open your kapacitor alert rules and "resave" them so that they will now have the `.details()` field filled out.

**Comment by partheshzeotap** [comment]
I used TICK stack with docker and docker-compose. Using chronograf web-ui I m try to send alerts. @nathanielc

**Comment by partheshzeotap** [comment]
@goller @nathanielc 
I blocked on this issue.
I clone "/feature/kapacitor-detail" branch but I am able to start docker container.
 
Error: exec /usr/bin/chronograf : permission denide

Please give me some solutions.

**Comment by nhaugo** [comment]
Please take the conversation to chronograf, thanks!
