### ISSUE TITLE
Add ability to expire groups

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#1157]
Kapacitor has a similar issue to the InfluxDB TSI cardinality issue, where Kapacitor will remember tags forever. Kapacitor needs to ability to expire or remove tags, groups from the running tasks. This way the cardinality doesn't growth indefinitely in time.  See #610 for an initial implementation that will be to be reworked.

**Comment by ono760** [comment]
Instead of using the deadman, could use the barrier node. In this case, priority should be given to window nodes.
