### ISSUE TITLE
Mail alert picking wrong address

### ISSUE THREAD

**Issue by adityacs** [influxdata/kapacitor#1160]
I have the smtp configured as below. However, from kapacitor logs I can see that it is trying to connect to different smtp. Very strange for me. Please help on this

[smtp]

  enabled = false
  host = "smtp.gmail.com"
  port = 587
  username = "myemailid"
  password = "mypassword"
  from = "email"
  to = ["email"]
  no-verify = false
  idle-timeout = "30s"
  global = false
  state-changes-only = false"""

###Logs
[smtp] 2017/02/01 11:10:40 E! error connecting to SMTP server dial tcp: lookup smtp.test.com on 192.168.2.1:53: no such host

Thanks,
Aditya

**Comment by nathanielc** [comment]
@adityacs Configuration can be overridden via the API. You can verify the running configuration options via the endpoint `http://localhost:9092/kapacitor/v1/config/smtp/`. A simple GET request will return JSON of the running config. See the [API docs](https://docs.influxdata.com/kapacitor/v1.2/api/api/#configuration) for more info.

**Comment by adityacs** [comment]
@nathanielc Thanks. Works for me. 

why when I update in /etc/kapacitor/kapacitor.conf it's not picking up?. I am restarting kapacitor as well

**Comment by nhaugo** [comment]
When changes to the SMTP configuration are made via the API those changes are stored in bolt and will not be overridden by the config file on restart. Let us know if there are still any questions.

**Comment by adityacs** [comment]
@nhaugo Thanks.

**Comment by crazy-canux** [comment]
Hi,  I have a question about this issue.
where do we store the value by http api?
And what if I want to reload configuration from /etc/kapacitor/kapacitor.conf not the bolt?
