### ISSUE TITLE
Feature Request: adding roll up to alerts

### ISSUE THREAD

**Issue by usdin** [influxdata/kapacitor#1167]
Hi,
Currently Kapacitor sends multiple alerts for different tags. Can we have roll-up feature, so Kapacitor will send one alert containing info of multiple alerts. 
Suppose we define roll-up for 1m in tick, kapacitor will collect all alerts generated in previous 1m and send all alerts.

**Comment by nathanielc** [comment]
@usdin What content would you want the aggregate alert to contain? FYI see related discussion here #828

**Comment by nhaugo** [comment]
Closing as duplicate
