### ISSUE TITLE
InfluxDB/Kapacitor integration with Machine Learning engines?

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/kapacitor#1172]
There is any  example on how to integrate influxdb as data source for any opensource ML engines  (tensorflow, scikit-learn, apache incubator-prediction-io , h2o-ai ?).

I would like build a anomaly detection system on top of influxdb with hardware/software monitoring metrics. 

Any suggestion on what engine could be most feasible for integration with kapacitor/influxdb?

**Comment by allen13** [comment]
This might get you started: https://docs.influxdata.com/kapacitor/v1.2/examples/anomaly_detection/

**Comment by goller** [comment]
Hi @toni-moreno, @desa and I put together a webinar last week about using InfluxDB as data for tensorflow.  Here is the repo of our code: https://github.com/influxdata/tensorflow-influxdb
 and here is the video: https://vimeo.com/202289126

Basically, we have a simple python library that queries InfluxDB and produces tensorflow's SequenceExamples.  For demo purposes we just load the entire sequence into RAM, but, it should be straightforward to use a tensorflow queue.

Let us know how it goes!
