### ISSUE TITLE
Is there a way to do dynamic number of alerts or triggers for an alert

### ISSUE THREAD

**Issue by rao2100** [influxdata/kapacitor#1176]
I am creating tasks from a template based on my own conf using the rest API. In this template I have crit alert defined which I pass in the lambda.

What I would like to do is to dynamically create multiple alerts based on rules in my conf. This is because each task can have different number of alerts/rules.

For example
rule1 = alert1
rule2 = alert2 
.
.

I thought of two ways this could be achieved:
1) Pass in a complex lambda where each rule is evaluated with an OR, downside i reckon would be hard to know which expression triggered the alert.
Example: 
`alert()
         .crit(lambda: ("metic1" 50) OR ( "metric2" < 40)`
2) Create a task without using a template and generate the task tick script my self. Hence I can put in multiple alerts.

Please do let me know how to go about this.

Thank you :)

**Comment by nathanielc** [comment]
@rao2100 Have you seen the templating feature builtin to Kapacitor? It might make your option 2 easier.  https://docs.influxdata.com/kapacitor/v1.2/examples/template_tasks/

**Comment by rao2100** [comment]
hi @nathanielc thank you for the reply.
Yeah I am using template, but it requires that i specify the number of alerts i need before hand. Below is my template, as you can see i defined two templates and pass in the lambda when i create a task.
Is there a way i can define the template so that i can pass in dynamic number of alerts? For example for one task i want to pass in 2 alert and for another 3 using the same template. Thanks again :)

`// Parameters
var vnfId string
var vduId string
var measurementIn string
var cost float
var costId string
var metric string
var warn lambda
var crit lambda
var warnUrl string
var critUrl string
var measurementOut string
var groups = [*]

// Fixed Parameters
var period = 1m
var every = 1m
var database = 'telegraf'
var retention = 'autogen'

// Dataframe
var data = stream
  |from()
    .database(database)
    .retentionPolicy(retention)
    .measurement(measurementIn)
    .groupBy(groups)
//need to change this to vdu
    .where(lambda: "cpu" == vduId)
  |window()
    .period(period)
    .every(every)
  |mean(metric)
    .as('metric')
  |eval(lambda: "metric" * cost, lambda: costId)
     // Give the resulting field a name
    .as('cost', 'costId')
    .keep('metric','cost', 'costId')

data
  |influxDBOut()
    .database('calm')
    .retentionPolicy('autogen')
    .measurement(measurementOut)

data
  |alert()
    .warn(warn)
    .post(warnUrl)
    .log('/tmp/warn.log')

data
  |alert()
    .crit(crit)
    .post(critUrl)
    .log('/tmp/crit.log')`

**Comment by nathanielc** [comment]
@rao2100 The templating system does not allow you to modify the task DAG( the task structure), but rather the contents and options of each of the nodes in the task DAG.

Are you trying to do multiple alerts so that each alert level can have a different handler? Or is that just specific to this one TICKscript?

**Comment by rao2100** [comment]
Hi @nathanielc 
I've decided on the approach of creating multiple template files for each scenario.

That will solve my issue :)
