### ISSUE TITLE
Deadman fires on "<=", intentional?

### ISSUE THREAD

**Issue by octalthorpe** [influxdata/kapacitor#1179]
So it appears that the deadman will fire on a threshold of "<=", which does not match, the documentation:
```
Helper function for creating an alert on low throughput, a.k.a. deadman's switch.
Threshold – trigger alert if throughput drops below threshold in points/interval.
```

Looking at the code is looks like the alert is set to fire on "TokenLessEqual"

```
func (n *node) Deadman(threshold float64, interval time.Duration, expr ...*ast.LambdaNode) *AlertNode {
	dn := n.Stats(interval).Align().
		Derivative("emitted").NonNegative()
	dn.Unit = interval

	an := dn.Alert()
	critExpr := &ast.BinaryNode{
		Operator: ast.TokenLessEqual,
		Left: &ast.ReferenceNode{
			Reference: "emitted",
		},
		Right: &ast.NumberNode{
			IsFloat: true,
			Float64: threshold,
		},
	}
```

Is this the intention?  I would expect if I set deadman to 1.0 i.e.
```
deadman(1.0, 10m)
```
The the alert would fire if there were "<" 1 points in that window.  If I received 1 point, then no alert would occur.

Easy for me to change to:
```
deadman(0.9, 10m)
```
Just wondering if this was done with purpose?

Thanks

**Comment by nathanielc** [comment]
Yes, this was intentional. I'll update the docs to make it more clear.
