### ISSUE TITLE
'timestamp' field cannot be counted if timestamp is present in line protocol

### ISSUE THREAD

**Issue by sputnik13** [influxdata/kapacitor#1180]
With the following tick script

    stream
        |from()
            .measurement('timestamp.test')
        |window()
            .period(60s)
            .every(1s)
        |count('timestamp')
        |alert()
            .id('d712f384-7b79-48c6-8a52-d22d468f9acb')
            .message('10 timestamps found')
            .crit(lambda: "count" > 10)
            .stateChangesOnly(60s)
            .log('/tmp/test.log')

When submitting this data via curl

    timestamp.test value=5i,timestamp=1486420682i

count is incremented as expected and we eventually get a critical alert

On the other hand if the optional timestamp is present in the line protocol

    timestamp.test value=5i,timestamp=1486420682i 1486420682000000000

the count is not incremented and we never get a critical alert.

**Comment by nathanielc** [comment]
@sputnik13 Hmm, its not likely the name of the field is messing things up. Is it possible that when you specify the timestamp explicitly it is in the past and so does not trigger the window node to emit a new batch?

**Comment by sputnik13** [comment]
@nathanielc that seems to be it, I guess window period is based on the timestamp of the message (with implicit timestamp of 'now' when timestamp isn't present), not based on when it was received by kapacitor.

**Comment by nathanielc** [comment]
> I guess window period is based on the timestamp of the message (with implicit timestamp of 'now' when timestamp isn't present), not based on when it was received by kapacitor.

Correct, this allows tasks to be deterministic in nature.
