### ISSUE TITLE
Wrong Type errors in log, but alerts work

### ISSUE THREAD

**Issue by TomerAmirV** [influxdata/kapacitor#1182]
I have the following tick script:

```
var data = stream
    |from()
        .measurement('cpuStats')
    |groupBy('host', 'cluster')
    |window()
        .period(1h)
        .every(1m)
    |mean('idle')
    |eval(lambda: int(100.0 - "mean"))
        .as('res')

// Send Alert
data
    |alert()
        .id('{{ .TaskName }} - {{ index .Tags "host" }}')
        .message('{{ .Level}}: Host {{ index .Tags "host" }} CPU usage in the last hour is {{ index .Fields "res" }}%')
        .warn(lambda: "res" >= 25)
        .crit(lambda: "res" >= 50)
        .stateChangesOnly()
        .hipChat()

// Save data to Influxdb for dashboard
data
    |alert()
        .warn(lambda: "res" >= 25)
        .crit(lambda: "res" >= 50)
    |influxDBOut()
        .database('clusterStatus')
        .retentionPolicy('rp')
        .measurement('cpuStatus')
```

It looks like it's running fine since we are getting notifications when our CPUs work hard, but when we look at the log we see the following error:
```
[all_high_cpu:mean4] 2017/02/08 10:33:06 E! failed to aggregate batch: field idle has wrong type: got string exp float64
```

Looking at the database we can't find any string typed entries.
Should we be worried about this error?

* OS: centos7
* Kapacitor Version: `Kapacitor 1.1.1 (git: master d1e0173df2b9f44c64b7bbf1a120a1bdb3ef683e)`
* Installed pre-built version (did not build source ourseves)

**Comment by rossmcdonald** [comment]
@TomerAmirV It may be that one client is sending bad values. Can you try adding a [log node](https://docs.influxdata.com/kapacitor/latest/nodes/log_node/) to your task? This will dump the raw data to the Kapacitor logs, which should hopefully show why the error is being thrown.

For example:

```
var data = stream
    |from()
        .measurement('cpuStats')
    |groupBy('host', 'cluster')
    |window()
        .period(1h)
        .every(1m)
    |log()
    |mean('idle')
    ...
```
