### ISSUE TITLE
The relationship between Subscription and Batch

### ISSUE THREAD

**Issue by EricQAQ** [influxdata/kapacitor#1187]
Hi, I want to know the relationship between Subscription and Batch...

I use Kapacitior as the metrics alert, and if I set some dbcp in the influxdb.subscription in kapacitor.conf, I found that the server will send many udp packages...

And I have known that the Influxdb will use Subscription to send udp packages to kapacitor. But I'm wondering that if I just use Batch in the tickscript, is it necessary to set the `disable-subscriptions = false`? How about Stream?

Thanks a lot.

**Comment by nathanielc** [comment]
Batch tasks do not need subscriptions. So if you disable subscriptions batch tasks will continue to work, but stream tasks will not. Also o subscriptions can use HTTP/TCP instead of UDP.
