### ISSUE TITLE
no method or property "eval" on *pipeline.StreamNode

### ISSUE THREAD

**Issue by sc0rp10** [influxdata/kapacitor#1188]
I need to count some hit/miss ratio for two different measurements.
I'm got example from https://docs.influxdata.com/kapacitor/v1.2/nodes/influx_d_b_out_node/ and cant define new metric.
```
# kapacitord version
Kapacitor 1.2.0 (git: master 5408057e5a3493d3b5bd38d5d535ea45b587f8ff)

# cat foo.tick
stream
    |eval(lambda: "some_hit" / "some_miss")
        .as('some_hitmiss')
    |influxDBOut()
        .database('default')
        .measurement('ratios')
# kapacitor define foo -type stream -tick foo.tick -dbrp main.default
invalid TICKscript: line 2 char 6: no method or property "eval" on *pipeline.StreamNode
```
What am I doing wrong?

**Comment by nathanielc** [comment]
@sc0rp10 You must always use a `|from()` to select which data you want off the stream.

**Comment by sc0rp10** [comment]
@nathanielc thanks for reply, but I cant understand, how can I select data from two measurements with `|from()`.
Maybe is there another way with following code?
```
var hits = stream
    |from()
        .measurement('hit')

var misses = stream
    |from()
        .measurement('miss')

# ???
```

**Comment by nathanielc** [comment]
@sc0rp10 Your code snippet looks good. What do you want to do with the two measurements?

**Comment by sc0rp10** [comment]
@nathanielc devide first to second and store it as new measurement

**Comment by nathanielc** [comment]
Here is a quick example but I recommend reading the docs here too:

https://docs.influxdata.com/kapacitor/v1.2/nodes/join_node/
https://docs.influxdata.com/kapacitor/v1.2/examples/join_backfill/

```
var hits = stream
    |from()
        .measurement('hit')

var misses = stream
    |from()
        .measurement('miss')

hits
   |join(misses)
      .as('hits', 'misses')
   |eval(lambda:"hits.value" / "misses.value")
      .as('ratio')
   |influxDBOut()
      .database('db')
      .measurement('m')
```
