### ISSUE TITLE
Can I pass in a lambda variable to tick template for eval?

### ISSUE THREAD

**Issue by rao2100** [influxdata/kapacitor#1191]
Is something like below supported? Any examples please.
`var doCalc lambda

var data = stream
  |from()
    .database(database)
    .retentionPolicy(retention)
    .measurement(measurementIn)
    .groupBy(groups)
    .where(lambda: "cpu" == 'usage_user')
  |window()
    .period(period)
    .every(every)
  |eval(doCalc)
     // Give the resulting field a name
    .as('calcVal')
    .keep('calcVal')`

**Comment by nathanielc** [comment]
Yes that will work. See the Vars section right below the Tasks section https://docs.influxdata.com/kapacitor/v1.2/api/api/#tasks

**Comment by rao2100** [comment]
Thank you :) @nathanielc 

Posting my simple code and json for reference:

Tick Template:
`// Parameters
var measurementIn string
var measurementOut string
var cost float
var metric string
var crit lambda
var calc lambda
var groups = [*]

// Fixed Parameters
var period = 1m
var every = 1m
var database = 'telegraf'
var retention = 'autogen'

// Dataframe
var data = stream
  |from()
    .database(database)
    .retentionPolicy(retention)
    .measurement(measurementIn)
    .groupBy(groups)
//need to change this to vdu
    .where(lambda: "cpu" == 'cpu-total')
  |window()
    .period(period)
    .every(every)
  |mean(metric)
    .as('metric')
  //|eval(lambda: "metric" * cost)
  |eval(calc, lambda: cost)
     // Give the resulting field a name
    .as('calcCost', 'valCost')
    .keep('calcCost', 'metric', 'valCost')

data
  |influxDBOut()
    .database('calm')
    .retentionPolicy('autogen')
    .measurement(measurementOut)


data
  |alert()
    .crit(crit)
    .log('/tmp/rao.log')`


Tick JSON:

`{
    "groups": {"type": "list", "value": [{"type":"string", "value":"host"}]},
    "cost": {"type" : "float", "value" : 0.5},
    "measurementIn": {"type" : "string", "value" : "cpu" },
    "measurementOut": {"type" : "string", "value" : "rao_test" },
    "metric": {"type" : "string", "value" : "usage_user" },
    "calc": {"type" : "lambda", "value" : "\"metric\" * 5.0"},
    "crit": {"type" : "lambda", "value" : "50.0 > 10.0" }
}`
