### ISSUE TITLE
Default node does not handle batch groupBy tags correctly

### ISSUE THREAD

**Issue by fdhex** [influxdata/kapacitor#1192]
Hi,

In the following code, I expected the default to fill the gap of the missing value, but somehow it remains blank. What am I missing? I get an alert with id 'kapacitor//...'
```
batch
    |query('select mean(used_percent) from "influxdb"."default"."mem"')
      .groupBy('tag1','missing-tag')
      .period(15m)
      .every(15m)
    |eval(lambda: trunc("mean"))
      .as('mean')
    |default()
      .tag('missing-tag', 'unknown')
    |alert()
        .id('kapacitor/{{ index .Tags "missing-tag" }}/...
```

**Comment by nathanielc** [comment]
@fdhex This looks like a bug because of the groupBy in the batch query. I'll get a fix out for this.

 In the meantime this will get you working.

```
batch
    |query('select mean(used_percent) from "influxdb"."default"."mem"')
      .groupBy('tag1','missing-tag')
      .period(15m)
      .every(15m)
    // By using last here the edge type switches from batch to stream and the bug only exists in the batch handling, so this is a hack workaround. 
    // Using last doesn't change anything since the batch query only returns a single aggregated point anyways.
    |last('mean')
       .as('mean')
    |eval(lambda: trunc("mean"))
      .as('mean')
    |default()
      .tag('missing-tag', 'unknown')
    |alert()
        .id('kapacitor/{{ index .Tags "missing-tag" }}/...
```

**Comment by fdhex** [comment]
@nathanielc 

Thanks for the quick help, however the code you write above is still not working for me. Is there a specific release I should use?

**Comment by desa** [comment]
@nathanielc It appears to me that everything is working as I would expect it to. Maybe I have a misunderstanding though.

The issue that @fdhex is experiencing is that

```js
    |query('select mean(used_percent) from "influxdb"."default"."mem"')
      .groupBy('tag1','missing-tag')
```
actually sets the tags on the resulting data to give
```js
"tags":{"missing-tag":"","tag1":""}
```
Adding 
```js
    |query('select mean(used_percent) from "influxdb"."default"."mem"')
      .groupBy('tag1','missing-tag')
     ...
    |last('mean')
       .as('mean')
```
Changes that to
```js
"Tags":{"missing-tag":"","tag1":""}
```

So in either case, when the data hits
```js
|default()
   .tag('missing-tag','unknown')
```
the tag `missing-tag` exists and has a value of `""`. As a result, the default conditions don't apply.

The two paths I see ahead are

1. Change the functionality of the `default` node so that empty string satisfies the conditions for default (only for tags).
2. Document a work around for the case.

**Comment by desa** [comment]
I was both right and wrong. As discussed in Slack, the steps to fix the issue are
1. Change condition for empty string
2. Update Batch.Tags map
3. Update the .Group value on both the Batch struct and each stream Point struct

**Comment by desa** [comment]
Fixed by https://github.com/influxdata/kapacitor/pull/1233
