### ISSUE TITLE
Kapacitor HTTP API does not update task

### ISSUE THREAD

**Issue by alparslanuysal** [influxdata/kapacitor#1195]
Hi influxdata folks, I cannot update kapacitor task with http api.After sending the payload below,I check the task with "kapacitor show  m40_temp_alert1".It seems to be updated and changes the script values however it triggers old crit values for example(previous critTemp=30) 

URL (PATCH) : http://localhost:9092/kapacitor/v1/tasks/m40_temp_alert1
BODY:
{
	"id" : "m40_temp_alert1",
	"type": "stream",
	"dbrps": [
    {
      "db": "dell_iot",
      "rp": "autogen"
    }
  ],
	"script": "var critTemp = 70\n\nvar warningTemp = 60\n\nstream\n    |from()\n                .measurement('testtempaccxtable')\n        .where(lambda: \"machine_name\" == 'M40')\n    |alert()\n        .id('7')\n        .message('{{ index .Fields \"temp\" }}')\n        .crit(lambda: \"temp\" > critTemp)\n        .warn(lambda: \"temp\" > warningTemp)\n        .stateChangesOnly()\n        .details('')\n        .log('/home/iot/m40_alert_temp1.log')",
    "status":"enabled"
}

**Comment by nathanielc** [comment]
@alparslanuysal You will need to disable and then enable the task in order for it to apply the changes.

**Comment by SrikarshVardhan** [comment]
@alparslanuysal Are you able to patch your script. I am facing this issue. https://github.com/influxdata/kapacitor/issues/1639 

We are trying to patch this
"script": "batch\n |query('''\n SELECT count(response_time) as count\n from "sdp_monitoring"."13m"."net_response"\n where "type" = 'kafka'\n ''')\n .groupBy('cluster', 'host')\n .period(45s)\n .every(10s)\n |where(lambda: "count" \u003e 0)\n |deadman(1.0, 30s)\n .stateChangesOnly()\n .exec('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down')\n\n// stream\n// |from()\n// .database('sdp_monitoring')\n// .retentionPolicy('13m')\n// .measurement('net_response')\n// .where(lambda: "type" == 'kafka')\n// .groupBy('cluster', 'host')\n// |deadman(1.0, 30s)\n// .stateChangesOnly()\n// .exec('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down')\n\n"

adding this to the above AND "cluster" != 'tsys' but we are facing issue even while patching with same thing mentioned above. Below is the error we escaped brackets and \n even though we are facing error with script. Could anyone please have a look on this.

curl --request PATCH -H "Accept: application/json" --data '{"script": "batch/ \n |query('''/ \n SELECT count(response_time) as count/ \n from "sdp_monitoring"."13m"."net_response"/ \n where "type" = 'kafka'/ \n ''')/ \n .groupBy('cluster', 'host')/ \n .period(45s)/ \n .every(10s)/ \n |where(lambda: "count" \u003e 0)/ \n |deadman(1.0, 30s)/ \n .stateChangesOnly()/ \n .exec('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down')/ \n/ \n// stream/ \n// |from()/ \n// .database('sdp_monitoring')/ \n// .retentionPolicy('13m')/ \n// .measurement('net_response')/ \n// .where(lambda: "type" == 'kafka')/ \n// .groupBy('cluster', 'host')/ \n// |deadman(1.0, 30s)/ \n// .stateChangesOnly()/ \n// .exec('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down')/ \n/ \n"}' http://localhost:9092/kapacitor/v1/tasks/kafkaproc_alert
curl: (6) Could not resolve host: \n; Name or service not known
curl: (6) Could not resolve host: SELECT; Name or service not known
curl: (6) Could not resolve host: count(response_time); Name or service not known
curl: (6) Could not resolve host: as; Name or service not known
curl: (6) Could not resolve host: count; Name or service not known
curl: (6) Could not resolve host: \n; Name or service not known
curl: (6) Could not resolve host: from; Name or service not known
curl: (6) Could not resolve host: "sdp_monitoring"."13m"."net_response"; Name or service not known
curl: (6) Could not resolve host: \n; Name or service not known
curl: (6) Could not resolve host: where; Name or service not known
curl: (6) Could not resolve host: "type"; Name or service not known
curl: (6) Could not resolve host: =; Name or service not known
curl: (6) Could not resolve host: kafka; Name or service not known
curl: (6) Could not resolve host: \n; Name or service not known
curl: (6) Could not resolve host: ); Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down; Name or service not known
curl: (6) Could not resolve host: Alert, Kafka; Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down, Kafka; Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down); Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down; Name or service not known
curl: (6) Could not resolve host: Alert, Kafka; Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down, Kafka; Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (3) [globbing] unmatched close brace/bracket at pos 18
{
"error": "invalid JSON"
}
