### ISSUE TITLE
[feature request] Operator for verifying whether a value is present

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/kapacitor#1203]
Add a function that is able to be referenced in a lambda expression that returns a boolean based on whether the field/tag key is present. For example:

```
|eval(lambda: is_present("myfield"))
```

Which would return TRUE if `myfield` is a valid identifier and FALSE otherwise.

/cc @kostasb

**Comment by desa** [comment]
Going  to close this as it was delivered a while ago.
