### ISSUE TITLE
[feature request] Node for dropping whole points

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/kapacitor#1204]
Support the ability to drop points based on specific criteria. For example:

```
|drop(lambda: "value" < 0)
```

Which would simply drop the point from the DAG when `value` < 0. To do this today, you have to use an `eval` and a `where` node, which is not always obvious. To do the same thing today:

```
|eval(lambda: "value" < 0).as('drop_point').keep()
|where(lambda: "drop_point" == FALSE)
...
```

/cc @kostasb

**Comment by nathanielc** [comment]
Why doesn't using a single where node work?

```
|where(lambda: "value" >= 0)
```

or 

```
|where(lambda: !("value" < 0))
```

**Comment by rossmcdonald** [comment]
Ahhh, nevermind. I was obviously over-thinking this one.
