### ISSUE TITLE
Kapacitor failed to connect to InfluxDB on restart.

### ISSUE THREAD

**Issue by thealphaking01** [influxdata/kapacitor#1213]
I think this issue was solved, although I am not sure. I restarted Kapacitor and then none of my tasks were showing.

Restarting InfluxDB and then restarting Kapacitor again was also no use.

Getting the following output:

ID                            Type      Status    Executing Databases and Retention Policies
Get http://localhost:9092/kapacitor/v1/tasks?dot-view=attributes&fields=type&fields=status&fields=executing&fields=dbrps&limit=100&offset=0&pattern=&replay-id=&script-format=formatted: dial tcp 127.0.0.1:9092: getsockopt: connection refused

**Comment by rossmcdonald** [comment]
What version? The error:

> dial tcp 127.0.0.1:9092: getsockopt: connection refused

Either means the Kapacitor service is not active or the Kapacitor daemon is not listening on 127.0.0.1. Have you checked the Kapacitor logs for more information?

**Comment by thealphaking01** [comment]
Hey Guys,

Was finally able to solve the problem - Influx was crashing due to OOM the moment it was started, and that led to Kapacitor not responding properly. Anyway, had to remove some data from Influx, change its Retention Policy and then everything worked fine.

**Comment by Shadow126** [comment]
thea

> Hey Guys,
> 
> Was finally able to solve the problem - Influx was crashing due to OOM the moment it was started, and that led to Kapacitor not responding properly. Anyway, had to remove some data from Influx, change its Retention Policy and then everything worked fine. Closing the issue

Hi, how to fix?? tks!
