### ISSUE TITLE
Kapacitor triggers topic for one task only (sometimes)

### ISSUE THREAD

**Issue by jaapz** [influxdata/kapacitor#1220]
Ok, so this is a good one. Bear with me...

We log status data into influxdb, values are typically 0 (ok) or 1 (not ok). Theses values are all put into one measurement (log_record), and tagged with a "sensor_id".

I have a template in kapacitor which looks like this:

```
var sensorId string

var problemTypeId string

stream
    |from()
        .measurement('log_record')
    |where(lambda: "sensor_id" == sensorId)
    |default()
        .tag('problem_type_id', problemTypeId)
    |alert()
        .crit(lambda: "value" == 1)
        .topic('problem')
```

On the "problem" topic, I have a POST handler that posts the alert to a webhook that handles further processing, like figuring out who should receive notifications, and logging the alert in our relational database. That handler uses "stateChangeOnly", by the way, not much more to it.

Then I define two tasks with the same template, the same sensorId, but a different ID and problemTypeId.

Those tasks run and whenever 1 is logged to the measurements with the related sensorId's, they seem to react, they both add 1 to their "crits_triggered" value.

So because they both triggered a CRIT, I expect them both to send a POST to our webhook, through the "problem" topic.

However, there's always only *one* task whose alert is then also posted to our webhook. Sometimes it's the first one, sometimes it's the second. And sometimes it *does* POST both...

Am I doing something wrong, or did I uncover a bug?

**Comment by nathanielc** [comment]
My first guess is that the alert IDs are colliding. Try adding the task name to the alert ID to make it unique across all tasks from this template.

```
var sensorId string

var problemTypeId string

stream
    |from()
        .measurement('log_record')
    |where(lambda: "sensor_id" == sensorId)
    |default()
        .tag('problem_type_id', problemTypeId)
    |alert()
         .id('{{.TaskName}}:{{.Name}}:{{.Group}}')
        .crit(lambda: "value" == 1)
        .topic('problem')
```


The default ID template is `{{ .Name }}:{{ .Group }}` which will be the same for the two tasks since they have the same group by and measurement. 

The alert topic system treats alerts by their ID. This allows you to have alerts interact from different tasks, which is not what you want in this case so making them unique should fix the issue.

**Comment by jaapz** [comment]
Is Task ID something different than Alert ID?
I'll try this out later today, thanks for the quick response.

**Comment by jaapz** [comment]
Very nice, I just tested out the alert ID fix, and it fixed the problem so it was indeed the alert ID's colliding. Thanks for the solution!
