### ISSUE TITLE
Kapacitor can't run data through graph

### ISSUE THREAD

**Issue by juise** [influxdata/kapacitor#1230]
```
[analyzers]# influxd version
InfluxDB v1.1.1 (git: master e47cf1f2e83a02443d7115c54f838be8ee959644)
[analyzers]# telegraf version
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
[analyzers]# kapacitor version
Kapacitor 1.1.0 (git: master 939fdf670b028c142944977dcfcb045cac2343ed)
```

```
> show SUBSCRIPTIONS
name: _internal
retention_policy        name                                            mode    destinations
----------------        ----                                            ----    ------------
monitor                 kapacitor-c728dcf6-9cb5-4c2c-adcc-8515c8f04222  ANY     [http://localhost:9092]

name: telegraf
retention_policy        name                                            mode    destinations
----------------        ----                                            ----    ------------
autogen                 kapacitor-c728dcf6-9cb5-4c2c-adcc-8515c8f04222  ANY     [http://localhost:9092]
```

```
[analyzers]# kapacitor record stream -task cpu -duration 10s
6557c7bf-9498-430a-8064-3ada2cc12564
[analyzers]# kapacitor show cpu
ID: cpu
Error:
Template:
Type: stream
Status: disabled
Executing: false
Created: 27 Feb 17 10:37 -0500
Modified: 28 Feb 17 15:37 UTC
LastEnabled: 01 Jan 01 00:00 UTC
Databases Retention Policies: ["telegraf"."autogen"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" < 100)
        .stateChangesOnly()
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

DOT:
digraph cpu {
stream0 -> from1;
from1 -> alert2;
}
[analyzers]# kapacitor stats ingress | grep cpu
telegraf   autogen          cpu                      15037
...
[analyzers]# kapacitor stats ingress | grep cpu
telegraf   autogen          cpu                      15083
```

In logs:

```
[httpd] ::1 - - [28/Feb/2017:16:05:00 +0000] "POST /write?consistency=&db=_internal&precision=ns&rp=monitor HTTP/1.1" 204 0 "-" "InfluxDBClient" a800ae0d-fdcf-11e6-83bd-000000000000 2656
[edge:6557c7bf-9498-430a-8064-3ada2cc12564|stream->stream0] 2017/02/28 16:05:00 I! aborting c: 53 e: 53
[edge:6557c7bf-9498-430a-8064-3ada2cc12564|stream->stream0] 2017/02/28 16:05:00 D! closing c: 53 e: 53
[httpd] ::1 - - [28/Feb/2017:16:05:00 +0000] "POST /write?consistency=&db=telegraf&precision=ns&rp=autogen HTTP/1.1" 204 0 "-" "InfluxDBClient" a82e1162-fdcf-11e6-83be-000000000000 558
[httpd] ::1 - - [28/Feb/2017:16:05:00 +0000] "POST /write?consistency=&db=telegraf&precision=ns&rp=autogen HTTP/1.1" 204 0 "-" "InfluxDBClient" a82eb536-fdcf-11e6-83bf-000000000000 749
```

Looks like kapacitor can't run data through graph

**Comment by nathanielc** [comment]
What output were you expecting? Everything looks normal to me.

**Comment by juise** [comment]
I've expected to see /tmp/alerts.log file, but it didn't exists. Also, I've except to see that digraph will show me how many points flow through it

**Comment by nathanielc** [comment]
The digraph will show you points that flow through it but you first need to enable the task.

```
kapacitor enable cpu
```

If you want see the data flowing through a task during a replay use 

```
kapacitor show -replay-id XXXX cpu
```

**Comment by juise** [comment]
Yep, enable task fix my problem, thanks!

But please, fix the doc, doc says about file /tmp/alerts.log that will appear and **enable** in different order:

> Check the log using the command below, did we get any alerts? The file should contain lines of JSON, where each line represents one alert. The JSON contains the alert level and the data that triggered the alert.
> cat /tmp/alerts.log
> Depending on how busy the server was, maybe not. Let’s modify the task to be really sensitive so that we know the alerts are working. Change the .crit(lambda: "usage_idle" < 70) line in the TICKscript to .crit(lambda: "usage_idle" < 100). Now every data point that was received during the recording will trigger an alert. Let’s replay it again and verify the results. Any time you want to update a task change the TICKscript and then run the define command again with just the TASK_NAME and -tick arguments:
> # edit threshold in cpu_alert.tick and redefine the task.
> kapacitor define cpu_alert -tick cpu_alert.tick
> kapacitor replay -recording $rid -task cpu_alert
> Now that we know it’s working, let’s change it back to a more reasonable threshold. Are you happy with the threshold? If so, let’s enable the task so it can start processing the live data stream with:
> kapacitor enable cpu_alert
> Now you can see alerts in the log in real time.
