### ISSUE TITLE
Replay Alert: Time of Value

### ISSUE THREAD

**Issue by sj14** [influxdata/kapacitor#1239]
Hi,
I'm recording data and replaying it to test my tick scripts. The alert log always shows the time, when the alert was triggered, but I also want to know the time of the value, which triggered the alarm.
According to [1], this should be possible with:

`.message('value time: {{ .Time }}')`

unfortunately, the result is the "alarm time". I have reproduced it by using the 'getting started' documentation [2]. Do I miss something?

Thanks in advance,
Simon

[1]  https://docs.influxdata.com/kapacitor/v1.2/nodes/alert_node/#message
[2] https://docs.influxdata.com/kapacitor/v1.2//introduction/getting_started/

**Comment by nathanielc** [comment]
@sj14 Can you share how you reproduced it and what you were expecting? The current code only exposes the time of the value, never the current time when the alert is triggered. Meaning we only track one time for the alert which is the timestamp of the value that triggered the alert. Since you and I are saying opposite things an example would help me understand specifically what you are expecting or where I am miss understanding.

**Comment by sj14** [comment]
Hi @nathanielc 
I am using OSX and the brew versions:

1. starting influxdb v1.2.0
```influxd``` 

2. Creating the telegraf.conf file:
```
[agent]
    interval = "1s"

[outputs]

# Configuration to send data to InfluxDB.
[outputs.influxdb]
    urls = ["http://localhost:8086"]
    database = "kapacitor_example"
    user_agent = "telegraf"

# Collect metrics about cpu usage
[cpu]
    percpu = false
    totalcpu = true
    drop = ["cpu_time"]
```

3. Starting telegraph version 1.2.0 with config file:
```
telegraf -config telegraf.conf
```

4. Check setup:
```
curl -G 'http://localhost:8086/query?db=kapacitor_example' --data-urlencode 'q=SELECT count(usage_idle) FROM cpu'
```

output:
```
{"results":[{"statement_id":0,"series":[{"name":"cpu","columns":["time","count"],"values":[["1970-01-01T00:00:00Z",30]]}]}]}
```
(the time here is already suspicious)


5. Create capacitor config file:
```
kapacitord config > kapacitor.conf
```

6. Start kapacitord version v1.2.0
```
kapacitord -config kapacitor.conf
```

7. Create cpu_alert.tick:
```
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
	.message('valuetime: {{ .Time }}')
        .crit(lambda: "usage_idle" <  70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')
```

8. Define task:
```
kapacitor define cpu_alert \
    -type stream \
    -tick cpu_alert.tick \
    -dbrp kapacitor_example.autogen
```

9. Record
```
kapacitor record stream -task cpu_alert -duration 20s
```

10. set recording id:
```
rid=944bce69-1399-499f-aa74-0161b97d66ef
```

11. check recording:
```
kapacitor list recordings $rid
```

output (correct time):
```
ID                                   Type    Status    Size      Date                   
944bce69-1399-499f-aa74-0161b97d66ef stream  finished  929 B     07 Mar 17 08:56 CET    
```

12. Stopping telegraf to not trigger alarms based on live data

13. Check time (date)
```
Di  7 Mär 2017 09:02:09 CET
```

14. Replay Recording:
```
kapacitor replay -recording $rid -task cpu_alert
```

15. Check Alarm.log:
only the first row:

```
{"id":"cpu:nil","message":"valuetime: 2017-03-07 08:02:23.076996208 +0000 UTC","details":"{\u0026#34;Name\u0026#34;:\u0026#34;cpu\u0026#34;,\u0026#34;TaskName\u0026#34;:\u0026#34;cpu_alert\u0026#34;,\u0026#34;Group\u0026#34;:\u0026#34;nil\u0026#34;,\u0026#34;Tags\u0026#34;:{\u0026#34;cpu\u0026#34;:\u0026#34;cpu-total\u0026#34;,\u0026#34;host\u0026#34;:\u0026#34;Simon-Air.fritz.box\u0026#34;},\u0026#34;ID\u0026#34;:\u0026#34;cpu:nil\u0026#34;,\u0026#34;Fields\u0026#34;:{\u0026#34;usage_guest\u0026#34;:0,\u0026#34;usage_guest_nice\u0026#34;:0,\u0026#34;usage_idle\u0026#34;:67.75818639798489,\u0026#34;usage_iowait\u0026#34;:0,\u0026#34;usage_irq\u0026#34;:0,\u0026#34;usage_nice\u0026#34;:0,\u0026#34;usage_softirq\u0026#34;:0,\u0026#34;usage_steal\u0026#34;:0,\u0026#34;usage_system\u0026#34;:19.395465994962215,\u0026#34;usage_user\u0026#34;:12.846347607052897},\u0026#34;Level\u0026#34;:\u0026#34;CRITICAL\u0026#34;,\u0026#34;Time\u0026#34;:\u0026#34;2017-03-07T08:02:23.076996208Z\u0026#34;,\u0026#34;Message\u0026#34;:\u0026#34;valuetime: 2017-03-07 08:02:23.076996208 \u0026#43;0000 UTC\u0026#34;}\n","time":"2017-03-07T08:02:23.076996208Z","duration":0,"level":"CRITICAL","data":{"Series":[{"name":"cpu","tags":{"cpu":"cpu-total","host":"Simon-Air.fritz.box"},"columns":["time","usage_guest","usage_guest_nice","usage_idle","usage_iowait","usage_irq","usage_nice","usage_softirq","usage_steal","usage_system","usage_user"],"values":[["2017-03-07T08:02:23.076996208Z",0,0,67.75818639798489,0,0,0,0,0,19.395465994962215,12.846347607052897]]}],"Messages":null,"Err":null}}
```

16. Problem:
expected:
original value timestamp should be at 8:56 maybe 8:57 CET (time of the recording)

output:
the time of the alert or the time of replaying the data, but not the original time of the value
```
valuetime: 2017-03-07 08:02:23.076996208 (UTC -> 9:02 CET)
```

Best regards,
Simon

**Comment by nathanielc** [comment]
@sj14 When you replay a recording there are two ways to treat the times in the recording.

1. Using the `-rec-time` flag which uses the times stored in the recording
2. The default behavior, which is to adjust times to be relative to when you started the replay, not recording.

Try using the `-rec-time` flag when replaying the data. That should do what you want.

**Comment by sj14** [comment]
Ah, ok. I have already found a workaround for myself by adding an own ID to track the value, but `-rec-time` should probably do the trick. Thank you.
