### ISSUE TITLE
deadman reports dead for a node which never reported before

### ISSUE THREAD

**Issue by Tgillon** [influxdata/kapacitor#1248]
Hi,
I want to report a node as dead only if it reported before and stopped reporting.
Currently I get alerts in hipchat  for a host which never reported to influxdb.
For me a node is considered as dead only if it reported before and stopped.
Is it possible?
Is it possible to do it using lambda expression?
below my script:
var data = stream
    |from()
        .measurement('cpuStats')
     |groupBy('host')
    |window()
        .period(1h)
        .every(1m)
    |mean('idle')
    |eval(lambda: 100.0 - "mean")
        .as('res')

data
   |deadman(0.0, 5m)
     .id('{{ .TaskName }}')
     .message('{{ .ID }} : for server {{ index .Tags "host" }} : {{ index .Fields "emitted" }}  points seen in last 5m')
     .stateChangesOnly()
     .hipChat()

data
   |deadman(0.0, 5m)
   |influxDBOut()
     .database('clusterStatus')
     .retentionPolicy('two_hours')
     .measurement('deadmanCpu')

**Comment by nhaugo** [comment]
Can you take this issue over to https://community.influxdata.com we try to keep github issues to bug reports and feature requests.
