### ISSUE TITLE
Improving VictorOps alerts

### ISSUE THREAD

**Issue by ggenot** [influxdata/kapacitor#1250]
Hello, 

I'm using Kapacitor with VictorOps alerting. It's working well but set of available data are quite limited.

In my model I need the hostname most of the time. It's an info I have in the tags in influx, that are available from kapacitor but not accessible in victorops as the data field is embedded json

A solution could be to send Data.Result as json object instead of json string in data fields

Victorops accept arbitrary json value and will automatically flatten the JSON of Data.Result

We have now 1 data field available: 

>data: {"Series":[{"name":"example","tags":{"host":"examplehost"},"columns":["time","duration","incoming","restransmit_0","restransmit_1","restransmit_16","restransmit_2","restransmit_4","restransmit_8"],"values":[["2017-03-07T23:47:58.287132323Z",0.038,0,20,0,17,0,0,0]]}],"Messages":null,"Err":null}

That will become

>data.series.0.name: example
>data.series.0.tags.host: examplehost
>data.series.0.columns.0: time
>data.series.0.columns.1: duration
>[...]

This way I can get the hostname from "data.series.0.tags.host" via transmogrifier transformation

Another solutions would be to be able to set arbitrary fields for victorOps but I don't think it's wanted

**Comment by hansgustavson** [comment]
+ 1

We are facing the same problem when using the Kapacitor/VictorOps integration.

**Comment by hansgustavson** [comment]
👍

Hans Gustavson | Sr. Director Cloud Operations | Coupa Software
<http://www.coupa.com> | hans.gustavson@coupa.com | 650.390.4396
