### ISSUE TITLE
hostname as FQDN

### ISSUE THREAD

**Issue by maddygoes** [influxdata/kapacitor#1253]
Please let me know, how to convert host tag to fqdn ?

Scenario -- below is my alert string and I wanna replace `<HOSTNAME>` to `<FQDN>` .. may be this is something I can hardcode in host tag. Please suggest me, how to change host tag / hard code host tag :

{"Date":"2017-03-03T10:13:46Z","Host":"`<HOSTNAME>`","Source":"Influx","SourceInstance":"Not Applicable","ObjectName":"disk_tea_status","InstanceName":"D:-`<HOSTNAME>` is WARNING  Current average Disk Utilization value past 15m  is: 93.7328541838882 
exceeds threshold of  90%  with Severity:2 )","CounterName":"mean","SampleValue":"93.7328541838882","KPI":"Not Applicable","ThresholdOperator":"Not Applicable","Average":"Not Applicable"}

**Comment by nathanielc** [comment]
I would recommend changing the source of the host tag. What are you using to collect the data? Telegraf? Change whatever system to use FQDN instead of just HOSTNAME from the start.

**Comment by maddygoes** [comment]
windows pass hostname only ...

**Comment by nathanielc** [comment]
OK, you can use https://docs.influxdata.com/kapacitor/v1.2/nodes/eval_node/#tags to map HOSTNAME to FQDN as a first step in your task.

**Comment by maddygoes** [comment]
Thanks @nathanielc
