### ISSUE TITLE
error while evaluating WHERE expression: no field or tag exists for role

### ISSUE THREAD

**Issue by osysee** [influxdata/kapacitor#1256]
Hi,

There's some issue about kapacitor tasks.
I would like to send mysql data from telegraf to kapacitor on stream.
This is an error messages from kapacitor.log

[check_slave_io:from1] 2017/03/13 11:52:08 E! error while evaluating WHERE expression: no field or tag exists for role

### Relevant telegraf.conf:
[global_tags]
role = "SLAVE"

### Relevant kapacitor.conf:
[[influxdb]]

enabled = false
default = false
name = "kapacitor"
urls = ["http://localhost:8086"]
username = ""
password = ""
timeout = 0
insecure-skip-verify = false
startup-timeout = "5m"
disable-subscriptions = true

### Kapacitor tick script below
var period = 10s
var every = 10s
var defaultValue = 0.0
var measurement = 'mysql'
var whereFilter = lambda: "role" == 'SLAVE'
var groups = ['host']
// Dataframe
var data = stream
|from()
.database(database)
.retentionPolicy(rp)
.measurement(measurement)
.where(whereFilter)
.groupBy(groups)
|window()
.period(period)
.every(every)
|default()
.field('slave_Slave_IO_Running', defaultValue)
|max('slave_Slave_IO_Running')
.as('value')
// Thresholds
var alert = data
|alert()
.crit(lambda: "value" != float(1))
.stateChangesOnly()
.log('/tmp/alert.log')

There's lots of error messages logged, but task is doing correctly.

Help me!!

Sorry for my english writing not well.

Thank you.

**Comment by nathanielc** [comment]
Your TICKscript uses this lambda expression `var whereFilter = lambda: "role" == 'SLAVE'`  but your data does not have the tag "role", as such the TICKscript is erroring out with the error message you posted.

**Comment by osysee** [comment]
I configured this on telegraf.
[global_tags]
role = "SLAVE"
and received data contains "role" tag.

please remind this issue.
thank you.
