### ISSUE TITLE
kapacitor don't make alerts

### ISSUE THREAD

**Issue by jcmartins** [influxdata/kapacitor#126]
Hi,
I'm using:
kapacitor 0.2.3-1
telegraf 0.3.0-beta2
Influxdb 0.9.6.1

**telegraf + Influxdb is OK!!!**

But kapacitor don't make alerts to me.

SHOW RETENTION POLICIES ON "telegraf"
name   duration replicaN default 
default     "0"        1          true

**cat /root/cpu_alert.tick**
stream 
 // Select just the cpu_usage_idle measurement from our example database. 
 .from().measurement('cpu') 
   .alert() 
     .crit(lambda: "usage_idle" < 98) 
     // Whenever we get an alert write it to a file. 
     .log('/tmp/alerts.log')

kapacitor define -name cpu_alert -type stream -dbrp telegraf.default -tick /root/cpu_alert.tick

kapacitor enable cpu_alert

**kapacitor list tasks**
Name        Type      Enabled   Executing Databases and Retention Policies 
cpu_alert   stream    true      true      ["telegraf"."default"]

PS: Kapacitor don't create the file alters.log in the /tmp   so I created it and make a chown but this file always empty
**ls -la /tmp/alerts.log**
-rw-r--r-- 1 kapacitor kapacitor 0 Dec 23 12:26 /tmp/alerts.log

**kapacitor show cpu_alert**
Name: cpu_alert 
Error:  
Type: stream 
Enabled: true 
Executing: true 
Databases Retention Policies: ["telegraf"."default"] 
TICKscript: 
stream 
 // Select just the cpu_usage_idle measurement from our example database. 
 .from().measurement('cpu') 
   .alert() 
     .crit(lambda: "usage_idle" < 98) 
     // Whenever we get an alert write it to a file. 
     .log('/tmp/alerts.log') 

DOT: 
digraph cpu_alert { 
stream0 -> stream1 [label="0"]; 
stream1 -> alert2 [label="0"]; 
}

**In the /var/log/kapacitor/kapacitor.log**
[httpd] 2015/12/23 12:35:43 I! 127.0.0.1 - - [23/Dec/2015:12:35:43 +0000] POST /api/v1/enable?name=cpu_alert HTTP/1.1 200 23 - Go-http-client/1.1 af292bea-a971-11e5-8003-000000000000 15.639924ms

tks
Joao

**Comment by rossmcdonald** [comment]
@jcmartins From your tickscript:

```
stream 
// Select just the cpu_usage_idle measurement from our example database. 
.from().measurement('cpu') 
...
```

Do you have a measurement named `cpu` in your database? Telegraf (at least by default) does not have a measurement named `cpu`, so you may need to change it to use the measurement name `cpu_usage_idle`. This would make it:

```
stream 
// Select just the cpu_usage_idle measurement from our example database. 
.from().measurement('cpu_usage_idle') 
.alert() 
.crit(lambda: "value" < 98) 
// Whenever we get an alert write it to a file. 
.log('/tmp/alerts.log')
```

Which means select `value` from `cpu_usage_idle`, and alert when it is below `98`.

**Comment by jcmartins** [comment]
SHOW MEASUREMENTS   (created by telegraf 0.3 beta 2)
**measurements**
name
cpu
disk
diskio
engine
httpd
icmp_inaddrmaskreps
icmp_inaddrmasks
icmp_incsumerrors
icmp_indestunreachs
icmp_inechoreps
icmp_inechos
icmp_inerrors
icmp_inmsgs
icmp_inparmprobs
icmp_inredirects
icmp_insrcquenchs
icmp_intimeexcds
icmp_intimestampreps
icmp_intimestamps
icmp_outaddrmaskreps
icmp_outaddrmasks
icmp_outdestunreachs
icmp_outechoreps
icmp_outechos
icmp_outerrors
icmp_outmsgs
icmp_outparmprobs
icmp_outredirects
icmp_outsrcquenchs
icmp_outtimeexcds
icmp_outtimestampreps
icmp_outtimestamps
icmpmsg_intype0
icmpmsg_intype3
icmpmsg_intype8
icmpmsg_outtype0
icmpmsg_outtype8
ip_defaultttl
ip_forwarding
ip_forwdatagrams
ip_fragcreates
ip_fragfails
ip_fragoks
ip_inaddrerrors
ip_indelivers
ip_indiscards
ip_inhdrerrors
ip_inreceives
ip_inunknownprotos
ip_outdiscards
ip_outnoroutes
ip_outrequests
ip_reasmfails
ip_reasmoks
ip_reasmreqds
ip_reasmtimeout
mem
net
netstat
ping
procstat
rabbitmq_node
rabbitmq_overview
shard
subscriber
system
tcp_activeopens
tcp_attemptfails
tcp_currestab
tcp_estabresets
tcp_incsumerrors
tcp_inerrs
tcp_insegs
tcp_maxconn
tcp_outrsts
tcp_outsegs
tcp_passiveopens
tcp_retranssegs
tcp_rtoalgorithm
tcp_rtomax
tcp_rtomin
trig
udp_incsumerrors
udp_indatagrams
udp_inerrors
udp_noports
udp_outdatagrams
udp_rcvbuferrors
udp_sndbuferrors
udplite_incsumerrors
udplite_indatagrams
udplite_inerrors
udplite_noports
udplite_outdatagrams
udplite_rcvbuferrors
udplite_sndbuferrors
wal
write

So I do 
**select * from cpu** 
cpu
time	cpu	dc	host	usage_guest	usage_guest_nice	usage_idle	usage_iowait	usage_irq	usage_nice	usage_softirq	usage_steal	usage_system	usage_user
2015-12-22T16:09:00Z	"cpu1"	"sa-east-1"	"server.sensu.ops.uat.sa-east-1"	0	0	98.4487072557719	0.05004170141802649	0	0	0	0	0.16680567139215738	1.334445371137259
2015-12-22T16:09:00Z	"cpu-total"	"sa-east-1"	"server.sensu.ops.uat.sa-east-1"	0	0	98.43150342074287	0.05840146837982401	0	0	0	0.008343066911454243	0.17520440514023083	1.3265476389157471
2015-12-22T16:09:00Z	"cpu0"	"sa-east-1"	"server.sensu.ops.uat.sa-east-1"	0	0	98.44715311376588	0.0667891133727952	0	0	0	0	0.1836700617797426	1.3023877108044344
2015-12-22T16:10:00Z	"cpu1"	"sa-east-1"	"server.sensu.ops.uat.sa-east-1"	0	0	99.38302484557197	0.08337502084377367	0	0

**Comment by rossmcdonald** [comment]
@jcmartins Sorry about that, I didn't realize the naming conventions had changed with Telegraf 0.3. I did a quick test using the TICKscript here (slightly modified version of yours):

```
root@kapacitor1:/tmp$ kapacitor list tasks
Name                          Type      Enabled   Executing Databases and Retention Policies
cpu_alert2                    stream    true      true      ["telegraf"."default"]

root@kapacitor1:/tmp# cat /vagrant/files/cpu_alert_telegraf_0.3.tick
stream
   // Select just the cpu_usage_idle measurement from our Telegraf database
   .from().measurement('cpu')
   .alert()
   .warn(lambda: "usage_idle" <  90)
   .crit(lambda: "usage_idle" <  80)
   // Whenever we get an alert write it to a file.
   .stateChangesOnly()
   .log('/tmp/cpu_idle_alerts.log')
```

And then generated some CPU utilization using the command:

```
while true; do i=0; done
```

Which produced the output:

```
root@kapacitor1:/tmp# cat cpu_idle_alerts.log
{"id":"cpu:nil","message":"cpu:nil is CRITICAL","time":"2015-12-30T13:50:40Z","level":"CRITICAL","data":{"series":[{"name":"cpu","tags":{"cpu":"cpu0","host":"kapacitor1"},"columns":["time","time_guest","time_guest_nice","time_idle","time_iowait","time_irq","time_nice","time_softirq","time_steal","time_system","time_user","usage_guest","usage_guest_nice","usage_idle","usage_iowait","usage_irq","usage_nice","usage_softirq","usage_steal","usage_system","usage_user"],"values":[["2015-12-30T13:50:40Z",0,0,427.79,0.26,0.02,1.97,0.87,0,7.8,27.73,0,0,23.946784922395004,0,0,0,0,0,0.11086474501108433,75.9423503325944]]}]}}
{"id":"cpu:nil","message":"cpu:nil is OK","time":"2015-12-30T13:51:00Z","level":"OK","data":{"series":[{"name":"cpu","tags":{"cpu":"cpu0","host":"kapacitor1"},"columns":["time","time_guest","time_guest_nice","time_idle","time_iowait","time_irq","time_nice","time_softirq","time_steal","time_system","time_user","usage_guest","usage_guest_nice","usage_idle","usage_iowait","usage_irq","usage_nice","usage_softirq","usage_steal","usage_system","usage_user"],"values":[["2015-12-30T13:51:00Z",0,0,444.05,0.26,0.02,1.97,0.87,0,7.87,30.94,0,0,99.39759036144576,0,0,0,0,0,0.40160642570281013,0.2008032128514006]]}]}}
```

If you enable debug logging, do you receive output when running the commands below?

```
kapacitor level debug
tailf /var/log/kapacitor/kapacitor.log | grep cpu_alert
```

If so, can you post about 20-40 lines? Also, what OS and version are you running?

**Comment by nathanielc** [comment]
@jcmartins This part of the show output list information about the flow of data through your task.

```
DOT: 
digraph cpu_alert { 
stream0 -> stream1 [label="0"]; 
stream1 -> alert2 [label="0"]; 
}
```

The `label` values indicate the number of points that have passed along that edge of the task graph. Since the first edge is `0` this show that Kapacitor is not receiving any data for the configured database and retention policy. How are you sending data to Kapacitor? Via subscriptions form InfluxDB? If so run `SHOW SUBSCRIPTIONS` and make sure that your network(firewall etc) allow the UDP traffic on the ports.

**Comment by jcmartins** [comment]
@nathanielc  It's all in the same machine.

**Comment by jcmartins** [comment]
@rossmcdonald 
Ross I do like y
root@server:~# kapacitor define -name cpu_alert2 -type stream -dbrp telegraf.default -tick /root/cpu_alert2.tick
root@server:~# kapacitor enable cpu_alert2
root@server:~# kapacitor list tasks
Name                          Type      Enabled   Executing Databases and Retention Policies
cpu_alert2                    stream    true      true      ["telegraf"."default"]
root@server:~# 
root@server:~# 
root@server:~# 
root@server:~# cat cpu_alert2.tick 
stream
  // Select just the cpu_usage_idle measurement from our example database.
  .from().measurement('cpu')
    .alert()
      .warn(lambda: "usage_idle" <  90)
      .crit(lambda: "usage_idle" <  80)
  // Whenever we get an alert write it to a file.
    .stateChangesOnly()
    .log('/tmp/alerts.log')
root@server:~# ls -la /tmp/alerts.log 
-rw-r--r-- 1 kapacitor kapacitor 0 Dec 23 12:26 /tmp/alerts.log

root@server:~# while true; do i=0; done
I have changes on kapacitor.log
tail -f kapacitor.log 
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! collect point c: 173 e: 173
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! collect point c: 174 e: 173
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! next point c: 175 e: 174
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! next point c: 175 e: 175
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! collect point c: 175 e: 175
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! collect point c: 176 e: 175
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! next point c: 177 e: 176
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! next point c: 177 e: 177
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! collect point c: 177 e: 177
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:13 D! next point c: 178 e: 178
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! collect point c: 178 e: 178
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! collect point c: 179 e: 178
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! next point c: 180 e: 179
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! next point c: 180 e: 180
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! collect point c: 180 e: 180
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! collect point c: 181 e: 180
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! next point c: 182 e: 181
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! next point c: 182 e: 182
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! collect point c: 182 e: 182
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! collect point c: 183 e: 182
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! next point c: 184 e: 183
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! next point c: 184 e: 184
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! collect point c: 184 e: 184
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:23 D! next point c: 185 e: 185
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! collect point c: 185 e: 185
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! collect point c: 186 e: 185
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! next point c: 187 e: 186
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! next point c: 187 e: 187
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! collect point c: 187 e: 187
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! collect point c: 188 e: 187
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! next point c: 189 e: 188
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! next point c: 189 e: 189
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! collect point c: 189 e: 189
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! collect point c: 190 e: 189
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! next point c: 191 e: 190
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! next point c: 191 e: 191
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! collect point c: 191 e: 191
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:33 D! next point c: 192 e: 192
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! collect point c: 192 e: 192
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! collect point c: 193 e: 192
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! next point c: 194 e: 193
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! next point c: 194 e: 194
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! collect point c: 194 e: 194
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! collect point c: 195 e: 194
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! next point c: 196 e: 195
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! next point c: 196 e: 196
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! collect point c: 196 e: 196
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! collect point c: 197 e: 196
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! next point c: 198 e: 197
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! next point c: 198 e: 198
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! collect point c: 198 e: 198
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:45:43 D! next point c: 199 e: 199

**but any writes on /tmp/alerts.log**

My kapacitor hostname is localhost      (kapacitor+influx+telegraf it's all in the same machine)

**Comment by nathanielc** [comment]
@jcmartins Can you post the log from when Kapacitor first starts up? Everything between the line `Kapacitor starting` and `Listening for signals`.

You should see two lines like:

```
[udp:telegraf.default] 2016/01/04 10:10:20 I! Started listening on UDP: [::]:41541
[influxdb] 2016/01/04 10:10:20 I! started UDP listener for telegraf default
```

**Comment by jcmartins** [comment]
**cat kapacitor.log**
[run] 2016/01/04 12:39:03 I! Kapacitor starting, version 0.2.3, branch master, commit 7ea4a548108e82a214d6c7a94b66a59ffeda1bd9
[run] 2016/01/04 12:39:03 I! Go version go1.5.1, GOMAXPROCS set to 2
[srv] 2016/01/04 12:39:03 I! Kapacitor hostname: localhost
[task_master] 2016/01/04 12:39:03 I! opened
[srv] 2016/01/04 12:39:03 I! ClusterID: 5a45d3a9-b3fe-42d3-873b-eafd01385df7 ServerID: 87368ff5-d75b-44e5-94d5-16186ed9bade
[srv] 2016/01/04 12:39:03 D! opening service: *httpd.Service
[httpd] 2016/01/04 12:39:03 I! Starting HTTP service
[httpd] 2016/01/04 12:39:03 I! Authentication enabled: false
[httpd] 2016/01/04 12:39:03 I! Listening on HTTP: [::]:9092
[srv] 2016/01/04 12:39:03 D! opened service: *httpd.Service
[srv] 2016/01/04 12:39:03 D! opening service: *influxdb.Service
[edge:TASK_MASTER|write_points->stream] 2016/01/04 12:39:03 D! next point c: 0 e: 0
[srv] 2016/01/04 12:39:03 D! opened service: *influxdb.Service
[srv] 2016/01/04 12:39:03 D! opening service: *task_store.Service
[srv] 2016/01/04 12:39:03 D! opened service: *task_store.Service
[srv] 2016/01/04 12:39:03 D! opening service: *replay.Service
[srv] 2016/01/04 12:39:03 D! opened service: *replay.Service
[srv] 2016/01/04 12:39:03 D! opening service: *stats.Service
[stats] 2016/01/04 12:39:03 I! opened service
[srv] 2016/01/04 12:39:03 D! opened service: *stats.Service
[srv] 2016/01/04 12:39:03 D! opening service: *reporting.Service
[edge:TASK_MASTER|stats->stream] 2016/01/04 12:39:03 D! next point c: 0 e: 0
[srv] 2016/01/04 12:39:03 D! opened service: *reporting.Service
[run] 2016/01/04 12:39:03 I! Listening for signals

**netstat -na |more**
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:36582         127.0.0.1:15672         ESTABLISHED
tcp        0      0 127.0.0.1:47805         127.0.0.1:8086          ESTABLISHED
tcp        0      0 127.0.0.1:15672         127.0.0.1:36585         ESTABLISHED
tcp        0      0 127.0.0.1:36580         127.0.0.1:15672         TIME_WAIT  
tcp        0      0 127.0.0.1:38525         127.0.0.1:4369          ESTABLISHED
tcp        0      0 127.0.0.1:47800         127.0.0.1:8086          ESTABLISHED
tcp        0      0 127.0.0.1:36585         127.0.0.1:15672         ESTABLISHED
tcp        0      0 127.0.0.1:15672         127.0.0.1:36582         ESTABLISHED
tcp6       0      0 :::8086                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::8088                 :::*                    LISTEN     
**tcp6       0      0 :::9092                 :::*                    LISTEN     **
tcp6       0      0 :::5672                 :::*                    LISTEN     
tcp6       0      0 :::8080                 :::*                    LISTEN     
tcp6       0      0 :::4369                 :::*                    LISTEN     
tcp6       0      0 :::8083                 :::*                    LISTEN     
tcp6       0      0 127.0.0.1:8086          127.0.0.1:47800         ESTABLISHED
tcp6       0      0 127.0.0.1:4369          127.0.0.1:38525         ESTABLISHED
tcp6       0      0 127.0.0.1:8086          127.0.0.1:47805         ESTABLISHED
tcp6       0      0 127.0.0.1:4369          127.0.0.1:57221         TIME_WAIT  
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
udp        0      0 10.0.225.143:123        0.0.0.0:*                          
udp        0      0 127.0.0.1:123           0.0.0.0:*                          
udp        0      0 0.0.0.0:123             0.0.0.0:*                          
udp        0      0 0.0.0.0:59432           0.0.0.0:*                          
udp6       0      0 fe80::8a2:14ff:feed:123 :::*                               
udp6       0      0 ::1:123                 :::*                               
udp6       0      0 :::123                  :::*                               
udp6       0      0 :::33429                :::*

**Comment by nathanielc** [comment]
I don't see any subscriptions in the startup log. Can you share your kapacitor config? And the output of `SHOW SUBSCRIPTIONS` on the influxdb host?

**Comment by jcmartins** [comment]
root@server:~# cat /etc/kapacitor/kapacitor.conf                                                                                                                                                                  
# The hostname of this node.                                                                                                                                                                                      
# Must be resolvable by any configured InfluxDB hosts.                                                                                                                                                            
hostname = "localhost"                                                                                                                                                                                            
# Directory for storing a small amount of metadata about the server.                                                                                                                                              
data_dir = "/var/lib/kapacitor"                                                                                                                                                                                   
                                                                                                                                                                                                                  
[http]                                                                                                                                                                                                            
  # HTTP API Server for Kapacitor                                                                                                                                                                                 
  # This server is always on,                                                                                                                                                                                     
  # it servers both as a write endpoint                                                                                                                                                                           
  # and as the API endpoint for all other                                                                                                                                                                         
  # Kapacitor calls.                                                                                                                                                                                              
  bind-address = ":9092"                                                                                                                                                                                          
  auth-enabled = false                                                                                                                                                                                            
  log-enabled = true                                                                                                                                                                                              
  write-tracing = false                                                                                                                                                                                           
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"

[logging]
    # Destination for logs
    # Can be a path to a file or 'STDOUT', 'STDERR'.
    file = "/var/log/kapacitor/kapacitor.log"
    # Logging level can be one of:
    # DEBUG, INFO, WARN, ERROR, or OFF
    level = "DEBUG"

[replay]
  # Where to store replay files, aka recordings.
  dir = "/var/lib/kapacitor/replay"

[task]
  # Where to store the tasks database
  dir = "/var/lib/kapacitor/tasks"

[influxdb]
  # Connect to an InfluxDB cluster
  # Kapacitor can subscribe, query and write to this cluster.
  # Using InfluxDB is not required and can be disabled.
  enabled = true
  urls = ["http://localhost:8086"]
  username = "root"
  password = "root"
  timeout = 0
  # Subscriptions use the UDP network protocl.
  # The following options of for the created UDP listeners for each subscription.
  # Number of packets to buffer when reading packets off the socket.
  udp-buffer = 1000
  # The size in bytes of the OS read buffer for the UDP socket.
  # A value of 0 indicates use the OS default.
  udp-read-buffer = 0

  [influxdb.subscriptions]
    # Set of databases and retention policies to subscribe to.
    # If empty will subscribe to all, minus the list in
    # influxdb.excluded-subscriptions
    #
    # Format
    # db_name = <list of retention policies>
    #
    # Example:
    # my_database = [ "default", "longterm" ]
    my_database = [ "telegraf", "default" ]
  [influxdb.excluded-subscriptions]
    # Set of databases and retention policies to exclude from the subscriptions.
    # If influxdb.subscriptions is empty it will subscribe to all
    # except databases listed here.
    #
    # Format
    # db_name = <list of retention policies>
    #
    # Example:
    # my_database = [ "default", "longterm" ]

[smtp]
  # Configure an SMTP email server
  # Will use TLS and authentication if possible
  # Only necessary for sending emails from alerts.
  enabled = false
  host = "localhost"
  port = 25
  username = ""
  password = ""
  # From address for outgoing mail
  from = ""
  # List of default To addresses.
  # to = ["oncall@example.com"]

  # Skip TLS certificate verify when connecting to SMTP server
  no-verify = false
  # Close idle connections after timeout
  idle-timeout = "30s"

[victorops]
  # Configure VictorOps with your API key and default routing key.
  enabled = false
  # Your VictorOps API Key.
  api-key = ""
  # Default VictorOps routing key, can be overridden per alert.
  routing-key = ""
  # The VictorOps API URL should not need to be changed.
  url = "https://alert.victorops.com/integrations/generic/20131114/alert"
  # If true the all alerts will be sent to VictorOps
  # without explicity marking them in the TICKscript.
  # The routing key can still be overridden.
  global = false

[pagerduty]
  # Configure PagerDuty.
  enabled = false
  # Your PagerDuty Service Key.
  service-key = ""
  # The PagerDuty API URL should not need to be changed.
  url = "https://events.pagerduty.com/generic/2010-04-15/create_event.json"
  # If true the all alerts will be sent to PagerDuty
  # without explicity marking them in the TICKscript.
  global = false

[slack]
  # Configure Slack.
  enabled = false
  # The Slack webhook URL, can be obtained by addding
  # an Incoming Webhook integration.
  # Visit https://slack.com/services/new/incoming-webhook
  # to add new webhook for Kapacitor.
  url = ""
  # Default channel for messages
  channel = ""
  # If true the all alerts will be sent to Slack
  # without explicity marking them in the TICKscript.
  global = false


[reporting]
  # Send anonymous usage statistics
  # every 12 hours to Enterprise.
  enabled = true
  url = "https://usage.influxdata.com"

##################################
# Input Methods, same as InfluxDB
#

[collectd]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "10s"
  typesdb = "/usr/share/collectd/types.db"

[opentsdb]
  enabled = false
  bind-address = ":4242"
  database = "opentsdb"
  retention-policy = ""
  consistency-level = "one"
  tls-enabled = false
  certificate = "/etc/ssl/influxdb.pem"
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"
root@server:~# 

**SHOW SUBSCRIPTIONS;**
Success! (no results to display)

**Comment by nathanielc** [comment]
@jcmartins This line in the configuration is the problem. 

```
my_database = [ "telegraf", "default" ]
```

You are telling Kapacitor to listen for data from the `my_database` in InfluxDB, but want you really want is to subscribe to the data in the `telegraf` database.

Change the line to this or just remove it and Kapacitor should start getting data:

```
telegraf = [ "default" ]
```

You can confirm that it work by running `SHOW SUBSCRIPTIONS` again and see something about telegraf and Kapacitor.

Running `kapacitor show cpu_alert` should also show that the task is receiving data, the `DOT` section should have non-zero values for the labels. For example the zeros below should be replaced with a number indicating the number of points the task has processed.

```
DOT: 
digraph cpu_alert { 
stream0 -> stream1 [label="0"]; 
stream1 -> alert2 [label="0"]; 
}
```

**Comment by jcmartins** [comment]
**SHOW SUBSCRIPTIONS**
telegraf
**retention_policy	name	mode	destinations**
default	"kapacitor"	"ANY"	udp://localhost:50749

**kapacitor show cpu_alert**
Name: cpu_alert
Error: 
Type: stream
Enabled: true
Executing: true
Databases Retention Policies: ["telegraf"."default"]
TICKscript:
stream
  // Select just the cpu_usage_idle measurement from our example database.
  .from().measurement('cpu')
    .alert()
      .crit(lambda: "usage_idle" < 98)
      // Whenever we get an alert write it to a file.
      .log('/tmp/alerts.log')


DOT:
digraph cpu_alert {
stream0 -> stream1 [label="978"];
stream1 -> alert2 [label="18"];
}

tks a lot of!!!

**Comment by jait-23** [comment]
// **cod_alert.tick**
stream
   |from()
   .measurement('cod')
   |alert()
   .crit(lambda: "reading" > 87)
   .log('/tmp/cod_alert.log')

// **kapacitor.conf**
 [influxdb.subscriptions]
    # Set of databases and retention policies to subscribe to.
    # If empty will subscribe to all, minus the list in
    # influxdb.excluded-subscriptions
    #
    # Format
    # db_name = <list of retention policies>
    #
    # Example:
    # my_database = [ "default", "longterm" ]
    kerneltest = [ "autogen", "default" ]

commands to execute and run:
1) kapacitor define cod_alert -type stream -dbrp kerneltest.autogen -tick /cod_alert.tick
2) kapacitor lists tasks
3) kapacitor enable cod_alert

Next, I am searching the log file in the /tmp/cod_alert.log, but unable to generate it.
Strange thing is I am able to generate the log file for telegraf database for the cpu-usage tick-script Kindly help me out!!! Thanks.

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
