### ISSUE TITLE
Help needed on logical operation.

### ISSUE THREAD

**Issue by SamuelToh** [influxdata/kapacitor#1265]
Hi there,

Just a fundamental problem which I am trying to solve.

Does Kapacitor's tick script has the capability to do logical operation?

E.g. 

```
var my_sum = batch
  |query(
     '''
     SELECT sum(value)
       FROM "database_abc"."autogen".measurementYYY 
      WHERE tag1 = 'helloWorld'    OR
            tag1 = 'hello999' 
     ''')
      .period(1s)
      .every(1s)


If (my_sum.sum > 500) {
    // do this
}
else {
    // do that
}
```

Is the latter bit of logic possible in tick script yet? I do notice there is 'if' support for the Eval operation, trouble is I don't think that can solve the problem above.

Any help will be greatly appreciated.

**Comment by m4ce** [comment]
@SamuelToh, what exactly are you trying to accomplish in `// do this` and `// do that`?

If you can explain what you are trying to achieve, it will be easier to help out.

**Comment by SamuelToh** [comment]
@m4ce thanks for getting back to me. *Note: I have already figured out a solution to my problem, probably not elegant enough but I am happy to discuss for a better solution.

To simplify what I was doing earlier on, I have a measurement called "Electricity".
In the measurement there are let say 2 rows;

1. {Field: [ { Value = 10 }, { time = 2017-03-17T14:15:06Z } ] tag: [ { Id = "Generator1", SumOfAbove20" = '' } ]

2. {Field: [ { Value = 15 }, { time = 2017-03-17T14:15:06Z } ] tag: [ { Id = "Generator2", SumOfAbove20" = '' } ]

So I was trying to do a sum of the 2 rows;
Filtering based on => **WHERE** Id = 'Generator1' **OR** Id = 'Generator2' **AND** Time = 2017-03-17T14:15:06Z"

If the sumOf both rows is above 20 then I would like to update the tag 'SumOfAbove20' for both row to have value = 'true' else 'false'. Which is what motivated me into researching whether it is possible for us to do logical operation like if-else in tick script.


It seems like I don't need the logical operation to achieve what I was doing. 
I solve it by using a combination of '|join()' and '|lambda()' Here is what I had;

**Note** All information provided (+ the tick script) are pseudo data and script so they may not compile but the idea is there.

```
var sum = batch
  |query(
     '''
     SELECT sum(value)
       FROM "databaseName"."autogen".elecPower 
      WHERE id = 'Generator1' OR
            id = 'Generator2' 
     ''')
      .period(1s)
      .every(1s)
      .groupBy(time(1s))

var generator1 = batch
  |query(
     '''
     SELECT *
       FROM "databaseName"."autogen".elecPower 
      WHERE id = 'Generator1' 
     ''')
      .period(1s)
      .every(1s)
      .groupBy(time(1s))

sum
    |join(generator1)
      .as('a', 'b')
    |eval(lambda: if ("a.sum" >= 20, 'true', 'false'))
       .as('SumOfAbove20')
       .tags('SumOfAbove20')
       .keep('b.value')
    |influxDBOut()
       .database('databaseName')
       .retentionPolicy('autogen')
       .precision('ms')
       .measurement('electricity')
       .tag('id', 'Generator1')

// Then also do the same for Data Generator2 (Basically a copy paste from the paragraph of code above

```
Any ideas on how I could do it better will be greatly appreciated.

Also I'm happy to close this issue.

**Comment by nhaugo** [comment]
@SamuelToh this is probably the best way to solve the issue in TICK script. I am closing the issue for now.
