### ISSUE TITLE
Help with Deadman

### ISSUE THREAD

**Issue by mbarragan** [influxdata/kapacitor#1267]
Hi,

I would to create an alert that triggers an event if there have not been any point during the last hour but during the previows hour there had been at least one point.

For example:

Between the 4 - 5 pm the tag "client" == 'myself' has 3 points, but between 5 - 6 pm there is no points for 'myself'. It should trigger an alert for any possible client with points in the previows hour.

Is it possible?

Thanks and best regards,
Marcos.

**Comment by nathanielc** [comment]
Have you seen the deadman node https://docs.influxdata.com/kapacitor/v1.2/nodes/stream_node/#deadman ?

**Comment by mbarragan** [comment]
Yes, I've seen that documentation. I think that I understand how deadman works... I've implemented an example for a specific value of a specific tag and it works fine. But it is not what I want.

I want something like:

```
var data = stream
	|from()
		.database('database_example')
		.retentionPolicy('policy_example')
		.measurement('measurement_example')
		.groupBy('tag1','tag2')

data
	|deadman(1.0, 10s)
		.stateChangesOnly(1h)
		.slack()
		.channel('#example_channel')
		.iconEmoji(':scream:')
		.username('Kapacitor - No Traffic')
		.message('NO TRAFFIC DETECTED {{ .Level }} {{ index .Tags "tag1" }} - {{ index .Tags "tag1" }}')
```

The problem here is that if for a specific tag1 and tag2 there are no points in the last hour but there are points in the previous hour, there will not be any alert for that points.

How can I get an alert for the the tags that have stopped to write points?

**Comment by nhaugo** [comment]
Hi @mbarragan can you take general questions to https://community.influxdata.com we try to keep github issues to bug reports and feature requests.
