### ISSUE TITLE
InfluxQLNode documentation needs improvement

### ISSUE THREAD

**Issue by SamuelToh** [influxdata/kapacitor#1268]
Hi,

I reading through the Kapacitor documentation and I think the influxQL node section isn't very clear.

For instance the example doesn't seem relevant to the topic.
   ```
 stream
        |window()
            .period(10s)
            .every(10s)
        // Sum the values for each 10s window of data.
        |sum('value')
```

Note the "|InfluxQLNode(...)" isn't there... At the moment, newbies like me will have to guess the arguments for the node.Probably a copy paste error as InfluxQLNode doesn't support the .period and .every.
properties. 

Also, since it doesn't support the period property I suppose there is no way we can take advantage of the stateful information we get from the typical |Query(...)? That is, we need to know ahead in time what we want to SELECT and build the query?

Thanks!
Sam

**Comment by nhaugo** [comment]
Hi @SamuelToh I think there is a bit of misunderstanding on how this works. This probably means that we need to update the documentation a bit. Would you mind taking this to https://community.influxdata.com for further discussion. We try to keep github issues to bugs and feature requests.

**Comment by SamuelToh** [comment]
@nhaugo  will do thanks.
