### ISSUE TITLE
Alert on event count

### ISSUE THREAD

**Issue by kigakree** [influxdata/kapacitor#127]
I have measurements like
```
response host=web1 status=ok value=50 
response host=web1 status=ok value=60 
response host=web1 status=ok value=55 
response host=web1 status=ok value=50 
response host=web1 status=error value=100
response host=web1 status=ok value=60 
```
Is there any way to count them by status and alert if error occurs 10 times in a row?
In pseudocode it would be something like this:
```
counter = 0

if status == error
  counter += 1
else
  counter = 0
end

if counter > 10 
  alert()
```

**Comment by nathanielc** [comment]
This is not easily archived with current functionality. Some things you can do are to window the data for a period of time and then count the total occurrences of each state. Then you could compare their ratios for that window to a threshold. Not exactly what you wanted but close. 

This could be achieved if the eval lambda expressions had conditional logic, but currently they do not. Not exactly sure what that would look like in a TICKscript either. Any ideas?

**Comment by MartinSbs** [comment]
Is it possible now to do like Kigakree would like or it's still not available with the current functionality?

**Comment by nathanielc** [comment]
@MartinSbs It is possible if you write a UDF to implement the custom logic. It is not possible with a pure TICKscript implementation.
