### ISSUE TITLE
Add measurement tag to InfluxDBOut node

### ISSUE THREAD

**Issue by abadyan-vonage** [influxdata/kapacitor#1279]
I'm using kapacitor 1.2.

I'm trying to select from all measurements in my db, do some processing and then output back to influxdb. Is there a way to add a tag as to which measurement the data came from? Using groupByMeasurement only adds it to group id, but no tag is created.

**Comment by nathanielc** [comment]
See https://docs.influxdata.com/kapacitor/v1.2/nodes/influx_d_b_out_node/#tag

**Comment by abadyan-vonage** [comment]
@nathanielc This method only adds a static tag. I am selecting from all measurements in the db so that will not do the trick.
I ended up adding a special tag to all the measurements (addToSpecialCalculation=true) and using that to differentiate.
