### ISSUE TITLE
SMTP email out does not work

### ISSUE THREAD

**Issue by iotp** [influxdata/kapacitor#128]
I tested this with gomail as stand alone and it works. I am also seeing alerts being generated at alerts.log, so I am pressed to believe that this is a bug. I am testing it with the fake SMTP server listening on port 2225.

the go code that works:
m := gomail.NewMessage()
m.SetHeader("From", "a@example.com")
m.SetHeader("To", "b@example.com")
m.SetHeader("Subject", "Hello!")
m.SetBody("text/html", "Hello!")

d := gomail.NewPlainDialer("localhost", 2225, "", "")

// Send the email to Bob, Cora and Dan.
if err := d.DialAndSend(m); err != nil {
    panic(err)
}

And here is my SMTP setting in kapacitor:
[smtp]
  enabled = true
  host = "localhost"
  port = 2225
  username = ""
  password = ""
  no-verify = true
  global = false
  from = "test@test.com"
  to = ["alert@alert.com"]
  idle-timeout = "300s"

**Comment by nathanielc** [comment]
Are there any errors in the logs? Can you share your TICKscript that can reproduce the behavior? I can verify it works for simple cases on my machine but you are not the first to report issues with SMTP alerts. Any details you can give will be very beneficial.

**Comment by iotp** [comment]
Mine is a very simple case as well.
TICKscript:
stream
    .from().measurement('entropy_entropy')
    .alert()
        .crit(lambda: "value" <  800)
        .email()
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

I define it as: kapacitor define     -name press_alert     -type stream     -tick press_alert.tick     -dbrp metrics.default
And enable as: kapacitor enable press_alert

And my alert log snippet shows:
{"id":"entropy_entropy:nil","message":"entropy_entropy:nil is OK","time":"2015-12-30T07:19:57Z","level":"OK","data":{"series":[{"name":"entropy_entropy","tags":{"host":"host"},"columns":["time","value"],"values":[["2015-12-30T07:19:57Z",823]]}]}}
{"id":"entropy_entropy:nil","message":"entropy_entropy:nil is CRITICAL","time":"2015-12-30T07:21:27Z","level":"CRITICAL","data":{"series":[{"name":"entropy_entropy","tags":{"host":"host"},"columns":["time","value"],"values":[["2015-12-30T07:21:27Z",717]]}]}}
{"id":"entropy_entropy:nil","message":"entropy_entropy:nil is CRITICAL","time":"2015-12-30T07:21:37Z","level":"CRITICAL","data":{"series":[{"name":"entropy_entropy","tags":{"host":"host"},"columns":["time","value"],"values":[["2015-12-30T07:21:37Z",748]]}]}}
{"id":"entropy_entropy:nil","message":"entropy_entropy:nil is OK","time":"2015-12-30T07:21:47Z","level":"OK","data":{"series":[{"name":"entropy_entropy","tags":{"host":"host"},"columns":["time","value"],"values":[["2015-12-30T07:21:47Z",805]]}]}}

It doesn't seem to log any errors at debug or at info level. If I were to disable the SMTP at the kapacitor settings, it would log an error saying I need to enable it. Once I enable, it acts like everything is working good.

Please let me know what other information I can provide, Thanks!
