### ISSUE TITLE
Docker ENV config for SMTP TO value

### ISSUE THREAD

**Issue by rudijs** [influxdata/kapacitor#1280]
Hi,

Is it possible to configure the alert SMTP to with an environment variable?

So far I've not been able to.

I'm using the official docker image 1.2.0-alpine from https://hub.docker.com/_/kapacitor/

This is a sample of the kapacitor.conf file generated, which I use for reference:

```
[smtp]
  enabled = false
  host = "localhost"
  port = 25
  username = ""
  password = ""
  no-verify = false
  global = false
  state-changes-only = false
  from = ""
  idle-timeout = "30s"
```  

From these config options I'm able to set all I require with one exception:

Examples (substituted email address):

```
KAPACITOR_SMTP_ENABLED=true
KAPACITOR_SMTP_HOST=10.144.65.38
KAPACITOR_SMTP_FROM=alerts@example.com
KAPACITOR_SMTP_GLOBAL=true
KAPACITOR_SMTP_STATE_CHANGES_ONLY=true
```

From the docs at https://docs.influxdata.com/kapacitor/v1.2/nodes/alert_node/#email

I should be able to set a global smtp to config.

```
[smtp]
  to = ["oncall@example.com"]
```

```
Define the To addresses for the email alert. 
Multiple calls append to the existing list of addresses. 
If empty uses the addresses from the configuration.
```
I've tried all these without success (substituted email address):

1. KAPACITOR_SMTP_TO_0=alerts@exmple.com
2. KAPACITOR_SMTP_TO=alerts@exmple.com
3. KAPACITOR_SMTP_TO=["alerts@exmple.com"]

However I always see this in the kapacitor logs:

    not sending email, no recipients defined

The only way I'm able to send email is to configure the smtp.to config within the tickscript (example):

```
batch
  |query('SELECT count("value") FROM "riemann"."autogen".api_http_status')
  .period(5m)
  .every(5m)
    |deadman(0.0, 5m)
    .log('/tmp/alerts.log')
    .email().to('alerts@example.com')
```

So with this it works, but I'd prefer a single global smtp.to setting - if possible.

I think I'm using the tool correctly, if not any tips or advise?

Much appreciated,

Thanks.

**Comment by nhaugo** [comment]
Hi @rudijs,
Can you move this question to https://community.influxdata.com we try to limit github to bugs and feature requests.

Thanks

**Comment by sofuture** [comment]
@rudijs Did you find a solution to this? It seems like a bug unless there's some really magical thing we're both missing.

**Comment by sofuture** [comment]
I opened a discussion here https://community.influxdata.com/t/unable-to-set-smtp-to-via-environment-variable/917/1 for anyone that comes across this

**Comment by rudijs** [comment]
@sofuture Hey Jeff, I'm still using the configuration I pasted earlier in this thread - so no solution as yet.

**Comment by sofuture** [comment]
@rudijs Hey Rudi, I figured out the cause of this is #1344 . You can workaround by defining dummy values in config *file*, and then they override correctly via env variables. I'm halfway through putting together a fix for it, but that workaround will work for now!

**Comment by rudijs** [comment]
@sofuture Nice find, right on :-)

**Comment by mcfedr** [comment]
As i understand this is still not fixed? I just went though the same process of trying all combinations I could think of for SMTP_TO

**Comment by CMoH** [comment]
Same here. Seems it was not fixed, which kindof makes the library/kapacitor docker image useless as is for email alerts. I've decided to work around this by creating a docker image that handles this issue, but then... why stop here and not generate the entire configuration file?
