### ISSUE TITLE
[smtp] Using remote SMTP may require to define a hostname instead of localhost

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/kapacitor#1282]
Hi,

I have TICK (latest versions) installed on a server. I send mail over another one and I got this:

```
Mar 28 13:56:00 co-front3-deb8 postfix/smtpd[32358]: connect from xvm-168-114.dc0.ghst.net[95.142.168.114]
Mar 28 13:56:00 co-front3-deb8 postfix/smtpd[32358]: NOQUEUE: reject: RCPT from xvm-168-114.dc0.ghst.net[95.142.168.114]: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname; from=<noreply@compta-online.com> to=<contact@cerenit.fr> proto=ESMTP helo=<localhost>
```
To be clear:
* 95.142.168.114 is the host on which TICK is running
* co-front3-deb8 is my SMTP server

On the target SMTP server, I do greylisting and a few other checks like being sent with a FQDN.

Is there a way to know from where the script which sends the mail get the "host" and a way to update it ?

I tried to:
* Set `hostname` to my monitoring domaine name in kapacitor.conf and no effects,
* Change ssmtp rules (if used) to override domain : no effect
* Pass hostname at reverse proxy level in case it was inherited from here : no effect.
* Look at API in `/kapacitor/v1/config` and found nothing related to hostname

I can setup a new postfix as relay on this server but not sure it would change anything.

I define alerts through chronograf - if it can have side impacts on kapacitor conf.

Thanks,
Nicolas

**Comment by nsteinmetz** [comment]
FYI, just dropped `ssmtp` in favor of `postfix` and use `localhost` on TICK side for SMTP setup and it works fine.

**Comment by nathanielc** [comment]
@nsteinmetz You can set the SMTP host you connect to via the `[smtp] host` config option like:

```
[smtp]
   host = "co-front3-deb8"
   # Other SMTP config ...
```

**Comment by nsteinmetz** [comment]
Hi, 

Thanks, will try this on another server then. Thanks! 

Have a nice day, 
Nicolas
