### ISSUE TITLE
kapacitor udf keepalive timeout

### ISSUE THREAD

**Issue by alparslanuysal** [influxdata/kapacitor#1287]
Hi folks,Anomaly tasks are terminated immediately after its starts. I think kapacitor does not get points. I could not find any solution.

Kapacitor version :1.1.1
OS : Ubuntu 16.04
Kapacitor Logs:

[task_store] 2017/03/31 15:03:33 E! task m67_temp_anomaly finished with error: tTest3: keepalive timedout, last keepalive received was: 2017-03-31 15:03:23.294728348 +0300 +03
[crane1_accx_anomaly:tTest3] 2017/03/31 15:03:33 I!P Starting agent for TTestHandler
[crane1_accx_anomaly:tTest3] 2017/03/31 15:03:33 I!P MOvingStats init method
[crane1_accx_anomaly:tTest3] 2017/03/31 15:03:33 I!P Init method
[crane1_accx_anomaly:tTest3] 2017/03/31 15:03:33 I!P Agent finished
[m76_accx_anomaly:tTest3] 2017/03/31 15:03:33 E! keepalive timedout, last keepalive received was: 2017-03-31 15:03:23.728088951 +0300 +03
[edge:m76_accx_anomaly|window2->tTest3] 2017/03/31 15:03:33 I! aborting c: 0 e: 0
[m76_accx_anomaly:tTest3] 2017/03/31 15:03:33 E! keepalive timedout, last keepalive received was: 2017-03-31 15:03:23.728088951 +0300 +03
[task_master:main] 2017/03/31 15:03:33 E! Stopped task: m76_accx_anomaly tTest3: keepalive timedout, last keepalive received was: 2017-03-31 15:03:23.728088951 +0300 +03

Influxdb Logs:

[httpd] 127.0.0.1 - - [31/Mar/2017:16:00:35 +0300] "POST /write?db=scatto HTTP/1.1" 204 0 "-" "Python-urllib/2.7" 07dd72ba-1612-11e7-8029-000000000000 5510
[subscriber] 2017/03/31 16:00:36 Post http://localhost:9092/write?consistency=&db=scatto&precision=ns&rp=autogen: dial tcp 127.0.0.1:9092: getsockopt: connection refused
[httpd] 127.0.0.1 - - [31/Mar/2017:16:00:36 +0300] "POST /write?db=scatto HTTP/1.1" 204 0 "-" "Python-urllib/2.7" 082d8cee-1612-11e7-802a-000000000000 4250
[subscriber] 2017/03/31 16:00:40 Post http://localhost:9092/write?consistency=&db=_internal&precision=ns&rp=monitor: dial tcp 127.0.0.1:9092: getsockopt: connection refused
[subscriber] 2017/03/31 16:00:50 Post http://localhost:9092/write?consistency=&db=_internal&precision=ns&rp=monitor: dial tcp 127.0.0.1:9092: getsockopt: connection refused
[subscriber] 2017/03/31 16:01:00 Post http://localhost:9092/write?consistency=&db=_internal&precision=ns&rp=monitor: dial tcp 127.0.0.1:9092: getsockopt: connection refused
[subscriber] 2017/03/31 16:01:10 Post http://localhost:9092/write?consistency=&db=_internal&precision=ns&rp=monitor: dial tcp 127.0.0.1:9092: getsockopt: connection refused
[subscriber] 2017/03/31 16:01:20 Post http://localhost:9092/write?consistency=&db=_internal&precision=ns&rp=monitor: dial tcp 127.0.0.1:9092: getsockopt: connection refused

Influx subscriptions:

name: scatto
retention_policy	name						mode	destinations
----------------	----						----	------------
autogen			kapacitor-288d83d9-e966-4098-87cd-ec970f6c1f35	ANY	[http://localhost:9092]

name: mydb
retention_policy	name						mode	destinations
----------------	----						----	------------
autogen			kapacitor-288d83d9-e966-4098-87cd-ec970f6c1f35	ANY	[http://localhost:9092]

**Comment by nhaugo** [comment]
Hi @alparslanuysal,
Can you take this to https://community.influxdata.com we try to limit github to bugs and feature requests.
