### ISSUE TITLE
percentile - reflect: Call using int64 as type float64

### ISSUE THREAD

**Issue by cheribral** [influxdata/kapacitor#129]
I was going to try out the example on the bottom of the getting started page, and ran into this error when trying to reload the tick script:
invalid task: error calling func "percentile" on obj *kapacitor.influxqlMapReducers: reflect: Call using int64 as type float64

With my feeble understanding of how the scripts work and only a notion of what the error might mean, I tried to make a new variable that was cast to different types (float or int) using a lambda expression, but with no luck.  All of my data is fed in from telegraf, and looks something like this
```
name: cpu_usage_idle
--------------------
time			cpu		datacenter	host					location	value
1451520660000000000	cpu0		tx		dbsn1					tx		41.9993290845898
...
```
The tick script has only a modification to the groupBy, but should otherwise be exactly as it appears in the example
```
stream
    // Select just the cpu_usage_idle measurement from our example database.
    .from().measurement('cpu_usage_idle')
    .eval(lambda: 100 - "value")
        .as('used')
    .groupBy('location')
    .window()
        .period(1m)
        .every(1m)
    // calculate the 95th percentile of the used cpu.
    .mapReduce(influxql.percentile('used', 95))
    .eval(lambda: sigma("percentile"))
        .as('sigma')
        .keep('percentile', 'sigma')
    .alert()
        .id('{{ .Name }}/{{ index .Tags "service" }}/{{ index .Tags "datacenter"}}')
        .message('{{ .ID }} is {{ .Level }} cpu-95th:{{ index .Fields "percentile" }}')
        // Compare values to running mean and standard deviation
        .warn(lambda: "sigma" > 2.5)
        .crit(lambda: "sigma" > 3.0)
        .log('/tmp/alerts.log')
```

Is there some trick I need to do to get around this, or is this a bug?

**Comment by nathanielc** [comment]
Change this line

` .mapReduce(influxql.percentile('used', 95))` to ` .mapReduce(influxql.percentile('used', 95.0))`

That should get you around the error.

**Comment by cheribral** [comment]
Ah ok, I had fixated on 'used' as the problem, and never even considered the percentile.  I should have thought of that... :P
Thank you!
