### ISSUE TITLE
Filter Issue (or feature) about hour

### ISSUE THREAD

**Issue by JulienChampseix** [influxdata/kapacitor#1290]
Hi Team,

I'm having some trouble using hour condition you'll find bellow my explanation.

I would have an alert based on query which will count 'value' for last5 min but only during certain defined hours so i build my tick with this need.

Tick : 

```
var data = batch
|query('''select count(value) as value from "metrics"."autogen"."datas" ''')
.groupBy('channel','result')

var last5min = data
.every(1m)
.period(5m)
|where(lambda: hour("time") > 10 AND hour("time") < 20)
|where(lambda: "time" - now() > 5m)
|where(lambda: "metric" == 'last5min')

last5min
        |alert()
        .id('Last5min {{ .Name }} - {{ index .Tags "channel" }} {{ index .Tags "result" }} ')
        .message('''
*[{{.Level}}] - {{.ID}}*
*Value:* {{ index .Fields "last5min.value" }}
''')
        .crit(lambda: "last5min.value" != 0)
        .critReset(lambda: "last5min.value" > 300)
        .slack()
        .log('/tmp/alerting_registration.log')
```

Unfortunatly the query ran is this one by example (so taking hour as interval instead of condition) : 
```SELECT count(value) AS value FROM metrics.autogen.datas WHERE time >= '2017-03-31T10:00:00.419071259Z' AND time < '2017-03-31T19:44:59.419071259Z'```

The result expected : 
The query run with time > now() - 5m only if hours are in the range defined (hour("time") > 10 AND hour("time") < 20)

Thanks for your help.

**Comment by nhaugo** [comment]
Hi @JulienChampseix, would you mind taking this to https://community.influxdata.com we try to use github for bugs and feature requests. Thank you.

**Comment by JulienChampseix** [comment]
@nhaugo does that mean the returned result is correct ? I thought it was a bug in term of usage with hour() which look weird.
