### ISSUE TITLE
Unexpected calculation behavior

### ISSUE THREAD

**Issue by ZhijieWang** [influxdata/kapacitor#1293]
I have a very odd case, the Kapacitor `if` clause comparison is failing at a very specific spot

System OSX 10.11.6
Homebrew install

Kapacitor v1.2.0 (git:  5408057e5a3493d3b5bd38d5d535ea45b587f8ff)

Connected to http://localhost:8086 version 1.2.2
InfluxDB shell version: v1.2.2

Input for the task
``
influx -database 'example' -execute 'select time, bay_utilization from bay_utilization' -format 'column' -precision 'rfc3339'
``
> name: bay_utilization
> time                 bay_utilization
> ----                 ---------------
> 2017-03-31T12:05:00Z 30
> 2017-03-31T12:06:00Z 30
> 2017-03-31T12:07:00Z 30
> 2017-03-31T12:08:00Z 30
> 2017-03-31T12:09:00Z 30
> 2017-03-31T12:10:00Z 30
> 2017-03-31T12:11:00Z 30
> 2017-03-31T12:12:00Z 30
> 2017-03-31T12:13:00Z 30
> 2017-03-31T12:14:00Z 30
> 2017-03-31T12:15:00Z 30
> 2017-03-31T12:16:00Z 30
> 2017-03-31T12:17:00Z 30
> 2017-03-31T12:18:00Z 30
> 2017-03-31T12:19:00Z 30
> 2017-03-31T12:20:00Z 90
> 2017-03-31T12:21:00Z 90
> 2017-03-31T12:22:00Z 90
> 2017-03-31T12:23:00Z 90
> 2017-03-31T12:24:00Z 90
> 2017-03-31T12:25:00Z 90
> 2017-03-31T12:26:00Z 90
> 2017-03-31T12:27:00Z 90
> 2017-03-31T12:28:00Z 90
> 2017-03-31T12:29:00Z 90
> 2017-03-31T12:30:00Z 90
> 2017-03-31T12:31:00Z 90
> 2017-03-31T12:32:00Z 90
> 2017-03-31T12:33:00Z 90
> 2017-03-31T12:34:00Z 90

Task Definition:
```
// Get batch data
var views = batch
    |query('SELECT mean(bay_utilization) FROM "example"."autogen".bay_utilization')
        .period(15m)
        .every(15m)
        .groupBy(time(1m), *)
        .fill(0)

views
//  |log()
//     .prefix('Debugging TICK')
    |eval(lambda: if ("mean">40, 1, 0))
    .as('value')
    |influxDBOut()
    .database('example')
    .measurement('Bay')
```

execution:
```
## clear output table
influx -database 'example' -execute 'delete from Bay'
## define task, refresh task definition
kapacitor define bay_state \
    -type batch \
    -tick BayState.tick \
    -dbrp example.autogen
## generate recording
rid=$(kapacitor record batch -task bay_state -start 2017-03-30T12:03:25.472999936Z -stop 2017-04-01T12:03:25.472999936Z)
## test task definition with recoding
kapacitor replay -task bay_state -recording $rid -rec-time 
## remove recording after done
kapacitor delete recordings $rid
## verify output
influx -database 'example' -execute 'select * from Bay' -format 'csv' -precision 'rfc3339'
```

Output

> ef6979b0-b455-40a4-872d-c44084eb5131
> name,time,bay_number,value,work_zone

> Bay,2017-03-31T12:10:00Z,6,0,NW
> Bay,2017-03-31T12:11:00Z,6,0,NW
> Bay,2017-03-31T12:12:00Z,6,0,NW
> Bay,2017-03-31T12:13:00Z,6,0,NW
> Bay,2017-03-31T12:14:00Z,6,0,NW
> Bay,2017-03-31T12:15:00Z,6,0,NW
> Bay,2017-03-31T12:16:00Z,6,0,NW
> Bay,2017-03-31T12:17:00Z,6,0,NW
> Bay,2017-03-31T12:18:00Z,6,0,NW
> Bay,2017-03-31T12:19:00Z,6,0,NW
> Bay,2017-03-31T12:20:00Z,6,1,NW
> Bay,2017-03-31T12:21:00Z,6,1,NW
> Bay,2017-03-31T12:22:00Z,6,1,NW
> Bay,2017-03-31T12:23:00Z,6,1,NW
> Bay,2017-03-31T12:24:00Z,6,1,NW
> Bay,2017-03-31T12:25:00Z,6,1,NW
> Bay,2017-03-31T12:26:00Z,6,1,NW
> Bay,2017-03-31T12:27:00Z,6,1,NW
> Bay,2017-03-31T12:28:00Z,6,1,NW
> Bay,2017-03-31T12:29:00Z,6,1,NW
> Bay,2017-03-31T12:30:00Z,6,1,NW
> Bay,2017-03-31T12:31:00Z,6,1,NW
> Bay,2017-03-31T12:32:00Z,6,1,NW
> Bay,2017-03-31T12:33:00Z,6,0,NW
> Bay,2017-03-31T12:34:00Z,6,1,NW
> Bay,2017-03-31T12:35:00Z,6,0,NW
> Bay,2017-03-31T12:36:00Z,6,0,NW
> Bay,2017-03-31T12:37:00Z,6,0,NW
> Bay,2017-03-31T12:38:00Z,6,0,NW

The issue is `2017-03-31T12:33:00Z` for the output will always be 0. I have tried to adjust the threshold.

Trying to debug Kapacitor task input:
`influx -database 'example' -execute "select mean(bay_utilization) from bay_utilization where time>'2017-03-31T12:03:25.472999936Z' and time<'2017-03-31T12:50:25.472999936Z' group by time(1m)" -format 'csv' -precision 'rfc3339'`

> name,time,mean
```
bay_utilization,2017-03-31T12:03:00Z,
bay_utilization,2017-03-31T12:04:00Z,
bay_utilization,2017-03-31T12:05:00Z,30
bay_utilization,2017-03-31T12:06:00Z,30
bay_utilization,2017-03-31T12:07:00Z,30
bay_utilization,2017-03-31T12:08:00Z,30
bay_utilization,2017-03-31T12:09:00Z,30
bay_utilization,2017-03-31T12:10:00Z,30
bay_utilization,2017-03-31T12:11:00Z,30
bay_utilization,2017-03-31T12:12:00Z,30
bay_utilization,2017-03-31T12:13:00Z,30
bay_utilization,2017-03-31T12:14:00Z,30
bay_utilization,2017-03-31T12:15:00Z,30
bay_utilization,2017-03-31T12:16:00Z,30
bay_utilization,2017-03-31T12:17:00Z,30
bay_utilization,2017-03-31T12:18:00Z,30
bay_utilization,2017-03-31T12:19:00Z,30
bay_utilization,2017-03-31T12:20:00Z,90
bay_utilization,2017-03-31T12:21:00Z,90
bay_utilization,2017-03-31T12:22:00Z,90
bay_utilization,2017-03-31T12:23:00Z,90
bay_utilization,2017-03-31T12:24:00Z,90
bay_utilization,2017-03-31T12:25:00Z,90
bay_utilization,2017-03-31T12:26:00Z,90
bay_utilization,2017-03-31T12:27:00Z,90
bay_utilization,2017-03-31T12:28:00Z,90
bay_utilization,2017-03-31T12:29:00Z,90
bay_utilization,2017-03-31T12:30:00Z,90
bay_utilization,2017-03-31T12:31:00Z,90
bay_utilization,2017-03-31T12:32:00Z,90
bay_utilization,2017-03-31T12:33:00Z,90
bay_utilization,2017-03-31T12:34:00Z,90
bay_utilization,2017-03-31T12:35:00Z,
bay_utilization,2017-03-31T12:36:00Z,
bay_utilization,2017-03-31T12:37:00Z,
bay_utilization,2017-03-31T12:38:00Z,
bay_utilization,2017-03-31T12:39:00Z,
bay_utilization,2017-03-31T12:40:00Z,
bay_utilization,2017-03-31T12:41:00Z,
```

**Comment by ZhijieWang** [comment]
After further debugging with Kapacitor logging, `2017-03-31T12:33` is the end of first batch, and the beginning of the second batch. `2017-03-31T12:33` in the batch 1 has mean of 90, in the batch 2 has mean of 0. It seems Kapacitor batch slicing is using (start-time, end-time]. So endtime is included in the previous batch, not in the next batch, and all of my events are stamped at the exact 0 second.

**Comment by ZhijieWang** [comment]
`fill(0)` will result in above behavior

`fill('previous')` will handle is properly

is there any way to fill a fixed value properly?

**Comment by nathanielc** [comment]
Does adding a `.align()` to the batch query fix the issue as well?

**Comment by ZhijieWang** [comment]
adding `.align()` resolved the problem. may i know the reason behind this?
