### ISSUE TITLE
Evaluating lambda with tags at the alert level

### ISSUE THREAD

**Issue by jose5918** [influxdata/kapacitor#1301]
I was wondering if it was possible to alert based off of tags.

An example would be: 

``` 
.warn(lambda: strContains("pod_name",'filter'))
```
`pod_name` is a tag that was grouped by and I get the following error when trying to use it in an alert
```
E! error evaluating expression for level WARNING: no field or tag exists for pod_name
```
I have verified using the `|log()` function that `pod_name` exists and contains a value.  My question is whether this is the intended scope of warnings (that they shouldn't be able to use tags), and if this is the case the error logs should be made to reflect that tags are not allowed.

**Kapacitor version 1.1**
**Using the container image for 1.1**

**Comment by nathanielc** [comment]
@jose5918 You should be able to use tags, can you share the log lines that show the value?

**Comment by jose5918** [comment]
@nathanielc I had to modify it a bit to take out anything sensitive, but this is what log entries look like before using the `|alert()` node
```
[test:log19] 2017/04/04 22:18:29 I!  {cpu/limit 2017-04-04 22:18:00 +0000 UTC 
container_name=cassandra,namespace_name=cassandra,pod_name=cassandra-client false 
map[container_name:cassandra namespace_name:cassandra pod_name:cassandra-client]
 [{2017-04-04 22:18:00 +0000 UTC map[sigma:NaN request.stat:250 usage_percent:77.2 
request_percent:77.2 limit.stat:250 usage.stat:193]
 map[container_name:cassandra namespace_name:cassandra pod_name:cassandra-client]}]}
```

**Comment by nathanielc** [comment]
Thanks and was this log followed immediately with an error like the one posted above?

**Comment by jose5918** [comment]
Yes, the alert following the log gives that error.

**Comment by jose5918** [comment]
@nathanielc I am using the latest version and don't experience this issue.  You can close this if you would like
