### ISSUE TITLE
RHEL7 failed to enable service

### ISSUE THREAD

**Issue by jasonkeller** [influxdata/kapacitor#1309]
Upon installing Kapacitor on RHEL7, doing the following to try to start it on startup comes up with this error...
```
#systemctl enable kapacitor
Failed to execute operation: Too many levels of symbolic links
```
I believe this is due to...
```
# ls -lh /etc/systemd/system
lrwxrwxrwx. 1 root root   41 Apr  7 10:01 kapacitor.service -> /usr/lib/systemd/system/kapacitor.service
-rw-rw-r--. 1 root root  466 Mar 22 22:47 kibana.service
-rw-r--r--. 1 root root  511 Mar 30 13:47 logstash.service
```
You can see the others are real .service files, but this is a symlink.

**Comment by nathanielc** [comment]
@jasonkeller What version did you install? Did you install via the rpms package we provide? What is the value of `/usr/lib/systemd/system/kapacitor.service`? Is it another symlink or an actual file?

**Comment by jasonkeller** [comment]
Installed it via the repository with yum...
`kapacitor.x86_64                     1.2.0-1`
```
# If you modify this, please also make sure to edit init.sh

[Unit]
Description=Time series data processing engine.
Documentation=https://github.com/influxdb/kapacitor
After=network.target

[Service]
User=kapacitor
Group=kapacitor
LimitNOFILE=65536
EnvironmentFile=-/etc/default/kapacitor
ExecStart=/usr/bin/kapacitord -config /etc/kapacitor/kapacitor.conf $KAPACITOR_OPTS
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
Alias=kapacitor.service

```

**Comment by adityacs** [comment]
@jasonkeller May be due to this [https://github.com/systemd/systemd/issues/3010](url).

**Comment by jasonkeller** [comment]
@adityacs that's entirely possible, but I couldn't say for certain that the issue lies entirely there.  Logstash, Kibana, Telegraf, and Elasticsearch all work just fine as packaged.

**Comment by adityacs** [comment]
@jasonkeller From your screenshot I don't see symlinks created for elasticsearch.service and kibana.service. If theose services were enabled then there should have been a symlink. Also, for kapacitor there is a symlink created. I believe it's enabled. Have you tried rebooting your system and then check that kapacitor starts on reboot?

**Comment by jasonkeller** [comment]
I believe it's putting them elsewhere...
```
# systemctl disable logstash
Removed symlink /etc/systemd/system/multi-user.target.wants/logstash.service.
```
Kibana wasn't actually enabled for startup...
```
# systemctl enable kibana
Created symlink from /etc/systemd/system/multi-user.target.wants/kibana.service to /etc/systemd/system/kibana.service.
```
Please pardon some of the confusion on this box; it's a temporary staging area that we're testing different products in and shaking down our methodology and configurations before moving to production.

```
# ls -lh /etc/systemd/system/multi-user.target.wants/
lrwxrwxrwx. 1 root root 45 Mar  9 10:18 elasticsearch.service -> /usr/lib/systemd/system/elasticsearch.service
lrwxrwxrwx. 1 root root 46 Mar  9 14:36 grafana-server.service -> /usr/lib/systemd/system/grafana-server.service
lrwxrwxrwx. 1 root root 41 Apr  7 10:01 kapacitor.service -> /usr/lib/systemd/system/kapacitor.service
lrwxrwxrwx. 1 root root 34 Apr 11 09:41 kibana.service -> /etc/systemd/system/kibana.service
lrwxrwxrwx. 1 root root 37 Mar  9 14:05 nginx.service -> /usr/lib/systemd/system/nginx.service
lrwxrwxrwx. 1 root root 40 Mar 17 09:57 telegraf.service -> /usr/lib/systemd/system/telegraf.service
```
It appears it wants actual service files in both `/etc/systemd/system` and `/usr/lib/systemd/system`, not just a symlink from the first to the second.

**Comment by adityacs** [comment]
I am using centOS7 and I don't see any problem. I have a symlink from 
`/etc/systemd/system to /usr/lib/systemd/system`

`kapacitor.service -> /usr/lib/systemd/system/kapacitor.service`

**Comment by nathanielc** [comment]
This error 

```
Failed to execute operation: Too many levels of symbolic links
```

typically means that you have infinity recursive symlinks somewhere. 

My guess is that systemd isn't being picky about symlinks but rather it followed the path of symlinks and never actually ended up at a real file.

**Comment by jasonkeller** [comment]
Ironically now I can't even start Kapacitor; it fails after mere milliseconds of starting with no log output

**Comment by nathanielc** [comment]
In my experience I have seen systemd drop output from STDERR if the process immediately dies. Try running it by hand and see what output you get


```
sudo -u kapacitor kapacitord -config /etc/kapacitor/kapacitor.conf
```

**Comment by jasonkeller** [comment]
I seem to have it sorted by copying the .service file instead of the symlink, and now systemd is happy.  I have the service starting and it should start on restart now.

Before I go too far OT, is there another place to post questions/issues other than influx community (which has been down all day now)?

**Comment by nathanielc** [comment]
> Before I go too far OT, is there another place to post questions/issues other than influx community (which has been down all day now)?

No, for now using github issues is fine. Hopefully we have it back up soon, and are able to avoid such outages in the future.

**Comment by jasonkeller** [comment]
Thank @nathanielc ; especially with Kapacitor I've had a very, very difficult time trying to find reliable configuration examples for what I'm trying to accomplish (basically taking stream output from Telegraf (which is gathering SNMP octet counters from network devices), calculating a longer average derivative (such as daily), and feeding it back into Telegraf to put into Elasticsearch in a different index set.

This is of course all in the name of downsampling the data, and I have to keep data bucketed per-interface per-device.  Basically I'll have 1 minute data kept 30 days; daily averages kept for probably 2 years for trending.  Thus far I've been striking out, and it's the last piece of this puzzle I need to put together.  Part of the reason for using Kapacitor to do the calculation is to try to make it resistant to a counter reset/rollover as I'm told my compatriots in the NOC love resetting counters on equipment.  Unfortunately I'm totally lost as to how to get Kapacitor working for this, especially since I have to use Elasticsearch and not InfluxDB (netflow will also be stored in this DB, and I need quick scale-out and redundancy options).

**Comment by nathanielc** [comment]
@jasonkeller Do you have a TICKscript you have tried at this point? Sounds like you now have the service running? What step are you on next?

What you describe sounds like pretty straightforward down sampling task so I should be able to help you out.  There is one hurdle you willll have, which is that Kapacitor has no persistence of the data it is processing. So if Kapacitor restarts you will loose all data in RAM, the typical answer to that problem is store the data in InfluxDB and Kapacitor can resume where it left off, but in your case that is going to be difficult. I would consider backing Kapacitor by InfluxDB at least for a small buffer of time so that you can overcome that issue. But we can come back to that problem when we get there.

Right now what have you tried and where are you stuck?

**Comment by jasonkeller** [comment]
So far I have this in Telegraf...

```
[[inputs.http_listener]]
  service_address = "localhost:8186"
  read_timeout = "10s"
  write_timeout = "10s"
```

```
[[outputs.elasticsearch]]
  urls = [ "http://127.0.0.1:9200" ]
  timeout = "5s"
  enable_sniffer = false
  health_check_interval = "10s"
  index_name = "telegraf-%Y.%m.%d"
  namedrop = ["aggregate*"]

[[outputs.elasticsearch]]
  urls = [ "http://127.0.0.1:9200" ]
  timeout = "5s"
  enable_sniffer = false
  health_check_interval = "10s"
  index_name = "telegraf-%Y"
  namepass = ["aggregate*"]

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "telegraf"

```

And here's the TICKscript...
```
# cat /etc/kapacitor/rollup.tick
stream
    |from()
        .database('telegraf')
        .retentionPolicy('autogen')
        .measurement('interface')
        .groupBy(*)
    |window()
        .period(1h)
        .every(1h)
        .align()
        |derivative('ifHCInOctects')
                .as('in_bandwidth')
                .unit(1s)
                .nonNegative()
    |influxDBOut()
        .database('telegraf')
        .retentionPolicy('autogen')
        .measurement('aggregate')
        .precision('s')

stream
    |from()
        .database('telegraf')
        .retentionPolicy('autogen')
        .measurement('interface')
        .groupBy(*)
    |window()
        .period(1h)
        .every(1h)
        .align()
        |derivative('ifHCOutOctects')
                .as('out_bandwidth')
                .unit(1s)
                .nonNegative()
    |influxDBOut()
        .database('telegraf')
        .retentionPolicy('autogen')
        .measurement('aggregate')
        .precision('s')
```

Configuration of Kapacitor is just the default, though I ended up having to set this in the conf file to get the service to respond...

```
[[influxdb]]
  enabled = false
```

**Comment by nathanielc** [comment]
OK looks good so far expect for the influxdb telegraf output.

```
[[outputs.influxdb]]
  urls = ["http://localhost:9092"]
  database = "telegraf"
```

Telegraf can write to Kapacitor as if it were an InfluxDB server, just change the port to be the default Kapacitor port.

Once that is setup check that Kapacitor is receiving data from Telegraf via:

```
kapacitor stats ingress
```

You should see lots of entries from the `telegraf` database.

**Comment by jasonkeller** [comment]
oooh!  that poke did it.  I'd have never guessed to switch an output from telegraf to the api endpoint of kapacitor (I thought that was only for commands to it, not data).

```
# kapacitor stats ingress
Database   Retention Policy Measurement Points Received
_kapacitor autogen          edges                    15
_kapacitor autogen          ingress                  15
_kapacitor autogen          kapacitor                 3
_kapacitor autogen          nodes                    12
_kapacitor autogen          runtime                   3
telegraf                    dhcp                   2540
telegraf                    interface              9687
telegraf                    system                   12
```
I'm hoping I'm at least close with this configuration, but I can't be perfectly sure how it's going to turn out (if it's going to be bucketed properly, how it's rolling up the interval, how much memory it needs, etc).

Memory and CPU are big concerns; right now my production flight-list will have Kapacitor co-located on the same node with Telegraf with 4 vCPU and 8GB of memory (I'm pushing for 16GB, but not sure I'm going to get it).  I have 1600 devices I'll be polling probably every minute.

**Comment by nathanielc** [comment]
@jasonkeller Community is back up, should we move this conversation over there?

**Comment by jasonkeller** [comment]
Sure; https://community.influxdata.com/t/using-kapacitor-to-rollup-metrics/522

**Comment by nathanielc** [comment]
Great, I'll follow that thread over there. For now I am going to close this issue here.

**Comment by dandv** [comment]
[Same issue with influxd](https://github.com/influxdata/influxdb/issues/7850) v1.3.

**Comment by twm** [comment]
For the record, I hit this issue with influxdb.service. The Debian package was failing in the configure stage:

```
$ sudo dpkg-reconfigure influxdb --force
Failed to execute operation: Too many levels of symbolic links
```

The workaround is to recreate the systemd wants symlink:

```
$ sudo systemctl disable influxdb
Removed symlink /etc/systemd/system/influxdb.service.
Removed symlink /etc/systemd/system/multi-user.target.wants/influxdb.service.
$ sudo systemctl enable influxdb
Created symlink from /etc/systemd/system/influxd.service to /lib/systemd/system/influxdb.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/influxdb.service to /lib/systemd/system/influxdb.service.
```
