### ISSUE TITLE
Alert initializing "currentState" incorrectly with groupBy

### ISSUE THREAD

**Issue by sputnik13** [influxdata/kapacitor#1316]
When we upgraded from kapacitor 1.0.0-rc2 to 1.2.0 our tasks with groupBy started emitting extra "ok" alerts and fewer "critical" alerts.  This is based on periodic unit tests we have to ensure correct function of the monitoring framework.

From looking at the current code for the alert node, it appears when alerts are coupled with groupBy, initial alerts states for new groups are being mishandled.

https://github.com/influxdata/kapacitor/blob/d13c950150c4de6c3364aa9d9721f1e491ca5c18/alert.go#L497-L513

There seems to be an assumption that renderID will result in an ID that is unique to the group

https://github.com/influxdata/kapacitor/blob/d13c950150c4de6c3364aa9d9721f1e491ca5c18/alert.go#L1041

However the idTmpl is actually hardcoded to the node ID

https://github.com/influxdata/kapacitor/blob/d13c950150c4de6c3364aa9d9721f1e491ca5c18/alert.go#L104

Thus when event state is retrieved for a group that has not been seen previously

https://github.com/influxdata/kapacitor/blob/d13c950150c4de6c3364aa9d9721f1e491ca5c18/alert.go#L507

The resulting state ends up being the state of the last group that generated an event, which does not correspond with the user's expectation that the default state will be 'OK'.  This is especially problematic if StateChangeOnly is specified, as non-OK state may be masked for a new group if the first message received for the group meets an alert threshold and the last event sent by the alert node prior to the new group is in the same state.

It's tempting to change the idTmpl to account for the group ID, however it seems as though there's a need to add support for GroupID in the entire event chain rather than overriding the ID (which is user specified).  Since the user already has an expectation that the ID specified for the Alert node will be communicated in the id field of the output, changing the format of this ID field to be an amalgamation of ID (user specified) and groupID (data specified) could be a breaking change in the output format.

**Comment by nathanielc** [comment]
@sputnik13 Can you share a simple TICKscript that reproduces the behavior that is unexpected?

The ID field needs to account for the groupID if that is important to your use case. Some use cases want to merge alerts by using an ID field that generates the same ID from different data.

**Comment by sputnik13** [comment]
@nathanielc sure

```
stream
    |from()
        .measurement('some-measurement')
    |default()
        .field('tags.threshold_name', '')
    |where(lambda: "tags.threshold_name" == 'metric_group_by)
    |eval(lambda: "tags.hostname", lambda: "tags.threshold_name")
        .as('tags.hostname', 'tags.threshold_name')
        .tags('tags.hostname', 'tags.threshold_name')
        .keep()
    |groupBy('tags.hostname', 'tags.threshold_name')
    |default()
        .tag('thresholdId', 'a938388a-3818-4057-892d-071b0a75fdbe')
        .tag('thresholdName', 'metric_groupby')
        .tag('tenant', 'test')
    |alert()
        .id('a938388a-3818-4057-892d-071b0a75fdbe')
        .message('threshold \'metric_groupby\' is {{ .Level}}, currentValues: tags.threshold_name={{ index .Tags "tags.threshold_name" }}')
        .crit(lambda: "value" > 5)
        .stateChangesOnly()
        .post('some_alert_handler_service')
```

Our test data looks something like this

```
// expected begin state (host1 ok, host2 ok, host3 ok, host4 ok)
wait 5s
send [
    (host1, 7)  // expect 1 crit
]

// expected begin state (host1 crit, host2 ok, host3 ok, host4 ok)
wait 5s
send [
    (host2, 7) // expect 1 crit
    (host3, 4) // expect no alert (neither crit nor ok)
]

// expected begin state (host1 crit, host2 crit, host3 ok, host4 ok)
wait 5s
send [
    (host2, 7) // expect no alert due to state change only 30
    (host3, 7) // expect 1 crit
]

// expected begin state (host1 crit, host2 crit, host3 crit, host4 ok)
wait 5s
send [
    (host2, 7) // expect no alert, state change only 30
    (host3, 7) // expect no alert, state change only 30
    (host1, 4) // expect 1 ok
]

// expected begin state (host1 ok, host2 crit, host3 crit, host4 ok)
wait 5s
send [
    (host1, 7) // expect 1 crit
    (host4, 7) // expect 1 crit
]

// expected begin state (host1 crit, host2 crit, host3 crit, host4 crit)
wait 5s
send [
    (host1, 4) // expect 1 ok
    (host2, 4) // expect 1 ok
    (host3, 4) // expect 1 ok
    (host4, 4) // expect 1 ok
]
```

So at the end of all that we are expecting a total of 5 crit alerts and 5 ok alerts, which we were getting in 1.0.  However, with 1.2 we were getting 3 crit and 6 ok alerts (I don't have the exact sequence right now, will need to recreate environment with 1.2 to do this)

Tracking down what changed and why this was happening led to the analysis in the first post.

**Comment by sputnik13** [comment]
With respect to group ID, I can see the case for the latter example you gave of users wanting to merge alerts with the same ID, so I think the groupID (which is actually present in the alert detail when you deserialize that field as json) should be part of the uniqueness consideration when evaluating state of an alert, which it actually is in

https://github.com/influxdata/kapacitor/blob/d13c950150c4de6c3364aa9d9721f1e491ca5c18/alert.go#L502

The problem is, when a state is not found for the group, the attempt to "restoreEventState" ends up using just the alert ID and does not account for the group information.  I believe this is due to a flawed assumption in

https://github.com/influxdata/kapacitor/blob/d13c950150c4de6c3364aa9d9721f1e491ca5c18/alert.go#L497

that passing p.Group (what I'm calling a "groupID") to renderID would result in an ID that accounts for group, which it does not.

At the same time, if the alert emitted an ID that embedded the groupID rather than providing a separate field for the groupID, it may impact the second use case you mentioned.
