### ISSUE TITLE
typo in UDF example

### ISSUE THREAD

**Issue by ZhijieWang** [influxdata/kapacitor#1325]
In the following line

> func (o *outlierHandler) Snaphost() (*udf.SnapshotResponse, error) {
	return &udf.SnapshotResponse{}, nil
}

`Snaphost` should be `Snapshot`.
https://github.com/influxdata/kapacitor/blob/master/udf/agent/examples/outliers/outliers.go#L67

I have gone through all the examples in repo and `agent.go` interface. All of them are defined as `Snaphost`.

**Comment by nathanielc** [comment]
@ZhijieWang  Thanks!
