### ISSUE TITLE
[Feature Request] Kapacitor should have dashboad which shows the all registered alerts

### ISSUE THREAD

**Issue by achilles42** [influxdata/kapacitor#1328]
Kapacitor should have dashboard which will show all the alerts which includes enabled and disabled alerts along with the info which is currently there in `kapacitor show alert_name` command

For example: 

 ```
alert1 [ avg_exec_time_ns="15.673794ms"
            batches_queried="57728" 
            points_queried="1731400"
            query_errors="0" 
   ];
 alert2 [alerts_triggered="0"
            avg_exec_time_ns="24.218µs" 
            crits_triggered="0" 
            infos_triggered="0" 
            oks_triggered="0" 
            warns_triggered="0" 
  ];
```

**Comment by adityacs** [comment]
@shukla-praveen Use "Chronograf ". You can configure, enable and disable alerts and also see how many alerts were triggered from "Chronograf" UI.

**Comment by shukla-praveen** [comment]
Thanks @adityacs, will checkout chronograf's configure alerts functionality.
