### ISSUE TITLE
derivative node returns value from the future

### ISSUE THREAD

**Issue by phemmer** [influxdata/kapacitor#1329]
The `derivative()` node computes the derivative between a point, and the one that follows it, but adds the calculated derivative value to the first point, not the second.
This is counterintuitive as this is not how a derivative is defined, nor is it how InfluxDB's derivative behaves.
Additionally the behavior results in the `derivative()` node buffering a point. If it behaved as expected, buffering would not be necessary.

```
foo v=1i 1000000000
foo v=2i 2000000000
foo v=4i 3000000000
foo v=8i 4000000000
foo v=16i 5000000000
```
```
stream|from().measurement('foo')|derivative('v').as('derivative')|log()
```

Expected:
```
"Fields":{"v":1},"Time":"1970-01-01T00:00:01Z"
"Fields":{"v":2,"derivative":1},"Time":"1970-01-01T00:00:02Z"
"Fields":{"v":4,"derivative":2},"Time":"1970-01-01T00:00:03Z"
"Fields":{"v":8,"derivative":4},"Time":"1970-01-01T00:00:04Z"
"Fields":{"v":16,"derivative":8},"Time":"1970-01-01T00:00:05Z"
```

Actual:
```
"Fields":{"v":1,"derivative":1},"Time":"1970-01-01T00:00:01Z"
"Fields":{"v":2,"derivative":2},"Time":"1970-01-01T00:00:02Z"
"Fields":{"v":4,"derivative":4},"Time":"1970-01-01T00:00:03Z"
"Fields":{"v":8,"derivative":8},"Time":"1970-01-01T00:00:04Z"
```

**Comment by nathanielc** [comment]
@phemmer Looking through your examples I agree the actual behavior is quite confusing. We will take a look at the best way to fix this while minimizing any breaking changes to existing behavior.

**Comment by phemmer** [comment]
I actually started work on this. Basically I just adjusted it so that the derivative is added to the latter point, not the former one, and the first point in the stream/batch is dropped (currently in batch the last point is dropped).
But I can abandon the work if you want to handle it yourself.

**Comment by nathanielc** [comment]
Go ahead a put up a PR on what you have, we can start the discussion from there. Your solution sounds like what I was thinking.
