### ISSUE TITLE
Alerts and StateChange

### ISSUE THREAD

**Issue by jgerschk** [influxdata/kapacitor#134]
With regard to state change, I assume, based on my testing that state change is only valid for one tick script.  

Let me explain with data.

tick=30,metric=DN,symbol=GPSMDN94,component=SM

this will trigger an alarm (critical) as it matches the where below.

tick=1,metric=DN,symbol=GSSMDN94,component=SM

The symbol tag is slightly different, and this produces and OK if after the above critical.  

stream
 .from().measurement('metric')
  .where(lambda: "metric" == 'DN' AND "component" == 'SM')
  .alert()
   .id ('{{ index .Tags "symbol" }} / {{ index .Tags "location" }}')
   .message('{{.ID}} is {{.Level}} value: {{ index .Fields "tick"}}')
   .crit(lambda: "tick" > 25)
   .email('someone@work.com')
   .log('/tmp/user_alerts.log')

Now, my questions.

1) Can state change be disabled ?
2) Can we make state change unique to a tag or the id of the alert so that we don't get clears for data that really should not be OK util it is OK.

Let me know what you guys think.

**Comment by rossmcdonald** [comment]
@jgerschk Do you observe the same behaviour if you alter your script to the following:

```
stream
.from().measurement('metric')
.where(lambda: "metric" == 'DN' AND "component" == 'SM').groupBy('symbol')
.alert()
.id ('{{ index .Tags "symbol" }} / {{ index .Tags "location" }}')
.message('{{.ID}} is {{.Level}} value: {{ index .Fields "tick"}}')
.crit(lambda: "tick" > 25)
.email('someone@work.com')
.log('/tmp/user_alerts.log')
```

Where `.groupBy('symbol')` is added to the `.where()`? 

Otherwise you're just relying on the `tick` value alone for your alerting, which is why you're seeing the alert switch back and forth regardless of `symbol` value. I may be misunderstanding your intention, though.

**Comment by jgerschk** [comment]
@rossmcdonald Let me give that a try, never thought about adding groupBy there.  I'll let you guys know later.

**Comment by jgerschk** [comment]
@rossmcdonald Thank you.  That seems to have cured my problem.  Appreciate the quick response.

Closing question/issue.
