### ISSUE TITLE
Multiple email address in .email not working

### ISSUE THREAD

**Issue by jgerschk** [influxdata/kapacitor#135]
It appears that multiple email address do not work.  No matter what I use to separate the email address, either , or ; (both legal depending on the mail server).  In this case we are replying via POSTFIX so comma list is acceptable.  Further if I change the order, so move user2 first only that one gets it.

In the postfix logs, I only see one receipt ever being sent to, not the second one.  

I've tried to add two .email lines, then no emails come.

stream
 .from().measurement('metric')
  .where(lambda: "metric" == 'TT' AND "component" == 'QM').groupBy('symbol')
  .alert()
   .id ('{{ index .Tags "symbol" }} / {{ index .Tags "location" }}')
   .message('{{.ID}} is {{.Level}} value: {{ index .Fields "tick"}}')
   .crit(lambda: "tick" > 45000)
   .email('user1@domain.com, user2@domain.com')
   .log('/tmp/qm_alerts.log')

What am I missing?

**Comment by nathanielc** [comment]
Try,
`.email('user1@example.com', 'user2@example.com')`

**Comment by jgerschk** [comment]
@nathanielc Perfect.  Thank you.  Resolves it.  Thanks for the query reply.

Loving what I am seeing and able to do with this tool.  Thanks for the work on it.

Closing issue.

**Comment by ZhangZhenhua** [comment]
hi @nathanielc @jgerschk ,

Have you tried to define the mail list as variable and then use it as `.email(maillist)`?

I tried 

```
var maillist = 'user1@example.com',`user2@example.com`
````
 and 
```
var maillist = ' \'user1@example.com\',\'user2@example.com\' '
```
but both failed.

Could you please shed some light on it? Thanks!

**Comment by nathanielc** [comment]
@ZhangZhenhua To define a list use `[]`

```
var maillist = ['user1@example.com','user2@example.com']

...
|alert()
  .email(maillist)
```

This requires version >= 1.0.0-beta1

**Comment by ZhangZhenhua** [comment]
@nathanielc thanks, look forward to the official 1.0 now. BTW, great work on kapacitor!
