### ISSUE TITLE
Feature - Pagerduty API v2

### ISSUE THREAD

**Issue by JulienChampseix** [influxdata/kapacitor#1358]
Hi Team,

Would be great to have also the support the version of pagerduty API v2.
https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2

Currently only v1 looks to be supported. 
Have the choice between v1 & v2 into the alert node will be amazing !

**Comment by phemmer** [comment]
As an end user, is there any visible benefit one would get out of API v2?

**Comment by panovodv** [comment]
As an enduser you get to send more metadata (location, class, component, severity) and then you can use event supression rules based on that.

**Comment by zygis** [comment]
Pagerduty just announced end of life for api v1. 
>[..] we are extending API v1 support to February 6, 2018 [..]

**Comment by nathanielc** [comment]
Thanks @panovodv and @zygis for the info. PRs welcome on upgrading to the v2 API. If anyone wants to take a crack at it I'll help get you started.

**Comment by nathanielc** [comment]
Fixed by #1795
