### ISSUE TITLE
Kapacitor | Morgoth - Permission Denied error

### ISSUE THREAD

**Issue by xylene1980** [influxdata/kapacitor#1362]
Hello,
Trying to run "Morgoth" , facing the below error after restarting Kapacitor...

`E! open server: open service *udf.Service: failed to load process info for "morgoth": fork/exec /home/ec2-user/go/bin/morgoth: permission denied`

Please advise

**Comment by nathanielc** [comment]
What are the permissions on /home/ec2-user/go/bin/morgoth and what user is the kapacitord process running as?

**Comment by xylene1980** [comment]
Here is below permissions for morgoth
`-rwxrwxr-x 1 ec2-user ec2-user 3499695 May  8 07:03 morgoth`

and Kapacitord process is running as 

`496       2366  0.0  2.1 210832 21604 ?        Sl   07:11   0:00 /usr/bin/kapacitord -pidfile /var/run/kapacitor/kapacitord.pid -config /etc/kapacitor/kapacitor.conf`

**Comment by nathanielc** [comment]
The kapacitor user does not have access to the home dir of the ec2-user /home/ec2-user/.
