### ISSUE TITLE
[Feature Request] Backoff period after first alert is send

### ISSUE THREAD

**Issue by mantzas** [influxdata/kapacitor#1384]
It would be nice if we could setup a backoff period after the first alert is send in order to avoid sending the same alert multiple times and flooding the recipient with messages.

example
``` 
       stream
           .groupBy('service')
       |alert()
           ...
           .backoff(10m)
```

which would backoff the alert for the next 10 minutes.

**Comment by goller** [comment]
Hi @mantzas , does the `.stateChangesOnly` node work for your use case? (https://docs.influxdata.com/kapacitor/v1.2/nodes/alert_node/#statechangesonly)

**Comment by mantzas** [comment]
hi @goller almost. it would be nice to have another alert after x minutes just as a reminder. The main purpose is not to silence the alert but to throttle the alerts so that it does not flood the recipients!

**Comment by phemmer** [comment]
@mantzas you can, `.stateChangesOnly(15m)` will resend after 15 minutes if it's still in an alert state.

**Comment by mantzas** [comment]
perfect. thanks for that.
