### ISSUE TITLE
Slack enabled=true doesn't seem to work

### ISSUE THREAD

**Issue by dboek** [influxdata/kapacitor#140]
Server: 64Bit Ubuntu 14.04
Kapacitor: 0.2.4
Package: kapacitor_0.2.4-1_amd64.deb

I installed Kapacitor using the Debian Package mentioned above. Everything installs fine, I am able to start and use Kapacitor. I was able to enable SMTP and got alerts with some simple Alerting scenarios I defined, replayed and enabled.
SMTP upon start of Kapacitor is mentioned in the logs as a Service being started.

Then I enabled Slack with a working Webhook URL, I restarted Kapacitor, but Slack is never mentioned in the logs upon start. When I use it inside an AlertNode the logs show an Error that Slack is not enabled.

Can I somehow validate the config using kapacitor? I didn't see any typo and since I used the pregenerated conf from /etc/kapacitor/kapacitor.conf I think this should be ok.

**Comment by nathanielc** [comment]
If Kapacitor starts up then the config is valid. One of the first log entries during startup is the path to the configuration file so you can confirm the daemon is using the expected one. 

You can paste you config here and I'll take a look. Also the output of `kapacitor show <task_name>` for you task would be helpful in debugging the issue.

**Comment by dboek** [comment]
Tailing the log in /var/log/kapacitor/kapacitor.log there is no mentioning of the conf path, but when I look in /var/log/kapacitor/kapacitord.err it seems to use the correct conf file:
```
2016/01/11 19:47:55 Using configuration at: /etc/kapacitor/kapacitor.conf
```
Now it works! It's weird, because I changed the parameters only at this location and did a restart every time. Could there have been indention problems in the tick script, evaluation slack() at the wrong place?

```
Name: nginx_active
Error:
Type: stream
Enabled: true
Executing: true
Databases Retention Policies: ["telegraf"."default"]
TICKscript:
stream
     .from()
       .database('telegraf')
       .measurement('nginx')
    .alert()
	.id('nginx active connections')
        .crit(lambda: "active" > 10)
	.stateChangesOnly()
	.slack()


DOT:
digraph nginx_active {
stream0 -> stream1 [label="0"];
stream1 -> alert2 [label="0"];
}
```

Sorry for this ticket.

**Comment by nathanielc** [comment]
TICKscripts  ignore white space so that's not it but glad you got it working.

**Comment by nathanielc** [comment]
Reopening since another report of similar behavior has shown up.

**Comment by nathanielc** [comment]
This seems similiar to #158

**Comment by nathanielc** [comment]
I think I may have figured out the issue. Were you testing this via record/replay commands?

There was a bug where various alerting services where disabled for replays only. Should be fixed in master.
