### ISSUE TITLE
Setting Slack Channel dynamically

### ISSUE THREAD

**Issue by metroidprototype** [influxdata/kapacitor#1404]
Is dynamically generating the slack channel based on tag or field data not possible? Here's a simplified version of my tick script:
```
stream
    |from()
        .measurement('docker_container_cpu')
        .groupBy('service')
    |window()
        .period(1m)
        .every(1m)
    |alert()
        .message('{{ .Level}}: {{ .Name }}/{{ index .Tags "service" }} has high cpu usage: {{ index .Fields "usage_percent" }}')
        .info(lambda: TRUE)
        .slack()
        .channel('{{ index .Tags "service" }}')
```

However, doing this seems to cause the slack message to silently fail. Nothing in regards to an error is logged, and the message never shows up in the slack channel. The channel in question does exist, and if I manually set the channel to the actual string (i.e. `.channel('test-service')`, it sends out as expected. 

Is my only option here to use a template task? Ideally I would prefer to avoid submitting a vars file for every service we are trying to monitor against.

**Comment by nathanielc** [comment]
The channel option does not support templates currently. While not quite 100% dynamic you can use the alert handlers API to define a slack handler and channel for each service you have. 

Example alert handler definition:
```
kind: slack
match: "service" == 'serviceA'
options:
   channel: serviceA
```

Then in your TICKscript send the alert to a topic instead of directly to slack.

```
stream
    |from()
        .measurement('docker_container_cpu')
        .groupBy('service')
    |window()
        .period(1m)
        .every(1m)
    |alert()
        .message('{{ .Level}}: {{ .Name }}/{{ index .Tags "service" }} has high cpu usage: {{ index .Fields "usage_percent" }}')
        .info(lambda: TRUE)
        .topic('services')
```

Then define a handler on the `services` topic for each service with the appropriate channel.
 See the [API](https://docs.influxdata.com/kapacitor/v1.3/api/api/#alerts) docs and [this](https://docs.influxdata.com/kapacitor/v1.3/guides/using_alert_topics/) guide for more information on using topics and alert handlers.

**Comment by metroidprototype** [comment]
Thanks, I'll have a closer look at the alert handlers API.

**Comment by mvarge** [comment]
Having this feature would be really good, can't we reopen this issue?

**Comment by Puneeth-n** [comment]
This doesn't seem to work for me.

handler
```
topic: nodejs
id: ecs_nodejs_prod
kind: slack
match: changed() == TRUE AND CT_ENVIRONMENT == 'prod'
options:
  channel: '#production_ops'
  username: 'ECS'
  workspace: 'foo.slack.com'
  icon-emoji: ':ghost:'
```

task
```
dbrp "telegraf"."autogen"

var db = 'telegraf'

var rp = 'autogen'

var measurement = 'docker_container_health'

var groupBy = ['CT_SERVICE', 'CT_ENVIRONMENT']

var whereFilter = lambda: ("CT_SERVICE" != 'nlp-api')

var name = 'nodejs'

var idVar = name + ':{{.Group}}'

var message = '{{.ID}} is *{{.Level}}* because of health check failures!!!'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var crit = 0

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "failing_streak")
        .as('value')

var trigger = data
    |alert()
        .crit(lambda: "value" > crit)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .topic('nodejs')

trigger
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

trigger
    |httpOut('output')

```

**Comment by connoranderson** [comment]
> serviceA

Is it possible that this functionality exists now or is it still not implemented? It seems like the "channel" option in the slack alert node would benefit from being able to set this dynamically.

**Comment by connoranderson** [comment]
> The channel option does not support templates currently. While not quite 100% dynamic you can use the alert handlers API to define a slack handler and channel for each service you have.
> 
> Example alert handler definition:
> 
> ```
> kind: slack
> match: "service" == 'serviceA'
> options:
>    channel: serviceA
> ```
> Then in your TICKscript send the alert to a topic instead of directly to slack.
> 
> ```
> stream
>     |from()
>         .measurement('docker_container_cpu')
>         .groupBy('service')
>     |window()
>         .period(1m)
>         .every(1m)
>     |alert()
>         .message('{{ .Level}}: {{ .Name }}/{{ index .Tags "service" }} has high cpu usage: {{ index .Fields "usage_percent" }}')
>         .info(lambda: TRUE)
>         .topic('services')
> ```
> Then define a handler on the `services` topic for each service with the appropriate channel.
> See the [API](https://docs.influxdata.com/kapacitor/v1.3/api/api/#alerts) docs and [this](https://docs.influxdata.com/kapacitor/v1.3/guides/using_alert_topics/) guide for more information on using topics and alert handlers.

Is it possible that this functionality exists now or is it still not implemented? It seems like the "channel" option in the slack alert node would benefit from being able to set this dynamically.
