### ISSUE TITLE
Kapacitor in the InfluxData repo hasn't been updated since 1/24

### ISSUE THREAD

**Issue by austinbutler** [influxdata/kapacitor#1405]
I was surprised to find a fresh install is at 1.2.0.

https://repos.influxdata.com/centos/7Server/amd64/stable/

**Comment by hanej** [comment]
Can we get the latest version pushed out to the repo?

**Comment by nathanielc** [comment]
@austinbutler @hanej The repo is now up-to-date with 1.3.1. Sorry for the delay.
