### ISSUE TITLE
Trouble Defining Multiple InfluxDB Servers

### ISSUE THREAD

**Issue by nhproject** [influxdata/kapacitor#142]
In the [influxdb] section in the configuration file, there's the "urls" variable. I tried to define over there three influxdb machines which I have in my cluster, like this:
```urls = ["SERVER1_URL","SERVER2_URL","SERVER3_URL"]. ```
After that, I restarted the Kapacitor in order to apply it - but nothing happened, it seemed like its stuck, and the log didn't showed the usual messages it always shows.
What can be the reason for that? Should I write the servers in a different way?

**Comment by nathanielc** [comment]
This looks correct to me. Are there any logs at all or does the process just hang when trying to connect?

**Comment by nhproject** [comment]
tail -f /var/log/kapacitor/kapacitor.log - no logs at all.

**Comment by nathanielc** [comment]
@nhproject can you check /var/log/kapacitor/kapacitor.err ? If Kapacitor crashes before it can initialize its logs, the STDERR content gets put there.

**Comment by nhproject** [comment]
panic: reflect: slice index out of range

goroutine 1 [running]:
reflect.Value.Index(0x974a20, 0xc820110950, 0xd7, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:847 +0x151
github.com/BurntSushi/toml.(*MetaData).unifySliceArray(0xc82015b448, 0x972bc0, 0xc82015eb00, 0x57, 0x974a20, 0xc820110950, 0xd7, 0x0, 0x0)
	/gopath/src/github.com/BurntSushi/toml/decode.go:321 +0x12e
github.com/BurntSushi/toml.(*MetaData).unifySlice(0xc82015b448, 0x972bc0, 0xc82015eb00, 0x974a20, 0xc820110950, 0xd7, 0x0, 0x0)
	/gopath/src/github.com/BurntSushi/toml/decode.go:314 +0x253
github.com/BurntSushi/toml.(*MetaData).unify(0xc82015b448, 0x972bc0, 0xc82015eb00, 0x974a20, 0xc820110950, 0xd7, 0x0, 0x0)
	/gopath/src/github.com/BurntSushi/toml/decode.go:206 +0xdf7
github.com/BurntSushi/toml.(*MetaData).unifyStruct(0xc82015b448, 0x988fc0, 0xc82011ee40, 0xb5f3a0, 0xc820110948, 0xd9, 0x0, 0x0)
	/gopath/src/github.com/BurntSushi/toml/decode.go:252 +0x69c
github.com/BurntSushi/toml.(*MetaData).unify(0xc82015b448, 0x988fc0, 0xc82011ee40, 0xb5f3a0, 0xc820110948, 0xd9, 0x0, 0x0)
	/gopath/src/github.com/BurntSushi/toml/decode.go:200 +0xe8f
github.com/BurntSushi/toml.(*MetaData).unifyStruct(0xc82015b448, 0x988fc0, 0xc82011ec90, 0xb809c0, 0xc820110900, 0xd9, 0x0, 0x0)
	/gopath/src/github.com/BurntSushi/toml/decode.go:252 +0x69c
github.com/BurntSushi/toml.(*MetaData).unify(0xc82015b448, 0x988fc0, 0xc82011ec90, 0xb809c0, 0xc820110900, 0xd9, 0x0, 0x0)
	/gopath/src/github.com/BurntSushi/toml/decode.go:200 +0xe8f
github.com/BurntSushi/toml.Decode(0xc82016a000, 0x8af, 0x94d420, 0xc820126048, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/BurntSushi/toml/decode.go:114 +0x1ed
github.com/BurntSushi/toml.DecodeFile(0x7fffbfcc9f1f, 0x1d, 0x94d420, 0xc820126048, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/BurntSushi/toml/decode.go:124 +0x13d
github.com/influxdb/kapacitor/cmd/kapacitord/run.(*Command).ParseConfig(0xc820160000, 0x7fffbfcc9f1f, 0x1d, 0x2e2, 0x0, 0x0)
	/gopath/src/github.com/influxdb/kapacitor/cmd/kapacitord/run/command.go:213 +0x2e8
github.com/influxdb/kapacitor/cmd/kapacitord/run.(*Command).Run(0xc820160000, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
	/gopath/src/github.com/influxdb/kapacitor/cmd/kapacitord/run/command.go:71 +0x1ce
main.(*Main).Run(0xc82015bef0, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
	/gopath/src/github.com/influxdb/kapacitor/cmd/kapacitord/main.go:80 +0x678
main.main()
	/gopath/src/github.com/influxdb/kapacitor/cmd/kapacitord/main.go:41 +0x363

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

**Comment by rossmcdonald** [comment]
I've encountered this same issue when attempting to specify three 0.9.6.1 nodes in the config (not sure if it's 0.9-specific).

**Comment by nathanielc** [comment]
I was looking into this an it turns out to be a bug in the config parser. Should be fixed with #155

**Comment by nhproject** [comment]
thanks Nat!

**Comment by nathanielc** [comment]
Fixed with #268
