### ISSUE TITLE
alerting after threshold has been met for x amount of minutes

### ISSUE THREAD

**Issue by henry-megarry-tr** [influxdata/kapacitor#1427]
We would like to be able to alert after its been failing for certain number of minutes. This is to ignore the momentary spikes. What would the best way about going about this?

**Comment by nathanielc** [comment]
This can easily be done via the use of window nodes and the alert `.all` property. 

Can you send you questions to the community board at [community.influxdata.com](https://community.influxdata.com/) so that we can have this discussion preserved better for others?
