### ISSUE TITLE
[bug] RHEL/Centos 7 package installation fails

### ISSUE THREAD

**Issue by bbczeuz** [influxdata/kapacitor#1428]
...seems to be mainly a packaging problem.

@ maintainer: PLEASE: Other than on the Debian family, on Redhat based Linuxes, installed packages typically do NOT auto-start nor auto-enable themselves (i.e. not creating said links)

### How to reproduce
```
# yum install kapacitor    
[...]
Running transaction
  Installing : kapacitor-1.3.1-1.x86_64                                                                                                                                               1/1 
Created symlink from /etc/systemd/system/kapacitor.service to /usr/lib/systemd/system/kapacitor.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/kapacitor.service to /usr/lib/systemd/system/kapacitor.service.
Failed to execute operation: Too many levels of symbolic links
warning: %posttrans(kapacitor-1.3.1-1.x86_64) scriptlet failed, exit status 1
Non-fatal POSTTRANS scriptlet failure in rpm package kapacitor-1.3.1-1.x86_64
[...]
# systemctl status kapacitor  
● kapacitor.service - Time series data processing engine.
   Loaded: loaded (/usr/lib/systemd/system/kapacitor.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://github.com/influxdb/kapacitor
Warning: kapacitor.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```

### Expected
- No error msg
- Not creating links in `/etc/systemd/system/multi-user.target.wants`. This is somewhere between surprising and evil.
- No manual `systemctl daemon-reload` needed

### Environment
- RHEL 7
- uname `Linux influxdb_test 3.10.0-514.21.1.el7.x86_64 #1 SMP Sat Apr 22 02:41:35 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by nathanielc** [comment]
@bbczeuz Thanks for the detailed report. I agree that this is not correct behavior for RHEL/CentOS systems we will work towards a fix.

**Comment by cocampbe** [comment]
Work around. Delete the link /etc/systemd/system/kapacitor.service. Then enable it via systemd.
