### ISSUE TITLE
Bind Error After Restart

### ISSUE THREAD

**Issue by nhproject** [influxdata/kapacitor#143]
When I start Kapacitor, it created a subscription automatically, and everything works great.
Then, In order to apply new configs (for example), I'm restarting the service.
When restarting, I get the following error:
``` "Failed to set up UDP listener at address.....bind: cannot assign requested address". ```
My workaround for this is stopping Kapacitor, dropping the previous created subscription, and starting Kapacitor again (and it creates a new subscription).
Should it work like that? Or am I doing something not right?

**Comment by nathanielc** [comment]
It definitely should not work like that. 

What OS/Arch are you using?
How did you install it?
How are you restarting the daemon?

**Comment by nhproject** [comment]
I'm using Ubuntu 14.04.
I installed Kapacitor using wget & dpkg (as usual..).
I'm restarting the daemon using "sudo service kapacitor restart".

**Comment by nathanielc** [comment]
Sounds like the kapacitor daemon is still running after you tell it to stop. 

If you run `sudo service kapacitor  stop` and then `ps aux | grep kapacitord` are there any running kapacitor daemons?

If so kill them and try start stoping kapacitor again.

Do you see the log `server shutdown complete` after stopping kapacitor?

**Comment by nhproject** [comment]
I followed your instructions :
I started Kapacitor, it created a subscription automatically.
Then I ran: ``` sudo service kapacitor stop ```
I saw in the log : ``` server shutdown complete ```
and no daemon was running (I ran: ``` ps aux | grep kapacitord ```).

**Comment by nathanielc** [comment]
OK,. so the daemon is stopping correctly.

Is there another process that is still bound to the UDP port? You can use `netstat -nlp` to see a list of process and the ports they listen on.

**Comment by nhproject** [comment]
nope. The UDP port is 38513 and nothing is bound to it.

**Comment by nathanielc** [comment]
Here is the relevant code: 

https://github.com/influxdata/kapacitor/blob/master/services/udp/service.go#L75-L85 

Kapacitor is just trying to listen on the UDP port. If nothing is bound to that port I am not sure what would be causing the error. The port is > 1024 so you shouldn't need any special root privileges, maybe selinux? just a guess...

Is this the literal error you are seeing in the logs `"Failed to set up UDP listener at address.....bind: cannot assign requested address"`? Because that would indicate the `net.ResolveUDPAddr` is returning an invalid result without throwing an error. It should probably read something like `"Failed to set up UDP listener at address [::]:38513: cannot assign requested address"`.

Can you post your config there may be something odd in there?

**Comment by nhproject** [comment]
Sure. There it is:

# The hostname of this node
hostname = $HOSTNAME
# Directory for storing a small amount of metadata about the server.
data_dir = "/var/lib/kapacitor"

[http]
  # HTTP API Server for Kapacitor
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"

[logging]
    # Destination for logs
    file = "/var/log/kapacitor/kapacitor.log"
    level = "INFO"

[replay]
  # Where to store replay files, aka recordings.
  dir = "/var/lib/kapacitor/replay"

[task]
  # Where to store the tasks database
  dir = "/var/lib/kapacitor/tasks"

[influxdb]
  enabled = true
  urls = [$INFLUXDB_URL]
  username = $INFLUXDB_USERNAME
  password = $INFLUXDB_PASSWORD
  timeout = 0
  udp-buffer = 1000
  udp-read-buffer = 0

  [influxdb.subscriptions]
    $DB_NAME = [ $RETENTION_POLICY ]
  [influxdb.excluded-subscriptions]

[slack]
  enabled = true
  url = $SLACK_URL
  channel = $CHANNEL
  global = false

[reporting]
  enabled = true
  url = "https://usage.influxdata.com"

**Comment by nathanielc** [comment]
What is the value of the `$HOSTNAME` var? That could create this problem if its not set/correct.

**Comment by nhproject** [comment]
Its the kapacitor's public ip

**Comment by nathanielc** [comment]
Is this still an issue? I haven't been able to reproduce locally...

**Comment by nhproject** [comment]
Nope.
It shows this error but all is good - The error just mentioning that the address is already binded.
I'm Closing it.
