### ISSUE TITLE
Multiple states on a node

### ISSUE THREAD

**Issue by kamanaPE** [influxdata/kapacitor#1444]
I have a stream monitoring disk space on a number of servers, each with several shares/partitions. My script groups by both host and path.

An alert is triggered onChangeOnly, with defined warn and crit levels. However, the logged alerts suggest  node only has one state to share between all the groups, with the following unwanted consequence:
Even though all separate partitions are stable on their respective states, the fact that they are on different states triggers multiple alerts on each check. 

E.g: 
On first check, kapacitor finds this:
server1/tmp is on warn state - node state is set to warn, alert sent
server1/var is on warn state - node state is unchanged, no alert 
server2/tmp is on crit state - node state is changed to crit, alert sent

On the second check kapacitor finds this:
server1/tmp is on warn state (still) - node state was on crit from server2/tmp on last check, so now changes to warn and sends alert...even though the state of the share is unchanged from last check.

Is it correct that there is only one state per node, or is there a way to have a state for each grouping, for example?

Here is my script, for reference:
```
stream
	// Select disk measurements
	|from().measurement('disk')
	|groupBy('host, path')

	|alert()
		.warn(lambda: "used_percent" > 80)
		.crit(lambda: "used_percent" > 90)
		.id('{{ index .Tags "host"}}{{ index .Tags "path"}}')
		.message('{{ .Level }} level disk space alert at {{ .Time }}: {{ .ID }} is '+
		' {{ index .Fields "used_percent"}}% full.')

		.stateChangesOnly()

		// Log the alert
		.log('/tmp/kapacitor/disk.log')
```

**Comment by nathanielc** [comment]
@kamanaPE Looks like a typo in the groupBy node,

Should be:
```
	|groupBy('host', 'path')
```

**Comment by kamanaPE** [comment]
Thank you for that correction.

Fixing the syntax error changed the behavior of the alerts, presumably to what I had in mind. Does that mean that the alert node is capable of monitoring more than one state? One per grouping?

**Comment by nathanielc** [comment]
Yes, an alert node tracks state per group.
