### ISSUE TITLE
variables in messages and resetting alert level by stateDuration

### ISSUE THREAD

**Issue by kamanaPE** [influxdata/kapacitor#1447]
A couple of things I have been trying to accomplish, but as of yet failed to:

1) When using stateDuration to trigger alerts, I might want to include in the message how long state has been. E.g 
.message(' {{ index .Tags "host" }} has been swapping for X minutes.')
where X is the states duration. Syntaxes I have tried include {{ .state_duration }}, {{ "state_duration" }} etc. None of them led to the desired result.

Is it possible to use names like this in the message? If not, that would be a nice future feature.

2) I have also desired to repeat a stateChangesOnly alert daily, even though the state persists. I have tried e.g. warnReset(lambda: "state_duration" > 24), where 24 is hours, predifined in the stateDuration call. Is it possible to reset warning leves by state duration? If so, what is the correct syntax? If not, that would also be a nice feature. ;)

**Comment by nathanielc** [comment]
@kamanaPE The `state_duration` value is a field so it can be accessed by indexing into the set of fields.

Try `{{index .Fields "state_duration"}}`.

For your second question use `.stateChangesOnly(1d)` which will repeat the alert after 1d has passed even if the state hasn't changed.
