### ISSUE TITLE
Error messages for missing fields which are arguments to functions are not clear.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#1452]
If you call a function in a lambda expression and the field is missing as an argument to the function you get and error message about the function not having a function signature for missing values and no mention of which field is missing is given.

See https://community.influxdata.com/t/kapacitor-shiftnode-and-join-in-stream/1401/2 for an example.

**Comment by desa** [comment]
I agree that the error is super unhelpful, but I'm not exactly sure what the error should be in the  case of

```
|eval(lambda: max("x",float("y")))
```

when "x" is missing or has value of another invalid type.

Should I print out all of the arguments? Maybe something like

```
 E! Cannot call function "max" with args signature ("x": missing, float("y"): float), available signatures are [(float, float)].
```

Or I could get more fine grained and only list the parameters that are invalid. This approach would be more involved.
