### ISSUE TITLE
Alert node crit  overrides

### ISSUE THREAD

**Issue by alparslanuysal** [influxdata/kapacitor#1453]
Hi team, I want to use condition on crit() node, I could not find and info in documentation.
In kapacitor version 1.1 , I was able to chain two crit() node by using
.crit(lambda: "temperature" > max)
.crit(lambda: "temperature" < min)

However, in version 1.3,
.crit(lambda: "temperature" > max)
.crit(lambda: "temperature" < min)

It overrides the above crit() node.What is the best way for OR condition?

**Comment by nathanielc** [comment]
Use 
```
.crit(lambda: "temperature" > max OR "temperature" < min)
```

**Comment by alparslanuysal** [comment]
It worked, thank you so much @nathanielc
