### ISSUE TITLE
Keep track of updates for hosts

### ISSUE THREAD

**Issue by winem** [influxdata/kapacitor#1458]
Hi, 

I want to create a stream task that updates a new series whenever there is a write to any series for a host. 

I tried this in many ways but was not that successful yet (which might be caused by #1457 ). 

In the end I just want to be able to query the new series for "select * from track_hosts where time < now() - 5m" to get a list of "outdated" hosts. 

My most recent tick script I used for my tests: 
```
// fill a measurement with the most recent record of each host
var host_data = stream
    |from()
        .database('host_statistics')
        .retentionPolicy('ninety_days')
        .measurement('cpu')
        .groupBy('host')
    |window()
        .period(1m)
        .every(1m)
    |last('host')
    |default()
        .field('is_obsolete', 0)

host_data
    |influxDBOut()
        .database('host_statistics')
        .retentionPolicy('twentyfour_hours')
        .measurement('track_hosts')
```

I guess there is a better and much smarter approach then my one. How would you handle that? 

Best regards,
Marcel

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the community board at [community.influxdata.com](https://community.influxdata.com/).

**Comment by winem** [comment]
This can be closed. Sorry.
