### ISSUE TITLE
invalid TICKscript: no method or property "topic" on *pipeline.AlertNode

### ISSUE THREAD

**Issue by eqinox76** [influxdata/kapacitor#1469]
Hi all,

first thanks for the great work with influx in general and its nice to see that the alerting side gets some love.

I try to use the new alert topics but even using the default example i get a error as if the feature is not yet implemented. Using the kapacitor-1.3.1.x86_64.rpm package for installation.

$ kapacitor version
> Kapacitor 1.3.1 (git: master 3b5512f7276483326577907803167e4bb213c613)

$ cat test.tick
>stream
>    |from()
>        .measurement('cpu')
>        .groupBy(*)
>    |alert()
>        .warn(lambda: "usage_idle" < 20)
>        .crit(lambda: "usage_idle" < 10)
>        // Send alerts to the `cpu` topic
>        .topic('cpu')

$ kapacitor define cpu_alert -type stream -tick test.tick -dbrp db.rp
> invalid TICKscript: line 9 char 10: no method or property "topic" on *pipeline.AlertNode

Any help what i do wrong?

**Comment by desa** [comment]
@eqinox76 just verified myself that this appears to be working just fine on the version you've specified

Can you run
```
$ curl -I http://<kapacitor_host>:9092/ping
```

and see what the `X-Kapacitor-Version` is.

**Comment by eqinox76** [comment]
Sorry missed the notification and have no longer access to the test system :(
