### ISSUE TITLE
InfluxDbOut as alert provider

### ISSUE THREAD

**Issue by gianarb** [influxdata/kapacitor#1478]
Hello! 

I am interested in storing alerts triggered by kapacitor in InfluxDB, because the number of alerts looks like a  time series and the behavior is interesting. We can get information out of it.

If the number of alerts triggered increases probably we can make proactive actions. I am doing something like this:

```
data
    |alert()
        .id('....')
        .message('....}')
        .details('')
        .crit(lambda: "percent_down" > pager_threshold)
        .critReset(lambda: "percent_down" == 0.0)
        .stateChangesOnly()
        .pagerDuty()

data
    |where(lambda: "percent_down" > pager_threshold)
    |influxDBOut()
        .create()
        .database('potato')
        .measurement('alerts')
        .tag('name', 'watcher-ping')
        .tag('type', 'pager_threshold')
```
I have the same lambda configurated and I am using InfluxDBOut function the second time.
Now in this example, I don't know how to store `critReset` and more in general, I think that a proper InfluxDB alert provider will make my tick script easy to write and maintain.

**Comment by desa** [comment]
@gianarb For reference https://community.influxdata.com/t/linking-custom-kapacitor-tasks-to-chronograf/1394

There are additional methods on the `|alert()` node for adding the alert level and id to data passing through a tickscript. Those methods are `IdField`, `IdTag`, `LevelField`, and `LevelTag`.

The following should do what you want
```
data
    |alert()
        .id('....')
        .message('....}')
        .details('')
        .crit(lambda: "percent_down" > pager_threshold)
        .critReset(lambda: "percent_down" == 0.0)
        .stateChangesOnly()
        .pagerDuty()
        .IdTag()
        .LevelTag()
    |influxDBOut()
        .create()
        .database('potato')
        .measurement('alerts')
        .tag('name', 'watcher-ping')
        .tag('type', 'pager_threshold')
```

**Comment by gianarb** [comment]
Thanks a o lot!
