### ISSUE TITLE
count for threshold cpu usage in a moving window

### ISSUE THREAD

**Issue by rjshrjndrn** [influxdata/kapacitor#1486]
Hi,
I just started kapacitor and tick. It seems to be a powerful tool.

I am trying to count the threshold cpu usage, say >80% for a window of 5 mins and every 2mins.
I am not able to figure out how to reduce the count from the emitted 2 min window.
I just want to count in my active window.

my tick is

var curr = stream
    |from()
         .measurement('cpu_usage')
    |window()
        .period(5m)
        .every(2m)
        .align()
// here i want the count to happen
//if usage > 80: count += 1 
    |alert()
        .crit(lambda: "count" > 5 )
        .log('/tmp/alerts.log')

**Comment by IgorGrizzzly** [comment]
Answer: Here is what you need:
After your .window() node evaluate your expression for every point with .eval() into either 1 or 0, then sum up 1s in the next step:

    |eval(lambda: if ("value" >= 8, 1, 0))  // check individual point
        .as('crit')
    |sum('crit') // count number of bad points
        .as('sm')
    |alert()
        .crit(lambda: "sm" >= 2) // alert on 2 bad points per window
