### ISSUE TITLE
Set up/reference Fields via vars to reuse them on all nodes

### ISSUE THREAD

**Issue by sbengo** [influxdata/kapacitor#1511]
Hi,

EDIT: Using Kapacitor 1.3.0

I'm playing with Kapacitor and trying to set up some alerts with stream and batch modes.
I'm trying to set up all params on a TICK script, but it's hard to define a field name on param and be reusable on lambda or other expressions:

- Its an easy way to set up a field name and use it on all expressions which can be part of?

The following table shows the different test I have done with field var definition and where it is used on:

Definition | Lamda | Select | InfluxQLNode
-----------|----------|----------|-------
|Used on --> | `.info(lambda: field > threshold)`| `query('SELECT "' + field + '" FROM ... `|`mean(field)`
||||
`var field = "myField"` | `Error: invalid TICKscript: unsupported literal type *ast.ReferenceNode` |`Error: invalid TICKscript: unsupported literal type *ast.ReferenceNode`|`cannot assign *ast.ReferenceNode to type string, did you use double quotes instead of single quotes?`
`var field = lambda: ("myField") `|`OK`|`invalid TICKscript: name "myField" is undefined. Names in scope:`|`error calling func "mean" on obj *pipeline.QueryNode: reflect: Call using *ast.LambdaNode as type string`
`var field = 'myField'`|`NOOK: It is using literal 'myField' value `|`OK`|`OK`
 
So with above results,  the only  workaround is set up 2 vars:
1. `var field = lambda: ("myField")` for lambda expressions
2. `var field_lit = 'myField'` for other nodes

**Comment by desa** [comment]
@sbengo This is a really good write up of the a common thing people bring up about tickscript. The fundamental issue is that sometimes some nodes use string values (`'`) and lambdas use references (`"`).

**Comment by sbengo** [comment]
Hi @desa , thanks for answering.

So, there is no actually a way to set up a single var that fills for lambda expressions, select and influxql right?

I would ask you to add more info in documentation about setting up vars depending on what node is used!

Thanks for all,
Regards!

**Comment by desa** [comment]
> So, there is no actually a way to set up a single var that fills for lambda expressions, select and influxql right?

Unfortunately there is not

> I would ask you to add more info in documentation about setting up vars depending on what node is used!

Great suggestion. I'm going to close this issue in favor of https://github.com/influxdata/docs.influxdata.com/issues/1238 on the documentation repository.
