### ISSUE TITLE
Minor annoyance with autocomplete

### ISSUE THREAD

**Issue by skuxy** [influxdata/kapacitor#1521]
Hi,

when some task has a somewhat lengthy name, auto-completion by pressing tab sometimes appends task type to its name. I.e. 

som -> <tab> -> some_task

ano -> <tab> -> anothertaskwithlongernamebatch (instead of anothertaskwithlongername)

I use Kapacitor 1.0.0, is this fixed in some later version? Thanks a lot!

**Comment by desa** [comment]
@skuxy Thanks for reporting the issue. What OS are you using?

Also, I'd definitely try upgrading to see if that resolves the issue.

**Comment by skuxy** [comment]
Hi, sorry for the delay, slipped this notification.

OS is CentOS release 6.7, upgrading is not possible at the moment, but perhaps in a couple of weeks. Will try it on local machine

**Comment by skuxy** [comment]
I do think I should clean this one for you guys, sorry
