### ISSUE TITLE
E! invalid math operator / for type missing

### ISSUE THREAD

**Issue by ricohomewood** [influxdata/kapacitor#1523]
I'm getting a strange error when running a TICKscript that is just getting an error rate across a series.

My setup:
InfluxDB: version: 1.3.3
Kapacitor: 1.3.2 (git: HEAD 2b6a049e5b9dc7d7e8d58a8bbde8d186dc8543e3)

Kapacitor.log is showing the following on a eval node:

[error_percent:eval5] 2017/08/16 12:50:30 E! invalid math operator / for type missing
[error_percent:eval5] 2017/08/16 12:50:30 E! invalid math operator / for type missing
[error_percent:eval5] 2017/08/16 12:50:30 E! invalid math operator / for type missing
[error_percent:eval5] 2017/08/16 12:50:30 E! invalid math operator / for type missing

The tickscript is configured as:

var errors = stream
    |from()
        .measurement('errors')
        .groupBy(*)

var requests = stream
    |from()
        .measurement('requests')
        .groupBy(*)

errors
    |join(requests)
        .as('errors', 'requests')
        .tolerance(1s)
        .fill(0.0)
        .streamName('error_rate')

|eval(lambda: "errors.value" / "requests.value")
        .as('rate')

|influxDBOut()
        .measurement('error_percent')

So looks like is not recognising the / in the eval stream but this looks correct to me?

**Comment by ricohomewood** [comment]
looks like this issue was related to how the values are being sent to influxdb

**Comment by Atmozfears** [comment]
Did you find the solution on it?

**Comment by Atmozfears** [comment]
I got the same issue.
How did you solve?
