### ISSUE TITLE
[Feature Request] Lookahead mode for Derivative node.

### ISSUE THREAD

**Issue by SamuelToh** [influxdata/kapacitor#1559]
Based on the Derivative documentation found [here](https://docs.influxdata.com/kapacitor/v1.3/nodes/derivative_node/). The default behaviour for the node is that the result is calculated based on the current point value _less_ the previous point value. 

**Quote:**

> 
> Computes the derivative via: (current - previous ) / ( time_difference / unit)
> 
> The derivative is computed for each point, and because of boundary conditions the first point is dropped.
> 

I see this behaviour as a "lookbehind" mode. While this addresses most of the standard use cases but not for point values that are cumulative (gets bigger overtime). 

For instance let say I have a measurement call "Energy consumption", which is an energy counter and it has the following points below;

- Timestamp: 1 Jan 2017 Value: 100

- Timestamp: 1 Jan 2018 Value: 2000

- Timestamp: 1 Jan 2019 Value: 7000

My use case is, I would like to find the overall energy usage for the year 2018. 

One strategy to tickle this problem would be to use the Derivative node. By default, the derivative node would tell me that the usage for 2018 is **1900** because;

`Point["Date: 1 Jan 2018"].Value - Point["Date: 1 Jan 2017"].Value = 1900 (2000 - 100).`  

This isn't correct because the energy consumption for year 2018 should be **5000** instead. Taking 2019.value of 7000 less 2018.value of 2000.

That is, to solve my problem it seems like I'll need another form of derivative which looks ahead in time VS the default look behind.

Hence the documentation for it can be; 

> 
> Computes the derivative via: (next - current) / ( time_difference / unit)
> 
> The derivative is computed for each point, and because of boundary conditions the last point is dropped.
> 

I am proposing a new property call **mode** for the Derivative node. By default it looks behind but users may specify the value of 'lookahead' in property mode(...) to go the opposite direction.

Please advise if this is a valid solution for my problem. If it is then I won't mind getting my hands dirty to implement it. 

Also, will be great if someone can assess the change scope to see if it is possible at the moment.

Thanks!

**Comment by phemmer** [comment]
Have you tried it?
Works fine for me:

```
> insert energy value=100i 1483228800000000000
> insert energy value=2000i 1514764800000000000
> insert energy value=7000i 1546300800000000000
> select derivative(value,365d) from energy where time >= '2017-01-01T00:00:00Z' and time <= '2019-01-01T00:00:00Z'
name: energy
time                 derivative
----                 ----------
2019-01-01T00:00:00Z 3450
2018-01-01T00:00:00Z 5000
```

**Comment by SamuelToh** [comment]
@phemmer Thanks a lot for looking into my issue. A few things here;

Firstly ->

Quote:

> I just noticed, 2019 looks weird.

Yeah indeed. The point value for year 2019 should be dropped because there is no way you can calculate its usage until the point data for year 2020 is written to the measurement. 

This is reflected in my "lookahead" derivative proposal above.

*Quote from my proposal:*
The derivative is computed for each point, and because of boundary conditions the last point is dropped.


Secondary ->

Assuming the Influxql is correct, specifying unit = 365d can be a bad idea as it does not carter for **leap** years which occurs once every 4 years.

Thirdly ->

The proposal is an enhancement for the Kapacitor's Derivative node rather than InfluxQL. Note the difference between influxQL's derivative vs Kapacitor's derivative node. As highlighted in the documentation, the node's implementation is independent to the normal InfluxQL function.

**Comment by SamuelToh** [comment]
@nathanielc @desa 

Just pinging to see if you guys have any opinion on this? This has been a show stopper for our project.

**Comment by desa** [comment]
I think it makes sense. I think a [similar issue on the InfluxDB repo](https://github.com/influxdata/influxdb/issues/7738). I think it makes sense to have implementations for forward, central, and backwards differences. Though I'm not 100% certain what a central difference would look like here.

**Comment by SamuelToh** [comment]
Thanks everyone for looking into this. I believe we may have found a workaround for it using the `Shift` node.

A little bit of creative programming here. We first use the derivative node to do the calc, then we shift the results backwards by a certain interval (duration) to correct the calculation.

That is, using the same dataset.

- Timestamp: 1 Jan 2017 Value: 100

- Timestamp: 1 Jan 2018 Value: 2000

- Timestamp: 1 Jan 2019 Value: 7000

The derivative node would give us...

- 2018 usage = 1900

Obviously incorrect but we can shift the 2018 result back a year and make it look like `2017 usage = 1900` instead. I'm not sure if the shift node could actually do `-1y` but my actual use case don't require years but minutes instead. So we are all good now.

Many thanks to everybodys' contribution.
