### ISSUE TITLE
[Feature Request] Adding the .quiet() property to all node types and making it more configurable 

### ISSUE THREAD

**Issue by oplehto** [influxdata/kapacitor#1561]
The eval node has a .quiet() property which is very useful for supressing errors and warnings that we don't necessarily care about. It would be great if more, or even all, node types would offer this functionality. 

Ideally I'd like even with more control over which log level messages get supressed and possibly a lambda expression to supress specific errors. For example, we might want DerivativeNode to supress just the "0 time difference" errors but nothing else.

**Comment by rbetts** [comment]
@nathanielc Can we scope this for effort / feasibility?

**Comment by oplehto** [comment]
Yeah. Having a .quiet() propety and some parameter to adjust the verbosity (like a list of errors) would be sufficient. Fair point about the lambda expressions.

**Comment by russorat** [comment]
A trivial example: We process a measurement where a certain field is not always defined. We want to supress the error that results in a node failing to process that field if it is undefined. We could start adding default nodes but that can become really convoluted. Just having kapacitor drop the problematic line to the floor *quietly* would be the preferred option.
I've hit situations several times where I've found myself trying doing extra work with a script just to supress the error messages while the script itself is already working properly
