### ISSUE TITLE
Have Kapacitor ONLY when alert has passed threshold specified in lambda function

### ISSUE THREAD

**Issue by Nav31** [influxdata/kapacitor#1567]
The following TICKSCRIPT causes data to be sent to an HTTP endpoint and written to the log file, even when the value of a metric being streamed is not greater than what is specified in the lambda function.
Example, lets say I want to write to a log file, and an HTTP endpoint when the value of some metric (os.cpu) is greater than 11.  I am seeing data being written to the log file where the value is signficantly below 11 (5.5, etc...).
  
Essentially, I would only like data to be written to the log file, and sent to the HTTP endpoint when the value of a metric **equals** or **exceeds** what is specified in the lambda function.    

This is my TICKSCRIPT: 
```
    stream
            |from() 
                .measurement('os.cpu')
                .where(lambda: "client_key" == 'some_client_key' AND "host" == 'some_host_name')
            |alert()        
                .crit(lambda: "value" >  11)        
                .log('/tmp/alerts_auto_2.log')
                .post('http://example.com/some/end_point')
```

**Comment by Nav31** [comment]
Also, in the documentation, I have seen `StateChangesOnly`.  This is a bit of an improvement, however, it would still alert when the state went from Critical back down to OK.  Where as I am **only** looking for an alert when state is changed to critical by exceeding value in lambda function.  
Please correct me if I am wrong.  Any help will be greatly appreciated!

**Comment by desa** [comment]
@Nav31 If I understand correctly, you just don't want `OK` alerts. You'd like to only be notified on non-OK level alerts?

**Comment by Nav31** [comment]
@desa exactly, that is correct.

**Comment by desa** [comment]
This should currently be possible using `alert topics`, specifically using [match conditions](http://docs.influxdata.com/kapacitor/v1.3/guides/using_alert_topics/#match-conditions). It'll look something like

```
kind: post
match: level() == CRITICAL
options:
  url: 'http://example.com/some/end_point'
```

Let me know if that doesn't work. I'm going to close the issue for the time being. If it turns out that the behavior isn't sufficient I'll reopen it.

**Comment by Nav31** [comment]
@desa thanks a lot! I will look into that ASAP.
