### ISSUE TITLE
HTTP Post endpoints with custom HTTP Body

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#1568]
The HTTP Post Node should allow for the body to be customizable. This way Kapacitor will be able to inter-operate with many different systems since the body can be customized. 

Proposal:

* Add a `template` option to an httppost endpoint configuration that contains a Go template.
 Use a similar structure to alert messages to populate data for the template evaluation step.
* Add a `template_file` option which lets you define a template via an absolute file path instead of placing the template directly in the configuration.

@desa Thoughts?

**Comment by desa** [comment]
sounds good to me.

**Comment by dali20022** [comment]
Hi,

Any news for this proposition please ?

Thanks
