### ISSUE TITLE
Kapacitor REST API authentication

### ISSUE THREAD

**Issue by pootzko** [influxdata/kapacitor#157]
Hi,

does Kapacitor support authentication? As far as I can see, 0.2.4 doesn't, though I might be wrong. Do you think it will in the future? 

Also, do you have a rough estimate about when v0.10.0 might come out? Is it still scheduled for this month? :)

Thanks

**Comment by nathanielc** [comment]
Currently there is no authentication on the API. Yes it will be coming.

As for the 0.10.0 release I cut the v0.10.0-rc1 yesterday and expect the final release in the next week or so.

**Comment by pootzko** [comment]
Great, thanks for the response. Do you have an idea of how far away it is? Near, further future? I guess we'll be able to lock the REST API by api for now, but I'm still curious.

Thanks.
