### ISSUE TITLE
how to change tag value using regex

### ISSUE THREAD

**Issue by peaksnail** [influxdata/kapacitor#1570]
Hi，
I have a tick like that

batch
	|query('''
		SELECT distinct("uid") AS uid  FROM measurement
		WHERE "source" = 'project_name'
	''')
		.period(1h)
		.every(1h)
		.align()
		.groupBy(time(1h), 'version')

I want to get the version distribution info.And the version info like x.x.x.date.

Now ,I want change the version to x.x.x that filter date  using regex or some other way.

Is there any way to get it?

thanks

**Comment by desa** [comment]
@peaksnail we reserve issues for bug reports and feature requests. Please ask your question at https://community.influxdata.com/
