### ISSUE TITLE
pagerDuty not enabled error

### ISSUE THREAD

**Issue by kisienya** [influxdata/kapacitor#158]
Hi,
Many thanks for this very useful tool. 
I am trying to alert to pager duty.
My kapacitor.conf looks as follows:
############################################
[pagerduty]
  enabled = true
  url = "https://events.pagerduty.com/generic/2010-04-15/create_event.json"
  service-key = "xxxxxxxxxxxxxxxx"
  global = false
############################################
My Tick file looks as follows
#############################################
.alert()
       .pagerDuty()
       .email()
#############################################
My email alerts work perfectly. 
PagerDuty error is "E! failed to send PagerDuty alert. PagerDuty is not enabled"

What am I doing wrong?

Thanks

**Comment by nathanielc** [comment]
Your config looks correct. The only thing I can think of is that Kapacitor didn't get restarted after the config change.

**Comment by kisienya** [comment]
Thanks for the reply

The strange thing is that, I have restarted the server, but I still get the error.

Any ideas....

**Comment by nathanielc** [comment]
Could you put together a simple script that can reproduce the issue? Maybe there is a weird edge case in how each of us are doing it. Thanks

**Comment by kisienya** [comment]
.from().measurement('cpu_usage_idle')
    .alert()
        .crit(lambda: "value" < 90)
        .pagerDuty()
        .email()
################################################
Testing both pagerduty and email. Email works well.

**Comment by nathanielc** [comment]
I think I may have figured out the issue. Were you testing this via record/replay commands?

There was a bug where various alerting services where disabled for replays only. Should be fixed in master.

**Comment by kisienya** [comment]
Thanks for the response.Yes I was testing via record /replay commands.

Kindly explain what you mean by "should be fixed in master ".

**Comment by nathanielc** [comment]
By 'fixed in master' I mean the master branch of the code has the fix already but it has not been cut for a release. I am cutting the 0.10.1 release today so you can upgrade and it will be fixed.

**Comment by kisienya** [comment]
Hi,

Thanks,

Kindly shoot me a note when you have cut the release.

Truly appreciate.

**Comment by nathanielc** [comment]
I cut the release, the downloads page has the updated links. https://influxdata.com/downloads/

**Comment by kisienya** [comment]
Many, many thanks. Let me have a look

**Comment by kisienya** [comment]
its now working many thanks.
