### ISSUE TITLE
Accessing a record from outside window and add it to the data

### ISSUE THREAD

**Issue by programmer-pragmatic** [influxdata/kapacitor#1582]
Hi,

I need to run a batch per hour and if values are missing at the start of the hour, I need to fetch the previous value (which will be out of current window) and add it to current window resultset.

For ex, If tickscript is working on 9 AM to 10 AM window, and it does not find any row @9:00 AM exact, it will fetch the last values (which might came at 8:30) and add this to current resultset for 9:00AM.

for instance, it it find following value in this window:

9:30 power: 40
9:45 power: 60
10:00 power: 40

It will access the value came before 9:30 and add it to result set (with time 9:00):

9:00 power:20
9:30 power: 40
9:45 power: 60
10:00 power: 40

**Comment by desa** [comment]
@programmer-pragmatic we reserve issues for bug reports and feature requests. Please ask your question at https://community.influxdata.com/
