### ISSUE TITLE
system-load | wrong measurement

### ISSUE THREAD

**Issue by JanDevDE** [influxdata/kapacitor#1594]
I'll create this issue on chronograf and kapacitor, because I don't know to which one it fits better.

So I created an alert which sends an alarm to Telegram if the system-load is greater than 0.8.
It works, but if the system is on complete idle it's getting strange. As you can see below, I get completely wrong measurements in the alarm. (And it spams it.)

Normal:

System Alert:nil is CRITICAL value: 0.81
System Alert:nil is OK value: 0.06

Issue on idling for some minutes:

 System Alert:nil is CRITICAL value: 0.9
 System Alert:nil is OK value: 0
 System Alert:nil is CRITICAL value: 0.91
 System Alert:nil is OK value: 0
 System Alert:nil is CRITICAL value: 0.91
 System Alert:nil is OK value: 0
 System Alert:nil is CRITICAL value: 1.07
 System Alert:nil is OK value: 0
 System Alert:nil is CRITICAL value: 1.06
 System Alert:nil is OK value: 0
 System Alert:nil is CRITICAL value: 1.04
 System Alert:nil is OK value: 0
 System Alert:nil is CRITICAL value: 1.03
 System Alert:nil is OK value: 0

**Comment by desa** [comment]
@JanDevDE can you supply `kapacitor show <task name>` for the task in question.

**Comment by JanDevDE** [comment]
This was sadly just a company project which is now over so I can't provide any more details. <Closed>
