### ISSUE TITLE
panic: ... SIGSEGV: segmentation violation code

### ISSUE THREAD

**Issue by DaveBender** [influxdata/kapacitor#1595]
kapacitor is crashing with the error below, a segmentation violation.   Is there a way to debug where that's coming from?  The **.(*InfluxQLNode** reference makes it looks like a TICKscript error, but how can we determine which script is causing the problem, and, within that script (if that's the underlying cause), which line or variable is at fault?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0xa07575]

goroutine 9365 [running]:
github.com/influxdata/kapacitor.(*InfluxQLNode).runStreamInfluxQL(0xc428800200, 0xc4229b3200, 0xc420018000)
        /home/ec2-user/go/src/github.com/influxdata/kapacitor/influxql.go:106 +0xe05
github.com/influxdata/kapacitor.(*InfluxQLNode).runInfluxQLs(0xc428800200, 0x0, 0x0, 0x0, 0xc428936f78, 0xc4229b3200)
        /home/ec2-user/go/src/github.com/influxdata/kapacitor/influxql.go:43 +0x115
github.com/influxdata/kapacitor.(*InfluxQLNode).(github.com/influxdata/kapacitor.runInfluxQLs)-fm(0x0, 0x0, 0x0, 0xc428936fa0, 0x3d64695f65636e61)
        /home/ec2-user/go/src/github.com/influxdata/kapacitor/influxql.go:36 +0x48
github.com/influxdata/kapacitor.(*node).start.func1(0xc428800200, 0x0, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/influxdata/kapacitor/node.go:140 +0x8e
created by github.com/influxdata/kapacitor.(*node).start
        /home/ec2-user/go/src/github.com/influxdata/kapacitor/node.go:141 +0x5d

```

**Comment by desa** [comment]
@DaveBender Can you supply the associated tickscript and any other data that can be used to reproduce this.

**Comment by DaveBender** [comment]
The segmentation violation happened when the script hit a divide-by-zero error determining the error rate with `errors/total`.  During a slow spell, there were no records, so `total` was zero.  I corrected it by adding 1 to `total`, which is not elegant but gets around the problem.

```
|eval(lambda: float("totalErrors.count") / float("totals.count" + 1)  )
                .as('rate')
                .keep()

```

I was wondering, though, how to connect the stack trace to the script causing the problem.  Does the `goroutine 9365 ` equate to anything humanly followable? 

I was also wondering whether there's a way to isolate the TICKscripts so they don't bring down Kapacitor.

**Comment by desa** [comment]
@DaveBender From what I can tell, it doesn't appear to be an issue with the `eval` node, but rather an issue with the `influxQL` node.

Would it be possible to get the entire tickscript you're using and any associated line-protocol data that you think will help reproduce it.

**Comment by desa** [comment]
@DaveBender Just stated to investigate this a bit more, and from looking at the stack-trace, it looks like somehow, there is a point that does not contain any fields

https://github.com/influxdata/kapacitor/blob/v1.3.3/influxql.go#L106
```go
			f, exists := p.Fields[c.field]
```

having an example tickscript that can reproduce this as well as any sample data would go a long way in helping us fully diagnose the issue.
