### ISSUE TITLE
Chronograf Alert Count

### ISSUE THREAD

**Issue by dishmael** [influxdata/kapacitor#1596]
Chronograf is not reflecting the correct alert count for Kapacitor TICK scripts loaded from the command line.  It seems that Chronograf is only counting alerts that were created through the UI.

**Comment by desa** [comment]
@dishmael I think this may be intended behavior. Could you repost this issue in https://community.influxdata.com/ until we can establish that there is actually an issue?

**Comment by dishmael** [comment]
I did raise that as an [issue](https://community.influxdata.com/t/alert-count-not-updating/2486) on InfluxData's community and they said to raise it as a bug here.

How could that be "intended behavior"?  Chronograf should be showing the count for alerts that were created in the UI as well as from the command like via Kapacitor.  This seems like a bug to me.

**Comment by desa** [comment]
@dishmael I've responded on community.
