### ISSUE TITLE
kapacitor alerts to onpremise hipchat

### ISSUE THREAD

**Issue by venkyrprabhu** [influxdata/kapacitor#1602]
Hi,

Kapacitor provides configuration option to only update subdomain for hipchat.   Any reason why the entire hipchat url cannot be configured.  
We have an on-premise hipchat and the endpoint is not in this format - https://<subdomain>.hipchat.com

Thanks
Venky

**Comment by oplehto** [comment]
I'm using Kapacitor (1.3.0) with an on-prem hipchat and simply pointing the url config parameter to our hipchat server works fine:
`url = "https://myhipchatserver.mydomain.com/v2/room"`

**Comment by venkyrprabhu** [comment]
Thanks @oplehto , i think i was having something funny going on with chronograf overriding the subdomain over kapacitor's url config.

**Comment by brianbaker** [comment]
FYI - https://github.com/influxdata/chronograf/issues/1506

**Comment by perzizzle** [comment]
Was anyone able to sort this out? I'm on kapacitor-1.4.1-1.x86_64 have the url configured in the kapacitor.conf file and the web ui is empty. When I generate an alert in the logs I can see:

2018-03-21T15:43:41.408-05:00 lvl=error msg="failed to send event to Alerta" service=hipchat handler=hipchat topic=system err="Post https://.hipchat.com/v2/room/influx-notifications/notification?auth_token=redacted: dial tcp: lookup .hipchat.com: no such host"

**Comment by xxwassyxx** [comment]
I'm getting a similar experience
