### ISSUE TITLE
How to use stream with data from telegraf 0.10.x?

### ISSUE THREAD

**Issue by UnderGreen** [influxdata/kapacitor#161]
For now, I think stream processing does't  work, because we have measurements with fields.
And I did't find in documentation and code how it possible to work with these data.

**Comment by nhproject** [comment]
You can, I succeeded to work with it.

If, for example, you had:
```.from().measurement('cpu_usage_idle')```
and
```.mapReduce(influxql.last('value'))```
Now you just need to change it to:
```.from().measurement('cpu')```
and
```.mapReduce(influxql.last('usage_idle'))```

**Comment by UnderGreen** [comment]
Thank you!
