### ISSUE TITLE
Difference between enable and reload

### ISSUE THREAD

**Issue by pootzko** [influxdata/kapacitor#162]
Hi, 

could you please tell me what is the difference between `enable` and `reload`? I see that they both hit the "enable" REST API endpoint but I can't see if there's any difference in the request body. Do they do something different logically? And if yes, what's different that's being sent through the body?

Thanks

**Comment by nathanielc** [comment]
The only difference is that `reload` also disables the task first. Reload is essentially an alias to:

```sh
kapacitor disable task_name && kapacitor enable task_name
```

The `enable` action is idempotent meaning that if the task is already enabled it will do nothing. In order to *reload* a running task it must first be disabled before being enabled again.

**Comment by pootzko** [comment]
Oh ok, thought there would be a small catch like that. Thanks.
