### ISSUE TITLE
"define-topic-handler" match is not work

### ISSUE THREAD

**Issue by wing731** [influxdata/kapacitor#1621]
kapacitor version: v1.3.3

kind: smtp
match: "host" == 's001.example.com'
options:
    to:
       - aaa@example.com

`kapacitor define-topic-handler base_sys_fs smtp_dba halder/smtp_dba.yaml 
failed to unmarshal yaml handler file "halder/smtp_dba.yaml": error converting YAML to JSON: yaml: line 1: did not find expected key`

if i remove the the match rule, it works fine.

**Comment by 2solt** [comment]
@wing371
It works for me like:
`match: \"host\" == 's001.example.com'`

**Comment by wing731** [comment]
@2solt 
It's not works for me ...

Your kapacitor version ?

kind: smtp
match: \"host\" == 's001.example.com'
options:
    to:
         -- aaa@example.com


kapacitor define-topic-handler base_sys_fs smtp_dba halder/smtp_dba.yaml

failed to create handler: invalid match expression: parser: unexpected unknown state, last char: '\\' line 1 char 1 in "\"host\" =". expected: "number","string","duration","identifier","TRUE","FALSE","==","(","-","!"

**Comment by 2solt** [comment]
`Kapacitor 1.3.3 (git: HEAD ce586f35e89e75a1779e2b493caba15d66295a15)`
Yeah, sorry its:
`match: "\"host\" == 's001.example.com'"`

**Comment by wing731** [comment]
Thanks, it works

**Comment by connoranderson** [comment]
I believe this should be updated in the documentation on the following page:

https://docs.influxdata.com/kapacitor/v1.5/working/alerts/#match-expressions
