### ISSUE TITLE
Missing 1.3.3 RPM in yum repo

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/kapacitor#1624]
Kapacitor 1.3.3 was released 2017/08/11 but the [official repo](https://repos.influxdata.com/rhel/7/x86_64/stable/?C=M;O=D) still does not have the rpm.

**Comment by austinbutler** [comment]
And the [download page](https://portal.influxdata.com/downloads) is even further behind (1.3.1).

**Comment by rakshit-jain** [comment]
Facing the same issue. Unable to install kapacitor using yum

**Comment by desa** [comment]
Can you confirm that this is still an issue?

**Comment by adrianlzt** [comment]
Now it is in place: https://repos.influxdata.com/rhel/7/x86_64/stable/kapacitor-1.3.3.x86_64.rpm

Thanks!

**Comment by rakshit-jain** [comment]
Thanks for the support. Issue is resolved
Regards 

Rakshit Jain +91-9999429474 

    On Monday, October 30, 2017, 11:24:44 PM GMT+5:30, Michael Desa <notifications@github.com> wrote:  
 
 
Can you confirm that this is still an issue?
