### ISSUE TITLE
kapacitor.service file has bug

### ISSUE THREAD

**Issue by lfarkas** [influxdata/kapacitor#1626]
currently in kapacitor.service the last line:
Alias=kapacitor.service
which cause error on all update since kapacitor reference itself which is nonsense. this line should have to be deleted!
```
Failed to execute operation: Too many levels of symbolic links
warning: %post(kapacitor-1.3.2-1.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package kapacitor-1.3.2-1.x86_64
```

**Comment by lfarkas** [comment]
no one care about it

**Comment by davidby-influx** [comment]
I don't see the line you want to have removed: https://github.com/influxdata/kapacitor/blob/master/scripts/kapacitor.service

Is there a different file to which you are referring?  Can you provide a link to it in our repo?

**Comment by lfarkas** [comment]
already fixed
