### ISSUE TITLE
Feature Request: Indicate whether an alert is auto-recovering or not in the alert JSON output

### ISSUE THREAD

**Issue by oplehto** [influxdata/kapacitor#1627]
It would be useful to have an indication if NoRecoveries is set in the alert JSON output. 

In my use case this will be used by custom monitoring system (via the exec handler) to display to the user whether a given alert will auto-recover or need to be manually acknowleged. We have a mix of both types of alerts.

**Comment by desa** [comment]
@oplehto Sorry about the delayed response to this.

Seems like a reasonable request to me. I'll get on this ASAP.

**Comment by nathanielc** [comment]
Fixed by #1828
