### ISSUE TITLE
JSON sent to programs/scripts to be executed via exec property modified slightly

### ISSUE THREAD

**Issue by skuxy** [influxdata/kapacitor#1638]
Before we had: 

```
{"id":"some_id","message":"some_message","details":"some_details","time":"2017-10-25T00:00:00Z","duration":0,"level":"INFO","data":{"series":[{"name":"measurement_name","tags":{"some_tag":"some_tag_value"},"columns":["time","count"],"values":[["2017-10-25T00:00:00Z",399]]}],"Messages":null,"Err":null}}
```

This changed slightly to:
```
{"id":"some_id","message":"some_message","details":"some_details","time":"2017-10-25T00:00:00Z","duration":0,"level":"INFO","data":{"Series":[{"name":"measurement_name","tags":{"some_tag":"some_tag_value"},"columns":["time","count"],"values":[["2017-10-25T00:00:00Z",399]]}],"Messages":null,"Err":null}}
```
That is, "series" under "data" field changed to "Series", which made some shell scripts triggered by our ticks to not work properly, due to them extracting tags buried inside those "series". 

We fixed that problem, but I've just wanted to know how it came to this change? I've skimmed changelog and noticed nothing related to this change. 
Additionally, if there is preferred way to get the same result, please enlighten me :)

Thanks!

**Comment by phemmer** [comment]
What version did you upgrade from/to? We got bit by this same issue around 8 months ago. The name changed from `series` to `Series` and then back to `series` again. Broke our alerting each time :-(

See https://github.com/influxdata/kapacitor/commit/8ed20f124651557db7e099c0f2f8ac30ed372cbb#diff-bd7f9bc9538b2728f328cfbbeaf9b0a0R9

**Comment by SrikarshVardhan** [comment]
We are facing this issue https://github.com/influxdata/kapacitor/issues/1639

**Comment by skuxy** [comment]
Hey @phemmer , we've went from v1.0 to v1.2 when our ticks got rowdy-ish. I guess transition to v1.3 will revert to old state (thus breaking scripts again)?

**Comment by nathanielc** [comment]
@skuxy @phemmer You are right the `series` key changed. It was always supposed to be `series` and it was accedentially changed to `Series`. We reverted the change and added tests around it to ensure that doesn't happen again. Sorry for the trouble of having to deal with this. If you update to >= 1.3, the key will be `series`.

Relevent note from the CHANGELOG:

>#1199: BREAKING: Fix inconsistency with JSON data from alerts. The alert handlers Alerta, Log, OpsGenie, PagerDuty, Post and VictorOps allow extra opaque data to be attached to alert notifications. That opaque data was inconsistent and this change fixes that. Depending on how that data was consumed this could result in a breaking change, since the original behavior was inconsistent we decided it would be best to fix the issue now and make it consistent for all future builds. Specifically in the JSON result data the old key Series is always series, and the old key Err is now always error instead of for only some of the outputs.

**Comment by skuxy** [comment]
@nathanielc thnx for the warning! We'll keep this in mind for the next upgrade.
