### ISSUE TITLE
Problem with patching the script

### ISSUE THREAD

**Issue by SrikarshVardhan** [influxdata/kapacitor#1639]
We are trying to patch this
"script": "batch\n    |query('''\n            SELECT count(response_time) as count\n            from \"sdp_monitoring\".\"13m\".\"net_response\"\n            where \"type\" = 'kafka'\n            ''')\n        .groupBy('cluster', 'host')\n        .period(45s)\n        .every(10s)\n    |where(lambda: \"count\" \u003e 0)\n    |deadman(1.0, 30s)\n        .stateChangesOnly()\n        .exec('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down')\n\n// stream\n//     |from()\n//       .database('sdp_monitoring')\n//       .retentionPolicy('13m')\n//       .measurement('net_response')\n//       .where(lambda: \"type\" == 'kafka')\n//       .groupBy('cluster', 'host')\n//     |deadman(1.0, 30s)\n//         .stateChangesOnly()\n//         .exec('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down')\n\n"

adding this to the above AND \"cluster\" \!= 'tsys' but we are facing issue even while patching with same thing mentioned above. Below is the error we escaped brackets and \n even though we are facing error with script. Could anyone please have a look on this.

curl --request PATCH -H "Accept: application/json" --data '{"script": "batch/ \\n    |query\('''/ \\n            SELECT count\(response_time\) as count/ \\n            from \"sdp_monitoring\".\"13m\".\"net_response\"/ \\n            where \"type\" = 'kafka'/ \\n            '''\)/ \\n        .groupBy\('cluster', 'host'\)/ \\n        .period\(45s\)/ \\n        .every\(10s\)/ \\n    |where\(lambda: \"count\" \u003e 0\)/ \\n    |deadman\(1.0, 30s\)/ \\n        .stateChangesOnly\(\)/ \\n        .exec\('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down'\)/ \\n/ \\n// stream/ \\n//     |from\(\)/ \\n//       .database\('sdp_monitoring'\)/ \\n//       .retentionPolicy\('13m'\)/ \\n//       .measurement\('net_response'\)/ \\n//       .where\(lambda: \"type\" == 'kafka'\)/ \\n//       .groupBy\('cluster', 'host'\)/ \\n//     |deadman\(1.0, 30s\)/ \\n//         .stateChangesOnly\(\)/ \\n//         .exec\('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down'\)/ \\n/ \\n"}' http://localhost:9092/kapacitor/v1/tasks/kafkaproc_alert
curl: (6) Could not resolve host: \n; Name or service not known
curl: (6) Could not resolve host: SELECT; Name or service not known
curl: (6) Could not resolve host: count(response_time); Name or service not known
curl: (6) Could not resolve host: as; Name or service not known
curl: (6) Could not resolve host: count; Name or service not known
curl: (6) Could not resolve host: \n; Name or service not known
curl: (6) Could not resolve host: from; Name or service not known
curl: (6) Could not resolve host: "sdp_monitoring"."13m"."net_response"; Name or service not known
curl: (6) Could not resolve host: \n; Name or service not known
curl: (6) Could not resolve host: where; Name or service not known
curl: (6) Could not resolve host: "type"; Name or service not known
curl: (6) Could not resolve host: =; Name or service not known
curl: (6) Could not resolve host: kafka; Name or service not known
curl: (6) Could not resolve host: \n; Name or service not known
curl: (6) Could not resolve host: \); Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down; Name or service not known
curl: (6) Could not resolve host: Alert, Kafka; Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down, Kafka; Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down\); Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down; Name or service not known
curl: (6) Could not resolve host: Alert, Kafka; Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (6) Could not resolve host: Down, Kafka; Name or service not known
curl: (6) Could not resolve host: Process; Name or service not known
curl: (3) [globbing] unmatched close brace/bracket at pos 18
{
    "error": "invalid JSON"
}

**Comment by desa** [comment]
@SrikarshVardhan Are you sure your JSON is well formed? I've just tried running what you've supplied through `jq` and I'm getting malformed JSON.

**Comment by desa** [comment]
@SrikarshVardhan looks like you may have forgot to escape the double quoted elements of your tickscript.

Try
```
{
  "script": "batch/ \n |query('''/ \n SELECT count(response_time) as count/ \n from \"sdp_monitoring\".\"13m\".\"net_response\"/ \n where \"type\" = 'kafka'/ \n ''')/ \n .groupBy('cluster', 'host')/ \n .period(45s)/ \n .every(10s)/ \n |where(lambda: \"count\" > 0)/ \n |deadman(1.0, 30s)/ \n .stateChangesOnly()/ \n .exec('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down')/ \n/ \n// stream/ \n// |from()/ \n// .database('sdp_monitoring')/ \n// .retentionPolicy('13m')/ \n// .measurement('net_response')/ \n// .where(lambda: \"type\" == 'kafka')/ \n// .groupBy('cluster', 'host')/ \n// |deadman(1.0, 30s)/ \n// .stateChangesOnly()/ \n// .exec('/kapacitor/tick-scripts/hpomi.py', 'Kafka Process Down Alert', 'Kafka Process Down', 'Kafka Process Down')/ \n/ \n"
}
```
and let us know if the issue persists.
