### ISSUE TITLE
Http authentication ignores credentials

### ISSUE THREAD

**Issue by MisterMartin** [influxdata/kapacitor#1669]
Docker for macOS on OSX Sierra 10.12.6
Docker official images:
kapacitor:1.3
influxdb:1.2

I’m trying to use http basic authentication with Kapacitor.

I’ve set these env variables:
KAPACITOR_HTTP_AUTH_ENABLED=true
KAPACITOR_HTTP_USERNAME=admin
KAPACITOR_HTTP_PASSWORD=*****.

I get an authentication error if I don’t supply a username in the get request. However, the authentication succeeds if I supply only a username, and the username can be anything, e.g.:

```
curl -G http://foo@localhost:9092/kapacitor/v1/config
```

The log shows:

```
[noauth] 2017/11/03 23:06:40 W! using noauth auth backend. Faked authentication for user foo
```

The log message indicates that authentication is being ignored, but does not explain why. A similar issue remains unanswered in #1480.

**Comment by nathanielc** [comment]
@MisterMartin Thanks for the heads up, I have responded on the #1480 issue.
