### ISSUE TITLE
Kapacitor and InfluxDB should have similar HTTPS Configuration

### ISSUE THREAD

**Issue by desa** [influxdata/kapacitor#1690]
Kapacitor doesn't split out cert and key as separate files https://github.com/influxdata/kapacitor/blob/9ea0764954678ed2693f53a33dd84942445f5367/services/httpd/service.go#L128-L132
```
	if s.https {
		cert, err := tls.LoadX509KeyPair(s.cert, s.cert)
		if err != nil {
			return err
		}
```

Telegraf, InfluxDB, and Chronograf have them as separate https-cert and https-key

InfluxDB:
https://github.com/influxdata/influxdb/blob/e9cbc6da11435fd690561ff82e4a367ebdc62c79/services/httpd/service.go#L93-L97
```
	if s.https {
		cert, err := tls.LoadX509KeyPair(s.cert, s.key)
		if err != nil {
			return err
		}
```

Either Kapacitor should switch to using the same convention of the rest of TICK, or TIC should change to Kapacitor's convention.

**Comment by desa** [comment]
@nathanielc thoughts on this issue?

**Comment by nathanielc** [comment]
@desa When did this change for InfluxDB? The Kapacitor TLS code was copied verbatim from InfluxDB.

I think having them split makes more sense. Can we split them now and still have backwards compatible config?

**Comment by nathanielc** [comment]
Looks like we just need to apply this patch to the Kapacitor code. https://github.com/influxdata/influxdb/commit/5d9eae61b070f56adf9e4dad33a7fd4000669f00

**Comment by desa** [comment]
https://github.com/influxdata/influxdb/commit/5d9eae61b0

**Comment by desa** [comment]
👍

**Comment by AdamSLevy** [comment]
This will be very nice to have fixed.
