### ISSUE TITLE
Tests failed on ARM

### ISSUE THREAD

**Issue by vlasov01** [influxdata/kapacitor#172]
Hi,

I'd like to try Kapacitor on ARM based Linux.
$ uname -a
Linux localhost 3.10.9 #1 SMP PREEMPT Mon Nov 9 19:38:46 KST 2015 armv7l armv7l armv7l GNU/Linux

I've build it after adding several packages:
go get github.com/dustin/go-humanize
go get gopkg.in/gomail.v2
go get github.com/serenize/snaker
go get github.com/shurcooL/markdownfmt/markdown
go get github.com/stretchr/testify/assert

But tests failed:

$ go test ./...
2016/01/25 23:25:17 Reuse of exported var name: num_tasks
panic: Reuse of exported var name: num_tasks

goroutine 1 [running]:
log.Panicln(0x10a4ff24, 0x2, 0x2)
        /home/iot/.gvm/gos/go1.5.2/src/log/log.go:334 +0xa4
expvar.Publish(0x4ffe90, 0x9, 0xb544c080, 0x712588)
        /home/iot/.gvm/gos/go1.5.2/src/expvar/expvar.go:254 +0x19c
github.com/influxdata/kapacitor.init.1()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/global_stats.go:44 +0xe0
github.com/influxdata/kapacitor.init()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/window.go:206 +0x238
github.com/influxdb/kapacitor_test.init()
        /home/iot/gocodez/src/github.com/influxdb/kapacitor/udf_process_test.go:341 +0x60
main.init()
        github.com/influxdb/kapacitor/_test/_testmain.go:78 +0x5c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/iot/.gvm/gos/go1.5.2/src/runtime/asm_arm.s:1036 +0x4

goroutine 34 [syscall]:
os/signal.loop()
        /home/iot/.gvm/gos/go1.5.2/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /home/iot/.gvm/gos/go1.5.2/src/os/signal/signal_unix.go:28 +0x30
FAIL    github.com/influxdb/kapacitor   0.126s
ok      github.com/influxdb/kapacitor/clock     0.094s
?       github.com/influxdb/kapacitor/cmd/kapacitor     [no test files]
?       github.com/influxdb/kapacitor/cmd/kapacitord    [no test files]
?       github.com/influxdb/kapacitor/cmd/kapacitord/help       [no test files]
2016/01/25 23:25:31 Reuse of exported var name: cluster_id
panic: Reuse of exported var name: cluster_id

goroutine 1 [running]:
log.Panicln(0x10d3df54, 0x2, 0x2)
        /home/iot/.gvm/gos/go1.5.2/src/log/log.go:334 +0xa4
expvar.Publish(0x6bb8a0, 0xa, 0xb64cf0f0, 0x9a6508)
        /home/iot/.gvm/gos/go1.5.2/src/expvar/expvar.go:254 +0x19c
github.com/influxdata/kapacitor/cmd/kapacitord/run.init.1()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/server.go:61 +0x70
github.com/influxdata/kapacitor/cmd/kapacitord/run.init()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/server.go:589 +0xf4
github.com/influxdb/kapacitor/cmd/kapacitord/run_test.init()
        /home/iot/gocodez/src/github.com/influxdb/kapacitor/cmd/kapacitord/run/server_test.go:824 +0x58
main.init()
        github.com/influxdb/kapacitor/cmd/kapacitord/run/_test/_testmain.go:82 +0x5c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/iot/.gvm/gos/go1.5.2/src/runtime/asm_arm.s:1036 +0x4

goroutine 18 [syscall]:
os/signal.loop()
        /home/iot/.gvm/gos/go1.5.2/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /home/iot/.gvm/gos/go1.5.2/src/os/signal/signal_unix.go:28 +0x30
FAIL    github.com/influxdb/kapacitor/cmd/kapacitord/run        0.053s
?       github.com/influxdb/kapacitor/command   [no test files]
?       github.com/influxdb/kapacitor/command/test      [no test files]
ok      github.com/influxdb/kapacitor/integrations      1.086s
?       github.com/influxdb/kapacitor/models    [no test files]
ok      github.com/influxdb/kapacitor/pipeline  0.087s
?       github.com/influxdb/kapacitor/services/alerta   [no test files]
?       github.com/influxdb/kapacitor/services/deadman  [no test files]
?       github.com/influxdb/kapacitor/services/hipchat  [no test files]
?       github.com/influxdb/kapacitor/services/httpd    [no test files]
?       github.com/influxdb/kapacitor/services/influxdb [no test files]
?       github.com/influxdb/kapacitor/services/logging  [no test files]
?       github.com/influxdb/kapacitor/services/opsgenie [no test files]
?       github.com/influxdb/kapacitor/services/pagerduty        [no test files]
?       github.com/influxdb/kapacitor/services/replay   [no test files]
?       github.com/influxdb/kapacitor/services/reporting        [no test files]
?       github.com/influxdb/kapacitor/services/sensu    [no test files]
?       github.com/influxdb/kapacitor/services/slack    [no test files]
?       github.com/influxdb/kapacitor/services/smtp     [no test files]
?       github.com/influxdb/kapacitor/services/stats    [no test files]
?       github.com/influxdb/kapacitor/services/task_store       [no test files]
?       github.com/influxdb/kapacitor/services/udf      [no test files]
ok      github.com/influxdb/kapacitor/services/udp      0.227s
?       github.com/influxdb/kapacitor/services/victorops        [no test files]
ok      github.com/influxdb/kapacitor/tick      0.092s
?       github.com/influxdb/kapacitor/tick/cmd/tickdoc  [no test files]
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.InfoRequest
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.InfoResponse
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.OptionInfo
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.InitRequest
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.Option
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.OptionValue
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.InitResponse
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.SnapshotRequest
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.SnapshotResponse
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.RestoreRequest
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.RestoreResponse
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.KeepaliveRequest
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.KeepaliveResponse
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.ErrorResponse
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.BeginBatch
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.Point
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.EndBatch
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.Request
2016/01/25 23:25:16 proto: duplicate proto type registered: udf.Response
panic: proto: duplicate enum registered: udf.EdgeType

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterEnum(0x1d2290, 0xc, 0x1040e780, 0x1040e7a0)
        /home/iot/gocodez/src/github.com/gogo/protobuf/proto/properties.go:876 +0xc0
github.com/influxdata/kapacitor/udf.init.1()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/udf/udf.pb.go:1037 +0x7a8
github.com/influxdata/kapacitor/udf.init()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/udf/udf.pb.go:1039 +0x340
github.com/influxdb/kapacitor/udf_test.init()
        /home/iot/gocodez/src/github.com/influxdb/kapacitor/udf/io_test.go:69 +0x58
main.init()
        github.com/influxdb/kapacitor/udf/_test/_testmain.go:60 +0x5c
FAIL    github.com/influxdb/kapacitor/udf       0.084s
?       github.com/influxdb/kapacitor/udf/agent [no test files]
?       github.com/influxdb/kapacitor/udf/agent/examples        [no test files]
?       github.com/influxdb/kapacitor/wlog      [no test files]

**Comment by nathanielc** [comment]
I just tried this out on a Raspberry Pi B and the tests are passing fine.

My system:
```
 4.1.4-1-ARCH #1 PREEMPT Thu Aug 6 21:07:48 MDT 2015 armv6l GNU/Linux
```

Its armv6 and yours is armv7. Seems unlikely arm version related but possible. 

What version of `go` are you using?

Also try `go test -parallel 1 ./...` since a lot of the errors you are seeing seem to be namespace collisions.

**Comment by vlasov01** [comment]
I'm testing on a relatively fast board ARTIK 10 https://www.artik.io/hardware/artik-10 with ARM A15x4@1.3GHz + A7x4@1.0GHz.
I'm using go 1.5.2.

The test still fails:
[iot@localhost kapacitor]$ go test -parallel 1 ./...
2016/01/26 19:09:32 Reuse of exported var name: num_tasks
panic: Reuse of exported var name: num_tasks


goroutine 1 [running]:
log.Panicln(0x10a3bf24, 0x2, 0x2)
        /home/iot/.gvm/gos/go1.5.2/src/log/log.go:334 +0xa4
expvar.Publish(0x4ffe90, 0x9, 0xb4a80018, 0x712588)
        /home/iot/.gvm/gos/go1.5.2/src/expvar/expvar.go:254 +0x19c
github.com/influxdata/kapacitor.init.1()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/global_stats.go:44 +0xe0
github.com/influxdata/kapacitor.init()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/window.go:206 +0x238
github.com/influxdb/kapacitor_test.init()
        /home/iot/gocodez/src/github.com/influxdb/kapacitor/udf_process_test.go:341 +0x60
main.init()
        github.com/influxdb/kapacitor/_test/_testmain.go:78 +0x5c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/iot/.gvm/gos/go1.5.2/src/runtime/asm_arm.s:1036 +0x4

goroutine 4 [syscall]:
os/signal.loop()
        /home/iot/.gvm/gos/go1.5.2/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /home/iot/.gvm/gos/go1.5.2/src/os/signal/signal_unix.go:28 +0x30

goroutine 5 [runnable]:
text/template/parse.lexText(0x10917100, 0x59cccc)
        /home/iot/.gvm/gos/go1.5.2/src/text/template/parse/lex.go:237 +0x310
text/template/parse.(*lexer).run(0x10917100)
        /home/iot/.gvm/gos/go1.5.2/src/text/template/parse/lex.go:206 +0x54
created by text/template/parse.lex
        /home/iot/.gvm/gos/go1.5.2/src/text/template/parse/lex.go:199 +0x154
FAIL    github.com/influxdb/kapacitor   0.133s
ok      github.com/influxdb/kapacitor/clock     0.119s
?       github.com/influxdb/kapacitor/cmd/kapacitor     [no test files]
?       github.com/influxdb/kapacitor/cmd/kapacitord    [no test files]
?       github.com/influxdb/kapacitor/cmd/kapacitord/help       [no test files]
2016/01/26 19:09:46 Reuse of exported var name: cluster_id
panic: Reuse of exported var name: cluster_id


goroutine 1 [running]:
log.Panicln(0x10d51f54, 0x2, 0x2)
        /home/iot/.gvm/gos/go1.5.2/src/log/log.go:334 +0xa4
expvar.Publish(0x6bb8a0, 0xa, 0xb649e0c0, 0x9a6508)
        /home/iot/.gvm/gos/go1.5.2/src/expvar/expvar.go:254 +0x19c
github.com/influxdata/kapacitor/cmd/kapacitord/run.init.1()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/server.go:61 +0x70
github.com/influxdata/kapacitor/cmd/kapacitord/run.init()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/server.go:589 +0xf4
github.com/influxdb/kapacitor/cmd/kapacitord/run_test.init()
        /home/iot/gocodez/src/github.com/influxdb/kapacitor/cmd/kapacitord/run/server_test.go:824 +0x58
main.init()
        github.com/influxdb/kapacitor/cmd/kapacitord/run/_test/_testmain.go:82 +0x5c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/iot/.gvm/gos/go1.5.2/src/runtime/asm_arm.s:1036 +0x4

goroutine 19 [syscall]:
os/signal.loop()
        /home/iot/.gvm/gos/go1.5.2/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /home/iot/.gvm/gos/go1.5.2/src/os/signal/signal_unix.go:28 +0x30
FAIL    github.com/influxdb/kapacitor/cmd/kapacitord/run        0.052s
?       github.com/influxdb/kapacitor/command   [no test files]
?       github.com/influxdb/kapacitor/command/test      [no test files]
ok      github.com/influxdb/kapacitor/integrations      1.219s
?       github.com/influxdb/kapacitor/models    [no test files]
ok      github.com/influxdb/kapacitor/pipeline  0.050s
?       github.com/influxdb/kapacitor/services/alerta   [no test files]
?       github.com/influxdb/kapacitor/services/deadman  [no test files]
?       github.com/influxdb/kapacitor/services/hipchat  [no test files]
?       github.com/influxdb/kapacitor/services/httpd    [no test files]
?       github.com/influxdb/kapacitor/services/influxdb [no test files]
?       github.com/influxdb/kapacitor/services/logging  [no test files]
?       github.com/influxdb/kapacitor/services/opsgenie [no test files]
?       github.com/influxdb/kapacitor/services/pagerduty        [no test files]
?       github.com/influxdb/kapacitor/services/replay   [no test files]
?       github.com/influxdb/kapacitor/services/reporting        [no test files]
?       github.com/influxdb/kapacitor/services/sensu    [no test files]
?       github.com/influxdb/kapacitor/services/slack    [no test files]
?       github.com/influxdb/kapacitor/services/smtp     [no test files]
?       github.com/influxdb/kapacitor/services/stats    [no test files]
?       github.com/influxdb/kapacitor/services/task_store       [no test files]
?       github.com/influxdb/kapacitor/services/udf      [no test files]
ok      github.com/influxdb/kapacitor/services/udp      0.131s
?       github.com/influxdb/kapacitor/services/victorops        [no test files]
ok      github.com/influxdb/kapacitor/tick      0.073s
?       github.com/influxdb/kapacitor/tick/cmd/tickdoc  [no test files]
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.InfoRequest
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.InfoResponse
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.OptionInfo
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.InitRequest
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.Option
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.OptionValue
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.InitResponse
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.SnapshotRequest
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.SnapshotResponse
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.RestoreRequest
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.RestoreResponse
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.KeepaliveRequest
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.KeepaliveResponse
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.ErrorResponse
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.BeginBatch
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.Point
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.EndBatch
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.Request
2016/01/26 19:09:30 proto: duplicate proto type registered: udf.Response
panic: proto: duplicate enum registered: udf.EdgeType

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterEnum(0x1d2290, 0xc, 0x1040e780, 0x1040e7a0)
        /home/iot/gocodez/src/github.com/gogo/protobuf/proto/properties.go:876 +0xc0
github.com/influxdata/kapacitor/udf.init.1()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/udf/udf.pb.go:1037 +0x7a8
github.com/influxdata/kapacitor/udf.init()
        /home/iot/gocodez/src/github.com/influxdata/kapacitor/udf/udf.pb.go:1039 +0x340
github.com/influxdb/kapacitor/udf_test.init()
        /home/iot/gocodez/src/github.com/influxdb/kapacitor/udf/io_test.go:69 +0x58
main.init()
        github.com/influxdb/kapacitor/udf/_test/_testmain.go:60 +0x5c
FAIL    github.com/influxdb/kapacitor/udf       0.143s
?       github.com/influxdb/kapacitor/udf/agent [no test files]
?       github.com/influxdb/kapacitor/udf/agent/examples        [no test files]
?       github.com/influxdb/kapacitor/wlog      [no test files]

**Comment by vlasov01** [comment]
And now it fails to build as well:

./build.py --packages

--- Kapacitor Builder ---

Checking environment:
        - GOPATH -> /home/iot/gocodez
        - GOBIN -> None


Checking for dependencies:
        - git -> /usr/bin/git
        - go -> /home/iot/.gvm/gos/go1.5.2/bin/go
        - fpm (optional) -> /usr/local/bin/fpm
        - rpmbuild (optional) -> /usr/bin/rpmbuild

Building for...
        - version: 0.10.0
        - commit: cc53904
        - branch: master
        - platform: linux
        - arch: armv7l
        - nightly? false
        - race enabled? false

Retrieving Go dependencies... done.
Starting build...
        - Building 'kapacitord'...
Executed command failed!
-- Command run was: GOOS=linux GOOARCH=armv7l go build -o build/kapacitord -ldflags="-X main.buildTime='2016-01-28T04:48:45.933710' -X main.version=0.10.0 -X main.branch=master -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71" ./cmd/kapacitord/main.go
-- Failure was: # github.com/influxdb/influxdb/tsdb
2016/01/27 23:48:47 reading input: EOF

**Comment by rossmcdonald** [comment]
@vlasov01 I don't believe that `amv7l` is a [valid](https://github.com/golang/go/wiki/GoArm) GOARCH (or GOARM) value. We'll need to tweak the build script to support more ARM architectures, but for now try running the build commands manually. For example:

```
GOOS=linux GOARCH=arm GOARM=7 go build -o build/kapacitord -ldflags="-X main.version=$(git describe --always --tags --abbrev=0) -X main.branch=$(git rev-parse --abbrev-ref HEAD) -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71" ./cmd/kapacitord/main.go
```

**Comment by vlasov01** [comment]
@rossmcdonald I've tried to build as per your instruction. here is the output:

[iot@localhost kapacitor]$ GOOS=linux GOARCH=arm GOARM=7 go build -o build/kapacitord -ldflags="-X main.version=$(git describe --always --tags --abbrev=0) -X main.branch=$(git rev-parse --abbrev-ref HEAD) -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71" ./cmd/kapacitord/main.go
# github.com/influxdb/influxdb/tsdb
2016/01/28 21:53:27 reading input: EOF

**Comment by rossmcdonald** [comment]
@vlasov01 Can you rerun the same command except adding a `-x` to display the underlying commands being run? That will hopefully show us what's causing the `reading input: EOF` error.

**Comment by vlasov01** [comment]
@rossmcdonald Here is the output as per your request:

```
[iot@localhost kapacitor]$ GOOS=linux GOARCH=arm GOARM=7 go build -o -x build/kapacitord -ldflags="-X main.version=$(git describe --always --tags --abbrev=0) -X main.branch=$(git rev-parse --abbrev-ref HEAD) -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71" ./cmd/kapacitord/main.go
can't load package: package build/kapacitord: cannot find package "build/kapacitord" in any of:
        /home/iot/.gvm/gos/go1.5.2/src/build/kapacitord (from $GOROOT)
        /home/iot/gocodez/src/build/kapacitord (from $GOPATH)
can't load package: package -ldflags=-X main.version=v0.10.0 -X main.branch=master -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71: cannot find package "-ldflags=-X main.version=v0.10.0 -X main.branch=master -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71" in any of:
        /home/iot/.gvm/gos/go1.5.2/src/-ldflags=-X main.version=v0.10.0 -X main.branch=master -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71 (from $GOROOT)
        /home/iot/gocodez/src/-ldflags=-X main.version=v0.10.0 -X main.branch=master -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71 (from $GOPATH)
can't load package: package github.com/influxdb/kapacitor/cmd/kapacitord/main.go: cannot find package "github.com/influxdb/kapacitor/cmd/kapacitord/main.go" in any of:
        /home/iot/.gvm/gos/go1.5.2/src/github.com/influxdb/kapacitor/cmd/kapacitord/main.go (from $GOROOT)
        /home/iot/gocodez/src/github.com/influxdb/kapacitor/cmd/kapacitord/main.go (from $GOPATH)

```
But it seems to me that the file in question exists:
```
-rw-rw-r-- 1 iot iot 4504 Jan 25 22:43 /home/iot/gocodez/src/github.com/influxdb/kapacitor/cmd/kapacitord/main.go
-rw-rw-r-- 1 iot iot 4504 Jan 25 22:43 /home/iot/gocodez/src/github.com/influxdata/kapacitor/cmd/kapacitord/main.go

```

**Comment by rossmcdonald** [comment]
@vlasov01 The order of the operators matters when running the `go build` command. Can you try this command instead:

```
GOOS=linux GOARCH=arm GOARM=7 go build -x -o build/kapacitord -ldflags="-X main.version=$(git describe --always --tags --abbrev=0) -X main.branch=$(git rev-parse --abbrev-ref HEAD) -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71" ./cmd/kapacitord/main.go
```

Where the `-o` and `-x` are swapped?

**Comment by vlasov01** [comment]
@rossmcdonald  Here is the output:

```
[iot@localhost kapacitor]$ GOOS=linux GOARCH=arm GOARM=7 go build -x -o build/kapacitord -ldflags="-X main.version=$(git describe --always --tags --abbrev=0) -X main.branch=$(git rev-parse --abbrev-ref HEAD) -X main.commit=cc53904ee398dd9bc4ff1dddd779173782780d71" ./cmd/kapacitord/main.go
WORK=/tmp/go-build387104615
mkdir -p $WORK/github.com/influxdb/influxdb/tsdb/_obj/
mkdir -p $WORK/github.com/influxdb/influxdb/
cd /home/iot/gocodez/src/github.com/influxdb/influxdb/tsdb
/home/iot/.gvm/gos/go1.5.2/pkg/tool/linux_arm/compile -o $WORK/github.com/influxdb/influxdb/tsdb.a -trimpath $WORK -p github.com/influxdb/influxdb/tsdb -complete -buildid 0e70d55f42cb7653df7f651984f799460041a038 -D _/home/iot/gocodez/src/github.com/influxdb/influxdb/tsdb -I $WORK -I /home/iot/gocodez/pkg/linux_arm -pack ./aggregate.go ./batcher.go ./config.go ./cursor.go ./doc.go ./engine.go ./executor.go ./functions.go ./into.go ./mapper.go ./meta.go ./query_executor.go ./raw.go ./shard.go ./show_measurements.go ./show_tag_keys.go ./store.go
# github.com/influxdb/influxdb/tsdb
2016/02/01 19:15:49 reading input: EOF

```

**Comment by vlasov01** [comment]
I've tried a new build with 0.10.0

It failed. Here is the output:

```
[iot@localhost kapacitor]$ ./build.py  --packages

--- Kapacitor Builder ---

Checking environment:
        - GOPATH -> /home/iot/.gvm/pkgsets/go1.5.2/global
        - GOBIN -> None

!! WARNING: Your current directory is not under your GOPATH! This probably won't work.


Checking for dependencies:
        - git -> /usr/bin/git
        - go -> /home/iot/.gvm/gos/go1.5.2/bin/go
        - fpm (optional) -> /usr/local/bin/fpm
        - rpmbuild (optional) -> /usr/bin/rpmbuild

Building for...
        - version: 0.10.0
        - commit: 35c9c6f
        - branch: HEAD
        - platform: linux
        - arch: armv7l
        - nightly? false
        - race enabled? false

Retrieving Go dependencies... done.
Starting build...
        - Building 'kapacitord'...
Executed command failed!
-- Command run was: GOOS=linux GOOARCH=armv7l go build -o build/kapacitord -ldflags="-X main.buildTime='2016-02-08T02:55:29.579940' -X main.version=0.10.0 -X main.branch=HEAD -X main.commit=35c9c6fe6543f9d65779d10723ea3a70657d8bba" ./cmd/kapacitord/main.go
-- Failure was: # github.com/hashicorp/go-msgpack/codec
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/hashicorp/go-msgpack/codec/msgpack.go:26: syntax error: unexpected semicolon or newline, expecting )
# gopkg.in/fatih/pool.v2
/home/iot/.gvm/pkgsets/go1.5.2/global/src/gopkg.in/fatih/pool.v2/channel.go:6: newline in string
/home/iot/.gvm/pkgsets/go1.5.2/global/src/gopkg.in/fatih/pool.v2/channel.go:6: syntax error: unexpected semicolon or newline, expecting )
# github.com/armon/go-metrics
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/armon/go-metrics/statsd.go:7: newline in string
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/armon/go-metrics/statsd.go:7: syntax error: unexpected semicolon or newline, expecting )
# github.com/influxdata/kapacitor/services/alerta
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdata/kapacitor/services/alerta/service.go:9: syntax error: unexpected semicolon or newline, expecting (
# golang.org/x/crypto/bcrypt
/home/iot/.gvm/pkgsets/go1.5.2/global/src/golang.org/x/crypto/bcrypt/bcrypt.go:11: newline in string
/home/iot/.gvm/pkgsets/go1.5.2/global/src/golang.org/x/crypto/bcrypt/bcrypt.go:11: syntax error: unexpected semicolon or newline, expecting .
# github.com/twinj/uuid
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/twinj/uuid/rfc4122.go:10: newline in string
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/twinj/uuid/rfc4122.go:10: syntax error: unexpected semicolon or newline, expecting .
# github.com/influxdb/influxdb/client
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/client/influxdb.go:9: newline in string
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/influxdb/client/influxdb.go:9: syntax error: unexpected semicolon or newline, expecting )
# gopkg.in/gomail.v2
/home/iot/.gvm/pkgsets/go1.5.2/global/src/gopkg.in/gomail.v2/auth.go:7: newline in string
/home/iot/.gvm/pkgsets/go1.5.2/global/src/gopkg.in/gomail.v2/auth.go:7: syntax error: unexpected semicolon or newline, expecting .
# github.com/influxdb/usage-client/v1
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/usage-client/v1/client.go:7: newline in string
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdb/usage-client/v1/client.go:7: syntax error: unexpected semicolon or newline, expecting )
# github.com/influxdata/kapacitor/services/talk
/home/iot/.gvm/pkgsets/go1.5.2/global/src/github.com/influxdata/kapacitor/services/talk/service.go:8: syntax error: unexpected semicolon or newline, expecting (


Stopping.
```

**Comment by nathanielc** [comment]
There are a couple of things odd about the log output:

1. This warning `!! WARNING: Your current directory is not under your GOPATH! This probably won't work.
` you need to make sure that the Kapacitor source is checkout under the GOPATH like `$GOPATH/src/github.com/influxdata/kapacitor`.
2. The errors you are getting are not even Kapacitor code and they are parse errors. This makes me think you have a broken Go installation. I see that you are using gvm to install go. FWIW Kapacitor now uses 1.5.3 but I don't expect that to fix your problem. Are you able to compile a simple go program? Have you tried cross compiling and then just running the binaries on the ARM device? Here is a guide for cross compiling with Go http://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5

**Comment by vlasov01** [comment]
@nathanielc I was able to successfully build Influx/influxd just before kapacitor on the same machine. I was using a different version of Go for it. Thank you for the guide. I'll read it and try the build again.

**Comment by rossmcdonald** [comment]
@vlasov01 I also ran into the error you saw before:

```
2016/02/01 19:15:49 reading input: EOF
```

Earlier today when attempting to compile a Go program on a small machine (1 core, 1GB of RAM), which was causing the compilation process to get killed by the system. I haven't had issues compiling Kapacitor on small-ish machines, but you may also want to check `dmesg` or syslog output to make sure the compilation is not getting killed due to consuming too much memory (triggering the system's OOM killer).

In addition, we've started running nightly builds with `arm` as a target. I haven't verified these work yet, but you might want to give it a shot (we also have RPM's and DEB's, depending on which distro of Linux you're running).

**Comment by vlasov01** [comment]
@rossmcdonald Thank you! I've downloaded kapacitor-nightly.arm.rpm as I'm running Fedora.

Here is the result:
dnf install kapacitor-nightly.arm.rpm
Last metadata expiration check performed 0:11:17 ago on Mon Feb  8 20:59:22 2016.
Error: package kapacitor-0.10.1~n1454918629-0.arm is not installable
(try to add '--allowerasing' to command line to replace conflicting packages)

dnf install --allowerasing kapacitor-nightly.arm.rpm
Last metadata expiration check performed 0:12:54 ago on Mon Feb  8 20:59:22 2016.
Error: package kapacitor-0.10.1~n1454918629-0.arm is not installable

**Comment by rossmcdonald** [comment]
@vlasov01 Sorry for the delay in following up here! Since the last update we have corrected the issues with ARM packages. The latest armhf nightly packages are available [here](https://s3-us-west-1.amazonaws.com/kapacitor-nightly/kapacitor-nightly.armhf.rpm). We also offer the official releases for the ARM architectures on [our downloads page](https://influxdata.com/downloads/#kapacitor) as well.

I'm going to go ahead and close this issue, but let us know if you run into any further problems.
