### ISSUE TITLE
[Feature Request] Add Alert inhibitions

### ISSUE THREAD

**Issue by karanatree** [influxdata/kapacitor#1734]
We have Kapacitor configured to send alerts for a bunch of measurements in multiple databases. All of these alerts have their own deadman component.

1) What we need is a configuration for a global outage across measurements and databases. Say our influxdb itself is down. Instead of Kapacitor firing an alert for each measurement in each db, can Kapacitor send out one alert?
 
2) And if say Kapacitor sends out an alert if a service is down on a node, consequently Kapacitor would send out alerts SEPARATELY for each node rather than a collective alert. Even if we develop logic for a combined alert, the individual node alerts will still fire since they're configured too. So if we have 20 nodes on which we collect and store data, and the database goes down, we need a single global alert rather than 20 separate alerts firing. However if say 2 nodes aren't reporting data, we want them to fire alerts independently. 

Are there possible configurations for the problems.

**Comment by nathanielc** [comment]
@karanatree This is not currently possible. We have been talking internally about this and have an initial design but it hasn't gotten past that stage.

What we are thinking is that an alert can `inhibit` or `suppress` another alert based on the matching tags of the alerts. Given your example, you would configure the host alert for influxdb to suppress all db/measurement alerts with the same host tag. This way alerts are still separate, its just that one alert can suppress others while its firing. This design is not new, its inspired by this https://prometheus.io/docs/alerting/alertmanager/#inhibition. 

Does that sound like it would work for your needs?

**Comment by karanatree** [comment]
Thanks for the prompt reply @nathanielc 

Yes, the inhibit/suppress feature of Prometheus is precisely what I was looking for. I appreciate the information regarding its progress here in the TICK stack. 

I, for one, would benefit immensely with the roll out of such a feature. Looking forward to seeing its implementation here.

**Comment by nathanielc** [comment]
Reopening to track the feature request, since while we have had discussions internally we hadn't yet created an issue.
