### ISSUE TITLE
Defining a Task from a Template using the -file flag assigns a random ID

### ISSUE THREAD

**Issue by Z3KAISER** [influxdata/kapacitor#1745]
- Full details of your operating system (or distribution) e.g. 64-bit Ubuntu 14.04

64-bit Ubuntu 16.04.3

- The version of Kapacitor you are running

Kapacitor 1.4.0 (git: HEAD fcce3ee9e6abcee5595fd61066bfc904edb1e113)

- Whether you installed it using a pre-built package, or built it from source

https://dl.influxdata.com/kapacitor/releases/kapacitor_1.4.0_amd64.deb

- A small test case, if applicable, that demonstrates the issues

Define a task from a template with the following command:
```
kapacitor define test_alert -file /path/to/file/test.json
```

List tasks:
```
ID                                   Type      Status    Executing Databases and Retention Policies
a06a3b26-fd93-4016-836a-04a5ef076249 stream    disabled  false     ["telegraf"."autogen"]
```

The ID of task should be "test_alert" but instead the ID is a random string.

**Comment by AdamSLevy** [comment]
This is the same as the bug I submitted the other day. Issue #1743

**Comment by Z3KAISER** [comment]
Good call. Ty @AdamSLevy
