### ISSUE TITLE
Could you please post on how to build binaries for the latest release?

### ISSUE THREAD

**Issue by Srungaram** [influxdata/kapacitor#175]
I have tried using go build but getting below error
../influxdata/kapacitor/udf/udf.pb.go:286: undefined: proto.ErrInternalBadWireType
../influxdata/kapacitor/udf/udf.pb.go:293: undefined: proto.ErrInternalBadWireType
../influxdata/kapacitor/udf/udf.pb.go:300: undefined: proto.ErrInternalBadWireType
../influxdata/kapacitor/udf/udf.pb.go:307: undefined: proto.ErrInternalBadWireType
../influxdata/kapacitor/udf/udf.pb.go:314: undefined: proto.ErrInternalBadWireType
../influxdata/kapacitor/udf/udf.pb.go:618: b.EncodeMessage undefined (type *proto.Buffer has no field or method EncodeMessage)
../influxdata/kapacitor/udf/udf.pb.go:623: b.EncodeMessage undefined (type *proto.Buffer has no field or method EncodeMessage)
../influxdata/kapacitor/udf/udf.pb.go:628: b.EncodeMessage undefined (type *proto.Buffer has no field or method EncodeMessage)
../influxdata/kapacitor/udf/udf.pb.go:633: b.EncodeMessage undefined (type *proto.Buffer has no field or method EncodeMessage)
../influxdata/kapacitor/udf/udf.pb.go:638: b.EncodeMessage undefined (type *proto.Buffer has no field or method EncodeMessage)
../influxdata/kapacitor/udf/udf.pb.go:638: too many errors
# github.com/influxdb/influxdb/services/meta/internal
../influxdb/influxdb/services/meta/internal/meta.pb.go:1648: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1649: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1650: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1651: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1652: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1653: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1654: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1655: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1656: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1657: undefined: proto.RegisterType
../influxdb/influxdb/services/meta/internal/meta.pb.go:1657: too many errors

**Comment by nathanielc** [comment]
Looks like you are missing some dependencies. The supported way to build it is using `./build.py`. This will place the binaries in a `./build/` directory. If you have docker you can run `./build.sh` to build the code inside a docker container for better isolation.

`build.py` is just a wrapper around `go build`.  Maybe try `go get -v -u ./...` to update your gopath deps?
