### ISSUE TITLE
Support Matrix as an alert endpoint

### ISSUE THREAD

**Issue by yatcipije** [influxdata/kapacitor#1758]
This is a feature request for supporting [Matrix](https://matrix.org) as an alert endpoint. Matrix specifies a RESTful API for decentralized communication among users and Matrix homeservers. [A guide to the API exists here](https://matrix.org/docs/guides/client-server.html), [the full API spec exists here](https://matrix.org/docs/spec/client_server/r0.3.0.html), and [an introduction to Matrix exists here](https://matrix.org/docs/spec/intro.html).

Here is roughly what I would expect to see as an example Matrix config, with user @kapacitor:example.xyz and target room !asfLdzLnOdGRkdPZWu:example.xyz:
```
[matrix]
  # Configure Matrix.
  enabled = true
  username = "kapacitor"
  # The homeserver on which the user is registered
  user_homeserver = "https://example.xyz"
  # The user's access token
  access_token = "QGV4YW1wbGU6bG9jYWxob3N0.AqdSzFmFYrLrTmteXc"
  # The ID of the default room to which messages will be posted
  # The specified user must be invited or otherwise able to join
  room_id = "asfLdzLnOdGRkdPZWu"
  # The homeserver on which the default room resides
  room_homeserver = "https://example.xyz"
  # If true then all alerts will be sent to Matrix
  # without explicitly marking them in the TICKscript.
  global = false
  # Only applies if global is true.
  # Sets all alerts in state-changes-only mode,
  # meaning alerts will only be sent if the alert state changes.
  state-changes-only = false
```

In TICKscript, I'd expect it to look like `…|alert().matrix()`. To override the default room and homeserver, one could use `…|alert().matrix('qBFNwucQebGPQldAnq', 'https://differenthomeserver.org')`.

Some notes:
- The admin should take care of registering the Matrix user, getting their access token, finding the internal room ID of the target room, and inviting them or allowing them to join this room.
- The user and room may be on different homeservers.
- In the API guide that I linked above, all requests are done on port 8448. However, most homeservers reverse proxy Matrix to port 443, as is recommended, so don't assume that port 8448 should be the default.
- Instead of specifying the room ID, maybe we could support joining via room alias (e.g. #devops:example.xyz instead of !asfLdzLnOdGRkdPZWu:example.xyz). This would only take [one more API call to resolve the alias to a room ID](https://matrix.org/docs/spec/client_server/r0.3.0.html#get-matrix-client-r0-directory-room-roomalias), but keep in mind that not all rooms have aliases.

If you have any questions about how Matrix works, ask me and I'll try my best to explain.

**Comment by goller** [comment]
@yatcipije looks neat. Does a go client already exist for matrix?

**Comment by yatcipije** [comment]
@goller It appears that there is [an official Go client SDK](https://github.com/matrix-org/gomatrix). The README says breaking changes are frequent, but matrix.org says it's stable, so make what you will of it.

**Comment by yatcipije** [comment]
[OpenSAPS](https://gitlab.com/pztrn/opensaps) now exists, which makes it possible to interact with Matrix through a Slack API. The Slack alert endpoint can be used for this purpose instead.
