### ISSUE TITLE
Emit batch when no data

### ISSUE THREAD

**Issue by segseriy** [influxdata/kapacitor#1767]
Hello.
I need a help. I'm trying to calculate errors rate of my application based on data from InfluxDB.
Here is my tick script
`// get errors
var errors = batch
    |query('''
        SELECT sum("count")
        FROM "telegraf"."autogen".errors
        WHERE "status_code" =~ /^5\d+/
    ''')
        .period(5m)
        .every(10s)
        .groupBy('host')
        .fill(0)
        .align()
    |last('sum').as('value')

// get views
var views = batch
    |query('''
        SELECT count(*)
        FROM "telegraf"."autogen".request_time
    ''')
        .period(5m)
        .every(10s)
        .groupBy('host')
        .fill(0)
        .align()
    |last('count_request_time').as('value')

errors
    |join(views)
        .as('errors', 'views')
    |eval(lambda: int(("errors.value" / "views.value") * 100.0))
        .as('value')
    |alert() ...`

Everything works fine when in both measurements i have data, but it is not always present.
I'm sending data to influxdb on my own and only if there is an error/request.
So if i have no data (no requests and errors) for tha period of time (5m) my batches are not emitted.
What i'm doing wrong?
I was trying to use DefaultNode but no effect.

**Comment by RobHoman** [comment]
@segseriy I'm having the same problem - did you find a workaround?

**Comment by segseriy** [comment]
Unfortunately no. I did not find workaround, just replaced my task...
