### ISSUE TITLE
Can't delete handler with same name as topic

### ISSUE THREAD

**Issue by rconn01** [influxdata/kapacitor#1776]
If a topic handler is created that has the same name as the topic, there is no way to delete that topic handler. When I try to delete the handler the whole topic gets deleted. When the topic is created again the handler is still there.

Based on this code it seems that is intentional?

https://github.com/influxdata/kapacitor/blob/96a4b75deae3e8054a94e9c1ab0cff2bbbe12bc9/services/alert/api.go#L213-L217

If so what is the recommend way to delete a handler that was created with the same name as the topic.

**Comment by rconn01** [comment]
@nathanielc any ideas here. The best I was able to come up with (without code change) was delete the kapacitor storage db, and then just re-create all my definitions. If this intentional logic, perhaps some logic should be added that prevents creating a handler that has the same name as the topic

**Comment by internaught** [comment]
Wow, I just ran into this issue myself. Deleting the storage DB seems pretty dangerous and I'm not sure that cloud-hosted (enterprise) Kapacitor instances support it. Let's get some traction on this.
