### ISSUE TITLE
Deadman alert not triggered after reboot

### ISSUE THREAD

**Issue by matthenning** [influxdata/kapacitor#1784]
I have a deadman alert configured which triggers when any process from procstat is dead which works fine during normal operation.
If a service doesn't start after reboot the alert is not being triggerd though.

How to reproduce:
* Create an alert like below
* All monitored services are running but at least one is not on auto start
* Reboot the machine (all components are running on a single host in my case including the monitored processes)
* The service without auto start shows up in the telegraf log but kapacitor does not send out an alert

Output from kapacitor if the alert triggers correctly. This does not show up if the service does not start on boot and is dead before kapacitor started:
```
ts=2018-01-31T19:19:00.001+01:00 lvl=debug msg="alert triggered" service=kapacitor task_master=main task=chronograf-v1-579ae317-2e35-4147-b3ba-2228f947c185 node=influxdb_out8 level=CRITICAL id="Service State:exe=ts3server,host=redacted" event_message="redacted - ts3server is CRITICAL" data="&{stats map[exe:ts3server host:redacted] [time emitted] [[2018-01-31 18:19:00 +0000 UTC 0]]}"
```

Telegraf registers the stopped process:
```
2018-01-31T18:19:00Z E! Error in plugin [inputs.procstat]: E! Error: procstat getting process, exe: [ts3server] pidfile: [] pattern: [] user: [] Error running /usr/bin/pgrep: exit status 1
```

The TICK script was created by chronograf:
```
var db = 'telegraf'

var rp = 'telegraf'

var measurement = 'procstat'

var groupBy = ['host', 'exe']

var whereFilter = lambda: TRUE

var period = 1m

var name = 'Service Status'

var idVar = name + ':{{.Group}}'

var message = '{{ index .Tags "host" }} - {{ index .Tags "exe" }} is {{ .Level }}'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'deadman'

var threshold = 0.0

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)

var trigger = data
    |deadman(threshold, period)
        .stateChangesOnly()
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)

trigger
    |eval(lambda: "emitted")
        .as('value')
        .keep('value', messageField, durationField)
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

trigger
    |httpOut('output')
```

Ubuntu 16.04.3 LTS

TICK packages are pre-built
Kapacitor 1.4.0 (git: HEAD fcce3ee9e6abcee5595fd61066bfc904edb1e113)
InfluxDB v1.4.2 (git: 1.4 6d2685d1738277a1c2672fc58df7994627769be6)
Telegraf v1.5.1 (git: release-1.5 0605af7c)
Chronograf 1.4.0.1 (git: a5e9baf0d6ee128792f7e8e804401ac8e05ce68b)

**Comment by alexey-mk** [comment]
Hi!
> This does not show up if the service does not start on boot and is dead before kapacitor started
it is because Kapacitor at this moment don't know that dead service exists.
To "know" about dead service after Kapacitor restart, it shoud recive at least one point from whis service.

So solution woud be to make your script batch, and then every period do two batch selects in it:
First "old_data" get a single point (e.g last("myField") ) for each service from last few days - to get the "list" of all services, even if they are dead now.
And the second batch "current_data" - to get current services activity, e.g. last 1m.
Then union both bathes and pass to deadman node, there deadman.threshold would be =deadman.period / old_data.every (so much points will always be emitted in deadman stats because of old_data, meaning service is actually dead.)

Example
```
var v_old_period = 3d // search for hosts in this period. Returns 1 data point for each host.
var v_current_period = 1m // current hosts activity. Returns 0+ data points for each host.
var v_every = 1m // data request interval.

var v_dead = 2m // how often to check the throughput for host in deadman. If host has not sent a new point in this interval - it's dead.
var v_dead_emitted = 2.0 // v_dead/v_every points will always be emitted in deadman stats because of old data, meaning host is actually dead.

// last data points for all hosts. Returns 1 point for each host.
var old_data = batch
        |query('''
		SELECT last("myField") as "myField" FROM "myDB"."rp"."myTable"
		''')
		.period(v_old_period)
		.every(v_every)
		.groupBy('host')
		.cluster('bank1')
        .align()

// current data points for all hosts. Returns 0+ data points for each host.
var current_data = batch
        |query('''
		SELECT "myField" FROM "myDB"."rp"."myTable"
		''')
		.period(v_current_period)
		.every(v_every)
		.groupBy('host')
		.cluster('bank1')
		.align()

// union data and check status
old_data
        |union(current_data)
        |deadman(v_dead_emitted, v_dead)
		.id('host_deadman/{{ index .Tags "host" }}')
		.message('Host={{ index .Tags "host" }} is {{ if eq .Level "OK" }}alive{{ else }}dead{{ end }}. Emitted={{ index .Fields "emitted" }}')
		.details('')
		.log('/data/logs/host_deadman.log')
		.flapping(0.25, 0.5)
		.stateChangesOnly()
```

**Comment by matthenning** [comment]
Thank you, this solved my issue.
