### ISSUE TITLE
Feature request: Reduce repetitive declaration redundancy of redundant declarations when defining tasks by reducing redundancy

### ISSUE THREAD

**Issue by cheribral** [influxdata/kapacitor#1797]
When I declare a task or a template, it feels like I am repeating myself a lot.  For example, in a template, I have to declare variable types, and then declare them again when providing the values.  When defining the tasks, I have to specify whether it is batch or stream on the command line, and then declare it again in the tick script.  I also have to specify the dbrp on the command line, and then specify it again in my query within the tick script.

Is this something that could be fixed?  It seems like passing a bit more information between the stages of parsing, definition and loading could make the workflow a bit easier.

**Comment by nathanielc** [comment]
@cheribral Most of this has been fixed with the latest version 1.4.

Now in TICKscripts you can specify the dbrp and we can parse the file to determine the type dynamically.

Example:

```
dbrp "telegraf.autogen"

stream
    |from()
       ...
```

Then the command to define the task is simply:
```
kaapcitor define mytask -tick path/to/script.tick
```

**Comment by cheribral** [comment]
Ah cool, good to know, thanks.

Would my feature request still be valid for the templates?  For instance, with a template which defines 
`var group list`
The documentation shows the var file must be like this: 
`"groups": {"type": "list", "value": [{"type":"star", "value":"*"}]}`
Since it is already known that `group` should be a list, is it possible to sort out the type and validity when parsing, so it could simply be something like:
`"groups": ["*"]`
I'm guessing that type:star is something which could be detected automatically.  The difference between strings and durations etc. is already detected when a script is loaded, since it will throw errors if they are not appropriate.  Would it be possible to just check how they parse against what is defined in the template?

Cheers!

**Comment by nathanielc** [comment]
I don't expect this change will be possible. While the JSON structure is a bit verbose we leverage the type information throughout the code. It may be possible to gather the type information from the script itself and then apply it to the JSON, but that represents quite a bit of work for what in this case is a small gain. 

Additionally  at this point changing the JSON structure would be a breaking change so its not possible to change. 

Thanks for the suggestions, we are going to have to live with the redundancy in the JSON vars for now.

**Comment by cheribral** [comment]
Ok, thanks for the reply.  It is what it is then.  It was worth a try :)
btw, I really appreciate the work you've done with kapacitor, so thank you!
