### ISSUE TITLE
kapacitor halts when creating a task

### ISSUE THREAD

**Issue by rj-reilly** [influxdata/kapacitor#1804]
Hi, I have a instillation of influxdb and kapacitor on two different hosts. I can validate connectivity by telnet to each port from the other host. I have sensu writing measurements to influxdb. When i start kapacitor i see entries from influxdb like this
`kapacitor/unknown,now 1.4.0-1 amd64 [installed]`
`influxdb/unknown,now 1.4.2-1 amd64 [installed]`

```
4815886Z method=POST uri=/write?consistency=&db=statsd&precision=ns&rp=shortterm protocol=HTTP/1.1 status=204 referer=- user-agent=InfluxDBClient request-id=d4bf0503-11c0-11e8-8012-000000000000 duration=739.355µs
```

when i attempt to add the following tick script 
```
stream
    |from()
        .measurement('load_avg_5')
        .groupBy('host')
    |window()
        .period(5m)
        .every(1m)
    |mean('value')
    |alert()
        .message('{{ .Level}}: {{ .Name }}/{{ index .Tags "host" }} has high cpu load: {{ index .Fields "value" }}')
         warn(lambda: sigma("value") > 2.0)
         crit(lambda: sigma("value") > 3.0)
        // Send alert to hander of choice.
        .log("/tmp/kap.log")
```

kapacitor seems to halt and i get the following error (404 return)
```
46291747Z method=GET uri=/kapacitor/v1/tasks/Load_5_alert?dot-view=attributes&replay-id=&script-format=formatted protocol=HTTP/1.1 status=404 referer=- user-agent=KapacitorClient request-id=df5acc91-11c0-11e8-8018-000000000000 duration=277.721µs
```

then i get no more messages from influx and I have to kill and restart kapacitor to get it to respond to requests.

**Comment by MarilynZ** [comment]
@rj-reilly Hi, reilly. I also met the same problem. but the status is 202.Did you resolve it?
