### ISSUE TITLE
Kapacitor not producing alerts with small data set

### ISSUE THREAD

**Issue by ono760** [influxdata/kapacitor#1805]
Possible bug. 

Kapacitor version: 1.4.0

1. Original Points inserted:

```
 myServerStats,host=myHost1 myBuilds=-1i
 myServerStats,host=myHost1 myBuilds=-1i
 myServerStats,host=myHost1 myBuilds=-1i
 myServerStats,host=myHost1 myBuilds=0i
 myServerStats,host=myHost1 myBuilds=0i
 myServerStats,host=myHost1 myBuilds=-1i
 myServerStats,host=myHost1 myBuilds=2i
```

2. Kapacitor `show task` output:

```
kapacitor show  myServerStats-myBuilds.tick
ID: myServerStats-myBuilds.tick
Error: 
Template: 
Type: stream
Status: enabled
Executing: true
Created: 14 Feb 18 16:42 PST
Modified: 14 Feb 18 16:42 PST
LastEnabled: 14 Feb 18 16:42 PST
Databases Retention Policies: ["myStatsDB"."default"]
TICKscript:
var point = stream
    |from()
        .database('myStatsDB')
        .measurement('myServerStats')
        .groupBy('host')
    |log()
var summation = point
    |window()
        .periodCount(6)
        .everyCount(1)
        .fillPeriod()
    |sum('myBuilds')
        .as('buildsCount')
    |log()

point
    |join(summation)
        .as('point', 'summation')
    |alert()
        .id('kapacitor/{{ .TaskName }}')
        .crit(lambda: "point.myBuilds" <= 0 AND "summation.buildsCount" <= 0)
        .message('Host {{index .Tags "host"}} has not recovered and not running expected number of builds.')
        .idField('id')
        .messageField('description')
        .levelField('level')
        .log('/tmp/alert.log')
```

```
DOT:
digraph myServerStats-runningBuilds.tick {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0s" errors="0" working_cardinality="0" ];
stream0 -> from1 [processed="7"];

from1 [avg_exec_time_ns="14.807µs" errors="0" working_cardinality="0" ];
from1 -> log2 [processed="7"];

log2 [avg_exec_time_ns="75.016µs" errors="0" working_cardinality="0" ];
log2 -> window3 [processed="7"];
log2 -> join7 [processed="7"];

window3 [avg_exec_time_ns="26.39µs" errors="0" working_cardinality="1" ];
window3 -> sum4 [processed="2"];

sum4 [avg_exec_time_ns="1.169µs" errors="0" working_cardinality="1" ];
sum4 -> log5 [processed="2"];

log5 [avg_exec_time_ns="54.967µs" errors="0" working_cardinality="0" ];
log5 -> join7 [processed="2"];

join7 [avg_exec_time_ns="0s" errors="0" working_cardinality="1" ];
join7 -> alert8 [processed="0"];

alert8 [alerts_triggered="0" avg_exec_time_ns="0s" crits_triggered="0" errors="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" working_cardinality="0" ];
}
```

To get this TickScript to work, I simply had to insert additional points.

**Comment by rbetts** [comment]
Can you describe what you are trying to accomplish?
Ryan.

**Comment by Manoj321** [comment]
As I saw this originally.

Here I basically want to get alerted only if a server is not running builds for long period ie, look at past 6hr(a point comes in every hour) window and if it's < 0 and current build count is also <0 then trigger crit.

**Comment by nathanielc** [comment]
Kapacitor buffers data, since data is arriving on hour intervals buffering a single point delays the alert by an hour. There are two places this script is buffering data:

1. The window node has been instructed to buffer 6 points (6h) of data before emitting any data, this is because of the .fillPeriod property.
2. The join node needs to buffer data to ensure it processes data in order accurately.

As a result adding more data fixes the issue because it pushes data through the task. As a workaround you can send data more frequently. In addition you can rewrite the task as a batch task so that there isn't a 6 hour warm up period for the task.

**Comment by Manoj321** [comment]
Let me give you more details, which I think I gave to the support team. They were able to reproduce this issue as well.

First of all I shouldn't have mentioned one hour window my bad, please ignore it. That applies only in our production.

As the tick script is written it should produce an alert every 6th point given that lamda is satisfied. In this case if you insert following data, it doesn't trigger CRIT.

 myServerStats,host=myHost1 myBuilds=-1i
 myServerStats,host=myHost1 myBuilds=-1i
 myServerStats,host=myHost1 myBuilds=-1i
 myServerStats,host=myHost1 myBuilds=0i
 myServerStats,host=myHost1 myBuilds=0i
 myServerStats,host=myHost1 myBuilds=-1i  <- this should trigger crit.
 myServerStats,host=myHost1 myBuilds=2i

Inserting more data triggers CRIT but that doesn't solve this issue. I'm trying to write a unit test for this tick which expects one CRIT and OK but it continuously fails. May be there's a bug in join(timestamps for both pipelines are same)?

For more info please look at the log file I provided to support-team over email.

**Comment by ono760** [comment]
Closing this GitHub issue; I opened an EAR instead.
