### ISSUE TITLE
UDF unable to read pickle file

### ISSUE THREAD

**Issue by mrishansharma** [influxdata/kapacitor#1808]

**Comment by mrishansharma** [comment]
Was experimenting with kapacitor to check if I could add machine learning models in a user defined function.
Was able to successfully do it.

**Comment by MASIFAYUB** [comment]
can u share the resource brother how did u add the ML model with Kapacitor ?

**Comment by mrishansharma** [comment]
https://docs.influxdata.com/kapacitor/v1.6/guides/anomaly_detection/
