### ISSUE TITLE
add ability to determine if Kapacitor version is OSS or Enterprise

### ISSUE THREAD

**Issue by kevinhogan111** [influxdata/kapacitor#1811]
It'd be great to add the ability to easily determine if Kapacitor is running the OSS or Enterprise version.

When you type in: `kapacitord version`
the output now is: Kapacitor 1.4.0 

This request is to add output to the version command to determine OSS vs Enterprise.

**Comment by nathanielc** [comment]
Ensure `kapacitor stats general` also shows the correct version information.

**Comment by russorat** [comment]
awesome!
