### ISSUE TITLE
OpsGenie v2 Support

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#1819]
Comparing https://docs.opsgenie.com/docs/alert-api to https://docs.opsgenie.com/docs/alert-api-deprecated it looks like there are a few difference:

* The authentication method changes from a property of the JSON body to an HTTP header
* The team/recipients properties are combined into a respondents  list. Teams are `{"name":"team name","type":"team"}` and recipients are `{"username": "user name","type":"user"}`.

At this point I believe we can switch to using the new API without needing to create a new config or handler. Simply updating the existing code should be enough.

**Comment by russorat** [comment]
link https://github.com/influxdata/kapacitor/issues/1708
