### ISSUE TITLE
OpsGenie - Report tags as extra properties (Feature request)

### ISSUE THREAD

**Issue by abadyan-vonage** [influxdata/kapacitor#1821]
Currently the only extra fields reported to opsgenie are level and monitoring tool (which is always Kapacitor). All other data is reported as a big a$$ json. OpsGenie doesn't support searching inside this json so that information has very limited usability.
Looking at the code, it doesn't look very hard to dynamically turn all tags of the alerts into extra properties, making it much easier to use. I can help with a pull request if you think this is a good idea.

**Comment by nathanielc** [comment]
@abadyan-vonage I am in the middle of reworking the OpsGenie integration for their v2 API. I'll take a look at this as I do. I'd appreciate any testing/feedback you can give once I have it up.

**Comment by nathanielc** [comment]
@abadyan-vonage I have a PR up #1823 that uses the new v2 API and adds the tags as you suggests. We'd appreciate any feedback/testing you can provide.
