### ISSUE TITLE
Need to document KAPACITOR_USERNAME/KAPACITOR_PASSWORD

### ISSUE THREAD

**Issue by udf2457** [influxdata/kapacitor#1822]
The Cronograf docs make mention of `$KAPACITOR_USERNAME` and `$KAPACITOR_PASSWORD` however the Kapacitor docs are silent on this, as is the default sample kapacitor.conf file.

**Comment by nathanielc** [comment]
@udf2457 What chronograf docs are you referring to? Kapacitor does not have support for those env vars.

**Comment by stevebang** [comment]
Chronograf has some [configuration options for Kapacitor](e.g., https://docs.influxdata.com/chronograf/v1.4/administration/config-options/#kapacitor-username), but they could only be used to define one instance using the CLI or even using the environment variables. If you use the Chronograf UI, you can define multiple Kapacitor instances. The current plan is to deprecate these configuration options in a future release.

**Comment by stevebang** [comment]
Closing this since the functionality does not exist in Kapacitor and is going to be deprecated in Chronograf.
