### ISSUE TITLE
Add support for sending Alerts to Kafka queue

### ISSUE THREAD

**Issue by russorat** [influxdata/kapacitor#1826]
connect https://github.com/influxdata/kapacitor/pull/956

This feature would add an alert node that could be configured to send alerts to a kafka queue.

related ui issue https://github.com/influxdata/chronograf/issues/2904

**Comment by rbetts** [comment]
Acceptance criteria:
 
- Support most recent Kafka API model. 
  - Configure the topic (assuming all configuration is in Kafka per-topic)
- Support same output format as HTTP POST (json, templates)

**Comment by russorat** [comment]
i don't see this node showing up in the API configs in 1.5.0rc1. http://localhost:9092/kapacitor/v1/config/kafka

**Comment by nathanielc** [comment]
@russorat Looking into this I think I know what is going on...

Kafka allows multiple config sections to be defined and by default no sections exist.

You can add this to your config and you will see it appear via the config API:

```toml
[[kafka]]
  enabled = false
  id = "default"
  brokers = ["localhost:9083"]
```

Alternatively you can use the config API to dynamically add a new configuration section for kafka. https://docs.influxdata.com/kapacitor/v1.4/working/api/#overriding-configurations

**Comment by russorat** [comment]
@nathanielc thanks for this. I see it after configuring. how should Chronograf figure out what alert nodes are available to configure? is there an API that lists all available alerts nodes so we can know what to show in the UI? this is useful in case someone is running an older version of Kapacitor without kafka available.
