### ISSUE TITLE
Issue with combining two measurements in tickscript

### ISSUE THREAD

**Issue by arushigangrade** [influxdata/kapacitor#1832]
I have two measurements cpu and mem. They have a field called value, which has integer numbers. Is there a way I could write a tickscript to alert me when cpu value >90 and mem value >90.?

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the community board at [community.influxdata.com](https://community.influxdata.com/).

Have a look at this https://docs.influxdata.com/kapacitor/v1.4/nodes/join_node/
