### ISSUE TITLE
[bug] Using a variable in place of "stream" in Kapacitor v1.4 no longer works.

### ISSUE THREAD

**Issue by danyli78** [influxdata/kapacitor#1834]
In Kapacitor v1.4, the below code doesn't work if you use a variable (e.g, task_type) instead of the word stream. When doing "define" tasks, it say Unknown task type.

```
var task_type = stream

var data = task_type
  |from()
....
```

It works fine in Kapacitor v1.3.3

**Comment by nathanielc** [comment]
Fixed in #1851
