### ISSUE TITLE
Alerts firing for stale thresholds after reload

### ISSUE THREAD

**Issue by lpalm** [influxdata/kapacitor#184]
I have an alert set up like this:

```javascript
var delays = stream
  .from()
    .database('DBNAME')
    .measurement('MEASUREMENT')
    .groupBy('TAG1')
    .window()
      .period(1h)
      .every(30s)


delays.alert()
    .id('kapacitor//{{ index .Tags "TAG1" }}')
    .message('{{ .ID }} is  {{ .Level }} MEASUREMENT:{{ index .Fields "value" }}')
    .info(lambda: "value" > 500000)
    .crit(lambda: "value" > 1000000)
    .email('my@email.com')
```

The info and crit thresholds were previously 100 and 1000. Last night I disabled the task, changed and saved the tick script to use the much higher thresholds and today I reloaded and enabled the task. 

kapacitor disable TASK // last night
vi TASK.tick  // edit to increase thresholds
kapacitor reload TASK  // Seems to restart the task according to the logs
kapacitor enable TASK // Just in case

However I started getting emails for INFO alerts when value was >100 and CRITICAL when above 1000. So it seems that reload isn't changing the alert thresholds to match the tick script as I expected.

Deleting the task, defining and enabling it again seems to work, but that makes the reload command seem redundant if it does nothing without a redefine. What's the correct usage for define/reload?

Thanks!

**Comment by lpalm** [comment]
Looks like https://github.com/influxdata/kapacitor/issues/173 would address this. I'm still interested in knowing what the use cases for a (re)define without a reload, and for a reload without a file change + (re)define are.

**Comment by nathanielc** [comment]
@lpalm This issue is that you did not define the task again and you are correct #173 will make this less confusing. 

The steps should be:
```sh
kapacitor disable TASK // last night
vi TASK.tick // edit to increase thresholds
kapacitor define -name TASK -tick TASK.tick
kapacitor reload TASK // Seems to restart the task according to the logs
```

But after #173 it can be:
```
kapacitor disable TASK // last night
vi TASK.tick // edit to increase thresholds
kapacitor define -name TASK -tick TASK.tick -reload
```

But the define step is always necessary since Kapacitor stores its own copy of the TICKscript and editing your copy will have no effect on Kapacitor.

**Comment by lpalm** [comment]
Thanks, @nathanielc.
When would the define command without -reload be useful for a task that was already previously defined? I.e. should the -reload flag be implicit when the task is already defined for consistency with the behavior when the task was not previously defined?

Also, given your reply and #173, we may want to update the "getting started" documentation:
"Any time you want to update a task change the TICKscript and then run the define command again with _just the -name and -tick arguments:_"

**Comment by nathanielc** [comment]
@lpalm The use case I had in mind it a edit/verify/publish workflow where there is an explicit verification step in between defining and enabling a task. But that is by far a less common use case and so I have changed the default behavior to reflect that. See #173 again for updates.
