### ISSUE TITLE
Not able to combine two measurements in a single TickScript

### ISSUE THREAD

**Issue by arushigangrade** [influxdata/kapacitor#1841]
Hi

I have two measurements cpu and mem in my own database in Influx. I want to do a combined alert on both of them as when cpu >70 and mem >90. I have a python script in place to populate the Influxdb measurements.I have written the following tick script-

var m1 = stream
    |from()
        .measurement('cpu')
	       
var m2 = stream
    |from()
        .measurement('mem')
   
var data = m1
    |join (m2)
          .as('m1','m2')

data
    |alert()
        .crit(lambda: "value">70 AND "m2.value" >90)
        .message('CPU usage is high as {{ index .Fields "m1.value" }} and Mem usage is high as {{ index .Fields "m2.value" }}')
        .log('/var/log/kapacitor/two-metric-alert.log')

I have defined the task in Kapacitor, and I am able to record a stream alert. When I list the recording it shows  the following-

ocker exec tik_kapacitor_1 kapacitor list recordings f020f7a1-f1d4-452f-8b5b-382fe47b24af
ID                                   Type    Status    Size      Date                   
f020f7a1-f1d4-452f-8b5b-382fe47b24af stream  finished  965 kB    08 Mar 18 20:34 UTC 

I do know that when you replay the recording, alerts are written in the log file I mentioned above. Though that is not happening. So I am not sure if my script is wrong or there are no alerts generated.
Kindly help

**Comment by AAbouZaid** [comment]
>  .crit(lambda: "value">70 AND "m2.value" >90)
`value` should be `m1.value`.

**Comment by arushigangrade** [comment]
Thanks AAbouZaid.!
I figured that out and it worked. Though I forgot to close the issue.
