### ISSUE TITLE
Hi, i need help using difference node in tickscript

### ISSUE THREAD

**Issue by ctaity** [influxdata/kapacitor#1850]
I hace a mesurement like this

TIME iD SOLD_QUANTITY
XXX  1    1
XXX  1    2
XXX  1    2
XXX  2   1
XXX  2   1

I wish with kapacitor get the difference betweent last value and new value with stream. I trying to do:

dbrp "ml"."autogen"

> stream
>   |from().measurement('items').groupBy('item_id')
>   |window().period(1d)
>   |difference('sold_quantity')
>   |log()
> 

But dont work, some body can help me. Thanks

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the community board at [community.influxdata.com](https://community.influxdata.com/).
