### ISSUE TITLE
eval :: returns NaN when dividing by 0

### ISSUE THREAD

**Issue by arturo-mondelo** [influxdata/kapacitor#1855]
Hi,
I have to set up a tick that alerts when the errors percent raise the given threshold. The problem is when there are not errors (aka, 0) and the division between erros/count is giving NaN.

Is there any way to force this results to be 0? I mean: 0/x=0 and also x/0=0??

Thanks in advance!

Regards

**Comment by heiderich** [comment]
From a mathematical point of view, division by 0 is not defined. So x/0 should not be 0.

**Comment by docmerlin** [comment]
For floating point numbers division by zero is defined as NaN.  This is not a bug.
