### ISSUE TITLE
Reset alerts ignores ".all()" property method.

### ISSUE THREAD

**Issue by AAbouZaid** [influxdata/kapacitor#1859]
When alert node has `.all()` property method, it's triggered only if all points in a batch match the criteria.
The same should happen to reset the alert, all points should match the filter expression (crit, warn, etc).

But what happens now it matches all points to alert, but only 1 point to reset the alert.
Also I did try to use `critReset`, but no change.

This has been tested with:
```
Kapacitor 1.3.0 (git: master 7e27fd070e6a629a9b760c6300fade41364f4c7f)
Kapacitor 1.4.0 (git: HEAD fcce3ee9e6abcee5595fd61066bfc904edb1e113)
```
I believe that wasn't the case with version `1.1.0`.

-----------------------

### More details.

TICKScript:
```
var source01 = batch
    |query('''
        SELECT percentile("used_percent", 95.0) AS "used_percent"
        FROM "telegraf"."autogen"."mem"
    ''')
        .groupBy(time(1m), 'host')
        .period(5m)
        .every(2m)
        .fill('none')

var source02 = batch
    |query('''
        SELECT last("memory") AS "memory"
        FROM "db"."rp"."measurement"
    ''')
        .groupBy(time(1m), 'host')
        .period(5m)
        .every(2m)
        .fill('none')

var data = source01
    |join(source02)
        .as('s1', 's2')
    |eval(lambda: "s1.used_percent", lambda: "s2.memory")
        .as('used_percent', 'memory')

data
    |alert()
        .all()
        .flapping(0.25, 0.5)
        .id('memory_usage')
        .message('memory_usage')
        .stateChangesOnly()
        .crit(lambda: "used_percent" > 95 AND "memory" == 'default')
        .log(alert_log_file)
```

Data:
```
# Crit alert - all points should be "above" 95, which is the case here.
{"id":"memory_usage","message":"memory_usage","details":"{"Name":"mem","TaskName":"memory_used_percent","Group":"host=testhost01","Tags":{"host":"testhost01"},"ServerInfo":{"Hostname":"kapacitor","ClusterID":"791c7b72-8b4c-4d9a-9a35-d122a2bf295b","ServerID":"f70f707e-4be7-4d5b-acf6-11e18ef78dcb"},"ID":"memory_usage","Fields":{"memory":"default","used_percent":96.08808433572959},"Level":"CRITICAL","Time":"2018-03-14T17:27:00Z","Duration":0,"Message":"memory_usage","time":"2018-03-14T17:27:00Z","duration":0,"level":"CRITICAL","data":{"series":[{"name":"mem","tags":{"host":"testhost01"},"columns":["time","memory","used_percent"],"values":[["2018-03-14T17:23:00Z","default",96.08808433572959],["2018-03-14T17:24:00Z","default",95.54605882306421],["2018-03-14T17:25:00Z","default",95.57116815740983],["2018-03-14T17:26:00Z","default",95.33342032630271],["2018-03-14T17:27:00Z","default",95.22813906221579]]}]},"previousLevel":"OK"}

# Crit reset - all points should be "below" 95.
{"id":"memory_usage","message":"memory_usage","details":"{"Name":"mem","TaskName":"memory_used_percent","Group":"host=testhost01","Tags":{"host":"testhost01"},"ServerInfo":{"Hostname":"kapacitor","ClusterID":"791c7b72-8b4c-4d9a-9a35-d122a2bf295b","ServerID":"f70f707e-4be7-4d5b-acf6-11e18ef78dcb"},"ID":"memory_usage","Fields":{"memory":"default","used_percent":95.22813906221579},"Level":"OK","Time":"2018-03-14T17:31:00Z","Duration":240000000000,"Message":"memory_usage","time":"2018-03-14T17:31:00Z","duration":240000000000,"level":"OK","data":{"series":[{"name":"mem","tags":{"host":"testhost01"},"columns":["time","memory","used_percent"],"values":[["2018-03-14T17:27:00Z","default",95.22813906221579],["2018-03-14T17:28:00Z","default",95.07392425284903],["2018-03-14T17:29:00Z","default",95.13561017659573],["2018-03-14T17:30:00Z","default",94.99780540463594],["2018-03-14T17:31:00Z","default",94.91812775312977]]}]},"previousLevel":"CRITICAL"}
```

**Comment by nathanielc** [comment]
@AAbouZaid The negation of an `all` condition is an `any` condition. Meaning that if the condition is that all points must match then if any one point does not then the condition is not met.

Can you provide some example data and what you want the alert to do with that data?

**Comment by AAbouZaid** [comment]
@nathanielc what simply I'm looking for (without any complex stuff), for example if memory greater than 90% for `5m` fire an alert (which is the case here using `.all`)
And reset the alert if memory less than 90% for `5m` (5 points in row).

**Comment by nathanielc** [comment]
OK, in that case take the min and max of the 5m window and use those values in the alert. If the min is above 90 then alert, if the max is below 90 recover the alert.

**Comment by AAbouZaid** [comment]
That's the point, I believe that should be done through the DSL itself, so
no need to handel this case everytime.

Specifically `all` is already here.

**Comment by nathanielc** [comment]
For backwards compatibility reasons we cannot change the existing behavior for `all`. The existing behavior treats `any` as the negation of `all` and we must preserve that behavior.

I would argue that using explicit `max` and `min` values in the alert criteria makes what you are trying to do more clear. Since there is already another interpretation of the `.all` property, it avoid any confusion.

Closing this issue now, as there is a solution for the use case and we cannot change the existing `.all` behavior.

**Comment by AAbouZaid** [comment]
No problem, I create another request to add this as a new property method
(y).
