### ISSUE TITLE
OpsGenie2 service-tests API error

### ISSUE THREAD

**Issue by marsn** [influxdata/kapacitor#1865]
```
POST /kapacitor/v1/service-tests/opsgenie2
{
    "teams": null,
    "recipients": null,
    "message-type": "OK",
    "message": "test opsgenie message",
    "entity-id": "testEntityID"
 }
```
Runtime error: index out of range - kapacitor/services/opsgenie2/service.go:191

**Comment by rbetts** [comment]
`details.series[0]` is out of range. `details` is a `models.Result`.   I don't know if it is valid to have no series and if this needs to write `range` more safely or if having series present is a pre-condition, though.

**Comment by denispesikov** [comment]
Hey guys! is there any workaround for using OpsGenie API v2 with Kapacitor v1.4.1 before v1.5 will be released? Thnx!
