### ISSUE TITLE
Kapacitor UDF in Python 3

### ISSUE THREAD

**Issue by jaapz** [influxdata/kapacitor#1868]
Do you have any plans on supporting the python udf package to run in python 3?

**Comment by francisconroy** [comment]
This is absolutely essential, and from what I can tell the changes required are minimal. Libraries I would like to use with the Agent are only working properly in python 3. Is it possible to fork and submit a pull request as public contributor?

**Comment by voiprodrigo** [comment]
I'm having problems trying to run UDF with Python 3.6 (Anaconda).
What would be the required changes for it to work?
