### ISSUE TITLE
Search function for documentation on web site!?

### ISSUE THREAD

**Issue by johankcarlsson** [influxdata/kapacitor#188]
I'm not able to free search in the Kapacitor documentation on the web.
Have I missed the search function?

If there is non please add the possibility to search freely in the whole (syntaxt) document.
That is applicable for all InfluxDB docs.
/Johan

**Comment by rossmcdonald** [comment]
@johankcarlsson Search functionality should be coming soon. In the meantime, you can search the documentation repository directly using Github's search [here](https://github.com/influxdata/docs.influxdata.com/search?utf8=%E2%9C%93&q=).

**Comment by rossmcdonald** [comment]
Search is now functional on the docs site.
