### ISSUE TITLE
failed to send alert data to Slack: failed to understand Slack response

### ISSUE THREAD

**Issue by enviroeye** [influxdata/kapacitor#189]
Hi there,

Having some issues with Slack integration. Enabled Slack in the .conf file, and added in the webhook URL for my channel to the .conf file. (I tested the URL using curl and successfully received an alert.). I then restarted Kapacitor to pick up the changes to the configuration. However within Kapacitor all is not well and I am receiving the follow error:

[humidity_alert:alert2] 2016/01/31 10:24:33 E! failed to send alert data to Slack: failed to understand Slack response

Output from 'show' task as follows:

Name: humidity_alert
Error: 
Type: stream
Enabled: true
Executing: true
Databases Retention Policies: ["mydb"."default"]
TICKscript:
stream
    // Select just the cpu_usage_idle measurement from our example database.
.from().measurement('pilot_data')
    .alert()
        .crit(lambda: "hum" <  70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')
        .slack()
        .channel('#alerting')

DOT:
digraph humidity_alert {
stream0 -> stream1 [label="49"];
stream1 -> alert2 [label="49"];
}

**Comment by nathanielc** [comment]
My first guess is that you have a different kind of slack integration. Did you create a https://slack.com/services/new/incoming-webhook or some other kind of slack integration? The error message is vague and not helpful, so I'll update the error message so we can get a better understanding of the issue.

**Comment by enviroeye** [comment]
Cool, sounds like a plan.

Yeap, I did create one at the URL above, and have a resulting URL in the format:

https://hooks.slack.com/services/<integration_token>

Section from my .conf file

[slack]
  enabled = true 
  url = "https://hooks.slack.com/services/<my_integration_token>"
  channel = "alerting"
  global = false

**Comment by nathanielc** [comment]
@enviroeye Can you build from master and see what error message you receive now?

**Comment by enviroeye** [comment]
You'll have to pardon me, as I've not programmed with Go before. But when I try and build from the master I get the following errors during complilation:

# github.com/influxdb/influxdb/client
/home/ubuntu/go/src/github.com/influxdb/influxdb/client/influxdb.go:121:28: error: unknown field â€˜Timeoutâ€™ in â€˜http.Clientâ€™
   httpClient: &http.Client{Timeout: c.Timeout},
                            ^
# github.com/influxdata/kapacitor/tick
/home/ubuntu/go/src/github.com/influxdata/kapacitor/tick/parser.go:91:18: error: reference to undefined identifier â€˜strings.LastIndexByteâ€™
  if i := strings.LastIndexByte(p.Text[start:tok.pos], '\n'); i != -1 {
                  ^
# github.com/influxdb/influxdb/services/meta
/home/ubuntu/go/src/github.com/influxdb/influxdb/services/meta/response_logger.go:151:19: error: reference to undefined field or method â€˜BasicAuthâ€™
   if u, _, ok := r.BasicAuth(); ok {
                   ^
(null):0: confused by earlier errors, bailing out

Please let me know if it's something to do with my build environment. I notice the first error it to do with and Influxdb package, which I have not rebuilt.

Mark

**Comment by nathanielc** [comment]
@enviroeye Do you have access to docker? If so running `./build.sh` from the repo will build the code in a docker container. The container will setup the go env and everything else for you so your host machine doesn't need anything but docker installed. The binaries from the build are placed in the `./build` directory.  Note that the docker build will take a while the first time since it has to compile a few dependencies from source, so just be patient. 

Otherwise it looks like your GOPATH is somehow corrupted. I recommend creating  a new clean GOPATH directory for just the Kapacitor project.

Also we setup our build process to create nightly builds of Kapacitor last night. So once I verify they worked I'll post a link here so you can just grab to build yourself. Thanks for working with us.

**Comment by nathanielc** [comment]
Here are the links to the nightly builds.

RPM
https://s3-us-west-1.amazonaws.com/kapacitor-nightly/kapacitor-nightly.x86_64.rpm

DEB
https://s3-us-west-1.amazonaws.com/kapacitor-nightly/kapacitor_nightly_amd64.deb

Binaries
https://s3-us-west-1.amazonaws.com/kapacitor-nightly/kapacitor-nightly_linux_amd64.tar.gz

**Comment by enviroeye** [comment]
Install nightly build all okay, message recieved from Slack was 'bad token'. Regenerated the webhooks URL in Slack, (which also regenerates the token) and all is working now. Had a typo in one of my channel definitions too, which showed up in the log, so having the actual error message from Slack is very helpful.

Looking good now, have things working with Slack, OpsGenie, VictorOps and an Rest API for an SMS service here is Australia.

Awesome potential in what you guys are building, keep up the great work.

Mark

**Comment by nathanielc** [comment]
@enviroeye Glad to here it.
