### ISSUE TITLE
Unable to test additional Slack nodes in Kapa 1.5rc3

### ISSUE THREAD

**Issue by russorat** [influxdata/kapacitor#1923]
i have two workspaces configured, one is named `test`, and the other is named `something`. When i try `curl -XPOST http://localhost:9092/kapacitor/v1/service-tests/slack -d '{"workspace":"something"}'`

It makes a request to the `test` workspace
`{"success":false,"message":"Post not%20a%20url: unsupported protocol scheme \"\""}`

**Comment by rbetts** [comment]
@russorat can you include your configuration here?

**Comment by russorat** [comment]
@rbetts i can, but i'm configuring all of this through the API and can't publish the urls. to reproduce, set up two slack configurations and name each workspace with different names, put a valid url in the second workspace, and an invalid url in the first one, then try to call `/kapacitor/v1/service-tests/slack` on the second workspace.

```
{"link":{"rel":"self","href":"/kapacitor/v1/config/slack"},"elements":[{"link":{"rel":"self","href":"/kapacitor/v1/config/slack/russtest"},"options":{"channel":"#random","default":true,"enabled":true,"global":false,"icon-emoji":"","insecure-skip-verify":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","state-changes-only":false,"url":true,"username":"","workspace":"russtest"},"redacted":["url"]},{"link":{"rel":"self","href":"/kapacitor/v1/config/slack/snickname"},"options":{"channel":"#general","default":false,"enabled":true,"global":false,"icon-emoji":"","insecure-skip-verify":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","state-changes-only":false,"url":true,"username":"","workspace":"snickname"},"redacted":["url"]}]}

```
