### ISSUE TITLE
[alerta] There is no option for "severity"

### ISSUE THREAD

**Issue by madshall** [influxdata/kapacitor#193]
There's no option to specify the severity of an alert which makes the integration pretty useless. Could you please add this method?

**Comment by nathanielc** [comment]
@madshall The severity is mapped from the Kapacitor Alert Level to the Alerta Severity. 

As a result specifying the severity explicitly would not allow it to be dynamic based on the data being evaluated. The mappings are as follows:

| Kapacitor Alert Level | Alerta Severity |
| ----------------------------| ---------------------|
| OK | OK |
| Info | Informational| 
| Warn | Warning |
| Crit | Critical|


The other Severities listed here http://docs.alerta.io/en/latest/api/alert.html#severity-table are not possible to define within Kapacitor. If you specifically needed one of those severities then we can look for a solution. 

Example:

```javascript
stream
 ....
 .alert()
   .info(lambda: "value" > 5)
   .warn(lambda: "value" > 10)
   .crit(lambda: "value" > 15)
   .alerta()
```

So for a given value the alerta severity would be as follows:

| Value | Alert Severity|
|---------|-------------------|
| 1| ok |
|6 | informational |
| 13 | warning |
| 23 | criticial|
