### ISSUE TITLE
Kafka missing topic leads to panic

### ISSUE THREAD

**Issue by russorat** [influxdata/kapacitor#1935]
If a user creates a Kafka alert node without specifying a kafka topic, it will panic Kapacitor.

```
panic: cannot create a kafka writer with an empty list of brokers

goroutine 94 [running]:
github.com/influxdata/kapacitor/vendor/github.com/segmentio/kafka-go.NewWriter(0x0, 0x0, 0x0, 0x0, 0x0, 0xc4205f2540, 0x2ea41c0, 0xc420a30a80, 0x0, 0x0, ...)
	/Users/rsavage/go/src/github.com/influxdata/kapacitor/vendor/github.com/segmentio/kafka-go/writer.go:165 +0x3b2
github.com/influxdata/kapacitor/services/kafka.(*Cluster).writer(0xc4200f42c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rsavage/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:63 +0x28a
github.com/influxdata/kapacitor/services/kafka.(*Cluster).WriteMessage(0xc4200f42c0, 0x0, 0x0, 0xc4210ef930, 0xd, 0x10, 0xc421162000, 0x4e9, 0x4e9, 0x0, ...)
	/Users/rsavage/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:39 +0x5d
github.com/influxdata/kapacitor/services/kafka.(*handler).Handle(0xc4207f4c80, 0xc4204e3b40, 0x3e, 0xc420eb6510, 0xd, 0x0, 0x0, 0xc4206fcb00, 0x285, 0x0, ...)
	/Users/rsavage/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:265 +0x2bd
github.com/influxdata/kapacitor/alert.(*bufHandler).run(0xc420abe0f0)
	/Users/rsavage/go/src/github.com/influxdata/kapacitor/alert/topics.go:440 +0x7a
github.com/influxdata/kapacitor/alert.newHandler.func1(0xc420abe0f0)
	/Users/rsavage/go/src/github.com/influxdata/kapacitor/alert/topics.go:397 +0x57
created by github.com/influxdata/kapacitor/alert.newHandler
	/Users/rsavage/go/src/github.com/influxdata/kapacitor/alert/topics.go:395 +0xf2
```

**Comment by dp1140a** [comment]
It appear that even if you do specify the topic this will sometimes occur.  The following config and TICK script panic when an alert is created:

========= kapcitor.conf ==========
[[kafka]]
  enabled = true
  id = "kafka-cluster"
  brokers = ["robot-kafka:9092"]
  timeout = "10s"
  batch-size = 100
  batch-timeout = "1s"
  use-ssl = false
  ssl-ca = ""
  ssl-cert = ""
  ssl-key = ""
  insecure-skip-verify = false

========= tick script ========

var cpu_one_minute_threshold = 1
stream
|from()
	.measurement('myMeasurement')
	.groupBy('Producer', 'node-name') 
|alert()
	.crit(lambda: int(\"total-cpu-one-minute\") >= 0 )
	.log('/var/log/robot/ticks_alert.log')
	.message('test of jzj6 cpu')
	.kafka()
		.cluster('kafka-cluster')
		.kafkaTopic('cpu_alerts')

==========error==============
panic: cannot create a kafka writer with an empty topic

goroutine 2181 [running]: 
panic(0x1c45200, 0x229e220) 
/usr/local/go/src/runtime/panic.go:551 +0x3c1 fp=0xc423fa9400 sp=0xc423fa9360 pc=0x42c681 
github.com/influxdata/kapacitor/vendor/github.com/segmentio/kafka-go.NewWriter(0xc420604430, 0x1, 0x1, 0x0, 0x0, 0xc423ed2fc0, 0x22a4ac0, 0xc420af7b00, 0x0, 0x0, ...) 
/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/segmentio/kafka-go/writer.go:169 +0x394 fp=0xc423fa9450 sp=0xc423fa9400 pc=0x1888084 
github.com/influxdata/kapacitor/services/kafka.(*Cluster).writer(0xc4202d2bb0, 0x0, 0x0, 0x0, 0x0, 0x0) 
/root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:63 +0x28a fp=0xc423fa96b8 sp=0xc423fa9450 pc=0x18929ca 
github.com/influxdata/kapacitor/services/kafka.(*Cluster).WriteMessage(0xc4202d2bb0, 0x0, 0x0, 0xc42403ddc0, 0x70, 0x70, 0xc4239ac800, 0x75f, 0x75f, 0x0, ...) 
/root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:39 +0x5d fp=0xc423fa97d8 sp=0xc423fa96b8 pc=0x18925bd 
github.com/influxdata/kapacitor/services/kafka.(*handler).Handle(0xc423b5b740, 0xc422addcc0, 0x31, 0xc42403dd50, 0x70, 0xc423cd1ac0, 0xf, 0xc420956c00, 0x3d6, 0xf7f4900, ...) 
/root/go/src/github.com/influxdata/kapacitor/services/kafka/service.go:265 +0x2bd fp=0xc423fa9b28 sp=0xc423fa97d8 pc=0x189498d 
github.com/influxdata/kapacitor/alert.(*bufHandler).run(0xc423cdd0b0) 
/root/go/src/github.com/influxdata/kapacitor/alert/topics.go:440 +0x7a fp=0xc423fa9fb0 sp=0xc423fa9b28 pc=0x72589a 
github.com/influxdata/kapacitor/alert.newHandler.func1(0xc423cdd0b0) 
/root/go/src/github.com/influxdata/kapacitor/alert/topics.go:397 +0x57 fp=0xc423fa9fd8 sp=0xc423fa9fb0 pc=0x7263c7 
runtime.goexit() 
/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc423fa9fe0 sp=0xc423fa9fd8 pc=0x45be91 
created by github.com/influxdata/kapacitor/alert.newHandler 
/root/go/src/github.com/influxdata/kapacitor/alert/topics.go:395 +0xf2

**Comment by ertaoxu** [comment]
I had met the same problem.
