### ISSUE TITLE
Alerts with boolean not working with templates

### ISSUE THREAD

**Issue by tarunhg** [influxdata/kapacitor#1943]
I am able to create an alert using chronograf based on a field's value of true or false. When I try to replicate it using a template and a task, it starts failing with 

ts=2018-05-22T18:53:01.301Z lvl=error msg="error evaluating expression for level" service=kapacitor task_master=main task=smart_health node=alert3 err="mismatched type to binary operator. got string == boolean. see bool(), int(), float(), string(), duration()" level=CRITICAL

----template-----
var crit lambda
var trigger = data
   |alert()
     .crit(lambda: "value" == crit)
     .stateChangesOnly()

----task----
  field:
    type: string
    value: health_ok
  crit: 
    type: lambda
    value: ("value" == TRUE)

I understand the error message but not sure why it is being thrown as I am not seeing this behaviour for int/float values. Any ideas?

**Comment by faskiri** [comment]
value: bool("value") == TRUE

**Comment by tarunhg** [comment]
Thanks @faskiri. Other issue  was missing field in the template.

`   |last(field)`
 `.as('value')`

**Comment by xkfen** [comment]
lambda: "value" == bool(1)
