### ISSUE TITLE
Cannot enable stats via env variables

### ISSUE THREAD

**Issue by benishak** [influxdata/kapacitor#1953]
I'm using Kapacitor 1.4 via Docker 

here are my configuration

```
KAPACITOR_HTTP_BIND_ADDRESS | :9092
KAPACITOR_INFLUXDB_0_DEFAULT | true
KAPACITOR_INFLUXDB_0_ENABLED | true
KAPACITOR_INFLUXDB_0_KAPACITOR_HOSTNAME | kapacitor.local
KAPACITOR_INFLUXDB_0_NAME | my-influx
KAPACITOR_INFLUXDB_0_PASSWORD | ***
KAPACITOR_INFLUXDB_0_URLS_0 | ***
KAPACITOR_INFLUXDB_0_USERNAME | ***
KAPACITOR_LOGGING_LEVEL | WARN
KAPACITOR_SLACK_ENABLED | true
KAPACITOR_SLACK_URL | ***
KAPACITOR_SLACK_USERNAME | ***
KAPACITOR_STATS_DATABASE | _kapacitor
KAPACITOR_STATS_ENABLED | true
KAPACITOR_STATS_RETENTION_POLICY | default
KAPACITOR_STATS_STATS_INTERVAL | 30s
```

Are there any other steps I need to follow before and after setting these variables ?

**Comment by faskiri** [comment]
What do you mean by not enabled? If you meant that it is not showing up in influx, you have to do this:
```
$ echo "{\"status\": \"enabled\", \"id\": \"_publish_statss\", \"dbrps\": [ { \"db\": \"_kapacitor\", \"rp\": \"autogen\" } ], \"type\": \"stream\", \"script\" : \"stream|from()|influxDBOut().create().database('kapacitor').retentionPolicy('autogen'.measurement('stats_')\" }" | curl ewr01-nomad04.$v:9092/kapacitor/v1/tasks -d@- -v
```
This is not an issue per-se, more of a documentation missing it seems

**Comment by benishak** [comment]
thanks that worked great!
although I was already using a tickscript that I manually created via Chronograf and looked like this

```
stream|from().database(’_kapacitor’).retentionPolicy(‘default’)
```

and before that I was created the database also manually from Chronograf but it did not work.


with your curl command worked fine, maybe there were issue in tickscript

this should be documented somewhere
