### ISSUE TITLE
Best way of monitoring multiple fields at once?

### ISSUE THREAD

**Issue by pootzko** [influxdata/kapacitor#197]
Hi,

this is a slightly simpler version of what I currently have:

```
stream
    .from().measurement('reading')
    .alert()
        .id('Sensor {{ index .Tags "sensorId" }}')
        .message('{{ .ID }} is {{ .Level }} (Temp: {{ index .Fields "Temperature" }}C, Humidity: {{ index .Fields "Humidity" }}%)')
        .warn(lambda: "Temperature" > 20 OR "Humidity" > 60)
        .email('oncall@example.com')
```

I have two questions regarding this. 

- Is there a smarter way of monitoring 2 different fields at the same time than putting an `OR` inside a lambda like I did here?
- Is there a way to tell which one of these two values triggered the warning/crit inside the `message()`? If I had that, I would not have to display both fields when perhaps only one of them is relevant at a certain moment.

If this is explained somewhere in the docs, sorry for the trouble, I somehow didn't find it then, but I believe I checked it all.

Thanks

**Comment by nathanielc** [comment]
@pootzko There are two ways to do what you want.

1. Using the `OR` as you have it and using conditional logic in the template itself. See golang template docs https://golang.org/pkg/text/template/. But that requires you to duplicate the logic in the lambda expression and the template which is not ideal.

2. Use two different alert nodes one for each field.

```javascript
var data = stream
    .from().measurement('reading')

// Alert for high Humidity 
data
   .alert()
        .id('Sensor {{ index .Tags "sensorId" }}')
        .message('{{ .ID }} is {{ .Level }} Humidity: {{ index .Fields "Humidity" }}%')
        .warn(lambda: "Humidity" > 60)
        .email('oncall@example.com')

// Alert for high Temperature
data
   .alert()
        .id('Sensor {{ index .Tags "sensorId" }}')
        .message('{{ .ID }} is {{ .Level }} Temp: {{ index .Fields "Temperature" }}C')
        .warn(lambda: "Temperature" > 20)
        .email('oncall@example.com')

```
A little more verbose but I think its more clear what you are trying to do.

**Comment by pootzko** [comment]
Oh ok, that's great. Thank you. 

What would you say, is there any significant performance difference between using `OR` and having two alert nodes?

**Comment by nathanielc** [comment]
There is a performance difference as more work needs to be to send the data to both alert nodes but I do not think it is significant, but I don't have any data to back that up ;) 

FYI  I am currently working to better quantify the performance characteristics so if I learn something surprising I'll post back.

**Comment by pootzko** [comment]
That would be most awesome. Thanks. :)
