### ISSUE TITLE
Kapacitor Client -  No package `github.com/influxdata/influxdb/influxql`

### ISSUE THREAD

**Issue by vanugrah** [influxdata/kapacitor#1986]
Hello - I think the following package `github.com/influxdata/influxdb/influxql` got moved here 
https://github.com/influxdata/influxql however the client still references the old import. I'm using the Kapacitor client to build a tool to co-ordinate multi-datacenter Kapacitor task/udf management 
however I'm not being able to vendor the kapacitor client due to this import.

**Comment by toni-moreno** [comment]
same problem here.

**Comment by shaodan** [comment]
you can try my fork: https://github.com/shaodan/kapacitor-client

**Comment by docmerlin** [comment]
This is fixed in v1.6.5
