### ISSUE TITLE
Reuse TICKscript 

### ISSUE THREAD

**Issue by ono760** [influxdata/kapacitor#1987]
As a user, I should be able to re-use a TICK script for multiple hosts. 

Instead of  having to create two TICKscripts/pipelines that do the same thing, one with

```go
var system_data = stream
    |from()
        .measurement(meas_name)
        .groupBy(groups)
    |where(lambda: isPreseent("creator"))
    |where(lambda: strContains("creator", 'ono'))

...

var other_system_data = stream
    |from()
        .measurement(meas_name)
        .groupBy(groups)
    |where(lambda: strContains("host", 'tick'))
```

and alert on each one independently, I should be able to use only one script to accomplish the above.

**Comment by faskiri** [comment]
Why wont the template solve this usecase? I have been using template for a while and it seems pretty good at doing what you are trying to do

**Comment by timhallinflux** [comment]
I would recommend templates too.

We use these extensively for creating reusable downsampling scripts with multiple different input variables....
