### ISSUE TITLE
Relative alert-rule always starts to alert after some time

### ISSUE THREAD

**Issue by heayin** [influxdata/kapacitor#1992]
I configured the relative rule which time-shift is 5 minutes，  task was started at 07:50:08, the first alert happened at 07:52:33.
I configured the relative rule which time-shift is 10 minutes，  task was started at 07:50:08, the first alert happened at 08:00:34.

I configured the relative rule which time-shift is 15 minutes，  task was started at 08:02:08, the first alert happened at 08:14:33.

When does the first alert happen when the relative rule is configured？What does the first alert-time depend on？

**Comment by faskiri** [comment]
There are a few nodes which have a state, e.g. join. When you say
var foo = stream|from().measurement("foo")...shift(5m)

You are basically creating a stream of values from foo *AS THE POINTS ARRIVE*, which is then shifted forward by 5m. This means, that for the first 5 mins, the stream foo has no datapoints at all.

To get around this, you can use a batch with a query:
e.g.
batch|query("SELECT foo FROM bar").period(5m).every(1m).shift(5m) which says, select foo from bar  where time >= now() - 5m. This is then shifted forward 5m and works as you would expect.

PS: The above might not work as is. It is meant to show the concept, please refer to documentation for exact syntax.

**Comment by heayin** [comment]
@faskiri Thank you very much for your reploy. I have tested the batch query. It  can not join. My tickscript is as follows:

var db = 'ocean'

var rp = 'autogen'

var measurement = 'cpu'

var groupBy = []

var whereFilter = lambda: TRUE

var period = 10s

var every = 30s

var name = 'wbg-relative-test1'

var idVar = name

var message = ' {{.ID}} {{.Name}}'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'relative'

var shift = 1m

var crit = -1000

var data = batch
    |query('''SELECT count(usage_idle) as value FROM "ocean"."autogen"."cpu" ''')
        .period(period)
        .every(every)
        .groupBy('10s')

var data2 = data
    |shift(shift)

var join = data
    |join(data2)
        .as('current', 'past')

data
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement('data')

data2
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement('data2')

join
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement('b_join')

The script runs at a period of 30s. 
One record is inserted into measurement data. It is as follows:

time                                                | value
2018-07-05T06:25:33.043003714Z | 98
One record is inserted into measurement data2. It is as follows:

time                                                 | value
2018-07-05T06:26:33.043003714Z | 98

My question is that why there is only one record for measuremnt DATAand measurement DATA2 at a  period? Why does the join fail?

**Comment by faskiri** [comment]
var data2 = data
|shift(shift)

You missed the offset.

The right syntax is:
```
var data = batch
|query('''SELECT count(usage_idle) as value FROM "ocean"."autogen"."cpu" ''')
.period(period)
.every(every)
.groupBy('60s')

var data2 = batch
|query('''SELECT count(usage_idle) as value FROM "ocean"."autogen"."cpu" ''')
.period(period)
.every(every)
.groupBy('60s')
.offset(shift)
.shift(shift)
```
What this would do is, the second query would get data `shift` duration ago, and shift if forward by `shift` (to the current time) which is now good to be joined to the data (since they both look as if it were data from the same time).

The best way is to look at kapacitor logs and grep for the task name

```
kapacitor logs | grep task
```
You can see your SQL query with the time and the data it fetched (add a log node after both data and data2). It will help you understand what it is doing much better.

**Comment by heayin** [comment]
@faskiri  Thank you very much for your reply.
Using the tickscript as follows:
var data = batch
    |query('''SELECT count(usage_idle) as value FROM "ocean"."autogen"."cpu" ''')
        .period(period)
        .every(every)

var data2 = batch
    |query('''SELECT count(usage_idle) as value FROM "ocean"."autogen"."cpu" ''')
        .period(period)
        .every(every)
        .offset(shift)
    |shift(shift)

var join = data
    |join(data2)
        .as('current', 'past')
        .tolerance(1m)

It works.
Thank you very much!!

**Comment by heayin** [comment]
close the issue
