### ISSUE TITLE
Alert is not expected with groupby

### ISSUE THREAD

**Issue by F4ncyMooN** [influxdata/kapacitor#2008]
I found something strange for alert evaluation. It seems kapacitor will wrongly check the status of different group together in the first batch of data.

My tick is as below.

```
var from = stream|from()
		.database('test')
		.retentionPolicy('oneday')
		.measurement('M1')
		|groupBy('host')
from|alert()
		.crit(lambda: "metric" > 100)
		.id('{{ .TaskName }}')
		.message('')
		.details('')
```

And the data is as the table shows:

|time|host|metric|
|:--:|:--:|:--:|
|2018-07-24T09:00:00Z|host1|120|
|2018-07-24T09:00:00Z|host2|10|
|2018-07-24T09:00:10Z|host1|120|
|2018-07-24T09:00:10Z|host2|10|
|2018-07-24T09:00:20Z|host1|120|
|2018-07-24T09:00:20Z|host2|10|

What I got from the triggered alerts are 

|time|level|host|metric||
|:--:|:--:|:--:|:--:|:--:|
|2018-07-24T09:00:00Z|CRITICAL|host1|120||
|2018-07-24T09:00:00Z|OK|host2|10|<- seems wrong|
|2018-07-24T09:00:10Z|CRITICAL|host1|120||
|2018-07-24T09:00:20Z|CRITICAL|host1|120||

This will only be triggered at the first batch of data (restart or define). Then everything will back to normal.

**Comment by F4ncyMooN** [comment]
@nathanielc Could you help me with this issue. It really bothered me a lot.
I think this is a bug when dealing with the first point in alert node.

**Comment by arturo-mondelo** [comment]
Since you groupBy host, and redefine the alert, it will check all the combinations (host1 + M1 and host2 + M2). Is reporting OK on host 2 since is it's correct state.

**Comment by F4ncyMooN** [comment]
When I group by host, host1 and host2's data should not compared together. But I found at the first batch, data are not splitted and host2's ok will reset host1's critical.

**Comment by alexey-mk** [comment]
Hi!
Because you defined .id('{{ .TaskName }}') - all groups (hosts) is treated as one stream of data (tags are ignored)
This is how ID property works. By default ID includes all tags - so groups treated as separate streams.
