### ISSUE TITLE
Getting a lot of "EOF" errors using post handler 

### ISSUE THREAD

**Issue by jaapz** [influxdata/kapacitor#2014]
Whenever an alert is triggered or resolved, we send an update to a small HTTP API we have running in our backend, this way we can keep track of alerts and figure out who should be notified on our platform.

We have been consistently getting this error every few hours:

> ts=2018-08-08T06:26:00.162Z lvl=error msg="failed to POST alert data" service=httppost handler=paniek-post-1 topic=alert err="Post http://paniek:5000/alert: EOF"

I looked at the relevant code in kapacitor that triggers this log message and it seems you guys are using `http.DefaultClient` which, according to the internet, tries to re-use (tcp?) connections. Apparently when the connection is closed by the server (possibly without the Connection:close header), the DefaultClient only picks up on that on the next time he tries to use that connection, and throws an error. When this happens, kapacitor logs the above error and then returns. No retries are done, as far as I can see.

Apart from the fact that I'm not sure why these EOF errors keep happening (and you guys might know why), it would be great if kapacitor would at least retry the request a few times when it fails with an error like this. After all, it's not a server error for which the request is failing, it's Go trying to reuse a connection that was already closed.

For the record, we are using a Flask app running behind uWSGI (using it's built-in http load balancer) to handle the requests on the server side.

**Comment by jaapz** [comment]
I think this was due to either uWSGI's http server running out of resources for handling bursts of requests, or an incompatibility between kapacitor and uWSGI's http server.

I solved this by putting an nginx loadbalancer in front of our uWSGI app and reconfiguring the uWSGI app to not do any HTTP.

**Comment by huskeyw** [comment]
I am having the same error, only when running LLMs that use two Nvidia GPUS (M40 ) 

ime=2024-11-21T17:49:06.138-08:00 level=INFO source=sched.go:730 msg="new model will fit in available VRAM, loading" model=/home/huskeyw/.ollama/models/blobs/sha256-a677b4a4b70c45e702b1d600f7905e367733c53898b8be60e3f29272cf334574 library=cuda parallel=4 required="43.2 GiB"
time=2024-11-21T17:49:06.341-08:00 level=INFO source=server.go:105 msg="system memory" total="251.6 GiB" free="247.0 GiB" free_swap="8.0 GiB"
time=2024-11-21T17:49:06.342-08:00 level=INFO source=memory.go:343 msg="offload to cuda" layers.requested=-1 layers.model=81 layers.offload=81 layers.split=41,40 memory.available="[22.3 GiB 22.3 GiB]" memory.gpu_overhead="0 B" memory.required.full="43.2 GiB" memory.required.partial="43.2 GiB" memory.required.kv="2.5 GiB" memory.required.allocations="[22.0 GiB 21.2 GiB]" memory.weights.total="38.4 GiB" memory.weights.repeating="37.6 GiB" memory.weights.nonrepeating="822.0 MiB" memory.graph.full="1.1 GiB" memory.graph.partial="1.1 GiB"
time=2024-11-21T17:49:06.343-08:00 level=INFO source=server.go:383 msg="starting llama server" cmd="/tmp/ollama1665379698/runners/cuda_v11/ollama_llama_server --model /home/huskeyw/.ollama/models/blobs/sha256-a677b4a4b70c45e702b1d600f7905e367733c53898b8be60e3f29272cf334574 --ctx-size 8192 --batch-size 512 --n-gpu-layers 81 --threads 24 --parallel 4 --tensor-split 41,40 --port 40923"
time=2024-11-21T17:49:06.344-08:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2024-11-21T17:49:06.344-08:00 level=INFO source=server.go:562 msg="waiting for llama runner to start responding"
time=2024-11-21T17:49:06.345-08:00 level=INFO source=server.go:596 msg="waiting for server to become available" status="llm server error"
time=2024-11-21T17:49:06.362-08:00 level=INFO source=runner.go:883 msg="starting go runner"
time=2024-11-21T17:49:06.362-08:00 level=INFO source=runner.go:884 msg=system info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | cgo(gcc)" threads=24
time=2024-11-21T17:49:06.362-08:00 level=INFO source=.:0 msg="Server listening on 127.0.0.1:40923"
llama_model_loader: loaded meta data with 29 key-value pairs and 724 tensors from /home/huskeyw/.ollama/models/blobs/sha256-a677b4a4b70c45e702b1d600f7905e367733c53898b8be60e3f29272cf334574 (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Meta Llama 3.1 70B Instruct
llama_model_loader: - kv   3:                           general.finetune str              = Instruct
llama_model_loader: - kv   4:                           general.basename str              = Meta-Llama-3.1
llama_model_loader: - kv   5:                         general.size_label str              = 70B
llama_model_loader: - kv   6:                            general.license str              = llama3.1
llama_model_loader: - kv   7:                               general.tags arr[str,6]       = ["facebook", "meta", "pytorch", "llam...
llama_model_loader: - kv   8:                          general.languages arr[str,8]       = ["en", "de", "fr", "it", "pt", "hi", ...
llama_model_loader: - kv   9:                          llama.block_count u32              = 80
llama_model_loader: - kv  10:                       llama.context_length u32              = 131072
llama_model_loader: - kv  11:                     llama.embedding_length u32              = 8192
llama_model_loader: - kv  12:                  llama.feed_forward_length u32              = 28672
llama_model_loader: - kv  13:                 llama.attention.head_count u32              = 64
llama_model_loader: - kv  14:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  15:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv  16:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  17:                          general.file_type u32              = 2
llama_model_loader: - kv  18:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  19:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  20:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  21:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  22:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  23:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  24:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  25:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  26:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  27:                    tokenizer.chat_template str              = {{- bos_token }}\n{%- if custom_tools ...
llama_model_loader: - kv  28:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  162 tensors
llama_model_loader: - type q4_0:  561 tensors
llama_model_loader: - type q6_K:    1 tensors
time=2024-11-21T17:49:06.596-08:00 level=INFO source=server.go:596 msg="waiting for server to become available" status="llm server loading model"
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 0.7999 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_layer          = 80
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 131072
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 70B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 70.55 B
llm_load_print_meta: model size       = 37.22 GiB (4.53 BPW) 
llm_load_print_meta: general.name     = Meta Llama 3.1 70B Instruct
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
llm_load_print_meta: EOM token        = 128008 '<|eom_id|>'
llm_load_print_meta: EOG token        = 128008 '<|eom_id|>'
llm_load_print_meta: EOG token        = 128009 '<|eot_id|>'
llm_load_print_meta: max token length = 256
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: Tesla M40 24GB, compute capability 5.2, VMM: yes
  Device 1: Tesla M40 24GB, compute capability 5.2, VMM: yes
llm_load_tensors: ggml ctx size =    1.02 MiB
llm_load_tensors: offloading 80 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 81/81 layers to GPU
llm_load_tensors:        CPU buffer size =   563.62 MiB
llm_load_tensors:      CUDA0 buffer size = 18821.57 MiB
llm_load_tensors:      CUDA1 buffer size = 18725.43 MiB
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =  1312.00 MiB
llama_kv_cache_init:      CUDA1 KV buffer size =  1248.00 MiB
llama_new_context_with_model: KV self size  = 2560.00 MiB, K (f16): 1280.00 MiB, V (f16): 1280.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     2.08 MiB
llama_new_context_with_model: pipeline parallelism enabled (n_copies=4)
llama_new_context_with_model:      CUDA0 compute buffer size =  1216.01 MiB
llama_new_context_with_model:      CUDA1 compute buffer size =  1216.02 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    80.02 MiB
llama_new_context_with_model: graph nodes  = 2566
llama_new_context_with_model: graph splits = 3
time=2024-11-21T17:49:18.137-08:00 level=INFO source=server.go:601 msg="llama runner started in 11.79 seconds"
[GIN] 2024/11/21 - 17:49:18 | 200 | 12.328292046s |       127.0.0.1 | POST     "/api/generate"
CUDA error: out of memory
  current device: 1, in function alloc at ggml-cuda.cu:406
  cuMemCreate(&handle, reserve_size, &prop, 0)
ggml-cuda.cu:132: CUDA error
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No stack.
The program is not being run.
SIGABRT: abort
PC=0x77834d09eb1c m=3 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 7 gp=0xc0000f0380 m=3 mp=0xc0000ad008 [syscall]:
runtime.cgocall(0x5599fb0d8b70, 0xc0000bbb20)
	runtime/cgocall.go:157 +0x4b fp=0xc0000bbaf8 sp=0xc0000bbac0 pc=0x5599fae5a3cb
github.com/ollama/ollama/llama._Cfunc_llama_decode(0x7782f8006b10, {0xf, 0x7782f828bed0, 0x0, 0x0, 0x7782f8009bd0, 0x7782f80070c0, 0x7782f8012260, 0x7782f8024fd0, 0x0, ...})
	_cgo_gotypes.go:543 +0x52 fp=0xc0000bbb20 sp=0xc0000bbaf8 pc=0x5599faf57952
github.com/ollama/ollama/llama.(*Context).Decode.func1(0x5599fb0d486b?, 0x7782f8006b10?)
	github.com/ollama/ollama/llama/llama.go:169 +0xd8 fp=0xc0000bbc40 sp=0xc0000bbb20 pc=0x5599faf59f18
github.com/ollama/ollama/llama.(*Context).Decode(0xc0000bbd28?, 0x0?)
	github.com/ollama/ollama/llama/llama.go:169 +0x17 fp=0xc0000bbc88 sp=0xc0000bbc40 pc=0x5599faf59d77
main.(*Server).processBatch(0xc000188120, 0xc00012e000, 0xc0000bbf10)
	github.com/ollama/ollama/llama/runner/runner.go:427 +0x38d fp=0xc0000bbed0 sp=0xc0000bbc88 pc=0x5599fb0d380d
main.(*Server).run(0xc000188120, {0x5599fb417ea0, 0xc0000dc0f0})
	github.com/ollama/ollama/llama/runner/runner.go:327 +0x1a5 fp=0xc0000bbfb8 sp=0xc0000bbed0 pc=0x5599fb0d3105
main.main.gowrap2()
	github.com/ollama/ollama/llama/runner/runner.go:922 +0x28 fp=0xc0000bbfe0 sp=0xc0000bbfb8 pc=0x5599fb0d7ba8
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000bbfe8 sp=0xc0000bbfe0 pc=0x5599faec2de1
created by main.main in goroutine 1
	github.com/ollama/ollama/llama/runner/runner.go:922 +0xc52

goroutine 1 gp=0xc000006380 m=nil [IO wait]:
runtime.gopark(0x1?, 0xc00002d900?, 0xf4?, 0xd?, 0xc00002d8e0?)
	runtime/proc.go:402 +0xce fp=0xc00002d880 sp=0xc00002d860 pc=0x5599fae9100e
runtime.netpollblock(0x10?, 0xfae59b26?, 0x99?)
	runtime/netpoll.go:573 +0xf7 fp=0xc00002d8b8 sp=0xc00002d880 pc=0x5599fae89257
internal/poll.runtime_pollWait(0x778365f89820, 0x72)
	runtime/netpoll.go:345 +0x85 fp=0xc00002d8d8 sp=0xc00002d8b8 pc=0x5599faebdaa5
internal/poll.(*pollDesc).wait(0x3?, 0x778365fc38e8?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc00002d900 sp=0xc00002d8d8 pc=0x5599faf0d9c7
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0001be100)
	internal/poll/fd_unix.go:611 +0x2ac fp=0xc00002d9a8 sp=0xc00002d900 pc=0x5599faf0ee8c
net.(*netFD).accept(0xc0001be100)
	net/fd_unix.go:172 +0x29 fp=0xc00002da60 sp=0xc00002d9a8 pc=0x5599faf7d949
net.(*TCPListener).accept(0xc0000c6200)
	net/tcpsock_posix.go:159 +0x1e fp=0xc00002da88 sp=0xc00002da60 pc=0x5599faf8e67e
net.(*TCPListener).Accept(0xc0000c6200)
	net/tcpsock.go:327 +0x30 fp=0xc00002dab8 sp=0xc00002da88 pc=0x5599faf8d9d0
net/http.(*onceCloseListener).Accept(0xc000208b40?)
	<autogenerated>:1 +0x24 fp=0xc00002dad0 sp=0xc00002dab8 pc=0x5599fb0b4be4
net/http.(*Server).Serve(0xc0001ce0f0, {0x5599fb417860, 0xc0000c6200})
	net/http/server.go:3260 +0x33e fp=0xc00002dc00 sp=0xc00002dad0 pc=0x5599fb0ab9fe
main.main()
	github.com/ollama/ollama/llama/runner/runner.go:942 +0xfec fp=0xc00002df50 sp=0xc00002dc00 pc=0x5599fb0d792c
runtime.main()
	runtime/proc.go:271 +0x29d fp=0xc00002dfe0 sp=0xc00002df50 pc=0x5599fae90bdd
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00002dfe8 sp=0xc00002dfe0 pc=0x5599faec2de1

goroutine 2 gp=0xc000006e00 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0000a6fa8 sp=0xc0000a6f88 pc=0x5599fae9100e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.forcegchelper()
	runtime/proc.go:326 +0xb8 fp=0xc0000a6fe0 sp=0xc0000a6fa8 pc=0x5599fae90e98
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000a6fe8 sp=0xc0000a6fe0 pc=0x5599faec2de1
created by runtime.init.6 in goroutine 1
	runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000007340 m=nil [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc0000a7780 sp=0xc0000a7760 pc=0x5599fae9100e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.bgsweep(0xc0000220e0)
	runtime/mgcsweep.go:278 +0x94 fp=0xc0000a77c8 sp=0xc0000a7780 pc=0x5599fae7bb54
runtime.gcenable.gowrap1()
	runtime/mgc.go:203 +0x25 fp=0xc0000a77e0 sp=0xc0000a77c8 pc=0x5599fae70685
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000a77e8 sp=0xc0000a77e0 pc=0x5599faec2de1
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc000007500 m=nil [GC scavenge wait]:
runtime.gopark(0xc0000220e0?, 0x5599fb317260?, 0x1?, 0x0?, 0xc000007500?)
	runtime/proc.go:402 +0xce fp=0xc0000a7f78 sp=0xc0000a7f58 pc=0x5599fae9100e
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.(*scavengerState).park(0x5599fb5e6520)
	runtime/mgcscavenge.go:425 +0x49 fp=0xc0000a7fa8 sp=0xc0000a7f78 pc=0x5599fae79549
runtime.bgscavenge(0xc0000220e0)
	runtime/mgcscavenge.go:653 +0x3c fp=0xc0000a7fc8 sp=0xc0000a7fa8 pc=0x5599fae79adc
runtime.gcenable.gowrap2()
	runtime/mgc.go:204 +0x25 fp=0xc0000a7fe0 sp=0xc0000a7fc8 pc=0x5599fae70625
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000a7fe8 sp=0xc0000a7fe0 pc=0x5599faec2de1
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:204 +0xa5

goroutine 5 gp=0xc0000f0000 m=nil [finalizer wait]:
runtime.gopark(0xc0000a6648?, 0x5599fae63f85?, 0xa8?, 0x1?, 0xc000006380?)
	runtime/proc.go:402 +0xce fp=0xc0000a6620 sp=0xc0000a6600 pc=0x5599fae9100e
runtime.runfinq()
	runtime/mfinal.go:194 +0x107 fp=0xc0000a67e0 sp=0xc0000a6620 pc=0x5599fae6f6c7
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0000a67e8 sp=0xc0000a67e0 pc=0x5599faec2de1
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:164 +0x3d

goroutine 70 gp=0xc0000f0540 m=nil [select]:
runtime.gopark(0xc00025da48?, 0x2?, 0x50?, 0x81?, 0xc00025d7ec?)
	runtime/proc.go:402 +0xce fp=0xc00025d658 sp=0xc00025d638 pc=0x5599fae9100e
runtime.selectgo(0xc00025da48, 0xc00025d7e8, 0xf?, 0x0, 0x1?, 0x1)
	runtime/select.go:327 +0x725 fp=0xc00025d778 sp=0xc00025d658 pc=0x5599faea23e5
main.(*Server).completion(0xc000188120, {0x5599fb417a10, 0xc000217340}, 0xc0002058c0)
	github.com/ollama/ollama/llama/runner/runner.go:667 +0xa45 fp=0xc00025dab8 sp=0xc00025d778 pc=0x5599fb0d5345
main.(*Server).completion-fm({0x5599fb417a10?, 0xc000217340?}, 0x5599fb0afd2d?)
	<autogenerated>:1 +0x36 fp=0xc00025dae8 sp=0xc00025dab8 pc=0x5599fb0d8396
net/http.HandlerFunc.ServeHTTP(0xc0000eaf70?, {0x5599fb417a10?, 0xc000217340?}, 0x10?)
	net/http/server.go:2171 +0x29 fp=0xc00025db10 sp=0xc00025dae8 pc=0x5599fb0a87c9
net/http.(*ServeMux).ServeHTTP(0x5599fae63f85?, {0x5599fb417a10, 0xc000217340}, 0xc0002058c0)
	net/http/server.go:2688 +0x1ad fp=0xc00025db60 sp=0xc00025db10 pc=0x5599fb0aa64d
net/http.serverHandler.ServeHTTP({0x5599fb416d60?}, {0x5599fb417a10?, 0xc000217340?}, 0x6?)
	net/http/server.go:3142 +0x8e fp=0xc00025db90 sp=0xc00025db60 pc=0x5599fb0ab66e
net/http.(*conn).serve(0xc000208b40, {0x5599fb417e68, 0xc0000e8e10})
	net/http/server.go:2044 +0x5e8 fp=0xc00025dfb8 sp=0xc00025db90 pc=0x5599fb0a7408
net/http.(*Server).Serve.gowrap3()
	net/http/server.go:3290 +0x28 fp=0xc00025dfe0 sp=0xc00025dfb8 pc=0x5599fb0abde8
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00025dfe8 sp=0xc00025dfe0 pc=0x5599faec2de1
created by net/http.(*Server).Serve in goroutine 1
	net/http/server.go:3290 +0x4b4

goroutine 73 gp=0xc00021b6c0 m=nil [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0xb?)
	runtime/proc.go:402 +0xce fp=0xc000281da8 sp=0xc000281d88 pc=0x5599fae9100e
runtime.netpollblock(0x5599faef7558?, 0xfae59b26?, 0x99?)
	runtime/netpoll.go:573 +0xf7 fp=0xc000281de0 sp=0xc000281da8 pc=0x5599fae89257
internal/poll.runtime_pollWait(0x778365f89728, 0x72)
	runtime/netpoll.go:345 +0x85 fp=0xc000281e00 sp=0xc000281de0 pc=0x5599faebdaa5
internal/poll.(*pollDesc).wait(0xc000234000?, 0xc000202c71?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc000281e28 sp=0xc000281e00 pc=0x5599faf0d9c7
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000234000, {0xc000202c71, 0x1, 0x1})
	internal/poll/fd_unix.go:164 +0x27a fp=0xc000281ec0 sp=0xc000281e28 pc=0x5599faf0e51a
net.(*netFD).Read(0xc000234000, {0xc000202c71?, 0x0?, 0x0?})
	net/fd_posix.go:55 +0x25 fp=0xc000281f08 sp=0xc000281ec0 pc=0x5599faf7c845
net.(*conn).Read(0xc000236000, {0xc000202c71?, 0x0?, 0x0?})
	net/net.go:185 +0x45 fp=0xc000281f50 sp=0xc000281f08 pc=0x5599faf86b05
net.(*TCPConn).Read(0x0?, {0xc000202c71?, 0x0?, 0x0?})
	<autogenerated>:1 +0x25 fp=0xc000281f80 sp=0xc000281f50 pc=0x5599faf924e5
net/http.(*connReader).backgroundRead(0xc000202c60)
	net/http/server.go:681 +0x37 fp=0xc000281fc8 sp=0xc000281f80 pc=0x5599fb0a1377
net/http.(*connReader).startBackgroundRead.gowrap2()
	net/http/server.go:677 +0x25 fp=0xc000281fe0 sp=0xc000281fc8 pc=0x5599fb0a12a5
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000281fe8 sp=0xc000281fe0 pc=0x5599faec2de1
created by net/http.(*connReader).startBackgroundRead in goroutine 70
	net/http/server.go:677 +0xba

rax    0x0
rbx    0xcdd0
rcx    0x77834d09eb1c
rdx    0x6
rdi    0xcdce
rsi    0xcdd0
rbp    0x778305bf6410
rsp    0x778305bf63d0
r8     0x0
r9     0x0
r10    0x8
r11    0x246
r12    0x6
r13    0x84
r14    0x16
r15    0x4c311a4000
rip    0x77834d09eb1c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
[GIN] 2024/11/21 - 17:51:18 | 200 |  6.040296177s |       127.0.0.1 | POST     "/api/chat"
