### ISSUE TITLE
v1.5.1 [2018-08-06] Improve Kafka alert throughput.(Receiving one  alarm  taking  time  about 200 milliseconds.)

### ISSUE THREAD

**Issue by HendSame** [influxdata/kapacitor#2022]
I using kafkaNode to receive  1000 alarms continuously . But every alarm takes  time  about 200 milliseconds.

This is my  kapacitor's log:

`
ts=2018-08-13T16:03:28.162+08:00 lvl=info msg=point service=kapacitor task_master=main task=task_72104d05d9034e8e8c6bd36ad8614c0b node=log5 prefix= name=hik.hosp.ham.indictor.v2.ipc db=hik_hosp rp=default group=id=123456789995,key=,resourceType=ipc dimension_0=id dimension_1=key dimension_2=resourceType tag_level=CRITICAL tag_alertID=task_ipc_72104d05d9034e8e8c6bd36ad8614c0b:id=123456789995,key=,resourceType=ipc tag_id=123456789995 tag_resourceType=ipc field_id=123456789995 field_value=1 field_collectTime=995 field_state_count=1 field_key=signalStatus field_message= field_duration=0 time=2018-08-13T08:00:45.048Z
ts=2018-08-13T16:03:28.337+08:00 lvl=info msg=point service=kapacitor task_master=main task=task_72104d05d9034e8e8c6bd36ad8614c0b node=log5 prefix= name=hik.hosp.ham.indictor.v2.ipc db=hik_hosp rp=default group=id=123456789996,key=,resourceType=ipc dimension_0=id dimension_1=key dimension_2=resourceType tag_id=123456789996 tag_resourceType=ipc tag_level=CRITICAL tag_alertID=task_ipc_72104d05d9034e8e8c6bd36ad8614c0b:id=123456789996,key=,resourceType=ipc field_value=1 field_collectTime=996 field_key=signalStatus field_id=123456789996 field_state_count=1 field_message= field_duration=0 time=2018-08-13T08:00:45.062Z
ts=2018-08-13T16:03:28.540+08:00 lvl=info msg=point service=kapacitor task_master=main task=task_72104d05d9034e8e8c6bd36ad8614c0b node=log5 prefix= name=hik.hosp.ham.indictor.v2.ipc db=hik_hosp rp=default group=id=123456789997,key=,resourceType=ipc dimension_0=id dimension_1=key dimension_2=resourceType tag_resourceType=ipc tag_id=123456789997 tag_level=CRITICAL tag_alertID=task_ipc_72104d05d9034e8e8c6bd36ad8614c0b:id=123456789997,key=,resourceType=ipc field_value=1 field_collectTime=997 field_message= field_duration=0 field_key=signalStatus field_id=123456789997 field_state_count=1 time=2018-08-13T08:00:45.067Z

`

**Comment by markweghorst** [comment]
When the Kafka alert handler was first introduced it suffered from very poor throughput in my application.   In 1.5.1 the throughput was dramatically improved by moving changing the Kafka client to be async:

[https://github.com/influxdata/kapacitor/pull/1989](url)

Now the Kafka client will place the messages to be transmitted into a memory buffer and then batch transmit those messages based on two tunable parameters in kapacitor.conf:

`# BatchSize is the number of messages that are batched before being sent to Kafka
  # If 0 a default of 100 will be used.
  batch-size = 10
  # BatchTimeout is the maximum amount of time to wait before flushing an incomplete batch.
  # If 0 a default of 1s will be used.
  batch-timeout = "10s"`

With these settings, the Kafka client will flush the alerts to the broker when there are 10 messages waiting for transmission or every 10 seconds whichever comes first.  This allows messages to be gathered into a Kafka message set, and transmitted as a batch.

You could try setting batch-size=1 to force immediate transmission and see if that improves your latency, but be aware that prior to 1.5.1 I was capped at about 10-12 alerts/second going to Kafka.  So there is a tradeoff between latency, and throughput.  

What do you currently have configured for batch-size and batch-timeout?

**Comment by HendSame** [comment]
Thanks!
As you said. I will try to configure the batch-size and batch-timeout.
Could you help me with another question? Maybe it's more urgent!
[https://github.com/influxdata/kapacitor/issues/2032](https://github.com/influxdata/kapacitor/issues/2032)
