### ISSUE TITLE
Issue with influxdb 0.10 rc1

### ISSUE THREAD

**Issue by groblus** [influxdata/kapacitor#206]
I can't get influx to stream data to kapacitor. I get no errors in log even at debug level. Kapacitor starts listening at certain udp port - proper subscriptions are created at influxdb level. Database is pumped with data from telegraf. I have a feeling that there is simply no data flow between influx and kapacitor. Are there any issues with influx v0.10 vs kapacitor v0.10 ?
Is there some way to debug it some more ?

**Comment by nathanielc** [comment]
There are no known issues with compatibility between the two versions. You can check that data is flowing using various network tools like tcpdump or ngrep. If you are using a linux based system this command should show if traffic is flowing to Kapacitor. It could be that a firewall or something is blocking the traffic.

```
tcpdump -n udp port SUBSCRIPTION_PORT
```

Have you checked the InfluxDB logs? If InfluxDB can't connect to Kapacitor there should be an error log in there.

Also how are you verifying that Kapacitor is not receiving any data? It could also be that Kapacitor is receiving the data but no task is configured to consume it so Kapacitor is just dropping it.

**Comment by groblus** [comment]
Hi. Thanks for the prompt reply.
You were right - I checked my loopback device for udp traffic and it's there. I think I got tricked by the docs. According to the docs I should be getting something like this int the debug logs: 
`[edge:src->stream] 2015/10/22 14:02:13 D!`
Nothing like that appeared. 
I tried creating a task as described in the docs, but as I already know it won't work with Telegraf 0.10 data. I'm on my way on trying to edit the task so it will work with the current telegraf.
I'll report as soon as I get some results.

**Comment by nathanielc** [comment]
yeah, sorry about that, the logging was simply too verbose so I removed that log. I'll update the getting started guide accordingly. Thanks

**Comment by nathanielc** [comment]
@groblus Take a look at https://github.com/influxdata/docs.influxdata.com/pull/194/files It is the PR for the updated getting started guide using Telegraf v0.10. I should go live soon but until then...

**Comment by groblus** [comment]
Thanks. New docs surely helped.
Are there any nightly builds available (as rpm's) - I'm looking forward to try the new ".details()" on post messages.

**Comment by nathanielc** [comment]
@groblus No nightly builds yet, but they will be coming.
