### ISSUE TITLE
Alerts are sent continuously with deadman and a groupby

### ISSUE THREAD

**Issue by fungiboletus** [influxdata/kapacitor#2075]
Hei,

I made a few `deadman` alerts, using a `group by` host in Kapacitor using Chronograf. I have a few hosts up, and sometimes a few hosts down. I configured Kapacitor to send an email after 1 minutes of downtime.

Kapacitor do send 1 email per minute per host down until they go back to normal. Is that the standard behaviour ? I thought it would send an email after 1 minute of downtime, and stop until the host goes back up.

**Comment by bogski87** [comment]
you can add .stateChangesOnly to your TICK script alert node, then it should only generate an alert when the state changes. Once for when it goes down and once when it checks in as OK again.

`|alert()
.crit(lambda: "crit_condition" >= 3 )
.stateChangesOnly()
.message(message)
.details(details)
.id(idVar)
.idTag(idTag)
.levelTag(levelTag)
.messageField(messageField)
.durationField(durationField)`

**Comment by fungiboletus** [comment]
Thank you very much.

It would be nice to have this feature easily accessible in Chronograf, but that's another thing.
