### ISSUE TITLE
Future Development?

### ISSUE THREAD

**Issue by mgresser** [influxdata/kapacitor#2085]
What is the status of Kapacitor these days? Can we expect future updates or is this sidelined for the foreseeable future?

**Comment by arturo-mondelo** [comment]
Is not just Kapacitor, but you can have an idea what the future of the complete stack will be:

https://www.youtube.com/watch?v=f5gVpHHKfUM

No more tick scripts is my first thought...

**Comment by oori** [comment]
@mgresser Go to [min 38](https://youtu.be/f5gVpHHKfUM?t=2279) in the video,   the answer is:  Flux will ultimately make kapacitor obsolete.

**Comment by timhallinflux** [comment]
We have reached the end of feature addition for Kapacitor.  We will continue to maintain this and are currently working on a 1.5.2 maintenance release.  But, we do not intend to add any more features.

As part of InfluxDB 2.0 - Flux unifies the languages, essentially allowing for the database to be queried and those same queries can also be scheduled as a task.  The alpha of InfluxDB 2.0 will have the task portion of Flux. (That isn't present in the Flux 0.7 technical preview within InfluxDB 1.7 --- that is only the interactive query portion).  The beta of InfluxDB 2.0 will also introduce the notification and alerting functions to round out the functionality.

We are also looking to create some offline TICKscript -> Flux conversion scripts to assist with the migration from TICK 1.x -> InfluxDB 2.0.

**Comment by mgresser** [comment]
Thank you all for providing me some clarity here.
