### ISSUE TITLE
Best way of monitoring multiple measurements at once

### ISSUE THREAD

**Issue by pootzko** [influxdata/kapacitor#212]
This is kind of related to a [question](https://github.com/influxdata/kapacitor/issues/197) I had earlier.

I have a task that looks like this:

```
var data = stream
    .where(lambda: "SensorSerialCode" == 'AQS1XOLD10000000' OR "SensorSerialCode" == 'AQS1XNEW10000000')
    .from().measurement('reading')

data
    .alert()
        .id('Sensor {{ index .Tags "SensorSerialCode" }}')
        .message('{{ .ID }} {{ .Level }}: Temperature ({{ index .Fields "Temperature" }}) went above threshold (10) ')
        .warn(lambda: "Temperature" > 10)
        .log('/tmp/alerts.log')


data
    .alert()
        .id('Sensor {{ index .Tags "SensorSerialCode" }}')
        .message('{{ .ID }} {{ .Level }}: Voc ({{ index .Fields "Voc" }}) went below threshold (500) ')
        .warn(lambda: "Voc" < 500)
        .log('/tmp/alerts.log')
```

But what seems to be happening here is if one of these sensors triggers a warning, it will output an alert for the other sensor as well. 

For example AQS1XOLD10000000 has a temperature of 30, and AQS1XNEW10000000 has temperature at 5. Now because of that AQS1XOLD10000000 triggers an alert which is fine, but AQS1XNEW10000000 also triggers an alert even though it's bellow the threshold. 

Not sure if this is by design or not and if my approach makes sense or not really? Would it be better if I just had to streams instead? 

Thanks

**Comment by nathanielc** [comment]
My guess as to what is happening is that AQS1XOLD10000000 first triggers an alert , putting the alert in the `warn` state. Then the AQS1XNEW10000000 data point comes and since is < 10 it changes the state to `ok` and you get a message in the log saying that now the alert is OK. Can you confirm in the log that the alert corresponding to AQS1XNEW10000000 is an OK alert?

To solution is to use the `groupBy` method to treat each sensor separately. The alert node will track state independently for each group it processes so you just need to assign each sensor to its own group. This can easily be done like so:

```javascript
var data = stream.from()// note you should normally use the from method first, as you can create weird behavior if you use more than one stream later. See #203
    .measurement('reading')
    .where(lambda: "SensorSerialCode" == 'AQS1XOLD10000000' OR "SensorSerialCode" == 'AQS1XNEW10000000')
    // Group the stream by sensor, now each alert node will track state by group aka sensor.
    .groupBy('SensorSerialCode')
    

data
    .alert()
        .id('Sensor {{ index .Tags "SensorSerialCode" }}')
        .message('{{ .ID }} {{ .Level }}: Temperature ({{ index .Fields "Temperature" }}) went above threshold (10) ')
        .warn(lambda: "Temperature" > 10)
        .log('/tmp/alerts.log')


data
    .alert()
        .id('Sensor {{ index .Tags "SensorSerialCode" }}')
        .message('{{ .ID }} {{ .Level }}: Voc ({{ index .Fields "Voc" }}) went below threshold (500) ')
        .warn(lambda: "Voc" < 500)
        .log('/tmp/alerts.log')
```

**Comment by pootzko** [comment]
Hi, 

yes, I did see OK's in there (for the same alert event, just the opposite sensor), just like you described. I did see the groupBy in some of the examples, but I didn't realize I actually needed it for something like this so I left it out rather than just C/P code around. 

Thanks a lot for your help. Much appreciated.
