### ISSUE TITLE
Documentation for OpsGenie incorrect

### ISSUE THREAD

**Issue by bogski87** [influxdata/kapacitor#2131]
Your ops genie 2 docs are incorrect.

[docs](https://docs.influxdata.com/kapacitor/v1.5/event_handlers/opsgenie/v2/#example-tickscript)

The documenation specifies teamsList('team name', 'team name').

If you add this to your alert script
.opsGenie2()
.teamsList('team') 

you get this:
invalid TICKscript: line 68 char 10: no method or property "teamsList" on *pipeline.OpsGenie2Handler

The correct value should be teams('teams name'). Personally, i rely heavily on the documentation and it is extremely frustrating when it is incorrect. Defining a script when the documentation was wrote would have highlighted this.

**Comment by zabullet** [comment]
https://github.com/influxdata/docs.influxdata.com/pull/2453

**Comment by bogski87** [comment]
Awesome
