### ISSUE TITLE
Invalid cron expression causes panic: runtime error: index out of range

### ISSUE THREAD

**Issue by dataviruset** [influxdata/kapacitor#2148]
Using Kapacitor 1.5.1 in Docker.
kapacitor                     1.5.1               9722b53c16b5        4 months ago        254MB

$ kapacitor version
Kapacitor OSS 1.5.1 (git: HEAD 89828ffff6cf5cd4cb2b34bf883e134395f734de)

TICKscript:

```
var data = batch
    |query(''' SELECT sum("value")  FROM "foo"."autogen"."bar" WHERE  "foo"='bar' AND "foo"='bar'  ''')
        .period(10m)
        .cron('0 0/10 21-9 * * * *')
    |httpOut('current')

var trigger = data
    |httpOut('alert')
    |alert()
        .crit(lambda: ("sum" < 15))
        .message('''测试 123: {{ index .Fields "sum" }}''')
        .post('http://www.example.com/send?access_token=foobar')
```

Result:

```
2019/01/11 15:38:00 Using configuration at: /etc/kapacitor/kapacitor.conf
panic: runtime error: index out of range

goroutine 1868 [running]:
github.com/influxdata/kapacitor/vendor/github.com/gorhill/cronexpr.(*Expression).nextDayOfMonth(0xc436945500, 0xbf062fd6e2ab1153, 0xa6d700cf, 0x3464fe0, 0x0, 0x3b, 0x22ab1153ffffffff)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/gorhill/cronexpr/cronexpr_next.go:115 +0x254
github.com/influxdata/kapacitor/vendor/github.com/gorhill/cronexpr.(*Expression).Next(0xc436945500, 0xbf062fd6e2ab1153, 0xa6d700cf, 0x3464fe0, 0xc4300eff10, 0x405215, 0xc42153bec0)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/gorhill/cronexpr/cronexpr.go:210 +0x699
github.com/influxdata/kapacitor.(*cronTicker).Start.func1(0xc428572b40)
	/root/go/src/github.com/influxdata/kapacitor/batch.go:502 +0xef
created by github.com/influxdata/kapacitor.(*cronTicker).Start
	/root/go/src/github.com/influxdata/kapacitor/batch.go:498 +0x5c
```

After this, the database goes corrupted and cannot be used, kapacitor keeps on crashing on start. So it's hard to fix the invalid cron expression.

**Comment by docmerlin** [comment]
Ok, I we updated the cron library.  That fixed a different panic, but did not fix this one.  The library has been archived and is no longer being updated (last update was 2 years ago, and PR's are being ignored).

For fixing your database in the short run, I suggest https://github.com/br0xen/boltbrowser.
In the short run I'm going to add some recover logic around the cron parsing so it won't crash loop.

Longer term options:
Options: 
1) switch to https://godoc.org/github.com/robfig/cron
2) fork http://github.com/gorhill/cronexpr
3) add tz support to http://github.com/influxdata/cron

**Comment by docmerlin** [comment]
This should be closed as the latest version no longer panics.

**Comment by docmerlin** [comment]
I'm going to go ahead and close this as it shouldn't panic anymore.

**Comment by dataviruset** [comment]
Thanks for your help! @docmerlin
