### ISSUE TITLE
Generated Conf file on windows does not parse and crashes

### ISSUE THREAD

**Issue by shantanoo-desai** [influxdata/kapacitor#2165]
## System
Windows 10 Powershell

## Kapacitor
`v1.5.2-1`

## Reproduction
As a standard `kapacitor.conf` is aligned mostly for *NIX  type file systems e.g. `/path/to/file` I needed to generate a configuration file for Windows Filesystem compatibility.

1. `.\kapacitord.exe config > generated.conf` provided the following file:

```
hostname = "127.0.0.1"
data_dir = "C:\\Users\\des\\.kapacitor"
skip-config-overrides = false
default-retention-policy = ""

[alert]
  persist-topics = true

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"
  https-private-key = ""
  shutdown-timeout = "10s"
  shared-secret = ""

[replay]
  dir = "C:\\Users\\des\\.kapacitor\\replay"

[storage]
  boltdb = "C:\\Users\\des\\.kapacitor\\kapacitor.db"

[task]
  dir = "C:\\Users\\des\\.kapacitor\\tasks"
  snapshot-interval = "1m0s"

[load]
  enabled = false
  dir = "C:\\Users\\des\\.kapacitor\\load"

[[influxdb]]
  enabled = true
  name = "default"
  default = false
  urls = ["https://test-server-ip:8086"]
  username = "des"
  password = "lincoln"
  # ssl-ca = ""
  # ssl-cert = ""
  # ssl-key = ""
  insecure-skip-verify = true
  timeout = "0s"
  disable-subscriptions = false
  subscription-protocol = "http"
  subscription-mode = "cluster"
  kapacitor-hostname = ""
  http-port = 0
  udp-bind = ""
  udp-buffer = 1000
  udp-read-buffer = 0
  startup-timeout = "5m0s"
  subscriptions-sync-interval = "1m0s"
  [influxdb.excluded-subscriptions]
    _kapacitor = ["autogen"]

[logging]
  file = "STDERR"
  level = "DEBUG"

[config-override]
  enabled = true


[[httppost]]
  endpoint = "example"
  url = "http://example.com"
  alert-template = ""
  alert-template-file = ""
  row-template = ""
  row-template-file = ""
  [httppost.basic-auth]
    username = ""
    password = ""

[deadman]
  interval = "10s"
  threshold = 0.0
  id = "{{ .Group }}:NODE_NAME for task '{{ .TaskName }}'"
  message = "{{ .ID }} is {{ if eq .Level \"OK\" }}alive{{ else }}dead{{ end }}: {{ index .Fields \"emitted\" | printf \"%0.3f\" }} points/INTERVAL."
  global = false
```
(With some modification for brewity)

2. Upon trying to execute the file `.\kapacitord.exe -config .\generated.conf` the following parsing error exists:

```
2019/03/05 17:17:38 Using configuration at: .\generated.conf
ts=2019-03-05T17:17:38.237+01:00 lvl=error msg="encountered error" service=run err="parse config: Near line 0 (last key parsed ''): bare keys cannot contain '�'"
run: parse config: Near line 0 (last key parsed ''): bare keys cannot contain '�'
```

Related Issues: #2030

**Comment by shantanoo-desai** [comment]
## Possible Solution
1. Generate a new `.conf` file on the Powershell

         .\kapacitord.exe config

2. Copy the output and paste it into a file with `CRLF` ending
3. Execute using `.\kapacitord.exe -config kapacitor.gen.conf`
and this should work.

**Comment by madwizard** [comment]
I have followed your workaround and it does not work. I confirmed that lines end with crlf sequence, but I still get the same error.

**Comment by shantanoo-desai** [comment]
@madwizard can you provide me the error which is thrown on the server?

**Comment by madwizard** [comment]
Hi @shantanoo-desai 
Sorry for long delay.
Error message (also attached screenshot):

PS C:\Program Files\Kapacitor> .\kapacitord.exe -config .\kapacitor.conf

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::

2019/09/30 13:53:13 Using configuration at: .\kapacitor.conf
run: create server: invalid configuration: dir must be an absolute path. To generate a valid configuration file run `kapacitord config > kapacitor.generated.conf`.
PS C:\Program Files\Kapacitor>

![kapacitord](https://user-images.githubusercontent.com/811871/65876637-04fa1100-e38a-11e9-8e7f-9804f6d716de.PNG)

**Comment by shantanoo-desai** [comment]
@madwizard Do the following steps:

1.

**Comment by madwizard** [comment]
I can test this for you tomorrow.
