### ISSUE TITLE
no need of OK Label

### ISSUE THREAD

**Issue by priyankamondalairtel** [influxdata/kapacitor#2196]
HI,

In my environment, I have to trigger alert if value decreases.
I am taking maxValue and minValue in 5 mins interval and if the value differs, is throwing alert.
but the problem facing that, after 5 mins of triggering CRIT alert, it automatically takes the alert into OK label.
Is this possible to have alert it does not throw OK alert or any other way to implement this concept?

below is the tickscript:

var data1 = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |window()
        .period(5m)
        .every(5m)
    |max('value')
        .as('MaxValue')

var data2 = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |window()
        .period(5m)
        .every(5m)
    |min('value')
        .as('MinValue')

var data = data1
    |join(data2)
        .as('data1', 'data2')

var trigger = data
    |alert()
        .crit(lambda: "data1.MaxValue" > "data2.MinValue")
        .critReset(lambda: "data1.MaxValue" != 0)
        .log('/tmp/SQLtest2.log')

**Comment by bogski87** [comment]
Have you tried adding the no recoveries function to your alert node?
[.noRecoveries](https://docs.influxdata.com/kapacitor/v1.5/nodes/alert_node/#norecoveries)

**Comment by priyankamondalairtel** [comment]
thanks for the solution!!
now I able to solve the issue of triggering OK alert.
