### ISSUE TITLE
 Count different ip's separately in TICKscript

### ISSUE THREAD

**Issue by sousa97** [influxdata/kapacitor#2206]
I guys i have a TICKscript with some error, but i couldn't find the solution 
my TICKscript its bellow:
dbrp "telegraf"."autogen"

// Dataframe
var data = batch
  |query('''SELECT HEADER_SOURCE_IP''')
    .period(30s)
    .every(30s)
	.groupBy('unique_ip')
  |eval(lambda: HEADER_SOURCE_IP)
	.as('unique_ip')
  |alert()
    .info(lambda: count("unique_ip") > 0)
    .warn(lambda: count("unique_ip") > 3)
    .crit(lambda: count("unique_ip") > 10)
	.log('/tmp/mem_alert_log.txt')

I just have another TICKscript that can count the ip's but count the all ip´s who send request
So can somenone help me to resolve this issue or propose other TICKscript that meets my goal, thx

@nathanielc can you pls help me?

**Comment by gamefundas** [comment]
@sousa97  How did you solve this? In my use case I want to ensure a certain number of nodes (IP's) are always operating at a given time, if the count falls below a certain value then alert.
