### ISSUE TITLE
[repo] Chronograf in debian repository is still 0.4.0 and not 0.10.0

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/kapacitor#222]
Even if timestamped at 20/1/2016, it's still 0.4.0 version:

```
chronograf_0.4.0_amd64.deb	2016-01-20 17:09 	4.1M
```

Could you please update it to 0.10.0 ?

It would also allow me to rely always on latest package on debian repo instead of rebuilding [docker image](https://hub.docker.com/r/nsteinmetz/influxdb-chronograf/) after each upgrade ;-)

Thanks,
Nicolas

**Comment by rossmcdonald** [comment]
The repo should be updated now.

**Comment by nsteinmetz** [comment]
Indeed, thanks !
