### ISSUE TITLE
Don't specify 'tasks' or 'recordings' explicitly when deleting task or recording.

### ISSUE THREAD

**Issue by OrangeTux** [influxdata/kapacitor#223]
Currently `delete recording` can be used in 2 ways: either with `tasks <task_name>` or with `recordings <record id>`. An example:

``` shell
$ kapacitor delete tasks cpu_alert
$ kapacitor delete recordings b1dee9e8-eb4a-4a19-ae69-f0dab340c816
```

I think specifying explicitly if the thing you want to delete is a task or a recording is not necessary. You can figure it out by looking at the name/id. Recordings are identified by a unique id matching a certain pattern. It's very unlikely that task names are matching the same pattern.

My proposal is to remove the keywords `tasks` and `recordings` from the `delete command`.

**Comment by nathanielc** [comment]
This  workflow has changed and this request is no longer relevant.
