### ISSUE TITLE
Kapacitor-generated Kafka alert messages have incorrect or invalid Kafka timestamp

### ISSUE THREAD

**Issue by mtlaird** [influxdata/kapacitor#2239]
- OS: Centos 7.6
- Kapacitor: 1.5.3 (installed from pre-built package)
- Kafka 2.12-2.3 (but I've also tried with other versions)

When using the Kafka event handler to send alerts to a Kafka topic, I am able to generate and send alerts successfully to the topic, but something about the metadata in the messages causes them to be deleted by Kafka's log cleaner prior to the retention time. They will be deleted the next time the log.retention.check.interval comes up, with the following message in the logs: 

`Found deletable segments with base offsets [5] due to retention time 604800000ms breach (kafka.log.Log)`

This is logged and the messages are deleted even if they were produced within the last minute.

However, if I have Kapacitor write messages to a log file and then use the Apache kafka-console-producer to add those messages to the kafka topic, they are maintained for the expected retention time period. As far as I can tell, the kafka-console-consumer seems to indicate that the contents of these messages are the same, so there seems to be some issue with the way that Kapacitor itself is setting (or not setting) the timestamp or some other aspect of the metadata when producing its messages.

This is my kafka config section from the kapacitor.conf file:

> [[kafka]]
> enabled = true
> id = "localhost"
> brokers = ["localhost:9092"]
> timeout = "10s"
> batch-size = 100
> batch-timeout = "1s"
> use-ssl = false
> ssl-ca = ""
> ssl-cert = ""
> ssl-key = ""
> insecure-skip-verify = false`

(note that I also changed Kapacitor to run on port 9094, since it would otherwise conflict with the default Kafka port)

And this is my TICKScript: 
> dbrp "telegraf"."autogen"
> 
> // Parameters
> var period = 10s
> var every = 10s
> 
> // Dataframe
> var data = stream
>   |from()
>     .database('telegraf')
>     .retentionPolicy('autogen')
>     .measurement('cpu')
>     .groupBy('host')
>   |window()
>     .period(period)
>     .every(every)
>   |mean('usage_idle')
>     .as('stat')
> 
> // Thresholds
> var alert = data
> |alert()
>     .id('{{ index .Tags "host"}}/cpu')
>     .message('{{ .ID }}:{{ index .Fields "stat" }}')
>     .warn(lambda: "stat" > 95)
> 
> // Alert
> alert
>   .kafka()
>     .cluster('localhost')
>     .kafkaTopic('kapacitor')`

I'm also running Telegraf 1.11.4 and Influx 1.7.7, both installed from pre-built packages. Other than the changes to Kapacitor.conf noted above, everything in the TICK stack is running with standard configurations.

And just for reference, here are the definitions of the kafka topic I was using:
> Topic:kapacitor    PartitionCount:1    ReplicationFactor:1  Configs:segment.bytes=1073741824
>    Topic: kapacitor    Partition: 0    Leader: 0    Replicas: 0    Isr: 0`

And the log retention policy section of the kafka server.properties file (all default settings):
> log.retention.hours=168
> #log.retention.bytes=1073741824
> log.segment.bytes=1073741824
> log.retention.check.interval.ms=300000

**Comment by mtlaird** [comment]
With a little bit more investigation, I was able to verify that Kapacitor is generating messages with a 0 value for the Kafka timestamp. I did this using the Kafkacat utility:

Here are the timestamps from two otherwise identical messages, the first one generated using Kapacitor, and the second generated using the apache-console-producer using input from a message that Kapacitor had written to a log file on the system: https://github.com/edenhill/kafkacat

> $ kafkacat -b localhost -C -t kapacitor -f 'Timestamp: %T\n' -p 0 -o 2
> Timestamp: 0
> Timestamp: 1566508653098

**Comment by jzakrzeski** [comment]
Huge plus one on this, this bit us pretty hard while trying to implement kapacitor in production. It seems to be fixed on master, pending release. Any word on when that may be?

**Comment by mtlaird** [comment]
Wasn't this done with this commit? https://github.com/influxdata/kapacitor/commit/5d93d01cf2e4e16edf12989050c8e8f56b5eaa7f

And that was included in the 1.5.4 release, as far as I can tell. Is someone from Influx supposed to to close this ticket, or am I supposed to be the one to close it?
