### ISSUE TITLE
Deleting recording should not require full id, a unique first few characters should be enough 

### ISSUE THREAD

**Issue by OrangeTux** [influxdata/kapacitor#224]
If you want to delete a recording you've to select the recording with its full id:

``` shell
$ kapacitor delete recordings b1dee9e8-eb4a-4a19-ae69-f0dab340c816
```

Most of the time the first few characters are enough to distinguish a recording from other recordings. Assume I've these recordings:

``` shell
$ kapacitor list recordings
ID                                      Type    Size      Created                
b1dee9e8-eb4a-4a19-ae69-f0dab340c816    stream  791 B     05 Feb 16 20:57 CET    
5983d6ec-90b2-460a-80fc-3db0d287bfe6    stream  0 B       07 Feb 16 15:39 CET    
902b58a9-4590-4308-83e9-e60b451a52bc    stream  0 B       07 Feb 16 15:45 CET    
5ac7a276-a22a-49b0-aff9-fe8a4fe0db15    stream  0 B       07 Feb 16 15:47 CET    
```

Deleting the second recording should be possible with only the first 2 characters of it's id:

``` shell
$ kapacitor delete recordings 59
```

**Comment by nathanielc** [comment]
+1 I like this idea. PRs welcome :)

**Comment by sputnik13** [comment]
is this still needed given you can do ```kapacitor delete recordings 59*```?

**Comment by nathanielc** [comment]
Given good tab completion and glob style matching supported through requests I think this issue has been addressed. Closing
