### ISSUE TITLE
REST API hangs when task execution fails

### ISSUE THREAD

**Issue by pootzko** [influxdata/kapacitor#226]
Hi,

I think I found a situation where querying the Kapacitor's REST API hangs (does not really process any incoming requests) if a task in the background failed.

How to reproduce this? Everything was working fine with a local POSTFIX which was running on the same VM where Kapacitor is installed. The serie of queries that I executed was: "define", "disable", "enable". My TICKScripts obviously do have the `email()` inside the alert. Once I changed the SMTP setup in `kapacitor.conf` to a different one (which was as it turns out an invalid configuration) and tried to re-execute the same serie of queries multiple times, REST requests started hanging. With the right SMTP configuration executing them in the same way did not cause any problems.

I understand that a wrong configuration is not something one should have but a same scenario might occur in case the SMTP server is for example temporarily unavailable.

If you need additional info on this, please let me know.

Cheers

**Comment by nathanielc** [comment]
Which commands were hanging? All of them or just one of them?

**Comment by pootzko** [comment]
Basically all of them. This is a full cycle:

1. Define task
2. Disable task
3. Enable task
4. InfluxDb accepts a new measurement
5. Kapacitor receives the measurement and raises an alert
6. Disable/Delete/Define task (didn't try any other calls here)
7. Retry Disable/Delete/Define

Basically any REST requests after 5) would hang and remain like that until I restart the daemon.

**Comment by nathanielc** [comment]
@pootzko What error if any did you receive in the logs when you had the bad SMTP configuration? So far I can't reproduce the behavior you describe. I have tired several bad SMTP configurations but every time an alert is triggered an error is logged and the process continues to work as normal.

Could you post the stack traces the next time it gets into a hung state? This can be done by sending the SIGQUIT signal to the kapacitor daemon. The traces will be output over STDERR.

**Comment by pootzko** [comment]
Hi,

sure, I'll do it tomorrow when I get back into the office and give you the stacktraces.

**Comment by pootzko** [comment]
Ok, so what I did was I run the daemon, set the output level to debug, executed the REST queries and then SIGQUIT using the following (I believe the `2>&1` part should output to STDOUT, also tried using `tee` and outputting to file as well):

```bash
sudo kill -SIGQUIT $(pgrep -f kapacitor) 2>&1
```

But that didn't give me any output. Here is the output from *kapacitor.log*

```
influx@influxdb:~$ sudo tail -f /var/log/kapacitor/kapacitor.log 
[httpd] 2016/02/10 12:59:57 I! Listening on HTTP: [::]:9092
[influxdb] 2016/02/10 12:59:57 I! linking subscriptions
[udp:_internal.monitor] 2016/02/10 12:59:57 I! Started listening on UDP: 127.0.0.1:46692
[influxdb] 2016/02/10 12:59:57 I! started UDP listener for _internal monitor
[udp:SomeDb.default] 2016/02/10 12:59:57 I! Started listening on UDP: 127.0.0.1:32938
[influxdb] 2016/02/10 12:59:57 I! started UDP listener for SomeDb default
[task_master] 2016/02/10 12:59:57 I! Started task: TestAlert_2
[stats] 2016/02/10 12:59:57 I! opened service
[run] 2016/02/10 12:59:57 I! Listening for signals
[httpd] 2016/02/10 13:00:01 I! ::1 - - [10/Feb/2016:13:00:01 +0000] POST /loglevel?level=debug HTTP/1.1 200 23 - Go-http-client/1.1 321fe00b-cff6-11e5-8001-000000000000 107.427µs
[httpd] 2016/02/10 13:00:20 I! 192.168.1.120 - - [10/Feb/2016:13:00:20 +0000] POST /task?name=TestAlert_2&type=stream&dbrps=%5B%7B%22db%22:%22SomeDb%22,%20%22rp%22:%22default%22%7D%5D HTTP/1.1 200 0 - InfluxData.Net.Kapacitor 3d8a697b-cff6-11e5-8002-000000000000 1.969902ms
[edge:TestAlert_2|stream->stream0] 2016/02/10 13:00:20 D! closing c: 4 e: 4
```

Linux version:
```
influx@influxdb:~$ uname -a
Linux influxdb 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

That's Ubuntu server edition 14.04 running inside a VirtualBox VM, Kapacitor v0.10.1.

**Comment by pootzko** [comment]
Here is *kapacitord.err* [dump](http://pastebin.com/3SMnbbeQ) if it helps you in any way.

**Comment by nathanielc** [comment]
This has been fixed
