### ISSUE TITLE
How to pass name of the host into tick script .exec() event handler

### ISSUE THREAD

**Issue by pavank97386** [influxdata/kapacitor#2266]
I am currently working in tick script, I want to pass host name as an argument when alert triggers from that specific host, so I am unable to find the exact variable to pass to that script.

            var trigger = data
                |alert()
                    .crit(lambda: "value" > crit)
                    .message(message)
                    .id(idVar)
                    .idTag(idTag)
                    .levelTag(levelTag)
                    .messageField(messageField)
                    .durationField(durationField)
                    .exec('/usr/bin/python', '/home/scripts/pythons/memory.py' ) // here need to pass host 
                     name

**Comment by ashishkaransingh** [comment]
You should really post your questions to the following channel:
https://community.influxdata.com/
This must be used for issues and bugs.

As to answer to your question.
Since host is a tag, can you not access host it like this {{index .Tags "host"}}

**Comment by russorat** [comment]
you can also join the community slack channel at https://influxdata.com/slack .

**Comment by pavank97386** [comment]
> You should really post your questions to the following channel:
> https://community.influxdata.com/
> This must be used for issues and bugs.
> 
> As to your question i do not know about your memory.py but can you try like this:
> Since host is a tag try passing the tag as {{index .Tags "host"}}

thank you for your quick response
.exec('/usr/bin/python', '/home/scripts/pythons/memory.py' , {{index .Tags "host"}})  we already tried this but not getting host name to the python script as argument or even in  logs.
