### ISSUE TITLE
No alert dispatched on crit(lambda: TRUE)

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#227]
Hi,

I might be doing something very silly.. but I can't figure out what =X
I am using kapacitor:
```
Kapacitor 0.10.0 (git:  35c9c6fe6543f9d65779d10723ea3a70657d8bba)
```

and having the next tick script:
```
stream
    // Select just the cpu_usage_idle measurement from our example database.
		.from().measurement('cpu')
    .alert()
        .crit(lambda: TRUE)
				.log('/tmp/alerts.log')
```

For some odd reason no alerts are written to the log file, here is show result.
```
Name: cpu_alert
Error:
Type: stream
Enabled: true
Executing: true
Databases Retention Policies: ["kapacitor_example"."default"]
TICKscript:
stream
    // Select just the cpu_usage_idle measurement from our example database.
		.from().measurement('cpu')
    .alert()
        .crit(lambda: TRUE)
				.log('/tmp/alerts.log')



DOT:
digraph cpu_alert {
stream0 -> stream1 [label="189"];
stream1 -> alert2 [label="0"];
}
```

I see that data flows to stream1, but from stream1 to alert2.. and the task is executing..
Why this is not working? and what is "stream0" and "stream1"?

**Comment by nathanielc** [comment]
A per this:

```
digraph cpu_alert {
stream0 -> stream1 [label="189"];
stream1 -> alert2 [label="0"];
}
```
You task received 189 points but none of them where from the `cpu` measurement. Are you using Telegraf >= 0.10.0 to create the cpu data?

**Comment by yosiat** [comment]
I am using Telegraf 0.10.2 and it looks the cpu measurement is empty 
```
SELECT time,value FROM cpu WHERE time > now() - 1d
``` 
returns no results.

So what does the "189" stands for? and what is stream0 and stream1 then?

**Comment by nathanielc** [comment]
See https://docs.influxdata.com/kapacitor/v0.10/introduction/getting_started/ for a walk-through of what the output of the `kapacitor show task_name` command means. Just search for `kapacitor show` which is part way throught the guide.

**Comment by yosiat** [comment]
It kinda works, I replaced my "telegraf.conf" with the configuration from the Getting started tutorial.

And my dot graph is now like this:
```
digraph cpu_alert {
stream0 -> stream1 [label="580"];
stream1 -> alert2 [label="229"];
}
```

How can I "debug" or see why 351 (580 - 229) aren't passed to alert2?

Feature idea: change the name of "stream0" and "stream1" to more indicative names - for example "points_stream" and "cpu_stream" respectively.

**Comment by nathanielc** [comment]
@yosiat 351 points are not passed to the alert because they do not match the criteria of the stream1 node, which is `.from().measurement('cpu')`. So in this case telegraf sent 351 points to Kapacitor that are not from the `cpu` measurement. The node stream0 got the points since they came from telegraf but stream1 dropped them because you only want the `cpu` data.

As for your feature idea I like it but where would I get those names?

**Comment by yosiat** [comment]
@nathanielc this is weird, because I don't which type are measurements are flowing through kapacitor, th e only one I know of is the "cpu" measurement. Is there a way I can see in the logs?

about the question from where to fetch the names, I will dig into the source and check that out..
