### ISSUE TITLE
failed to POST alert data because of unsupported protocol scheme

### ISSUE THREAD

**Issue by wyxpku** [influxdata/kapacitor#2271]
In my kapactior config file, I defined a httppost handler named after `wechat`
```
[[httppost]]
  endpoint = "wechat"
  url = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=mykey"
  headers = {Content-Type = "application/json"}
  alert-template = "{{.Message}}"
  row-template = "{{.Message}}"
```

In chronograf, my alram rule was set as below:
![image](https://user-images.githubusercontent.com/7309388/71458102-27aa9300-27dc-11ea-866c-626d2e3f3cef.png)

But in kapacitor, I got this error:
```
ts=2019-12-26T04:36:01.958Z lvl=error msg="failed to POST alert data" service=httppost task=chronograf-v1-2378c0fc-f058-486c-96c6-6052543d2d02 err="Post wechat: unsupported protocol scheme \"\""
```

I have no idea about where the problem is...

**Comment by russorat** [comment]
@wyxpku thanks for the issue. I believe this is an issue with Chronograf. The alert rule builder in chronograf is configuring the options for the HTTP manually. So it isn't looking for the name of the endpoint you've configured (`wechat`), it's looking for a url (`https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=mykey`). If you'd like to use the endpoint you have set up, you will need to manually edit the resulting TICKscript to call the endpoint as shown here: https://docs.influxdata.com/kapacitor/v1.5/event_handlers/post/#post-alerts-from-a-tickscript

**Comment by wyxpku** [comment]
@russorat thanks for you reply.
