### ISSUE TITLE
Kapacitor DB installation on Kubernetes

### ISSUE THREAD

**Issue by naomidpkg** [influxdata/kapacitor#2295]
Hi, 

I am facing issues while reloading the kapacitor.db file, My application is hosted on Kubernetes pods, 
How do I ensure that the changes I have done in my db file gets reflected in the chronograf and also my pod should not get redeployed.

**Comment by russorat** [comment]
@naomidpkg thanks for the issue. Check out https://github.com/influxdata/helm-charts/tree/master/charts/kapacitor for an example of deploying Kapacitor in k8s using helm.

If you have more questions, please join us in Slack https://influxdata.com/slack !
