### ISSUE TITLE
Environment variable on Windows (kapacitor)

### ISSUE THREAD

**Issue by ganendran** [influxdata/kapacitor#2300]
Hi,

In the documentation I see the I can write Environment variables like "KAPACITOR_HTTPPOST_0_ENDPOINT = "example""

Where do I have to write this on windows pc? Is this on Environment variables in system properties?
I set up kapacitor on windows.

Thanks,
Ganendran

**Comment by russorat** [comment]
@ganendran thanks for the issue. Questions like this are better suited for our Community Slack workspace  (https://influxdata.com/slack) or Discourse site (https://community.influxdata.com).

I'm not a windows expert but this blog post might help: https://www.influxdata.com/blog/running-the-tick-stack-on-windows/ 

Here is some info on setting environment variables on various windows platforms: https://www.computerhope.com/issues/ch000549.htm
