### ISSUE TITLE
Certain Kafka fails are silent.

### ISSUE THREAD

**Issue by docmerlin** [influxdata/kapacitor#2317]
Certain failures to send to Kafka are silent.  We need to inject a logger into the Kafka client so that those errors will show up in Kapacitor logs, and be visible, to help people debug their Kafka problems.

**Comment by GeorgeJahad** [comment]
This is one kafka failure with an easy fix, just update the client:
https://github.com/influxdata/kapacitor/issues/2260

**Comment by docmerlin** [comment]
Closed by https://github.com/influxdata/kapacitor/pull/2319

**Comment by docmerlin** [comment]
Closed by https://github.com/influxdata/kapacitor/pull/2319
