### ISSUE TITLE
 failed to send alert data to VictorOps: failed to understand VictorOps response

### ISSUE THREAD

**Issue by devilldog** [influxdata/kapacitor#232]
Here is my config.
 enabled = true
  api-key = "xxxxx"
  routing-key = "everyone"
  url = "https://alert.victorops.com/integrations/generic/20131114/alert"

  global = false

**Comment by nathanielc** [comment]
@devilldog  Which version are you using? There should be a more verbose error logged about how the communication with VictorOps failed.

**Comment by devilldog** [comment]
10.0-1

**Comment by nathanielc** [comment]
If you upgrade to v0.10.1-1 you will get a better error message and we can
debug further.

*Nathaniel Cook*
Kapacitor Lead
▼▴

*InfluxData.com <http://influxdata.com/>*

Twitter <http://www.twitter.com/nathanielvcook>

**Comment by devilldog** [comment]
OK Will do thanks !

**Comment by devilldog** [comment]
I upgraded to 0.10.1 but i get the sam message for VictorOps as before and i enabled DEBUG in the logs

**Comment by devilldog** [comment]
quickly looking at the code for a language i do not know, it looks like the error is not being returned and it is not actually printing out the error just the proceeding line "failed to understand response"

**Comment by devilldog** [comment]
any thoughts ?

**Comment by nathanielc** [comment]
@devilldog The relevant line in the code is https://github.com/influxdata/kapacitor/blob/master/services/victorops/service.go#L83 
which defaults the error message to `"failed to understand VictorOps response: " + string(body)` where `body` is the raw response from VictorOps. You should see something like:

```
[task_name:alert5] 2016/02/17 12:26:04 E! failed to send alert data to VictorOps: failed to understand VictorOps response: RAW_RESPONSE
```

Can you post the logs you are seeing relating to the error?

**Comment by devilldog** [comment]
```
[load_alert:alert2] 2016/02/14 19:22:09 E! failed to send alert data to VictorOps: failed to understand VictorOps response:
[load_alert:alert2] 2016/02/14 19:22:09 E! failed to send alert data to VictorOps: failed to understand VictorOps response:
[load_alert:alert2] 2016/02/14 19:22:09 E! failed to send alert data to VictorOps: failed to understand VictorOps response:
[load_alert:alert2] 2016/02/14 19:22:29 E! failed to send alert data to VictorOps: failed to understand VictorOps response:
[load_alert:alert2] 2016/02/14 19:22:39 E! failed to send alert data to VictorOps: failed to understand VictorOps response:
[load_alert:alert2] 2016/02/14 19:22:39 E! failed to send alert data to VictorOps: failed to understand VictorOps response:
[load_alert:alert2] 2016/02/14 19:22:59 E! failed to send alert data to VictorOps: failed to understand VictorOps response:
[load_alert:alert2] 2016/02/14 19:23:19 E! failed to send alert data to VictorOps: failed to understand VictorOps response:
```

**Comment by devilldog** [comment]
rpm -qa|grep kapac
kapacitor-0.10.1-1.x86_64

**Comment by nathanielc** [comment]
@devilldog I think I have finally reproduced the issue! VictorOps will return a 404 with no content when the API key is not valid. I have a fix coming that will print out a better error message indicating the actual error.

Can you double check your API key to make sure it is correct?

**Comment by devilldog** [comment]
yeah i came to the same conclusion, i will test and let you know thanks !
