### ISSUE TITLE
Kapacitor alerts to Alert manager

### ISSUE THREAD

**Issue by SS30723** [influxdata/kapacitor#2320]
dbrp "_internal"."monitor"
  
stream
    // Select the CPU measurement from the `telegraf` database.
    |from()
        .measurement('cpu_load_short')
    // Triggers a critical alert when the CPU idle usage drops below 70%
    |log()
    |alert()
        .crit(lambda: int("usage_idle") <  70)
        // Write each alert to a file.
        .log('/tmp/alert.log')
        .message('{{ index .Tags "usage_idle" }} is {{ .Level }} and it {{index .Fields "value"}}')
        .post('http://URL')
        .header('Content-type','application/json')
        .captureResponse()

how to send the JSON body to alert manager using the above TICK script?

**Comment by timhallinflux** [comment]
Example here in the docs:
https://docs.influxdata.com/kapacitor/v1.5/introduction/getting-started/#trigger-alerts-from-batch-data

Let us know if that helps!

**Comment by SS30723** [comment]
@timhallinflux .. Thanks for responding. Above tick script is causing below error in the kapacitor logs.
2020-04-17T17:47:24.435Z lvl=error msg="POST returned non 2xx status code" service=httppost task=sandbox22 err="{\"status\":\"error\",\"errorType\":\"bad_data\",\"error\":\"json: cannot unmarshal object into Go value of type []*types.Alert\"}" code=400

1. Alertname, severity and trace ID are some of the fields that we are trying to send to Alertmanager. How to send these JSON fields?
2. We are actually trying to send the JSON body using the .message() field above. Is that correct?

**Comment by josephthanaraja** [comment]
Additional info - alert manager expects some  HTTP post payloads(request body) as a json. How we can pass those using HTTPPoat alert

**Comment by SS30723** [comment]
@nathanielc .. your thoughts on this?

**Comment by ngohoa211** [comment]
@SS30723 i have my custom kapacitor have suport put alert to alertmanager. you may want to take a look:

https://github.com/ngohoa211/kapacitor

affter config in kapacitor.conf

```

[alertmanager]

  # Configure AlertManager.

  enabled = true

  # The Alerta URL.

  url = "http://<alertmanager_Server>:9093/api/v1/alerts"

```

you can write script like this

```

    |alert()

        ...

        .stateChangesOnly(30s)

        .log('/tmp/alerts.log')

        .alertManager()

        .alertManagerTagNames('tag_a', 'tag_b','host')

        .alertManagerTagValues('value_a','value_b', '{{ index .Tags "host" }}')

        .alertManagerAnnotationNames('message', 'value')

        .alertManagerAnnotationValues(message, '{{ index .Fields "value" }}')

```

happy to discuss this further

**Comment by SS30723** [comment]
@ngohoa211 .. I resolved the above issue using a python script.. But when I implement the above framework using kubernetes, I am not getting the database and measurements from influxdb to the kapacitor. All I see is 
_kapacitor data base with autogen as rentention policy and ingress, kapacitor, load and runtime as the measurements.
I am using kapacitor version as 1.5.4 and influx DB  shell version is 1.7.6
How can I trouble shoot this issue?
