### ISSUE TITLE
Depreciate ssl v3.0

### ISSUE THREAD

**Issue by docmerlin** [influxdata/kapacitor#2321]
```
SSLv3 has been irreparably broken since the POODLE attack 5 years ago
and RFC 7568 (f.k.a. draft-ietf-tls-sslv3-diediedie) prohibits its use
in no uncertain terms.
```

https://tools.ietf.org/html/rfc7568

SSL v3.0 was removed from mainline go (in 1.14.2) in a pr as of august of 2019.  If we wish to continue using go past 1.14.2 we will should, ideally remove ssl v3.0 support.

**Comment by psteinbachs** [comment]
This has been done as part of moving to go 1.15
