### ISSUE TITLE
How message Template working in tickscript ?

### ISSUE THREAD

**Issue by wuguanyu** [influxdata/kapacitor#2324]
{{ if gt  index .Fields "value"  0.0 }} up {{ index .Fields "value" | printf "%0.2f"}} % 
{{ else if lt  index .Fields "value"  0.0 }} down {{ index .Fields "value" | printf "%0.2f"}} %
{{else}} {{ index .Fields "value" | printf "%0.2f"}} % {{end}}'

**Comment by wuguanyu** [comment]
executing \"message\" at <gt>: wrong number of args for gt: want 2 got 4

**Comment by ashishkaransingh** [comment]
Are you using row-template or alert-template?

**Comment by wuguanyu** [comment]
I use alart-template

**Comment by wuguanyu** [comment]
> Are you using row-template or alert-template?

I use alert template, maybe I don't acknowledge the grammar of go template ,It result this error

**Comment by wuguanyu** [comment]
I just want use if statement to distinguish the fields of message

**Comment by wuguanyu** [comment]
I guess I need escape this  index .Fields "value" in  {{ if gt index .Fields "value" 0.0 }}

**Comment by ashishkaransingh** [comment]
I struggled a lot with templating accessing .Tags and Field, though i was unable to access Field i did find workaround which works.

You can use row-template like the following for if else condition here "value" is a field.
{{range .Values}}{{ index . "value" }}{{end}}

Also the following example will help you to use if else condition with row-template:

"severity":{{range .Values}} {{ if (eq .xyz "high")}}"3"{{else if (eq .message "low")}}"1"{{else if (eq .message "OK")}}"0" {{ end }}{{end}}

For more information check out the post i created here:
https://community.influxdata.com/t/solution-create-custom-http-body-and-access-tags-and-values-using-row-template/13775

**Comment by ashishkaransingh** [comment]
> I guess I need escape this index .Fields "value" in {{ if gt index .Fields "value" 0.0 }}
Yeah do not give up on this there could be a way out of directly accessing field, though i used if else condition in tickscript using {{.Message}} as I could not access .Fields in alert-template.

**Comment by ashishkaransingh** [comment]
I updated the post refresh it if you need more info.

**Comment by wuguanyu** [comment]
var message = {{ if gt index .Fields "value" 0.0 }} up {{ index .Fields "value" | printf "%0.2f"}} %
{{ else if lt index .Fields "value" 0.0 }} down {{ index .Fields "value" | printf "%0.2f"}} %
{{else}} {{ index .Fields "value" | printf "%0.2f"}} % {{end}}

function "**gt"** need two arguments  but it think this have four arguments but I need use  index .Fields "value" to judge

**Comment by wuguanyu** [comment]
> need

I can't open this url https://community.influxdata.com/t/solution-create-custom-http-body-and-access-tags-and-values-using-row-template/13775

**Comment by wuguanyu** [comment]
> I updated the post refresh it if you need more info.
I can't open this url https://community.influxdata.com/t/solution-create-custom-http-body-and-access-tags-and-values-using-row-template/13775

**Comment by ashishkaransingh** [comment]
try this
https://community.influxdata.com/t/solution-create-custom-http-body-and-access-tags-and-values-using-row-template/13775/7

**Comment by wuguanyu** [comment]
> https://community.influxdata.com/t/solution-create-custom-http-body-and-access-tags-and-values-using-row-template/13775/7

thanks a lot

**Comment by ashishkaransingh** [comment]
Also i remember while using alert-template-file i had to print function as it was throwing error, this may help you (please note i tried this in alert-template-file and not alert-template inline)

"severity": {{ if eq (.Level | print) "WARNING" }}"4"{{else if eq (.Level | print) "CRITICAL"}}"1" {{else if eq (.Level | print) "OK"}}"5"{{ end }},

**Comment by wuguanyu** [comment]
> try this
> https://community.influxdata.com/t/solution-create-custom-http-body-and-access-tags-and-values-using-row-template/13775/7

I use kapacitor default post json to our interface

**Comment by ashishkaransingh** [comment]
Yes post works for alert-template. In case you try row-template  then you need to use |httpPost()

**Comment by wuguanyu** [comment]
> Yes post works for alert-template. In case you try row-template then you need to use |httpPost()

Thanks for your support  I have already resolve my issue 

var message = {{ if gt .Fields.value 0.0}} up {{ index .Fields "value" | printf "%0.2f"}} % 
{{ else if lt .Fields.value  0.0 }} down {{ index .Fields "value" | printf "%0.2f"}} %
{{else}} {{ index .Fields "value" | printf "%0.2f"}} % {{end}}
