### ISSUE TITLE
Kapacitor is taking a wrong time format

### ISSUE THREAD

**Issue by MartinAparicioPons** [influxdata/kapacitor#234]
I collected some open source [samples](https://github.com/numenta/NAB/blob/master/data/realKnownCause/nyc_taxi.csv) and set the following tick script for detecting anomalies:

    batch
        .query('select mean(value) from "nycTaxi"."default"."nycTaxi"')
            .period(1h)
            .every(2h)
            .groupBy(time(1h))
    .mapReduce(influxql.percentile('mean', 90.0))
        .eval(lambda: sigma("percentile"))
            .as('sigma')
            .keep('percentile', 'sigma')
        .alert()
            .warn(lambda: "sigma" > 2.0)
            .log('/path/alerts.log')
            .crit(lambda: "sigma" > 3.0)
            .log('/path/alerts.log')

Obtaining alerts like the following: 

     {"id":"nycTaxi:nil",
      "message":"nycTaxi:nil is WARNING",
      "details":{  
         "Name":"nycTaxi",
         "TaskName":"nyc",
         "Group":"nil",
         "Tags":null,
         "ID":"nycTaxi:nil",
         "Fields":{  
             "percentile":3714,
             "sigma":1.6523726137265795
          },
         "Level":"OK",
         "Message":"nycTaxi:nil is OK"
       },
      "time":"2016-09-13T14:43:21.892057062Z",
      "level":"WARNING",
      "data":{  
        "series":[  
          {  
            "name":"nycTaxi",
            "columns":[  
              "time",
              "percentile",
              "sigma"
            ],
            "values":[  
              [  
                "2016-09-13T14:43:21.892057062Z",
                1279,
                2.002345963142575
      ]]}]}}

For some reason Kapacitor interprets the time as a 2016 date when in the DB the oldest date is 2015-01-31. Why does this happen?

I'm using all latest InfluxDB and Kapacitor (v0.10) in 64-bit ubuntu 15.10.

**Comment by nathanielc** [comment]
@MartinAparicioPons  How did you get Kapacitor to query any of the past data if it is not current? Meaning the `batch` node by default queries current data. In your case the last hour of data. Are you using recording/replays to consume the old data? If so the kapacitor `replay` command has a `-rec-time` flag to tell Kapacitor to use the time of the recorded data instead of adjusting for current time.

The `batch` node does have an `offset` property so you can query data from a given offset from the current time but that doesn't seem useful in this scenario.

**Comment by MartinAparicioPons** [comment]
@nathanielc I used this line `kapacitor record batch -start 2014-07-01T00:00:00Z -stop 2015-02-31T00:00:00Z -name nyc`.

**Comment by nathanielc** [comment]
@MartinAparicioPons so when you replay the recording use this command:

```
kapacitor replay -id RECORDING_ID -name nyc -fast -rec-time
```

With that command the times will match the older dates

**Comment by MartinAparicioPons** [comment]
@nathanielc Worked like a charm. Thanks a lot, I'm closing the issue.
