### ISSUE TITLE
Kapcitor go get install not compiling

### ISSUE THREAD

**Issue by jlark** [influxdata/kapacitor#235]
Suprised I'm seeing this.
```

go get github.com/influxdb/kapacitor/cmd/kapacitor

# github.com/influxdb/influxdb/client
src/github.com/influxdb/influxdb/client/influxdb.go:131:28: error: unknown field ‘Timeout’ in ‘http.Client’
   httpClient: &http.Client{Timeout: c.Timeout, Transport: tr},
                            ^
# github.com/influxdata/kapacitor/tick
src/github.com/influxdata/kapacitor/tick/parser.go:91:18: error: reference to undefined identifier ‘strings.LastIndexByte’
  if i := strings.LastIndexByte(p.Text[start:tok.pos], '\n'); i != -1 {
                  ^
# github.com/influxdata/influxdb/services/meta
src/github.com/influxdata/influxdb/services/meta/response_logger.go:151:19: error: reference to undefined field or method ‘BasicAuth’
   if u, _, ok := r.BasicAuth(); ok {
                   ^
(null):0: confused by earlier errors, bailing out
# github.com/influxdb/influxdb/services/meta
src/github.com/influxdb/influxdb/services/meta/response_logger.go:151:19: error: reference to undefined field or method ‘BasicAuth’
   if u, _, ok := r.BasicAuth(); ok {
                   ^
(null):0: confused by earlier errors, bailing out
```

**Comment by nathanielc** [comment]
Recent changes https://github.com/influxdata/influxdb/pull/5196 were committed into InfluxDB that are no longer compatible with Kapacitor. In the interim Kapacitor has the needed InfluxDB dependencies vendored. Set the env var GO15VENDOREXPERIMENT=1 and go get will function again.

To be clear this is not  a long term solution but the intermediate step until Kapacitor is updated to consume the new Query Engine code from InfluxDB.

**Comment by jlark** [comment]
ok thanks for the clarification @nathanielc any idea when the new query engine will be integrated. I'm happy to wait on this.

**Comment by nathanielc** [comment]
I am hoping to get in the 0.11 release but it is a big change and may not make it. There shouldn't be a need to wait, `go get` will work as long as you use go >=1.5 and GO15VENDOREXPERIMENT=1, details here https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit
