### ISSUE TITLE
Panic on groupby

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#236]
Hi,
I got panic while I used groupBy in my tick script.

I don't think this is a good strategy for not implemented features, I think it should be an error that will be logged.
For fixing this I needed for remove my Kapacitor data folder and only then my service got up.

**Comment by nathanielc** [comment]
Can you post the panic stack trace?

**Comment by yosiat** [comment]
The panic is from here, on the default case -

https://github.com/influxdata/kapacitor/blob/master/group_by.go

**Comment by nathanielc** [comment]
Perfect thanks, Agreed since it makes it hard to restart Kapacitor I will change the error behavior.

**Comment by yosiat** [comment]
I think it should be validation on the "wants" and "provides" of each node.

If I am connecting window node to group node, on the define request I should get errors the window provides batch and group wants stream.
