### ISSUE TITLE
please consider migrating to go modules

### ISSUE THREAD

**Issue by williamh** [influxdata/kapacitor#2362]
Hi all,

I see that Kapacitor is still using Gopkg.* to manage dependencies.

Would you please consider converting to go modules (https://blog.golang.org/migrating-to-go-modules)? This is the internal dependency management system Go uses.

Thanks much for your time,

William

**Comment by docmerlin** [comment]
This is the plan, @williamh .  I've been on family leave, so I haven't gotten to it yet, 
I've made a ticket to remind myself to do it.
Thanks for reminding me to make it.
https://github.com/influxdata/kapacitor/issues/2378
