### ISSUE TITLE
Kapacitor Downtime/Acknowledge equivalents

### ISSUE THREAD

**Issue by sofixa** [influxdata/kapacitor#237]
Hello everyone.

Great work on Kapacitor, it's pretty awesome! I have started using it recently, so i am not at all familiar with it in depth, so maybe i am missing something.

In the Nagios Universe, you can acknowledge an alert and downtime a host, so that you don't receive unneccessary alerts(when you are working to resolve the problem or you plan an outage). 

Is there a way to do a similart thing in Kapacitor? Silence the alerts for a certain host(tag) or service+host(tag) ?

I think it could work with a second table which contains all "downtimes" and "acknowledges" and have Kapacitor verify if the target in question should or should not notify and trigger the alert correspondingly, but i am unsure if that's the best approach. 

Any thoughts or ideas?

Thanks in advance

**Comment by nathanielc** [comment]
@sofixa Kapacitor is not an Alert Manager meaning it does not manage the workflows associated with alerts like acking/silencing etc. Kapacitor is an Alert Generator meaning it will trigger alerts and integrates with many Alert Managers. Eventually we may add these features into Kapacitor or another product that integrates well with Kapacitor but for now we encourage you to use one of the many feature rich and open source options. See https://docs.influxdata.com/kapacitor/v0.10/tick/alert_node/ for details on all the available integrations. 

As for your second question about how to implement it in Kapacitor it would be possible to have a second table to check against when triggering alerts but that would add significant complexity to each of your TICKscripts and complexity for performing ack/silence actions. I would first look at using one of the alerting integrations.

**Comment by sofixa** [comment]
Yeah, i thought so. 

The problem is that Kapacitor proposes integrations with email/HipChat/Slack etc., and for them, there's no way of adding such a logic. 
All the alert traffic should pass through PagerDuty/VictorOps/Alerta(i think?), which become a (dangerous) single point of failure.
As for future evolving of Kapacitor/other InfluxData tools, it would indeed be handy. I think there's a (slight) lack of integration between Kapacitor and the other parts of TICKStack(most notably visualisation, Chronograf - for me, the ability to view and manage alerts via a GUI is.. a must-have in order to fully replace traditional, old-school, monolithic monitoring solutions).

Is there a way to see/ask for the roadmap for the TICKStack?

Anyways, thanks for your response, you can close this issue :)

**Comment by nathanielc** [comment]
Yes the more messaged based alerting handlers are designed to be simple and get you working  fast but not be a full fledged alerting manager. 

As for the other integrations that have alert managing features why would you consider them a single point of failure? I believe each one can be run in an HA mode. It there an HA alert managing platform you already use that you would like to see integrate with Kapacitor? 

As for visualizations of alerts it is on our roadmap :)

**Comment by sofixa** [comment]
Cool about your roadmap! So far InfluxData has never disappointed, so i am looking forward to your progresses.

As for the Alert manager role, i am aware of all the integrations, and they seem somewhat solid, but so far there's nothing self-hosted of really good quality(on par with TICK), and for me, personally, that's a risk. Currently we are using a Nagios-based platform that is way too old and with various improvised patches here and there, totally unsuitable for today's world, so a complete overhaul is needed and TICK definitely seems the way to go, as soon as we choose an appropriate alert manager add-on.

Anyway, thank you for your responses!

PS: I don't suppose alert managing is part of the (planned) scope of Kapacitor?
