### ISSUE TITLE
Kapacitor 1.5.5 is not available in Docker

### ISSUE THREAD

**Issue by jjbuchan** [influxdata/kapacitor#2372]
Looking at https://hub.docker.com/_/kapacitor?tab=tags `1.5.4` is available but not `1.5.5`.

Can that be corrected?

Thanks

**Comment by hzliangbin** [comment]
@jjbuchan seems something blocked. https://github.com/influxdata/influxdata-docker/pull/393

**Comment by docmerlin** [comment]
@jjbuchan @hzliangbin It should be available now.
