### ISSUE TITLE
Kapacitor Critical alert for every new line

### ISSUE THREAD

**Issue by thiagocorredor** [influxdata/kapacitor#2374]
Good morning all, 

How can we configure a TICK script to send an alert for every new line that is inserted on the influxdb table?

Ex: Our monitor check a table on the system and insert in influxdb every record that has an issue. This means that every new line must send a CRIT alert. We do not need INFO / OK / WARN alerts.

Our TICK script:

var measurement = 'table_error'

var data = stream
    |from()
        .measurement(measurement)
        .groupBy('workunit_number')
    |log()
        .level('DEBUG')

var alert = data
    |alert()
        .id('sampleID')
        .message('Sample Message for measurement')
        .crit(lambda: TRUE)
        .log('/tmp/sample_tick.txt')
    |httpOut('alert')

Checking the log, every new record is "collected" but no alert sent:

"node-stats": {
            "alert3": {
                "alerts_inhibited": 0,
                "alerts_triggered": 0,
                "avg_exec_time_ns": 0,
                "collected": 6,
                "crits_triggered": 0,
                "emitted": 0,
                "errors": 0,
                "infos_triggered": 0,
                "oks_triggered": 0,
                "warns_triggered": 0,
                "working_cardinality": 1

**Comment by thiagocorredor** [comment]
Kapacitor version: 1.5.6

**Comment by docmerlin** [comment]
Your alert should use the httppost handler instead of `|httpOut`
For how to use it, look here.
https://docs.influxdata.com/kapacitor/v1.5/event_handlers/post

**Comment by docmerlin** [comment]
I'm going to go ahead an close this issue.  @thiagocorredor

If it didn't help, feel free to reopen.
