### ISSUE TITLE
sending SIGHUP to kapacitor resets Collected points

### ISSUE THREAD

**Issue by j3ffrw** [influxdata/kapacitor#2377]
Hi, when sending SIGHUP to kapacitor to reload configs/tick script, it also reset to zero the Collected points  w/c prevents alert that uses on changeDetect to not get triggered at all since it looses track of the previous point. Is this a expected behavior?  the task/script that uses changeDetect do not have any changes in it, also tasks that were defined via "kapacitor define" is not affected.

Kapacitor version: 1.5.4

tick script: 
```
stream
  |from()
    .measurement(measurement)
    .groupBy(*)
  |changeDetect('commit')
  |alert()
    .log('logfile.log')
```

**Comment by docmerlin** [comment]
Yes, killing the kapacitor instance will reset the collected points, this is expected behavior.
Tasks definitions are defined in a local key value store, on disk so are not erased.

**Comment by docmerlin** [comment]
I hope this answered your question, feel free to re-open if it did not.
