### ISSUE TITLE
Executing a script using .exec() Node

### ISSUE THREAD

**Issue by nhproject** [influxdata/kapacitor#241]
I wrote a python script, which works fine.
The script returns some value, let's say a list of DB schemes.
I have two questions:
1. I would like to run this script only when the state is CRITICAL. Can I do that?
2. How can I get and print the returned value into the alert message, If at all?

Also - what about UDF? Is it possible to do so also with the UDF functionality?

Thanks!

Nitz

**Comment by nathanielc** [comment]
@nhproject The `.exec` method is purely a handler for an alert. The output cannot be used. To make the script only run on critical alerts, only define a critical expression or have the script itself check the level and exit if it is not critical. 

As for the UDF question you could write a UDF to add a string field to the data with the list of DB schemes and then reference that field in the alert message template. You would need to place the UDF before the alert node so the alert node has the necessary data. As a result it may be beneficial to move the alert logic up as well. 

For example, assuming a simple alert like this:

```javascript
...
    .alert()
        .crit(lambda: "value" > 10)
```

You could change it to this and have the same functionality, plus the DB schemes feature:

```javascript
...
   .where(lambda: "value" > 10)
   .udfDBSchemes()
   .alert()
        .message('{{ index .Fields "dbs" }}')
        .crit(lambda: TRUE)
```

This way the UDF is only triggered when a point matches the critical condition.

**Comment by nhproject** [comment]
@nathanielc Many thanks for the fast and descriptive answer! :+1:

**Comment by shaharharap** [comment]
Hello 
do you have an example to how to write a UDF to add a string field to the data ?
and in the some issue It will be nice to have the ability to take data and use it in the alert massage straight forward without passing the agent.
thx  Shahar

**Comment by nathanielc** [comment]
@shaharharap 


 Doing string work is the same as numeric data you just need to set it on the fieldsString property:
From the UDF example here https://docs.influxdata.com/kapacitor/v0.10/examples/anomaly_detection/

This code,
```
            response.point.fieldsDouble["t"] = t
            response.point.fieldsDouble["pvalue"] = pvalue
```

would change to:

```
            response.point.fieldsString["t"] = 'asdf'
            response.point.fieldsString["pvalue"] = 'another stirng'
```

**Comment by jommgoncalves** [comment]
Hi,

** Case: ** I have a stream of values ​​and I want to validate if the current value surpassed the threshold.

If the threshold is surpassed, I want to send a SMS. To do this, I created a shell script and use ` exec` to call it. But I don't know how I can pass the value that surpassed the threshold.

Anyone can help me?
Cheers,

**Comment by nathanielc** [comment]
@jommgoncalves The value should be part of the JSON object that is sent over STDIN to the script. You could use any number of tools to read stdin and get the value. I personally like `jq`

```
#!/bin/bash

data=$(jq .data)
....
```

**Comment by jommgoncalves** [comment]
@nathanielc The problem isn't the shell script but how can I send the value that surpassed the threshold.

For example:
> .crit(lambda: "value" >= threshold)
> .exec('send_sms', '{value: "value"}')

Cheers,

**Comment by jommgoncalves** [comment]
Anyone can help me?

Thanks,

**Comment by lfarkas** [comment]
any solution to this problem?
