### ISSUE TITLE
Kafka messages with the same key are not written to the same partition

### ISSUE THREAD

**Issue by BlocDrummer** [influxdata/kapacitor#2413]
### The Problem
The Kafka doc says "Events with the same event key (e.g., a customer or vehicle ID) are written to the same partition, and Kafka guarantees that any consumer of a given topic-partition will always read that partition's events in exactly the same order as they were written.". See: https://kafka.apache.org/documentation/#intro_concepts_and_terms

However, when writing Kapacitor events to Kafka, that is not the case.

### Possible Solution
I assume that is because the _Balancer_ in _WriterConfig_ is not set. The _Balancer_ defaults to the _RoundRobinGroupBalancer_ as you can see here: https://godoc.org/github.com/segmentio/kafka-go#WriterConfig

To fix this issue one would have to set _Hash_ as _Balancer_. That ensures that messages with the same key are written to the same partition. See: https://godoc.org/github.com/segmentio/kafka-go#Hash.Balance

### Bug Report Infos
Operating System: 64-Bit RHEL 8
Kapacitor Version: Kapacitor OSS 1.5.6 (git: HEAD ee3f609cd1c96f7c8f4eea924278db1fb2a96f0b)
installed using a pre-built package

### Test Case That Demonstrates The Issue
Write a streaming task that sends events with the same key to a Kafka topic with 3 partitions. To set the key you have  to set the id. For example:

dbrp "telegraf"."autogen"

stream
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: int("usage_idle") <  70)
        .id('foo')
        .kafka()
            .cluster('my-cluster')
            .kafkaTopic('my-topic')

Now Kafka messages with the key "foo" will be sent to Kafka. They should all be written to the same partition but they are not.

**Comment by danxmoran** [comment]
The fix for this is complete, and staged for the 1.6.0 release
