### ISSUE TITLE
Readme link to documentation returns 404

### ISSUE THREAD

**Issue by andoks** [influxdata/kapacitor#2418]
In master branch, the link to the documentation at the bottom of the [readme](https://github.com/influxdata/kapacitor/blob/master/README.md) file leads to https://docs.influxdata.com/kapacitor/v1.5/examples/, which returns 404

**Comment by docmerlin** [comment]
@andoks thanks for bringing this to my attention.

**Comment by docmerlin** [comment]
I'm closing this issue as it doesn't seem to be the case anymore.

**Comment by andoks** [comment]
This is indeed fixed, the example link was removed between [1.5.7-rc0](https://github.com/influxdata/kapacitor/blob/v1.5.7-rc0/README.md) and [1.5.7](https://github.com/influxdata/kapacitor/blob/v1.5.7/README.md)
