### ISSUE TITLE
GZIP influxdb writes with the option to opt out.

### ISSUE THREAD

**Issue by docmerlin** [influxdata/kapacitor#2439]
Currently Kapacitor does not gzip encode influxdb writes.  It would save a lot of space if it did.  We should intelligently gzip encode influxdb writes.

**Comment by calebsmac** [comment]
All of our data ingress to Cloud 2.0 comes via Kapacitor, and at the moment it's turning out to be prohibitively expensive on ingress. Hoping that this could really reduce ingress cost and make it a more viable option.

**Comment by docmerlin** [comment]
This is part of with 1.5.8 and a bug with it was fixed in 1.5.9

**Comment by docmerlin** [comment]
https://github.com/influxdata/kapacitor/pull/2479
https://github.com/influxdata/kapacitor/pull/2456
