### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by m4ce** [influxdata/kapacitor#2444]
Not sure where to ask this question so dropping it here. I noticed a lot of issues are not being looked at. Since we are looking at using kapacitor for the long term, it'd be good to know if the project itself is not going to be decommissioned?

**Comment by ValD97** [comment]
Same question here :/ There's very few mentions of Kapacitor in Influxdata docs. With my team we have the feelings that Kapacitor has been integrated in InfluxDB 2.0 by default, without naming it as alert engine. And no more Kapacitor Enterprise, have the features been moved in another offering ?

**Comment by docmerlin** [comment]
The project isn't dead @m4ce @ValD97 .  We are in the process of moving *some* features from kapacitor enterprise to OSS.  Kapacitor enterprise will be dead, but we are putting resources on OSS.  Sorry if I haven't gotten to all the issues yet.

**Comment by m4ce** [comment]
@docmerlin - thanks for the reply. This is excellent news. I think Kapacitor is the most powerful monitoring tool there is out there at the moment. Keep it up.
