### ISSUE TITLE
Kapacitor gives a wrong date

### ISSUE THREAD

**Issue by MartinAparicioPons** [influxdata/kapacitor#245]
See issue #234. The issue there is solved but I noticed that it was giving me a future date (2016-09-13) when it should give the last hour (AFAIK if you don't use the `-rec-time` flag it should process the last hour of data). 

May it be a bug?

**Comment by nathanielc** [comment]
@MartinAparicioPons If you don't use the `-rec-time` flag the times start at the current time and move forward based on the data in the recording. As a result future dates are common and expected.
