### ISSUE TITLE
get hex codes in alert output after moving to 10.0.1

### ISSUE THREAD

**Issue by devilldog** [influxdata/kapacitor#246]
{"id":"load_shortterm:nil","message":"load_shortterm:nil is CRITICAL","details":"{\u0026#34;Name\u0026#34;:\u0026#34;load_shortterm\u0026#34;,\u0026#34;TaskName\u0026#34;:\u0026#34;load_alert\u0026#34;,\u0026#34;Group\u0026#34;:\u0026#34;nil\u0026#34;,\u0026#34;Tags\u0026#34;:{\u0026#34;host\u0026#34;:\u0026#34;xxx\u0026#34;,\u0026#34;type\u0026#34;:\u0026#34;load\u0026#34;,\u0026#34;type_instance\u0026#34;:\u0026#34;relative\u0026#34;},\u0026#34;ID\u0026#34;:\u0026#34;load_shortterm:nil\u0026#34;,\u0026#34;Fields\u0026#34;:{\u0026#34;value\u0026#34;:1.085},\u0026#34;Level\u0026#34;:\u0026#34;CRITICAL\u0026#34;,\u0026#34;Message\u0026#34;:\u0026#34;load_shortterm:nil is CRITICAL\u0026#34;}","time":"2016-02-18T15:59:33.368443Z","level":"CRITICAL","data":{"series":[{"name":"load_shortterm","tags":{"host":"xxx","type":"load","type_instance":"relative"},"columns":["time","value"],"values":[["2016-02-18T15:59:33.368443Z",1.085]]}]}}

**Comment by nathanielc** [comment]
Yes, that is known change. See #204 The `details` property if HTML formatted data for the alert. It can be controlled via the `.details` method on the AlertNode. See https://docs.influxdata.com/kapacitor/v0.10/tick/alert_node/#details 

It should not affect existing behavior as only a new key was added to the JSON.

**Comment by devilldog** [comment]
Yeah that's fine, by sec regex ignores it, thanks !
