### ISSUE TITLE
Slack integration uses legacy Attachment functionality, should be updated to use Block Kit

### ISSUE THREAD

**Issue by hackery** [influxdata/kapacitor#2460]
The message building code in [slack/service.go](https://github.com/influxdata/kapacitor/blob/master/services/slack/service.go#L282-L295) uses [attachments](https://api.slack.com/messaging/composing/layouts#attachments) for formatting, which is now [considered legacy functionality](https://api.slack.com/messaging/composing/layouts#when-to-use-attachments) and should be reworked to use blocks.

**Comment by lesam** [comment]
Are you experiencing user-visible effects of this that you believe could be resolved by moving to the block kit format? From the same docs:

> While we aren't deprecating them, you should understand that they might change in the future, in ways that reduce their visibility or utility.

Unfortunately it is not possible to move to blocks and keep the same formatting (with the red/yellow/green colour bar) that the slack notifications currently have. I'm not sure it is a good idea to globally change alert formatting just to use the latest API.

**Comment by lesam** [comment]
Attaching a patch to move to blocks in case we need to come back to this, but closing for now.

Patch: https://gist.github.com/lesam/bca46ad159c73655229cc684fa399a90
