### ISSUE TITLE
InfluxDB 2.0 connection config

### ISSUE THREAD

**Issue by mustafah009** [influxdata/kapacitor#2473]
Hi,

Can someone confirm what should the Kapacitor config have in the user and password fields of influxdb to be able to read and write in a batch tick to InfluxDB 2.0?

I’ve tried setting the password field with the Influx admin token as per the documentation and also “username:password” and I’m getting a 401 in both scenarios.

Dbrp is configured to my bucket and I’m using that DB and RP in the tick script.

Thanks

**Comment by docmerlin** [comment]
You have to use the command `influx v1 auth create --username <username> --password <the password>`

**Comment by docmerlin** [comment]
I'm going to go ahead and close this issue, feel free to reopen, if you still have problems.  @mustafah009
