### ISSUE TITLE
How to configure kapacitor v.1.5 to influxdb 2.0 with token ?

### ISSUE THREAD

**Issue by craph** [influxdata/kapacitor#2476]
Hi,

I open this issue because I'm unable to find the correct way to configure Kapacitor with my influxdb 2.0.

My influxdb 2.0 is protected by user/pwd and I have generated a new access token but I can't find where to put the token in the Kapacitor configuration file.

In the go file [client.go](https://github.com/influxdata/kapacitor/blob/master/influxdb/client.go#L110) I can see Token but unable to find it in the config file.

How can I use token in the configuration file ?

Thank you very much for your help.

Best regards,

**Comment by danxmoran** [comment]
Hi @craph, kapacitor is still targeting InfluxDB's v1 APIs. You can still use it with a 2.x deployment, but it'll take a little more setup work. On the InfluxDB side, you'll need to:
1. Create a bucket, and get its ID
2. Decide on parameters you want to use for your V1 mappings:
    * Name of the database you want to map to your bucket
    * Name of the retention policy you want to map to your bucket
    * Name for the user you want to access your bucket
    * Password for the user you want to access your bucket
2. On the command-line, create V1 compatibility mappings:
    * Create a DBRP mapping: `influx v1 dbrp create --org <your-org> --db <db-name> --rp <rp-name> --bucket-id <your-bucket-id>`
    * Create a V1 token: `influx v1 auth create --org <your-org> --username <user-name> --password <password> --write-bucket <your-bucket-id> # Or maybe --read-bucket <your-bucket-id>`

You'd then configure kapacitor using the DB/RP and username+password, as if you were connecting to a v1 instance.

**Comment by craph** [comment]
Hi @danxmoran ,

Thank you very much for the update I appreciate that :)
I'll try what you said and keep you posted:)

I have two other questions : 

1. Do you have an official documentation that explain all this steps ?
2. What is the target for kapacitor to target the InfluxDb's v2 APIs ?

Thank you very much.

**Comment by timhallinflux** [comment]
Kapacitor 1.6 should include two things:
1) the Flux Task engine and associated v2 APIs for managing the tasks
2) a fluxNode for batch-based Flux queries that will use the v2 APIs

**Comment by timhallinflux** [comment]
Here are the docs we have now: https://docs.influxdata.com/influxdb/v2.0/tools/kapacitor/
We need to add the v1 auth setup that @danatinflux outlined above to those instructions. @kelseiv
