### ISSUE TITLE
Integrate Kapacitor with new Query Engine

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#249]

**Comment by yosiat** [comment]
Hi @nathanielc ,
What capabilities/features the new query engine will bring? there is documentation/issue on influxdb about this?

**Comment by rossmcdonald** [comment]
@yosiat The PR is [here](https://github.com/influxdata/influxdb/pull/5196), which contains a high-level overview of the changes.

**Comment by yosiat** [comment]
@rossmcdonald  thanks!

**Comment by nathanielc** [comment]
Fixed in https://github.com/influxdata/kapacitor/pull/280
