### ISSUE TITLE
Markdown In Slack Alerts

### ISSUE THREAD

**Issue by nhproject** [influxdata/kapacitor#251]
Hi all,

Is it possible to combine markdown in the alerts' messages? In particular I'm referring to Slack.
I know Slack supports markdown lang.

Thanks!

**Comment by nathanielc** [comment]
The alert message can contain whatever content you want. I am not sure whether slack will honor the markdown based on how we call the API but its worth a try.

**Comment by nhproject** [comment]
https://github.com/influxdata/kapacitor/blob/master/services/slack/service.go#L63
@nathanielc Three parameters are shown in this section of the file: Fallback, Text, Color.
We probably need to add fourth parameter - "mrkdwn_in" - in order we will be able to work with markdown, and also mention that the text should work with markdown, like it is shown here:
https://api.slack.com/docs/formatting#message_formatting
in the attachments section.
(I'm not sure how to write this parameter using the GO api you used for this implementation)
