### ISSUE TITLE
Handle HTTP OPTIONS requests for DELETE from browser

### ISSUE THREAD

**Issue by gargooza** [influxdata/kapacitor#255]
I'm trying to write a JavaScript front-end that allows me to manage Kapacitor tasks through a browser. This means I'm doing a lot of XMLHttpRequest to talk to Kapacitor.

The (undocumented) API for deleting a task requires the HTTP DELETE method. For security reasons, browsers preflight DELETE requests with an OPTIONS request. Kapacitor returns a 404 response to that preflight OPTIONS request, thus preventing the browser from ever sending the DELETE.

GET and POST requests via browser work great for the undocumented API methods such as defining, enabling, disabling, listing, etc. But I need to be able to delete tasks. I know the API isn't official yet but if deleting tasks is going to be implemented via HTTP DELETE then it seems you'll also want to be able deal with OPTIONS requests so browser front-ends can fully communicate directly with Kapacitor.

**Comment by nathanielc** [comment]
@gargooza This should be an easy fix, I'll put something up in a bit
