### ISSUE TITLE
Finalize kapacitor flux tasks API & UX

### ISSUE THREAD

**Issue by lesam** [influxdata/kapacitor#2556]
After https://github.com/influxdata/kapacitor/pull/2555 , we have flux tasks working, provisionally at API endpoint `kapacitor/v1/fluxtasks/...` instead of 2.x's `api/v2/tasks` .

Need to figure out the actual correct api endpoints (probably `kapacitor/v1/flux/tasks` ?) and figure out how the users will actually access this API - will the `influx` client work or should we add this to the `kapacitor` client?

**Comment by timhallinflux** [comment]
hmmm... I'm using this as a reference: https://docs.influxdata.com/influxdb/v1.8/tools/api/
to review how we handled the compatibility between v1 and v2 for the read and write paths on InfluxDB.

any reason not to do <kapacitor>/api/v2/tasks  where the <kapacitor> bit is the base path?
