### ISSUE TITLE
how many data/s can Kapacitor handle 

### ISSUE THREAD

**Issue by earthnut** [influxdata/kapacitor#260]
@nathanielc 

I found a very strange issue when I tried to setup alert to our influxDB which hosts our network traffic data.

from influxdb side: 
     1. I see Kapacitor as a subscriber
     2. UDP packet send out to Kapacitor UDP port 

from the server running Kapacitor:
    1. I see Kapacitor listened on the same UDP port 
    2. The RX of the port shows incoming data .
   3.  the peak of the incoming data flow is 9.+Mb and  average is 2.5+Mb

from Kapacitor:
    1. I see the label are all 0 ;

>    Name: cpu_alert
Error:
Type: stream
Enabled: true
Executing: true
Databases Retention Policies: ["collectd"."default"]
TICKscript:
stream
    .from().measurement('load_shortterm')
    .groupBy('host')
    .alert()
        .id('kapacitor/{{ .Name }}/{{ .Group }}')
        .message('{{ .ID }} is {{ .Level }} value:{{ index .Fields "value" }}')
        .crit(lambda: "value" >0 )
        .log('/var/log/kapacitor/alert.log')

	DOT:
	digraph cpu_alert {
	stream0 -> stream1 [label="0"];
	stream1 -> alert2 [label="0"];
	}

   2. I try to get the "bytes_rx" from the stats map using:
        
`stream.from().database('_kapacitor').retentionPolicy('default').alert().crit(lambda: count() > 0 OR TRUE).log(path to log file)`

But when I look into  the log file,   there is no "bytes_rx" metric show up.

I think I am stuck in the debugging process. Do you have any idea on this case ?

Thanks a lot .

**Comment by nathanielc** [comment]
Looks like you have a mix up in your task definition. The task is defined
to get data from collectd.default while the script has _kapacitor.default,
these combined mean the task doesn't get any data.

**Comment by earthnut** [comment]
@nathanielc 

sorry for the confusing, there are  2 scripts
  1. cpu_alert is the script  processing the steaming data from influxDB collectd.default
  2. stream.from().database('_kapacitor').retentionPolicy('default').alert().crit(lambda: count() > 0 OR TRUE).log(path to log file)  to print the Kapacitor internal status 

  the label for the 1st script is 0 and no log in the log file
  the label for the 2nd script is not 0 and I found messages in the log file, however I didn't find "bytes_rx".

   The reason why I put the 2nd script there is:
       i found the code `s.statMap.Add(statBytesReceived, int64(n))`
   
   I think  no "bytes_rx"  may mean no data was handled by this function.


Thanks

**Comment by earthnut** [comment]
summarize the issue I met:
       influxDB is running on host_a
       kapacitor is running on host_b  



   1. Kapacitor is  listening on the UDP  port_k
   2. influxdb is sending UDP data to host_b: port_k
   3. tcpdump on host_b port_k shows incoming data.
   4. there is no bytes_rx in the Kapacitor internal status metric.

**Comment by nathanielc** [comment]
@earthnut Thanks for digging in, looks like there is a bug with the UDP service code where it is reporting its stats the old way and so it is not being recorded. It is super easy fix so I'll try and get something up for it today. 

As for why the cpu_alert task is not getting data there are a few reasons:

1. Network - but you have verified this on many levels and should be good
2. The task database does not match the incoming data. Meaning the task is listening for a different dbrp value than the subscription provides. You seem to already have check this.
3. Lastly the measurement name could be different from the data and what is being selected in the task. 

It has to be one of these three layers, or Kapacitor has a severe bug ;) 

If its not an issue could you post the start up log for Kapacitor, and a small dump of the data on the port? In the startup log I am interested in the lines relating to subscriptions as they will confirm the dbrp of the subscriptions. The dump of packets (plain text is fine) should show the measurement name. With all that data we can confirm which layer is the issue.

Thanks for working through this.

**Comment by earthnut** [comment]
@nathanielc 

  We figure out the reason. Sorry,  it is the Firewall who blocked the traffic. 
  I will close this issue.
Thanks
