### ISSUE TITLE
Kapacitor crash on task definition

### ISSUE THREAD

**Issue by sofixa** [influxdata/kapacitor#264]
Hello, everybody.

We are having an issue with Kapacitor. It works fine with basic tasks, but on our first try at a more complicated TICKScript, kapacitord crashes and refuses to relaunch(it outputs the same Go stacktrace). So far the only way I've found to make it start again is to delete everything in ~/.kapacitor/tasks/*

Judging by the errors, it seems like the groupBy isn't properly used. Still, i don't think that a crash is the expected result.

This is our TICKScript
```javascript
stream
    // Select just the cpu measurement from our example database.
    .from().measurement('mem')
    .window()
        .period(10s)
        .every(10s)
    .groupBy('host')
    .where(lambda: "used_percent" > 80)
    .alert()
        .message('{{ .Level}}: {{ .Name }}/{{ index .Tags "host" }}  - <strong>used_percent</strong> is {{ index .Fields "used_percent" }}')
        .crit(lambda: "used_percent" >  80)
        .hipChat()
        .log('/tmp/alerts.log')
```

This is what kapacitor says when the task is defined and enabled or upon launch after a crash :

`root@oxalide:~# kapacitord -config /etc/kapacitor/kapacitor.conf
2016/02/29 11:08:54 Using configuration at: /etc/kapacitor/kapacitor.conf
[run] 2016/02/29 11:08:54 I! Kapacitor starting, version 0.10.1, branch master, commit 22b917b4722addf9ff604d16fa01                                                                                                                          a09431641c55
[run] 2016/02/29 11:08:54 I! Go version go1.5.3, GOMAXPROCS set to 1
[srv] 2016/02/29 11:08:54 I! Kapacitor hostname: 10.255.128.6
[task_master] 2016/02/29 11:08:54 I! opened
[srv] 2016/02/29 11:08:54 I! ClusterID: d4ec085c-2282-48c9-8ba9-81ead22ab97e ServerID: 3ab0c9b0-1d90-49ce-a4d2-abb0                                                                                                                          63a44adf
[httpd] 2016/02/29 11:08:54 I! Starting HTTP service
[httpd] 2016/02/29 11:08:54 I! Authentication enabled: false
[httpd] 2016/02/29 11:08:54 I! Listening on HTTP: [::]:9092
[influxdb] 2016/02/29 11:08:54 I! linking subscriptions
[udp:telegraf.default] 2016/02/29 11:08:54 I! Started listening on UDP: 10.255.128.6:55877
[influxdb] 2016/02/29 11:08:54 I! started UDP listener for telegraf default
[task_master] 2016/02/29 11:08:54 I! Started task: mem_alert
[stats] 2016/02/29 11:08:54 I! opened service
[run] 2016/02/29 11:08:54 I! Listening for signals
panic: not implemented

goroutine 36 [running]:
github.com/influxdata/kapacitor.(*GroupByNode).runGroupBy(0xc82000d420, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/group_by.go:44 +0x360
github.com/influxdata/kapacitor.(*GroupByNode).(github.com/influxdata/kapacitor.runGroupBy)-fm(0x0, 0x0, 0x0, 0x0,                                                                                                                           0x0)
        /root/go/src/github.com/influxdata/kapacitor/group_by.go:25 +0x4c
github.com/influxdata/kapacitor.(*node).start.func1(0xc82000d420, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/node.go:95 +0x7f
created by github.com/influxdata/kapacitor.(*node).start
        /root/go/src/github.com/influxdata/kapacitor/node.go:96 +0x8d

goroutine 1 [chan receive]:
main.(*Main).Run(0xc820119ef0, 0xc82000a1c0, 0x2, 0x2, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/main.go:96 +0xbf1
main.main()
        /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/main.go:41 +0x363

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select]:
github.com/influxdata/kapacitor.(*Edge).NextPoint(0xc820149290, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/influxdata/kapacitor/edge.go:119 +0x17d
github.com/influxdata/kapacitor.(*TaskMaster).runForking(0xc820077760, 0xc820149290)
        /root/go/src/github.com/influxdata/kapacitor/task_master.go:380 +0x76
created by github.com/influxdata/kapacitor.(*TaskMaster).stream
        /root/go/src/github.com/influxdata/kapacitor/task_master.go:374 +0x14f

goroutine 27 [chan receive]:
github.com/influxdata/kapacitor/services/udp.(*Service).processPackets(0xc820150a00)
        /root/go/src/github.com/influxdata/kapacitor/services/udp/service.go:143 +0xe6
created by github.com/influxdata/kapacitor/services/udp.(*Service).Open
        /root/go/src/github.com/influxdata/kapacitor/services/udp/service.go:105 +0xc84

goroutine 26 [IO wait]:
net.runtime_pollWait(0x7f3a773ab890, 0x72, 0xc82000e190)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820109b80, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820109b80, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readFrom(0xc820109b20, 0xc8201c6000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7f3a773a4050, 0xc82000e190)
        /usr/local/go/src/net/fd_unix.go:259 +0x2a5
net.(*UDPConn).ReadFromUDP(0xc820024188, 0xc8201c6000, 0x10000, 0x10000, 0x10000, 0x10000, 0x0, 0x0)
        /usr/local/go/src/net/udpsock_posix.go:61 +0x117
github.com/influxdata/kapacitor/services/udp.(*Service).serve(0xc820150a00)
        /root/go/src/github.com/influxdata/kapacitor/services/udp/service.go:125 +0x166
created by github.com/influxdata/kapacitor/services/udp.(*Service).Open
        /root/go/src/github.com/influxdata/kapacitor/services/udp/service.go:103 +0xc39

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7f3a773ab950, 0x72, 0xc82000e190)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820108a70, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820108a70, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820108a10, 0x0, 0x7f3a773aba90, 0xc8201576a0)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820024128, 0x455ad0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820024128, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc820016c60, 0x7f3a773aa9d0, 0xc820024128, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7f3a773aa9d0, 0xc820024128, 0x7f3a773aba68, 0xc820016a20, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1765 +0x85
github.com/influxdata/kapacitor/services/httpd.(*Service).serve.func1(0xc820013770)
        /root/go/src/github.com/influxdata/kapacitor/services/httpd/service.go:114 +0x6e
created by github.com/influxdata/kapacitor/services/httpd.(*Service).serve
        /root/go/src/github.com/influxdata/kapacitor/services/httpd/service.go:122 +0x35

goroutine 33 [select]:
github.com/influxdata/kapacitor.(*Edge).NextPoint(0xc8201e2120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/influxdata/kapacitor/edge.go:119 +0x17d
github.com/influxdata/kapacitor.(*StreamNode).runStream(0xc8201397a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/stream.go:42 +0x89
github.com/influxdata/kapacitor.(*StreamNode).(github.com/influxdata/kapacitor.runStream)-fm(0x0, 0x0, 0x0, 0x0, 0x                                                                                                                          0)
        /root/go/src/github.com/influxdata/kapacitor/stream.go:31 +0x4c
github.com/influxdata/kapacitor.(*node).start.func1(0xc8201397a0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/node.go:95 +0x7f
created by github.com/influxdata/kapacitor.(*node).start
        /root/go/src/github.com/influxdata/kapacitor/node.go:96 +0x8d

goroutine 34 [select]:
github.com/influxdata/kapacitor.(*Edge).NextPoint(0xc8201b4cf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/influxdata/kapacitor/edge.go:119 +0x17d
github.com/influxdata/kapacitor.(*StreamNode).runStream(0xc8201398c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/stream.go:42 +0x89
github.com/influxdata/kapacitor.(*StreamNode).(github.com/influxdata/kapacitor.runStream)-fm(0x0, 0x0, 0x0, 0x0, 0x                                                                                                                          0)
        /root/go/src/github.com/influxdata/kapacitor/stream.go:31 +0x4c
github.com/influxdata/kapacitor.(*node).start.func1(0xc8201398c0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/node.go:95 +0x7f
created by github.com/influxdata/kapacitor.(*node).start
        /root/go/src/github.com/influxdata/kapacitor/node.go:96 +0x8d

goroutine 35 [select]:
github.com/influxdata/kapacitor.(*Edge).NextPoint(0xc8201b4f30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/influxdata/kapacitor/edge.go:119 +0x17d
github.com/influxdata/kapacitor.(*WindowNode).runWindow(0xc8200e2900, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/window.go:31 +0x11b
github.com/influxdata/kapacitor.(*WindowNode).(github.com/influxdata/kapacitor.runWindow)-fm(0x0, 0x0, 0x0, 0x0, 0x                                                                                                                          0)
        /root/go/src/github.com/influxdata/kapacitor/window.go:24 +0x4c
github.com/influxdata/kapacitor.(*node).start.func1(0xc8200e2900, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/node.go:95 +0x7f
created by github.com/influxdata/kapacitor.(*node).start
        /root/go/src/github.com/influxdata/kapacitor/node.go:96 +0x8d

goroutine 37 [runnable]:
github.com/influxdata/kapacitor.(*node).start.func1(0xc82000d500, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/node.go:75
created by github.com/influxdata/kapacitor.(*node).start
        /root/go/src/github.com/influxdata/kapacitor/node.go:96 +0x8d

goroutine 38 [runnable]:
github.com/influxdata/kapacitor.(*node).start.func1(0xc8201dec60, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/kapacitor/node.go:75
created by github.com/influxdata/kapacitor.(*node).start
        /root/go/src/github.com/influxdata/kapacitor/node.go:96 +0x8d

goroutine 39 [runnable]:
github.com/influxdata/kapacitor.(*ExecutingTask).runSnapshotter(0xc8201ad260)
        /root/go/src/github.com/influxdata/kapacitor/task.go:370
created by github.com/influxdata/kapacitor.(*ExecutingTask).start
        /root/go/src/github.com/influxdata/kapacitor/task.go:184 +0x236

goroutine 40 [runnable]:
github.com/influxdata/kapacitor/services/task_store.(*Service).StartTask.func1(0xc8201ad260, 0xc820016a80, 0xc8201a                                                                                                                          2940)
        /root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:611
created by github.com/influxdata/kapacitor/services/task_store.(*Service).StartTask
        /root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:625 +0x271

goroutine 41 [runnable]:
github.com/influxdata/kapacitor.(*TaskMaster).runForking(0xc820077760, 0xc8201e2510)
        /root/go/src/github.com/influxdata/kapacitor/task_master.go:378
created by github.com/influxdata/kapacitor.(*TaskMaster).stream
        /root/go/src/github.com/influxdata/kapacitor/task_master.go:374 +0x14f

goroutine 42 [runnable]:
github.com/influxdata/kapacitor/services/stats.(*Service).sendStats(0xc820083e00)
        /root/go/src/github.com/influxdata/kapacitor/services/stats/service.go:95
created by github.com/influxdata/kapacitor/services/stats.(*Service).Open
        /root/go/src/github.com/influxdata/kapacitor/services/stats/service.go:76 +0x1fa

goroutine 43 [runnable]:
github.com/influxdata/kapacitor/services/reporting.(*Service).usage(0xc820078900)
        /root/go/src/github.com/influxdata/kapacitor/services/reporting/service.go:83
created by github.com/influxdata/kapacitor/services/reporting.(*Service).Open
        /root/go/src/github.com/influxdata/kapacitor/services/reporting/service.go:65 +0x39c

goroutine 44 [runnable]:
github.com/influxdata/kapacitor/cmd/kapacitord/run.(*Server).Open.func2(0xc82008bf00)
        /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/server.go:440
created by github.com/influxdata/kapacitor/cmd/kapacitord/run.(*Server).Open
        /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/server.go:447 +0x8f

goroutine 45 [runnable]:
github.com/influxdata/kapacitor/cmd/kapacitord/run.(*Command).monitorServerErrors(0xc820078630)
        /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/command.go:145
created by github.com/influxdata/kapacitor/cmd/kapacitord/run.(*Command).Run
        /root/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/run/command.go:127 +0x1314

goroutine 46 [select, locked to thread]:
runtime.gopark(0xda5d50, 0xc8201eb728, 0xc42d40, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc8201eb728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc8201eb728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
`

Thanks in advance.

**Comment by sofixa** [comment]
It would be nice if there's a TICKScript parser/checker, which, upon defining a task, would try to parse the .tick file and output any errors :) Feature request ?

**Comment by nathanielc** [comment]
@sofixa This has been fixed #236 

Kapacitor does parse the TICKscript when it is defined and returns any errors. This was a case of a branch of code that was hit that was not implemented yet and paniced. #236 fixes the issue, in the future a simple error will be returned instead of a panic.

**Comment by sofixa** [comment]
Has this been pakcaged in the latest .deb or do we need to compile from source?

**Comment by nathanielc** [comment]
@sofixa It has been packaged in the nightly build which can be found with the rest of the downloads here https://influxdata.com/downloads/. It is not yet part of an official release.

**Comment by sofixa** [comment]
Okay, thanks :)
