### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#267]
Hi,

I am using Kapacitor 0.10.1 (nightly version from one week ago) with 950 stream tasks that split to two kinds:

- Filter by two tags and check the values and trigger alert to based on them

- Filter by two tags, create value delta (using window, and two mapReduce for first and last) and trigger alert based on the value delta.

Those alerts send to log file (for start, in the future they will post to some http service).

I have started to ingest events 200,000 events (every 10 second) and I see that kapacitor takes 100% cpu on: 2 cores, 4gb virtual machine.

**Comment by nathanielc** [comment]
I you are using the nightly you should be able to see which node in a task is slowest. Can you share the `show` output of one of the tasks so we can begin to understand the performance profile?

**Comment by yosiat** [comment]
I am using:
> 0.11.0~n1455782624 (git: master f741d460c4f1b77647efc93ad6718252f051e3c0)

So I don't the throuput metrics yet, tomorrow (Israel time) I will upgrade to the latest nightly.

By the way, some info that I forgot to mention:
- I am using Ethernet 
- I am calling write directly to kapacitor without using influxdb

**Comment by yosiat** [comment]
Hi @nathanielc,
I have installed the latest nightly and now I see that the throughput is between 750 to 820 points per second.

I have upgraded to 4 cores and the cpu is still 100%

**Comment by nathanielc** [comment]
Could you post the complete `show` output from two of your tasks?

**Comment by yosiat** [comment]
Yes, btw - I see that we have high cpu usage while inserting and I changed the alerts to post to http service instead of log file.

![20160302_183009](https://cloud.githubusercontent.com/assets/306253/13467086/555c609e-e0a5-11e5-8de9-f0503c38bce9.jpg)

![20160302_182856](https://cloud.githubusercontent.com/assets/306253/13467038/31834ef8-e0a5-11e5-988d-43c754eb4f17.jpg)

**Comment by yosiat** [comment]
@nathanielc any ideas? 

I reproducing this high cpu usage on my dev computer and I am seeing something weird:
On the production vm I saw there was 5-6 processes of kapacitor (I saw in htop in tree mode) and In my local computer I see only one process.

_On the prod I have 950 tasks and in my local computer I have 4 tasks_

**Comment by nathanielc** [comment]
@yosiat Kapacitor is single processed but multi-threaded, htop will show threads by default http://unix.stackexchange.com/questions/10362/why-does-htop-show-more-process-than-ps

As for the high cpu, what is your expectation of cpu usage for your ingestion rate? Based on the info I see you are pushing approx  950*4000 = 3,800,000 metrics per second. If that is the case then 100% cpu on 4 cores is really efficient. 

Could you get me some more data? First that 3.8 million number is a complete guess and seems really high, what is your real total throughput? Kapacitor reports its total throughput as the `TASK_MASTER` task. You can use a task like this one to save those metrics in InfluxDB

```javascript
stream
    .from()
    .influxDBOut()
        .precision('s')
```

Then query your total throughput like this:

```
select non_negative_derivative(collected) from edges where task = 'TASK_MASTER' and parent = 'write_points' and time > now() - 1m
```

That should give us more insight into the total amount of work Kapacitor is doing.

Second capturing a cpu and memory profile from Kapacitor would also help to expose bottle necks. If you start kapacitord with the args  `-cpuprofile path/to/cpu.prof -memprofile path/to-mem.prof ` then let Kapacitor run for a few minutes at least and shut it down the files will contain profiles I can use to further investigate any bottle necks in the code.

**Comment by yosiat** [comment]
@nathanielc I will send the data as soon as possible!

But before that I don't understand your calculation of 3.8 million metrics per second.
I am ingesting to Kapacitor 4500 metrics per second, If Kapacitor replicates those metrics it would be in-efficient, why not route the metrics to specific tasks instead of ingesting to all tasks?

For example:

- Read from the point it's measurement,db and rp 
- Find the relevant tasks (by building index of (measurement,db,rp) to task)
- Insert point to task stream

**Comment by nathanielc** [comment]
Kapacitor does duplicate the metric for each task so that each task can manipulate the data. I have already profiled the duplication overhead and it is not significant. The reason I multiplied by the tasks was because I assumed each task was getting a unique set of data, obviously a wrong assumption. The throughput value that the query will return is the number of points Kapacitor has received not the duplicated count so it will give a good idea of how much data is being shared/duplicated across tasks.

Another question: How similar are the 950 tasks? In my experience it is easy to write a single task to handle a large scope problem. Could you show me a few example TICKscripts for your tasks? If not could you explain some of the differences between each of the tasks?

Thanks for working with me through all of this :)

**Comment by yosiat** [comment]
Thank you for helping me out with Kapacitor :)

My tasks falls to two structures (which I posted above as Alert1 and Alert2) they vary by their measurement and thresholds.

**Comment by yosiat** [comment]
@nathanielc I have ran this query:
```
select non_negative_derivative(collected) from edges where task = 'TASK_MASTER' and parent = 'write_points' and time > now() - 1m
```

and got between 480 to 485

**Comment by yosiat** [comment]
@nathanielc 
I have upgraded the machine to 8 cores and Kapacitor got faster and 70% cpu.

I think I can make performance improvements, right know I write all the data toל Kapacitor and rely on it to filter the measurements, I am thinking to do this on my side and it will take the pressure down on Kapacitor.

What do you think?

BTW - Do you have any benchmark result on Kapacitor? how many tasks & points per second it can handle?

**Comment by yosiat** [comment]
@nathanielc  I upgraded to nightly and thanks to #360 we dropped from 70% steady to 0.1% with little peaks of 9% cpu.

Next week we will run hermeticity test to make sure we are processing 100% of the data, until then I will close this issue.
