### ISSUE TITLE
Topic Store Rewrite

### ISSUE THREAD

**Issue by docmerlin** [influxdata/kapacitor#2723]
### Primary problem:

Topics save the entire alert state to disk every time an alert state changes. This is only ever read on application startup. For small alert ID cardinality, this is fine, but when cardinality gets large, this causes massive slowdowns, as the state of all alert topics is saved any time any one of the alerts changes.

#### Secondary problem:

There is no way to delete topic state, so it grows without bound when alert id cardinality is unbounded.

#### Proposed Solution to Primary problem:

We change the current on-disk format to allow for updating the alert topic by alert ID instead of all at once.

##### Current Key Format:

```string
/topics/data/main:nameOfTopic:alert5
```

##### Current Value Format:

```json
{
  "version": 1,
  "value": {
    "topic": "main:nameOfTopic:alert5",
    "event-states": {
      "alertID0": {
        "message": "Message",
        "details": " large user specified string ",
        "time": "2022-09-22T23:45:00Z",
        "duration": 0,
        "level": "INFO"
      },
....
....      
....
      "alertID1": {
        "message": "Message",
        "details": " large user specified string ",
        "time": "2022-09-23T12:40:00Z",
        "duration": 900000000000,
        "level": "INFO"
      }
    }
  }
}
```

Any changes to the topic/alert require the entire state of all the events it has seen be saved. We propose breaking it up into keys and buckets. The bucket, would take the name of the current key, and each key inside that bucket would take the key of the current key in the `"event-states"` object.

##### Proposed Bucket name String:

```
/topics/data/main:nameOfTopic:alert5
```

##### Proposed Key Format:

The proposed key is just the alert ID

```
alertID0
```

##### Proposed Value Formats:

```json
{
        "message": "Message",
        "details": " large user specified string ",
        "time": "2022-09-22T23:45:00Z",
        "duration": 0,
        "level": "INFO"
}
```

Furthermore, some of these objects can get very large so we are considering compressing with lz4 or snappy, as we already have a dependency on libraries for each of them.

##### Rollback:

Do we need rollback capacity, for saving the current topic alert states across a rollback, to a version of kapa that uses the old on disk scheme?

#### Proposed solution to Secondary Problem:

Allow automated deletion of event-state alert-ids. When we have a Reset and we return to `OK` state, we should delete the alert-id from the topic store. We should also allow the alert to time out and the ID be deleted, if it continues past a user specified time, as has been requested by other users.

**Comment by gwossum** [comment]
@docmerlin The current key format and proposed key format look the same to me. Are they supposed to be the same?

**Comment by gwossum** [comment]
@docmerlin Looks reasonable. What is the suggested way to detect new storage vs old storage format?

**Comment by docmerlin** [comment]
> @docmerlin Looks reasonable. What is the suggested way to detect new storage vs old storage format?

Update the version key in the DB.  The DB already stores its format elsewhere.
