### ISSUE TITLE
Status of recordings

### ISSUE THREAD

**Issue by gargooza** [influxdata/kapacitor#279]
Would it be possible to add a field to the `kapacitor list recordings` results that indicates whether a recording has completed? Recordings can take a long time to create and it would be nice to know which ones have finished so they can be replayed. I know that I can do an HTTP GET for /task?id=81a...323 and wait for it to return, but that's not really a good option. This is especially true in cases where I'd like to report recording results on a webpage immediately while many recordings are being created simultaneously.

If I can add an "I wish" feature request, too, it would be cool if that completion status also indicated how much of the recording has been processed. It may not be perfect, but just a simple percentage of the time duration has been covered so far would suffice.

**Comment by nathanielc** [comment]
I think something like this would be possible, and would also play nice with #283

**Comment by nathanielc** [comment]
This was fixed as part of the API rewrite.
