### ISSUE TITLE
Kapacitor Alert.Exec() can't find executable in $PATH

### ISSUE THREAD

**Issue by DJFliX** [influxdata/kapacitor#282]
I'm running a tick script that feeds JSON and an email address to a NodeJS Application built with nexe. The executable is placed in /usr/local/bin/ and can be resolved:

```bash
azureuser@influx-dev:~/tickscripts$ whereis templatemail
templatemail: /usr/local/bin/templatemail
```

When reading `/var/log/kapacitor/kapacitor.log` I see the following error:
`[ID1234:alert3] 2016/03/04 13:57:33 E! error running alert command: exec: "templatemail": executable file not found in $PATH`

Does capacitor not adhere to the regular $PATH variables? Or is there a special path that I can set?

This is the tick script responsible for sending a notification to the templatemailer:

```javascript
var s = stream
  .from().measurement('ID1234')
  .window()
    .period(15m)
    .every(5m)

s.alert()
    .id('ID1234')
    .message('{{ .ID }} is {{ .Level }} value: {{ index .Fields "importantval" }}')
    .warn(lambda: "importantval" > 23.0)
    .crit(lambda: "importantval" > 25.0)
    .log('/tmp/alerts2.log')
    .stateChangesOnly()
    .exec('templatemail', 'violationwarning', '{name:"Felix Mann",user:"user@example.com"}')
```

**Comment by OrangeTux** [comment]
The content of $PATH variable depends on the user. I suppose kapacitor is not running under user `azureuser`. Is best practise not to depend on $PATH in these cases and use full path to the executable:

```
s.alert()
    ...
    .exec('/usr/local/bin/templatemail', 'violationwarning', '{name:"Felix Mann",user:"user@example.com"}')
```

**Comment by DJFliX** [comment]
I am very sorry to have wasted your time! Thank you for a clear and quick response. I should have thought of that. Have a great day!

**Comment by OrangeTux** [comment]
You're welcome.
