### ISSUE TITLE
Record and Replay immediately

### ISSUE THREAD

**Issue by gargooza** [influxdata/kapacitor#283]
Is there an option to immediately replay a recording after it has been created? If there isn't, can that be implemented? I'd like to be able to start a recording and then have that recording get replayed without waiting for the CLI or HTTP GET to return and then issue a separate replay command.

**Comment by nathanielc** [comment]
No, but it should most definitely be implemented. It should be as simple as adding another option to the record command to auto-replay against a task. 

Another possible implementation is to perform the replay as the recording is happening without actually saving the replay. This way you can replay larger periods without having to worry about local disk space, etc.

**Comment by gargooza** [comment]
Those are both great ideas and would be really useful. The latter makes a lot of sense and at least for the way I use kapacitor I don't have a need to store recordings locally.

**Comment by nathanielc** [comment]
For the later case, do you frequently replay the same recording multiple times or is it more of a 1:1 relation between recording:replay counts?

In other words if the later case didn't save the recording at all and just replayed it as it recorded it would that be OK?

**Comment by gargooza** [comment]
I only replay it once. 1:1
