### ISSUE TITLE
Task namespacing

### ISSUE THREAD

**Issue by lpalm** [influxdata/kapacitor#284]
I'd like to be able to use a single Kapacitor instance but be able to partition tasks such that some users only see their own tasks. Another use case is to separate throwaway tasks that we use for backtesting and persistent production alerts generated after backtesting them first. They are similar but different in the outputs they produce. 

Is there already a way to do this? Otherwise I was thinking of using a naming convention and use that to filter any displayed list of tasks, e.g:
- USER|userName|taskName
- TEST|taskName
- PROD|taskName

It would be nicer to have a built-in way to separate tasks, but if not, are there restrictions in the maximum length or allowed characters in a task name?

Thanks.

**Comment by nathanielc** [comment]
There is no builtin way to namespace tasks. Your idea to prefix the names will work well for now. This kind of a feature will come along with adding real users and authentication to Kapacitor which is on the roadmap.

**Comment by lpalm** [comment]
Sounds good, thanks.
