### ISSUE TITLE
[0.11.0] Unexpected Type

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/kapacitor#287]
Version information:

```
Kapacitor 0.11.0~n1457078737 (git: master a5cf89b6ff2de970fa4a2fabc5faa23e0a08f224)
```

I'm trying to cast a float to an int for a little more appealing error messages. When I use the tick script (`disk_used`):

```
stream
    .from().measurement('disk')
    .groupBy('host','path')
    .eval(lambda: int("used_percent")).as('used_percent')
    .alert()
      .warn(lambda: "used_percent" > 75)
      .crit(lambda: "used_percent" > 85)
      .log('/tmp/disk_alerts.log')
      .stateChangesOnly()
```

I get the error:

```
[disk_used:eval2] 2016/03/04 21:27:30 E! expression returned unexpected type int64
[task_master] 2016/03/04 21:27:30 E! Stopped task: disk_used expression returned unexpected type int64
[task_store] 2016/03/04 21:27:30 E! task disk_used finished with error: expression returned unexpected type int64
```

The digraph looks like:

```
DOT:
digraph disk_free {
srcstream0 -> stream1;
stream1 -> eval2;
eval2 -> alert3;
}
```

So it looks like:

```
.eval(lambda: int("used_percent")).as('used_percent')
```

Is expecting a `float64` return type. I get this error whether I'm using the name `.as('used_percent')` or `.as('used_percent_int')`. 

Is there something I'm doing wrong, or is there a different way to cast values?

**Comment by nathanielc** [comment]
@rossmcdonald Definitely a bug, but since you just care about an alert message there is another way to format the message:

```
.alert()
    .message('{{.ID}} is {{.Level}}: Used Percentage: {{ index .Fields "used_percent" | printf "%d"}}')
```

**Comment by rossmcdonald** [comment]
@nathanielc Ah, excellent. Thanks for your help!

**Comment by rossmcdonald** [comment]
@nathanielc Actually, when I use:

```
Used Percentage: {{ index .Fields "used_percent" | printf "%d" }}
```

What I get now is:

```
Used Percentage:%!d(float64=80.51166639306805)
```

This works, though:

```
Used Percentage: {{ index .Fields "used_percent" | printf "%.f" }}
```

**Comment by nathanielc** [comment]
Correct sorry it is a float after all.

On Fri, Mar 4, 2016 at 3:21 PM, Ross McDonald <notifications@github.com>
wrote:

> @nathanielc <https://github.com/nathanielc> Actually, when I use:
>
> Used Percentage: {{ index .Fields "used_percent" | printf "%d" }}
>
> What I get now is:
>
> Used Percentage:%!d(float64=80.51166639306805)
>
> This works, though:
>
> Used Percentage: {{ index .Fields "used_percent" | printf "%.f" }}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdata/kapacitor/issues/287#issuecomment-192496970>
> .
>



-- 
*Nathaniel Cook*
Kapacitor Lead
▼▴

*InfluxData.com <http://influxdata.com/>*

Twitter <http://www.twitter.com/nathanielvcook>
