### ISSUE TITLE
Tasks stop executing when unable to connect InfluxDB

### ISSUE THREAD

**Issue by fffw** [influxdata/kapacitor#289]
My InfluxDB crashed for a few hours and all batch tasks stopped without my notice. Do we have an option to let tasks continue executing next time even it failed? I didn't spot such option from the default configuration.

> [task_master] 2016/02/22 12:00:42 E! Stopped task: heroku_response_time Get https://<host>:8080/ping: dial tcp 127.0.1.1:8080: getsockopt: connection refused

**Comment by nathanielc** [comment]
@fffw For errors connecting to InfluxDB this has been fixed in the nightlies. The InfluxDBOut Node will only log failures but continue to operate. Working on adding stats about dropped writes as well so it is easier to track any drops.

**Comment by fffw** [comment]
Thanks @nathanielc ! I didn't use `InfluxDBOut` node, only run batch queries from InfluxDB. Did that fixed as well?

**Comment by nathanielc** [comment]
@fffw No it do not, It is an easy fix.

**Comment by fffw** [comment]
Great thanks!

**Comment by fffw** [comment]
Wow it's quick @nathanielc ! Thanks!
