### ISSUE TITLE
Handle HTTP OPTIONS requests for DELETE recording

### ISSUE THREAD

**Issue by gargooza** [influxdata/kapacitor#300]
I'm having the same issue deleting recordings via XMLHttpRequest() from a browser as I was  for tasks (see https://github.com/influxdata/kapacitor/issues/255). This ought to be a simple fix, no?

**Comment by nathanielc** [comment]
Yep, thanks

**Comment by gargooza** [comment]
SO FAST! Thanks, Nathaniel!
