### ISSUE TITLE
Question: Format value as human readable

### ISSUE THREAD

**Issue by ivankennethwang** [influxdata/kapacitor#303]
Is there a way to format the message in a tick script such that 

instead of printing 1.691058176e+09, it will 1.69GB?

**Comment by nathanielc** [comment]
You have all of the traditional `printf` type formats available but I do not think human readable byte sizes is among them. https://golang.org/pkg/fmt/

It would not be too hard to add helper functions for this. PRs welcome :)

**Comment by ivankennethwang** [comment]
I'm not an expert in Go. I tried looking around to understand the code. Meanwhile, I think it will be great if we can add something like this... https://godoc.org/github.com/dustin/go-humanize?

**Comment by titilambert** [comment]
@nathanielc Could you give an example ?
I guess, it's something like:
```
{{ index .Fields "used_percent" "%.2f" }}
```

**Comment by titilambert** [comment]
@nathanielc Could you also give us some hint to be able to create a PR with https://godoc.org/github.com/dustin/go-humanize ? (like which files need to be patched)

**Comment by titilambert** [comment]
Found it !
```{{ index .Fields "used_percent" | printf "%.2f" }}```
Look here for more info: https://golang.org/pkg/text/template/
