### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mspiegle** [influxdata/kapacitor#304]
Full details of your operating system (or distribution) e.g. 64-bit Ubuntu 14.04:
- Fedora 23 / 4.3.3-301.fc23.x86_64

The version of Kapacitor you are running:
- kapacitor-0.10.1-1.x86_64

Whether you installed it using a pre-built package, or built it from source:
- From RPM

A small test case, if applicable, that demonstrates the issues:
- I don't yet have a small test case yet.  More explanation below

I am using logstash's influxdb output plugin to push metrics at Kapacitor.  This seemed to work fine for 15 minutes, then it crashed.  The rate of incoming metrics was probably on the order of 50/s.  The logs from the panic are in the gist:

https://gist.github.com/mspiegle/7848b56da50c7d38df72

**Comment by nathanielc** [comment]
@mspiegle The panic is because an influxdb cluster has not been configured but a request to record the results of an InfluxDB query was issued. I have a fix coming that will return an error instead of panicing, but you should be able to get it working by configuring an InfluxDB instance.
