### ISSUE TITLE
Replaying AlertNode/log handler has failed in Windows environment

### ISSUE THREAD

**Issue by ritalin** [influxdata/kapacitor#312]
Hi.

TICK script:
```
stream
    .from().measurement('cpu')
    .alert()
        .crit(lambda: "usage_idle" < 70)
        .log('D:/www/influxdb/alerts.txt')
```

I had tried to execute replay command with this script.
But received error message: **task start: alert log path must be absolute: alerts.txt is not absolute**

This issue is guessed involving from [golang/go#1483 ](https://github.com/golang/go/issues/1483).

From that issue, t may be resolved replacing *path.IsAbs()* to *filepath.IsAbs()*.

Best regards.

**Comment by nathanielc** [comment]
@ritalin You are correct thanks. I'll get that fixed.
