### ISSUE TITLE
Tags are empty.

### ISSUE THREAD

**Issue by gregoryb** [influxdata/kapacitor#314]
I'm using Telegraf to send CPU values to InfluxDB.
I adapted the Basic Exemple fromthe Readme and when i use window(), I'm no able to access to the "Tags" map when i try to customize the alert. .Tags is empty.

**Comment by rossmcdonald** [comment]
@gregoryb Can you provide a TICK script that reproduces this issue?

**Comment by gregoryb** [comment]
You can close finally :) I fix it. It's just a missmatch between " and ' in the groupBy clause.

**Comment by rossmcdonald** [comment]
@gregoryb No worries. Thanks for letting us know!
