### ISSUE TITLE
proposal for alert to Pushover.net service

### ISSUE THREAD

**Issue by abarban** [influxdata/kapacitor#322]
to support email and other messaging systems, it might be interesting to add the ability to access alert Pushover (pushover.net) that allow you to have push notifications on Android, iOS, Desktop with multiple possibilities

**Comment by nathanielc** [comment]
@abarban Adding a new alert handler is relatively simple and has been done many times, before see these PRs #139 #160

**Comment by desa** [comment]
Implemented by https://github.com/influxdata/kapacitor/pull/1162
