### ISSUE TITLE
Enable window node to window based on count in addition  to time.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#327]
Something as simple as:

``` javascript
...
    .window()
        .period(10s)
        .every(10s)
// vs
    .window()
        .period(10)
        .every(10)
```

Where the first window uses time since durations were passed and the second uses counts since ints were passed.

I like the simplicity, but it might make it easy for a typo to mess up a script in a significant way.

**Comment by yosiat** [comment]
@nathanielc  can you explain? will it support both?

**Comment by nathanielc** [comment]
Yes, the window node will support both.

**Comment by nathanielc** [comment]
The proposed change is that if you pass ints to the window node it will count points for windowing instead of checking their times.
