### ISSUE TITLE
Is kapacitor thread safe?

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#329]
Hi,

Currently I am inserting to Kapacitor from one thread with bulk size of 3000.

Is it safe to insert from multiple threads? (safe = concurrency & ordering of events) ?

**Comment by nathanielc** [comment]
It is safe to insert into Kapacitor from multiple endpoints. Kapacitor makes two assumptions about the data being inserted.

1. All data for a measurement comes from a single source.
2. The data is already ordered in time for each measurement. Note different measurements can be out of order from each other. Only within a measurement must the data be ordered.

**Comment by yosiat** [comment]
thanks!

**Comment by vittorfp** [comment]
Hello @yosiat and @nathanielc !
Have you figured out if  "measurement" means measurement + tags?
Thanksssssssss
