### ISSUE TITLE
OK dispatched from different host than alert was

### ISSUE THREAD

**Issue by jpohjolainen** [influxdata/kapacitor#330]
Hi,

I have the simple cpu_alert (with added html email setting) set and when I stress one server, I get critical alert correctly but at the same time I also receive OK message from another host. If I keep stressing one server enough, I get loop of  CRITICAL and OK messages originating from same 2 different hosts. 

Here's the tick:
```
stream
  .from().measurement('cpu')
    .where(lambda: "cpu" == 'cpu-total')
  .alert()
    .id('{{ index .Tags "host" }}')
    .message('{{ .TaskName }} on {{ .ID }} is {{ .Level }}')
    .details('''
<h1>{{ .ID }}</h1>
<b>CPU idle</b> is {{ index .Fields "usage_idle" }}%
''')
    .warn(lambda: "usage_idle" < 30)
    .crit(lambda: "usage_idle" < 10)
    .email()
```

**Comment by nathanielc** [comment]
Alerts are computed by each `group` in the data. Since you are not grouping the data Kapacitor has defaulted to assuming all data is in the same group.

Since you have a tag `host` then use this as the groupBy dimension and then alerts will be computed by host.

```javascript
stream
  .from().measurement('cpu')
    .where(lambda: "cpu" == 'cpu-total')
    // Group the data by host tag.
    .groupBy('host')
  .alert()
    .id('{{ index .Tags "host" }}')
    .message('{{ .TaskName }} on {{ .ID }} is {{ .Level }}')
    .details('''
<h1>{{ .ID }}</h1>
<b>CPU idle</b> is {{ index .Fields "usage_idle" }}%
''')
    .warn(lambda: "usage_idle" < 30)
    .crit(lambda: "usage_idle" < 10)
    .email()
```

**Comment by jpohjolainen** [comment]
I thought something like that was missing, but I relied that kapacitor would keep state of alerts itself. 
Thank you!
