### ISSUE TITLE
Disable "stateChangesOnly"

### ISSUE THREAD

**Issue by jroda** [influxdata/kapacitor#332]
Hi, 

I would know if is possible o dissable the method "stateChangesOnly" or will be possible in the future.

Thanks and best regards, Javier

**Comment by nathanielc** [comment]
@jroda `stateChangesOnly` is not on by default unless you have globally configured a an alert handler. Is that the case? If so which one?

**Comment by jroda** [comment]
Yes, that was the problem. Thanks so much for fast answer @nathanielc .
