### ISSUE TITLE
Add the ability to active all tick scripts with one command

### ISSUE THREAD

**Issue by panda87** [influxdata/kapacitor#337]
I see this feature very useful when using Kapacitor in docker containers, when the run command will active all TICK's at one single command, instead of follow one after one.

**Comment by OrangeTux** [comment]
Maybe a solution to enable/disable TICK scripts using glob style pattern matching?

I often prefix the names of my TICK scripts like this:

```
frontend_memory
frontend_deadman
backend_mysql
```

If i want to enable all scripts I could use `kapacitor enable *`, but if I only want to enable scripts for frontend I could use `kapacitor enable frontend_*`.

**Comment by nathanielc** [comment]
I like the idea of glob syntax. This would not be to hard to add, PRs welcome.

**Comment by yosiat** [comment]
@nathanielc I can implement this.. Where do we want to happen?

- Client will send to the server - enable/frontend_* 
- Client will fetch all tasks and call enable per task?

**Comment by nathanielc** [comment]
@yosiat I think having the server implement the glob logic is the right place. Thanks!

**Comment by yosiat** [comment]
@nathanielc I will do this, I think we should enable this feature for disable and reload as well.

**Comment by nathanielc** [comment]
Agreed lets make the change consistent.

**Comment by yosiat** [comment]
@nathanielc This is harder than I thought.
I can write this code with lots of duplicated, but I decided to add "FindTasks(predicate func(string)bool) []rawTasks" so methods like:
- GetTasksInfo
- Enable
- Disable

will use them.. I will send PR once it will be finished.

**Comment by yosiat** [comment]
@nathanielc I started to implement this and found it difficult, there two ways to implement this, and please tell me what you prefer:

Implement a function that will get a predicate with the task name and will return an array of rawTask, it will fetch the boltdb and will return all the matching tasks, we can use this in:
 - GetTasksInfo - to filter by the given array of tasks (?tasks=...)
 - Enable/Disable - the predicate will be global function
The downside of this will be - we are accessing twice the boltdb - one to fetch the list of tasks and then to enable them/disable them.

The other option will be less DRY, and will be to filter in each boltdb acess before enabling/disbeling.

**Comment by nathanielc** [comment]
@yosiat The task_store has been implemented with simplicity in mind not performance. As a result the predicate function sounds better. Even with 1000 tasks the slow down should not even be noticeable and its a low throughput action.

**Comment by yosiat** [comment]
@nathanielc agreed, I will send PR in the weekend. sorry for the delay!

**Comment by framiere** [comment]
Shouldn't this issue be closed since #381 is merged ?

**Comment by yosiat** [comment]
This is upon @nathanielc  decision, he might not close this because 0.12 isn't released yet
