### ISSUE TITLE
Real time alerting on two different streams

### ISSUE THREAD

**Issue by AlexGrs** [influxdata/kapacitor#339]
I have on metric called c_test_status on my influx. Each metrics have a `status` tag which can either be `success` or `failed` and a `test_id` tag.

What I need : I want to raise an alert when the success rate over the last 5 minutes for a group of test_id is less than 90%. 

Example: test_id 18, 19 and 20 have 70% success rate over the last 5 minutes.

Unfortunately, I'm not able to find the solution. Here is a simple version I tried without trying to group by test_id. Even this is not ok :

```
var success_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'success')
        .window()
            .period(5m)
            .every(30s)
        .mapReduce(influxql.sum('value'))

var failed_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'failed')
        .window()
            .period(5m)
            .every(30s)
        .mapReduce(influxql.sum('value'))

success_stream.join(failed_stream)
        .as('success_stream', 'failed_stream')
        .alert()
        .crit(lambda: ((100.0 * "success_stream.sum") / ("success_stream.sum" + "failed_stream.sum")) < 90.0)
        .log('/tmp/stream.log')
        .slack()
```

Any idea what's going on there ?

**Comment by nathanielc** [comment]
@AlexGrs Looks like you are on track, just a few question to clarify:

* What is the value of `value`? Why are you summing vs counting?
* The crit expression looks like it has a typo, should it be: 
`lambda: (100.0 * ("success_stream.sum") / ("success_stream.sum" + "failed_stream.sum")) < 90.0`
* Finally you should add a `.tolerance(30s)` to the join node since its is possible that the two streams vary in time. Since you are emitting windows every 30s a tolerance of 30s will ensure they always match up.

**Comment by AlexGrs** [comment]
Hi !

Right now value is always one. So I changed my definition by changing sum to count. I fixed the lambda expression with the one you provided (thanks for the typo correction). I also changed the crit condition to try to trigger the alert and check it works : 
```
var success_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'success')
        .window()
            .period(5m)
            .every(30s)
        .mapReduce(influxql.count('value'))

var failed_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'failed')
        .window()
            .period(5m)
            .every(30s)
        .mapReduce(influxql.count('value'))

success_stream.join(failed_stream)
        .as('success_stream', 'failed_stream')
	.tolerance(30s)
        .alert()
        .crit(lambda: (100.0 * ("success_stream.sum") / ("success_stream.sum" + "failed_stream.sum")) > 10.0)
        .log('/tmp/stream.log')
        .slack()
```

Is there a possibility to follow during tests the value of the mapReduce and of the expression evaluated for the alert ? 

It has been 10 minutes the alert was modified and I still don't see any alerts in my slack channel :cry:

**Comment by nathanielc** [comment]
Here are some helpful debugging steps for TICKscripts:

* Record a static data set so you don't have to wait periods of time to see if your changes work. Just change the TICKscript and replay.
* Break the task into smaller pieces. For example to see what the result of the mapReduce operations where you can add an alert node with a always true condidtion and log the result
```
success_stream.alert().crit(lambda: TRUE).log('/tmp/failed.log')
failed_stream.alert().crit(lambda: TRUE).log('/tmp/failed.log')
```
That is not ideal, we should probably add an explicit logging node for exactly this purpose, but for now the alert trick works.
* Watch the flow of data using the `kapacitor show` command is it can show you where data gets *stuck* in the pipeline.

Also note the v0.11 has more detailed stats for the `show` output for more in depth understanding of the data flow. v0.11.0-rc1 was released a few minutes ago ;)

As for this specific task can you post the output of the `show` command?

**Comment by AlexGrs** [comment]
hey. 

Here is the output of the show command:

```
Name: stream_error
Error:
Type: stream
Enabled: true
Executing: true
Databases Retention Policies: ["database"."default"]
TICKscript:
var success_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'success')
        .window()
            .period(5m)
            .every(30s)
        .mapReduce(influxql.count('value'))

var failed_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'failed')
        .window()
            .period(5m)
            .every(30s)
        .mapReduce(influxql.count('value'))

success_stream.join(failed_stream)
        .as('success_stream', 'failed_stream')
	.tolerance(30s)
        .alert()
	.id('kapacitor/{{ .TaskName }}/{{ index .Tags }}/{{.Name}}')
	.message('{{ .ID }} is {{ .Level}} value: {{ index .Fields }}')
        .crit(lambda: (100.0 * ("success_stream.count") / ("success_stream.count" + "failed_stream.count")) > 10.0)
        .log('/tmp/stream.log')
        .slack()



DOT:
digraph stream_error {
stream0 -> stream5 [label="705"];
stream0 -> stream1 [label="705"];
stream5 -> window6 [label="17"];
window6 -> map7 [label="13"];
map7 -> reduce8 [label="13"];
reduce8 -> join10 [label="13"];
stream1 -> window2 [label="124"];
window2 -> map3 [label="13"];
map3 -> reduce4 [label="13"];
reduce4 -> join10 [label="13"];
join10 -> alert11 [label="11"];
}
```

**Comment by nathanielc** [comment]
Thanks,

so this line `join10 -> alert11 [label="11"];` tells us that the alert node has received 11 data points. If you do not see any alerts in the log then none of those 11 data points matched the criteria. Try adding an `OR TRUE` to the crit expression so that all points trigger an alert. The alert data in the log will contain the values of the fields so you can figure out why the expression is not working.

**Comment by AlexGrs** [comment]
Hm... This is strange. Each time I delete the task and redefine it, I the three alerts I defined in my tick (the two debug alerts and the good one):
![image](https://cloud.githubusercontent.com/assets/12913892/13818887/ef951b4a-eb97-11e5-91ae-11595bb68eb5.png)

But after this, nothing happens. At least I should get the DEBUG point where `lambda: TRUE``

Output of show:

```
digraph stream_error {
stream0 -> stream5 [label="533"];
stream0 -> stream1 [label="533"];
stream5 -> window6 [label="14"];
window6 -> map7 [label="9"];
map7 -> reduce8 [label="9"];
reduce8 -> alert10 [label="9"];
reduce8 -> join12 [label="9"];
stream1 -> window2 [label="93"];
window2 -> map3 [label="10"];
map3 -> reduce4 [label="10"];
reduce4 -> join12 [label="10"];
reduce4 -> alert9 [label="10"];
join12 -> alert13 [label="8"];
}```

**Comment by nathanielc** [comment]
Have you configured slack or any other alert handler globally? This carries the side effect of setting stateChangesOnly on all alerts. (Should probably change that ;) 

My guess is that since you now have `lambda: TRUE` you get the first alert but it never changes so you don't get any slack alerts for new points.

Also you might want to add `.groupBy('test_id')` after your where clauses now so that each test is treated separately.

**Comment by AlexGrs** [comment]
You were right. I configured slack notification with `global=true` :scream: I changed it and now I receive all debug alerts. But nothing regarding my 'real' alert with the expression percentage computed.

For your info, I upgrade into 0.11RC, here is the output of show command:

```
var success_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'success')
        .window()
            .period(5m)
            .every(30s)
        .count('value')

var failed_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'failed')
        .window()
            .period(5m)
            .every(30s)
        .count('value')

success_stream.alert().message('SUCCESS {{ .ID }} is {{ .Level}} value: {{ index .Fields }}').crit(lambda: TRUE).log('/tmp/failed.log').slack()
failed_stream.alert().message('FAILED {{ .ID }} is {{ .Level}} value: {{ index .Fields }}').crit(lambda: TRUE).log('/tmp/failed.log').slack()

success_stream.join(failed_stream)
        .as('success_stream', 'failed_stream')
	.tolerance(30s)
        .alert()
	.id('kapacitor/{{ .TaskName }}/{{ index .Tags }}/{{.Name}}')
	.message('{{ .ID }} is {{ .Level}} value: {{ index .Fields }}')
        .crit(lambda: (100.0 * ("success_stream.count") / ("success_stream.count" + "failed_stream.count")) > 10.0 )
        .log('/tmp/stream.log')
        .slack()



DOT:
digraph stream_error {
graph [throughput="0.00 points/s"];

srcstream0 [avg_exec_time_ns="0" ];
srcstream0 -> stream4 [processed="234"];
srcstream0 -> stream1 [processed="234"];

stream4 [avg_exec_time_ns="48.693µs" ];
stream4 -> window5 [processed="7"];

window5 [avg_exec_time_ns="73.026µs" ];
window5 -> count6 [processed="2"];

count6 [avg_exec_time_ns="0" ];
count6 -> alert8 [processed="2"];
count6 -> join10 [processed="2"];

alert8 [alerts_triggered="2" avg_exec_time_ns="557.241748ms" ];

stream1 [avg_exec_time_ns="3.374µs" ];
stream1 -> window2 [processed="38"];

window2 [avg_exec_time_ns="19.918µs" ];
window2 -> count3 [processed="3"];

count3 [avg_exec_time_ns="0" ];
count3 -> join10 [processed="3"];
count3 -> alert7 [processed="3"];

join10 [avg_exec_time_ns="67.441µs" ];
join10 -> alert11 [processed="0"];

alert11 [alerts_triggered="0" avg_exec_time_ns="0" ];

alert7 [alerts_triggered="3" avg_exec_time_ns="0" ];
}```

I think my expression tried to be evaluated but I can see this kind of messages in the logs:
```[stream_error:alert11] 2016/03/16 16:33:20 E! error evaluating expression: mismatched type to binary operator. got float64 * int64. see bool(), int(), float()
[stream_error:alert11] 2016/03/16 16:34:09 E! error evaluating expression: mismatched type to binary operator. got float64 * int64. see bool(), int(), float()```

I assume this comes from `100.0 * ("success_stream.count")`Should I cast the Int64 (count) in float64 ? Is there a special way to do that ?

**Comment by AlexGrs** [comment]
Sorry, I was not supposed to close the issue :s

**Comment by nathanielc** [comment]
Ah, good catch on the logs. Yes, you need to convert the counts to floats like so:

`(100.0 * float("success_stream.count") / float("success_stream.count" + "failed_stream.count"))`

**Comment by AlexGrs** [comment]
hm. The error is not triggered. I even changed the to `lambda: TRUE` in the crit expression but even with this, I'm not able to get any alerts in my slack or in the logs.

````
var success_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'success').groupBy('test_id')
        .window()
            .period(5m)
            .every(30s)
        .count('value')

var failed_stream = stream.from().measurement('c_test_status')
        .where(lambda: "status" == 'failed').groupBy('test_id')
        .window()
            .period(5m)
            .every(30s)
        .count('value')

success_stream.alert().message('SUCCESS {{ .ID }} is {{ .Level}} value: {{ index .Fields }}').crit(lambda: TRUE).log('/tmp/failed.log')//.slack()
failed_stream.alert().message('FAILED {{ .ID }} is {{ .Level}} value: {{ index .Fields }}').crit(lambda: TRUE).log('/tmp/failed.log')//.slack()

success_stream.join(failed_stream)
        .as('success_stream', 'failed_stream')
	.tolerance(30s)
        .alert()
	.id('kapacitor/{{ .TaskName }}/{{ index .Tags }}/{{.Name}}')
	.message('{{ .ID }} is {{ .Level}} value: {{ index .Fields }}')
        //.crit(lambda: ( (100.0 * float("success_stream.count") / float("success_stream.count" + "failed_stream.count")) > 10.0 ) OR TRUE )
	.crit(lambda: TRUE)
        .log('/tmp/stream.log')
        .slack()



DOT:
digraph stream_error {
graph [throughput="2.00 points/s"];

srcstream0 [avg_exec_time_ns="0" ];
srcstream0 -> stream4 [processed="185"];
srcstream0 -> stream1 [processed="185"];

stream4 [avg_exec_time_ns="4.757µs" ];
stream4 -> window5 [processed="6"];

window5 [avg_exec_time_ns="0" ];
window5 -> count6 [processed="1"];

count6 [avg_exec_time_ns="0" ];
count6 -> alert8 [processed="1"];
count6 -> join10 [processed="1"];

alert8 [alerts_triggered="1" avg_exec_time_ns="0" ];

stream1 [avg_exec_time_ns="33.284µs" ];
stream1 -> window2 [processed="31"];

window2 [avg_exec_time_ns="6.674µs" ];
window2 -> count3 [processed="11"];

count3 [avg_exec_time_ns="0" ];
count3 -> join10 [processed="11"];
count3 -> alert7 [processed="11"];

join10 [avg_exec_time_ns="0" ];
join10 -> alert11 [processed="0"];

alert11 [alerts_triggered="0" avg_exec_time_ns="0" ];

alert7 [alerts_triggered="11" avg_exec_time_ns="0" ];
}
```

Any idea ?

**Comment by nathanielc** [comment]
Notice that no points made it to the alert node this time: `join10 -> alert11 [processed="0"];`

This is because the join is not working right. Thinking about this I think you should change the script a bit so that we can guarantee the join will work.

But first let me explain more about join. Join looks for pairs of points that have the same group in this case test_id and same time within the tolerance. What happens if none of your tests fail? Your failed_stream will be empty and will not emit counts. As a result the join will block waiting for them. (We should probably handle this case better but for now it will just block forever, since it assume every point will have a match)

To avoid this we can use a window that has both successes and failed and count them separately. So instead of having two windows that we count we have one window that we first filter and then count. That way we are always guaranteed to generate pairs of points.


Here is what I mean:

```
var tests = stream.from().measurement('c_test_status')
        .groupBy('test_id')
        .window()
            .period(5m)
            .every(30s)

var success_stream = tests.where(lambda: "status" == 'success').count('value')
var failed_stream = tests.where(lambda: "status" == 'failed').count('value')
....
```

Sorry, I should have caught that earlier. I will think on how I can make it more robust, and handle the case where a point does not have a match, but for  now the restructure should work well. Thanks for your patience in working through all of this.

**Comment by AlexGrs** [comment]
I understand. I did the change but have no alert right now.

If I have no failed tests during the window, I assume the `tests.where(lambda: "status" == 'failed').count('value')`will contain no data at all -> so the join will be locked forever right ?

**Comment by nathanielc** [comment]
Looks like you are right. https://github.com/influxdata/kapacitor/blob/master/where.go#L77 I assumed it would output an empty batch so that the count could produce a 0 count point, but I was wrong. I think I can just remove that line and it will work but I'll need to test other edge cases were an empty batch could cause problems.

**Comment by AlexGrs** [comment]
Sure. I can try the solution if you need it. The product we are building will relies a lot on this feature. Maybe you can add a special parameter to the stream to bypass this empty batch protection ? So users who don't want this behavior can keep the old one. 

The strange thing is when I delete the task. It's like all the join locked due to empty batch were released at once Right now I just received 100 notifications at once.

**Comment by AlexGrs** [comment]
( i may have find a workaround for now : i have only two states in my points: success and failed). So i'm doing a filter on success tag only, and keep all the other point which are equals to success + failed.

As i'll be adding more status in the future, a solution to have the join with empty batch would be much appreciated.

**Comment by nathanielc** [comment]
I am losing my mind today ;)  As per the docs https://docs.influxdata.com/kapacitor/v0.10/tick/join_node/#fill
Fill should do what you want.

**Comment by AlexGrs** [comment]
So I used, .fill() option and manage to get some alerts. My main issue know is to understand when those alerts are fired. Indeed, I asked for a slack notification to receive them but it seems the alerts are triggered with a lot of delay..

For example:
<img width="598" alt="capture d ecran 2016-03-18 a 11 19 16" src="https://cloud.githubusercontent.com/assets/12913892/13875190/bc288718-ecfc-11e5-8801-d7b9792dbf46.png">

The message display .Time value, and i received it at 10h40 UTC time, but the message date is 8h40. So is there really 2 hours of delay for the alert ?

**Comment by AlexGrs** [comment]
Linked to #361

**Comment by AlexGrs** [comment]
Solved with last nightly and now using batch stream.
