### ISSUE TITLE
docker build of v0.10.1 fails

### ISSUE THREAD

**Issue by jonseymour** [influxdata/kapacitor#346]
I wanted to run the docker build of the v0.10.1 tag (with build.sh) but it is failing because the tip of master of influxdb/influxdb is no longer compatible. I worked around the issue by cherry-picking the first vendoring change in master onto a branch of v0.10.1 and running the build with that.

I can make the branch available to others if they would like it or will submit a pull request against a 0.10.0 maintenance branch if one is created.

**Comment by jonseymour** [comment]
The branch is here - https://github.com/jonseymour/kapacitor/tree/jss-346-0.10.1

**Comment by nathanielc** [comment]
@jonseymour Thanks, I'll create a v0.10 maintenance branch

**Comment by jonseymour** [comment]
Closed via #353
