### ISSUE TITLE
applyEnvOverrides fails to override array elements

### ISSUE THREAD

**Issue by jonseymour** [influxdata/kapacitor#348]
The following environment override:

```
KAPACITOR_INFLUXDB_URLS_0=http://influx:8086 kapacitord config
```

doesn't have the expected effect.

An attempt is made to ecursively apply overrides to array/slice elements, but the attempt fails because the recursive call returns early because the reflect.Value being operated on by the recursive call is not a struct.

**Comment by offlinehacker** [comment]
I guess the same error applies also to influxdb: https://github.com/influxdata/influxdb/blob/master/cmd/influxd/run/config.go

**Comment by jonseymour** [comment]
Yes, it would. I am happy to cross-port the fix back to influx.

**Comment by jonseymour** [comment]
@offlinehacker actually, right now it isn't a problem for influxdb because in the config language, arrays and slices are only ever used at the struct level (e.g. [[udp]]) never at the field level and the overrides do work at the struct level. 

It would be a problem if this ever changed.
