### ISSUE TITLE
[feature-request]: support for running kapacitor inside a docker container

### ISSUE THREAD

**Issue by jonseymour** [influxdata/kapacitor#349]
Unless I am missing some configuration option, it seems that kapacitor and influxdb can't easily be used together if each is deployed into a separate docker container.

The reason is that the UDP subscription ports created by the kapacitor process won't be in a network namespace that is visible to the influxdb process.

Is there an intention to address this issue? What subset of kapacitor functionality is not available if subscriptions are not working for this reason?

**Comment by nathanielc** [comment]
You are correct in that auto creating subscriptions is not docker friendly. The solution is to create the subscriptions your self so that the ports chosen are deterministic. On startup Kapacitor looks for all subscriptions of the name `kapacitor-<clusterID>` and then dynamically listens on the defined ports. If you configure subscriptions externally to Kapacitor it will find them and behave accordingly.  In this way the subscriptions act as another configuration source for Kapacitor.

Kapacitor logs its ClusterID on startup.

**Comment by jonseymour** [comment]
Ah cool - thanks for the info!

**Comment by rca** [comment]
@nathanielc Thanks for the explanation.  While I understand it, I don't yet know enough about Kapacitor and the way it interacts with InfluxDB.  Can you expand on where the subscriptions you mention are stored and how I can go about managing them?  Are these in Kapacitor or InfluxDB?  How can I query them?  How can I create them?  How can I remove them?  etc.

If this is documented somewhere, can you point me in the right direction.

Thank you!

**Comment by nathanielc** [comment]
@rca Here is the docs on subscriptions https://docs.influxdata.com/influxdb/v0.10/query_language/spec/#create-subscription

Basically they are stored in the metadata for a database in InfluxDB. You interact with them via InfluxQL commands.

`SHOW SUBSCRIPTIONS` -- lists existing subscriptions
`CREATE/DROP SUBSCRIPTION ...` -- creates or drops a subscription

More details can be found in the linked docs. Hope that helps!

**Comment by justindowning** [comment]
I have influxdb and kapacitor in their own containers. The secret is to create/use a unique network:
```
docker create -v /data:/data --name datastore ubuntu /bin/true
docker network create TICK
docker run -d --name influxdb -h influxdb \
  --net= TICK -p 8083:8083 -p 8086:8086 \
  -v /data/influxdb:/data/influxdb --volumes-from datastore \
  my-influxdb-container
docker run -d --name kapacitor -h kapacitor \
  --net=TICK -p 9092:9092 \
  -v /data/kapacitor:/var/lib/kapacitor --volumes-from datastore \
  my-kapacitor-container
```

**Comment by jonseymour** [comment]
@justindowning indeed - the realization that I needed this capability led to the need to upgrade my docker version to one that supported networks

**Comment by rca** [comment]
Correct me if I'm wrong, but this assumes InfluxDB and Kapacitor are running on the same Docker host.  The only way I've found to run them on separate hosts is by using Docker's `--net host` option.

Is there a better way?

**Comment by gianarb** [comment]
@justindowning are you sure about your message? is your system working with 2 containers in the same net? because for me seems not.. but I am not really sure about my setup :) 

Thaks

**Comment by justindowning** [comment]
@gianarb yep -- i create a separate network (named TICK) and launch two containers (influxdb, kapacitor) in that network.

**Comment by rca** [comment]
@justindowning are you on a single or multi-server setup?

**Comment by justindowning** [comment]
yes, same docker host
