### ISSUE TITLE
Allow alert.post to send request to authenticated endpoint

### ISSUE THREAD

**Issue by AlexGrs** [influxdata/kapacitor#357]
Hi,

I would like to send post request to an API endpoint with a Basic Http Authentication. Is it supported ?

Regards.

**Comment by nathanielc** [comment]
It is not :(

**Comment by nathanielc** [comment]
But it is not to hard to add PRs welcome.

All that would be required it to update this struct https://github.com/influxdata/kapacitor/blob/master/pipeline/alert.go#L325
and this method  https://github.com/influxdata/kapacitor/blob/master/alert.go#L567

**Comment by fcastello** [comment]
Is this already implemented?

**Comment by SamuelToh** [comment]
@nathanielc I think we should be able to close this one as #117 seem to have resolved this.

**Comment by docmerlin** [comment]
Closed as #117 resolves this.
