### ISSUE TITLE
kapacitor alerta event value (E! failed to send alert data to Alerta: Resource and Event are required to send an alert)

### ISSUE THREAD

**Issue by cryptokush** [influxdata/kapacitor#359]
Alerta integration is broken because I cannot define .event in alerta tickscripts due to the error:
invalid task: No method or property "event" on *pipeline.AlertaHandler

Yet if event is not defined (to satisfy the kapacitor define) you get the error E! failed to send alert data to Alerta: Resource and Event are required to send an alert. once kapacitord tries to talk to alerta.

I have tried to define .id and this is still present.

Presents only on v0.11.0-rc1/2 onwards, Using the dpkg. ubuntu.

**Comment by cryptokush** [comment]
Example failing tickscript without event defined:

TICKscript:
stream
	.from().measurement('checkpoint.temp.currentTemp')
	.groupBy('sensorName')
	.alert()
		.id('{{ index .Tags "host" }}')
		.message('{{ .Level}}: {{ .Name }}/{{ index .Tags "name" }} TEMPERATURE ALERT sensor: {{ index .Tags "sensorName"}} = {{ index .Fields "sensorValue" }}')
			.info(lambda: "sensorValue" > 0)
			.warn(lambda: "sensorValue" > 35)
			.crit(lambda: "sensorValue" > 50)
		.alerta()
		.resource('{{ index .Tags "name" }}')
		.services('{{ index .Tags "customerName" }}')
		.group('Check Point Firewall')
		.value('{{ index .Fields "sensorValue" }}')
		.log('/tmp/cp_temperature_threshold.log')

**Comment by satterly** [comment]
@cryptokush From my limited testing it looks like this will fail if the `.resource()` is not set to anything. Are you sure that there is a Tag called `"name"` and that it is non-empty?

@nathanielc Is it possible to define a default? eg. like `{{ index .Tags "name" || "unknown" }}`

**Comment by satterly** [comment]
Fixed by #461
