### ISSUE TITLE
Delay in alerts

### ISSUE THREAD

**Issue by AlexGrs** [influxdata/kapacitor#361]
When using join on stream with low throughput (ie one data point every 2 minutes), the alerts are delayed by 3 minutes.  Ie: I received at 10h32 UTC an alert triggered at 10:29 UTC. (on my screenshot slack hour is in UTC+1)

<img width="528" alt="capture d ecran 2016-03-21 a 11 34 50" src="https://cloud.githubusercontent.com/assets/12913892/13916110/f81ae9d8-ef58-11e5-9b7f-40a87af840d1.png">

Alert definition:

```
var tests = stream.from().measurement('c_test_status')
        .groupBy('test_id')
	.where(lambda: "test_id" == '34')
        .window()
            .period(5m)
            .every(1m)

var success_stream = tests.where(lambda: "status" == 'success').count('value')
var failed_stream = tests.count('value')

success_stream.join(failed_stream)
        .as('success_stream', 'failed_stream')
	.tolerance(1m)
	.fill(0)
        .alert()
	.id('kapacitor/{{ .TaskName }}/{{ index .Tags }}/{{.Name}}')
	.message('{{ .Time }} - {{ .ID }} is {{ .Level}} value: {{ index .Fields }}')
	.crit(lambda: TRUE)
        .slack()
```

Alert show
```
digraph ec {
graph [throughput="0.00 points/s"];

srcstream0 [avg_exec_time_ns="0" ];
srcstream0 -> stream1 [processed="1605"];

stream1 [avg_exec_time_ns="11.266µs" ];
stream1 -> window2 [processed="7"];

window2 [avg_exec_time_ns="12.91µs" ];
window2 -> count5 [processed="6"];
window2 -> where3 [processed="6"];

count5 [avg_exec_time_ns="0" ];
count5 -> join7 [processed="6"];

where3 [avg_exec_time_ns="0" ];
where3 -> count4 [processed="6"];

count4 [avg_exec_time_ns="0" ];
count4 -> join7 [processed="6"];

join7 [avg_exec_time_ns="34.668µs" ];
join7 -> alert8 [processed="5"];

alert8 [alerts_triggered="5" avg_exec_time_ns="0" ];
}
```

**Comment by AlexGrs** [comment]
Is it a normal behavior ? Maybe it could be linked with the way Group By time() are handled by influx ? Right now, it is the only thin which prevent me to deploy a feature.

**Comment by nathanielc** [comment]
@AlexGrs Yes, the delay is normal. The reason is that Kapacitor understands time as data arrives. It doesn't know that more data is not going to arrive for the minute 10:29 until data arrives with a greater time. Since you are sending data every 2m and the Window node is emitting data every 1m to total lag is 3m.

What kind of system is responding to the alert? Is a 3m delay too much for your requirements? If so can you send data to Kapacitor more often?

**Comment by AlexGrs** [comment]
This is what I thought. Sadly I can't send more data to the pipeline as the data is generated by some process we can't really modify. I tried to achieve the same behavior using batch. And I almost manage to have those real time alert even for this kind of low throughtput data.

I can see in real time the count of success and the total count of tests, but i'm not able to join them. 

See #362

**Comment by nathanielc** [comment]
Closing issue as behavior is as expected.
