### ISSUE TITLE
display warning or add big red warning in docs regarding types of quotes

### ISSUE THREAD

**Issue by rubycut** [influxdata/kapacitor#367]
I just spend half hour debugging this, this will never stream anything:

```
var data = stream.from().database('telegram').retentionPolicy('biweekly')
  .measurement('cassandra')
  .where(lambda: "table" == "metrics3")
```
Why?

Because, by mistake, I have double quotes around "metrics3" instead of single quotes. Task will load without problems, no warnign will be displayed, but it will not work.

**Comment by nathanielc** [comment]
@rubycut This is because what you have specified is valid. It means select points where field table is equal to field metrics3. An error should be logged when data is received and no field metrics3 exists.

**Comment by rubycut** [comment]
Ouch, this definitely needs to be documented in big red warning box.

**Comment by nathanielc** [comment]
@rubycut Agreed PRs welcome :) Here is the relevant docs repo https://github.com/influxdata/docs.influxdata.com/tree/master/content/kapacitor/v0.11
