### ISSUE TITLE
Alert node log files unreadable

### ISSUE THREAD

**Issue by gargooza** [influxdata/kapacitor#368]
I am running kapacitor as a service with user/group = kapacitor/kapacitor. Log files generated by alert nodes are unreadable to other users on the system since the log files have 0600 permissions and are owned by the kapacitor user.

Would it be possible to ease up on those restrictive log file permissions (https://github.com/influxdata/kapacitor/blob/7fdc137dc497d50c7ae2d6e2a481031a8b126511/alert.go#L616)? Maybe make an option to configure log file permissions for kapacitord in a `kapacitor.conf` file? I'd like to make them 0644 by default, but I'm sure that's a security concern for others and probably not something to be hardcoded.

**Comment by nathanielc** [comment]
@gargooza A very reasonable request. This should be easy to add.

1. Add a field to the LogHandler struct int64  https://github.com/influxdata/kapacitor/blob/master/pipeline/alert.go#L432
2. Implement using the new field in the handleLog method  https://github.com/influxdata/kapacitor/blob/master/alert.go#L610

PRs welcome

**Comment by yosiat** [comment]
@nathanielc do you want something like this:
```go
alert()
.log('/tmp/alert.log', 0644)
```

If so, does tick script support optional parameters?

I will implement this :)

**Comment by nathanielc** [comment]
I was thinking something more along the lines of,

alert()
   .log('some path')
       .mode(644)

Keeps it consistent with the other handlers

**Comment by nathanielc** [comment]
Closed with #404
