### ISSUE TITLE
When deleting or changing the definition of an alert with join, all existing alert are triggered

### ISSUE THREAD

**Issue by AlexGrs** [influxdata/kapacitor#374]
Hi.

I have an alert with a join (using stream or batch it's the same behavior) :+1: 
If i make a `kapacitor delete tasks` or a `kapacitor define` then it seems that kapacitor closes all pending on-going alerts and so I receive like 100 notifications at the same time.

I was expecting that, using a delete or define to modify an alerts definition, it would flush the alert pipeline instead of processing all existing one. 

Is it a wanted behavior ?

**Comment by nathanielc** [comment]
@AlexGrs When a task is `closed` which happens on disable or delete, all data in the internal buffers is flushed. So in part is expected but it still sounds like something unintended is happening.  Are you getting duplicate alerts? Are alerts arriving really delayed, as if the buffers are extremely full? I know we have worked and a similar issue already but can you share the output of `kapacitor show` for this task?
