### ISSUE TITLE
Recording not recording...

### ISSUE THREAD

**Issue by SleepyBrett** [influxdata/kapacitor#375]
I'm using Kapacitor version: 0.10.1-1 from the repo "https://repos.influxdata.com/ubuntu trusty stable"

    kapacitor record stream -name cpu_alert -duration 60s

results in this in the kapacitord logs:

    [httpd] 2016/03/23 18:18:50 I! 127.0.0.1 - - [23/Mar/2016:18:18:50 +0000] POST /record?duration=60s&name=cpu_alert&type=stream HTTP/1.1 200 82 - Go-http-client/1.1 b11239f6-f123-11e5-800c-000000000000 761.764µs

However the command never seems to return. It's now 10 minutes later..

     kapacitor list recordings
     ID                                      Type    Size      Created
     48b60266-ceb1-41a5-bda7-198601cd21cd    stream  0 B       23 Mar 16 11:18 PDT

**Comment by nathanielc** [comment]
@SleepyBrett The recording will hang if Kapacitor is not receiving any data. This is because the duration is measured by the increasing timestamps in received data vs real time.

Check that the task `cpu_alert` has a valid DBRP value and that Kapacitor is receiving data for that DBRP.

**Comment by SleepyBrett** [comment]
gotcha, I'll check my connection to influxdb then.

**Comment by SleepyBrett** [comment]
You can go ahead and close this, the only suggestion I might put forward is in general you guys don't explain failures very well.

The actual problem ended up being that the connection to influx wasn't being fully made because I was deploying it into a different pod than influxdb and thus the udp connection wasn't being made.

**Comment by nathanielc** [comment]
@SleepyBrett Agreed, we have an open issue for this specific bug, but in general we need to make it easier to determine if Kapacitor is receiving data for a given DBRP.
