### ISSUE TITLE
Using the kapacitor client, client does not bubble up errors

### ISSUE THREAD

**Issue by SleepyBrett** [influxdata/kapacitor#376]
Kapacitor 0.11.0rc3 (git: master 7fdc137dc497d50c7ae2d6e2a481031a8b126511)

Running commands like define and list tasks result in no error messages and no responses (list tasks returns nothing but a header bar). While troubleshooting I noticed that I had misconfigured the reverse proxy that sits in front of kapacitord and it was returning 502 errors. Kapacitor client didn't bubble up the problem.

**Comment by nathanielc** [comment]
@SleepyBrett Thanks for reporting, we will make sure this issue is fixed via https://github.com/influxdata/kapacitor/issues/386

**Comment by nathanielc** [comment]
Clsoed by #386
