### ISSUE TITLE
Make task store backend pluggable via DAO

### ISSUE THREAD

**Issue by goller** [influxdata/kapacitor#377]
It would be nice to have a backend distributed store like etcd.  Etcd would be nice for environments like kubernetes.

**Comment by nathanielc** [comment]
I like the idea but first we should make the backend pluggable via a DAO or something. Then each new backend can get its own implementation.

**Comment by goller** [comment]
I agree that it should have some sort of interface... here is something I put together many moons ago for a k/v store interface: https://github.com/goller/pkg

**Comment by yosiat** [comment]
@nathanielc I suggest you to look at: https://github.com/docker/libkv
It supports - boltdb, etcd, consul and zookeeper
