### ISSUE TITLE
Kubernetes heapster->influx observed by kapacitor

### ISSUE THREAD

**Issue by SleepyBrett** [influxdata/kapacitor#379]
Kapacitor 0.10.1 (sourced from your ubuntu repo)
Influxdb 0.9.6

After getting kapacitor into a container in a pod with influx and pointing heapster at influx I'm running into problems with record/replay.

As a first test I wrote the following tick (which I don't actually think will work, but we all have to start somewhere):

      var used = stream
		.from()
			.where(lambda: 'container_name' == 'machine')
			.groupBy('hostname')
		.measurement('filesystem/usage_bytes_gauge')

	var limit = stream
		.from()
			.where(lambda: 'container_name' == 'machine')
			.groupBy('hostname')
		.measurement('filesystem/limit_bytes_gauge')

	used
		.join(limit)
		.as('used', 'limit')
		.tolerance(10s)
		.eval(lambda: "used" / "limit")
		.as('percentage_disk_used')
		.alert()
			.crit(lambda: 'percentage_disk_used' > 0.8)
			.slack()

and ran a recording.

Upon trying to play it back I get this:

    $ kapacitor replay -id $rid -name machine_disk_usage -fast
    replay: unable to parse 'log/events,hostname=ip-xxx-xxx-xxx-xxx.us-west-2.compute.internal,pod_id=bb6d2d7d-f214-11e5-bb8d-026630f9b051,pod_name=kube-metrics-d58348fe-caaoe,uid=8b8a7bb4-f216-11e5-bb8d-026630f9b051 value="{': unbalanced quotes

Dumping the series from influx gives me things that look like the following:

                {
                    "name": "filesystem/usage_bytes_gauge",
                    "columns": [
                        "_key",
                        "container_base_image",
                        "container_name",
                        "host_id",
                        "hostname",
                        "labels",
                        "namespace_id",
                        "pod_id",
                        "pod_name",
                        "pod_namespace",
                        "resource_id"
                    ],
                    "values": [
                        [
                            "filesystem/usage_bytes_gauge,container_base_image=nordstrom/confluent-zookeeper:3.4.6,container_name=zk,host_id=i-6e1245a9,hostname=ip-xxx-xxx-xxx-xxx.us-west-2.compute.internal,labels=app:zookeeper\\,server-id:1\\,io.kubernetes.container.hash:5cfc79a0\\,io.kubernetes.container.name:zk\\,io.kubernetes.container.restartCount:0\\,io.kubernetes.container.terminationMessagePath:/dev/termination-log\\,io.kubernetes.pod.name:zookeeper-1-hfjvx\\,io.kubernetes.pod.namespace:default\\,io.kubernetes.pod.terminationGracePeriod:30\\,io.kubernetes.pod.uid:38b2551a-ebd9-11e5-a7ca-025e816a6fed,namespace_id=34d72f1a-ebd8-11e5-a6a0-02ed10092115,pod_id=38b2551a-ebd9-11e5-a7ca-025e816a6fed,pod_name=zookeeper-1-hfjvx,pod_namespace=default,resource_id=/dev/xvda9",
                            "nordstrom/confluent-zookeeper:3.4.6",
                            "zk",
                            "i-6e1245a9",
                            "ip-xxxx-xxx-xxx-xxx.us-west-2.compute.internal",
                            "app:zookeeper,server-id:1,io.kubernetes.container.hash:5cfc79a0,io.kubernetes.container.name:zk,io.kubernetes.container.restartCount:0,io.kubernetes.container.terminationMessagePath:/dev/termination-log,io.kubernetes.pod.name:zookeeper-1-hfjvx,io.kubernetes.pod.namespace:default,io.kubernetes.pod.terminationGracePeriod:30,io.kubernetes.pod.uid:38b2551a-ebd9-11e5-a7ca-025e816a6fed",
                            "34d72f1a-ebd8-11e5-a6a0-02ed10092115",
                            "38b2551a-ebd9-11e5-a7ca-025e816a6fed",
                            "zookeeper-1-hfjvx",
                            "default",
                            "/dev/xvda9"
                        ],
                        ...

Is the problem here just that kubernetes/heapster is applying to many labels to the series name and overflowing something in capacitor?

**Comment by nathanielc** [comment]
Assuming you are using InfluxDB subscriptions to get the data into Kapacitor the protocol being used is UDP. The maximum size of a single UDP packet it 64KB. Its possible that you could reach that max. The example you gave is only about 2KB so it would have to be much larger.

Also Kapacitor uses the same parsing code from InfluxDB so if InfluxDB can parse it so can Kapacitor.

Since you can reproduce the error via a recording, there is a good chance I can reproduce it too. Can you post or send to me directly the replay file you are using? It can be found in `/var/lib/kapacitor/replay/$rid.srpl`
