### ISSUE TITLE
Create official REST API client

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#386]
It is time to start locking down the HTTP REST API. The first step is to write an **official** golang client. We will also update the `kapacitor` command to use this client.

**Comment by upccup** [comment]
@nathanielc   Hi i want to know you plan of add an an official golang client. This task have a timetable yet? :100:

**Comment by nathanielc** [comment]
@upccup WIP PR already at #393

**Comment by upccup** [comment]
@nathanielc is great of https://github.com/influxdata/kapacitor/pull/393 . But there has a question. Can we use object replace TICKscript?

**Comment by upccup** [comment]
@nathanielc is great of https://github.com/influxdata/kapacitor/pull/393 . But there has a question. Can we use object replace TICKscript?

**Comment by nathanielc** [comment]
@upccup If you call the Define method and specify only the name and script parameters then the TICKscript will be replaced.

**Comment by upccup** [comment]
@nathanielc  yes that was great but in this way i can't use the new go client of kapacitor.

**Comment by upccup** [comment]
@nathanielc that's great and . When are you going to merged it?
