### ISSUE TITLE
The kapacitor autometically restarts after 30 seconds while exeuting the tick script

### ISSUE THREAD

**Issue by anand-vardham** [influxdata/kapacitor#392]
I am trying to run a tick script which is used to predict future values. I have written an UDF which uses the ARIMA model for forecasting.
 The tick script is as mentioned below.
 
batch
   .query('''
             select iops, latency, throughput, totalcapacity, usedcapacity from "db1"."rp"."data"
          ''')
   .period(1h)
   .every(1h)
   .groupBy('svm_id','cluster_id','id')
   .arimaForecast()
   .influxDBOut()
        .database('db')
        .measurement(arima_transformed')

 Here each tick script execution there are around 1000 batched for which the UDF : arimaForecast() executes. But the kapacitor restarts after 30s with forecast values
 of 100 batches, also there are no errors in the log file. The log file is as mentioned below.

  [arima_forecast:batch1] 2016/03/30 02:36:34 D! starting next batch query: SELECT iops, latency, throughput, totalcapacity, usedcapacity FROM db1."rp".data WHERE time > '2016-03-30T05:36:34.145191859Z' AND time < '2016-03-30T06:36:34.145191859Z' GROUP BY svm_id, cluster_id, id
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P /usr/lib64/python2.7/site-packages/rpy2-2.7.8-py2.7-linux-x86_64.egg/rpy2/robjects/functions.py:106: UserWarning: Loading required package: forecast
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P   res = super(Function, self).__call__(*new_args, **new_kwargs)
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P /usr/lib64/python2.7/site-packages/rpy2-2.7.8-py2.7-linux-x86_64.egg/rpy2/robjects/functions.py:106: UserWarning: Loading required package: zoo
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P   res = super(Function, self).__call__(*new_args, **new_kwargs)
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P /usr/lib64/python2.7/site-packages/rpy2-2.7.8-py2.7-linux-x86_64.egg/rpy2/robjects/functions.py:106: UserWarning:
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P Attaching package: ‘zoo’
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P   res = super(Function, self).__call__(*new_args, **new_kwargs)
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P /usr/lib64/python2.7/site-packages/rpy2-2.7.8-py2.7-linux-x86_64.egg/rpy2/robjects/functions.py:106: UserWarning: The following objects are masked from ‘package:base’:
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P     as.Date, as.Date.numeric
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P   res = super(Function, self).__call__(*new_args, **new_kwargs)
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P /usr/lib64/python2.7/site-packages/rpy2-2.7.8-py2.7-linux-x86_64.egg/rpy2/robjects/functions.py:106: UserWarning: Loading required package: timeDate
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:42 I!P   res = super(Function, self).__call__(*new_args, **new_kwargs)
[arima_forecast:arimaForecast2] 2016/03/30 02:36:43 I!P /usr/lib64/python2.7/site-packages/rpy2-2.7.8-py2.7-linux-x86_64.egg/rpy2/robjects/functions.py:106: UserWarning: This is forecast 6.2
[arima_forecast:arimaForecast2] 2016/03/30 02:36:43 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:43 I!P
[arima_forecast:arimaForecast2] 2016/03/30 02:36:43 I!P   res = super(Function, self).__call__(*new_args, **new_kwargs)
[run] 2016/03/30 02:37:11 I! Kapacitor starting, version 0.10.1, branch master, commit 22b917b4722addf9ff604d16fa01a09431641c55
[run] 2016/03/30 02:37:11 I! Go version go1.5.3, GOMAXPROCS set to 1
[srv] 2016/03/30 02:37:11 I! Kapacitor hostname: localhost
[task_master] 2016/03/30 02:37:11 I! opened
[srv] 2016/03/30 02:37:11 I! ClusterID: 5617446b-4a47-4cfc-aab2-c224a308f89e ServerID: ab0b670f-3be0-4018-9cf2-a8d38f7f97ed
[srv] 2016/03/30 02:37:11 D! opening service: *udf.Service
[udf] 2016/03/30 02:37:11 D! loaded UDF "pyavg"
[udf] 2016/03/30 02:37:11 D! loaded UDF "arimaForecast"
[srv] 2016/03/30 02:37:11 D! opened service: *udf.Service
[srv] 2016/03/30 02:37:11 D! opening service: *deadman.Service
[srv] 2016/03/30 02:37:11 D! opened service: *deadman.Service
[srv] 2016/03/30 02:37:11 D! opening service: *httpd.Service
[httpd] 2016/03/30 02:37:11 I! Starting HTTP service
[httpd] 2016/03/30 02:37:11 I! Authentication enabled: false
[httpd] 2016/03/30 02:37:11 I! Listening on HTTP: [::]:9092
[srv] 2016/03/30 02:37:11 D! opened service: *httpd.Service
[srv] 2016/03/30 02:37:11 D! opening service: *influxdb.Service
[influxdb] 2016/03/30 02:37:11 I! linking subscriptions
[udp:joe.default] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:45133
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for joe default
[udp:joe.5mins] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:55286
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for joe 5mins
[udp:janus32.default] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:53171
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for janus32 default
[udp:fireapp32.default] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:47668
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for fireapp32 default
[udp:talon32.5mins] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:43597
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for talon32 5mins
[udp:talon32.default] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:35051
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for talon32 default
[udp:orangeberry32.default] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:38395
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for orangeberry32 default
[udp:orangeberry32.5mins] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:58069
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for orangeberry32 5mins
[udp:_internal.monitor] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:50869
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for _internal monitor
[udp:anu.default] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:38683
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for anu default
[udp:anu.5mins] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:60774
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for anu 5mins
[udp:janus32.5mins] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:41456
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for janus32 5mins
[udp:fireapp32.5mins] 2016/03/30 02:37:11 I! Started listening on UDP: 127.0.0.1:38081
[influxdb] 2016/03/30 02:37:11 I! started UDP listener for fireapp32 5mins
[srv] 2016/03/30 02:37:11 D! opened service: *influxdb.Service
[srv] 2016/03/30 02:37:11 D! opening service: *task_store.Service
[task_store] 2016/03/30 02:37:11 D! starting enabled task on startup arima_forecast
[task_master] 2016/03/30 02:37:11 D! Starting task: arima_forecast
[task_master] 2016/03/30 02:37:11 I! Started task: arima_forecast
[task_master] 2016/03/30 02:37:11 D! digraph arima_forecast {
batch1 -> arimaForecast2;
arimaForecast2 -> influxdb_out3;
}
[task_store] 2016/03/30 02:37:11 D! started task during startup arima_forecast
[srv] 2016/03/30 02:37:11 D! opened service: *task_store.Service
[srv] 2016/03/30 02:37:11 D! opening service: *replay.Service
[srv] 2016/03/30 02:37:11 D! opened service: *replay.Service
[srv] 2016/03/30 02:37:11 D! opening service: *stats.Service
[stats] 2016/03/30 02:37:11 I! opened service
[srv] 2016/03/30 02:37:11 D! opened service: *stats.Service
[srv] 2016/03/30 02:37:11 D! opening service: *reporting.Service
[srv] 2016/03/30 02:37:11 D! opened service: *reporting.Service
[run] 2016/03/30 02:37:11 I! Listening for signals

**Comment by nathanielc** [comment]
@anand-vardham Can you check the STDERR output of the daemon to see if it crashed?

The STDERR can be found in  /var/log/kapacitor.err if you installed via a standard deb or rpm package.

**Comment by anand-vardham** [comment]
Hi

I have installed kapacitor using rpm package. But i am not able to find the file mentioned above in the log directory. The contents in the log directory are as mentioned below. Also is it possible that the kapacitor stops the long running tick script jobs.

[root@localhost log]# pwd
/var/log
[root@localhost log]# ls
aide           conman            dmesg.old       lastlog              messages-20150405.gz  prelink             secure-20151202    vbox
amanda         conman.old        fax             mail                 messages-20150412.gz  quagga              speech-dispatcher  wpa_supplicant.log
anaconda       cron              gdm             maillog              messages-20150420.gz  radius              spooler            wtmp
audit          cron-20150405.gz  glusterfs       maillog-20150405.gz  messages-20151202     rhsm                squid              yum.log
bacula         cron-20150412.gz  grubby          maillog-20150412.gz  ntpstats              sa                  sssd               yum.log-20160224
boot.log       cron-20150420.gz  hp              maillog-20150420.gz  openlmi-install.log   samba               stap-server
btmp           cron-20151202     httpd           maillog-20151202     pcp                   sa-update.log       systemtap.log
btmp-20160309  cups              ipaupgrade.log  mailman              pki                   secure              tallylog
ceph           dirsrv            iptraf-ng       mariadb              pluto                 secure-20150405.gz  tomcat
chrony         dmesg             kapacitor       messages             ppp                   secure-20150422.gz  tuned
[root@localhost log]# cd kapacitor/
[root@localhost kapacitor]# pwd
/var/log/kapacitor
[root@localhost kapacitor]# ls
kapacitor.log  rpy2-2.7.8.tar.gz  udf
[root@localhost kapacitor]#

Thanks a lot for looking into this issue.

**Comment by nathanielc** [comment]
> Also is it possible that the kapacitor stops the long running tick script jobs.

A task will stop if explicitly disabled or it encounters an error. But like your log shows its not the task stopping but rather the whole Kapacitor process. Could you maybe start kapacitor in the foreground to capture the stderr? This command should work:

```sh
sudo -u kapacitor kapacitord -config /etc/kapacitor/kapacitor.conf 
```

**Comment by anand-vardham** [comment]
The snapshot of the kapacitor process log when i run the kapacitor in the foreground is as mentioned below. I have also attached the full log file.
[log.txt](https://github.com/influxdata/kapacitor/files/197143/log.txt)

goroutine 117 [chan receive]:
github.com/influxdata/kapacitor.(*UDFNode).runUDF.func2(0xc82029c2d0, 0xc82001cae0)
        /root/go/src/github.com/influxdata/kapacitor/udf.go:91 +0x2a9
created by github.com/influxdata/kapacitor.(*UDFNode).runUDF
        /root/go/src/github.com/influxdata/kapacitor/udf.go:102 +0x1c3

goroutine 946 [runnable]:
net.runtime_pollWait(0x7f60b5206180, 0x77, 0xc823e24840)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc823de3e90, 0x77, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc823de3e90, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).connect(0xc823de3e30, 0x0, 0x0, 0x7f60b5206e38, 0xc82121dda0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:114 +0x1f6
net.(*netFD).dial(0xc823de3e30, 0x7f60b5205d78, 0x0, 0x7f60b5205d78, 0xc823e1ea50, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/sock_posix.go:137 +0x351
net.socket(0xc43698, 0x3, 0x2, 0x1, 0x0, 0xc823e1ea00, 0x7f60b5205d78, 0x0, 0x7f60b5205d78, 0xc823e1ea50, ...)
        /usr/local/go/src/net/sock_posix.go:89 +0x411
net.internetSocket(0xc43698, 0x3, 0x7f60b5205d78, 0x0, 0x7f60b5205d78, 0xc823e1ea50, 0x0, 0xc800000000, 0x0, 0x1, ...)
        /usr/local/go/src/net/ipsock_posix.go:160 +0x141
net.dialTCP(0xc43698, 0x3, 0x0, 0xc823e1ea50, 0x0, 0xc800000000, 0x0, 0xc823e24830, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:171 +0x11e
net.dialSingle(0xc823e20b80, 0x7f60b5205d10, 0xc823e1ea50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:364 +0x3f5
net.dialSerial.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:336 +0x75
net.dial(0xc43698, 0x3, 0x7f60b5205d10, 0xc823e1ea50, 0xc823bf16a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc823e20b80, 0xc823e24830, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:338 +0x760
net.(*Dialer).Dial(0xc823bf1918, 0xc43698, 0x3, 0xc82121dc47, 0x11, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:232 +0x50f
net.Dial(0xc43698, 0x3, 0xc82121dc47, 0x11, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:186 +0x95
net/http.(*Transport).dial(0xc82007a240, 0xc43698, 0x3, 0xc82121dc47, 0x11, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:501 +0xc4
net/http.(*Transport).dialConn(0xc82007a240, 0x0, 0xc82121dc40, 0x4, 0xc82121dc47, 0x11, 0xc823e0e7e0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc82007a240, 0x0, 0xc82121dc40, 0x4, 0xc82121dc47, 0x11, 0xc823e300c0)
        /usr/local/go/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:551 +0x265
[root@localhost /]#

**Comment by anand-vardham** [comment]
It looks like when the udf batch and the snapshot executes in parrallel the kapacitor process restarts.
The udf logs are as mentioned below.


2016-03-31 04:10:15,154 INFO:root: End Batch
2016-03-31 04:10:15,154 INFO:root: Begin batch
2016-03-31 04:10:15,284 INFO:root: End Batch
2016-03-31 04:10:15,284 INFO:root: Snapshot
2016-03-31 04:10:15,284 INFO:root: Begin batch
2016-03-31 04:10:15,427 INFO:root: Agent finished

**Comment by anand-vardham** [comment]
I have increased the snap shot interval to 10m. The tick script ran for 10mins

**Comment by anand-vardham** [comment]
@nathanielc I there a way to scale the kapacitor horizontally across multiple systems?

**Comment by anand-vardham** [comment]
Is there a way to turn off the snapshot feature?

**Comment by nathanielc** [comment]
@anand-vardham thanks for the details, it is clear what is going on now.

The UDF you have is responding to the Snapshot request with invalid data causing Kapacitor to crash. 

1. We need to fix Kapacitor to log an error instead of crash when it receives invalid data.
2. You can fix the UDF for now and things will continue to work
3. There is no way to turn off the snapshot feature but if the UDF replies with an empty snapshot it is ignored.

You can use this implementation for your UDF to fix the issue:

```python
    def snapshot(self):
        response = udf_pb2.Response()
        response.snapshot.snapshot = ''

        return response

    def restore(self, restore_req):
        response = udf_pb2.Response()
        response.restore.success = False
        response.restore.error = 'not implemented'

        return response
```


>  I there a way to scale the kapacitor horizontally across multiple systems?

This depends on your requirements. If you just need HA its simple enough to setup using a dual write system. If you need to distribute a single task across multiple instances this is not possible.

**Comment by anand-vardham** [comment]
@nathanielc  Thanks a lot the kapacitor script is work for me now. Also i had few question regarding the map reduce in kapacitor which are as mentioned below.
  1. Does the map reduce function runs on the influxdb cluster or the kapacitor 
  2. Is it possible to add new influxql function?
Thanks a gain for your help.

**Comment by nathanielc** [comment]
> Does the map reduce function runs on the influxdb cluster or the kapacitor

On Kapacitor, but Kapacitor  uses the same code as InfluxDB  to ensure consistent results.

> Is it possible to add new influxql function? Thanks a gain for your help.

Yes, what do you have in mind? I don't think we have any docs up on how to do this but I can walk you though it.
