### ISSUE TITLE
Ability to define UDP port for subscribes

### ISSUE THREAD

**Issue by fatihcode** [influxdata/kapacitor#398]
Hi all,

`kapacitord` binds the UDP port itself;

```
[task_master] 2016/04/01 19:43:30 I! opened
[influxdb] 2016/04/01 19:43:30 I! linking subscriptions
[udp:telegraf.default] 2016/04/01 19:43:30 I! Started listening on UDP: [::]:38972
[influxdb] 2016/04/01 19:43:30 I! started UDP listener for telegraf default
[httpd] 2016/04/01 19:43:31 I! Starting HTTP service
[httpd] 2016/04/01 19:43:31 I! Authentication enabled: false
[httpd] 2016/04/01 19:43:31 I! Listening on HTTP: [::]:9092
```

Not knowing that port in advance is challenging (and perhaps problematic) for containers. Is there a way to set that port in advance?

*Kapacitor 0.11.x - linux-amd64*

P.S.: Also `ClusterID` changes on every container. Is there a way to set it?

Thanks

**Comment by nathanielc** [comment]
@fatihcode Kapacitor gets the UDP port from the SUBSCRIPTION information store in InfluxDB. If you setup the subscriptions before hand then Kapacitor will just use those ports. 

> Also ClusterID changes on every container. Is there a way to set it?

The cluster ID is stored along with the local database. (typically in /var/lib/kapacitor) If you are using a container you need to persist that directory. 

See this issue for more details on Kapacitor + Docker 
https://github.com/influxdata/kapacitor/issues/349

**Comment by fatihcode** [comment]
@nathanielc : thanks for the quick reply...

It would be much more easier if Kapacitor allow us to set UDP port. Is there any reason it's not allowed? ( i.e. : not implemented yet, technical difficulties, etc? ) Base on your answer I can spend sometime and try to make a PR.

I will try manual SUBSCRIPTION approach which is not elegance since you need to mount a volume. Maybe I can manipulate `/var/lib/kapacitor/cluster.id` somehow... :-/

**Comment by nathanielc** [comment]
`/var/lib/kapacitor/cluster.id` Is just a text file with the ascii encoded cluster ID and can be written externally if you want.

The manual `SUBSCRIPTION` approach does not require a volume mount, but rather InfluxDB itself becomes the source of record.

**Comment by fatihcode** [comment]
@nathanielc : Kapacitor doesn't work when I create a subscription manually. It throws an error (`subscription already exists`) and exits.

```
2016/04/02 03:07:49 Using configuration at: /kapacitor.conf
[run] 2016/04/02 03:07:49 I! Kapacitor starting, version 0.11.0, branch master, commit 97ac4edb295c9f11b5c428fe5906bc6aa4e0865b
[run] 2016/04/02 03:07:49 I! Go version go1.5.3, GOMAXPROCS set to 1
[srv] 2016/04/02 03:07:49 I! Kapacitor hostname: ...
[srv] 2016/04/02 03:07:49 I! ClusterID: container ServerID: 360b2d2c-b5b1-4d12-a07c-5c7cfc1bf2a0
[task_master] 2016/04/02 03:07:49 I! opened
[influxdb] 2016/04/02 03:07:49 I! linking subscriptions
[udp:telegraf.default] 2016/04/02 03:07:49 I! Started listening on UDP: [::]:58228
[influxdb] 2016/04/02 03:07:49 I! started UDP listener for telegraf default
[udp:telegraf.default] 2016/04/02 03:07:59 I! Service closed
[httpd] 2016/04/02 03:07:59 I! Closed HTTP service
[task_master] 2016/04/02 03:07:59 I! closed
[run] 2016/04/02 03:07:59 E! open server: open service *influxdb.Service: subscription already exists
run: open server: open service *influxdb.Service: subscription already exists
```

**Comment by piniondna** [comment]
I'm at the same point on this problem, but I can't seem to get the configuration to work out...
```
2016/05/10 23:54:29 Using configuration at: /etc/kapacitor/kapacitor.conf
[run] 2016/05/10 23:54:29 I! Kapacitor starting, version 0.12.0, branch master, commit 32d4d1b8f688e2d310f4e9413b3fe6ac3ef73c70
[run] 2016/05/10 23:54:29 I! Go version go1.6, GOMAXPROCS set to 1
[srv] 2016/05/10 23:54:29 I! Kapacitor hostname: kapacitor
[srv] 2016/05/10 23:54:29 I! ClusterID: sensors ServerID: kapacitor
[task_master] 2016/05/10 23:54:29 I! opened
[influxdb] 2016/05/10 23:54:29 I! linking subscriptions
[udp:_internal.monitor] 2016/05/10 23:54:30 I! Started listening on UDP: 172.18.0.9:46661
[influxdb] 2016/05/10 23:54:30 I! started UDP listener for _internal monitor
[udp:sensors.default] 2016/05/10 23:54:30 I! Started listening on UDP: 172.18.0.9:46662
[influxdb] 2016/05/10 23:54:30 I! started UDP listener for sensors default
[udp:_internal.monitor] 2016/05/10 23:54:30 I! Service closed
[udp:sensors.default] 2016/05/10 23:54:30 I! Service closed
[srv] 2016/05/10 23:54:30 E! error closing service *stats.Service: error closing stats service: service not open
[httpd] 2016/05/10 23:54:30 I! Closed HTTP service
[task_master] 2016/05/10 23:54:30 I! closed
[run] 2016/05/10 23:54:30 E! open server: open service *task_store.Service: invalid argument
run: open server: open service *task_store.Service: invalid argument
exited with code 1
```

I'm using docker-compose (v2 syntax) which automatically creates a network for the containers.
The kapacitor host is called `capacitor` and the influxdb host is `influxdb`.
The hostname in the kapacitor.config file is set to `kapacitor`.
The cluster.id file contains `sensors`.
The bind address in the kapacitor.config file is set to `:9094` since I have a kafka service binding to `9092` already.

I've pre-created the subscriptions in influxdb and set the destinations to `udp://kapacitor:46661` and `udp://kapacitor:46662`, and both of these udp ports are exposed in the docker-compose file.

At this point I'm at a lose.
