### ISSUE TITLE
Writing the output message from capacitor over a TCP socket

### ISSUE THREAD

**Issue by AliGouta** [influxdata/kapacitor#405]
The list of services defined in kapacitor.conf does not include a TCP output. Is it planned to have such an output so that we can capture and process the event using some out of the box processing tools ?

**Comment by framiere** [comment]
You can leverage the `post(url)` method on alert nodes.
§ https://docs.influxdata.com/kapacitor/v0.11/nodes/alert_node/#post

**Comment by nathanielc** [comment]
@AliGouta Does the `post` method of the AlertNode suite your needs?

**Comment by AliGouta** [comment]
Yes! Thank you.
