### ISSUE TITLE
Kapacitor Rest API return EOF

### ISSUE THREAD

**Issue by earthnut** [influxdata/kapacitor#413]
@nathanielc 
I am using Kapacitor 0.10.0

There is a batch task and running properly 

**`kapacitor list tasks`**

> process_alert_test_batch_1    batch     true      true      ["collectd"."default"]

However every time I run :
**`kapacitor show process_alert_test_batch_1`**

> Get http://localhost:9092/task?name=process_alert_test_batch_1: EOF

could you help to take a look?

Thanks

**Comment by nathanielc** [comment]
This is a known issue and fixed in 0.10.1 and later
