### ISSUE TITLE
Add types of alerts triggered in dot/execution stats

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#419]
Hi,

Currently the AlertNode exposes alerts_triggered stats, I think it will be nice to add:

- Count by severity: ```{ "info": 129, "warn": 12, "crit" : 0 }```
- Last alert triggered time and it's severity

What do you think? I can submit a PR if you like this idea.

**Comment by nathanielc** [comment]
+1 on stats by severity.

The last alert time feels like overkill as a statistic. What is the use case for last alert time? Do you care about last alert time by group or just overall for the node? Seems related to this request too #388

**Comment by yosiat** [comment]
We have alerts that goes on windows that emits every 2 hour or longer, we would like to see the last severity popped out for this alert.

And yes, we care about the group.. but when I think about it this will be overkill =X

**Comment by yosiat** [comment]
@nathanielc so I can go on and implements stats by severity? this is a simple expvar.Map ?
