### ISSUE TITLE
Kapacitor list tasks formatting breaks with long task names

### ISSUE THREAD

**Issue by lpalm** [influxdata/kapacitor#420]
We have some fairly long task names. This is both for descriptiveness and as a makeshift namespacing system. This causes the formatting to break when listing tasks. Not really important, but it messes up the display and glues the task type to the task name.

`Name                          Type      Enabled   Executing Databases and Retention Policies
SomeIncrediblyLongTaskNameThatAlsoHappensToIncludeNamespacingElementsbatch     false     false     ["database"."default"]`

**Comment by hasit** [comment]
@lpalm,

I think I will be able to fix this. Can you give a little bit more information? What is the command that you are running (e.g. `kapacitor list recordings ...`)?

**Comment by lpalm** [comment]
@hasit , yes I was just running `kapacitor list tasks` with tasks longer than 30 characters.

**Comment by nathanielc** [comment]
@hasit Thanks for volunteering! I actually fixed this a few days ago but forgot to close this ticket, sorry about that.. See https://github.com/influxdata/kapacitor/pull/1018

Feel free to look over my solution if you like, as I just put together a simple fix.

**Comment by hasit** [comment]
@nathanielc oh yes. When I was reading the main.go file, nothing seemed out of place that would make the printing go wrong.
