### ISSUE TITLE
A simple way to make TICKscript 

### ISSUE THREAD

**Issue by upccup** [influxdata/kapacitor#424]
HI, there only  have way to transfer TICKscript  to a Node(object). Is there has a simple way to tansfer object to TICKscript or a simple way to make TICKscript.

**Comment by nathanielc** [comment]
@upccup Do you mean in code? Node objects have a Format method that produces a normalized TICKscript string from a node. See here for an example usage https://github.com/influxdata/kapacitor/blob/master/tick/fmt.go#L9

**Comment by upccup** [comment]
@nathanielc I mean is there has a function like *json.Marshal(v interface{}) ([]byte, error)* to create a object to script

**Comment by nathanielc** [comment]
Yes that's what the Format method does

**Comment by upccup** [comment]
But i don't have a script. I need to make new script

**Comment by nathanielc** [comment]
The previously linked method shows how to use this method
https://github.com/influxdata/kapacitor/blob/master/tick/node.go#L26
