### ISSUE TITLE
[feature request] Add a means to tag recordings

### ISSUE THREAD

**Issue by jonseymour** [influxdata/kapacitor#427]
It would nice to be able to tag recordings with an identifier.

Without a tagging mechanism, it is necessary to devise an external convention or mechanism to associate symbolic names with recording identifiers. It would be nice if Kapacitor provided a standard tagging mechanism that allowed symbolic names to be associated with recording identifiers so that no separate mechanism was required to track these associations.

**Comment by nathanielc** [comment]
@jonseymour I like the idea. There are several ways to go about this.

Some thoughts that come to mind:

* Use internal db to map tags to recording IDs (boltdb is a good choice since it is already being used for tasks)
* Add meta data to the header of each recording file.
* Get rid of the IDs entirely and always provide names to recordings

I like those options in order listed at first glance.

**Comment by jonseymour** [comment]
My working assumption that there would be n:1 mapping between tags and recordings - so each recording could be tagged by many tags. This would be consistent with how both docker and git use tags.

Other tagging systems, however, allow n:m mappings between tags and tagged entities.

One application of this might be to create groups of related recordings. 

On replay, you could do this:

     kapacitor replay --tag tag1

The semantics would be gather all the recordings tagged with tag1 and then replay all of them in parallel. If the recordings are guaranteed to be in timestamp order (not sure that this true, right now), then perhaps a --merge option would deliver them to the processing stream in strict timestamp order.

One application of tagging recordings like this is that you could gather a number of different recordings from different measurements at different times, and then replay them all at once which may have some uses.

**Comment by jonseymour** [comment]
A further extension would allow tags to be specified with tag expressions so that:

   '(include & ^exclude) | alternative'

would match all recordings with tag 'include' that did not have a tag 'exclude' or any recording with the tag 'alternative'

This might be useful for filtering recordings down to a subset.

**Comment by jonseymour** [comment]
@nathanielc would you prefer that I use the same bolt db instance as the task store or a separate instance? Keeping them separate seems reasonable (and easiest) to me, but if there is some reason not to do this, let me know.

**Comment by jonseymour** [comment]
@nathanielc would you prefer that I use the same bolt db instance as the task store or a separate instance? Keeping them separate seems reasonable (and easiest) to me, but if there is some reason not to do this, let me know.

**Comment by jonseymour** [comment]
See #447 for my WIP branch for this work.

**Comment by nathanielc** [comment]
Recordings can now be given their own ID, while not tagging it still solves the most common uses cases.
