### ISSUE TITLE
[feature request] improve support for "missing" fields.

### ISSUE THREAD

**Issue by jonseymour** [influxdata/kapacitor#432]
kapacitor doesn't currently handle "missing" fields gracefully in many circumstances.

for example, the following script fails with:

    `task run: invalid field type: <nil>`

```
var grouped = stream
	|from()
		.database('sampledb')
		.retentionPolicy('default')
		.measurement('sample')
		.groupBy('node')
	|window()
		.align()
		.period(5m)
		.every(5m)
	|shift(-5m)
	|mean('metric4').as('metric4')
```

if the input data contains points with missing 'metric4' fields.

A previous fix (#387) worked around one such problem for eval by suppressing the warning message that was generated.

It would be helpful if lambda expressions could express exclusion of such values, so:

...where(lambda: "metric4" != nil)

It would also be helpful if there was a node that could be used to fill in a default value in cases where this is acceptable resolution for the condition. So:

    |default('metric4', 0)

would default the field 'metric4' to 0 if a point does not otherwise contain a value for 'metric4' or would pass the input value otherwise.

**Comment by jonseymour** [comment]
An assertNotNill('metric1', 'metric4', ... etc) node might be useful for scripts that need to assert they are written with an assumption that the specified fields never contain nil

**Comment by nathanielc** [comment]
@jonseymour I ran into a usecase recently as well were a `default` node would have been useful. I think the `default` node should be able to operate on multiple fields at once similiar to   the `eval` node that can have multiple expressions:

How about?:

```javascript
    |default()
        .set('metric4', 0)
        .set('metric5', 0.0)
        .set('metric6', FALSE)
        // etc
```

**Comment by cnelissen** [comment]
+1

Empty/missing tags are also not handled gracefully. For instance:

```
stream
    |from()
        .database('myDb')
        .measurement('myMeasurement')
        .where(lambda: "sometimesPresentTag" =~ /.*/)
        .groupBy('sometimesPresentTag')
```

Results in an error:

```
E! error while evaluating WHERE expression: name "sometimesPresentTag" is undefined. Names in scope: value1, value2, value3
```
