### ISSUE TITLE
[feature request] support raw TSM files as input sources and output targets

### ISSUE THREAD

**Issue by jonseymour** [influxdata/kapacitor#436]
Due to its highly compressed nature, the influxdb TSM format is an excellent archival format for high frequency time series data that can't reasonably be kept online.

It would make sense if Kapacitor could treat TSM files as both a source and sink of timeseries data. This would allow subsets of high-frequency data to be re-processed using Kapacitor without the expense of fully reloading the entire TSM files into an Influx database (not that such a facility currently exists, anyway!)

**Comment by nathanielc** [comment]
Kapacitor can replay data sets using the record/replay features. The format is not TSM but the end result is the same.
