### ISSUE TITLE
[feature request] Support influx line format as a source and sink of data

### ISSUE THREAD

**Issue by jonseymour** [influxdata/kapacitor#437]
Influx line format is an easily understood, if not highly compressed, interchange format for timeseries data. 

It would be great if Kapacitor supported sources and sinks of influx line format data.

Kapacitor could monitor a directory and ingest any influx line format files it found there.

A Kapacitor output node could write influx line format files to a directory, chopping them up as required as   time &/or byte count limits were exceeded.

**Comment by nathanielc** [comment]
This is essentially what Kapacitor already does with its stream inputs and influxDBOut node.
