### ISSUE TITLE
Kapacitor panic

### ISSUE THREAD

**Issue by datastream** [influxdata/kapacitor#441]
Hi,
    I write a custom udf program, when i test it, I get this panic.
`
panic: interface conversion: udf.isResponse_Message is *udf.Response_Begin, not *udf.Response_Snapshot

goroutine 219 [running]:
panic(0xc07ba0, 0xc8209dc0c0)
        /home/datastream/go/src/runtime/panic.go:464 +0x3e6
github.com/influxdata/kapacitor.(*UDFProcess).Snapshot(0xc8200a84e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdata/kapacitor/udf_process.go:354 +0x1f2
github.com/influxdata/kapacitor.(*UDFNode).snapshot(0xc820601e60, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdata/kapacitor/udf.go:152 +0x45
github.com/influxdata/kapacitor.(*ExecutingTask).Snapshot.func1(0x7f8b98926660, 0xc820601e60, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdata/kapacitor/task.go:488 +0x57
github.com/influxdata/kapacitor.(*ExecutingTask).walk(0xc8202b6870, 0xc8201b6d58, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdata/kapacitor/task.go:120 +0xb6
github.com/influxdata/kapacitor.(*ExecutingTask).Snapshot(0xc8202b6870, 0xc820374c60, 0x0, 0x0)
        /home/datastream/gopackages/src/github.com/influxdata/kapacitor/task.go:487 +0xbe
github.com/influxdata/kapacitor.(*ExecutingTask).runSnapshotter(0xc8202b6870)
        /home/datastream/gopackages/src/github.com/influxdata/kapacitor/task.go:514 +0x20a
created by github.com/influxdata/kapacitor.(*ExecutingTask).start
        /home/datastream/gopackages/src/github.com/influxdata/kapacitor/task.go:206 +0x232
`

it seems readloop()/writeloop() in agent.go may have some race condition.

**Comment by nathanielc** [comment]
@datastream Thanks for the bug report. This has been fixed in #442
