### ISSUE TITLE
[0.12.0]  Template for constructing a meaningful message for the alert.

### ISSUE THREAD

**Issue by haowells** [influxdata/kapacitor#457]
stream
       |from()
           .measurement('cpu')
           .groupBy('service', 'host')
       |alert()
           .id('{{ index .Tags "service" }}/{{ index .Tags "host" }}')
           .message('{{ .ID }} is {{ .Level}} value: {{ index .Fields "value" }}')

I try to get tags value in message template {{ index .Tags "host" }} ,
but the problem is If I did not use "groupBy('service', 'host')" before alert node.  I can not get tags value.

**Comment by nathanielc** [comment]
@haowells Now that you are using `groupBy` is it working?

**Comment by haowells** [comment]
@nathanielc 
yes. using groupBy, can get tag values in this way {{ index .Tags "value"}} 
no groupBy, can not working.
