### ISSUE TITLE
failed to send alert data to Slack:Post <slack url>: dial tcp 54.239.190.40:443: i/o timeout

### ISSUE THREAD

**Issue by codervarun** [influxdata/kapacitor#459]
When ever i tried kapacitopr to post to my slack channel from my personal laptop it is working fine but when i tried to use kapacitor on staging machine , i am getting below error: 
E! failed to send alert data to Slack: Post <slack url>: dial tcp 54.239.190.40:443: i/o timeout

Although , I am able to post to slack using curl post command easily.

I am using kapacitor 0.12.0 version in staging.

**Comment by nathanielc** [comment]
Check that your staging environment has network access to the IP 54.239.190.40 over port 443.

**Comment by codervarun** [comment]
Hi Nathaniel,
We  are using proxy servers in our staging machines for any external calls .
And using those https proxy I can easily make call to slack channel by shooting a curl post request which hot successfully executed .

But when kapacitor tried to make post request it is showing the error which I already mentioned. So, I am not sure why kapacitor calls to slack channel should fail? 
What do you think ,what could be problem here  and if you know alternate way to do that ,please let me know that as well.

Thanks 
Varun

**Comment by codervarun** [comment]
@nathanielc . Any updates ??

**Comment by manojgour** [comment]
I'm facing the same issue:
When I execute curl command to post messages to my slack channel, it works fine (by setting https_proxy). But when I integrate with Kapacitor it won't work and gives the following error:
failed to send alert data to Slack: Post https://hooks.slack.com/services/######/######/####: dial tcp 54.230.196.204:443: i/o timeout

Please let me know if something else is missing here.

**Comment by nathanielc** [comment]
Seems that Kapacitor doesn't support HTTP proxies well. #841 is a feature request to add proxy support for the various alert handlers and external integrations for Kapacitor.

Let's consolidate this issue there.
