### ISSUE TITLE
Convert tests to junit format

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#471]
Hi,

I saw that circleci asks to output the results as junit xml format:
![circleci junit suggestion](https://cloud.githubusercontent.com/assets/306253/14581743/2bc90b62-03fd-11e6-8124-f931a1b87986.png)

I found a nice project for doing this - https://github.com/jstemmer/go-junit-report

@nathanielc what do you think about this? I think I can do this if you want.

**Comment by nathanielc** [comment]
I am not going to do this as it doesn't add value to me, but if someone else finds value in it I'll take a look at the PR.
