### ISSUE TITLE
Redefining a running=true tick results in running=false with no error

### ISSUE THREAD

**Issue by melor** [influxdata/kapacitor#472]
* Kapacitor 0.12.0 / Linux amd64
* When redefining a running=false tick with "kapacitor define", the "executing" state goes to "true" (this is ok)
* When redefining a running=true tick with "kapacitor define", the "executing" state goes to "false" (this is the problem)
* The error message visible in "kapacitor show" output is always empty when this happens
* Workaround: I always run "kapacitor reload <tick>" after redefining a tick

Example session:

```
-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db86feee4290d74826ad9f52f53a383264"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: true

-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db86feee4290d74826ad9f52f53a383264"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: false

-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db86feee4290d74826ad9f52f53a383264"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: true
```

**Comment by nathanielc** [comment]
@melor Could you share the HTTP request logs from Kapacitor when it fails? Thanks

**Comment by melor** [comment]
@nathanielc : I re-ran the commands and grabbed kapacitor logs:

```
-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db01beeb9dbbb541de8d83d3e6e09b2b1d"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: true
-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db01beeb9dbbb541de8d83d3e6e09b2b1d"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: true
-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db01beeb9dbbb541de8d83d3e6e09b2b1d"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: false
-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db01beeb9dbbb541de8d83d3e6e09b2b1d"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: true
-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db01beeb9dbbb541de8d83d3e6e09b2b1d"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: false
-bash-4.3# kapacitor define -name foo -tick foo.tick -dbrp "db01beeb9dbbb541de8d83d3e6e09b2b1d"."default" -type stream; kapacitor show foo | head -5
Name: foo
Error:
Type: stream
Enabled: true
Executing: true
```

[journal.txt](https://github.com/influxdata/kapacitor/files/224289/journal.txt)

**Comment by nathanielc** [comment]
@melor How often does the error happen? I have tested locally 1000+ times with a little stress script and cannot reproduce. It might be a race condition that the error hasn't been written by the time you request the task info. Try this to rule that out...

```
kapacitor define -name foo -tick foo.tick -dbrp "db01beeb9dbbb541de8d83d3e6e09b2b1d"."default" -type stream; sleep 1; kapacitor show foo | head -5
```

I am still digging into the code to see if I can figure out want is going on....

**Comment by melor** [comment]
@nathanielc I was running this manually from command-line with delays also longer than 1 sec. I'll see if I can arrange you access to a test box where this can be easily reproduced.

**Comment by nathanielc** [comment]
@melor I believe I have finally found the source of this bug. Internally an extra call to stop a stopped task was being made. In most cases the second stop request would have been a noop, buf if that stop request was blocked long enough to allow a start request to make it through the the task would be stopped right after starting it. I ran into the issue while working on #577 and fixed it there.

**Comment by melor** [comment]
@nathanielc I verified that v0.13.0 + 59433e312c65da7a61802d2a93fe694e1214a3e6 fixes the problem. Thanks!
