### ISSUE TITLE
support for multiple clusters

### ISSUE THREAD

**Issue by rubycut** [influxdata/kapacitor#489]
All my tick scripts use stream node, I am not using batch at the moment.

Kapacitor recently added support for multiple clusters. 

Documentation explains that one of the properties of batch node is "cluster" property, through which we choose cluster we defined in config.

But what about Stream node, it seems streams are supported only from default cluster?

**Comment by nathanielc** [comment]
@rubycut Stream data is pushed to Kapacitor, so there is no need to define which cluster. If you have multiple clusters and they are all pushing the data to Kapacitor then all of the data is available in a stream task.

**Comment by rubycut** [comment]
@nathanielc , consider following scenario: I have two influxdb servers, one is production, one staging, I watch them both with same kapacitor.

Both servers have _internal database, and I watch same data on both of them, which is pointsWrittenOK in httpd measurement. 

But, I need to distinguish those two influxdb servers when I am making alerts because I expect production writes to be much higher than staging ones.

**Comment by nathanielc** [comment]
@rubycut Unfortunately ATM there is now way via the  line protocol to communicate a source cluster.   But if I remember right the data in the `_internal` database is tagged with the InfluxDB  cluster/server IDs, so you should be able to group by those tags.

**Comment by rubycut** [comment]
That's strange, since kapacitor knows to which cluster it is connecting, each cluster is given name in config file, and this name can be added when use Batch node, I don't understand why it is problem to add same thing for Stream node.

You are right about clusterID tag, so this solves my issue at hand, but generally, I think it is good idea to be able to filter streams based on where we connected.

Also, this cluster name is strange, because all I have are two individual influxdb clusters.

**Comment by nathanielc** [comment]
>That's strange, since kapacitor knows to which cluster it is connecting

In the case of stream Kapacitor is not connecting to any cluster but rather  Kapacitor is listening and the cluster is connecting to it. 

Closing as the proposed solution is to add a tag to the data since that is what tags are for.
