### ISSUE TITLE
Alertnode write two events in log

### ISSUE THREAD

**Issue by jackfrost82** [influxdata/kapacitor#493]
Hi,
I noticed a strange behaviour on alert node: it seems to send non critical events to log.
This is my configuration:

```
stream
    |from()
        .measurement('check_http')
    |alert()
        .id('Application {{ index .Tags "application" }}, instance {{ index .Tags "instance" }} on node {{ index .Tags "fqdn" }}')
        .message('{{ .Time }} - Titolo: {{ index .Tags "application" }} not responding - Messaggio:  {{ index .Tags "application" }} not responding - Layer: {{ index .Tags "layer" }} - Node: {{ index .Tags "fqdn" }} - Instance: {{ index .Tags "instance" }} - Severity: {{ .Level}} - Management Desk: Middleware - CIType: BusinessApplication - CIName: {{ index .Tags "application" }} - CILifeCycle: Managed')
        .crit(lambda: "status" > 0.1)
        .exec('/opt/telegrafScripts/logger.sh')
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')
```
Exec just send via syslog the message.
Both in syslog and in alert.log I found two message: one is correct ( it's the one over the threshold), the second is one of the n-th measurement under the threshold.
Here the two message:

"2016-04-25 21:03:21 +0000 UTC - Titolo: xxxxxxxxxx not responding - Messaggio: xxxxxxxxx not responding - Layer: AW-L5-AS - Node: xxxxxxxxxx - Instance: xxxxxxx - **Severity: CRITICAL **- Management Desk: Middleware - CIType: BusinessApplication - CIName: xxxxxxxxxx - CILifeCycle: Managed"
"2016-04-25 21:03:22 +0000 UTC - Titolo: yyyyyyyyyyy not responding - Messaggio: yyyyyyyy not responding - Layer: AW-L5-AS - Node: yyyyyyyyy- Instance: yyyyyyyy- **Severity: OK **- Management Desk: Middleware - CIType: BusinessApplication - CIName: yyyyyyyyyy - CILifeCycle: Managed"

**Comment by nathanielc** [comment]
@jackfrost82 Based on your `.id` it looks like data is grouped by the `application`, `instance`, and `fqdn` tags. In that case you should add a groupBy statement to your `from` node.

```go
stream
    |from()
        .measurement('check_http')
        .groupBy('application', 'instance', 'fqdn')
    |alert()
        .id('Application {{ index .Tags "application" }}, instance {{ index .Tags "instance" }} on node {{ index .Tags "fqdn" }}')
        .message('{{ .Time }} - Titolo: {{ index .Tags "application" }} not responding - Messaggio:  {{ index .Tags "application" }} not responding - Layer: {{ index .Tags "layer" }} - Node: {{ index .Tags "fqdn" }} - Instance: {{ index .Tags "instance" }} - Severity: {{ .Level}} - Management Desk: Middleware - CIType: BusinessApplication - CIName: {{ index .Tags "application" }} - CILifeCycle: Managed')
        .crit(lambda: "status" > 0.1)
        .exec('/opt/telegrafScripts/logger.sh')
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')
```

**Comment by jackfrost82** [comment]
My fault, thanks
