### ISSUE TITLE
[feature request] - Alerta - Allow service to be a template and allow timeouts

### ISSUE THREAD

**Issue by hrzbrg** [influxdata/kapacitor#494]
Hi,

it would be very helpful, if the service field of an Alerta event would be a template in Kapacitor, so it can be assigned with a user defined value. Usecase is a microservice architecture, where we would be able to set the service in the alert to the actual service that caused it.

Second nice to have feature would be alert timeouts. Alerta lets you define a timeout in seconds for every alert event after which it will be deleted.

Regards
hrzbrg

**Comment by evaryont** [comment]
Is this the same as #1543 and thus fixed now by #1545?

**Comment by nathanielc** [comment]
@evaryont Yes, I'll close this issue, thanks for updating.
