### ISSUE TITLE
Parsing JSON string using TICK script

### ISSUE THREAD

**Issue by bogdanveres** [influxdata/kapacitor#508]
Having the following script:

```
stream
    |from()
        .measurement('DEVICE_1_LIVE')
    |alert()
        .info(lambda: "BoolTestStatus" == 1)
    .details('{{ .Name }}')
        .log('/tmp/teststatus.log')
	.slack()
        .channel('#teamnotifications')
```

This will return the following JSON string:

`{"id":"DEVICE_1_LIVE:nil","message":"DEVICE_1_LIVE:nil is INFO","details":"DEVICE_1_LIVE, DEVICE_1_LIVE_TestMetrics ","time":"2016-05-04T15:21:08Z","level":"INFO","data":{"series":[{"name":"DEVICE_1_LIVE","columns":["time","BoolTestStatus","CurrentTest","Cycle","TestExecutionTime","TestFailed","TestPassed"],"values":[["2016-05-04T15:21:08Z",1,3,1000,180,0,700]]}]}}`

I want to log in "teststatus.log" file a custom message and post a notification on Slack but I don't know how to parse the JSON string using TICK script. 
Is there a way to create the custom message without using other scripting languages?

**Comment by nathanielc** [comment]
Have you seen the `.message` property on the AlertNode https://docs.influxdata.com/kapacitor/v0.12/nodes/alert_node/#message ?

The details property is ignored by the `slack` notification since it is a simple message.

You shouldn't need to parse the JSON in TICKscript itself.

**Comment by bogdanveres** [comment]
@nathanielc thanks. Using the `.message` I was able to generate the correct output. Now I have another problem. The notification contains a link to a Grafana dashboard. Is there a way to add the timestamps to a link?

i.e.

`http://192.168.1.10:3000/dashboard/db/device_1_live?from=1462448901244&to=1462452501244`

My message now:

`.message('Cycle failed. Current cycle {{ index .Fields "Cycle" }}. Total cycles failed: {{ index .Fields "TestFailed" }}.
Cycle failed on device Device_1. <http://192.168.1.10:3000/dashboard/db/device_1_live?from=1462448901244&to=1462452501244|Click here> for details!')
`
I want to know if there is a way to calculate the value of  `from` and `to` using TICK. I found something [here](https://docs.influxdata.com/kapacitor/v0.12/tick/expr/#time-functions) but I don't know if this is what I need. If yes can you post an example? The ideea is that I want to add a link to Grafana to see some hardware metrics when a test fails and I need the timestamps. Thanks again.

**Comment by nathanielc** [comment]
@bogdanveres There isn't a way to do that, but I think it would be useful. I am going to create a new issue to track that and close this one.

**Comment by kamakhyarjun** [comment]
Is it possible to parse a filed which as its value has a nested json string.
for example Field SensorData in my measurement IOTData has a JSON string value save : '{"machine":"sensor1","var":"temp","val":"30"}'. Is there a way to read and parse this JSON string in TICK script and save in a new measurement.
