### ISSUE TITLE
Alert Node: field "message" should be passed as "state_message" to victorops

### ISSUE THREAD

**Issue by egarbi** [influxdata/kapacitor#514]
At this moment "message" field is being passed as "entity_display_name" to vitorops' API. 
The alert could be much more useful if the field "message" is passed as "state_message" instead.
As an example, see what happens if we send an disk alert using current format against my proposed:
Current Format:
<img width="530" alt="screen shot 2016-05-05 at 16 03 25" src="https://cloud.githubusercontent.com/assets/2984201/15047080/0351b278-12db-11e6-94fc-cbd21b68a0b9.png">
Same alert, proposed format:
<img width="533" alt="screen shot 2016-05-05 at 16 03 37" src="https://cloud.githubusercontent.com/assets/2984201/15047084/0e5766a4-12db-11e6-83aa-47c9139a5a23.png">

**Comment by nathanielc** [comment]
@egarbi Do you know how the `ENTITY` field got populated with `disk/server1`? Is that the ID of the alert?

**Comment by egarbi** [comment]
@nathanielc yes it is. ID of the alert will be set as "entity_id" on victorops, and the same will be placed by default on "entity_display_name" if the field is null.
All victorops fields available [here](http://victorops.force.com/knowledgebase/articles/Integration/Alert-Ingestion-API-Documentation/)
