### ISSUE TITLE
Streams Not Working In 0.12

### ISSUE THREAD

**Issue by nhproject** [influxdata/kapacitor#525]
Hi

I have a machine with Kapacitor 0.11, the "old" machine. I have a CPU task there, works great (stream). I also have some other batch ticks which works great too.
I created a new machine with Kapacitor 0.12. I copied all the mentioned tasks to this new machine, changed the syntax to the new one (pipes for chaining, dots for properties) 
All batch tasks works well, the cpu stream task doesn't do anything. Seems it doesn't work.
I also created another test tick file (stream), something much more simple and basic - it still doesn't work.

Any idea?
Thanks,

Nitz

**Comment by nhproject** [comment]
I will also mention that when converting the stream test task to batch, the batch works.

**Comment by nhproject** [comment]
This is the tick file:

`var msg = MSG

var data  = stream
		|from().measurement('cpu').where(lambda: "cpu" == 'cpu-total').truncate(1s)

var past_percentile_50 = data
		// Calculating the 50%ile of used CPU from the last half an hour
		.groupBy(time(30m),'host','node_name','dc','env','domain')
		|window().period(30m).every(30s)
		|percentile('usage_idle',50.0)
		|eval(lambda: 100.0 - "percentile").as('value')
  		// Truncation of the long float to 2 digits after the dot
		|eval(lambda: 100.0 * "value").as('value')
		|eval(lambda: trunc("value") / 100.0).as('value')
		// Shifting the value we got 5 minutes to the future in order to compare
		|shift(5m)

var current_percentile_50 = data
		// Calculating the 50%ile of used CPU from the last 5min
		.groupBy(time(5m),'host','node_name','dc','env','domain')
		|window().period(5m).every(30s)
		|percentile('usage_idle',50.0)
		|eval(lambda: 100.0 - "percentile").as('value')
		// Truncation of the long float to 2 digits after the dot
		|eval(lambda: 100.0 * "value").as('value')
		|eval(lambda: trunc("value") / 100.0).as('value')

var data = past_percentile_50
	|join(current_percentile_50).as('past_percentile_50', 'current_percentile_50')
	|eval(lambda: trunc(((("current_percentile_50.value" - "past_percentile_50.value") / "past_percentile_50.value") * 10000.0)) / 100.0).keep().as('change_percentile_50')

data
	|alert().message(msg)
		.crit(lambda: ...)
		.warn(lambda: ...)
		.info(lambda: ...)
		.stateChangesOnly()
		// Slack Notification
		.slack().channel('#ops_alerts-dev')`

**Comment by rossmcdonald** [comment]
@nhproject Can you show us the output to a `SHOW SUBSCRIPTIONS` run from the InfluxDB server? It sounds like there is something wrong with the subscription forwarding if batches work but streams do not.

**Comment by nhproject** [comment]
<img width="908" alt="screen shot 2016-05-10 at 10 06 22" src="https://cloud.githubusercontent.com/assets/15214994/15138199/f938c212-1696-11e6-87ba-69eeae634733.png">

**Comment by nhproject** [comment]
In the destination written my public IP of the Kapacitor machine with some random UDP port

**Comment by rossmcdonald** [comment]
@nhproject Can you check to see if Kapacitor is listening on the subscription UDP ports? If it's still not working, I'd recommend dropping all of the existing Kapacitor subscriptions and restarting the Kapacitor service.

**Comment by nhproject** [comment]
Closing this issue. Was my fault - wrong IP on config file.
Thanks!!
