### ISSUE TITLE
Improvement: alert timeout

### ISSUE THREAD

**Issue by jdursel** [influxdata/kapacitor#527]
Hi,

For the project I'm working on, I have to send the alert at most once per quarter and if the state hasn't changed, the alert must be thrown again at minute 0,15,30,45.

For the moment, I'm using a join trick to do it. By storing the alert state in an "alert" measurement and resetting it to "0" every 0,15,30,45 min of hour. When an alert is triggered, a "1" is stored into the measurement. The join is then used to check if the alert has already been triggered for the current quarter.
This is not quite elegant. But that's what I managed to find to fit my needs.

I'm quite new to goLang and have some difficulties to understand what can be done or not in the tick scripts. But i'm quite sure that it can be done more efficiently. Perhaps by using local tick script local variable or function (to avoid writing to an alert measurement)? 

But the best solution (from my point of view) would be to add a timeout or cron-timeout argument to the stateChangeOnly() method.

Thanks for reading,
Kr,

The tick script:
[alertFilterJoin.batch.txt](https://github.com/influxdata/kapacitor/files/254723/alertFilterJoin.batch.txt)

**Comment by nathanielc** [comment]
@jdursel  A timeout argument has been added to the `.stateChangesOnly` property that should do what you want.

https://docs.influxdata.com/kapacitor/v0.13/nodes/alert_node/#statechangesonly

**Comment by jdursel** [comment]
Thank you, it will greatly simplify the script :-)
Have a nice day.
