### ISSUE TITLE
Feature Request:  Suppress "data" and "details" from the Alert node log output

### ISSUE THREAD

**Issue by sslupsky** [influxdata/kapacitor#530]
It would be helpful to have an option with the Alert node to suppress the "data" that gets output after the user specified message.

{"id":"P274.c2c1a284","message":"Battery is CRITICAL, value: 3.1897","details":"None","time":"2016-05-06T00:00:00Z","level":"CRITICAL",**"data":{"series":[{"name":"P274.c2c1a284","tags":{"channel":""},"columns":["time","mean"],"values":[["2016-05-06T00:00:00Z",3.1897]]}]}}**

Also, suppression of the "details" would be helpful to minimize clutter as well.

**Comment by nathanielc** [comment]
@sslupsky Suppressing `details` is possible via setting it to the empty string:

```go
|alert()
    .crit(lambda: ...)
    .details('')
```

**Comment by sslupsky** [comment]
Hi, @nathanielc 

Thanks for the quick response!!!

When I set the details property to an empty string, it still outputs the "details" tag in the log, but the value is empty?  Can it be completely suppressed?

{"id":"P274.c2c1a284","message":"Battery is CRITICAL, value: 3.1897",**"details":""**,"time":"2016-05-06T00:00:00Z","level":"CRITICAL","data":{"series":[{"name":"P274.c2c1a284","tags":{"channel":""},"columns":["time","mean"],"values":[["2016-05-06T00:00:00Z",3.1897]]}]}}

**Comment by nathanielc** [comment]
No it cannot be completely suppressed.

**Comment by crashedserver** [comment]
> @sslupsky Suppressing `details` is possible via setting it to the empty string:
> 
> ```go
> |alert()
>     .crit(lambda: ...)
>     .details('')
> ```
> 
> Suppressing `data` is not possible but it is a good feature request.

@nathanielc Any plan to provide this feature? It would be very helpful in getting neat alerts.
