### ISSUE TITLE
invalid log level: ""  

### ISSUE THREAD

**Issue by motilevy** [influxdata/kapacitor#540]
Seems like setting loglevel is broken on 0.13 

> or l in debug info warn error ; do  echo $l ; kapacitor -url http://localhost:9092 level $l ; done
> debug
> invalid log level: ""
> info
> invalid log level: ""
> warn
> invalid log level: ""
> error
> invalid log level: ""
> 

kapacitor version

> Kapacitor 0.13.0 (git: master ce28f6dced073e473b44f592517fa6c4d05b5e65)

**Comment by AlexGrs** [comment]
I have the same issue on kapacitor 0.13
