### ISSUE TITLE
Cannot add tasks anymore since 0.13

### ISSUE THREAD

**Issue by jeroenjacobs1205** [influxdata/kapacitor#541]
kapacitor define -name disk_alert -type "stream" -tick /tmp/disk_alert.tick -dbrp collectd_db.default

results in

    unknown type "unknown TaskType 0"

Works fine in 0.12. Removing quotes around "stream" doesn't make a difference.

**Comment by nathanielc** [comment]
Several CLI command changes with the release ,see the CHANGLOG or the new help message for details. The equivalent command is now:

```sh
kapacitor define  disk_alert -type "stream" -tick /tmp/disk_alert.tick -dbrp collectd_db.default
```
