### ISSUE TITLE
Kapacitor 0.13.0: Alert Names with '/' in them can be created, but can't be updated

### ISSUE THREAD

**Issue by mglazer** [influxdata/kapacitor#544]
I created an alert with a notional name: `login/time`. 

Upon trying to update this alert, or getting it back, I'm blocked.

I've tried:

```
curl 'http://localhost:9092/kapacitor/v1/tasks/login/time?script-format=formatted&dot-view=attributes'
```

```
curl 'http://localhost:9092/kapacitor/v1/tasks/login%2Ftime?script-format=formatted&dot-view=attributes'
```

Curling:

```
http://localhost:9092/kapacitor/v1/tasks
```

Shows the task in the JSON.

**Comment by nathanielc** [comment]
@mglazer See #546 for a fix. Essentially your existing tasks with a `/` will continue to function but new tasks will not be allowed to have the `/` character. If this is a deal breaker lets discuss...

**Comment by mglazer** [comment]
That's fine. I'm not in production yet so throwing away these alerts and recreating is fine.
