### ISSUE TITLE
[feature request] Be able to reference TICK variables in alert message

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/kapacitor#552]
Currently it is not possible to reference TICK script variables in alert messages. For example:

```
var WARN_THRESHOLD = 2
...
    |alert()
        .message('Broke threshold of {{ $WARN_THRESHOLD }}')
...
```

This can be useful for conveying message details that include the value that triggered the alert as well as what threshold/value the alert is firing from.

**Comment by nathanielc** [comment]
Would string concatenation be enough?

Example:

```
var WARN_THRESHOLD = 2
...
    |alert()
        .message('Broke threshold of ' + string(WARN_THRESHOLD))
...
```

**Comment by rossmcdonald** [comment]
@nathanielc Definitely. Really just any way to reference them would be great.

**Comment by nathanielc** [comment]
@rossmcdonald Great, with this PR #577 this should be possible. I'll add a test case to make sure.
