### ISSUE TITLE
Periodically check if new InfluxDB DBRPs have been created

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#553]
Currently Kapacitor only creates subscriptions on startup. We should add both and API endpoint to tell Kapacitor to add update subscriptions as well as optionally do so on a periodic basis.

**Comment by titilambert** [comment]
@nathanielc Are you working on it ? If not, I can get it (I really need this one)

**Comment by nathanielc** [comment]
@titilambert I am not working on this ATM. Thanks for taking a look!

**Comment by titilambert** [comment]
@nathanielc I already got something, I just need more tests before create a PR

**Comment by schmurfy** [comment]
What about the api endpoints, was it added too ? I can't find it in the documentation but it may just not be documented so I prefer to ask directly. If There isn't it would be nice to have a way to tell kapacitor to updates its subscriptions.

**Comment by nathanielc** [comment]
@schmurfy It has been added and was left undocumented.

To trigger an explicit event to update subscriptions make an empty bodied POST request to `/kapacitor/v1/subscriptions`

**Comment by nathanielc** [comment]
@schmurfy I should have also mentioned that as of v1.1.0 which is has an rc2 release out now there is a new API for configuring Kapacitor. Since the API allows adding/removing and modifying InfluxDB clusters in the Kapacitor config it naturally needed to support dynamically linking subscriptions. Depending on why you needed to update them this may be a better option. See the CHANGELOG for more details.

**Comment by schmurfy** [comment]
thakns I will have a look at it, for now this is for testing purposes, I create the influxdb database on the fly and was looking for a way for kapacitor to immediately notice them.
