### ISSUE TITLE
Kapacitor is startup is failling

### ISSUE THREAD

**Issue by AbdulHameedM** [influxdata/kapacitor#556]
Influxdb + Telegraf is working good,any idea?

 Error
[run] 2016/05/18 12:44:56 I! Kapacitor starting, version 0.13.0, branch master, commit ce28f6dced073e473b44f592517fa6c4d05b5e65
[run] 2016/05/18 12:44:56 I! Go version go1.6.2, GOMAXPROCS set to 1
[srv] 2016/05/18 12:44:56 I! Kapacitor hostname: localhost
[srv] 2016/05/18 12:44:56 I! ClusterID: eb59dfe2-3573-4448-a370-2205e95497ec ServerID: 80577e5a-9d3e-4235-bbe2-99487c25f8d8
[task_master] 2016/05/18 12:44:56 I! opened
[influxdb] 2016/05/18 12:44:56 I! linking subscriptions
[srv] 2016/05/18 12:44:56 E! error closing service *stats.Service: error closing stats service: service not open
[httpd] 2016/05/18 12:44:56 I! Closed HTTP service
[task_master] 2016/05/18 12:44:56 I! closed
[run] 2016/05/18 12:44:56 E! open server: open service *influxdb.Service: unable to decode json: received status code 405 err: invalid character 'M' looking for beginning of value

**Comment by rossmcdonald** [comment]
It looks like you're running with an older version of InfluxDB. Kapacitor 0.13 can only be used with InfluxDB 0.13.

**Comment by jsvisa** [comment]
@rossmcdonald thanks, it works.
