### ISSUE TITLE
Getting "mismatched type to binary operator" for int64/int64 or float64/float/64 in 0.13

### ISSUE THREAD

**Issue by mtslzr** [influxdata/kapacitor#561]
Working a script for checking memory usage. We pull total and used (in bytes) from InfluxDB, so I need to generate the percent myself. In 0.12, I was able to do something akin to this, an example of usage being over 50%:

```
.info(lambda: float("used") / float("total") > 0.50)
```

Unfortunatley, since 0.13, damn near any combination of the above (using float or int) results in an error like this:

```
E! error evaluating expression: mismatched type to binary operator. got int64 > int64. see bool(), int(), float()
```

Still learning this, so my gut say it's something silly I'm missing, but I can't seem to figure it out.

And FWIW, I've managed to get similar errors for float64 > float64, int64 / int64 and int64 * int64.

**Comment by nathanielc** [comment]
@mtslzr We significantly changed the implementation of lambda expressions in 0.13 so something like probably messed up somewhere. I'll take a look.

**Comment by nathanielc** [comment]
@mtslzr I can't reproduce this locally, could you share a more complete example where you are getting this error? Thanks.

**Comment by nathanielc** [comment]
@mtslzr I figured it out, and I am chasing down the bug now....

**Comment by yosiat** [comment]
@nathanielc what's the bug? Sounds very weird bug..

**Comment by nathanielc** [comment]
@yosiat  I just posted the PR https://github.com/influxdata/kapacitor/pull/567

Besides some refactoring of the error messages, it boiled down to `isDynamicNode` not checking binary nodes. See https://github.com/influxdata/kapacitor/pull/567/files#diff-9de6492423b4172b3853bd681fd787ae
