### ISSUE TITLE
variables in .TICK script?

### ISSUE THREAD

**Issue by Talbion** [influxdata/kapacitor#565]
Hello,

I've recently setup Influx + Kapacitor (latest) and got the alerts setup and working great.
Now, I'd like to use variables instead of plain-text values (such as the '30' for CRIT).

Is it possible to read variables from a config file, that for example would be located in the ETC folder of the Kapacitor?
Or maybe there's another way to pass variables to TICK files?
(Just as reference, I'm pasting a simple .tick script for cpu measure)

Thanks!
```
stream
    |from()
        .measurement('cpu_value')
    |alert()
        .id('{{ .Name }}@{{ index .Tags "host"}}')
        .message('{{ .ID }} is {{.Level }} measure: {{ index .Fields "value" }}')
        .crit(lambda: "value" > 30 )
        .log('/opt/kapacitor/var/log/kapacitor/alerts.log')
        .slack()
```

**Comment by nathanielc** [comment]
@Talbion Yes, and not yet. You can define vars in a script like this:

```go
var threshold = 30

stream
    |from()
        .measurement('cpu_value')
    |alert()
        .id('{{ .Name }}@{{ index .Tags "host"}}')
        .message('{{ .ID }} is {{.Level }} measure: {{ index .Fields "value" }}')
        .crit(lambda: "value" > threshold )
        .log('/opt/kapacitor/var/log/kapacitor/alerts.log')
        .slack()
```

But currently that is all you can do. I am working on  a change to be able to set those vars dynamically via the API see #259 for more details.

**Comment by nathanielc** [comment]
Closing in favor of #259

**Comment by Talbion** [comment]
OK thanks for the quick response @nathanielc !

-talbion
