### ISSUE TITLE
Kapacitor doesn't seem resubscribe when influxdb restart

### ISSUE THREAD

**Issue by titilambert** [influxdata/kapacitor#576]
Hello,

It seems that Kapacitor doesn't resubscribe if InfluxDB restarts.
How to reproduce:

1. Launch InfluxDB
2. Launch Kapacitor
3. Run `show subscriptions` => You see the Kapacitor subscription
4. Restart InfluxDB
5. Run `show subscriptions` => You DON'T see the Kapacitor subscription

Same behaviour when dropping databases: 

1. Launch InfluxDB
2. Create DB `test`
3. Launch Kapacitor
4. Run `show subscriptions` => You see the Kapacitor subscription
5. Drop DB `test`
6. Create DB `test`
7. Run `show subscriptions` => You DON'T see the Kapacitor subscription on `test` DB

**Comment by nathanielc** [comment]
@titilambert The subscriptions are stored as part of the database meta data like retention policies. Does a restart of InfluxDB cause other data to be lost as well? 

Kapacitor doesn't need to `resubscribe` to InfluxDB for each startup, it creates the subscriptions once and then they should persist. 

As for the second workflow Kapacitor currently does not look for new databases except at startup. See #553

**Comment by titilambert** [comment]
I close this one, it duplicates #553
