### ISSUE TITLE
need better insights into whats going on with tickscripts.

### ISSUE THREAD

**Issue by james-lawrence** [influxdata/kapacitor#583]
been trying to debug a simple tick script using influxdb/telegraf/kapacitor based on the sample code.
```
stream
	|from()
		.database('telegraf')
		.retentionPolicy('default')
		.measurement('cpu')
		.where(lambda: 'usage_idle' > 10)
	|alert()
		.info(lambda: TRUE)
		.log('/tmp/alerts.log')
```

it doesn't perform anything. I have no idea if its the from() section just not generating any data or something wrong with the alert() section.

I know the data is getting to influxdb from this query which outputs a number of records:
```
SELECT * FROM cpu WHERE cpu = 'cpu-total' AND usage_idle > 10 LIMIT 10
```

What would be nice is a way to dump the results of a node to kapacitord's log/stderr ala:
|debugDump()

**Comment by nathanielc** [comment]
Try, `|log()`

On Fri, May 27, 2016, 6:54 PM James <notifications@github.com> wrote:

> been trying to debug a simple tick script using
> influxdb/telegraf/kapacitor based on the sample code.
>
> stream
>     |from()
>         .database('telegraf')
>         .retentionPolicy('default')
>         .measurement('cpu')
>         .where(lambda: 'usage_idle' > 10)
>     |alert()
>         .info(lambda: TRUE)
>         .log('/tmp/alerts.log')
>
> it doesn't perform anything. I have no idea if its the from() section just
> not generating any data or something wrong with the alert() section.
>
> I know the data is getting to influxdb from this query which outputs a
> number of records:
>
> SELECT * FROM cpu WHERE cpu = 'cpu-total' AND usage_idle > 10 LIMIT 10
>
> What would be nice is a way to dump the results of a node to kapacitord's
> log/stderr ala:
> |debugDump()
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/influxdata/kapacitor/issues/583>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADmOAvV9pi_BglWHZwpxwv6i3vAcc7Toks5qF5I3gaJpZM4Io9UM>
> .
>
-- 
Nathaniel Cook
Kapacitor Lead
https://influxdata.com

**Comment by james-lawrence** [comment]
tried it didn't seem to do anything either, i now have a tickscript working though so moving on for the time being.

**Comment by jsvisa** [comment]
@james-lawrence 

```
.where(lambda: 'usage_idle' > 10) 
```

to 

```bash
.where(lambda: "usage_idle" > 10)
```
