### ISSUE TITLE
Add more stateful global functions

### ISSUE THREAD

**Issue by jsvisa** [influxdata/kapacitor#585]
Hi, @nathanielc I like Kapacitor, I want Kapacitor alert out when it meets the below two conditions:

 1. The spread of CPU usage within window is larger than n1;
 2. And the sigma of CPU usage with the same window is larger than n2; 

If I want to imple that, seems i have an `eval` node like below:

```   
 |eval(lambda: sigma("used"), lambda: spread("used"))
        .as('sigma', 'spread')
        .keep('sigma', 'spread')
```

But by now, seems Kapacitor only support `sigma`, `count` lambda expressions, so I want to add more global functions in `eval.go` if that is accpeted. After I add some implemants like `sigma` in *tick/functions.go*, It builds out, but can't run, as error occured below:

```bash
invalid TICKscript: line 16 char40: no global function "spread" defined
```

What I'm missing?

**Comment by nathanielc** [comment]
Have a look at the NewFunctions method in tick/functions.go

On Mon, May 30, 2016, 6:30 AM Delweng Zheng <notifications@github.com>
wrote:

> Hi, @nathanielc <https://github.com/nathanielc> I like Kapacitor, I want
> Kapacitor alert out when it meets the below two conditions:
>
>    1. The spread of CPU usage within window is larger than n1;
>    2. And the sigma of CPU usage with the same window is larger than n2;
>
> If I want to imple that, seems i have an eval node like below:
>
>  |eval(lambda: sigma("used"), spread("used"))
>         .as('sigma', 'spread')
>         .keep('sigma', 'spread')
>
> But by now, seems Kapacitor only support sigma, count lambda expressions,
> so I want to add more global functions in eval.go if that is accpeted.
> After I add some implemants like sigma in *tick/functions.go*, It builds
> out, but can't run, as error occured below:
>
> invalid TICKscript: line 16 char40: no global function "spread" defined
>
> What I'm missing?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/influxdata/kapacitor/issues/585>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADmOAmdSlZ-9tLGU8oGtnkpJxy_J0_PSks5qGthfgaJpZM4Ipwfq>
> .
>
-- 
Nathaniel Cook
Kapacitor Lead
https://influxdata.com

**Comment by jsvisa** [comment]
@nathanielc Thanks for your advise, I just send a [Pull Request #586](https://github.com/influxdata/kapacitor/pull/586), could you please send me any feedback
