### ISSUE TITLE
Kapacitor Batch Undefined Error

### ISSUE THREAD

**Issue by mingraham** [influxdata/kapacitor#592]
Hello,

I have been looking around for why I am getting this error and cannot find an answer, so I am hoping there is a quick, easy answer to this.

I'm rewriting a TICKscript I have that was using streams, and now I would like it to use batches. When I define the TICKscript to overwrite the previous, I get `invalid task: name "batch" is undefined. Names in scope: time,stream`.

My Kapacitor version on this Ubuntu host is `0.12.0`.

Below is the relevant parts of my TICKscript (I removed the actions I take when alerting, because it is not pertinent):

```
var largeMean = batch
    |query('SELECT mean(sum) FROM "websocket"."default".CurrentTotalWebsocketConnections')
        .period(24h)
        .every(1m)
        .align()
        .groupBy(time(1m),*)
        .fill(0)

var smallMean = batch
    |query('SELECT mean(sum) FROM "websocket"."default".CurrentTotalWebsocketConnections')
        .period(5m)
        .every(1m)
        .align()
        .groupBy(time(1m),*)
        .fill(0)

largeMean
    |join(smallMean)
        .as('largeMean', 'smallMean')
    |alert()
```

Thanks,
Michael

**Comment by nathanielc** [comment]
You need to change the task type `kapacitor define TASK_NAME -type batch` should do it.

**Comment by mingraham** [comment]
Thank you, knew it was something simple! Much appreciated. Was in a time crunch and know how quickly you reply, thanks!
