### ISSUE TITLE
Rounding Decimals in Kapacitor

### ISSUE THREAD

**Issue by mingraham** [influxdata/kapacitor#594]
Hi,

In my `.message` property off an `alert()` node, I use a lot of tags and fields to write a detailed message to Slack. The only part I cannot seem to find online is how to round the decimals to, say, 2 decimal places. It would increase the readability by a large amount, and is quite needed.

If this is not able to be done in Kapacitor, is there a way from the InfluxDB side (because I am using batches and could possibly write the rounding logic in InfluxDB's query language)? I could not find anything on that route either.

Help is greatly appreciated, thank you,
Michael

**Comment by nathanielc** [comment]
Have a look at https://github.com/influxdata/kapacitor/issues/479

**Comment by mingraham** [comment]
Thank you very much.
