### ISSUE TITLE
alert:events sent

### ISSUE THREAD

**Issue by qianlnk** [influxdata/kapacitor#601]
how can i set events are sent to handlers if the alert is in a state other than 'OK' only? when the state change, I don't need alert.

**Comment by nathanielc** [comment]
Are you looking for `.stateChangesOnly`? https://docs.influxdata.com/kapacitor/v0.13/nodes/alert_node/#statechangesonly

**Comment by qianlnk** [comment]
No, I don't want message be sent when state change, but it always send message when state return to 'OK'.

**Comment by nathanielc** [comment]
@qianlnk Can you provide an example TICKscript and data that demonstrates what you are expecting?

**Comment by qianlnk** [comment]
@nathanielc it seem don't send message when state change to 'OK' as befroe.
By the way, I can control the frequency of sending mail? for example:
tick:
var m_request = stream
    |from()
        .measurement('m.request')
var m_response = stream
    |from()
        .measurement('m.response')
m_request
    |where(lambda: "Kafka" != "Valid" OR "Send" != "Valid" OR "Mysql" != "Valid")
    |alert()
        .crit(lambda: TRUE)
        .email()
m_response
    |where(lambda: "Kafka" != "Valid" OR "Send" != "Valid" OR "Mysql" != "Valid")
    |alert()
        .crit(lambda: TRUE)
        .email()

Data very much, so I need to control the frequency of the email. like one email perp 10min...

**Comment by nathanielc** [comment]
Use a window node:

```
var m_request = stream
    |from()
        .measurement('m.request')
    |window()
        .period(10m)
        .every(10m)
var m_response = stream
    |from()
        .measurement('m.response')
    |window()
        .period(10m)
        .every(10m)

m_request
    |where(lambda: "Kafka" != "Valid" OR "Send" != "Valid" OR "Mysql" != "Valid")
    |count()
    |alert()
        .crit(lambda: "count" > 0)
        .email()
m_response
    |where(lambda: "Kafka" != "Valid" OR "Send" != "Valid" OR "Mysql" != "Valid")
    |count()
    |alert()
        .crit(lambda: "count" > 0)
        .email()
```

**Comment by qianlnk** [comment]
thank you.
