### ISSUE TITLE
Kapacitor fails to define task with email "to" property

### ISSUE THREAD

**Issue by wunzeco** [influxdata/kapacitor#602]
I am unable to define a task that sends out email alert to a specific email address when CRITICAL is breached.  

Here are details of my host:

**Operating System:** Ubuntu 14.04 (64-bit)
**Kapacitor version:**  Kapacitor 0.13.0 (git: master ce28f6dced073e473b44f592517fa6c4d05b5e65)
**Install source:**   Pre-built package 

I was following online documentation at https://docs.influxdata.com/kapacitor/v0.13/nodes/alert_node/

My tick script looks this:

```
vagrant@default-ubuntu-1404:~$ cat cpu_alert.tick
stream
    |from()
        .measurement('cpu')
    |alert()
        // Compare values to running mean and standard deviation
        .crit(lambda: "usage_idle" <  99)
        .log('/tmp/alerts.log')
        .email().to("oiwunze@mydomain.com")
```

However, when I try to run `kapacitor define` on the script it fails

```
vagrant@default-ubuntu-1404:~$ kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp telegraf.default
invalid TICKscript: line 9 char 18: no method or property "to" on *pipeline.EmailHandler
```

I only able to define the task successfully if I remove `to("oiwunze@mydomain.com")` 

Assuming I configure smtp in kapacitor.conf to send all alerts to the email address above I still get no alerts.  I have tested locally on the server that I can send email using the mail command.

**Comment by nathanielc** [comment]
@wunzeco Thanks for the detailed report. This looks like a bug, I'll let you know what I find out.

**Comment by wunzeco** [comment]
System details:
**Operating System:** Ubuntu 14.04 (64-bit)
**Kapacitor version:**  Kapacitor **1.0.0~beta1** (git: master c6f7db54eeccc0cced849740a53f256458259966)
**Install source:**   Pre-built package 

@nathanielc 
Just to confirm that I get a different error when I try to define a task as described in my first post.

```
vagrant@default-ubuntu-1404:~$ kapacitor version
Kapacitor 1.0.0~beta1 (git: master c6f7db54eeccc0cced849740a53f256458259966)


vagrant@default-ubuntu-1404:~$ cat cpu_alert.tick
stream
    |from()
        .measurement('cpu')
    |alert()
        // Compare values to running mean and standard deviation
        .crit(lambda: "usage_idle" <  99)
        .log('/tmp/alerts.log')
        .mode(644)
        .email().to("oiwunze@mydomain.com")


vagrant@default-ubuntu-1404:~$ kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp telegraf.default
invalid TICKscript: line 9 char18: error calling func "to" on obj *pipeline.EmailHandler: reflect: cannot use *ast.ReferenceNode as type string in Call
```

Thought you might want to know.
Thanks

**Comment by nathanielc** [comment]
That error is really obscure and needs to be fixed, but basically it means use single quotes on the email address string.

**Comment by wunzeco** [comment]
I can confirm using single quotes worked. Thank you
