### ISSUE TITLE
Is there a kind of "If/else" available in "eval" nodes?

### ISSUE THREAD

**Issue by jdursel** [influxdata/kapacitor#603]
Hello,

I would like to do something like if/else to store a state in a new output measurement.

data
   |eval(lambda: if "value" gt 18 then 1 else 0).as("active")

Is it possible?
Thank you
John.

Kapacitor "0.12"

**Comment by yosiat** [comment]
@jdursel I think you can do something like this:
```
lambda: "value" > 18
```

Then active will be boolean.

**Comment by nathanielc** [comment]
And if you want to use and int type instead of boolean just convert it:

```
lambda: int("value" > 18)
```

Which will output a 1 or 0 accordingly.

**Comment by jdursel** [comment]
Hello,
Thank you for your answers. Unfortunately, this doesn't work. 
The first one gives : expression returned unexpected type bool
The second one gives : error calling int: cannot convert bool to integer
I didn't try with float(), but i don't expect it to work better :-)

It is probably due to the version of kapacitor 0.12

**Comment by jdursel** [comment]
I think it is the same kind of issue as : https://github.com/influxdata/kapacitor/issues/501
Kr

**Comment by nathanielc** [comment]
Correct the suggested solutions require 0.13 or greater. Also #501 should
be closed, as it was already implemented in 0.13.

On Wed, Jun 8, 2016, 1:41 AM jdursel <notifications@github.com> wrote:

> I think it is the same kind of issue as : #501
> <https://github.com/influxdata/kapacitor/issues/501>
> Kr
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/influxdata/kapacitor/issues/603#issuecomment-224513172>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADmOAgFhas-FaPU7ysUwne2ZguU5hPrTks5qJnIJgaJpZM4ItaL5>
> .
>
-- 
Nathaniel Cook
Kapacitor Lead
https://influxdata.com
