### ISSUE TITLE
[feature request] functions to cast float size to pretty size

### ISSUE THREAD

**Issue by jsvisa** [influxdata/kapacitor#619]
I want to add a function to cast float size to human readable string.

Assume we have the function as `pretty_size`

```
lambda: pretty_size(1)         // "1B"
lambda: pretty_size(1020)     // "1020.0B" 
lambda: pretty_size(1020)     // "1.0KB" 
lambda: pretty_size(1048576) // "1.0MB"
```

@nathanielc any idea?

**Comment by nathanielc** [comment]
@jsvisa Do you want the pretty version available as a field in the data or simply as part of an alert message?

**Comment by jsvisa** [comment]
@nathanielc for me, the first is better, and the second is sufficient by now. In your opion, which one is useful?

**Comment by nathanielc** [comment]
The first is more useful. Should be a simple addition. One need only add the function to `tick/stateful/functions.go` Kapacitor already makes use of the 	"github.com/dustin/go-humanize" package so it only a matter of connecting it all together.

**Comment by jsvisa** [comment]
I'll start the task later, and send a PR.

**Comment by jsvisa** [comment]
@nathanielc Sorry for the delay respond back to you,  review this [PR #669](https://github.com/influxdata/kapacitor/pull/669) for more information, by now I only added one function for humanize byte size, if you need more, please tell me.
