### ISSUE TITLE
Alert not resetting to ok state

### ISSUE THREAD

**Issue by bl1nk** [influxdata/kapacitor#620]
We are using the following tick file to alert on unhealthy hosts in our load balancers. Problem is that the alert does not reset if `unhealthyhostcount.maximum.count` returns to 0. We're not sure what's causing that problem, but a function like `.ok(lambda: "value" == 0)` would help here.

Is there something we're overlooking or is this behavior intended?

```
stream
    |from()
        .measurement('unhealthyhostcount.maximum.count')
        .groupBy('service')
    |window()
        .period(1m)
        .every(1m)
    |alert()
        .id('{{ .Name }}/{{ index .Tags "service" }}')
        .message('{{ .Level }} {{ index .Tags "service" }} has unhealthy instances in the ELB')
        .warn(lambda: "value" == 1)
        .crit(lambda: "value" > 1)
        .alerta()
        .value('{{ index .Fields "value" | printf "%.2f" }}')
        .resource('{{ index .Tags "service" }}')
        .environment('LIVE')
        .group('{{ index .Tags "service" }}')
        .stateChangesOnly()
```

**Comment by nathanielc** [comment]
@bl1nk Your script looks correct. Could you share more details about the data you are sending to Kapacitor? Also the output from a `|log()` node before the alert node would be helpful as well. The log output will be with the Kapacitor daemon logs.

```
stream
    |from()
        .measurement('unhealthyhostcount.maximum.count')
        .groupBy('service')
    |window()
        .period(1m)
        .every(1m)
    |log()
    |alert()
        .id('{{ .Name }}/{{ index .Tags "service" }}')
        .message('{{ .Level }} {{ index .Tags "service" }} has unhealthy instances in the ELB')
        .warn(lambda: "value" == 1)
        .crit(lambda: "value" > 1)
        .alerta()
        .value('{{ index .Fields "value" | printf "%.2f" }}')
        .resource('{{ index .Tags "service" }}')
        .environment('LIVE')
        .group('{{ index .Tags "service" }}')
        .stateChangesOnly()
```

**Comment by bl1nk** [comment]
We pull these metrics from cloudwatch and feed them into influxdb via some python script we put together. I just found out that kapacitor does not log any state changes if the value drops to 0. That means, that null-values just don't exist in influxdb.

I'd use `fill(0)` in kapacitor, but after reading the documentation this seems to be possible on joins only. Is there a way to work around that problem?

**Comment by nathanielc** [comment]
@bl1nk There is a `|default()` node which can fill missing fields

```
...
|default()
   .field('value', 0)
...
```

But it will only do so if the point itself exists but the field is missing.

If the case is that when the count is 0 a point is not sent to Kapacitor then you would need to use something like the `|deadman` switch in order to detect that case.

**Comment by bl1nk** [comment]
@nathanielc I don't think a point is sent to Kapacitor. I'd need a reverse `|deadman` switch then, but I'm not sure how to do it correctly.

**Comment by nathanielc** [comment]
@bl1nk The deadman switch is really a macro for this code

```
data
        |stats(1m)
        |derivative('emitted')
            .unit(1m)
            .nonNegative()
        |alert()
            .crit(lambda: "emitted" <= 1.0)
```

So to reverse the deadman logic simply use this code but change the alert condition, i.e.

```
data
        |stats(1m)
        |derivative('emitted')
            .unit(1m)
            .nonNegative()
        |alert()
            .warn(lambda: "emitted" >= 1.0)
            .crit(lambda: "emitted" > 1.0)
```
