### ISSUE TITLE
Two Lambdas in Eval Node Not Retaining Fields

### ISSUE THREAD

**Issue by mingraham** [influxdata/kapacitor#631]
Hello,

I have been debugging an issue where a message alerted to my Slack channel from Kapacitor v0.13.1 looks like
```
development's info is %!f(MISSING)% of the 24 hour average. Mean of %!f(MISSING) over the last 24 hours and mean of %!f(MISSING) over the last 5 minutes at 2016-06-09 21:47:20 +0000 UTC.
```
whereas it previously was working with a message like
```
development's info is 59.90% of the 24 hour average. Mean of 4.05 over the last 24 hours and mean of 2.42 over the last 5 minutes at 2016-06-02 16:49:10 +0000 UTC. 
```

My TICKscript looks like the following:
```
var oneDayMean = batch
    |query('SELECT mean(sum) FROM "db"."default".measurement')
        .period(1d)
        .every(10s)
        .align()
        .groupBy(*)
    |shift(1d)

var fiveMinuteMean = batch
    |query('SELECT mean(sum) FROM "db"."default".measurement')
        .period(5m)
        .every(10s)
        .align()
        .groupBy(*)
    |shift(5m)

oneDayMean
    |join(fiveMinuteMean)
        .as('oneDayMean', 'fiveMinuteMean')
        .fill(0)
    |eval(lambda: "fiveMinuteMean.mean" / "oneDayMean.mean", lambda: "decimalOf" * 100.0)
        .as('decimalOf', 'percentageOf')
        .keep('fiveMinuteMean.mean', 'oneDayMean.mean', 'percentageOf')
    |alert()
        .message('{{ index .Tags "environment" }}\'s info is {{ index .Fields "percentageOf" | printf "%0.2f" }}% of the 24 hour average. Mean of {{ index .Fields "oneDayMean.mean" | printf "%0.2f" }} over the last 24 hours and mean of {{ index .Fields "fiveMinuteMean.mean" | printf "%0.2f" }} over the last 5 minutes at {{ .Time }}.')
        .info(lambda: "percentageBelow" < 0.99)
        .warn(lambda: "percentageBelow" < 0.98)
        .crit(lambda: "percentageBelow" < 0.97)
        .slack()
```

I cannot seem to figure out what went wrong here, because I do not remember changing the syntax.

**Comment by mingraham** [comment]
After further debugging, it seems that I am doing something wrong with using two lambdas in one `eval` node. When I split that logic into two `eval` nodes, I seem to be able to retain all the fields I am using/creating. Any ideas why it is no longer working? I have tried the above on both 0.13.0 and 0.13.1.

**Comment by nathanielc** [comment]
@mingraham I have fixed the issue #635. This was a definite regression and tests have been added to prevent further regressions.

**Comment by mingraham** [comment]
Ok, thank you @nathanielc. Is the updated code in the nightly build?

**Comment by mingraham** [comment]
Also, what build is the last stable build without this bug in it? I am taking the TICKscript I am referencing into production today, and would like to use stable builds.

**Comment by nathanielc** [comment]
Its not in the nightly build yet. 

I believe you would have to go back to v0.12 to avoid this bug. 

FWIW I will be cutting 1.0.0-beta2 early next week with this fix.

**Comment by mingraham** [comment]
Ok, thanks for the quick work, much appreciated!

**Comment by mingraham** [comment]
@nathanielc I actually am not able to find a version of Kapacitor that is 0.12. Where should I download this from?

**Comment by nathanielc** [comment]
@mingraham Sorry for the delay, old releases are all under

`https://dl.influxdata.com/kapacitor/releases/`

To get the 0.12.0 rpm for example 

`https://dl.influxdata.com/kapacitor/releases/kapacitor-0.12.0-1.x86_64.rpm`

Or the deb 

`https://dl.influxdata.com/kapacitor/releases/kapacitor_0.12-1._amd64.deb`

**Comment by mingraham** [comment]
Thank you for the links, but looking through https://dl.influxdata.com/ with CMD+F, I could not find either of those available (I had looked here previously). Is there another way to check for existing downloadables?

**Comment by nathanielc** [comment]
@mingraham Sorry copy paste error, link updated.

@rossmcdonald Do you know if we have any location where you can find link to old versions?

**Comment by mingraham** [comment]
A tab to the right of `Nightly` listing all the available builds (including the current and previous) would be pretty incredible here: https://influxdata.com/downloads/.
