### ISSUE TITLE
Example UDF python code problems

### ISSUE THREAD

**Issue by cheribral** [influxdata/kapacitor#633]
I've been trying to work through the UDF examples on CentOS7 using python 2.7.5.  I first had to uninstall protobuf rpms and install the package with pip.  Then I had to comment out all the syntax='proto3' lines in udf_pb2.py.  That got it past python's complaints, but kapacitor is failing to start with this error on the moving average example:
"failed to load process info for "pyavg": error processing request of type info: list indices must be integers, not str"

The problem seems to be with the option names on lines 65-67 of moving_avg.py, since the mirror example works (no options), but this one fails unless I comment out the lines.  The same goes for outliers.

Looking at the udf.proto file, InfoResponse seems to define options as a map with string keys.  Any hints on what the issue might be?

**Comment by nathanielc** [comment]
@cheribral Kapacitor requires that you use version 3.0.0-beta-2 of the protocol buffer libs.

See `install-deps.sh` for a script which can install these deps from source since packages are not widely available yet.

**Comment by cheribral** [comment]
Ah ok, that fixed it.  Thank you!
