### ISSUE TITLE
Progress status of live replays doesn't change between 0 and 1

### ISSUE THREAD

**Issue by gargooza** [influxdata/kapacitor#634]
1.0.0~beta1 (git: master c6f7db54eeccc0cced849740a53f256458259966)

If I start a live replay and then do periodic GET requests to the /kapacitor/v1/replays/REPLAY_ID endpoint the approximate progress value is always zero until the replay finishes, at which point progress value is 1.

The replay itself takes ~7 minutes to run and I make the periodic GET requests roughly every second. I'd expect that at some point along the way I'd get some progress values between (0,1) instead of just 0 or 1.

In case it matters, the live replay is started with a POST to /kapacitor/v1/replays/batch with a payload of:
`{"task":"myBatchTask","start":"2016-06-09T16:13:00.297Z","stop":"2016-06-09T17:13:00.297Z","recording-time":true,"clock":"fast"}`

Why are there no progress values between zero and one on status requests?

**Comment by nathanielc** [comment]
@gargooza Updating the progress hasn't been implemented yet. The API has been fleshed out but currently only uses values of 0 or 1. See #506 for details.

**Comment by nathanielc** [comment]
Closing as dup of #506
