### ISSUE TITLE
Kapacitor on new host

### ISSUE THREAD

**Issue by viswa-devops947** [influxdata/kapacitor#641]
I have created two instances on aws.
Installed influxdb+telegraf on one instance and Kapacitor on other instance.

I want to connect Kapacitor to influxdb on specific UDP port.
so i created subscription in influxdb.

CREATE SUBSCRIPTION "kapacitor-12beaa5b-6a31-42c2-aae8-1c2032ea6199" ON kapacitor_example."default" DESTINATIONS ANY 'udp://kapacitor-public-ip:50000'; 

when i start Kapacitor it throws "E! failed to start listener: listen udp kapacitor-ip:50000: bind: cannot assign requested address".

Please let me know if i made any mistake.
i have open all ports for UDP as per testing.
All UDP UDP 0 - 65535 0.0.0.0/0

**Comment by nathanielc** [comment]
@viswa-devops947 The problem is that the Kapacitor host doesn't have an interface with `kapacitor-public-ip` since that IP is NATed to the box. In version 1.0.0~beta1 there is a new config option to lets you specify the bind ip. For example:

```
[[influxdb]]
  enabled = true
  ...
  udp-bind = "0.0.0.0"
```

This should allow the address to bind and still allow for the remote InfluxDB to connect to the correct public IP.

**Comment by viswa-devops947** [comment]
Thanks Nathaniel
will 1.0.0~beta1 kapacitor will support 0.13 influxdb?
and how can i over come this in 0.13 v

**Comment by nathanielc** [comment]
Normally, the versions need to match but this time I can't think of any breaking changes between Kapacitor 1.0.0-beta1 and InfluxDB 0.13.

If you have to stay with 0.13 Kapacitor then you must make the `kapacitor-public-ip` dns entry for the Kapacitor host resolve to an IP that the Kapacitor host has an interface for. Maybe modifying  /etc/hosts would work in the meantime.

**Comment by viswa-devops947** [comment]
Thanks Nathaniel.
Can i run same thing in separate docker containers with specific ports mappings ?

**Comment by viswa-devops947** [comment]
can i run Kapacitor and Influxdb on separate docker containers.
which version is prefer to use this setup.

**Comment by viswa-devops947** [comment]
I have installed new beta version kapacitor and 0.13 v influxdb on diff hosts.
In Kapacitor i am using default http protocol for subscriptions.I used public ip in the hostname field of kapacitor config.
After starting Kapacitor on influxdb SHOW SUBSCRIPTIONS i see destinations with http://public_ip:9092

when i enable alert i don’t  see any stream data from influxdb.
stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="0"];

in the capacitor logs i see http 202 response code when i tried to record.
GET /kapacitor/v1/recordings/0a911ddf-f467-4a84-856d-47ead7bbee5e HTTP/1.1 202

**Comment by nathanielc** [comment]
@viswa-devops947 With the 1.0 beta there is a command `kapacitor stats ingress` which will show you the databases, retention policies and measurements for which Kapacitor is receiving data. Can you share that output?

In answer to your other questions, yes they should work well in separate docker containers.
