### ISSUE TITLE
Kapacitor beta not working even on same influxdb host

### ISSUE THREAD

**Issue by viswa-devops947** [influxdata/kapacitor#645]
Hi,
I'm using:
kapacitor Unstable v1.0.0-beta1
telegraf Stable v0.13.0
Influxdb Stable v0.13.0

Telegraf and Influxdb are working fine.

**SHOW SUBSCRIPTIONS**
retention_policy	name	mode	destinations
default	"kapacitor-12299c0d-6ba1-420b-919e-9b4301a3de93"	"ANY"	http://localhost:9092

**show RETENTION POLICIES on "kapacitor_example"**
name	duration	shardGroupDuration	replicaN	default
default	"0"	"168h0m0s"	1	true

**vi cpu_alert.tick**
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" >  70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp kapacitor_example.default

kapacitor enable cpu_alert

**kapacitor show cpu_alert**
ID: cpu_alert
Error: 
Template: 
Type: stream
Status: disabled
Executng: false
Created: 14 Jun 16 21:14 UTC
Modified: 14 Jun 16 21:37 UTC
LastEnabled: 01 Jan 01 00:00 UTC
Databases Retenton Policies: ["kapacitor_example"."default"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" > 70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

DOT:
digraph cpu_alert {
stream0 -> from1;
from1 -> alert2;
}

In the /var/log/kapacitor/kapacitor.log

stats] 2016/06/14 21:13:55 I! opened service
[httpd] 2016/06/14 21:13:55 I! Starting HTTP service
[httpd] 2016/06/14 21:13:55 I! Authentication enabled: false
[httpd] 2016/06/14 21:13:55 I! Listening on HTTP: [::]:9092
[run] 2016/06/14 21:13:55 I! Listening for signals

[httpd] 2016/06/14 21:15:19 I! 127.0.0.1 - - [14/Jun/2016:21:15:19 +0000] GET /kapacitor/v1/recordings/2b7dfb16-3498-4efb-8c97-d9db6eddf6c5 HTTP/1.1 202 212 - KapacitorClient 19608eb3-3275-11e6-8015-000000000000 3.301933ms

**Comment by rossmcdonald** [comment]
What is the output to a `SHOW DATABASES` run from the InfluxDB side? The reason I ask is because the default Telegraf database is called `telegraf`, not `kapacitor_example`. Do you have the same issue if you define the task with the command below?

```
kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp telegraf.default
```

Also, the `show` command output lists the task status as disabled:

```
Status: disabled
Executng: false
```

Are there no error messages in the logs stating why the task is disabled after enabling it?

**Comment by viswa-devops947** [comment]
Thanks Ross for looking in to it.
output of SHOW DATABASES command.

databases
name
kapacitor_example
_internal

i ran below command.
kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp kapacitor_example.default

before enable the task i ran record stream command.
kapacitor record stream -name cpu_alert -duration 20s

when i ran this command the command got stuck and in logs i continuously saw HTTP 202 message and even after the enable of task same issue.

**Comment by rossmcdonald** [comment]
If you don't run the `record` command, does the task get enabled properly with a `kapacitor enable cpu_alert`? I've never seen an instance where a task is not enabled with a `kapacitor enable` _and_ an error is not logged or provided in the `show` output.

And does the `record` command hang for longer than the duration (`20s`)? A HTTP 202 means that the request has been accepted, but processing is ongoing.

**Comment by rossmcdonald** [comment]
Also what does the output of the following command look like?

```
kapacitor stats ingress
```

Kapacitor may hang during a recording if no data is received, so it may be an issue with the subscription.

**Comment by nhannguyen** [comment]
I have the same issue. Kapacitor doesn't listen to any UDP port

```
[task_master] 2016/06/21 08:28:33 I! opened
[task_master] 2016/06/21 08:28:33 I! Started task: cpu_alert
[stats] 2016/06/21 08:28:33 I! opened service
[httpd] 2016/06/21 08:28:34 I! Starting HTTP service
[httpd] 2016/06/21 08:28:34 I! Authentication enabled: false
[httpd] 2016/06/21 08:28:34 I! Listening on HTTP: [::]:9092
[run] 2016/06/21 08:28:34 I! Listening for signals
[httpd] 2016/06/21 09:42:21 I! 127.0.0.1 - - [21/Jun/2016:09:42:21 +0000] GET /kapacitor/v1/tasks/cpu_alert?dot-view=attributes&script-format=formatted HTTP/1.1 200 639 - KapacitorClient 7385b453-3794-11e6-8001-000000000000 1.745309ms
```

I've created subscription manually in influxdb. Did I miss anything?

**Comment by rossmcdonald** [comment]
@nhannguyen What version are you running? With Kapacitor v1.0~beta1, the subscriptions were switched from UDP to HTTP, so you may not see any UDP listeners unless specifically configured to do so starting with that version.

Also you shouldn't need to be creating subscriptions manually. Kapacitor should automatically create subscriptions at start time. If you restart the service are the subscriptions not being created?

**Comment by nhannguyen** [comment]
@rossmcdonald Sorry, it's my bad. I had some typo in my config. Just figured out.

**Comment by rossmcdonald** [comment]
@nhannguyen Not a problem.

@viswa-devops947 I'm going to go ahead and close out this issue, but let me know if you continue to have problems getting Kapacitor and InfluxDB to communicate.

**Comment by ipsha1545** [comment]
Hello
I am facing the similar issue.
1.Kapacitor,influxdb and telegraf all are running
2.I am able to see the database kapacitor_example  and the related data in SHOW DATABASES.
3.I am able to see an entry in kapacitor record stream but when I am executing kapacitor list recordings,its giving me 0 bytes of stream

version
Influxdb-0.13.0
Kapacitor-0.13.1
Telegraph-0.13.1
