### ISSUE TITLE
FEATURE: Adding Exists Node

### ISSUE THREAD

**Issue by mingraham** [influxdata/kapacitor#647]
Hello,

I came across a use case where I needed to see if a value existed in a window. I couldn't think of a clever way with the nodes that were currently available, so I would like to suggest creating an `exists` node.

Here is an example situation where it would be useful: Seeing if there was at least one HTTP 404 response in the past 5 minutes.

Example TICKscript:
```
stream
    |from()
        .measurement('http_response')
    |window()
    	.period(5m)
    	.every(5m)
    	.align()
    |exists('http_response_code')
        .target('404')
    	.as('404_exists')
    |alert()
        .message('There was a 404 in the past 5 minutes.')
        .crit(lambda: "404_exists" == true)
```

**Comment by ljagiello** [comment]
We're doing something similar for 5xx errors like that:
```
stream
    |from()
        .database('services')
        .measurement('http_server')
        .where(lambda: "app" != 'unavailable')
        .groupBy('mesos_task_id')
    |window()
        .period(3m)
        .every(10s)
    |default()
        .field('count', 0.0)
    |groupBy('mesos_task_id', 'dc', 'app', 'env')
    |spread('count')
        .as('count')
    |alert()
        .id('{{ index .Tags "dc" }}/{{ index .Tags "app" }}/{{ .Name }}/{{ index .Tags "mesos_task_id" }}/')
        .message('{{ .ID }} is {{ .Level }} http 5xx response occur: {{ index .Fields "count" }} in last 3 minutes')
        .warn(lambda: "count" > 0)
        .crit(lambda: "count" > 1)
        .stateChangesOnly(10m)
        .slack()
```

**Comment by mingraham** [comment]
@ljagiello That's clever! If in the past 3 minutes you had all 5xx errors, wouldn't that not alert because the spread is 0, though?

**Comment by mingraham** [comment]
This is a sanitized version of what my colleague and I came up with to alert when an application does not return at least 1 HTTP 200 in the past 2 minutes every 2 minutes. Still, an `exists` node would be way better, but this is a less clean way for now.

batch
	|query('''
		SELECT http_response_code
		FROM "telegraf"."default".http_response
		WHERE http_response_code = 200
	''')
		.period(2m)
		.every(2m)
		.align()
		.fill(0)
	|count('http_response_code')
		.as('nr_of_200_responses')
	|alert()
		.message('No status codes of HTTP 200 OK in the past 2 minutes. Check that the service is running.')
		.crit(lambda: "nr_of_200_responses" == 0)

**Comment by nathanielc** [comment]
I like this idea. Question on the API

From your example:
```
|exists('http_response_code')
        .target('404')
        .as('404_exists')
```

What does the `http_response_code` part mean? Is the field named `404`?

Would this syntax also make sense?

```
|exists()
        .field('404', '404_exists')
        .tag('host', 'host_exists')
```

That way you can do both fields and tags.

**Comment by mingraham** [comment]
@nathanielc awesome! My example was first specifying what field we are checking, then the `target` is checking to see if there is a 404 in that field in the data passed in from previous nodes, where we save a boolean into the value given in the `as` field.

I like your idea too, but my idea was that we would check for a value within a certain field, where your idea seems to be checking if a field exists.

Maybe we could incorporate both into `exists` somehow?

**Comment by nathanielc** [comment]
@mingraham If you want to count the points that match a values all you need is this:

```
stream
    |from()
        .measurement('http_response')
    |window()
        .period(5m)
        .every(5m)
        .align()
    |where(lambda: "http_response_code" == '404')
    |count('http_response_code')
    |alert()
        .message('There was a 404 in the past 5 minutes.')
        .crit(lambda: "count" > 0 )
```

**Comment by mingraham** [comment]
@nathanielc we also wanted to alert if there was no data coming in in that `window`, and, after re-reading some of the docs, we realize that data wouldn't make it past the `window` node unless there was back-pressure.

We opted for the `batch` and that implementation above, because since we are filling with `none`, the `count` will stay at 0 if there is no data flowing in, so that we can alert on that case as well as the case of many other bad status codes with no HTTP 200 OKs.

Are there any holes in that logic we missed? We were trying to get tricky with it.

**Comment by nathanielc** [comment]
@mingraham You are correct that the data will not make it past the window node if no new points arrive for later times.

In that case batch work well. Also there is a `deadman's` switch that can alert if you stop receiving data altogether.
