### ISSUE TITLE
Kapacitor 0.13 not working with non-default influxdb database

### ISSUE THREAD

**Issue by bstascavage** [influxdata/kapacitor#648]
# **Use Case**

I have a brand new CentOS server that I am trying to get Kapacitor working on.  I followed the tutorial [found here](https://docs.influxdata.com/kapacitor/v0.12/introduction/getting_started/) and everything worked fine.  All of my configs for InfluxDB and Telegraf are exactly like the tutorial, with nothing changed.

When I create a new DB in InfluxDB (called _starwars_ in this example) and point Telegraf at it, I see the CPU data being written to the DB fine.  However, when I configure my `cpu_alert` kapacitor task to point at the new _starwars_ DB, the command `kapacitor record stream -name cpu_alert -duration 20s` just hangs.  It never returns the replay ID, just hangs in till I kill the `kapacitord` process.

# **Steps to reproduce**

## What works

Assuming that InfluxDB, Telegraf, and Kapacitor are installed on the server, the following is the telegraf config:

```
[agent]
    interval = "1s"

[outputs]

[outputs.influxdb]
    urls = ["http://localhost:8086"]
    database = "kapacitor_example"
#    database = "starwars"
    user_agent = "telegraf"

[cpu]
    percpu = false
    totalcpu = true
    drop = ["cpu_time"]
```

And the following is the kapacitor config:

```
hostname = "localhost"
data_dir = "/var/lib/kapacitor"

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"
  shutdown-timeout = "10s"

[replay]
  dir = "/var/lib/kapacitor/replay"

[storage]
  boltdb = "/var/lib/kapacitor/kapacitor.db"

[task]
  dir = "/var/lib/kapacitor/tasks"
  snapshot-interval = "1m0s"

[[influxdb]]
  enabled = true
  name = "localhost"
  default = true
  urls = ["http://localhost:8086"]
  username = ""
  password = ""
  ssl-ca = ""
  ssl-cert = ""
  ssl-key = ""
  insecure-skip-verify = false
  timeout = "0"
  disable-subscriptions = false
  udp-buffer = 1000
  udp-read-buffer = 0
  startup-timeout = "0"
  [influxdb.subscriptions]
  [influxdb.excluded-subscriptions]

[logging]
  file = "/var/log/kapacitor/kapacitor.log"
  level = "INFO"

(Various outputs removed to decrease verboseness for the ticket)

```

cpu_alert.tick:

```
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" <  70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

```

Commands run:

```
[root@full-stack ~]# kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp kapacitor_example.default
[root@full-stack ~]# kapacitor record stream -task cpu_alert -duration 20s
96975a74-6a02-4fa1-9a17-e1feb707567d
```

## What doesn't works

Assuming that InfluxDB, Telegraf, and Kapacitor are installed on the server, the following is the telegraf config:

```
[agent]
    interval = "1s"

[outputs]

# Configuration to send data to InfluxDB.
[outputs.influxdb]
    urls = ["http://localhost:8086"]
#    database = "kapacitor_example"
    database = "starwars"
    user_agent = "telegraf"

# Collect metrics about cpu usage
[cpu]
    percpu = false
    totalcpu = true
    drop = ["cpu_time"]
```

And the following is the kapacitor config:

```
hostname = "localhost"
data_dir = "/var/lib/kapacitor"

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"
  shutdown-timeout = "10s"

[replay]
  dir = "/var/lib/kapacitor/replay"

[storage]
  boltdb = "/var/lib/kapacitor/kapacitor.db"

[task]
  dir = "/var/lib/kapacitor/tasks"
  snapshot-interval = "1m0s"

[[influxdb]]
  enabled = true
  name = "localhost"
  default = true
  urls = ["http://localhost:8086"]
  username = ""
  password = ""
  ssl-ca = ""
  ssl-cert = ""
  ssl-key = ""
  insecure-skip-verify = false
  timeout = "0"
  disable-subscriptions = false
  udp-buffer = 1000
  udp-read-buffer = 0
  startup-timeout = "0"
  [influxdb.subscriptions]
  [influxdb.excluded-subscriptions]

[logging]
  file = "/var/log/kapacitor/kapacitor.log"
  level = "INFO"

(Various outputs removed to decrease verboseness for the ticket)
```

cpu_alert.tick:

```
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" <  70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

```

InfluxDB creation (though allowing telegraf to automatically create the DB has the same problem):
`create database starwars;`

Commands run:

```
[root@full-stack ~]# kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp starwars.default
[root@full-stack ~]# kapacitor record stream -task cpu_alert -duration 20s

```

And that last command just hangs.

Software Versions:

- InfluxDB - 0.13.0
- Telegraf - 0.13.1
- Kapacitor - 0.13.1

**Comment by rossmcdonald** [comment]
Thanks for the report. Can you paste the output to the following commands?

```
kapacitor stats ingress

kapacitor show cpu_alert
```

Usually a hanging recording is a sign that no points are reaching Kapacitor. From the InfluxDB side, can you also paste the output to a `SHOW SUBSCRIPTIONS` run from the InfluxDB CLI?

**Comment by rossmcdonald** [comment]
Ah, sorry, `stats ingress` was added with `1.0~beta1`, so that won't return anything on `0.13`.

Based on the `show` output above, it looks like you've never enabled the `cpu_alert` task before. Can you re-paste the output to the same `show` command after running a `kapacitor enable cpu_alert`? That will be able to tell us whether or not points are successfully being forwarded from InfluxDB to Kapacitor.

**Comment by rossmcdonald** [comment]
Regarding:

> you should still be able to do a recording without the task enabled.

That is correct, but the recording will hang if there aren't any points being received. The `stats ingress` command displays this information, but unfortunately it's not available on 0.13 so we have to use the `show` output. Based on the throughput:

```
[throughput="0.00 points/s"]
```

It doesn't look like any points are reaching the task. Can you verify that Kapacitor is listening on the right subscription ports? You can see all of the Kapacitor ports in use with:

```
sudo netstat -tlupn | grep kapacitor
```

Also are there any messages in the InfluxDB or Kapacitor logs with any errors (connection refused, etc.)?

**Comment by bstascavage** [comment]
Kapacitor seems to be listening on the correct ports (based on my limited knowledge of kapacitor):

```
[root@full-stack ~]# sudo netstat -tlupn | grep kapacitor
tcp6       0      0 :::9092                 :::*                    LISTEN      30902/kapacitord
udp        0      0 127.0.0.1:52479         0.0.0.0:*                           30902/kapacitord
udp        0      0 127.0.0.1:54679         0.0.0.0:*                           30902/kapacitord
udp6       0      0 :::44076                :::*                                30902/kapacitord
```

When I kick off the recording, all I see in `/var/log/kapacitor/kapacitor.log` is the RESTful API calls the recording command is using:

```
[httpd] 2016/06/16 17:19:20 I! ::1 - - [16/Jun/2016:17:19:20 +0000] POST /kapacitor/v1/recordings/stream HTTP/1.1 201 211 - KapacitorClient 766752f2-33e6-11e6-8033-000000000000 10.26173ms
[httpd] 2016/06/16 17:19:20 I! ::1 - - [16/Jun/2016:17:19:20 +0000] GET /kapacitor/v1/recordings/35976390-b409-4f16-b3d3-b9e2706ac891 HTTP/1.1 202 211 - KapacitorClient 76b5a8d5-33e6-11e6-8034-000000000000 7.593872ms
[httpd] 2016/06/16 17:19:21 I! ::1 - - [16/Jun/2016:17:19:21 +0000] GET /kapacitor/v1/recordings/35976390-b409-4f16-b3d3-b9e2706ac891 HTTP/1.1 202 211 - KapacitorClient 7703ab41-33e6-11e6-8035-000000000000 892.246µs
[httpd] 2016/06/16 17:19:21 I! ::1 - - [16/Jun/2016:17:19:21 +0000] GET /kapacitor/v1/recordings/35976390-b409-4f16-b3d3-b9e2706ac891 HTTP/1.1 202 211 - KapacitorClient 7750680e-33e6-11e6-8036-000000000000 7.918244ms
```

The only non-API call I get is this:

`[edge:35976390-b409-4f16-b3d3-b9e2706ac891|stream->stream0] 2016/06/16 17:19:52 I! aborting c: 40 e: 40`

And the only thing I am getting in my InfluxDB log is the telegraf writes.

**Comment by bstascavage** [comment]
Ok, made some headway.  Apparently, if you change a tasks's database, it doesn't seem to actually start listening to the old one.  However, if you kill and restart kapacitor, it will then start to stream correctly, and the recording will work.

If I have a working DB called 'testdb' : 

```
[root@full-stack2 ~]# kapacitor show cpu_alert
ID: cpu_alert
Error:
Type: stream
Status: enabled
Executing: true
Created: 16 Jun 16 17:47 UTC
Modified: 16 Jun 16 17:48 UTC
LastEnabled: 16 Jun 16 17:48 UTC
Databases Retention Policies: ["testdb"."default"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" < 70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

DOT:
digraph cpu_alert {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="163"];

from1 [avg_exec_time_ns="782ns" ];
from1 -> alert2 [processed="163"];

alert2 [alerts_triggered="0" avg_exec_time_ns="4.912µs" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}
```

If I remove the tasks and readd it with another DB:

```
[root@full-stack2 ~]# kapacitor delete tasks cpu_alert
[root@full-stack2 ~]# kapacitor define cpu_alert     -type stream     -tick cpu_alert.tick     -dbrp testdb1.default
[root@full-stack2 ~]# kapacitor enable cpu_alert
```

...and point telegraf at the new DB:

```
[agent]
    interval = "1s"

[outputs]

# Configuration to send data to InfluxDB.
[outputs.influxdb]
    urls = ["http://localhost:8086"]
#    database = "starwars"
    database = "testdb1"
    user_agent = "telegraf"

# Collect metrics about cpu usage
[cpu]
    percpu = false
    totalcpu = true
    drop = ["cpu_time"]
```

```
[root@full-stack2 ~]# kapacitor show cpu_alert
ID: cpu_alert
Error:
Type: stream
Status: enabled
Executing: true
Created: 16 Jun 16 17:53 UTC
Modified: 16 Jun 16 17:55 UTC
LastEnabled: 16 Jun 16 17:55 UTC
Databases Retention Policies: ["testdb1"."default"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" < 70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')


DOT:
digraph cpu_alert {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="0"];

from1 [avg_exec_time_ns="0" ];
from1 -> alert2 [processed="0"];

alert2 [alerts_triggered="0" avg_exec_time_ns="0" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}

```

BUT...as soon as I kill Kapacitor and restart it:

```
[root@full-stack2 ~]# kapacitor show cpu_alert
ID: cpu_alert
Error:
Type: stream
Status: enabled
Executing: true
Created: 16 Jun 16 17:53 UTC
Modified: 16 Jun 16 17:55 UTC
LastEnabled: 16 Jun 16 17:55 UTC
Databases Retention Policies: ["testdb1"."default"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" < 70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')


DOT:
digraph cpu_alert {
graph [throughput="14.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="57"];

from1 [avg_exec_time_ns="807ns" ];
from1 -> alert2 [processed="57"];

alert2 [alerts_triggered="0" avg_exec_time_ns="1.628µs" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}
```

**Comment by nathanielc** [comment]
@bstascavage Kapacitor version 0.13.1 would not detect new databases that were created after Kapacitor was started. In the 1.0.0-beta1 Kapacitor now periodically checks to for new databases and subscribes to them. Its likely that deleting the task had little to do with but that restarting Kapacitor synced up the subscriptions for the new database.

**Comment by bstascavage** [comment]
Well thanks for clarifying.  You can go ahead and close this issue then.

**Comment by zargex** [comment]
Hi, I'm having a issue like you had @bstascavage, how you can solve it? .
I'm using Telegraf, influxdb and kapacitor version 1.0

**Comment by bstascavage** [comment]
I never really did.  I can only get Kapacitor to work when it is running on the same server as InfluxDB.  I can't get it to work on a remote server :(

**Comment by zargex** [comment]
Sorry to hear that, but currently I'm running kapacitor and influxdb in the same machine. 
I opened a new Issue (#948) because i have been trying to fix it for a few days. 
If you (or @nathanielc and @rossmcdonald ) can see it, I will appreciate it.

**Comment by jait-23** [comment]
// cod_alert.tick
stream
|from()
.measurement('cod')
|alert()
.crit(lambda: "reading" > 87)
.log('/tmp/cod_alert.log')

// kapacitor.conf
[influxdb.subscriptions]
# Set of databases and retention policies to subscribe to.
# If empty will subscribe to all, minus the list in
# influxdb.excluded-subscriptions
#
# Format
# db_name = 
#
# Example:
# my_database = [ "default", "longterm" ]
kerneltest = [ "autogen", "default" ]

commands to execute and run:

kapacitor define cod_alert -type stream -dbrp kerneltest.autogen -tick /cod_alert.tick
kapacitor list tasks
kapacitor enable cod_alert
Next, I am searching the log file in the /tmp/cod_alert.log, but unable to generate it.
Strange thing is I am able to generate the log file for telegraf database for the cpu-usage tick-script Kindly help me out!!! Thanks.

**Comment by nathanielc** [comment]
@jait-23 Can you post your question to the mailing list? As this issue is already closed. 

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
