### ISSUE TITLE
Not all data inserted into InfluxDB is processed 

### ISSUE THREAD

**Issue by Mahajarama** [influxdata/kapacitor#655]
I have the following script:

```
stream
    |from()
        .measurement('writes')
        .groupBy('node')
    |alert()
        .crit(lambda: "write" > 700)
        .log('/tmp/alerts.log')
```

where the task is defined as follows:

```
kapacitor-0.13.1-1/usr/bin/kapacitor define writes -dbrp node.one_day -type stream -tick scripts/writes.tick
```

I have an InfluxDB instance running.  Every minute, 20 points are inserted into the database; more specifically, there are 4 external data sources, each inserting 5 points into the database simulateneously.  Most of the time, all the inserted data points get processed by Kapacitor; however, sometimes I notice that this isn't the case.  For instance:

```
DOT:
digraph writes {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="15"];

from1 [avg_exec_time_ns="9.516µs" ];
from1 -> alert2 [processed="15"];

alert2 [alerts_triggered="5" avg_exec_time_ns="218.129µs" crits_triggered="5" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
```

After a minute of insertions, only 15/20 points are processed.  Looking at the database, I can see that all 20 points were inserted:

|time|write|
|-----|------|
|1466221156597000000|329
|1466221156597000000|748
|1466221156597000000|991
|1466221156597000000|940
|1466221156597000000|640
|1466221156609000000|236
|1466221156609000000|75
|1466221156609000000|464
|1466221156609000000|9
|1466221156609000000|704
|1466221156610000000|133
|1466221156610000000|90
|1466221156610000000|375
|1466221156610000000|236
|1466221156610000000|521
|1466221156610000000|453
|1466221156610000000|660
|1466221156610000000|508
|1466221156610000000|728
|1466221156610000000|396

Am I misinterpreting the meaning of the "processed" label? Is there a mistake in the TICK script or task definition? I started using Kapacitor only a couple of days ago, so chances are I am missing something here.

Thanks in advance!

**Comment by rossmcdonald** [comment]
@Mahajarama What version of Kapacitor are you using? Also are Kapacitor and InfluxDB on the same instance? 

Points are forwarded from InfluxDB to Kapacitor via UDP with versions at <= 0.13, so it's possible that some of the points are being lost in transit. Also, when you see drops, are there consistently only 5 points missing? Or does it vary?

**Comment by Mahajarama** [comment]
I am using kapacitor-0.13.1-1.  Kapacitor and InfluxDB are on the same instance.  When I see drops, there are consistently only 5 points missing.

**Comment by rossmcdonald** [comment]
That's interesting that it's always 5 points. With Kapacitor v1.0-beta1, the default subscriptions were changed to use HTTP, so I'd be curious to see if you get the same results with the latest builds.

If you update your script to:

```
stream
    |from()
        .measurement('writes')
        .groupBy('node')
    |alert()
        .info(lambda: TRUE)
        .log('/tmp/alerts.log')
```

(which should include an INFO alert for every point in the `/tmp/alerts.log` file)

Do you only get 15 lines?

**Comment by Mahajarama** [comment]
Changing it to 'info' results in 15 lines in the log file.  I'll see if I can reproduce the issue on the latest beta build.

**Comment by rossmcdonald** [comment]
@Mahajarama Okay, let me know if the upgrade fixes it. I'd also be curious to see if removing the `.groupBy('node')` changes anything.

**Comment by Mahajarama** [comment]
I haven't been able to hit the issue since upgrading, so it looks like it's fixed.  As for removing the groupBy, this has no effect on the older version (the issue is still hit)
