### ISSUE TITLE
Methods for reducing alert spamming

### ISSUE THREAD

**Issue by freeseacher** [influxdata/kapacitor#658]
What is the official way for reducing spam alerts in kapacitor? 
Let me explain better. Some triggers on several hosts may be too aggressive. 
For example my disk low trigger is near 60% but for several volumes i do not want that trigger be too low. 
So i have to exclude it from processing. But i can't find any tools for this nor exclude in where (of cause it will be not a good way) nor any specific node types nor possibility to disable alert for specific ('host', 'path')
my trigger is
```
var warn_threshold = 60
var crit_threshold = 62

var alerta_resource = 'Storage'
var message = '{{ .ID }} is {{ .Level }} value:{{ index .Fields "used_percent" }}'
var id = '[kapacitor] {{ index .Tags "host"}} | {{ index .Tags "path"}}'

var memory = stream
    |from()
        .measurement('disk')
        .groupBy('host', 'path')

memory
    |default()
        .field('used_percent', 0.0)
    |alert()
        .id(id)
        .message(message)
        .warn(lambda: "used_percent" > warn_threshold)
        .crit(lambda: "used_percent" > crit_threshold)
        .stateChangesOnly()
        .alerta()

```
Any ideas?

**Comment by rossmcdonald** [comment]
I'd recommend you specifically limit the `memory` variable to the paths you care about with `.where()` and lambda expressions (only alerting on the `/` filesystem, for example). Or assuming you are using Telegraf, you can also limit the [disk](https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L421) plugin configuration to only record values for filesystems/paths you care about.

If neither of those options work, you could investigate [task templates](https://docs.influxdata.com/kapacitor/v1.0/examples/template_tasks/) (available starting with v1.0~beta1), where you could specify a template for each host or type of hosts.

I hope that helps!

**Comment by freeseacher** [comment]
Of cause i am using telegraf :) 
But i really care about disk that are excluded from that alert i just wish to use another policies for them. and in case i have a lot of disk with another policy.
I doubt how cat templates can help me ? do i need to add disk for alerting on one by one basis ?

**Comment by nathanielc** [comment]
@freeseacher What would you like to see?

Currently as @rossmcdonald pointed out you can use the `where` clause to filter out host/path combos that you don't care to monitor.

For example:
```
var warn_threshold = 60
var crit_threshold = 62

var alerta_resource = 'Storage'
var message = '{{ .ID }} is {{ .Level }} value:{{ index .Fields "used_percent" }}'
var id = '[kapacitor] {{ index .Tags "host"}} | {{ index .Tags "path"}}'

var memory = stream
    |from()
        .measurement('disk')
        .groupBy('host', 'path')
        .where(lambda: "host" != 'somehost' AND "path" != "/boot")

memory
    |default()
        .field('used_percent', 0.0)
    |alert()
        .id(id)
        .message(message)
        .warn(lambda: "used_percent" > warn_threshold)
        .crit(lambda: "used_percent" > crit_threshold)
        .stateChangesOnly()
        .alerta()
```

This can get tedious to list all hosts/paths that you want to ignore. That is where templates come in. Templates make is easy to define new tasks based off a common template but with the different vars per task. This [link](https://docs.influxdata.com/kapacitor/v1.0/examples/template_tasks/) about Templates that Ross linked should show you how to do it.

Example template TICKscript

```
var warn_threshold = 60
var crit_threshold = 62
// Expect a host to be defined
var host string
// Expect a path to be defined
var path string

var alerta_resource = 'Storage'
var message = '{{ .ID }} is {{ .Level }} value:{{ index .Fields "used_percent" }}'
var id = '[kapacitor] {{ index .Tags "host"}} | {{ index .Tags "path"}}'

var memory = stream
    |from()
        .measurement('disk')
        .groupBy('host', 'path')
        // Only check for this specific host/path pair.
        .where(lambda: "host" == host AND "path" == path)

memory
    |default()
        .field('used_percent', 0.0)
    |alert()
        .id(id)
        .message(message)
        .warn(lambda: "used_percent" > warn_threshold)
        .crit(lambda: "used_percent" > crit_threshold)
        .stateChangesOnly()
        .alerta()
```

**Comment by freeseacher** [comment]
>freeseacher What would you like to see?

@nathanielc i don't know what i am exactly want to see. 
i just want to understand how to implement different policy on different devices without explicitly set them in where clause. 
examples like 
```where(lambda: "host" != 'somehost' AND "path" != "/boot")```
works well when we talking about one policy per group(influxdb, telegraf, kapacitor) but at least for disk space i cant use one size fits all solution. 
Maybe it will be better to maintain in kapacitor some kind of object selector for applying alerts to. That will populate `where` clause instead of me. 
Maybe i want to see some kind of predefining hosts to policy zone or something like that... at least hosts.

**Comment by rossmcdonald** [comment]
@freeseacher What about something like Python's `in` and `not in` operators, paired with arrays? For example:

```
var ignore_paths = [ "/boot" "/tmp" "/dev" ]
var ignore_hosts = [ "host1" "host2" ]

var memory = stream
    |from()
        .measurement('disk')
        .groupBy('host', 'path')
        // Limit results only to items _not_ in the ignore_* arrays
        .where(lambda: "host" not in ignore_hosts AND "path" not in ignore_paths)
```

I have no idea how difficult this would be to implement (sorry, Nathaniel 😄 ), but I want to get a better idea of what an ideal syntax would be for this use-case.

**Comment by freeseacher** [comment]
Recently i think about it once more, it looks like the best way to achieve my goal is to add several tags more in telegraf in global_tags section. 
So I add env tag so it will act as policy. 
Probably later i will search for an option for telegraf to set additional tags per plugin. 
thats looks like an acceptable solution for me now.

**Comment by rossmcdonald** [comment]
Okay, sounds good. I'm going to go ahead and close out this issue, but let us know if you have any other questions.
