### ISSUE TITLE
InfluxDB Subscriptions - HTTP Endpoint

### ISSUE THREAD

**Issue by dilgerma** [influxdata/kapacitor#663]
I try to run kapacitor against influxdb, but instead of udp, I try to report subscription data against kapacitor over http (like mentioned in the configuration..)
I see Kapacitor Subscriptions in InfluxDB pointing to http://<kapacitor ip>:9092, which is basically correct (I assume), but I dont see any data coming to kapacitor.

If I try to do a recording, it just hangs.

So the first question - is this setup supposed to work? As I cannot seem to find any information at all using HTTP Endpoint for Influx Subscriptions.

**Comment by rossmcdonald** [comment]
@dilgerma What version of Kapacitor are you running? Also what is the output of the following InfluxQL query run from your InfluxDB server?

```
> SHOW SUBSCRIPTIONS
```

Regarding:

> If I try to do a recording, it just hangs.

Recordings will hang if no points are reaching the instance, so it sounds like either no data is being written to the database or the subscriptions are misconfigured.

**Comment by bbczeuz** [comment]
Similar behavior here
- If I use ```subscription-protocol = "http"```
 - ```influx -execute "SHOW SUBSCRIPTIONS"``` shows subscriptions to all DBs
 - ```kapacitor stats ingress``` shows only subscriptions to ```_kapacitor``` (independent of if this DB exists or not)

- If I change kapacitor's config to ```subscription-protocol = "udp"```, everything works as expected, except that kapacitor never unsubscribes itself.

### environment

```
$ uname -a
Linux zeuz-vm0 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ go version
go version go1.6.2 linux/amd64
$ influxd version 
InfluxDB v0.13.0 (git: 0.13 e57fb88a051ee40fd9277094345fbd47bb4783ce)
$ kapacitor version
Kapacitor v1.0.0-beta1-3-g3003b83 (git:  )
```
I got it from git about 2w ago. The current master branch doesn't build, but that's another issue:
```
go install -ldflags "-X main.version=v1.0.0-beta1-25-g3a97fb9" ./...
# github.com/influxdata/kapacitor/vendor/github.com/influxdata/influxdb/services/httpd
vendor/github.com/influxdata/influxdb/services/httpd/handler.go:789: invalid operation: token.Claims["exp"] (type jwt.Claims does not support indexing)
vendor/github.com/influxdata/influxdb/services/httpd/handler.go:795: invalid operation: token.Claims["username"] (type jwt.Claims does not support indexing)
make: *** [build] Error 2
```

**Comment by rossmcdonald** [comment]
@bbczeuz What does the output to a `SHOW SUBSCRIPTIONS` look like?

**Comment by rossmcdonald** [comment]
@bbczeuz Regarding the build error, that's not working because you're trying to build the incorrect packages. If you need to compile Kapacitor from source, either use the `build.py` script included in the repo or the commands:

```
go install ./cmd/kapacitor
go install ./cmd/kapacitord
```

**Comment by dilgerma** [comment]
For me,
Http-Subscriptions work with 1.0-beta-1, not with 0.13.x.

**Comment by rossmcdonald** [comment]
@dilgerma Thank you for the update, I'm glad to hear the v1.0-beta is working for you. 

I'm going to go ahead and close this issue, but feel free to respond here if you run into further issues.
