### ISSUE TITLE
mode() not setting file permissions correctly

### ISSUE THREAD

**Issue by gargooza** [influxdata/kapacitor#665]
1.0.0~beta1 (git: master c6f7db54eeccc0cced849740a53f256458259966)

I have an alert that includes the following lines:
`b|deadman(100.0, 15m)
.id('Deadman')
.message('{{ .ID }} is {{ .Level }}: {{ index .Fields "emitted" }} points seen in last 15m')
.log('/tmp/Deadman.log')
.mode(644)`

I expected the resulting log file to have perms -rw-r--r-- but instead it has: 
`--w----r--  1 kapacitor kapacitor 1.7K Jun 22 10:37 Deadman.log`

**Comment by rossmcdonald** [comment]
@gargooza Do you have the same issue if you update the mode to `0644`? Based on the documentation, the `.mode()` node expects a 4-digit mode. 

There definitely needs some more validation on the specified mode to prevent issues like this, though.

**Comment by gargooza** [comment]
I am actually specifying `0644` as the mode when I define the task. What I pasted earlier was the output from a `show task`.

**Comment by nathanielc** [comment]
@gargooza The bug is that the mode is being interpreted as a decimal number instead of an octal number. We should change it to accept a string that then gets interpreted as an base 8 number.
