### ISSUE TITLE
Need help on a tick script

### ISSUE THREAD

**Issue by shang-wang** [influxdata/kapacitor#668]
Hi all:

I'm new to Kapacitor and I'm having trouble coming up with an alert in my mind related to influxdb.

The alert should be triggered when the latest value is greater than the mean() value for the past 24hrs in my current measurement. This alert should apply to any series. 

I came up with some TICK script fragments, but have no idea how to put them together:

```
var last_day_mean = batch
    |query('''SELECT mean("twoway_delay_min") FROM "latency_prod"."default".latency''')
        .groupBy(site, paa)
        .period(1d)
        .every(1h)
```

```
var last_value = batch
    |query('''SELECT last("twoway_delay_min") FROM "latency_prod"."default".latency''')
        .groupBy(site, paa)
        .period(1d)
        .every(1h)
```

I thought above nodes are able to join based on the tags(series):
```
last_day_mean
    |join(last_value)
        .as('last_day_mean', 'last_value')
    |alert()
        .crit(lambda: "last_day_mean.mean" < "last_value.last")
        .log('/tmp/test/log')
```

but apparently `join()` would only join on timestamp according to the documentation, which is kind of useless to me, because I want to compare the results for each pair of `(site, paa)`.

I'm in desperate need for a solution like this, I hope I made myself clean enough. Sorry for not being to do enough research as my time is limited. Thanks.

**Comment by nathanielc** [comment]
@shang-wang You are on the right track. The pieces your are missing are the [align](https://docs.influxdata.com/kapacitor/v0.13/nodes/query_node/#align) property of the QueryNode or the [tolerance](https://docs.influxdata.com/kapacitor/v0.13/nodes/join_node/#tolerance) property of the JoinNode. 

The join operation is time and the group by dimensions (aka tags/series). So all you need to do is ensure that the times match. There are two ways to do this:

1. Use align so that the queries are performed on the hour every hour
2. Use tolerance to allow points that are within the same hour to join 

An align example

```
var last_day_mean = batch
    |query('''SELECT mean("twoway_delay_min") FROM "latency_prod"."default".latency''')
        .groupBy(site, paa)
        .period(1d)
        .every(1h)
        .align()

var last_value = batch
    |query('''SELECT last("twoway_delay_min") FROM "latency_prod"."default".latency''')
        .groupBy(site, paa)
        .period(1d)
        .every(1h)
        .align()

last_day_mean
    |join(last_value)
        .as('last_day_mean', 'last_value')
    |alert()
        .crit(lambda: "last_day_mean.mean" < "last_value.last")
        .log('/tmp/test/log')
```

A tolerance example
```
var last_day_mean = batch
    |query('''SELECT mean("twoway_delay_min") FROM "latency_prod"."default".latency''')
        .groupBy(site, paa)
        .period(1d)
        .every(1h)

var last_value = batch
    |query('''SELECT last("twoway_delay_min") FROM "latency_prod"."default".latency''')
        .groupBy(site, paa)
        .period(1d)
        .every(1h)

last_day_mean
    |join(last_value)
        .as('last_day_mean', 'last_value')
        .tolerance(1h)
    |alert()
        .crit(lambda: "last_day_mean.mean" < "last_value.last")
        .log('/tmp/test/log')
```

Hope that helps.

**Comment by shang-wang** [comment]
@nathanielc That's super helpful. Please correct me if I'm wrong, but I think the value for `tolerance` might not be `1h`. Because doing a `mean()` on a period of `1d` will not guarantee to give you a timestamp that's within 1h difference of `last()`, right? But since both `mean()` and `last()` only yield one result for each dimension, there would always be a one to one match if I do `torlerance(1d)`.

**Comment by nathanielc** [comment]
The tolerance also rounds the resulting points' time so you will only get 1d resolution on your timestamps output for the output of the join node. Is it possible that you do not get at least one point per hour?

**Comment by shang-wang** [comment]
It's not possible in theory, but there's no guarantee, like the program that sends data to influxdb crashes. Do I need to have special action for possible empty data like using `fill()`(just learnt from the doc)?

**Comment by nathanielc** [comment]
@shang-wang Yes, fill would work, as well as using the [deadman](https://docs.influxdata.com/kapacitor/v0.13/nodes/source_batch_node/#deadman) switch

**Comment by shang-wang** [comment]
Cool. That's all. Thanks for all this.
