### ISSUE TITLE
Suppress alerts when recovering to OK state

### ISSUE THREAD

**Issue by vinhtr** [influxdata/kapacitor#670]
I'm currently running v0.12. Is it possible to prevent an alert from firing when it recovers to an OK state?

**Comment by nathanielc** [comment]
@vinhtr It is not possible in v0.12

In later versions you can chain alert nodes and filter out the OK alerts.

```
...
|alert()
    .crit(lambda: ...)
    .fieldLevel('level')
|where(lambda: "level" != 'OK')
|alert()
   .crit(lambda: "level" == "CRITICAL")
   .email() // or whatever handler you are using.
```

**Comment by nathanielc** [comment]
Fixed in #796

**Comment by mike-albano** [comment]
This is implemented as ".NoRecoveries()"

**Comment by hexiaobing5880** [comment]
Is it possible to prevent the alarm from being triggered when it returns to the normal state? What does it mean? @mike-albano
