### ISSUE TITLE
alert when don't receive data

### ISSUE THREAD

**Issue by diogofrazao** [influxdata/kapacitor#671]
Hello!

I want to receive alerts when don't receive data from 1 hour, is that possible in kapacitor?

Thank you

**Comment by rossmcdonald** [comment]
@diogofrazao Yes, I'd recommend reviewing Kapacitor's [deadman node](https://docs.influxdata.com/kapacitor/latest/nodes/alert_node/#deadman), which allows you to alert based on throughput over a period of time. For example, the node:

```
    data
        |deadman(0.0, 60m)
```

Means "alert when throughput drops to 0 points received over a 60 minute interval."

**Comment by diogofrazao** [comment]
Than you @rossmcdonald
