### ISSUE TITLE
Panic on Email Alert

### ISSUE THREAD

**Issue by vinhtr** [influxdata/kapacitor#675]
After an email gets sent out panic occurs and kapacitor restarts. I'm using v0.12.

```
panic: 421 Timeout waiting for data from client.

goroutine 19 [running]:
github.com/influxdata/kapacitor/services/smtp.(*Service).runMailer(0xc820162e60)
	/go/src/github.com/influxdata/kapacitor/services/smtp/service.go:91 +0x78c
created by github.com/influxdata/kapacitor/services/smtp.(*Service).Open
	/go/src/github.com/influxdata/kapacitor/services/smtp/service.go:36 +0x238

goroutine 1 [chan receive, 24 minutes]:
main.(*Main).Run(0xc82046bf10, 0xc82000a100, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/main.go:96 +0xbf1
main.main()
	/go/src/github.com/influxdata/kapacitor/cmd/kapacitord/main.go:41 +0x363
```

**Comment by vinhtr** [comment]
I see in newer versions it just logs an error instead of panic. Does this mean it will just keep the connection open or will it continue to create new connections every time?

master:
https://github.com/influxdata/kapacitor/blob/master/services/smtp/service.go#L91

v0.12:
https://github.com/influxdata/kapacitor/blob/v0.12.0/services/smtp/service.go#L91

**Comment by nathanielc** [comment]
Yes, it will log the error and then attempt to reconnect later.
