### ISSUE TITLE
Kapacitor record stream never ends

### ISSUE THREAD

**Issue by ckdarby** [influxdata/kapacitor#677]
Kapacitor v0.13.1

This would never end:
```kapacitor record stream -task transaction_stream_alert -duration 100s```

```
stream
    |from()
        .database('transactions')
        .retentionPolicy('default')
        .measurement('transactions')
    |window()
        .period(90s)
        .every(90s)
    |alert()
        .crit(lambda: "value" < 5)
        .log('/tmp/alerts.log')
```

**Comment by nathanielc** [comment]
@ckdarby There is an open issue where a recording hangs if no data is received.

If you are using version 1.0.0-beta* then you can check what data Kapacitor is receiving via

```
kapacitor stats ingress
```

**Comment by manan057** [comment]
@nathanielc This is what I get. 

Database                      Retention Policy              Measurement                   Points Received     
_kapacitor                    autogen                            edges                               214                 
_kapacitor                    autogen                            kapacitor                          53                  
_kapacitor                    autogen                            ingress                             207                 
_kapacitor                    autogen                            runtime                             53

**Comment by ckdarby** [comment]
@nathanielc I'm running 0.13 because I couldn't find new docs for 1.0-beta and it complains always about invalid body

**Comment by nathanielc** [comment]
@ckdarby Here are the 1.0 docs https://docs.influxdata.com/kapacitor/v1.0/

Could you share your complete error message?

@manan057 

What database retention policy (dbrp) is your task using? If its not in the ingress stats list then Kapacitor is not receiving the data.

**Comment by manan057** [comment]
@nathanielc 

This is the result I get when I run the `SHOW SUBSCRIPTIONS` query.
`
_internal
retention_policy	name	                              mode	    destinations
monitor	                "kapacitor-827c6b68-xx"	      "ANY"	    http://localhost:9092
monitor	                "kapacitor-55ca1cd8-xx"	      "ANY"    http://localhost:9092
monitor	                "kapacitor-744e9fdb-xx"	      "ANY"    http://localhost:9092

telegraf
retention_policy	name	                             mode	    destinations
default	                "kapacitor-827c6b68-xx"	     "ANY"	    http://localhost:9092
default	                "kapacitor-55ca1cd8-xx"	     "ANY"	    http://localhost:9092
default	                "kapacitor-744e9fdb-xx"	     "ANY"	    http://localhost:9092
`

This are the services that are running when I record the stream:
`
Database                     Retention Policy          Measurement             Points Received     
_kapacitor                    autogen                       runtime                       30                  
_kapacitor                    autogen                       kapacitor                     30                  
_kapacitor                    autogen                       ingress                       144                 
_kapacitor                    autogen                       edges                         159                 
_kapacitor                    autogen                       nodes                         90          
`

**Comment by pulord** [comment]
> @ckdarby There is an open issue where a recording hangs if no data is received.
> 
> If you are using version 1.0.0-beta* then you can check what data Kapacitor is receiving via
> 
> ```
> kapacitor stats ingress
> ```

slove my problem! thanks
