### ISSUE TITLE
How to do three way join on three different measurements?

### ISSUE THREAD

**Issue by shang-wang** [influxdata/kapacitor#681]
I'm not sure how to do a three way join on three different measurements, as I got error every time.

I have three measurements, one original measurement, two others aggregated ones from the original one(this works):
```
batch
    |query('''
            SELECT mean(twoway_delay_avg) AS twoway_delay_avg
            FROM "latency_prod"."default".latency
           ''')
        .groupBy(*)
        .period(1d)
        .every(10m)
    |influxDBOut()
        .database('latency_prod')
        .retentionPolicy('default')
        .measurement('latency_mean_every_10m_1d_period')
        .precision('m')

batch
    |query('''
            SELECT stddev(twoway_delay_avg) AS twoway_delay_avg
            FROM "latency_prod"."default".latency
           ''')
        .groupBy(*)
        .period(1d)
        .every(10m)
    |influxDBOut()
        .database('latency_prod')
        .retentionPolicy('default')
        .measurement('latency_stddev_every_10m_1d_period')
        .precision('m')
```

Now I'm trying to have another TICK script to see if the latest value is more than 2 stddevs from the mean from the last 24 hrs. But first, I'm trying to print the values in the log so I could at least verify the values. So I do:

```
var last_24h_stddev = batch
    |query('''
            SELECT site, paa, last("twoway_delay_avg")
            FROM "latency_prod"."default".latency_stddev_every_10m_1d_period''')
        .groupBy(*)
        .period(1d)
        .every(1h)
        .align()
    
var last_24h_mean = batch
    |query('''
            SELECT site, paa, last("twoway_delay_avg")
            FROM "latency_prod"."default".latency_mean_every_10m_1d_period''')
        .groupBy(*)
        .period(1d)
        .every(1h)
        .align()

var last_value = batch
    |query('''SELECT site, paa, last("twoway_delay_avg")
              FROM "latency_prod"."default".latency''')
        .groupBy(*)
        .period(1d)
        .every(1h)
        .align()

last_24h_mean
    |join(last_24h_stddev, last_value)
        .as('mean', 'stddev', 'last_value')
        .on('site', 'paa')
        .tolerance(1d)
    |eval(lambda: "mean.site",
          lambda: "mean.paa",
          lambda: "stddev.site",
          lambda: "stddev.paa",
          lambda: "last_value.site",
          lambda: "last_value.paa",
          lambda: "last_value.last",
          lambda: "mean.last",
          lambda: "stddev.last")
        .as('mean_site',
            'mean_paa',
            'stddev_site',
            'stddev_paa',
            'last_value_site',
            'last_value_paa',
            'last_value_last',
            'mean_mean',
            'stddev_stddev')
    |alert()
        .crit(lambda: TRUE)
        .log('/spare/local/kapacitor_data/scripts/influxdb_alerts.log')
```

It compiles fine with no syntax errors, but when I record and replay, kapacitor gives me:

`running replay: unexpected number of batch collectors. exp 2 got 3`

My question is: am I doing things correctly on the join term? Is there any flags I didn't specify when I do the dry run? Thanks!

**Comment by nathanielc** [comment]
@shang-wang Looks like you are trying to replay a recording that was created before you added the third query to the task. The error is complaining that the recording doesn't have data for the third query node.

Your join code looks correct.

**Comment by shang-wang** [comment]
You are right, I changed the code but forgot the redefine it. However, I'm not getting anything from the log despite the fact that `kapacitor list recordings` shows size of `4.5MB` collect result. Is there anyway that I can see how the data flows? I was doing two measurement-join on `stddev` and `mean` and it works, but with an additional join on the original measurements yields no results. Kapacitor log doesn't show any errors either.

**Comment by nathanielc** [comment]
@shang-wang If you are using 1.0.0-beta2 then  the `show` command now has an option to show a task running in a replay.

Example:
```
kapacitor show -replay REPLAY_ID TASK_ID
```
