### ISSUE TITLE
Get latest value and calculate stddev, mean for the last 24 hours

### ISSUE THREAD

**Issue by shang-wang** [influxdata/kapacitor#685]
I'm trying to check on the value on a field every 10 minutes and see if the latest value is 2 standard deviations more than the mean value in the past 24 hours. I came up with following tick script:
```
var last_24h_mean = batch
    |query('''
            SELECT mean("twoway_delay_avg") AS mean
            FROM "latency_prod"."default".latency
           ''')
        .period(1d)
        .every(10m)
        .groupBy(*)
        .align()
    |shift(1d)  // is this needed? 

var last_24h_stddev = batch
    |query('''
            SELECT stddev("twoway_delay_avg") AS stddev
            FROM "latency_prod"."default".latency
           ''')
        .period(1d)
        .every(10m)
        .groupBy(*)
        .align()
    |shift(1d)  // is this needed?

var last_value = batch
    |query('''
            SELECT last("twoway_delay_avg")
            FROM "latency_prod"."default".latency
           ''')
        .period(1d)
        .every(10m)
        .groupBy(*)
        .align()

last_24h_mean
    |join(last_24h_stddev, last_value)
        .as('mean', 'stddev', 'last_value')
        .on('site', 'paa')
        .tolerance(10m)
    |eval(lambda: "last_value.last",
          lambda: "mean.mean",
          lambda: "stddev.stddev",
          lambda: "last_value.last" - "mean.mean" - 2 * "stddev.stddev")
        .as('last_value_last',
            'mean',
            'stddev',
            'diff')
    |alert()
        .crit(lambda: "diff" > 0)
        .log('/tmp/alerts.log')
```

However, I'm not getting any results, while I could see from influxdb log that the queries are executed:
```
[query] 2016/06/28 17:16:51 SELECT stddev(twoway_delay_avg) AS stddev FROM latency_prod."default".latency WHERE time >= '2016-06-27T15:40:00Z' AND time < '2016-06-28T15:40:00Z' GROUP BY *
[query] 2016/06/28 17:17:01 SELECT last(twoway_delay_avg) FROM latency_prod."default".latency WHERE time >= '2016-06-27T15:40:00Z' AND time < '2016-06-28T15:40:00Z' GROUP BY *
[query] 2016/06/28 17:17:27 SELECT mean(twoway_delay_avg) AS mean FROM latency_prod."default".latency WHERE time >= '2016-06-27T15:40:00Z' AND time < '2016-06-28T15:40:00Z' GROUP BY *
......
```
But the result log file is never created. I even tried `crit(lambda: TRUE)` to make kapacitor always log everything, but sounds like the `join()` returns no data. 

I found out that if I do `mean()` or `stddev()` with date range, the timestamp would always be the beginning of the time range. So I tried with the `shift(1d)`, but it doesn't help. I feel like this is something people do all the time, but I couldn't find any references. Any advice is appreciated. Thanks.

**Comment by nathanielc** [comment]
@shang-wang The shifting of data is not needed. In general `|shift` is used in conjunction with `.offset`. 

Your script looks correct (minus the shifts). This bug #683 was fixed this morning related to doing joins with batch data and using the `.on` property. Do you have the ability to build master and try it out with the latest version?

**Comment by shang-wang** [comment]
@nathanielc I did try to pull the latest code and rebuilt, but since I didn't originally set every up I'm not sure if I did it correctly(he was on vacation). I run again but the result is still empty. I didn't have the exact outcome of bug #683 because my kapacitor didn't panic. However, I found out that getting ride of `on()` statement all together would actually make the script work. I was trying to be explicit about the join condition but sounds like I'll just do without it for now. Sorry for not being able to verify it, but will keep working on it and update. Thanks for making everything available and clear!

**Comment by shang-wang** [comment]
@nathanielc Sorry for bringing up an issue again. I ran my tick script without any problems, saw the log and everything makes sense. However, after I enabled the script and load it into kapacitor, it stops producing result again. I did `kapacitor show latency_alert`:

```
TICKscript:
var last_24h_mean = batch
    |query('''
            SELECT mean("twoway_delay_avg") AS mean
            FROM "latency_prod"."default".latency
           ''')
        .period(1d)
        .every(1m)
        .groupBy(*)
        .align()

var last_24h_stddev = batch
    |query('''
            SELECT stddev("twoway_delay_avg") AS stddev
            FROM "latency_prod"."default".latency
           ''')
        .period(1d)
        .every(1m)
        .groupBy(*)
        .align()

var last_value = batch
    |query('''
            SELECT last("twoway_delay_avg") AS last
            FROM "latency_prod"."default".latency
           ''')
        .period(1d)
        .every(1m)
        .groupBy(*)
        .align()

last_24h_stddev
    |join(last_24h_mean, last_value)
        .as('stddev', 'mean', 'last_value')
        .tolerance(1d)
    |eval(lambda: float("last_value.last") - 2.0 * "stddev.stddev" - "mean.mean")
        .as('diff')
    |alert()
        .crit(lambda: "diff" > 0.0)
        .log('/tmp/influxdb_alerts.log')

DOT:
digraph latency_alert {
graph [throughput="0.00 batches/s"];

query3 [avg_exec_time_ns="0" batches_queried="3649" connect_errors="0" points_queried="3649" query_errors="0" ];
query3 -> join6 [processed="3649"];

query2 [avg_exec_time_ns="0" batches_queried="3649" connect_errors="0" points_queried="3589" query_errors="0" ];
query2 -> join6 [processed="3649"];

query1 [avg_exec_time_ns="3.279303159s" batches_queried="3649" connect_errors="0" points_queried="3649" query_errors="0" ];
query1 -> join6 [processed="3649"];

join6 [avg_exec_time_ns="8.739µs" ];
join6 -> eval7 [processed="0"];

eval7 [avg_exec_time_ns="0" eval_errors="0" ];
eval7 -> alert8 [processed="0"];

alert8 [alerts_triggered="0" avg_exec_time_ns="0" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}
```

As you can see, on `join6 -> eval7 [processed="0"];`, it processes nothing. I initially thought `"diff" > 0.0` has no match so it doesn't evaluate anything, but even if I change the eval to `"diff" < 0.0` the result graph still looks the same. What could be the problem? Thanks!

**Comment by shang-wang** [comment]
Hey @nathanielc I hope you are well. I kept trying to make the script to work and I got some progress. I realize that changing the `tolerance()` would actually cause more/less metrix to join. However, the value of the `tolerance()` is mysterious to me. Yesterday I set it to `tolerance(48h)` and all the points are joined correctly. However, at around 20:00 the data stops coming in. When I came in this morning I played a little more, and I ended up setting it to `47h` before any alerts show up. So how does the timestamp for `mean()` and the `last()` would match? I know from [influxdb doc](https://docs.influxdata.com/influxdb/v0.13/query_language/functions/#mean) that aggregation would return the lower bound timestamp if a time range is specified, but that doesn't explain the tolerance value that I'm using. Can you somehow explain/reproduce this? Thanks.

**Comment by nathanielc** [comment]
Unless you are waiting more time than the `tolerance` time aka 47h between tests then the cause of the issue is not likely related to the tolerance. 

Internally all that is happening is the times on the points are rounded to the nearest interval of the tolerance time. Then if the rounded times are equal then the points "match" an can be joined.

**Comment by shang-wang** [comment]
@nathanielc  I have more information that might lead to the solution, sorry for reopening the issue.

I figured that it's better to log the query results for 2 different batches and compare by just looking at them to make sure that they look as I expected(and they do). Even though the `join()` still creates no result, I was able to obtain the 2 logs(attached here). I can clearly see that:

- Both have same number of entries. I verified that they contain exactly the same set of data grouped by tags.
- All entries in both files has the same timestamp. 

Here's the `show` command result again:

```
TICKscript:
var last_24h_mean_stddev = batch
    |query('''
            SELECT last("twoway_delay_avg_mean") AS mean,
                   last("twoway_delay_avg_stddev") AS stddev
            FROM "latency_prod"."default".latency_mean_stddev
            WHERE "site" != 'moscow'
           ''')
        .period(1d)
        .every(1m)
        .groupBy('site', 'paa')
        .align()
    |shift(1d)

last_24h_mean_stddev
    |alert()
        .crit(lambda: TRUE)
        .log('/spare/local/kapacitor_data/scripts/24h.txt')

var last_value = batch
    |query('''
            SELECT mean("twoway_delay_avg")
            FROM "latency_prod"."default".latency
           ''')
        .period(5m)
        .every(1m)
        .groupBy('site', 'paa')
        .align()
    |shift(5m)

last_value
    |alert()
        .crit(lambda: TRUE)
        .log('/spare/local/kapacitor_data/scripts/5m.txt')

last_24h_mean_stddev
    |join(last_value)
        .as('mean_stddev', 'last_value')
        .on('site', 'paa')
    |eval(
        lambda: "last_value.mean",
        lambda: "mean_stddev.mean",
        lambda: "mean_stddev.stddev",
        lambda: float("last_value.mean") - "mean_stddev.mean" - 3.0 * "mean_stddev.stddev"
    )
        .as('last_value_mean', 'mean_stddev_mean', 'mean_stddev_stddev', 'diff')
    |alert()
        .crit(lambda: TRUE)
        .log('/spare/local/kapacitor_data/scripts/joined.log')
DOT:
digraph latency_separate_measurement {
graph [throughput="0.00 batches/s"];

query4 [avg_exec_time_ns="0" batches_queried="3462" connect_errors="0" points_queried="3462" query_errors="0" ];
query4 -> shift5 [processed="3462"];

shift5 [avg_exec_time_ns="120ns" ];
shift5 -> alert6 [processed="3462"];
shift5 -> join8 [processed="3462"];

alert6 [alerts_triggered="3462" avg_exec_time_ns="220.597µs" crits_triggered="3462" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];

query1 [avg_exec_time_ns="0" batches_queried="3462" connect_errors="0" points_queried="3462" query_errors="0" ];
query1 -> shift2 [processed="3462"];

shift2 [avg_exec_time_ns="272ns" ];
shift2 -> join8 [processed="3462"];
shift2 -> alert3 [processed="3462"];

join8 [avg_exec_time_ns="7.779µs" ];
join8 -> eval9 [processed="0"];

eval9 [avg_exec_time_ns="0" eval_errors="0" ];
eval9 -> alert10 [processed="0"];

alert10 [alerts_triggered="0" avg_exec_time_ns="0" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];

alert3 [alerts_triggered="3462" avg_exec_time_ns="122.076µs" crits_triggered="3462" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}
```

Could you look at the log files and let me know why the join failed? Thanks.

By the way, my `kapacitor version` command shows `Kapacitor master (git: master HEAD)` as of 07/07/2016.

[5m.txt](https://github.com/influxdata/kapacitor/files/352434/5m.txt)
[24h.txt](https://github.com/influxdata/kapacitor/files/352433/24h.txt)

**Comment by PratikSavadi** [comment]
I'm trying to check on the value on a field every 5 minutes using morgoth algo but the alert is not triggering. I am not getting any result


var yesterday = batch
    |query('''Select (usage_idle)  From "telegraf"."autogen"."cpu" ''')
        .offset(1d)
        .period(5m)
        .every(1m)

var today = batch
    |query('''Select (usage_idle)  From "telegraf"."autogen"."cpu" ''')
        .period(5m)
        .every(1m)

yesterday
    |join(today)
        .as('yesterday', 'today')
        .tolerance(1s)
    @morgoth()
        .field('today')
        .scoreField('Anomalyscore')
        .sigma(3.0)
    |alert()
        .crit(lambda: "Anomalyscore" > 0.9)
        .message('CPU usage alert')
        .log('/tmp/abd.log')

DOT:
digraph abd {
graph [throughput="0.00 batches/s"];

query2 [avg_exec_time_ns="11.808391ms" batches_queried="121" errors="0" points_queried="7260" working_cardinality="0" ];
query2 -> join4 [processed="121"];

query1 [avg_exec_time_ns="13.226706ms" batches_queried="121" errors="0" points_queried="7260" working_cardinality="0" ];
query1 -> join4 [processed="121"];

join4 [avg_exec_time_ns="66.386µs" errors="0" working_cardinality="1" ];
join4 -> morgoth5 [processed="120"];

morgoth5 [avg_exec_time_ns="1.407µs" errors="0" working_cardinality="0" ];
morgoth5 -> alert6 [processed="120"];

alert6 [alerts_inhibited="0" alerts_triggered="0" avg_exec_time_ns="27.402µs" crits_triggered="0" errors="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" working_cardinality="1" ];
