### ISSUE TITLE
Reload kapacitor configuration file on signal

### ISSUE THREAD

**Issue by goller** [influxdata/kapacitor#687]
I'd like to avoid kapacitor downtime when change the kapacitor configuration file.  I'd like to see kapacitor take a SIGHUP or SIGUSR1 to mean reload configuration file without restarting the process.

**Comment by hraftery** [comment]
+1

**Comment by nathanielc** [comment]
Kapacitor now allows the configuration to be modified via the API at runtime. Reloading configuration on disk is no longer as important.

**Comment by nathanielc** [comment]
@hraftery Do you have a specific use case that isn't covered by the configuration API endpoints?

**Comment by hraftery** [comment]
@nathanielc I only had two use cases. The API endpoint solves one but not the other.

- Use case 1: updating the SMTP configuration.

The API allows me to update the SMTP configuration. It's certainly more cumbersome than a SIGHUP, but appears to do the job. I say "appears" but there doesn't appear to be a way to verify the password has been set. I used:

```
curl -H "Content-Type: application/json" -X POST -d '{ "set":{ "password": "aaa" } }' http://127.0.0.1:9092/kapactor/v1/config/smtp/
```

- Use case 2: adding a UDF function.

There does not appear to be an API endpoint to add or modify UDF functions.

So the configuration API endpoints look like a good improvement, but do not solve the issue.

**Comment by nathanielc** [comment]
@hraftery Thanks for the specifics. Reopening issue till we have a solution.

**Comment by ahsanali** [comment]
any update on adding UDF function through API ?

**Comment by crazy-canux** [comment]
Is there any authentication to use the api?
I always got 204(no content).
what's happend?

**Comment by pravindamodaran** [comment]
@nathanielc http-post endpoint does not get created properly through REST API. Opened #2363 . Looks like the http-post handler does not use the created endpoint, and hence the URL is empty.
