### ISSUE TITLE
Add the ability to add a "message" field when inserting alerts into InfluxDB

### ISSUE THREAD

**Issue by lpalm** [influxdata/kapacitor#692]
Similar to levelField, idField and durationField, having a "messageField" would be pretty handy, allowing the message for the alert to be persisted. This allows for Grafana annotations for alerts to have a nice, user-readable explanation of the conditions that triggered the alert. 
We're currently hacking this functionality by having an HTTP server receive the alert's JSON (which contains the message) and uploading to InfluxDB so not super high priority for us, but would be nice to streamline this data flow.

**Comment by nathanielc** [comment]
This was implemented a while back.
