### ISSUE TITLE
How to get an older version of kapacitor (if possible)?

### ISSUE THREAD

**Issue by pootzko** [influxdata/kapacitor#694]
Hi,

is there a way for me to get my hands on Kapacitor v0.10 or v0.10.1 somehow? I'm upgrading the 3rd party influxdata library for .net (for influx and kapacitor) which I made, and I can't run my integration tests for kapacitor v0.10 because my VM with influx and kapacitor got corrupted and I'm not able to install and run v0.10 again.

I tried to `go get` this: https://github.com/influxdata/kapacitor/tree/v0.10/cmd but it gives me:

package github.com/influxdata/kapacitor/tree/v0.10/cmd/kapacitor cannot find package "github.com/influxdata/kapacitor/tree/v0.10/cmd/kapacitor" in any of: /usr/lib/go/src/github.com/influxdata/kapacitor/tree/v0.10/cmd/kapacitor (from $GOROOT) /go/srcgithub.com/influxdata/kapacitor/tree/v0.10/cmd/kapacitor (from $GOPATH)"

No offense but I really don't understand why a working version at least hasn't been kept somewhere. What happens if someone needs to create additional servers with the same version of influx/kapacitor and is not in the position to upgrade everything because you guys decided to just remove it from the internet. You can't really expect everyone to upgrade everything all the time (a few of my influxdb reported issues have simply been closed after 3-4 months of no replies and I was told "to upgrade"..). I really appreciate all the hard work you guys are putting into this and that you're giving it for free, but it's really becoming tedious to work with your products because of things like this (and because of frequent API changes which to be fair did become more stable recently and I hope it will stay like that after v1.0). 

It's not really a major issue if I can't run a few tests, and I'm sure you have other things on your mind. But you need to understand people will start going away from your products because it seriously feels like they're not stable and because we can't even be sure that we'll be able to use what we already had in place after you guys decide to move on to newer versions and wipe everything you consider old. I've talked to a few people on a couple of IoT conferences who use your products and everyone had the same story - everyone thinks your products are cool and that they have potential, but nobody is happy about the stability.. :/

Anyway, if there is a chance you might have a working version v0.10  somewhere which I would be able to install easily enough, I would be most grateful if you could provide it to me. If not, I'll survive. :D might even clone the production server and use that for testing.

Thanks and cheers!

**Comment by rossmcdonald** [comment]
@pootzko Thank you for the feedback, and I apologize that the previous versions aren't easier to find. All current and previous versions of Kapacitor are available through our CDN, though. For example, 0.10.1:

https://dl.influxdata.com/kapacitor/releases/kapacitor-0.10.1-1.x86_64.rpm
https://dl.influxdata.com/kapacitor/releases/kapacitor_0.10.1-1_amd64.deb

Also the [yum repo](https://repos.influxdata.com/rhel/6/x86_64/stable/) has all historical versions, and we are working on the same for the apt repo.

Let me know if there's a specific package that you can't find and I can drop a link here.

**Comment by pootzko** [comment]
Awesome, thanks a lot.
