### ISSUE TITLE
HTTP POST with custom params

### ISSUE THREAD

**Issue by jommgoncalves** [influxdata/kapacitor#700]
Hi,

How can I send an HTTP POST to an external API with custom params?
For example:

> token: 'xpto'
> message: 'text'
> ...

Cheers,

**Comment by nathanielc** [comment]
@jommgoncalves This is not currently possible. See #117 for more details.

**Comment by caengcjd** [comment]
what a shit design

**Comment by lstwn** [comment]
Hey, 

as a follow up question on this basically: Is it somehow possible to influence how the body of the http POST is set? This would be highly useful for alerting to e. g. Matrix, which requires to have the body set to the following format:

```
{
  "msgtype": "m.text",
  "body": "<ALERT_INFO>",
}
```

c. f. https://www.matrix.org/docs/guides/client-server-api#sending-messages

I tinkered with the alert-template setting but I could not modify the basic structure outlined here [docs](https://docs.influxdata.com/kapacitor/v1.5/nodes/alert_node/#alert-event-data).

Thanks
