### ISSUE TITLE
Kapacitor as docker container

### ISSUE THREAD

**Issue by sidgod** [influxdata/kapacitor#703]
I am running influxdb and cronograf as docker containers from official images available on docker hub. Based on issue #349 I tried following on my docker host:
docker run --restart=always -d -p 8083:8083 -p 8086:8086 -v /opt/influx-data/influxdb-data:/var/lib/influxdb --name=influxdb -h influxdb --net=influxdb influxdb

docker run --restart=always -d -p 9092:9092 -v /opt/influx-data/conf/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro -v /opt/influx-data/kapacitor-data:/var/lib/kapacitor -e KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086 --name=kapacitor -h kapacitor --net=influxdb kapacitor

I created network called influxdb before running these commands. I am able to setup influxdb and configure cronograf to use influx db using its host in this new network.

Issue is seen when i try to record a stream using kapacitor. I can see data on cronograf arriving correctly. However same data is not recorded which means influxdb is not forwarding data to Kapacitor ?

I see no errors in influxdb / kapacitor logs. Am I missing something ?

**Comment by sidgod** [comment]
Sorry for trouble, got it solved. Fixed config getting loaded for kapacitor and it worked perfectly fine.

**Comment by alexbardas** [comment]
@sidgod I'm running into the exact same issue when running kapacitor and influxdb in different docker containers. Did you just add `-config /etc/kapacitor/kapacitor.conf` when calling the kapacitor container? Whatever I do I can't manage to get it working. I can further mention that I'm running them in the same network and influxdb / telegraf / grafana integration works fine.

**Comment by mattupstate** [comment]
@sidgod ditto
@alexbardas happen to figure this out yourself yet?

**Comment by nathanielc** [comment]
@mattupstate  Yes adding `-config /etc/kapacitor/kapacitor.conf` should fix the issue. In the future this flag won't be necessary. See https://github.com/influxdata/kapacitor/pull/723

**Comment by atbarker** [comment]
@sidgod Did you do anything to the influx and kapacitor config files that is different than the defaults?

**Comment by sidgod** [comment]
Instead of passing -config parameter I am using override config by environment param approach - e.g. -e KAPACITOR_SLACK_STATE-CHANGES-ONLY=true -e KAPACITOR_SLACK_CHANNEL=channel-alerts

This works for me since i am not overriding too much in config. I can see a problem if whole lot of things need to be changed from default config.
