### ISSUE TITLE
error calling "int": cannot convert bool to integer 

### ISSUE THREAD

**Issue by alexbarta** [influxdata/kapacitor#708]
Hi,

I have been playing a bit with kapacitor but now I have some trouble converting true/false condition into integers through eval(lambda: int())  function. Currently I have latest version available on influxdb site kapacitor-0.13.1.x86_64 for centOS .

here my example tick script:
```
 stream
    |from()
        .measurement('source')
    |eval(lambda: int("value" > 0))
        .as('test')
    |influxDBOut()
        .database('dest')
        .measurement('destination')
```

and here the log error output:
<pre><code>
[httpd] 2016/07/12 18:26:28 I! ::1 - - [12/Jul/2016:18:26:28 +0000] PATCH /kapacitor/v1/tasks/test HTTP/1.1 204 0 - KapacitorClient 25efa7d0-485e-11e6-8033-000000000000 9.419409ms
[httpd] 2016/07/12 18:26:30 I! ::1 - - [12/Jul/2016:18:26:30 +0000] GET /kapacitor/v1/tasks?dot-view=attributes&fields=type&fields=status&fields=executing&fields=dbrps&limit=100&offset=0&pattern=&script-format=formatted HTTP/1.1 200 224 - KapacitorClient 276ba665-485e-11e6-8034-000000000000 4.411627ms
[test:eval2] 2016/07/12 18:27:27 E! error calling "int": cannot convert bool to integer
[test:eval2] 2016/07/12 18:27:27 E! name "test" is undefined. Names in scope: value
[edge:test|eval2->influxdb_out3] 2016/07/12 18:27:27 I! aborting c: 1 e: 1
[test:influxdb_out3] 2016/07/12 18:27:27 E! point without fields is unsupported
[edge:test|stream->stream0] 2016/07/12 18:27:27 D! closing c: 1 e: 1
[edge:test|stream0->from1] 2016/07/12 18:27:27 D! closing c: 1 e: 1
[edge:test|from1->eval2] 2016/07/12 18:27:27 D! closing c: 1 e: 1
[edge:test|eval2->influxdb_out3] 2016/07/12 18:27:27 D! closing c: 1 e: 1
[task_master] 2016/07/12 18:27:27 E! Stopped task: test point without fields is unsupported
[task_store] 2016/07/12 18:27:27 E! task test finished with error: point without fields is unsupported
</code></pre>

Any help with this ?

Best regards,

Alessandro

**Comment by nathanielc** [comment]
@alexbarta Converting from bool to int was added in the version `1.0.0-beta1`. Try upgrading and it should work.

**Comment by alexbarta** [comment]
Thanks @nathanielc , I'll check it out .
