### ISSUE TITLE
Error: point without fields is unsupported

### ISSUE THREAD

**Issue by dengliu** [influxdata/kapacitor#717]
Hello, I am following the tutorial in https://docs.influxdata.com/kapacitor/v0.13/nodes/influx_d_b_out_node/
but get "point without fields is unsupported" error.
Is there anything wrong with my tick?
Any help is appreciated.

```
stream

    |from()
        .database('mydb')
        .retentionPolicy('default')
        .measurement('my_measurement')
        .groupBy(*)
    |eval(lambda: "myfield")
        .as('newfield')
    |influxDBOut()
        .database('mydb2')
        .retentionPolicy('default')
        .measurement('my_new_measurement')
        .precision('s')
```

**Comment by nathanielc** [comment]
@dengliu Somehow I missed this issue, my apologies. That error is not complaining about your script but rather that the data that is arriving at Kapacitor doesn't have any fields and as such is invalid.
