### ISSUE TITLE
Deadman trigger error on lambda statement

### ISSUE THREAD

**Issue by bowdenandrew** [influxdata/kapacitor#718]
I am hoping that someone can point me in the right direction for this, I have been working on this problem for a number of days and can't seem to make the deadman trigger adhere to a lambda statement in the 3rd parameter call.

I have only used the pre-built binaries but have tried 0.13.1, the nightly and 1.0.0-beta2 versions with differing errors.  I have written the script as both a batch and a stream and both appear to have the same errors.  I'm really hoping that I'm just doing this wrong but I have exhausted all the permutations that I can think of and I'm not getting very far.

Please note that the deadman switch works without the lambda statement for me.

**batch script:**

```
> var adt = batch
>         |query('SELECT count("messagecount") from "messages"."default"."messagestats"')
>         .period(1m)
>         .every(1m)
>         .groupBy(time(1m))
> 
> adt
>         |deadman(100.0, 1m, lambda: hour("time") > 20)
>                 .id('TESTING')
>                 .log('/tmp/testing.log')
```

**stream script:**

```
> var adt = stream
>         |from()
>                 .database('messages')
>                 .where(lambda: "server"=='JCPP01' AND "domain"=='ADT_PROD01_19100'
>                         AND "messageto" == 'medipath' AND "messagegenerictype" == 'ADT')
>         .groupBy(time(1m))
> adt
>         |deadman(0.0, 1m, lambda: hour("time") >= 20)
>                 .message('''Detection status update for ADT to Medipath between 7am and 5pm.   We {{ if eq .Level "OK" }}HAVE{{ else }}HAVEN'T{{ end }} sent ADT to Medipath in the last 5 minutes''')
>                 .log('/tmp/medipath2.log')
```

In the 0.13.1 version, for both of these scrits the kapacitor log shows:
`[medipath4:alert5] 2016/07/17 22:37:02 E! error evaluating expression: Failed to handle 1 argument: expression returned unexpected type invalid type`

every minute

In both the nightly and the 1.0.0-beta2 versions, the log shows:

`[medipath4:alert5] 2016/07/17 23:00:00 E! error evaluating expression: Failed to handle 1 argument: name "time" is undefined. Names in scope: emitted`

Again, this is also every minute

Please let me know if there is any further information needed.  Any and all help is appreciated.

Andrew

**Comment by bowdenandrew** [comment]
`[temp3:alert5] 2016/07/21 10:51:49 E! error evaluating expression: Failed to handle 1 argument: name "time" is undefined. Names in scope: emitted`

InfluxDB v0.13.0 (git: 0.13 e57fb88a051ee40fd9277094345fbd47bb4783ce)
Kapacitor 1.1.0~n201607170812 (git: master 8fc06032d6a6573d68418927ba84f3e70dfecc98)

**Comment by nathanielc** [comment]
@bowdenandrew Thanks for the details report. I'll take a look at this.

**Comment by bowdenandrew** [comment]
Thanks @nathanielc , I look forward to hearing from you about this.  The kapacitor product is great and it would be excellent to be able to get this threshold alerting working for different times. 

Alternatively, is there any other way that you can think of that I can get the time on an eval node and I can try to setup a .crit alert instead.
