### ISSUE TITLE
Best way to trigger alarm when a number changes

### ISSUE THREAD

**Issue by gpestana** [influxdata/kapacitor#725]
Thanks for putting Kapacitor together, great job! 

I want to trigger an alert when a certain number in a field changes. Lets say that the following query:

`SELECT * from "elasticsearch"."default"."elasticsearch_cluster_health"`

returns a bunch of entries from different ES clusters, each of them with a particular number of nodes (under the field number_of_nodes). The question is how do we trigger an alert when the number_of_nodes field changes in a certain ES cluster?

This should be fairly simple, but I haven't found a non-hackish way to define this alert yet. Thanks for the help!

**Comment by gpestana** [comment]
Go to this solution:

```
var data = stream
    | from()
        .database('elasticsearch')
        .measurement('elasticsearch_cluster_health')
    | groupBy('name', 'number_of_nodes')

data 
	|derivative('number_of_nodes')
		.as('number_of_nodes_diff')
    |alert()
        .id('Elasticsearch ::')
        .message('{{ .Level }} in task \'{{ .TaskName }}\': {{ index .Tags "name" }} number_of_nodes number changed (Derivative: {{ index .Fields "number_of_nodes_diff" }}) ')
        .warn(lambda: "number_of_nodes_diff" > 0)
        .crit(lambda: "number_of_nodes_diff" < 0)
		.pagerDuty()
		.log('/tmp/alarm_es_nodes_stream.log')
```

And still testing it.

**Comment by nathanielc** [comment]
@gpestana I was going to suggest a similar solution. 

Using `difference` would probably make more sense as it doesn't care about elapsed time. But `difference` isn't supported yet.

Also note that alert levels are expected to be subsets of previous levels. See [this](https://influxdata.com/blog/tldr-influxdb-tech-tips-may-19-2016/) for more details but essentially you need to change the warn and crit expressions to:

```
        .warn(lambda: "number_of_nodes_diff" != 0)
        .crit(lambda: "number_of_nodes_diff" < 0)
```

**Comment by nathanielc** [comment]
I have created an issue #827 for adding `difference` support. Closing this issue.
