### ISSUE TITLE
Support multiple lambda filter expressions in WhereNode

### ISSUE THREAD

**Issue by dengliu** [influxdata/kapacitor#733]
It would be very useful to support multiple lambda expressions in WhereNode.
E.g. If I want to divide the value into positive and negative , I can do 
```
data
    |stream ...
    |where(lambda: "value" < 0, lambda: "value" > 0 )
      .as("negativevalue", "positivevalue")
    |eval(lambda: "negativevalue" - 100, lambda: "positivevalue" + 100)
      .as("neg-100", "pos+100")
    |...
```

**Comment by nathanielc** [comment]
What is the value of `negativevalue` when the value is positive? Vice versa,
Since a single value cannot be both positive and negative at the same time are you expecting to join subsequent points into the same point?

Seems like a simple join would work:

```
var nonZero = data
    |stream ...
    |where(lambda:"value" != 0)

var neg =  nonZero
    |where(lambda: "value" < 0)

var pos = nonZero
    |where(lambda: "value" > 0)

pos
    |join(neg)
      .as('positive', 'negative')
      // now you have control over fill, tolerance etc. 
    |eval(lambda: "negative.value" - 100, lambda: "positive.value" + 100)
      .as("neg-100", "pos+100")
    |...
```

I could be completely misunderstanding what you example is trying to do, if so please let me know.

**Comment by ygtzf** [comment]
@nathanielc 
Hi,
   I also think it's a good ideal that support multiple lambda expressions in WhereNode.
In other word, I want to specify muliple condition in a query.
   For example:

   var capacity = stream
   |from()
        .database('collectd')
        .measurement('cluster_value')
        .where(lambda: "type_instance" == 'cluster.free' or "type_instance" == 'cluster.used')      
   ......

    Many variables can be defined to avoid one by one.

    Thanks!

**Comment by nathanielc** [comment]
@ygtzf What you are asking is already possible. You can use the keywords `AND`, `OR` to combine multiple logical expressions.

This is valid:
`.where(lambda: "type_instance" == 'cluster.free' OR "type_instance" == 'cluster.used')`

**Comment by ygtzf** [comment]
@nathanielc  Thank you for such a prompt reply, and sorry for my carelessness.
