### ISSUE TITLE
Does join work on a shiftNode?

### ISSUE THREAD

**Issue by dengliu** [influxdata/kapacitor#738]
Hi @nathanielc 
Does join work on a shiftNode?
When I join a shiftNode, it print out nothing.
 Tick is as below. 
Am I doing it right or this feature is not supported yet.
Thank you!

```
var shiftPeriod = 1m
var pastData = totalFlow
    |shift(shiftPeriod)

var futureData = totalFlow
    |shift(-shiftPeriod)

var replacementData = pastData
    |join(futureData)
      .as('past', 'future')
      .tolerance(1s)
    |log()
```

**Comment by nathanielc** [comment]
Try adding a `.fill()` option to the JoinNode. The first minute of data doesn't have anything to join with so its blocking. Adding a fill should fix that.
