### ISSUE TITLE
Meaning of ClusterID and ServerID

### ISSUE THREAD

**Issue by mrwilby** [influxdata/kapacitor#739]
I read some of the other issues to do with getting Kapacitor to play nice with InfluxDB when using Docker.

One of the recommendations was to pre-create Kapacitor subscriptions in InfluxDB using a deterministic cluster ID in order to be able to control the UDP ports which are used for subscription notifications.

I am curious about the actual intended purpose of these two variables. I see them written on first startup to the file system, and they look to contain generated identifiers.

ServerID - this should presumably be unique per Kapacitor host.

ClusterID - does this imply that it is possible to run multiple Kapacitor instances concurrently for a distributed HA setup? 

I didn't find any docs on this, but please point me at them if I missed them!

Thanks

**Comment by nathanielc** [comment]
@mrwilby You are correct in your understanding of the IDs. While ClusterID is intended to be unique per cluster currently a cluster can only contain a single server. Its simply exists for future needs.

**Comment by mrwilby** [comment]
@nathanielc Thanks Nathaniel, appreciate the quick clarification!
