### ISSUE TITLE
Mutliple instances of alert handler with different global parameters

### ISSUE THREAD

**Issue by phemmer** [influxdata/kapacitor#742]
Example scenario: You have pagerduty and want to send some alerts in as a low urgency, and other alerts as high urgency. You can do this by using separate service keys for each. Now you want to configure kapacitor to use the different service keys. However kapacitor's global config (`kapacitor.conf`) only has support for a single pagerduty service key. Meaning you have to put the service key(s) in every single tick script. This is rather cumbersome, and if you want to swap a key out, you have to modify every single script.

Instead, it would be useful if there was some way to define the keys globally, and use them in the tick scripts.

I don't think the solution should be pagerduty specific either, as other alert handlers have similar limitations.
I can think of 2 solutions.
1. Namespacing. Allow some form of namespacing, or multiple instances of the `[pagerduty]` config block in the `kapacitor.conf` file.
2. Global general purpose variables. Allow specifying global variables in `kapacitor.conf` and then the ability to reference those variables from a tick script.

**Comment by nathanielc** [comment]
I like option 2 initially as it could solve many other issues as well. 

Something like this:

```
|...
|alert()
   .pagerduty()
      .service(config('PD_DEV'))
```

vs 

```
|...
|alert()
   .pagerduty()
      .service(config('PD_PROD'))
```

or similar.

Would and `env` function that grabbed values from the process environment be any better? Or would config be best?

**Comment by nathanielc** [comment]
@phemmer  Have you seen the new alert API system? This should enable you to configure multiple handlers without duplicating lots of config in TICKscripts.

**Comment by kevinbheda** [comment]
@nathanielc can you give an example how to send to different pagerduty accounts using the new alert API system ?
that will be really helpful
