### ISSUE TITLE
Not getting any JSON on stdin using exec with bash

### ISSUE THREAD

**Issue by siryur** [influxdata/kapacitor#761]
According to: https://docs.influxdata.com/kapacitor/v1.0/nodes/alert_node#exec

It's expected to receive on stdin the alert data. But i'm getting nothing ...

My alert of my script:

```
current
|alert()
     .crit(lambda: "current.value" < 80)
     .exec('/home/user/command.sh')
```

My `command.sh` code:

```
#!/bin/bash
echo "${#}" > /home/user/test.test
echo "${1}" >> /home/user/test.test
```

My `test.test` result:
> 0

Am I missing something ?

**Comment by jommgoncalves** [comment]
I have the same problem :\

**Comment by phemmer** [comment]
In shell script, `${1}` is the first argument to the script, not STDIN. If you want to write STDIN to that `test.test` file, you want `cat >> /home/user/test.test`

**Comment by jommgoncalves** [comment]
@phemmer thank you! It works!
