### ISSUE TITLE
Question: how to specify a duration?

### ISSUE THREAD

**Issue by donnut** [influxdata/kapacitor#764]
What should I add to this definition so that the critical alert gets triggered when the 'used_percent' is above 95 % for more than 5 minutes?

Thanks!
```
stream
        |from()
                .measurement('mem')
                .groupBy('host')
        |alert()
                .id('{{index .Tags "host" }} memory utilization')
                .message('{{ .ID }} is {{ .Level }} value:{{ index .Fields "used_percent" }}')
                .crit(lambda: "used_percent" > 95)
                .stateChangesOnly()
                .log('/tmp/alerts.log')
```

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

**Comment by donnut** [comment]
Oke, thanks for letting me know.

**Comment by nathanielc** [comment]
For future readers this conversation continues here https://groups.google.com/forum/?pli=1#!topic/influxdb/cHpELeBAiyU
