### ISSUE TITLE
Anomaly Detection Algorithm

### ISSUE THREAD

**Issue by allen13** [influxdata/kapacitor#78]
The kapacitor article mentioned that anomaly detection is in the plans. I was curious if an algorithm had been chosen yet. 

I am about to work on a custom solution using (nupic htm)[https://github.com/numenta/nupic] with InfluxDB but after the kapacitor announcement (this is really awesome!) I may cancel my work depending on the status of this feature.

I'm particularly interested in how well the chosen algorithm will score on the (NAB)[https://github.com/numenta/NAB]

**Comment by nathanielc** [comment]
@allen13 Thanks for you interest. Long term we would love to have anomaly detection algorithms built it. First we feel it important to just allow each users to define their own custom processing functions. See issue #72. That way each end user can plugin the algorithm they need.  I am working issue #72 now so I would love feedback for how you would like to integrate the NuPIC algorithms.

**Comment by allen13** [comment]
Thanks! I will keep up to date on this.

**Comment by nathanielc** [comment]
@allen13 Have you seen to work with UDFs? You should be able to integrate the numenta algo at this point.
