### ISSUE TITLE
Clarification regarding deadman's switch global configuration

### ISSUE THREAD

**Issue by roribio** [influxdata/kapacitor#788]
Hi,

I am trying to configure a global deadman's switch for all my tasks in the `kapacitor.conf` file. The example configuration file states the following:

```
[deadman] 
  # Configure a deadman's switch
  # Globally configure deadman's switches on all stream tasks.
```
In the doc's reference for `BatchNode`, `Deadman` is listed as a chaining method. Hence I find it odd that a global configuration for it would work only for `stream` tasks and not `batch`.

So my question is: if the settings in the `kapacitor.conf` are truly *ONLY* valid for stream tasks, like it appears to be the case, therefore I should configure deadman's switches individually for each of my batch tasks?

Also, is there a way to blacklist a task from having a deadman's switch when it's configured globally?

Thank you

**Comment by nathanielc** [comment]
@roribio Initially it only worked for stream tasks but that changed. We will update the docs to state that global deadman will work for both stream and batch tasks.

>Also, is there a way to blacklist a task from having a deadman's switch when it's configured globally?

Not currently.

**Comment by roribio** [comment]
Thank you. I appreciate it 👍
