### ISSUE TITLE
[UDF] Lack of doc info using lambda on UDF 

### ISSUE THREAD

**Issue by siryur** [influxdata/kapacitor#789]
I'm using UDF, but I want the business logic to be defined on the tickscript.
So, what I'm trying to do is, define lambda exp on the tick script and then handle the values based on that lambda expression.

Tickscript ex:
```
@megaUDF()
        .comparable(lambda: "value" > 10)
        ...(more args here)
```

I want to return a bool if this lambda is true...
But I'm not understanding what should I do for this on the UDF side.
Problems:

- [ ] Type of Value. On `func Info()` what is the `{ValueTypes: []udf.ValueType{udf.ValueType_?}},` for the `comparable` option;
- [ ] How can I use/test the lambda only on the `func Point(p *udf.Point)` ?

**Comment by nathanielc** [comment]
The properties on a UDF are only for initialization of the UDF and are not evaluated for each point.

Use and eval node to evaluate the expression before passing the point to the UDF.

```
|eval(lambda: "value" > 10)
     .as('comparable')
     .keep()
@megaUDF()
        // Now inside the UDF code look at the value of the `comparable` field
        ...(more args here)
```

**Comment by siryur** [comment]
thanks :)
