### ISSUE TITLE
Kapacitor not running

### ISSUE THREAD

**Issue by jainbhavuk630** [influxdata/kapacitor#801]
I am trying to set up Kapacitor on my localhost (Mac OS-X). I am following the steps as mentioned in the following link: `https://docs.influxdata.com/kapacitor/v0.13/introduction/installation/`

My InfluxDB and my telegraf are running and they are working properly as well. I can also see the data getting collected in InfluxDB being sent by Telegraf. However, when I start up Kapacitor, it gives me the following messages and I am not sure if this is the way Kapacitor is meant to function. 

    '##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
     ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
     ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
     #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
     ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
     ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
     ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
    ..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
    
    2016/08/10 08:55:51 Using configuration at: kapacitor.conf
    [run] 2016/08/10 08:55:51 I! Kapacitor starting, version 0.13.1, branch unknown, commit ae7dde3aa467c46c06a5a2058a80c6125203f599
    [run] 2016/08/10 08:55:51 I! Go version go1.6.2, GOMAXPROCS set to 8
    [srv] 2016/08/10 08:55:51 I! Kapacitor hostname: localhost
    [srv] 2016/08/10 08:55:51 I! ClusterID: 616a5d39-8407-4e0d-9896-bd1c61e0456d ServerID: 40047d04-5f6f-44cb-a696-106ec20b4d75
    [task_master] 2016/08/10 08:55:51 I! opened
    [influxdb] 2016/08/10 08:55:51 I! linking subscriptions
    [udp:mydb.default] 2016/08/10 08:55:51 I! Started listening on UDP: 127.0.0.1:52522
    [influxdb] 2016/08/10 08:55:51 I! started UDP listener for mydb default
    [udp:kapacitor_example.default] 2016/08/10 08:55:51 I! Started listening on UDP: 127.0.0.1:52523
    [influxdb] 2016/08/10 08:55:51 I! started UDP listener for kapacitor_example default
    [udp:_internal.monitor] 2016/08/10 08:55:51 I! Started listening on UDP: 127.0.0.1:52520
    [influxdb] 2016/08/10 08:55:51 I! started UDP listener for _internal monitor
    [udp:telegraf.default] 2016/08/10 08:55:51 I! Started listening on UDP: 127.0.0.1:52521
    [influxdb] 2016/08/10 08:55:51 I! started UDP listener for telegraf default
    [task_store] 2016/08/10 08:55:51 W! could not open old boltd for task_store. Not performing migration. Remove the `task_store.dir` configuration to disable migration.
    [stats] 2016/08/10 08:55:51 I! opened service
    [httpd] 2016/08/10 08:55:54 I! Starting HTTP service
    [httpd] 2016/08/10 08:55:54 I! Authentication enabled: false
    [udp:mydb.default] 2016/08/10 08:55:54 I! Service closed
    [udp:kapacitor_example.default] 2016/08/10 08:55:54 I! Service closed
    [udp:_internal.monitor] 2016/08/10 08:55:54 I! Service closed
    [udp:telegraf.default] 2016/08/10 08:55:54 I! Service closed
    [stats] 2016/08/10 08:55:54 I! closed service
    [httpd] 2016/08/10 08:55:54 I! Closed HTTP service
    [task_master] 2016/08/10 08:55:54 I! closed
    [run] 2016/08/10 08:55:54 E! open server: open service *httpd.Service: listen tcp :9092: bind: address already in use
    run: open server: open service *httpd.Service: listen tcp :9092: bind: address already in use
 
I can also post my config file for Kapacitor, but I think it's correctly configured. I am asking this, because when I proceed to configure Kapacitor with Alerta, it doesn't work properly, even though Alerta is working fine in standalone. 

Is there something that I am missing?

**Comment by nathanielc** [comment]
> `open service *httpd.Service: listen tcp :9092: bind: address already in use` 

What is already listening on that port? Do you have a rouge kapacitor process still running or something else?

**Comment by jainbhavuk630** [comment]
So, I tried seeing which service is already running on that port. Here is the OP:

COMMAND    PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
kapacitor      2492  <username>           15u    IPv6   0x7cca0637eae090df      0t0  TCP *:XmlIpcRegSvc (LISTEN)

I try killing this kapacitor process using the kill command. I even tried stopping it using the Activity Monitor in my mac, but it continues each time with a different PID. It doesn't seem to stop. How do  I do it? 

I even tried seeing my influxDB logs after this, and it shows connection refused constantly.

**Comment by nathanielc** [comment]
>  but it continues each time with a different PID

My guess is you have some service management system that keeps turning on the kapacitord process.

**Comment by jainbhavuk630** [comment]
Probably this might be the issue. Is there any way then I can stop it and maybe restart it with its correct configuration? 
Also, in the installation guide, it mentions the way to start kapacitor using the config file. Is there any way to stop kapacitor too? Like maybe, sudo service kapacitor stop? Something like this? Other than manually killing the kapacitor process.

**Comment by jainbhavuk630** [comment]
Hi

I have been able to terminate the rogue kapacitor process, and I am now able to run kapacitor properly. My influxdb is set up correctly, my kapacitor starts up properly, I am making the default configuration file for kapacitor using: `kapacitord config > kapacitor.conf`. 
Following the guide at the link, "https://docs.influxdata.com/kapacitor/v0.13/introduction/getting_started/", I make the exact same cpu_alert.tick, but, when I run it, it doesn't capture any data. On seeing the logs for InfluxDB, I see the message for connection refused. 

[subscriber] 2016/08/11 10:26:00 write udp 127.0.0.1:61333->127.0.0.1:56737: write: connection refused
[subscriber] 2016/08/11 10:26:00 write udp 127.0.0.1:55673->127.0.0.1:64625: write: connection refused
[subscriber] 2016/08/11 10:26:04 write udp 127.0.0.1:52245->127.0.0.1:49356: write: connection refused
[subscriber] 2016/08/11 10:26:04 write udp 127.0.0.1:59222->127.0.0.1:56736: write: connection refused
[subscriber] 2016/08/11 10:26:04 write udp 127.0.0.1:60351->127.0.0.1:64764: write: connection refused
[subscriber] 2016/08/11 10:26:04 write udp 127.0.0.1:49829->127.0.0.1:62521: write: connection refused
[subscriber] 2016/08/11 10:26:04 write udp 127.0.0.1:54589->127.0.0.1:64624: write: connection refused
[subscriber] 2016/08/11 10:26:10 write udp 127.0.0.1:64013->127.0.0.1:64625: write: connection refused
[subscriber] 2016/08/11 10:26:10 write udp 127.0.0.1:62453->127.0.0.1:64765: write: connection refused
[httpd] 2016/08/11 10:26:10 ::1 - - [11/Aug/2016:10:26:10 +0530] POST /write?consistency=any&db=telegraf&precision=s&rp=default HTTP/1.1 204 0 - InfluxDBClient ebce9e0f-5f7f-11e6-84d1-000000000000 2.87901ms

Is there something that I have to do?

**Comment by nathanielc** [comment]
@jainbhavuk630 Check your firewall networks etc to make sure the UDP ports are open. Alternatively since it seems that you are just getting started I would recommend using the latest 1.0 beta release as it has support for HTTP based subscriptions that are much easier to use and configure, as well as many other improvements bug fixes.

**Comment by jainbhavuk630** [comment]
Alright, thanks. I think this is resolved.
