### ISSUE TITLE
Can not send email

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [influxdata/kapacitor#805]
- the kapacitor conf
 
  [smtp]
  enabled = true
  host = "smtp.exmail.qq.com"
  port = 25
  username = "chenfan@zbj.com"
  password = "xxxxxx"
  from = "chenfan@zbj.com"
  to = ["951982186@qq.com"]
  #no-verify = false
  global = true
  state-changes-only = true
  #idle-timeout = "30s"

- the log
  [cpu_alert:alert2] 2016/08/11 09:59:30 E! smtp service not enabled, cannot send email.

but the stmp can send mail by mailx ,why?

**Comment by nathanielc** [comment]
@Chentongxuedefanhua Can you share the logs from Kapacitor during startup with debug logging turned on? Thanks

**Comment by Chentongxuedefanhua** [comment]
@nathanielc Thank you for your reply. it works with the same conf..... maybe the smtp was worng yesterday
