### ISSUE TITLE
Alert isn't effective when update task with HTTP API

### ISSUE THREAD

**Issue by ygtzf** [influxdata/kapacitor#806]
Hi,

I found a issue when using kapacitor HTTP API:
*  It can take effect that disable or enable a task use 'PATCH' to a task.
*  But, when I modify a threshold of a level function (info(...)). the tick script is modified correct when I check the content use command “kapacitor show {task name}”, but not take effect in fact.
*  After I modify the script, it's correct that I disable the task use 'PATCH' and then enable.
*  It's correct modify use command “kapacitor define {tick name}”

   For example:
   The original tick script is:
```
stream
    |from()
        .database('physics')
        .measurement('system_load')
        .where(lambda: "host" == 'dev1' AND "type_instance" == 'load.1m')
    |alert()
        .message('this is alert:{.ID}/{.Level}/{.Time}')
        .info(lambda: "value" > float(1))
        .stateChangesOnly()
        .log('/tmp/load-alert.log')
```
    And I want to modify the threshold from 1 to 1.5:
        .info(lambda: "value" > float(1.5))

Thanks!

**Comment by nathanielc** [comment]
@ygtzf You are correct, after modifying a task TICKscript you must disable/enable the task via the API as well, for the task to be reloaded and use the new TICKscript. The command line utility `kapacitor` is doing this for you.

**Comment by arushigangrade** [comment]
I have a similar question. What happens to the already active alerts, which were triggered before the task was modified.? Will they still be there or will they go away.?
