### ISSUE TITLE
UDF protobuf problem

### ISSUE THREAD

**Issue by alparslanuysal** [influxdata/kapacitor#809]
I have downloaded all deps that is required for UDF and It worked well.However, when i reboot the pc , I get this error "udf.Service : failed to load process info for "geoSum" write error: write |1: broken pipe"

These are kapacitor logs:
[task_master] 2016/08/12 17:16:03 I! opened
[udf] 2016/08/12 17:16:03 I!P Starting GeoSumm
[udf] 2016/08/12 17:16:03 I!P Finished GeoSumm
[udf] 2016/08/12 17:16:04 D! loaded UDF info "geoSum"
[srv] 2016/08/12 17:16:04 D! opened service: *udf.Service
[srv] 2016/08/12 17:16:04 D! opening service: *deadman.Service
[srv] 2016/08/12 17:16:04 D! opened service: *deadman.Service
[srv] 2016/08/12 17:16:04 D! opening service: *influxdb.Service
[influxdb] 2016/08/12 17:16:04 I! linking subscriptions
[udp:telegraf.default] 2016/08/12 17:16:04 I! Started listening on UDP: 127.0.0.1:60227
[influxdb] 2016/08/12 17:16:04 I! started UDP listener for telegraf default
[udp:_internal.monitor] 2016/08/12 17:16:04 I! Started listening on UDP: 127.0.0.1:55088
[influxdb] 2016/08/12 17:16:04 I! started UDP listener for _internal monitor
[udp:scattolini.default] 2016/08/12 17:16:04 I! Started listening on UDP: 127.0.0.1:51245
[influxdb] 2016/08/12 17:16:04 I! started UDP listener for scattolini default
[srv] 2016/08/12 17:16:04 D! opened service: *influxdb.Service
[srv] 2016/08/12 17:16:04 D! opening service: *storage.Service
[srv] 2016/08/12 17:16:04 D! opened service: *storage.Service
[srv] 2016/08/12 17:16:04 D! opening service: *task_store.Service
[task_store] 2016/08/12 17:16:04 W! could not open old boltd for task_store. Not performing migration. Remove the `task_store.dir` configuration to disable migration.
[srv] 2016/08/12 17:16:04 D! opened service: *task_store.Service
[srv] 2016/08/12 17:16:04 D! opening service: *replay.Service
[udf] 2016/08/12 17:16:04 I!P Traceback (most recent call last):
[udf] 2016/08/12 17:16:04 I!P   File "/home/ubuntu/udf/geo.py", line 2, in <module>
[udf] 2016/08/12 17:16:04 I!P     from kapacitor.udf.agent import Agent, Handler
[udf] 2016/08/12 17:16:04 I!P   File "/home/ubuntu/udf/kapacitor/udf/agent/py/kapacitor/udf/agent.py", line 7, in <module>
[udf] 2016/08/12 17:16:04 I!P     import udf_pb2
[udf] 2016/08/12 17:16:04 I!P   File "/home/ubuntu/udf/kapacitor/udf/agent/py/kapacitor/udf/udf_pb2.py", line 7, in <module>
[udf] 2016/08/12 17:16:04 I!P     from google.protobuf import descriptor as _descriptor
[udf] 2016/08/12 17:16:04 I!P   File "build/bdist.linux-x86_64/egg/google/protobuf/descriptor.py", line 37, in <module>
[udf] 2016/08/12 17:16:04 I!P ImportError: No module named six
[srv] 2016/08/12 17:16:04 D! opened service: *replay.Service
[srv] 2016/08/12 17:16:04 D! opening service: *stats.Service
[stats] 2016/08/12 17:16:04 I! opened service
[srv] 2016/08/12 17:16:04 D! opened service: *stats.Service
[srv] 2016/08/12 17:16:04 D! opening service: *reporting.Service
[srv] 2016/08/12 17:16:05 D! opened service: *reporting.Service
[srv] 2016/08/12 17:16:05 D! opening service: *httpd.Service
[httpd] 2016/08/12 17:16:05 I! Starting HTTP service
[httpd] 2016/08/12 17:16:05 I! Authentication enabled: false
[httpd] 2016/08/12 17:16:05 I! Listening on HTTP: [::]:9092
[srv] 2016/08/12 17:16:05 D! opened service: *httpd.Service
[run] 2016/08/12 17:16:05 I! Listening for signals
[srv] 2016/08/12 17:16:08 E! error closing service *stats.Service: error closing stats service: service not open
[httpd] 2016/08/12 17:16:08 I! Closed HTTP service
[task_master] 2016/08/12 17:16:08 I! closed
[run] 2016/08/12 17:16:08 E! open server: open service *udf.Service: failed to load process info for "geoSum": write error: write |1: broken pipe
[run] 2016/08/12 17:16:08 I! Kapacitor starting, version 0.13.1, branch master, commit ae7dde3aa467c46c06a5a2058a80c6125203f599
[run] 2016/08/12 17:16:08 I! Go version go1.6.2, GOMAXPROCS set to 2
[srv] 2016/08/12 17:16:08 I! Kapacitor hostname: localhost

**Comment by nathanielc** [comment]
Note sure how but it looks like your python env changed after the reboot.

The error that is important is `ImportError: No module named six` which is part of the `geo.py` output. Try running geo.py manually to see if you can fix the python env issues.

**Comment by alparslanuysal** [comment]
After reboot, These two kapacitor process runs

kapacit+  4373  3.0  0.6 131424 13056 ?        Ssl  12:09   0:00 /usr/bin/kapacitord -config /etc/kapacitor/kapacitor.conf
kapacit+  4379 57.0  0.0      0     0 ?        Z    12:09   0:00 [python2] <defunct>

I killed these processes and start new process with this command
"sudo kapacitor -config kapacitor.conf -log-level debug" and it worked.
