### ISSUE TITLE
how to wirte a tick to alert the cpu useage

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [influxdata/kapacitor#817]
eg:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" <  70)
        .email()
it is not what i want.
i want to get the alert when useage_idle>70 last for 2 min,how ?

**Comment by phemmer** [comment]
See #764

**Comment by Chentongxuedefanhua** [comment]
@phemmer thanks a lot
