### ISSUE TITLE
I got 301 code when I define task use http api

### ISSUE THREAD

**Issue by tianqiangly** [influxdata/kapacitor#819]
I want to use kapacitor http api, but when I define task, the server response 301, i have no ideal,please help me.
the attach include tcpdump

![1](https://cloud.githubusercontent.com/assets/9765074/17769516/94a9ccaa-656b-11e6-839f-ea7bbc180728.jpg)

[acap.zip](https://github.com/influxdata/kapacitor/files/424554/acap.zip)

**Comment by nathanielc** [comment]
@tianqiangly 301 is a redirect, please follow all redirects when using the API. The redirect is being issued because you are using a path with two slashes at the begining ``//kapacitor/v1/tasks/` where is should only have one slash.
