### ISSUE TITLE
Update docs for creating task that is enabled to use correct POST path without ID.

### ISSUE THREAD

**Issue by superbool** [influxdata/kapacitor#820]
![image](https://cloud.githubusercontent.com/assets/8575470/17802039/5b297bd2-6620-11e6-8c0d-e7686dc6533e.png)
I use this method to create an task ,but it return:    {"error":"Not Found"}
Is there something wrong?

**Comment by superbool** [comment]
I know how to solve it  now。
the task id must be at the json body as create a normal task.
so please update the docs [](https://docs.influxdata.com/kapacitor/v0.13/api/api/#define-task).

but I have another question:
I have many fields in influxdb ,so I want to monitor some of them to alert. But I have to write tick scripts like this:
the first example all the fields alert in one task:
yaoguang_push.tick
```
var yaoguang_push = stream
    |from()
        .database('yaoguang')
        .retentionPolicy('default')
        .measurement('yaoguang_push')
        .groupBy('host')

yaoguang_push
    |alert()
        .id('yaoguang_push {{ index .Tags "host" }} ')
        .message('{{ .ID }} is {{ .Level }} dao_get_company_by_id_count:{{ index .Fields "dao_get_company_by_id_count" }}')
        .crit(lambda: "dao_get_company_by_id_count" < 10)
        .log('/tmp/alerts.log')
        .email('kefei@baixing.com')
        .talk()

yaoguang_push
    |alert()
        .id('yaoguang_push {{ index .Tags "host" }}')
        .message('{{ .ID }} is {{ .Level }} dao_get_company_by_id_time:{{ index .Fields "dao_get_company_by_id_time" }}')
        .crit(lambda: "dao_get_company_by_id_time" > 100)
        .log('/tmp/alerts.log')
        .email('kefei@baixing.com')
        .talk()
```
the second example write alert in different task,each task has only one field,
yaoguang_push_1.tick yaoguang_push_2.tick yaoguang_push_3.tick and so on:
```
var yaoguang_push = stream
    |from()
        .database('yaoguang')
        .retentionPolicy('default')
        .measurement('yaoguang_push')
        .groupBy('host')

yaoguang_push
    |alert()
        .id('yaoguang_push {{ index .Tags "host" }} ')
        .message('{{ .ID }} is {{ .Level }} dao_get_company_by_id_count:{{ index .Fields "dao_get_company_by_id_count" }}')
        .crit(lambda: "dao_get_company_by_id_count" < 10)
        .log('/tmp/alerts.log')
        .email('kefei@baixing.com')
        .talk()
```

Which way is better ? the first example seems simple,but when i want to update or delete some alert,its very complicated，the second one effect the Kapacitor performance if there are many tasks?

And How to Send Email to different adress, **.email('kefei@baixing.com,a@a.com,b@a.com')** doesn't work,it only send to the first email adress.

Hope you give me answer soon,thank you.

**Comment by nathanielc** [comment]
@superbool There are lots of different issues within this same issue. Can you create a separate issue for the email issue, and the multiple fields issue? Thanks for pointing out the docs are incorrect for creating a new task. We use this issue to track that fix.
