### ISSUE TITLE
Kapacitor recording is not working

### ISSUE THREAD

**Issue by sukantasaha** [influxdata/kapacitor#824]
Hi,

I am running influxdb and kapacitor with 0.13.0 version , both are running fine, since there is already data in influxdb (we push metrics data using our script ) , I am not using Telegraph.

I created task cpu_alert.tick, here I am using influxdb called sensu

stream
        |from()
           .database('sensu')
           .retentionPolicy('default')
           .measurement('cpu_idle')
           .where(lambda: "host" == 'qa-apple-red-server-1c')
        |alert()
                .warn(lambda: "value" < 30)
                .crit(lambda: "value" < 10)
                .log('/tmp/high_cpu.log')

And its enabled

/mnt1/kapacitor-0.13.1-1/usr/bin/kapacitor show cpu_alert
ID: cpu_alert
Error:
Type: stream
Status: enabled
Executing: true
Created: 22 Aug 16 16:20 UTC
Modified: 22 Aug 16 16:20 UTC
LastEnabled: 22 Aug 16 16:20 UTC
Databases Retention Policies: ["seusu"."default"]
TICKscript:
stream
    |from()
        .database('sensu')
        .retentionPolicy('default')
        .measurement('cpu_idle')
        .where(lambda: "host" == 'qa-apple-red-server-1c')
    |alert()
        .warn(lambda: "value" < 30)
        .crit(lambda: "value" < 10)
        .log('/tmp/high_cpu.log')

DOT:
digraph cpu_alert {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="0"];

from1 [avg_exec_time_ns="0" ];
from1 -> alert2 [processed="0"];

alert2 [alerts_triggered="0" avg_exec_time_ns="0" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}

But some how recording is not collecting data

/mnt1/kapacitor-0.13.1-1/usr/bin/kapacitor record stream -task cpu_alert -duration 20s

 /mnt1/kapacitor-0.13.1-1/usr/bin/kapacitor list recordings
ID                                      Type    Status    Size      Date
6ff0ecfc-2a7a-487c-a564-6d0e9e1a31b2    stream  running   0 B       23 Aug 16 09:43 UTC

When I run the recording command it just stuck, I had to press control+c , but in the kapacitor log I see something like this

[httpd] 2016/08/23 17:40:16 I! 127.0.0.1 - - [23/Aug/2016:17:40:15 +0000] POST /kapacitor/v1/recordings/stream HTTP/1.1 201 211 - KapacitorClient a6ec6b95-6958-11e6-80fd-000000000000 11.631336ms
[httpd] 2016/08/23 17:40:16 I! 127.0.0.1 - - [23/Aug/2016:17:40:16 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a73aba79-6958-11e6-80fe-000000000000 611.876µs
[httpd] 2016/08/23 17:40:17 I! 127.0.0.1 - - [23/Aug/2016:17:40:17 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a7874960-6958-11e6-80ff-000000000000 1.913226ms
[httpd] 2016/08/23 17:40:17 I! 127.0.0.1 - - [23/Aug/2016:17:40:17 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a7d403d8-6958-11e6-8100-000000000000 549.514µs
[httpd] 2016/08/23 17:40:18 I! 127.0.0.1 - - [23/Aug/2016:17:40:18 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a8208e72-6958-11e6-8101-000000000000 883.042µs
[httpd] 2016/08/23 17:40:18 I! 127.0.0.1 - - [23/Aug/2016:17:40:18 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a86d2524-6958-11e6-8102-000000000000 2.164506ms
[httpd] 2016/08/23 17:40:19 I! 127.0.0.1 - - [23/Aug/2016:17:40:19 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a8b9edcb-6958-11e6-8103-000000000000 685.234µs
[httpd] 2016/08/23 17:40:19 I! 127.0.0.1 - - [23/Aug/2016:17:40:19 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a9067dd8-6958-11e6-8104-000000000000 523.438µs
[httpd] 2016/08/23 17:40:20 I! 127.0.0.1 - - [23/Aug/2016:17:40:20 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a95302ec-6958-11e6-8105-000000000000 1.725304ms
[httpd] 2016/08/23 17:40:20 I! 127.0.0.1 - - [23/Aug/2016:17:40:20 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a99fbbb6-6958-11e6-8106-000000000000 532.051µs
[httpd] 2016/08/23 17:40:21 I! 127.0.0.1 - - [23/Aug/2016:17:40:21 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient a9ec3f00-6958-11e6-8107-000000000000 527.107µs
[httpd] 2016/08/23 17:40:21 I! 127.0.0.1 - - [23/Aug/2016:17:40:21 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient aa38c431-6958-11e6-8108-000000000000 1.723033ms
[httpd] 2016/08/23 17:40:22 I! 127.0.0.1 - - [23/Aug/2016:17:40:22 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient aa85877b-6958-11e6-8109-000000000000 536.888µs
[httpd] 2016/08/23 17:40:22 I! 127.0.0.1 - - [23/Aug/2016:17:40:22 +0000] GET /kapacitor/v1/recordings/045466ff-83e4-4681-b4a2-4fb40e9d4a32 HTTP/1.1 202 211 - KapacitorClient aad20d34-6958-11e6-810a-000000000000 533.925µs
[htt

Here is kapacitor config file

hostname = "localhost"
data_dir = "/data/kapacitor/data"

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"

[logging]
    file = "/mnt1/logs/kapacitor/kapacitor.log"
    level = "DEBUG"

[replay]
  dir = "/data/kapacitor/replay"

[task]
  dir = "/data/kapacitor/tasks"
  snapshot-interval = "60s"

[storage]
  boltdb = "/data/kapacitor/kapacitor.db"

[deadman]
  global = false
  threshold = 0.0
  interval = "10s"
  id = "node 'NODE_NAME' in task '{{ .TaskName }}'"
  message = "{{ .ID }} is {{ if eq .Level \"OK\" }}alive{{ else }}dead{{ end }}: {{ index .Fields \"collected\" | printf \"%0.3f\" }} points/INTERVAL."

[[influxdb]]
  enabled = true
  default = true
  name = "sensu"
  urls = ["http://localhost:8086"]
  username = ""
  password = ""
  timeout = 0

  insecure-skip-verify = false

  udp-buffer = 1000
  udp-read-buffer = 0

  [influxdb.subscriptions]
    sensu = [ "default" ]
  [influxdb.excluded-subscriptions]
    _internal = [ "default" ]

[smtp]
  enabled = false
  host = "localhost"
  port = 25
  username = ""
  password = ""
  from = ""

  no-verify = false
  idle-timeout = "30s"

  global = false
  state-changes-only = false

[opsgenie]
    enabled = false
    api-key = ""
    url = "https://api.opsgenie.com/v1/json/alert"
    recovery_url = "https://api.opsgenie.com/v1/json/alert/note"
    global = false

[victorops]
  enabled = false
  api-key = ""
  routing-key = ""
  url = "https://alert.victorops.com/integrations/generic/20131114/alert"
  global = false

[pagerduty]
  enabled = false
  service-key = ""
  url = "https://events.pagerduty.com/generic/2010-04-15/create_event.json"
  global = false

[slack]
  enabled = false
  url = ""
  channel = ""
  global = false
  state-changes-only = false

[hipchat]
  enabled = false
  url = "https://subdomain.hipchat.com/v2/room"
  room = ""
  token = ""
  global = false
  state-changes-only = false

[alerta]
  enabled = false
  url = ""
  token = ""
  environment = ""
  origin = "kapacitor"

[sensu]
  enabled = false
  addr = "sensu-client:3030"
  source = "Kapacitor"

[reporting]
  enabled = true
  url = "https://usage.influxdata.com"

[stats]
  enabled = true
  stats-interval = "10s"
  database = "_kapacitor"
  retention-policy= "default"

[udf]
[udf.functions]

[talk]
  enabled = false
  url = "https://jianliao.com/v2/services/webhook/uuid"
  author_name = "Kapacitor"

[collectd]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "10s"
  typesdb = "/usr/share/collectd/types.db"

[opentsdb]
  enabled = false
  bind-address = ":4242"
  database = "opentsdb"
  retention-policy = ""
  consistency-level = "one"
  tls-enabled = false
  certificate = "/etc/ssl/influxdb.pem"
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"

Any help would be appreciated

Thanks
Sukanta

**Comment by nathanielc** [comment]
Looks like for whatever reason Kapacitor isn't receiving any data from InfluxDB, which is causing the recording to not work since there is nothing to record.

**Comment by sukantasaha** [comment]
Any suggestion how do I debug it ?

**Comment by sidgod** [comment]
I had seen this issue when i first started using Kapacitor. Assuming you've deployed kapacitor on linux box / docker, as a first step you can see if data is being forwarded for your expected points on UDP channel opened by Kapacitor. You can run tcpdump to verify if points are received on Kapacitor box on specified UDP port as per Kapacitor -> InfluxDB subscription. I believe Kapcitor also states UDP port for subscription in its logs.

**Comment by sukantasaha** [comment]
I run this
nc -zu localhost 8090
Connection to localhost 8090 port [udp/*] succeeded!

**Comment by sukantasaha** [comment]
When I start kapacitor In the logs I see followings

[run] 2016/08/24 06:51:51 I! Kapacitor starting, version 0.13.1, branch master, commit ae7dde3aa467c46c06a5a2058a80c6125203f599
[run] 2016/08/24 06:51:51 I! Go version go1.6.2, GOMAXPROCS set to 4
[srv] 2016/08/24 06:51:51 I! Kapacitor hostname: localhost
[srv] 2016/08/24 06:51:51 I! ClusterID: 4368192f-b8df-4f07-b971-843ca8387d09 ServerID: 252b1434-c168-41a9-b9cf-04197e35d5a2
[task_master] 2016/08/24 06:51:51 I! opened
[srv] 2016/08/24 06:51:51 D! opening service: *udf.Service
[srv] 2016/08/24 06:51:51 D! opened service: *udf.Service
[srv] 2016/08/24 06:51:51 D! opening service: *deadman.Service
[srv] 2016/08/24 06:51:51 D! opened service: *deadman.Service
[srv] 2016/08/24 06:51:51 D! opening service: *influxdb.Service
[influxdb] 2016/08/24 06:51:51 I! linking subscriptions
[udp:sensu.default] 2016/08/24 06:51:51 I! Started listening on UDP: 127.0.0.1:45164
[influxdb] 2016/08/24 06:51:51 I! started UDP listener for sensu default
[srv] 2016/08/24 06:51:51 D! opened service: *influxdb.Service
[srv] 2016/08/24 06:51:51 D! opening service: *storage.Service
[srv] 2016/08/24 06:51:51 D! opened service: *storage.Service
[srv] 2016/08/24 06:51:51 D! opening service: *task_store.Service
[task_store] 2016/08/24 06:51:51 W! could not open old boltd for task_store. Not performing migration. Remove the `task_store.dir` configuration to disable migration.
[task_store] 2016/08/24 06:51:51 D! starting enabled task on startup cpu_alert
[task_master] 2016/08/24 06:51:51 D! Starting task: cpu_alert
[task_master] 2016/08/24 06:51:51 I! Started task: cpu_alert
[task_master] 2016/08/24 06:51:51 D! digraph cpu_alert {
stream0 -> from1;
from1 -> alert2;
}
[task_store] 2016/08/24 06:51:51 D! started task during startup cpu_alert
[srv] 2016/08/24 06:51:51 D! opened service: *task_store.Service
[srv] 2016/08/24 06:51:51 D! opening service: *replay.Service
[replay] 2016/08/24 06:51:51 D! skipping recording 045466ff-83e4-4681-b4a2-4fb40e9d4a32, metadata already migrated
[srv] 2016/08/24 06:51:51 D! opened service: *replay.Service
[srv] 2016/08/24 06:51:51 D! opening service: *stats.Service
[stats] 2016/08/24 06:51:51 I! opened service
[srv] 2016/08/24 06:51:51 D! opened service: *stats.Service
[srv] 2016/08/24 06:51:51 D! opening service: *reporting.Service
[srv] 2016/08/24 06:51:51 D! opened service: *reporting.Service
[srv] 2016/08/24 06:51:51 D! opening service: *httpd.Service
[httpd] 2016/08/24 06:51:51 I! Starting HTTP service
[httpd] 2016/08/24 06:51:51 I! Authentication enabled: false
[httpd] 2016/08/24 06:51:51 I! Listening on HTTP: [::]:9092
[srv] 2016/08/24 06:51:51 D! opened service: *httpd.Service
[run] 2016/08/24 06:51:51 I! Listening for signals

**Comment by gavinzhou** [comment]
I try  tutorial
https://docs.influxdata.com/kapacitor/v1.0/introduction/getting_started/

size is 0B

**Comment by pbrumm** [comment]
I had a similar issue.  I set the following setting to udp and data started to flow
subscription-protocol = "udp"

**Comment by sukantasaha** [comment]
Thank You So Much , I will try this

**Comment by cardonator** [comment]
If you're using docker and got here, it very likely means your InfluxDB can't communicate with your Kapacitor container. Using http for subscriptions means that events will be pushed to Kapacitor from InfluxDB. Make sure you have a hosts entry or have the two containers on the same docker network.

**Comment by docmerlin** [comment]
I'm going to close this issue, I assume it has been taken care of.
