### ISSUE TITLE
Which alert tick script is better?

### ISSUE THREAD

**Issue by superbool** [influxdata/kapacitor#836]
I have many fields in influxdb ,so I want to monitor some of them to alert. But I have to write tick scripts like this:
the first example all the fields alert in one task:
yaoguang_push.tick
```
var yaoguang_push = stream
    |from()
        .database('yaoguang')
        .retentionPolicy('default')
        .measurement('yaoguang_push')
        .groupBy('host')

yaoguang_push
    |alert()
        .id('yaoguang_push {{ index .Tags "host" }} ')
        .message('{{ .ID }} is {{ .Level }} dao_get_company_by_id_count:{{ index .Fields "dao_get_company_by_id_count" }}')
        .crit(lambda: "dao_get_company_by_id_count" < 10)
        .log('/tmp/alerts.log')
        .email('kefei@baixing.com')
        .talk()

yaoguang_push
    |alert()
        .id('yaoguang_push {{ index .Tags "host" }}')
        .message('{{ .ID }} is {{ .Level }} dao_get_company_by_id_time:{{ index .Fields "dao_get_company_by_id_time" }}')
        .crit(lambda: "dao_get_company_by_id_time" > 100)
        .log('/tmp/alerts.log')
        .email('kefei@baixing.com')
        .talk()
....
and so on
```
the second example write alert in different task,each task has only one field,
yaoguang_push_1.tick yaoguang_push_2.tick yaoguang_push_3.tick and so on:
```
var yaoguang_push = stream
    |from()
        .database('yaoguang')
        .retentionPolicy('default')
        .measurement('yaoguang_push')
        .groupBy('host')

yaoguang_push
    |alert()
        .id('yaoguang_push {{ index .Tags "host" }} ')
        .message('{{ .ID }} is {{ .Level }} dao_get_company_by_id_count:{{ index .Fields "dao_get_company_by_id_count" }}')
        .crit(lambda: "dao_get_company_by_id_count" < 10)
        .log('/tmp/alerts.log')
        .email('kefei@baixing.com')
        .talk()
```

Which way is better ? the first example seems simple,but when I want to update or delete some alert,its very complicated，the second one effect the Kapacitor performance if there are many tasks?

**Comment by nathanielc** [comment]
@superbool Have you seen the template tasks in the 1.0 version? It allows you to create a single template and then create multiple tasks from that template. Then updates to the template will update all tasks using that template. Here are some docs https://docs.influxdata.com/kapacitor/v1.0/examples/template_tasks/

**Comment by superbool** [comment]
OK, I am using the old version ,I will use it when the new version update.
