### ISSUE TITLE
Kapacitor and InfluxDB cann't work different manchine?

### ISSUE THREAD

**Issue by superbool** [influxdata/kapacitor#838]
My InfluxDB works on server A and my Kapacitor works on Server B,but I cann't get the alert,and the InfluxDB always log:
```
[subscriber] 2016/08/25 17:35:03 write udp 127.0.0.1:59634->127.0.0.1:47051: write: connection refused
[subscriber] 2016/08/25 17:35:13 write udp 127.0.0.1:53807->127.0.0.1:47051: write: connection refused
[subscriber] 2016/08/25 17:35:23 write udp 127.0.0.1:53584->127.0.0.1:47051: write: connection refused
```
They cann't work on different manchine? I have wroked all the afternoon and My heart will dead.I don't know how to do now ?

**Comment by rossmcdonald** [comment]
What versions of Kapacitor and InfluxDB? And what does your Kapacitor configuration look like? Is your `hostname` set in a way that the InfluxDB server will be able to reach the Kapacitor server using that hostname?

Also, what does the output to a `SHOW SUBSCRIPTIONS` look like when run from the InfluxDB CLI?

**Comment by superbool** [comment]
Kapacitor and InfluxDB are all 0.13 version,here is my Kapacitor conf:
```
hostname = "localhost"
data_dir = "/var/lib/kapacitor"

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"
  shutdown-timeout = "10s"

[replay]
  dir = "/var/lib/kapacitor/replay"

[storage]
  boltdb = "/var/lib/kapacitor/kapacitor.db"

[task]
  dir = "/var/lib/kapacitor/tasks"
  snapshot-interval = "1m0s"

[[influxdb]]
  enabled = true
  name = "localhost"
  default = true
  urls = ["http://bj2-crm04:8086"]
  username = ""
  password = ""
  ssl-ca = ""
  ssl-cert = ""
  ssl-key = ""
  insecure-skip-verify = false
  timeout = "0"
  disable-subscriptions = false
  udp-buffer = 1000
  udp-read-buffer = 0
  startup-timeout = "0"
  [influxdb.subscriptions]
  [influxdb.excluded-subscriptions]
...
```

You mean the ** hostname** shoud be the hostname or the ip of the machine, not the  **localhost**? 
That maybe the problem,but I have install Kapacitor and InfluxDB in the same machine now .

**Comment by rossmcdonald** [comment]
> You mean the hostname should be the hostname or the ip of the machine, not the localhost? 

Yes, otherwise InfluxDB does not know where to forward points to. Whatever is set as `hostname` must be resolvable by InfluxDB, so you certainly don't want it to be `localhost` if the services are running on different machines. The output of SHOW SUBSCRIPTIONS will show you where InfluxDB has been forwarding points, but you probably want to set Kapacitor's `hostname` to the IP address of the other machine.
