### ISSUE TITLE
Tick script parser issue

### ISSUE THREAD

**Issue by fandw06** [influxdata/kapacitor#840]
I made some tests of the parser. The parser could be able to detect some errors, for instance when the script is 
"stream
       |from(
" 
An error will return:
{
    "error": "invalid TICKscript: parser: unexpected EOF line 3 char 1 in \"\". expected: \"number\",\"string\",\"duration\",\"identifier\",\"TRUE\",\"FALSE\",\"==\",\"(\",\"-\",\"!\""
}
However, when the script is "stream" no error returns. A stream task could be created and enabled with this script. But when deleting this task from command line, the kapacitor server halted. Restart the kapacitor server doesn't solve this problem and I have to delete .kapacitor data to recover the server. Is it a bug and is it possible to check such kind of errors to avoid server halt?

**Comment by nathanielc** [comment]
@fandw06 I believe this issue was fixed in a recent version. What version are you using?

**Comment by fandw06** [comment]
@nathanielc 
0.13.1

**Comment by nathanielc** [comment]
@fandw06 Can you try with the 1.0.0-rc1 and see if the issue still exists?

**Comment by fandw06** [comment]
@nathanielc 
Yes it is solved. The output is 
{
    "error": "invalid TICKscript: task does nothing"
}
