### ISSUE TITLE
WhereNode modifies batch of data for non-dependent data paths

### ISSUE THREAD

**Issue by avaskys** [influxdata/kapacitor#842]
Consider the following tickscript and data (with timestamps in ms):

[test.tick.txt](https://github.com/influxdata/kapacitor/files/443579/test.tick.txt)
[test.data.txt](https://github.com/influxdata/kapacitor/files/443580/test.data.txt)

I would expect the logged values in countGood and countBad to be the same. However, the countFilter node appears to be modifying the batch of data that the countBad node receives, even though the structure of the tickscript would indicate that those data pathways are independent. Additionally, this behavior is racy and I get different output each time I run the same script with the same data.

If I comment out the countFilter node, things work as expected. My current workaround is to create separate window nodes for each data path.

**Comment by nathanielc** [comment]
@avaskys I'll look into this, what version are you using?
