### ISSUE TITLE
Kapacitor receives no data from influxdb unless restart kapacitord server

### ISSUE THREAD

**Issue by fandw06** [influxdata/kapacitor#843]
I have both influxdb(0.13.1) and kapacitor(0.13.1) installed on my local Mac. First, I run influxd and kapacitord with default configurations. Second, I run my custom program to write time series data continuously into influxdb. Then I create and run two simple kapacitor tasks(seqTest, overTest). However, there is no alert and I find there are no subscriptions.

Then I restart kapacitord and I find information:

[influxdb] 2016/08/29 23:11:09 I! linking subscriptions
[udp:_internal.monitor] 2016/08/29 23:11:09 I! Started listening on UDP: [::]:52579
[influxdb] 2016/08/29 23:11:09 I! started UDP listener for _internal monitor
[udp:seqTest.default] 2016/08/29 23:11:09 I! Started listening on UDP: [::]:52580
[influxdb] 2016/08/29 23:11:09 I! started UDP listener for seqTest default
[udp:overTest.default] 2016/08/29 23:11:09 I! Started listening on UDP: [::]:52581
[influxdb] 2016/08/29 23:11:09 I! started UDP listener for overTest default

Information from influxdb:

show subscriptions
name: _internal
---------------
retention_policy	name						mode	destinations
monitor			kapacitor-a8ead90c-33a7-4986-a8fa-2ca4b051cb21	ANY	[udp://localhost:52579]

name: seqTest
-------------
retention_policy	name						mode	destinations
default			kapacitor-a8ead90c-33a7-4986-a8fa-2ca4b051cb21	ANY	[udp://localhost:52580]

name: overTest
--------------
retention_policy	name						mode	destinations
default			kapacitor-a8ead90c-33a7-4986-a8fa-2ca4b051cb21	ANY	[udp://localhost:52581]

Now the alerts are running correctly. I tried a couple of times and results are the same. It seems that when dynamically create a task then kapacitor cannot receive data and there are no new subscriptions. So do I have to restart kapacitor server every time after I create new tasks?

**Comment by ygtzf** [comment]
Hi,

1. How do you create a task?
2. Please show tasks after you create a task use command "kapacitor show tasks"

thanks.

**Comment by fandw06** [comment]
Hello,
I just switched to 1.0rc and everything works well.
