### ISSUE TITLE
Could not alert in 0.13 if use count?

### ISSUE THREAD

**Issue by EricQAQ** [influxdata/kapacitor#844]
Hi, I have built telegraf + influxdb + grafana and they works well!
And I use kapacitor as an alert tools, and I use the example in https://docs.influxdata.com/kapacitor/v0.13/introduction/getting_started/#trigger-alert-from-batch-data to build an alert test, but it failed..

Here is the tickscript, it should count the usage_idle and sent alert email to me, but I could not receive the email nor the log.. And I want to know where the codes goes wrong..

Thx a lot!

```
batch 
    |query('''
        SELECT count(usage_idle)
        FROM "telegraf"."default"."cpu" 
        WHERE "usage_idle" < 100
        ''')
        .period(30s)
        .every(30s)
        .groupBy(time(30s))
    |alert() 
        .warn(lambda: "count" > 1)
        .crit(lambda: "count" > 7)
        .id('api_calls')
        .message('Alert: {{ .Level }}')
        .details('''
        <h1>ID: {{ .ID }}</h1>
        <b>Level: {{ .Level }}</b>
        <p>Time: {{ .Time }}</p>
        ''')                                                                      
        .email('xxxx@xxxx.com')                                         
        .log('/data/kapacitor/log/exception_alert.log')
```

**Comment by EricQAQ** [comment]
It seems the `count` goes wrong... If  `.warn(lambda: "count" > 1)` changes to `.warn(lambda: "count" > 0)`, I will receive many emails...

**Comment by nathanielc** [comment]
@EricQAQ How frequently are you sending data to InfluxDB from Telegraf? The default is 10s and you are only querying the last 30s of data so at most your count would be 3. 

Also remove the group by time as its not needed in this case. Only use group by time when your period is larger than your group by time interval.

**Comment by EricQAQ** [comment]
It's the default setting, every 10s the telegraf will send data to InfluxDB.

And I remove the group by, it also cannot work..
When I execute the `kapacitor replay`, the log of kapacitor is belowing:

```
[task_master] 2016/08/31 10:10:56 I! opened
[httpd] 2016/08/31 10:10:56 I! 127.0.0.1 - - [31/Aug/2016:10:10:55 +0800] POST /kapacitor/v1/replays HTTP/1.1 201 260 - KapacitorClient 26aa0cb1-6f20-11e6-8072-000000000000 36.350707ms
[task_master] 2016/08/31 10:10:56 I! Started task: cpu-alert
[task_master] 2016/08/31 10:10:56 I! Stopped task: cpu-alert
[task_master] 2016/08/31 10:10:56 I! closed
[httpd] 2016/08/31 10:10:56 I! 127.0.0.1 - - [31/Aug/2016:10:10:56 +0800] GET /kapacitor/v1/replays/50b72009-0501-490d-8b49-2fdfa79047ec HTTP/1.1 200 261 - KapacitorClient 26fc3418-6f20-11e6-8073-000000000000 2.557352ms
```

**Comment by nathanielc** [comment]
@EricQAQ Try using this TICKscript:

```
batch 
    |query('''
        SELECT count(usage_idle)
        FROM "telegraf"."default"."cpu" 
        WHERE "usage_idle" < 100
        ''')
        .period(30s)
        .every(30s)
        .groupBy(time(30s))\
    |log()
        .prefix('QUERY RESULT')
    |alert() 
        .warn(lambda: "count" > 1)
        .crit(lambda: "count" > 7)
        .id('api_calls')
        .message('Alert: {{ .Level }}')
        .details('''
        <h1>ID: {{ .ID }}</h1>
        <b>Level: {{ .Level }}</b>
        <p>Time: {{ .Time }}</p>
        ''')                                                                      
        .email('xxxx@xxxx.com')                                         
        .log('/data/kapacitor/log/exception_alert.log')
```

Check the Kapacitor logs and look for `QUERY RESULT` and see if the `count` value matches your expectations.

**Comment by EricQAQ** [comment]
@nathanielc Thx for your answer! My script goes well.. 

But it is strange that if I use `kapacitor record batch -task batch_cpu_alert -past 30s`, it couldn't work, but if I change `30s` to `1m`, it worked well... Is it because I set `every(30s)`, kapacitor will not execute this tasks in first 30 seconds, and when it start the time is out?
