### ISSUE TITLE
[Feature Request] InfluxDB Node create Database automatically

### ISSUE THREAD

**Issue by ygtzf** [influxdata/kapacitor#854]
Hi,

When I use InfluxDBOut node, it needs a existing database.
If I did not create the database, it will be error:
> E! failed to write points to InfluxDB: {"error":"database not found: \"physics_monitor\""}

I can create database by influxdb command.

But, I want to create the database using tick script. 
What can I do?

Thanks.

**Comment by nathanielc** [comment]
@ygtzf This is currently not possible, although we should add support for it.
