### ISSUE TITLE
Communication of Kapacitor inside a docker with influxdb on cloud

### ISSUE THREAD

**Issue by jainbhavuk630** [influxdata/kapacitor#859]
I am trying to configure Kapacitor running in a docker container (on a machine on cloud) with InfluxDB cluster that has been configured on a different machine on cloud as well. When I try to run the kapacitor with the kapacitor.conf (specifying the influxdb cluster information, i.e. the URL's of all the machines cluster has been set up on, the username and the password), it just shows starting with this configuration, but no subscriptions are created. Will I have to manually create subscriptions in order to enable communication with the InfluxDB cluster?

**Comment by nathanielc** [comment]
@jainbhavuk630 Can you share your startup log? What version are you using?

It should automatically create the subscriptions still.

**Comment by jainbhavuk630** [comment]
@nathanielc Here is my startup log:

`[root@bac55f4f5d65 /]# kapacitord -config /etc/kapacitor/kapacitor.conf

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::

2016/09/01 03:43:58 Using configuration at: /etc/kapacitor/kapacitor.conf
`
I think there might be an issue with the config file of my kapacitor. Also, just to specify, the docker container itself is on a machine on cloud. I am also attaching the part where influxDB specifications are mentioned in kapacitor.conf.

`# Multiple InfluxDB configurations can be defined.
# Exactly one must be marked as the default.
# Each one will be given a name and can be referenced in batch queries and InfluxDBOut nodes.
[[influxdb]]
  # Connect to an InfluxDB cluster
  # Kapacitor can subscribe, query and write to this cluster.
  # Using InfluxDB is not required and can be disabled.
  enabled = true
  default = true
  name = "localhost"
  urls = ["http://10.24.34.148","http://10.24.34.147","http://10.24.34.146"]
  username = "admin"
  password = "admin"
  timeout = 0
  # Absolute path to pem encoded CA file.
  # A CA can be provided without a key/cert pair
  #   ssl-ca = "/etc/kapacitor/ca.pem"
  # Absolutes paths to pem encoded key and cert files.
  #   ssl-cert = "/etc/kapacitor/cert.pem"
  #   ssl-key = "/etc/kapacitor/key.pem"

  # Do not verify the TLS/SSL certificate.
  # This is insecure.
  insecure-skip-verify = false

  # Subscriptions use the UDP network protocl.
  # The following options of for the created UDP listeners for each subscription.
  # Number of packets to buffer when reading packets off the socket.
  udp-buffer = 1000
  # The size in bytes of the OS read buffer for the UDP socket.
  # A value of 0 indicates use the OS default.
  udp-read-buffer = 0

  [influxdb.subscriptions]
    # Set of databases and retention policies to subscribe to.
    # If empty will subscribe to all, minus the list in
    # influxdb.excluded-subscriptions
    #
    # Format
    # db_name = <list of retention policies>
    #
    # Example:
    # my_database = [ "default", "longterm" ]
  [influxdb.excluded-subscriptions]
    # Set of databases and retention policies to exclude from the subscriptions.
    # If influxdb.subscriptions is empty it will subscribe to all
    # except databases listed here.
    #
    # Format
    # db_name = <list of retention policies>
    #
    # Example:
    # my_database = [ "default", "longterm" ]
`
Also, I haven't manually created any subscriptions. But, yes, I have done port mapping (9092) while running the docker image of kapacitor.

**Comment by jainbhavuk630** [comment]
@nathanielc , there seemed to be some problem with my kapacitor itself. On restarting, it created the subscriptions, however, I am having problem with data being streamed from InfluxDB to Kapacitor. Please help me out. I have posted this in another issue.
