### ISSUE TITLE
no method or property "influxDBOut" on *pipeline.LogHandler

### ISSUE THREAD

**Issue by jayannah** [influxdata/kapacitor#860]
Hi

I'm creating Alert using Kapacitor by querying the data from InfluxDB. I'm able to send query the data and able to login the Alert to Log File when condition meet.

But when I added "influxDBOut" to put the alert info back into the InfluxDB, I'm unable define the alert in kapacitor. 

Please see the details below.

[root@horizgrafana-qa kapacitor-0.12.0-1]# kapacitord version
Kapacitor 0.12.0 (git: master 32d4d1b8f688e2d310f4e9413b3fe6ac3ef73c70)
[root@horizgrafana-qa kapacitor-0.12.0-1]#

[root@myhost kapacitor-0.12.0-1]# kapacitor define -name batch_oracle_intellix_tablespace_usage_alert -type batch -tick batch_oracle_intellix_tablespace_usage_alert.tick -dbrp comm_qa.default
invalid task: line 15 char 6: no method or property "influxDBOut" on *pipeline.LogHandler
[root@myhost kapacitor-0.12.0-1]#

Below is my TICK script.  The script works fine **without** line # 15 onwards.. When I add influxDBOut properties, then it failed above error when defining the alert.

```
   1 var tablespace_errors = batch
  2     |query('''
  3        SELECT *  FROM "comm_qa"."default"."Oracle_Intellix_TableSpace"
  4     ''')
  5       .period(20m)
  6       .every(10m)
  7
  8 tablespace_errors
  9    |eval(lambda: "USED_MB" / "TOTAL_MB")
 10           .as('tablespace_used')
 11    |alert()
 12         .crit(lambda: "tablespace_used" >  0.6)
 13         // Whenever we get an alert write it to a file.
 14         .log('/tmp/batch_alerts.log')
 15    |influxDBOut()
 16         .database('comm_qa')
 17         .measurement('Oracle_Intellix_TableSpace_Alerts')
```

**Comment by nathanielc** [comment]
You will need to upgrade to Kapacitor version 1.0.0-rc1 for line # 15 onwards to work.

Version 0.12 doesn't support chaining methods off an alert node.

**Comment by jayannah** [comment]
Works fine in V1.1
