### ISSUE TITLE
Kapacitor Fails gives message too many open files

### ISSUE THREAD

**Issue by thealphaking01** [influxdata/kapacitor#861]
Hello,

I scheduled a couple of alerts on Kapacitor ( around 4-6 ) coupled with InfluxDB. However, after a particular period of time, I found that I was not getting any more alerts. Ultimately on checking, I found out that commands such as "kapacitor list tasks" etc were not working any more, with my log file showing :

**2016/09/01 13:27:38 http: Accept error: accept tcp [::]:9092: accept4: too many open files; retrying in 1s
2016/09/01 13:27:39 http: Accept error: accept tcp [::]:9092: accept4: too many open files; retrying in 1s
2016/09/01 13:27:40 http: Accept error: accept tcp [::]:9092: accept4: too many open files; retrying in 1s
2016/09/01 13:27:41 http: Accept error: accept tcp [::]:9092: accept4: too many open files; retrying in 1s**

Ultimately I had to restart kapacitord service and then this started working.

For most of the alerts, I was also logging them to a text file, located at '/tmp/alerts.log' using the .log() option, and also posting them to another server, using .post()

Can someone tell me what's wrong? I want to schedule more alerts and cannot afford this to fail.

**Comment by nathanielc** [comment]
@thealphaking01 What version are you using? If I remember right older versions had a bug where they forgot to close the HTTP connection for the post events.

**Comment by thealphaking01** [comment]
How can I check my version?

**Comment by nathanielc** [comment]
`kapacitord version`

**Comment by thealphaking01** [comment]
Apologies. I was trying to do kapacitord --version.
The result of version is :
**Kapacitor 0.13.1 (git: master ae7dde3aa467c46c06a5a2058a80c6125203f599)**

**Comment by nathanielc** [comment]
@thealphaking01 Can you upgrade to 1.0.0-rc2 and see if the issue still exists?

[This](https://github.com/influxdata/kapacitor/commit/ab8d34f0c87ac0fc6121618cd39da5a55dd8d672) change fixes the open connections issue I mentioned.

**Comment by thealphaking01** [comment]
Sure. Will doing a go get suffice?

**Comment by nathanielc** [comment]
@thealphaking01 I'd install it the same way you did for version 0.13.1. The same packages/distributions are available for 1.0.0-rc2

**Comment by thealphaking01** [comment]
I installed it using **wget https://dl.influxdata.com/kapacitor/releases/kapacitor_0.13.1_amd64.deb**

So I should use **wget https://dl.influxdata.com/kapacitor/releases/kapacitor_1.0.0_amd64.deb**
instead?

Apologies if the questions are a little too trivial.

**Comment by thealphaking01** [comment]
Got it. Have installed the new version. Will check and tell if it fails again. Thanks for all the help!

**Comment by thealphaking01** [comment]
Seems to work perfectly now. Is there a limit on the number of alerts I can schedule, say, with respect to my system's specifications?

**Comment by nathanielc** [comment]
Glad its working

> Is there a limit on the number of alerts I can schedule, say, with respect to my system's specifications?

There is no easy way to know this limit just based on your system specifications. The thing to do is to test it. The `kapacitor show TASK_NAME` command will output performance stats that you can use to determine how well a given task might scale. But in general Kapacitor consumes CPU and RAM resources more than disk.

**Comment by vittorfp** [comment]
Hello!
The same is happening to me, but on the version Kapacitor OSS 1.5.1 (git: HEAD 89828ffff6cf5cd4cb2b34bf883e134395f734de).

I just have configured some alerts and this started to happen.
