### ISSUE TITLE
Problems in communication of kapacitor with influxdb 

### ISSUE THREAD

**Issue by jainbhavuk630** [influxdata/kapacitor#862]
I am trying to configure Kapacitor running in a docker container (on a machine on cloud) with InfluxDB cluster that has been configured on a different machine on cloud as well. When I try to run the kapacitor with the kapacitor.conf (specifying the influxdb cluster information, i.e. the URL's of all the machines cluster has been set up on, the username and the password). Now, when I boot up the kapacitor, subscriptions are automatically created (because I can see them from the InfluxDB machine) but, data is not streamed. 

I have the following startup log:

```
[run] 2016/09/01 14:22:38 I! Kapacitor starting, version 0.13.1, branch master, commit ae7dde3aa467c46c06a5a2058a80c6125203f599
[run] 2016/09/01 14:22:38 I! Go version go1.6.2, GOMAXPROCS set to 1
[srv] 2016/09/01 14:22:38 I! Kapacitor hostname: 10.24.47.54
[srv] 2016/09/01 14:22:38 I! ClusterID: 34c9876b-c327-42d2-9c08-19acd604c13f ServerID: 3106a96f-2b3a-4c52-a423-4cd2bc6207d2
[task_master] 2016/09/01 14:22:38 I! opened
[influxdb] 2016/09/01 14:22:38 I! linking subscriptions
[udp:_internal.monitor] 2016/09/01 14:22:38 I! Started listening on UDP: [::]:43740
[influxdb] 2016/09/01 14:22:38 I! started UDP listener for _internal monitor
[udp:database.default] 2016/09/01 14:22:38 I! Started listening on UDP: [::]:37765
[influxdb] 2016/09/01 14:22:38 I! started UDP listener for database.default
[task_store] 2016/09/01 14:22:38 W! could not open old boltd for task_store. Not performing migration. Remove the `task_store.dir` configuration to disable migration.
[stats] 2016/09/01 14:22:38 I! opened service
[httpd] 2016/09/01 14:22:38 I! Starting HTTP service
[httpd] 2016/09/01 14:22:38 I! Authentication enabled: false
[httpd] 2016/09/01 14:22:38 I! Listening on HTTP: [::]:9092
[run] 2016/09/01 14:22:38 I! Listening for signals
[httpd] 2016/09/01 14:23:30 I! ::1 - - [01/Sep/2016:14:23:30 +0000] GET /kapacitor/v1/tasks/-name?dot-view=attributes&script-format=formatted HTTP/1.1 404 56 - KapacitorClient a837b747-704f-11e6-8001-000000000000 2.656384ms
[httpd] 2016/09/01 14:23:30 I! ::1 - - [01/Sep/2016:14:23:30 +0000] POST /kapacitor/v1/tasks HTTP/1.1 400 67 - KapacitorClient a8385d49-704f-11e6-8002-000000000000 356.523µs
[httpd] 2016/09/01 14:23:50 I! ::1 - - [01/Sep/2016:14:23:50 +0000] GET /kapacitor/v1/tasks/-name?dot-view=attributes&script-format=formatted HTTP/1.1 404 56 - KapacitorClient b409abdb-704f-11e6-8003-000000000000 2.47401ms
[httpd] 2016/09/01 14:23:50 I! ::1 - - [01/Sep/2016:14:23:50 +0000] POST /kapacitor/v1/tasks HTTP/1.1 400 67 - KapacitorClient b40a42b7-704f-11e6-8004-000000000000 589.468µs
[httpd] 2016/09/01 14:26:16 I! ::1 - - [01/Sep/2016:14:26:16 +0000] GET /kapacitor/v1/tasks/cpu_alert?dot-view=attributes&script-format=formatted HTTP/1.1 404 56 - KapacitorClient 0acac049-7050-11e6-8005-000000000000 341.206µs
[httpd] 2016/09/01 14:26:16 I! ::1 - - [01/Sep/2016:14:26:16 +0000] POST /kapacitor/v1/tasks HTTP/1.1 400 174 - KapacitorClient 0acadde4-7050-11e6-8006-000000000000 2.91239ms
[httpd] 2016/09/01 14:26:31 I! ::1 - - [01/Sep/2016:14:26:31 +0000] GET /kapacitor/v1/tasks/cpu_alert?dot-view=attributes&script-format=formatted HTTP/1.1 404 56 - KapacitorClient 142bef8d-7050-11e6-8007-000000000000 311.422µs
[httpd] 2016/09/01 14:26:31 I! ::1 - - [01/Sep/2016:14:26:31 +0000] POST /kapacitor/v1/tasks HTTP/1.1 200 460 - KapacitorClient 142c0c29-7050-11e6-8008-000000000000 15.840574ms
[httpd] 2016/09/01 14:27:56 I! ::1 - - [01/Sep/2016:14:27:55 +0000] POST /kapacitor/v1/recordings/stream HTTP/1.1 201 212 - KapacitorClient 46443e3f-7050-11e6-8009-000000000000 7.819697ms
[httpd] 2016/09/01 14:27:56 I! ::1 - - [01/Sep/2016:14:27:56 +0000] GET /kapacitor/v1/recordings/61480c66-37a3-484a-aafe-54d6e358cb25 HTTP/1.1 202 212 - KapacitorClient 4691f1be-7050-11e6-800a-000000000000 2.836211ms

```

As you can see, in the logs, there seem to be some HTTP requests too to the influxDB, but, I can't see the alerts (even after running the kapacitor and making a TICK Script).

My TICK Scripts goes as follows:

```
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .info(lambda: TRUE)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

```

In kapacitor.conf, I mention the IP of the machine running the Kapacitor container in the hostname, and InfluxDB configuration are as follows:

```
[[influxdb]]
  # Connect to an InfluxDB cluster
  # Kapacitor can subscribe, query and write to this cluster.
  # Using InfluxDB is not required and can be disabled.
  enabled = true
  default = true
  name = "database"
  urls = ["http://10.24.34.148:8086"]
  username = "admin"
  password = "admin"
  timeout = 0
  # Absolute path to pem encoded CA file.
  # A CA can be provided without a key/cert pair
  #   ssl-ca = "/etc/kapacitor/ca.pem"
  # Absolutes paths to pem encoded key and cert files.
  #   ssl-cert = "/etc/kapacitor/cert.pem"
  #   ssl-key = "/etc/kapacitor/key.pem"

```

What am I missing? Why can't I see any alerts even after enabling the alert, because when I try to record the data for let's say, 20seconds, it always shows 0bytes of data captured.

The show subscriptions command shows:

```
show subscriptions
name: _internal
---------------
retention_policy    name                        mode    destinations
monitor         kapacitor-34c9876b-c327-42d2-9c08-19acd604c13f  ANY [udp://10.24.47.54:43740]


name: database
------------------
retention_policy    name                        mode    destinations
default     kapacitor-34c9876b-c327-42d2-9c08-19acd604c13f  ANY [udp://10.24.47.54:37765]
```

**Comment by nathanielc** [comment]
Did you also open up ports 37765 and 43740 for UDP communication? Based on your subscription InfluxDB is attempting to send the data over UDP to ports 37765 and 43740.

**Comment by jainbhavuk630** [comment]
@nathanielc, no I haven't done that. I have a few doubts. 

1. Does InfluxDB automatically sends data to Kapacitor or Kapacitor pulls data from InfluxDB?
2. Which ports are used by both InfluxDB (8086?) and Kapacitor (9092?) respectively?
3. Everytime I start up kapacitor, it automatically creates subscriptions with random port numbers. Is there a way I can manually specify the port numbers I require the communication to happen on?
4. Under hostname, will I have to mention only the IP address of the machine the Kapacitor is running on, or do I have to mention the port number as well?
5. Under the configuration of InfluxDB, what does name mean? Is it the name of the cluster? But the cluster comprises of multiple machines. 
6. I got to know about creating subscriptions manually so that kapacitor can detect them. However, when I created the following subscription in influxDB, 

fcts_metrics
------------------
retention_policy	name						mode	destinations
fcts_ret		kapacitor-45sjd-949d-ader8			ALL	[udp://10.24.47.54:9092],

and then started my Kapacitor, it still created it's own subscription at a custom port like this:

fcts_ret		kapacitor-bcf27d76-8170-409c-9929-503f1f718218	ANY	[udp://10.24.47.54:34115].

Is there anything that I am missing?

I am sorry, I know these are a lot of questions, but running Kapacitor inside a docker seems to be a difficult task. I just want to have a better understanding of it.

**Comment by nathanielc** [comment]
1. For stream tasks InfluxDB sends the data to Kapacitor.
2. Correct
3. This is because you are using the UDP protocol. If you use upgrade to 1.0.0-rc2 then you can use HTTP based subscriptions and the only port Kapacitor will use is 9092.
4. No, the hostname should just be an IP or hostname that is resolvable from the InfluxDB host
5. Name just gives the cluster a name so in a task you can specify which cluster to want to use.
6. You created the subscription with the ALL mode and Kapacitor wants it to be the ANY mode so it deleted it and recreated it. If the you manually create a subscription identical to the ones Kapacitor creates except for the port then Kapacitor will use it instead of creating its own. This answers the second part of question 3.

**Comment by jainbhavuk630** [comment]
@nathanielc Thanks for the help. Things are much clearer now. But just one more question, since you said I am using UDP based subscriptions, will I have to comment out/delete the HTTP based subscriptions settings from kapacitor.conf and write some new settings for UDP?

**Comment by nathanielc** [comment]
@jainbhavuk630 If you stil have more questions please use the mailing list. Closing this issue now.
