### ISSUE TITLE
GroupBY in TICK Scripts?

### ISSUE THREAD

**Issue by jainbhavuk630** [influxdata/kapacitor#867]
Hi

I just want to know how exactly does GroupBY work in tick scripts and what is it's significance? The official documentation says, 

```
Group the data by a set of tags. Can pass literal * to group by all dimensions. Example:
    |groupBy(*)
node|groupBy(tag ...interface{})
```
Also, is there a possibility I can display the values that are used for determining alerts (warning/critical) with AlertaD configuration?

**Comment by nathanielc** [comment]
@jainbhavuk630 Since this is a general question and not a bug report or feature request it is better asked in the mailing list [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com).
