### ISSUE TITLE
How to use UDF to create a function that replace now's points with 1 minute ago's points

### ISSUE THREAD

**Issue by rydeng** [influxdata/kapacitor#868]
How to use UDF to create a function that replace now's points with 1 minute ago's points?
I want to replace this minute's ponits with 1 minute ago's ponits

**Comment by nathanielc** [comment]
@rydeng By replace do you mean in InfluxDB? Or only in the context of the Kapacitor task?

**Comment by rydeng** [comment]
@nathanielc  thx for reply,  I want to replace in influxDB.

**Comment by rydeng** [comment]
@nathanielc  Maybe  I can also replace in the context of the Kapacitor task and then put it in a new influxDB data base

**Comment by nathanielc** [comment]
@rydeng Yes, I would recommend writing the data to a new InfluxDB database. That way its clear which data has been updated and which has not. Also If you configure a subscription for Kapacitor and then write to the same database you are reading from, you can create an infinite loop where the data keeps being bounced back and forth between InfluxDB and Kapacitor.
