### ISSUE TITLE
How to use fully qualified database name in batch query

### ISSUE THREAD

**Issue by vinhtr** [influxdata/kapacitor#875]
Documentation says it's possible but can't find any examples.
https://github.com/influxdata/kapacitor/blob/master/etc/kapacitor/kapacitor.conf#L63

Given the following config with multiple Influxdb (using kapacitor v0.12). 

```
[[influxdb]]
  enabled = true
  default = true
  name = "foo"
  urls = ["http://1.2.3.4:8086"]
  timeout = 0
  udp-buffer = 1000
  udp-read-buffer = 0

  [influxdb.subscriptions]
    telegraf = ["default"]

[[influxdb]]
  enabled = true
  default = false
  name = "bar"
  urls = ["http://5.6.7.8:8086"]
  timeout = 0
  udp-buffer = 1000
  udp-read-buffer = 0

  [influxdb.subscriptions]
    telegraf = ["default"]
```

How do I specify the fully qualified name for the non default database? I tried the following but it doesn't work.

```
    |query('''
        SELECT *
        FROM "bar"."default".mymeasurement

    |query('''
        SELECT *
        FROM "bar"."telegraf"."default".mymeasurement
```

**Comment by nathanielc** [comment]
I think this is what you are looking for https://docs.influxdata.com/kapacitor/v0.13/nodes/query_node/#cluster

```
batch
    |query('''
        SELECT *
        FROM "telegraf"."default".mymeasurement
''')
     .cluster('bar')

batch
    |query('''
        SELECT *
        FROM "telegraf"."default".mymeasurement
''')
     .cluster('foo')

**Comment by vinhtr** [comment]
How does this work for streams? Doesn't appear to be a cluster method in StreamNode or StreamNode.From.

**Comment by nathanielc** [comment]
@vinhtr Streams do not distinguish the origin cluster. The data is pushed from the InfluxDB cluster to Kapacitor and its not know which cluster it came from.

**Comment by vinhtr** [comment]
To be clear - streams will automatically retrieve data from all databases configured?

**Comment by nathanielc** [comment]
@vinhtr Yes
