### ISSUE TITLE
Mysterious Ghost Tasks Back From The Dead

### ISSUE THREAD

**Issue by gargooza** [influxdata/kapacitor#876]
Kapacitor 1.0.0~beta4 (git: master 1e00423551591862b11f70b5fc59a47300ef596c)

Upon restarting Kapacitor, old tasks that were previously deleted months ago (via CLI `kapacitor delete tasks`) are back from the dead. I now have all of these ghost alerts -- some enabled and others disabled -- attempting to query on their previous batch query schedules.

![image](https://cloud.githubusercontent.com/assets/10506354/18314552/246cda4a-74d9-11e6-90d7-d720e858d575.png)

Any idea what's happening here or how to delete them even more permanently?

**Comment by nathanielc** [comment]
In the upgrade from 0.12 to 0.13 the location of the task data was moved and reorganized, to safely perform the migration the tasks were only copied from their old location not moved. Then once the migration was complete you could safely remove to old db file(or configure it to an empty string so it wouldn't perform the migration). My guess is that you never deleted to old task db and that a restart caused all the old tasks to be copied back over.

See the [release notes](https://github.com/influxdata/kapacitor/blob/master/CHANGELOG.md#v0130-2016-05-11) for the 0.13.0 upgrade steps.

**Comment by gargooza** [comment]
That was it! Thanks, @nathanielc! Case closed.
