### ISSUE TITLE
Error "Level has arguments but cannot be invoked as function"

### ISSUE THREAD

**Issue by octalthorpe** [influxdata/kapacitor#885]
I have the following tick script which at one point was outputting my user defined message on alerts, but now errors with
```
[healthy_host_count-auth:alert10] 2016/09/09 19:01:51 E! template: message:1:116: executing "message" at <.Level>: Level has arguments but cannot be invoked as function"
```
The tick script is as follows:
```
//###################################
//# Generated by 'task-generator.py'
//# Task: healthy_host_count-auth
//###################################

var retention_policy = 'default'
var callout = FALSE
var host_count_warn = 2
var database = 'ion'
var deployment = 'staging'
var slack_channel = 'kapacitor-test'
var host_count_critical = 1
var load_balancer_name = 'ion-staging-auth'

var data = stream
    |from()
        .database(database)
        .retentionPolicy(retention_policy)
        .measurement('cloudwatch_aws_elb')
    |eval(lambda: "load_balancer_name", lambda: "healthy_host_count_maximum")
       .as('_load_balancer_name', '_healthy_host_count_maximum')
       .keep()
       .quiet()
    |where(lambda: "_load_balancer_name" == load_balancer_name)
    //#1 |log()

data
    |deadman(1.0, 5m)
        .stateChangesOnly()
        .message('"{{ .TaskName }}": No Data Check - {{.Level}} -- {{ index .Fields "emitted" | printf "%0.3f" }} points recieved in 5m')
        .slack()
        .channel(slack_channel)
data
    |window()
        .period(10s)
        .every(10s)
    //#2 |log()
    |min('_healthy_host_count_maximum')
        .as('_host_count')
    //Slack
    |alert()
        .stateChangesOnly()
        .message('Healty Host Count {{.TaskName}} is {{ .Level }}: Got a value of {{ index .Fields "_host_count" }} expecting > {{ if .Level eq "WARN" }} {{ .host_count_warn }} {{ else }} {{ .host_count_critical }} {{ end }}')
        .warn(lambda: "_host_count" <= host_count_warn)
        .crit(lambda: "_host_count" <= host_count_critical)
        .slack()
          .channel(slack_channel)
    //OpsGenie
    |alert()
        .stateChangesOnly()
        //.message('Healty Host Count {{ .TaskName }} is {{ .Level }}: Got a value of {{ index .Fields "_host_count" }} expecting > {{ if .Level eq "WARN" }} {{ .host_count_warn }} {{ else }} {{ .host_count_critical }} {{ end }}')
        .crit(lambda: "_host_count" <= host_count_critical AND callout == TRUE)
        .slack()
```

Leaving out the .message() attribute, the alert fires with the default message.

Message as follows works:
```
.message('Healty Host Count {{.TaskName}} is {{ .Level }}: Got a value of {{ index .Fields "_host_count" }}')
```
So must be in the test and if/else logic, but I cannot for the life of me figure out what that message means, and where my error is.  Any guidance would be greatly appreciated.

**Comment by octalthorpe** [comment]
Sorry running "kapacitor-1.0.0~rc1-1"

**Comment by nathanielc** [comment]
@octalthorpe I believe you want to reverse this:

`{{ if .Level eq "WARN" }} `

like so:

`{{ if eq .Level  "WARN" }} `

Also using `{{ .host_count_warn }}` will not work, but doing this will:

`'{{ if eq .Level "WARN" }} ' + string(host_count_warn) + '{{ else }}' + string(host_count_critical) + '{{ end }}'`

**Comment by octalthorpe** [comment]
Of course, I was staring at that for some time, moving the order of the equals comparison to match the go template language syntax works.  Duh...

Following your example works.

Is the reason we need to do a variable to string expansion before the template is expanded, because the message node does not have access to all variables of the task in some form?  If so, any reason the message node cannot have access to all variables?  That way we would not have to do the +string(var) stuff to do one extra level of expansion, and simply use go template language natively.  i.e.
```
Healthy Host Count {{.TaskName}} is {{ .Level }}: Got a value of {{ index .Fields "_host_count" }} expecting > {{ if eq .Level "WARN" }} {{._host_count_warn}} {{ else }} {{._host_count_critical}} {{ end }}
```
I have not done much golang programming but maybe it makes more sense to keep the golang naming conventions and to have proper variables under another key, i.e. .TaskVars.HostCountCritical
```
Healthy Host Count {{.TaskName}} is {{ .Level }}: Got a value of {{ index .Fields "_host_count" }} expecting > {{ if eq .Level "WARN" }} {{.TaskVars.HostCountWarn}} {{ else }} {{.TaskVars.HostCountCritical}} {{ end }}
```

**Comment by nathanielc** [comment]
@octalthorpe I like your suggestion. Currently those two systems (TICK vars and alert template expansion) are isolated and do not interact. But there maybe a way to make it work and like you say it would make reading and writing the TICKscript easier.

Could you create a new issue with your proposed solution so we can track the request there? Thanks

**Comment by octalthorpe** [comment]
Will do.
