### ISSUE TITLE
Slack rate limit

### ISSUE THREAD

**Issue by slemire** [influxdata/kapacitor#887]
Is there a way to rate-limit the messages in Kapacitor whenever I need to send multiples messages to Slack? I seem to be hitting the rate-limit of 1 msg/sec whenever I trigger an alert (I send 6 messages for each alert and sometimes only half of them are received properly in my Slack channel).

**Comment by nathanielc** [comment]
@slemire Not currently but this feature is already being discussed here https://github.com/influxdata/kapacitor/pull/884

**Comment by andoks** [comment]
Relates to #828
