### ISSUE TITLE
kapacitor losing data?

### ISSUE THREAD

**Issue by csbond** [influxdata/kapacitor#888]
HI,
  I'm using kapacitor v1.0.0 right now and I wrote a program with UDPSocket to send data to telegraf.The program will print data as the following format shows:
```
			{
			"device_sn" : "universal_SMART_LINK_000000004707",
			"metric_name" : "breath6909",
			"count" : 1102,
			"running_time" : 2.167672551	
			}
```
"device_sn" and "metric_name" are my tag keys,"count" mean the total data had been send and "running_time" record the program running time.
**The program send data infinite loop until i stop it and every loop will _sleep 0.01s_.**
Start this program and stop it at a random time,the last print of program is : 
```
			{
			"device_sn" : "universal_SMART_LINK_000000005816",
			"metric_name" : "breath1150",
			"count" : 3098,
			"running_time" : 34.064161455	
			}
```
There are 3098 data have been send in 34s.
The telegraf log:
`2016/09/11 03:18:48 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 3098. Total dropped metrics: 0..`

kapacitor show task:
```
ID: check
Error: 
Template: 
Type: stream
Status: enabled
Executing: true
Created: 11 Sep 16 01:01 PDT
Modified: 11 Sep 16 03:15 PDT
LastEnabled: 11 Sep 16 03:15 PDT
Databases Retention Policies: ["metrics"."autogen"]
TICKscript:
stream
    |from()
        .measurement('charging_measurement')
        .groupBy(*)
    |alert()
        .id('check')
        .crit(lambda: TRUE)

DOT:
digraph check {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="3098"];

from1 [avg_exec_time_ns="2.868µs" ];
from1 -> alert2 [processed="3098"];

alert2 [alerts_triggered="3098" avg_exec_time_ns="593.337µs" crits_triggered="3098" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}
```

**Every thing looks like great,but if i alter the _sleep time to 0.001s_.**
Reload the task and clean the telegraf's log.
Start the program and stop it at a random time,the last print of program is :
```
			{
			"device_sn" : "universal_SMART_LINK_000000001076",
			"metric_name" : "breath6101",
			"count" : 14569,
			"running_time" : 23.871231481	
			}
```
The telegraf log:
`2016/09/11 03:31:24 Output [influxdb] buffer fullness: 0 / 10000 metrics. Total gathered metrics: 14569. Total dropped metrics: 0.`

kapacitor show task:
```
ID: check
Error: 
Template: 
Type: stream
Status: enabled
Executing: true
Created: 11 Sep 16 01:01 PDT
Modified: 11 Sep 16 03:30 PDT
LastEnabled: 11 Sep 16 03:30 PDT
Databases Retention Policies: ["metrics"."autogen"]
TICKscript:
stream
    |from()
        .measurement('charging_measurement')
        .groupBy(*)
    |alert()
        .id('check')
        .crit(lambda: TRUE)

DOT:
digraph check {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="7761"];

from1 [avg_exec_time_ns="11.119µs" ];
from1 -> alert2 [processed="7761"];

alert2 [alerts_triggered="7761" avg_exec_time_ns="1.071402ms" crits_triggered="7761" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}
```
We can see " "count" : 14569 ", it's mean the program have send 14569 data, but it's look like the kapacitor only recived 7761 data?

I have some questions:
- The program had sent the data but the kapacitor never received those data,so where is it?
- How can i avoid losing data?

Looking forward your reply as soon as possible.Thank you!
Best regards.

**Comment by nathanielc** [comment]
@csbond How does data get from Telegraf to Kapacitor? Are you sending it to InfluxDB and then relying on subscriptions to forward the data? Or is Telegraf configured to send the data directly to Kapacitor?

Also can you share the output of `kapacitor stats ingress`? Thanks

**Comment by csbond** [comment]
@nathanielc  I don't know Telegraf can send the data directyle to Kapacitor , i think i am sending it InfluxDB and then relying on subscritions to forword the data.

Here is my config file: 
Telegraf config:
[telegraf-conf.docx](https://github.com/influxdata/kapacitor/files/468745/telegraf-conf.docx)
Kapacitor config file:
[kapacitor-conf.docx](https://github.com/influxdata/kapacitor/files/468769/kapacitor-conf.docx)

Kapacitor stats ingress before send data:
![image](https://cloud.githubusercontent.com/assets/19200875/18460773/fbc19392-79a6-11e6-83c0-586d0bb5d433.png)aa

Start the program and stop it at a random time,the last print of program is :
```
                                { 
                                        "count" : 7368,
                                        "running_time" : 12.286491257,
                                        "sn" : "SMART_LINK_00000000000001",
                                        "metric_name" : "breath4517"
                                  }
```
Telegraf log:
`2016/09/13 11:46:57 Output [influxdb] buffer fullness: 0 / 100000 metrics. Total gathered metrics: 7368. Total dropped metrics: 0.`

InfluxDB query:
![image](https://cloud.githubusercontent.com/assets/19200875/18460906/fd08c314-79a7-11e6-858e-5346e668b2b0.png)

Kapacitor stats ingress after send data:

![image](https://cloud.githubusercontent.com/assets/19200875/18460937/2a6b65f0-79a8-11e6-809b-3c2d064a2278.png)
aaa

**Comment by nathanielc** [comment]
@csbond You are using UDP as the transport from InfluxDB to Kapacitor. Either take care to make sure your UDP buffers are large enough to avoid dropping packets (see [this](https://docs.influxdata.com/influxdb/v1.0/tools/udp/#main-nav), or switch to using HTTP for subscriptions, by setting the `subscription-protocol = "http"` in the `[[influxdb]]` section of the config.

**Comment by csbond** [comment]
Yes,my UDP buffers are too small,when i increase it to 8m,kapacitor can receive the full data!
Thank you.
