### ISSUE TITLE
I create a task with http client and cannot update the task useing command in shell.

### ISSUE THREAD

**Issue by ygtzf** [influxdata/kapacitor#891]
Hi,

Kapacitor version: 0.13.1 (git: master ae7dde3aa467c46c06a5a2058a80c6125203f599)
 
First, I create a task with http client, the task is worked ok.

Then, I want to update the task useing command in shell, but,  it have no effect, 
at the same time, the log of kapacitor is ok, have no error log. The command is 
"kapacitor define {taskname} -tick {tick script name}"

I check the task content with command "kapacitor show {taskname}" and I find the content of the task
are same as before.

Please check this issue.

Thanks!

**Comment by Daxda** [comment]
I have the same issue on the v1.0 version of Kapacitor.
Defining and enabling a `tick` script works perfectly. Changing the tick script and then using the 
`kapacitor reload <name>` doesn't change the modified script when showing it with `kapacitor show <name>`.

**Comment by nathanielc** [comment]
@ygtzf @Daxda Can you provide a simple script that reproduces this error?

**Comment by ygtzf** [comment]
@nathanielc 

 I'm so sorry for my mistake,  my command is not correct, my command is
**"kapacitor define {task name} {tick script name}"**, but it has no error log.

Also, when I type command **"kapacitor enable {task name}"** , if the task name
is not exist, kapacitor have no error log.

Once again apologize for my mistake.

Thanks!

**Comment by Daxda** [comment]
@nathanielc Here's how I proceed.

This is the example tick script I want to define and enable.
```
stream
    |from()
        .measurement('http_response')
        .where(lambda: "http_response_code" != 200)
    |alert()
        .info(lambda: TRUE)
        .log('/tmp/test_kapacitor.log')
```

I define the tick script with `kapacitor define test_script -tick test.tick -dbrp "db_x.autogen" -type stream`
kapacitor show test_script yields:

```
ID                            Type      Status    Executing Databases and Retention Policies
testing_all_the_things        stream    disabled  false     ["db_ojo"."autogen"]
```

After that I modify the tick script by inverting the boolean comparison to `        .where(lambda: "http_response_code" == 200)`

Then I reload the modified tick file with: `kapacitor reload test_script`. After executing the show command again I get the old result (the one without the modification).

**Comment by nathanielc** [comment]
@Daxda Did you `define` the task again after modifying the file? Kapacitor stores its own copy of the TICKscript for tasks. The workflow is:

```
kapacitor define test_script -tick test.tick -dbrp "db_x.autogen" -type stream
kapacitor show test_script
# Modify test.tick
kapacitor define test_script -tick test.tick
kapacitor show test_script
```

The `reload` action is a way of telling Kapacitor to stop and then start the task, such that it starts from a clean state, i.e. all counters are reset to 0 etc. The `define` action automatically reloads the task unless the `-no-reload` flag is provided.

**Comment by Daxda** [comment]
Aww :( I guess I misinterpreted the use of reload then.
Sorry for the confusion.

**Comment by vmahedia** [comment]
@nathanielc changing `reload` to update the task or  adding a new option called `update` sounds like a good option to put in.

**Comment by varaga** [comment]
@nathanielc - I see the same problem with extending the task by following 
```
kapacitor define <task name>
```
this was observed with Kapacitor version 1.3.x
I see no alert coming after redefining the task
