### ISSUE TITLE
Evaluate a Memory usage in Tick Script

### ISSUE THREAD

**Issue by Abhinavm8** [influxdata/kapacitor#896]
Hi @nathanielc  

I want to evaluate a memory usage of given node such that (x) . and that value of (x) comes in  int type like  ie 2345678234 . using the eval with humanBytes function i can parse into normal human readable format but when i want to compare these value with my threshold value it is saying   

{{ error evaluating expression for level CRITICAL: mismatched type to binary operator. got string > int. see bool(), int(), float(), string(), duration() }}

using eval as :  |eval(lambda: humanBytes("HeapMemoryUsage_max"))
                          .as('used_mem')

crit condition as :  .crit(lambda: ("used_mem") > threshold )

**Comment by nathanielc** [comment]
@Abhinavm8 humanBytes converts the int into a string which is no longer suitable for comparisons against your threshold.

Try something like this:
```
|eval(lambda: humanBytes("HeapMemoryUsage_max"))
    .as('used_mem')
    .keep('HeapMemoryUsage_max', 'used_mem')
|alert()
    .crit(lambda: "HeapMemoryUsage_max" > threshold )
    .message('Memory used is: {{ index .Fields "used_mem"}}')
```

**Comment by Abhinavm8** [comment]
thanks for your reply @nathanielc 
It did work. One more concern is that it is giving the data in GB . what if we want that   data to be represented in MB .?
Or if  we want to measure the metrics for Disk I/O they should be in wps or rps ?

**Comment by nathanielc** [comment]
@Abhinavm8 The `humanBytes` function tries to keep the number of digits that you have to read small. If you want a consistent representation then its not hard to do yourself.

```
var mb = 1024*1024

...
|eval(lambda: string(int("HeapMemoryUsage_max") / mb) + 'MB' )
    .as('used_mem')
    .keep('HeapMemoryUsage_max', 'used_mem')
|alert()
    .crit(lambda: "HeapMemoryUsage_max" > threshold )
    .message('Memory used is: {{ index .Fields "used_mem"}}'
```

**Comment by Abhinavm8** [comment]
thanks 
 it works for me .
