### ISSUE TITLE
The details section of the AlertNode returns all double quotes as UTF-8 code

### ISSUE THREAD

**Issue by TomerAmirV** [influxdata/kapacitor#901]
I tried to create a simple alert for high cpu, and for some reason all the alert section of the AlertNode is encoded in UTF-8. Is it on purpose?
Here is my output from the log:

`{"id":"cpuStats:nil","message":"My Test Message","details":"{\u0026#34;Name\u0026#34;:\u0026#34;cpuStats\u0026#34;,\u0026#34;TaskName\u0026#34;:\u0026#34;high_cpu\u0026#34;,\u0026#34;Group\u0026#34;:\u0026#34;nil\u0026#34;,\u0026#34;Tags\u0026#34;:{\u0026#34;host\u0026#34;:\u0026#34;callhandler-vos\u0026#34;},\u0026#34;ID\u0026#34;:\u0026#34;cpuStats:nil\u0026#34;,\u0026#34;Fields\u0026#34;:{\u0026#34;idle\u0026#34;:99.09,\u0026#34;interval\u0026#34;:60,\u0026#34;iowait\u0026#34;:0.09,\u0026#34;nice\u0026#34;:0.13,\u0026#34;processorid\u0026#34;:\u0026#34;-1\u0026#34;,\u0026#34;steal\u0026#34;:0,\u0026#34;system\u0026#34;:0.2,\u0026#34;user\u0026#34;:0.49},\u0026#34;Level\u0026#34;:\u0026#34;INFO\u0026#34;,\u0026#34;Time\u0026#34;:\u0026#34;2016-09-14T09:21:01Z\u0026#34;,\u0026#34;Message\u0026#34;:\u0026#34;Tomer Test\u0026#34;}\n","time":"2016-09-14T09:21:01Z","duration":60000000000,"level":"INFO","data":{"series":[{"name":"cpuStats","tags":{"host":"callhandler-vos"},"columns":["time","idle","interval","iowait","nice","processorid","steal","system","user"],"values":[["2016-09-14T09:21:01Z",99.09,60,0.09,0.13,"-1",0,0.2,0.49]]}]}}`

**Comment by rossmcdonald** [comment]
@TomerAmirV This is on purpose. From the documentation [here](https://docs.influxdata.com/kapacitor/v1.0//nodes/alert_node/#details):

> This template is rendered using the html/template package in Go so that safe and valid HTML can be generated.

You can also override what is included in the details using the `.details()` property method, or make it blank with `.details('')`.
