### ISSUE TITLE
[Question] UDF Snapshot and unknwon Request MessageCase

### ISSUE THREAD

**Issue by bbczeuz** [influxdata/kapacitor#903]
Hi,
What is the meaning of the SnapshotRequest? Shall my UDF send an array with the whole state information? This could be quite big (aggregating lots of data). Will Kapacitor automatically trigger a RestoreRequest upon reload?

Sometimes, my UDF I seems to receive Requests with MessageCase == MESSAGE_NOT_SET. Is this a bug in my Server/Agent/Handler, or what does this mean?

Kapacitor v1.0.0, libprotoc 3.0.0, Everything in C++ (boost::asio) on Centos 7

**Comment by nathanielc** [comment]
In reply to a SnapshotRequest your UDF can return what ever data it wishes to preserve. Yes, the data will be restored when the UDF is reloaded. This data is opaque to Kapacitor.

> Sometimes, my UDF I seems to receive Requests with MessageCase == MESSAGE_NOT_SET. Is this a bug in my Server/Agent/Handler, or what does this mean?

This is the first time it has been reported. Could you share more details about when this occurs? Details about the previous message received or any logs from the Kapacitor daemon would be helpful.

**Comment by bbczeuz** [comment]
MESSAGE_NOT_SET: It probably was a bug in my code. I'm using unix sockets for communication. 
It typically happened to the message after I received one or two 313B long kPoint messages (broken msgs were 101B long, starting with 0x5f 0x73 0x74 0x65... or 11B-16B long, starting with 0x75 0x73 0x61 0x67 0x65 0x5f...

Now I increased buffer space and it works fine (buffer_size was 1024B, messages were up to 320B, now buffer_size is 4096B) Kind of strange behavior. Needs testing on my side, so I close this issue.

**Comment by nathanielc** [comment]
@bbczeuz Thanks for digging in. After you get the C++ code working if your are willing we'd love to take a look at it and maybe adopt it as the C++ handler implementation in Kapacitor.

**Comment by bbczeuz** [comment]
@nathanielc Chances are good, that I'll open a PR for the C++ implementation. It's still very alpha like, WIP.

**Comment by nathanielc** [comment]
@bbczeuz Awesome! Excited to see it.
