### ISSUE TITLE
Capturing start and stop time of events 

### ISSUE THREAD

**Issue by seesiva** [influxdata/kapacitor#910]
I'm having a scenario where we are capturing the start event and stop event continuously. Where start is considered as value 1 and stop is considered as value 0. We would  like to record one start and one stop as a combined columns to determine the time elapsed between these two events using Kapacitor with stream. Any pointers which would help.

**Comment by seesiva** [comment]
The problem I'm trying to solve is similar to this https://github.com/influxdata/kapacitor/issues/643

**Comment by nathanielc** [comment]
@seesiva Yes, #643 will enable start event stop event detection.
