### ISSUE TITLE
Unreadable characters in alert log file

### ISSUE THREAD

**Issue by alparslanuysal** [influxdata/kapacitor#912]
Kapacitor version:  1.0

This is my template;
var measurement string

var where_filter = lambda: TRUE

var field string

var crit lambda

stream
    |from()
	.measurement(measurement)
	.where(where_filter)
    |alert()
	.crit(crit)
	.stateChangesOnly()
	.idField(field)
	.levelField(field)
	.log('/home/alparslan/template_alerts.log')
	.mode(0644)

This is my json file;

{
    "measurement": {"type" : "string", "value" : "pompa" },
    "where_filter": {"type": "lambda", "value": "\"device_name\" == 'banner'"},
    "field": {"type" : "string", "value" : "motion" },
    "crit": {"type" : "lambda", "value" : "\"motion\" > 40.0" }
}

This is the log

{"id":"pompa:nil","message":"pompa:nil is CRITICAL","details":"{\u0026#34;Name\u0026#34;:\u0026#34;pompa\u0026#34;,\u0026#34;TaskName\u0026#34;:\u0026#34;temp_motion_alert\u0026#34;,\u0026#34;Group\u0026#34;:\u0026#34;nil\u0026#34;,\u0026#34;Tags\u0026#34;:{\u0026#34;device_name\u0026#34;:\u0026#34;banner\u0026#34;},\u0026#34;ID\u0026#34;:\u0026#34;pompa:nil\u0026#34;,\u0026#34;Fields\u0026#34;:{\u0026#34;ambient_temps\u0026#34;:20,\u0026#34;devices_temp\u0026#34;:20,\u0026#34;motion\u0026#34;:60},\u0026#34;Level\u0026#34;:\u0026#34;CRITICAL\u0026#34;,\u0026#34;Time\u0026#34;:\u0026#34;2016-09-16T12:46:48.394131373Z\u0026#34;,\u0026#34;Message\u0026#34;:\u0026#34;pompa:nil is CRITICAL\u0026#34;}\n","time":"2016-09-16T12:46:48.394131373Z","duration":0,"level":"CRITICAL","data":{"series":[{"name":"pompa","tags":{"device_name":"banner"},"columns":["time","ambient_temps","devices_temp","motion"],"values":[["2016-09-16T12:46:48.394131373Z",20,20,60]]}]}}

**Comment by rossmcdonald** [comment]
@alparslanuysal Are you referring to the encoding in the `details` key (`\u0026#34`, etc.)? If so, please see my comment [here](https://github.com/influxdata/kapacitor/issues/901#issuecomment-247035340).
