### ISSUE TITLE
option to fill up window

### ISSUE THREAD

**Issue by rubycut** [influxdata/kapacitor#913]
As it currently works in kapacitor 1.0.0

|window().period(300s).every(60s)

This will emit as soon as 60 seconds passes. In other words, period is not honored.

While every(60) it seems logical to send every 60 seconds, this creates many fake alerts immediately after task is loaded (period didn't fill up yet).

So, there should be option fill() which should not emit anything until first period passes. For example:

|window().period(300s).every(60s).fill()

**Comment by nathanielc** [comment]
@rubycut Thanks for the suggestion.

**Comment by titilambert** [comment]
@nathanielc Any workaround for this ?

**Comment by nathanielc** [comment]
@titilambert Sadly no. But I am doing 1.2 planning right now and this is similar to some other work I plan to get done so I'll add it to the 1.2 milestone for now.

**Comment by titilambert** [comment]
@nathanielc even with batch mode ?
