### ISSUE TITLE
Does Kapacitor support writing alert back to influxdb directly?

### ISSUE THREAD

**Issue by wei-hai** [influxdata/kapacitor#917]
We would like to display the alert as annotation on grafana together with the data it is scanning, the only solution I can come up with is to let Kapacitor post the alert to a server and let the server parse the alert body and then inject it into influxdb.

**Comment by wei-hai** [comment]
influxDBOut() writes everything back to the database instead of the alert only. So my guess my requirement is not met.

**Comment by rossmcdonald** [comment]
@wei-hai Can you provide us with the TICK script, the current output, and then the output you would expect to see? Writing the alert back into InfluxDB should include all of the alert details except [the message itself](https://github.com/influxdata/kapacitor/issues/869). Adding the message didn't make it in to v1.0, but will be included in Kapacitor v1.1 and is currently in the latest nightlies.

**Comment by wei-hai** [comment]
batch
   |query('''
       SELECT sum(success)/sum(attempt) AS ratio
       FROM "mydb"."default"."signup"
   ''')
       .period(5m)
       .every(5m)
       .groupBy(time(1m))
   |alert()
       .id('Kapacitor alert')
       .message('signup success/attempt ratio is low, ratio={{index .Fields "ratio"}}')
       .crit(lambda: "ratio" < 0.4)
       .log('/etc/kapacitor/alert.log')
       .pagerDuty()
           .serviceKey(key)

Take this script as an instance, suppose the query returns 5 data samples [0.8, 0.7, 0.6, 0.3, 0.5], I would like to send the alert generated on the 4th sample instead of all of them to influxdb with detail.

**Comment by rossmcdonald** [comment]
@wei-hai Ah, okay, the current functionality will emit every sample to InfluxDB. One way to get around this is to add a `where()` node before the `influxDBOut()` to limit what is emitted to InfluxDB. For example, updating your script to:

```
batch
   |query('''
       SELECT sum(success)/sum(attempt) AS ratio
       FROM "mydb"."default"."signup"
   ''')
       .period(5m)
       .every(5m)
       .groupBy(time(1m))
   |alert()
       .id('Kapacitor alert')
       .message('signup success/attempt ratio is low, ratio={{index .Fields "ratio"}}')
       .crit(lambda: "ratio" < 0.4)
       .log('/etc/kapacitor/alert.log')
       .idField('id')
       .levelTag('level')
    |where(lambda: "id" != '')
    |influxDBOut()
        .database('kapacitor_alerts')
        .retentionPolicy('autogen')
        .measurement('signup')
```

Will only write the value `0.3` to InfluxDB (including the id and level of the alert being triggered).
