### ISSUE TITLE
Runing Kapacitor in docker container

### ISSUE THREAD

**Issue by bogdanveres** [influxdata/kapacitor#918]
I have the following docker file:

`FROM buildpack-deps:jessie-curl`

`RUN gpg \`
    `--keyserver hkp://ha.pool.sks-keyservers.net \`
    `--recv-keys 05CE15085FC09D18E99EFB22684A14CF2582E0C5`

`ENV KAPACITOR_VERSION 1.0.0`
`RUN wget -q https://dl.influxdata.com/kapacitor/releases/kapacitor_${KAPACITOR_VERSION}_amd64.deb.asc && \`
    `wget -q https://dl.influxdata.com/kapacitor/releases/kapacitor_${KAPACITOR_VERSION}_amd64.deb && \`
    `gpg --batch --verify kapacitor_${KAPACITOR_VERSION}_amd64.deb.asc kapacitor_${KAPACITOR_VERSION}_amd64.deb && \`
    `dpkg -i kapacitor_${KAPACITOR_VERSION}_amd64.deb && \`
    `rm -f kapacitor_${KAPACITOR_VERSION}_amd64.deb*`
`COPY kapacitor.conf /etc/kapacitor/kapacitor.conf`
`COPY Alert.tick /home/docker_containers/Alert.tick`

`EXPOSE 9092`

`VOLUME /home/docker_containers/kapacitor/volume`
`VOLUME /var/lib/kapacitor`

`COPY entrypoint.sh /entrypoint.sh`
`ENTRYPOINT ["/entrypoint.sh"]`
`CMD ["kapacitord"]`

Building with: `docker build -t kapacitor-v1 .`
All steps are completed successfully. 
I have created the following TICK script:

`stream`
    `.from().measurement('SIFEAT')`
        `.where(lambda: "value_12" >= 65600)`
    `.alert()`
    `.warn(lambda: "value_12" <= 65600)`
        `.crit(lambda: "value_12" >= 65600)`
        `.log('/tmp/high_cpu.log')`

I'm switching to bash Kapacitor container using:

`docker run -it kapacitor-v1 bash`

Then I run the following command to create the task:

`kapacitor define \`
    `-name cpu_alert \`
    `-type stream \`
    `-tick Alert.tick \`
    `-dbrp SIDATA.default`

where `SIDATA` is database with default retention policy.

And I get:

`Post http://localhost:9092/kapacitor/v1/tasks: dial tcp [::1]:9092: getsockopt: connection refused`
![getsockopt_error](https://cloud.githubusercontent.com/assets/3493668/18616748/a75c1c42-7dc9-11e6-8fee-9c3e8ac20e3f.png)

A zip file with Dockerfile and TICK script is attached. 
I don't know what do I have to change in order to be able to create subscriptions. Is there a detailed example or a guide to run kapacitor & influxdb from docker containers? I wasted too much time on this task and I can't figure out what should I change in order to enable subscriptions and notifications. InfluxDB is running form another container.
Any suggestions are appreciated.

[kapacitor.zip](https://github.com/influxdata/kapacitor/files/478776/kapacitor.zip)

**Comment by nathanielc** [comment]
@bogdanveres What version of Kapacitor are you using? Based on these command it looks like you are using a really old version that didn't support docker well. Can you try updating to the latest 1.0 version?

**Comment by bogdanveres** [comment]
@nathanielc I'm using the latest version of Kapacitor (1.0.0).
Here is the output for `docker version`:

`Client:`
 `Version:      1.9.1`
 `API version:  1.21`
 `Go version:   go1.4.3`
 `Git commit:   a34a1d5`
 `Built:        Fri Nov 20 17:56:04 UTC 2015`
 `OS/Arch:      linux/amd64`

`Server:`
 `Version:      1.9.1`
` API version:  1.21`
 `Go version:   go1.4.3`
` Git commit:   a34a1d5`
 `Built:        Fri Nov 20 17:56:04 UTC 2015`
` OS/Arch:      linux/amd64`

In the docker file Kapacitor version is set to 1.0.0.

`ENV KAPACITOR_VERSION 1.0.0`

I have no idea why this error is thrown. Kapacitor is running without any problems on other server but there we don't use docker. 

OS on host machine is Ubuntu 16.04.1 LTS

**Comment by nathanielc** [comment]
@bogdanveres  These snippets you provided:

> kapacitor define \
-name cpu_alert \
-type stream \
-tick Alert.tick \
-dbrp SIDATA.default

and 

>stream
.from().measurement('SIFEAT')
.where(lambda: "value_12" >= 65600)
.alert()
.warn(lambda: "value_12" <= 65600)
.crit(lambda: "value_12" >= 65600)
.log('/tmp/high_cpu.log')


are not Kapacitor 1.0.0 compatible, they are older syntax from version 0.10.0 and are no longer supported. Could that be the issue?
