### ISSUE TITLE
mysql slave alert

### ISSUE THREAD

**Issue by socol1** [influxdata/kapacitor#919]
I want to monitor the slave status of the MySQL ,when the state is normal, the value is 1, but not in normal state for null, I want to know the value of null, how can I judge through the script:
![image](https://cloud.githubusercontent.com/assets/18021407/18620368/cf4a394e-7e43-11e6-843b-fd362372825b.png)

The following is my script:

var crit_threshold = 1
var data = stream
        |from()
           .database('telegraf')
           .retentionPolicy('telegraf_01')
           .measurement('mysql')
           .groupBy('host')
        |window()
          .period(10s)
          .every(10s)
data
        |alert()
            .id('{{ index .Tags "host"}} | {{ index .Tags "slave_Slave_SQL_Running"}}')
            .message('{{ .ID }} is {{ .Level }} value:{{ index .Fields "slave_Slave_SQL_Running" }}')
            .crit(lambda: "slave_Slave_SQL_Running" != 1)
            .stateChangesOnly()
            .log('/tmp/alert.log')

Please help me.

telegraf+kapacitor+infuxDB

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.
