### ISSUE TITLE
Cross version problems

### ISSUE THREAD

**Issue by TomerAmirV** [influxdata/kapacitor#920]
I am trying to install and utilize kapacitor with our influxdb.
Our influxdb version is 0.13

At first I tried to use Kapacitor 1.0.0 since it says on the site that it should work with influxdb 0.13, but I could not get it to work.

Then I tried to install another influxdb version 1.0.0 to make sure it's not the kapacitor instance, and it worked.

Then I tried to install kapacitor 0.13 and tried to make it work with influx 0.13, but i could not make it work either.

I all cased I tried to create a simple CPU alert. We do not use telegraph, but I did make sure the data is written in the database.

In all cases I used the default configuration for kapacitor. (At first i did try to fiddle with it, but after that I tried to follow the manual as close as I could)

The tick file I am using is:

```
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .info(lambda: TRUE)
        .crit(lambda: "usage_idle" <  70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')
```

The register command for the tick:
```sh
kapacitor define high_cpu -dbrp test.default -type "stream" -tick ~/high_cpu.tick
```

I did notice that the `-dbrp` changed in version `1.0.0`, and I put the correct dbrp according to the version of influx I was using.

What am I doing wrong?

**Edit**
By not working I mean two things:
1. The log file `/tmp/alerts.log` was not created and written to
2. I did not see any reports in the kapacitor log (`/var/log/kapacitor/kapacitor.log`) and there were no error messages in `/var/log/kapacitor/kapacitord.error`

**Comment by nathanielc** [comment]
@TomerAmirV Kapacitor and InfluxDB will only work if their major version is the same.

As for why the task is not working in version 0.13 I need more information to be able to you get to the bottom of the issue. First off the output of `kapacitor show task_name` would be the most helpful.

**Comment by TomerAmirV** [comment]
Sorry it took some time, and thanks for the response!

here is the result you asked for:

```
D: high_cpu
Error: 
Type: stream
Status: enabled
Executing: true
Created: 19 Sep 16 07:35 UTC
Modified: 19 Sep 16 07:35 UTC
LastEnabled: 19 Sep 16 07:35 UTC
Databases Retention Policies: ["test"."default"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .info(lambda: TRUE)
        .crit(lambda: "usage_idle" < 70)
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')


DOT:
digraph high_cpu {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="0"];

from1 [avg_exec_time_ns="0" ];
from1 -> alert2 [processed="0"];

alert2 [alerts_triggered="0" avg_exec_time_ns="0" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}

```

This was taken from a kapacitor 0.13 instance with influxdb 0.13

**Comment by TomerAmirV** [comment]
Ok... Found my bug... Opening in a different issue
