### ISSUE TITLE
Add SNMPtrap service

### ISSUE THREAD

**Issue by titilambert** [influxdata/kapacitor#923]
Hello !
I need to add a SNMPtrap service for alerting.
Are you open to this ?
I think about using this lib : https://godoc.org/github.com/soniah/gosnmp which is the same as telegraf.

Thanks for your answer

**Comment by nathanielc** [comment]
@titilambert Are you wanting to generate SNMP traps or collect existing traps?

**Comment by titilambert** [comment]
To generate snmptraps. Does it fit with the roadmap ?

**Comment by nathanielc** [comment]
@titilambert I am only marginally familiar with how SNMP traps work but it seems like it would be similar to adding a new alert handler and service. There are many existing PRs already that do similar work.

**Comment by titilambert** [comment]
PR: #929 
I'm just starting to get it working.
Need some cleanup and templatingx
