### ISSUE TITLE
Alerting issues

### ISSUE THREAD

**Issue by dpoke** [influxdata/kapacitor#940]
i am testing kapacitor v 1.0.0 with influxdb v 1.0.0    

at influx - subscriptions show:

retention_policy	name						mode	destinations
autogen			kapacitor-a2s1b1dd-b66f-423f-b5b5-f9157agg89eb	ANY	[http://localhost:9092]

i verified that cpu usage idle data is getting stored at influxdb ok.

kapacitor shows the task as running:

ID                            Type      Status    Executing Databases and Retention Policies
cpu_alert                     stream    enabled   true      ["alert"."default"]

kapacitor logs shows:

[httpd] 127.0.0.1 - - [24/Sep/2016:05:57:40 +0000] "POST /write?consistency=&db=alert&precision=ns&rp=autogen HTTP/1.1" 204 0 "-" "InfluxDBClient" cd6l98c2-851b-71e6-8536-000000000000 11600
[httpd] 127.0.0.1 - - [24/Sep/2016:05:57:43 +0000] "POST /write?consistency=&db=alert&precision=ns&rp=autogen HTTP/1.1" 204 0 "-" "InfluxDBClient" cf2af3e2-851b-71e6-8537-000000000000 5531
[httpd] 127.0.0.1 - - [24/Sep/2016:05:57:46 +0000] "POST /write?consistency=&db=alert&precision=ns&rp=autogen HTTP/1.1" 204 0 "-" "InfluxDBClient" d0f99e39-851b-71e6-8538-000000000000 12282

nothing is showing as processing:

ID: cpu_alert
Error: 
Template: 
Type: stream
Status: enabled
Executing: true
Created: 23 Sep 16 21:19 UTC
Modified: 24 Sep 16 05:42 UTC
LastEnabled: 24 Sep 16 05:42 UTC
Databases Retention Policies: ["alert"."default"]
TICKscript:
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" < 100)
        // Whenever we get an alert write it to a file.
        .log('/home/user/kapacitor/alerts.log')

DOT:
digraph cpu_alert {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="0"];

from1 [avg_exec_time_ns="0" ];
from1 -> alert2 [processed="0"];

alert2 [alerts_triggered="0" avg_exec_time_ns="0" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="0" ];
}

When I try to record, it just hangs and I have to stop it:

f99fba83-a82a-4c17-90s3-bd1v481974cd    stream  failed    0 B       24 Sep 16 05:38 UTC   

And there is no alerts.log generated.

What do you suggest that I could try to fix this issue?

Thank you.

**Comment by jmmk** [comment]
I ran into something similar. It looks like you are using retention policy `default`, but the default retention policy is actually called `autogen`. Try using `kapacitor define ... -dbrp alert.autogen ...` to register the task.

**Comment by dpoke** [comment]
Yes, that was the problem. Thank you for your response!
