### ISSUE TITLE
Simple count of fields for alert

### ISSUE THREAD

**Issue by shaunwarman** [influxdata/kapacitor#946]
Influx version 1.0.0
Kapacitor version 1.0.0

Sorry for the ask. I seem to have some issues getting the correct count of statuses.

Example:
```
var info = 10
var warn = 30
var crit = 100

stream
    |from()
        .measurement('request')
        .where(lambda: "status" >= 400 AND "status" <= 499)
    |window()
        .period(10m)
        .every(10m)
    |count('status')
        .as('400_count')
    |alert()
         .message('Elevated 4xxs - {{ index .Fields "400_count" }}')
         .info(lambda: "400_count" > info)
         .warn(lambda: "400_count" > warn)
         .crit(lambda: "400_count" > crit)
         .slack()
         .log('/tmp/badrequest.log')
```

I want to get a count of all status codes, but I need to do something similar to `count("field")` Does this look correct?

Edit: worked after restart of kapd.

**Comment by shaunwarman** [comment]
Oddly, I'm getting some weird round numbers that don't reflect what's in grafana or queried in influx. What should have been a test of 40 returned 800. Is this stateful?

**Comment by nathanielc** [comment]
@shaunwarman Could you provide example data that shows the issue you are having?

**Comment by shaunwarman** [comment]
Could my expectations of `|count` be off? It should count the points which should be filtered based on `|where` correct?

Could the timing in the count be off because "Aggregation functions always use the batch time."

**Comment by shaunwarman** [comment]
Thanks @nathanielc for the help..

It looks like influxDB will dedupe data upon queries, but kapacitor won't. So alerts with count could seem inflated. Will switch to a batch approach to get the dedupe benefits from influxDB.
