### ISSUE TITLE
Slack settings should include icon_emoji and username options

### ISSUE THREAD

**Issue by pauldix** [influxdata/kapacitor#958]
Just a little more customization for the Slack messages that get sent.

**Comment by nathanielc** [comment]
@pauldix When you say `username` option do you mean be able to send message to a user by username or configure the username of the Kapacitor slack integration?

The former is already possible via the `channel` option, in Slack a user is just a channel with an `@` in front instead of a `#`

**Comment by pauldix** [comment]
@nathanielc To set the bot so it sends as a user. See https://api.slack.com/methods/chat.postMessage
