### ISSUE TITLE
Getting started on fresh ubuntu 16 environment not working

### ISSUE THREAD

**Issue by RainerW** [influxdata/kapacitor#960]
I followed the getting started guide and some of the tickets here, but it allways hung up when recording.
So i tried it on a fresh install with the same result :

Installed software :
 1. install fresh ubuntu 16
 2. install influxdb_1.0.2_amd64.deb
 3. install telegraf_1.0.1_amd64.deb
 4. install kapacitor_1.0.2_amd64.deb
 5. install grafana_3.1.1-1470047149_amd64.deb (optional)
 6. restart influxdb, telegraf , kapacitor, (grafana)
 7. create tick script from tutorial ( on db telegraf.default )
 8. try recording like tutorial -> but record calls hang, and does not return.

The tick script:

    # kapacitor  show cpu_alert
    ID: cpu_alert
    Error:
    Template:
    Type: stream
    Status: disabled
    Executing: false
    Created: 07 Oct 16 18:44 CEST
    Modified: 07 Oct 16 18:44 CEST
    LastEnabled: 01 Jan 01 00:00 UTC
    Databases Retention Policies: ["telegraf"."default"]
    TICKscript:
    stream
        // Select just the cpu measurement from our example database.
        |from()
            .measurement('cpu')
        |alert()
            .crit(lambda: "usage_idle" < 70)
            // Whenever we get an alert write it to a file.
            .log('/tmp/alerts.log')
    
    DOT:
    digraph cpu_alert {
    stream0 -> from1;
    from1 -> alert2;
    }

I have usage_ide data in the "telegraf" Database, seeing it with grafana and:

    # curl -G 'http://localhost:8086/query?db=telegraf' --data-urlencode 'q=SELECT count(usage_idle) FROM cpu'
    {"results":[{"series":[{"name":"cpu","columns":["time","count"],"values":[["1970-01-01T00:00:00Z",336]]}]}]}

now the record call will hang

     # kapacitor record stream -task cpu_alert -duration 20s

As far as i understand other tickets, this can happen when kapacitor is not receiving events, but i would suggest it is, because "telegraf                      autogen                       cpu                           363" is incrementing and Influx subscriber is enabled.

    #kapacitor stats ingress
    Database                      Retention Policy              Measurement                   Points Received
    _internal                     monitor                       httpd                         116
    telegraf                      autogen                       disk                          366
    _internal                     monitor                       tsm1_filestore                232
    telegraf                      autogen                       mem                           122
    telegraf                      autogen                       system                        122
    telegraf                      autogen                       swap                          122
    _internal                     monitor                       tsm1_cache                    232
    _internal                     monitor                       database                      232
    _internal                     monitor                       runtime                       116
    _internal                     monitor                       shard                         232
    telegraf                      autogen                       processes                     122
    _kapacitor                    autogen                       edges                         310
    _internal                     monitor                       queryExecutor                 116
    _internal                     monitor                       write                         116
    _kapacitor                    autogen                       runtime                       121
    _internal                     monitor                       tsm1_engine                   232
    telegraf                      autogen                       cpu                           363
    _internal                     monitor                       tsm1_wal                      232
    telegraf                      autogen                       kernel                        122
    _internal                     monitor                       subscriber                    348
    _kapacitor                    autogen                       kapacitor                     121
    telegraf                      autogen                       diskio                        610
    _internal                     monitor                       cq                            116
    _kapacitor                    autogen                       ingress                       2819

Also show subscription looks ok:

    SHOW SUBSCRIPTIONS
    telegraf
    retention_policy	name	mode	destinations
    autogen	"kapacitor-42a41dc7-379f-4792-91a8-a33ac5b7cb44"	"ANY"	http://localhost:9092

And the recordings just seem to run forever

    root@b54-infra-influx2:/var/log/influxdb# kapacitor list recordings
    ID                                      Type    Status    Size      Date
    8f96de37-d1f3-42f7-bae3-6f18ee0643ff    stream  running   0 B       07 Oct 16 19:06 CEST
    5679a9d7-8f3e-4972-8cea-152b369dd191    stream  running   0 B       07 Oct 16 18:45 CEST

There is nothing changed in the influxdb, telegraf or kapacitor configuration. They are as is after installing.

Any ideas?

**Comment by nathanielc** [comment]
The task is expecting data from telegraf.default but Kapacitor is receiving data for telegraf.autogen. Updating the task `kapacitor define cpu_alert -dbrp telegraf.autogen` should fix the issue. I'll update the getting started guide to reflect the change in retention policy name.

**Comment by beckettsean** [comment]
fixed by https://github.com/influxdata/docs.influxdata.com/pull/776

**Comment by RainerW** [comment]
column name "Retention Policy", damn, should have realized this. Now it records, thanks.
