### ISSUE TITLE
The command kapacitor record stream -name cpu_alert -duration 20s - just hangs

### ISSUE THREAD

**Issue by nikhilagrl** [influxdata/kapacitor#967]
Kapacitor version - Kapacitor 1.0.2 (git: master 1011dba109bf3d83366c87873ec285c7f9140d34) 
InfluxDB: 1.0.2 :  master	""	"ff307047057b7797418998a4ed709b0c0f346324"	"1.0.2"
Both installed in 1 EC2 Instance.

**kapacitor record stream -task cpu_alert -duration 20
No response - Kapacitor is hung.**

Lot of points received in Kapacitor - example below.
[root@ip-100-109-5-161 influxdb]# kapacitor stats ingress
Database                      Retention Policy              Measurement                   Points Received     
coriolis-qa                   autogen                       coriolis.api.v2.messages.c3a25743-1296-4f9c-920f-8ab6c9f8cc5c.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v1.settings.psstrial185                 
coriolis-qa                   autogen                       coriolis.api.v2.messages.b99c3a52-a8ea-4d68-bc95-05f0e67077d2.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v1.messages.9f8f759b-4448-4dd3-974e-b8367e8f799d.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v2.messages.ad24417f-a01a-49b3-b907-91b5aee6abd9.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v2.analytics.events.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v2.messages.a03a00f2-9f28-4060-b76a-4e386d5aaf19.realm100185                 
coriolis-qa                   autogen                       ec.accountKey.defaultView.timer.realm100197                 
coriolis-qa                   autogen                       coriolis.api.v1.messages.067f81a9-dd42-43b0-b961-48d1bcd4b7d1.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v2.messages.81d7bc3f-fc94-4d8a-9230-770194e9be35.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v2.messages.450d682b-4a28-4e00-abfb-95a657c11b57.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v2.messages.c1e28e43-5b31-4d38-abb3-53665b3cfaec.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v2.messages.3dd47bcb-38a4-43a3-9c6d-fb7761150498.realm100185                 
coriolis-qa                   autogen                       coriolis.api.v1.adminnuke.psstrial197                 
_internal                     monitor                       subscriber                    81536

**Comment by nathanielc** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

A similar question was just asked, I believe you will find the answers there.
