### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by AWinterman** [influxdata/kapacitor#972]
- There's no documentation on the meaning of the "|" character. 
- The CLI has no documentation, and the help command doesn't tell the user how to specify auth credentials.

**Comment by nathanielc** [comment]
@AWinterman The CLI is self documenting. Simply run `kapacitor help` to see the docs. If there are parts that are confusing we would like to address them.

As for the `|` character Here is an excerpt from the docs found [here](https://docs.influxdata.com/kapacitor/v1.2/nodes/batch_node/#chaining-methods-1)

>Chaining methods create a new node in the pipeline as a child of the calling node. They do not modify the calling node. Chaining methods are marked using the | operator.
