### ISSUE TITLE
invalid influxql func mean with field used_percent: invalid field type: <nil>

### ISSUE THREAD

**Issue by YKlausz** [influxdata/kapacitor#977]
Hi all;

Here is my script from an alerting :+1

```
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('mem')
        .groupBy('host')
    |window()
        .period(window)
        .every(window)
    |mean('used_percent')
        .as('mean_value')
    |alert()
         .warn(lambda: "mean_value" >  warn)
         .crit(lambda: "mean_value" >  crit)
         .stateChangesOnly()
         .message('{{ .Level}} Alert for {{ .TaskName }}: at {{ .Time }} on {{ .ID }} value: {{ index .Fields "mean_value" }}' + unit )
```

Timeseries come from influxdb, it turn out that for my measurement 'mem' there is no value for 'used_percent' because two different daemon write in measurement 'mem' in unfluxdb so mu mean function fail .
I tried to add  .where( lambda: "used_percent'" != '' )) => it worked but no alert are triggered .
My purpose is to ignore those timeseries

Do you have an idea ?

**Comment by nathanielc** [comment]
Use the [DefaultNode](https://docs.influxdata.com/kapacitor/v1.0/nodes/default_node/) to set a default value before the mean operation.

**Comment by YKlausz** [comment]
Thank you, now I am wondering something else:
The default value will set a value, so will this value be used in the mean function ?( I think yes)
I have found a little workaround which is to rename the incoming target measurement in order to differentiate them properly.
Before I had two different metrics with commons fields in the same measurement and now I have those metrics in two different measurement

Thank you for your time :)
