### ISSUE TITLE
Starting an empty kapacitord and registering the alerts later is fragile

### ISSUE THREAD

**Issue by rolele** [influxdata/kapacitor#985]
I am running kapacitor in swarm mode.
kapacitord is a running container that I start using: 
```
docker service create 
--name kapacitor 
--network appnet 
-p 9092:9092 
--constraint 'node.labels.monitoring == true' 
--mount type=bind,src=/mnt/glusterfs/kapacitor/kapacitor.conf,dst=/etc/kapacitor/kapacitor.conf,readonly 
kapacitor 
```

This service is quite useless I have to run another service and do a trick to tell swarm that it is not a long running service and when it ends this is normal do not try to restart it (--restart-condition none):
 ``` 
docker service create 
--name kapacitor_tick1 
--network appnet 
--restart-condition none
--constraint 'node.labels.monitoring == true' 
--mount type=bind,src=/mnt/glusterfs/kapacitor/cpu_alert.tick,dst=/root/cpu_alert.tick,readonly
 -w=/root 
-e KAPACITOR_URL='http://kapacitor:9092' 
kapacitor bash -c "kapacitor define cpu_alert -type stream -dbrp telegraf.default -tick /root/cpu_alert.tick && kapacitor enable cpu_alert"
```

Ok so I can include that in my ansible script so everything is fine at startup.
Now I can receive alerts if anything goes wrong.

If for whatever reason the kapacitord container crash, swarm will restart it automatically but the new container will not have the cpu_alert registered anymore. So it will look like everything is ok but it is not

I think a more robust option will be to be able to start kapacitord with some tick scripts included (without using the CLI to register them).

**Comment by nathanielc** [comment]
@rolele Are you preserving the `kapacitor.db` file across restarts? If so then your alerts will be remembered and start when Kapacitor starts back up.

From the looks of it your `mounts` section is saving the specific tick file you want but not the data that Kapacitor stores. By default Kapacitor stores data in `/var/lib/kapacitor` and it should be persisted across restarts or the new instance will act as if its never been started before.

**Comment by rolele** [comment]
This was not clear to me. Thanks a lot. I will try that soon.
I can close this for now.
