### ISSUE TITLE
infludbOut .tag with variables

### ISSUE THREAD

**Issue by schmurfy** [influxdata/kapacitor#987]
I wanted to add a dynamic tag to my data but it seems I can't add expression in them:

``` javascript
|alert()
  .id('{{ .Name }}')
//[...]
|influxDBOut()
//[...]
  .tag('alarm_id', '{{ .Name }}')
```

I removed the non important parts, in that example the alarm id is built as expected but I can't manage to do the same for a tag added in the influxDBOut, is it possible ?

**Comment by abadyan-vonage** [comment]
Same issue, I want to use a tag from the query data when I write back but it seems there is no way to do it.

**Comment by nathanielc** [comment]
@schmurfy @abadyan-vonage You can use the `eval` node to first create the tag, and then write it out to InfluxDB. https://docs.influxdata.com/kapacitor/v1.1/nodes/eval_node/#tags

**Comment by abadyan-vonage** [comment]
@nathanielc, thanks.
I now realize I misunderstood how tagging works in kapacitor.
If I group by the tag in the query, it is automatically grouped by that tag in InfluxDBOut.
So, works for me.
