### ISSUE TITLE
Alert Node should validate Message/ID templates etc

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#990]
Currently if an Alert specifies an invalid template it will not be discovered until it is executed the first time. It would be better of the defining of the task validated the template first.

**Comment by whoAbhishekSah** [comment]
@nathanielc this seems very very old issue. Is it still open to pick?

**Comment by docmerlin** [comment]
@whoAbhishekSah I believe it is no longer a problem.
