### ISSUE TITLE
Kapacitor uses the same default port as Kafka

### ISSUE THREAD

**Issue by rolele** [influxdata/kapacitor#996]
Knowing the popularity of Kafka  I am wondering if it is worth changing the default port 9092 of kapacitor.

**Comment by nathanielc** [comment]
@rolele Thanks for the heads up. At this point we are committed to our 1.0 promise of no backwards incompatible changes, so this change will not be possible. Its simple enough to change the port via the config so it shouldn't be a large barrier in setup even if the same host is running Kafka.
